### ISSUE TITLE
could it be made easier to browse between servers and build a varied feed? 

### ISSUE THREAD

**Issue by dobkeratops** [mastodon/mastodon#19664] opened 2022-11-02 09:23 UTC
### Pitch

I think its too hard to build a varied feed outside of your initial bubble. Following individuals randomly seems hard (and uncomfortable as its usually a signal of specific interest -you're wasting human input by asking a human to randomise) and it takes extra clicks to follow outside of the server after searching for a specific subject 
streamline the with some dedicated inter server UI, or default "out of the box" bots that are configured

ideas - explicit SERVER follows as opposed to just USER follows.
- or make SERVERS automatically  create a random aggregator feed bot that gives a preview, and add UI on a server that lets the admins pin a list of "friends of the server" or "recommended other servers", so new users signing up can quickly see *something* outside the bubble. They might even be best as defaults so you *start* with a varied feed, then unfollow what you dont want.

### Motivation

this will help keep people once they took the step to try it. My experience was that it got boring quickly because my feed was too limited, and I've got other distractions. I really like the federated idea, and I really like the idea of keeping a genuinely distributed alternative going .. but I think most casual internet users (or any power user who is busy) will sadly just gravitate back to  centralised platforms , in its current state

**Comment by sleepyfran** [comment] 2022-11-02 23:51
Seems like a duplicate of #6942

**Closed** 2023-05-20 20:14 UTC
Labels: suggestion
