### ISSUE TITLE
Add the transgender flag to the standard emoji keyboard on the web client 🏳️‍⚧️

### ISSUE THREAD

**Issue by afontenot** [mastodon/mastodon#20621] opened 2022-11-14 04:52 UTC
### Pitch

Currently the emoji keyboard on the web client does not have the transgender flag as a standard emoji. It has the rainbow flag, but not the transgender one.

My server seems to have worked around this by having a *custom* transgender flag emoji, but it is a rather ugly (IMO) low res bitmap with a black outline around it.
![5fa14063388db534](https://user-images.githubusercontent.com/3870410/201577023-5a985fe4-c68a-490d-b509-1f632404fa9d.png)

Seems like it would be a good idea to add the Unicode transgender flag emoji to the keyboard.

(Note: I'm talking about mastodon.social when I say my server. It is on 4.0.0rc3.)

The transgender flag was added in Emoji 13.0, almost 3 years ago, and is already in the SVG sourced emoji font that the web client uses.

### Motivation

🏳️‍⚧️

**Comment by afontenot** [comment] 2022-11-14 04:55
(Actually, more broadly, it looks like many or perhaps all the emoji from Unicode 13+ are missing.)

**Comment by ineffyble** [comment] 2022-11-14 05:04
My understanding is there's a fun bit of code tech debt that's stopping emoji from Twemoji 13 or 14 (which was just added to Mastodon) from showing in the picker.

**Comment by ineffyble** [comment] 2022-11-14 05:08
Duplicate of #18609.

**Closed by ineffyble** 2022-11-14 05:08 UTC
Labels: suggestion
