### ISSUE TITLE
Really avoid duplicated toots on timeline

### ISSUE THREAD

**Issue by JorgeStolfi** [mastodon/mastodon#22856] opened 2022-12-30 16:29 UTC
### Pitch

The same toot should never be displayed twice on the timeline.  Thus it is proposed that a boost  should NOT be displayed on my timeline if 

(1) I follow the author of the original toot,  or
(2) I follow some of the other people who have previously boosted the toot.

Ideally (1) and (2) should take into account the date and time when  I started following the user in question.

### Motivation

Duplicated posts on the timeline are quite annoying and a waste of the reader's time

**Comment by trwnh** [comment] 2023-05-19 06:24
Duplicate of #19665

**Closed by trwnh** 2023-05-19 06:24 UTC
Labels: suggestion
