### ISSUE TITLE
Users should be able to ignore instance silences

### ISSUE THREAD

**Issue by ealgase** [mastodon/mastodon#11218] opened 2019-07-01 00:13 UTC
### Pitch

Allow users to unsilence remote instances or users that have been silenced by their instance.

### Motivation

Many instances silence other instances to prevent their users from being annoyed/harassed/seeing unmarked NSFW.  However, I'd like to be able to disable those protections, without needing to follow every user on those instances.

**Comment by rodti** [comment] 2019-07-17 21:47
Could this be done via the 'Hidden domains' setting for the user?

**Comment by TemporaryUsername12481** [comment] 2019-07-17 22:05
That might work, having the instance's silences be added to that list as "default hidden domains" or the like.

**Comment by trwnh** [comment] 2022-07-27 08:15
Duplicate of #3890

**Closed** 2023-02-21 20:18 UTC
Labels: wontfix, suggestion
