### ISSUE TITLE
Don't show boosts of followed users by others

### ISSUE THREAD

**Issue by ArnonClark** [mastodon/mastodon#22955] opened 2023-01-05 20:12 UTC
### Pitch

Hi folks, I've been noticing that I end up seeing boosted toots of posts from people I already follow, Might there be a way of checking boosted posts against followed users and not displaying these in the timeline? Maybe making it optional if there's a reason I'm not seeing for it, like covering bases to make sure one doesn't miss a popular post by one of your follows?

### Motivation

 Absent QT functionality, this seems like a waste of screenspace and resources, as well as repetitious for the end-user.

**Comment by nemobis** [comment] 2023-01-06 14:41
Duplicate of https://github.com/mastodon/mastodon/issues/19665 https://github.com/mastodon/mastodon/issues/20411 (see also https://github.com/mastodon/mastodon/issues/22383#issuecomment-1367784377 ).

**Comment by trwnh** [comment] 2023-05-19 06:24
Duplicate of #19665

**Closed by trwnh** 2023-05-19 06:24 UTC
Labels: suggestion
