### ISSUE TITLE
End To End Encrypted Direct Messages

### ISSUE THREAD

**Issue by slayernominee** [mastodon/mastodon#23258] opened 2023-01-25 22:37 UTC
### Pitch

Hey I would suggest to add an direct message support like e.g. instagram but with end to end encryption.

my idea is that the user password is used to encrypt an chat password for each conversation or then all, idk 🤷🏼‍♂️ but that chat password is basically the private key for the decryption. This would make it possible by reporting an conversation to also share the secret key in this case for the conversation and make it readable for the admins of the instance. Also it would protect the user password and can be regenerated without changing the user password.

### Motivation

I wanted to answer on one post but the reply as an post didn’t seem matching so I thought a direct message would be better :)

**Comment by ClearlyClaire** [comment] 2023-01-26 08:15
This is a duplicate of #19565.

You can currently reply with a post using the “Mentioned people only” privacy setting, although that is not end-to-end encrypted. We have ideas for E2EE DMs but are still a long way from having them implemented.

**Closed by ClearlyClaire** 2023-01-26 08:15 UTC
Labels: suggestion
