### ISSUE TITLE
Ability to delete a single notification

### ISSUE THREAD

**Issue by koyuawsmbrtn** [mastodon/mastodon#12951] opened 2020-01-25 04:24 UTC
### Pitch

I can delete a single notification for example in Subway Tooter (an Android client for Mastodon) and I would like to do the same in the web interface.

### Motivation

Imagine you get an unwelcoming notification from someone you didn't like so you can just delete the notification and pretend that the person has never messaged you. Out of sight out of mind.

**Comment by Cassolotl** [comment] 2020-01-25 14:17
This is a duplicate of *Clear/hide specific notification #1900*, I think?

**Comment by trwnh** [comment] 2023-05-20 02:58
Duplicate of #1900

**Closed by trwnh** 2023-05-20 02:58 UTC
