### ISSUE TITLE
trying to upgrade to mastodon 4.1.3 but can't pull

### ISSUE THREAD

**Issue by albjeremias** [mastodon/mastodon#25763] opened 2023-07-06 14:49 UTC
### Steps to reproduce the problem

1. edit my docker-compose.yml file 
2. change tag to v4.1.3
3. manifest fails 
4. can't find the tag pushed in https://github.com/mastodon/mastodon/pkgs/container/mastodon/versions?filters%5Bversion_type%5D=tagged&page=2

### Expected behaviour

i expect that the tag is pushed to the docker registry 

### Actual behaviour

it fails to pull the tag

### Specifications

mastodon 4.0.5
docker-compose

**Comment by davidlougheed** [comment] 2023-07-06 14:55
it's still building.

**Comment by KarimGeiger** [comment] 2023-07-06 15:03
You can track the progress here: https://github.com/mastodon/mastodon/actions/runs/5475883545/jobs/9972611758

**Comment by albjeremias** [comment] 2023-07-06 15:06
2 hours for a build? :face_with_head_bandage: jeje. ok ill be back in some hours! already upgraded to 4.0.5 which i believe already has the latest security patch.! thanks for all people! hugs

hate #threads & #twitter 
love #mastodon <3

**Comment by fuomag9** [comment] 2023-07-06 15:28
it's up now @albjeremias

I agree on the time tho, it should not take two hours to build a container...

**Comment by renchap** [comment] 2023-07-06 16:19
We will work on optimising the Docker build. One of the issue is that we are building for 2 archs, and this seems to cause performance issues with Webpack.

Closing this as the 4.1.3 tag is now build and pushed

**Closed by renchap** 2023-07-06 16:19 UTC
Labels: bug
