### ISSUE TITLE
Non-interactable quote

### ISSUE THREAD

**Issue by saschanaz** [mastodon/mastodon#20709] opened 2022-11-14 23:09 UTC
### Pitch

Add a quote feature that only allows direct interaction with the quote but not the post being quoted.

See the below mockup image, where clicking the original post would only serve you the quote as if you clicked elsewhere of the post, not the original one. 

![A mock image of a Mastodon post, where the quoted post is shown as a card and there is no author information but just the text. The only extra information is the timestamp.](https://user-images.githubusercontent.com/3396686/201186654-dfe8b974-998e-4f48-bce5-9b6456361b3f.png)

### Motivation

The biggest problem of the quote feature is that anyone with big amount of followers can abuse their influence to bully other people. If so, what if such followers can't directly interact with the quoted post? What if you can't click the original post from the quote to access it and the original author is not even visible?

With non-interactable quote, one would be able to include the context without exposing the original post to hostile people.

**Comment by ineffyble** [comment] 2022-11-15 05:16
I want to say this is a duplicate of #20673 but there may be some nuance between the two.

**Comment by saschanaz** [comment] 2022-11-15 07:46
That one is more about opting in rather than fixing the problem of quote itself. I don't really want complicating user experience that way...

**Comment by richfelker** [comment] 2022-11-15 20:23
This version undermines most of the things that are good about quoting, particularly that it's a *citation* to give credit to the originator of an idea you're quoting. I can't imagine wanting people to be able to quote you without it being clear that the words were yours, and instead making it look like they were authored by the quoting user. That's pretty much the problem we have now with copy-and-paste quoting. It erases (or at least buries) attribution.

I agree that some people do not want to be quoted because of the potential that quoting be used for harassment (though this should be treated like all other forms of harassment with suspension of accounts of defederation of instances that won't handle abuse if someone repeatedly engages in unwanted quoting to drive harassment), but in any case that's why #20673 proposes to make it opt-in. So that users who are concerned it will be used to harass them can just not opt in.

**Comment by saschanaz** [comment] 2022-11-15 21:19
I see your point, and another point of the copy-paste is that some people just paste the screenshot instead of the text (which is easy too), and that frequently causes a11y issue. And I'm sure people will still try workaround the opt-out, causing the same issue.

I'd like to have an easy method that can at least guide people to more accessible way, not just blocking it.

**Comment by richfelker** [comment] 2022-11-15 21:28
Yes. If there's no QRT, people **will** screenshot to work around that. Probably without alt text. Best case would be that they settle on a browser extension to automatically screenshot and add the alt text, but this would have no protection against unwanted QRT.

The proposal in #20673 to make it opt-in avoids creating a motivation for folks to build nasty screenshot workflows that would not honor the user's choice of whether they want to be quoted and that would be harder to moderate. Certainly bad actors can still screenshot to drive harassment, but then you use the normal reporting and moderation workflow.

**Comment by ell1e** [comment] 2022-11-15 21:33
> The proposal in https://github.com/mastodon/mastodon/issues/20673 to make it opt-in avoids creating a motivation for folks to build nasty screenshot workflows

It might need to be an opt-out for that however, it won't really work in practice unless most people allow it.

**Comment by richfelker** [comment] 2022-11-15 21:41
I would be fine with and prefer opt-out, but I don't want to push for more than what folks would be comfortable with. Either way, though, I think folks who want to participate in a global discourse and have their ideas quoted to spread beyond their own circles would turn it on, and folks who want to be left alone would leave or turn it off. A lot of people who want this *want to be quoted* because our purpose in using social media isn't just to socialize with a circle of friends but to put ideas out there that we hope will expand beyond our own reach and get traction.

**Comment by RockstarRaccoon** [comment] 2022-12-30 08:37
Absolutely against, unless implemented as an opt-in on the account level.  Not simply a dislike, but a level of "This feels _literally criminal_ to me."

If I'm going to quote someone's messages, I'd like it to link back to their account, because this, to me, as someone who writes papers and makes art, feels like a form of content theft: it's putting someone else's words on my profile without giving them credit and a link.  I would be _ESPECIALLY_ uncomfortable, possibly to the point of _actual legal action_, if it were done to me, because, once again, I'm a small content-creator, and that's _content theft._  In the past, I've used things I publish on websites (including Mastodon for the past few years) to generate interest in things that I rely on for income, and when people copy those things to their own profiles with no indication that it came from me, that literally hindered my ability to generate interest and clout that got me art-sponsors and contract jobs.

**Comment by saschanaz** [comment] 2022-12-30 09:37
Thanks for the feedback. Discarding this proposal, since I'm using Misskey nowadays and is leaning to the argument that the full quote is not that harmful by itself.

**Closed** 2022-12-30 09:37 UTC
Labels: suggestion
