### ISSUE TITLE
Request: Add option to filter people you follow from local timeline

### ISSUE THREAD

**Issue by bannisdale** [mastodon/mastodon#8635] opened 2018-09-06 09:18 UTC
I constantly run into the inconvenience that I read a lot of duplicate statuses when I browse both my home timeline and my local timeline. Therefore, I would appreciate an option to filter people I follow from the local timeline. I would imagine it to be another option just like the "only show media" option we already have within the options of the local TL.

Thanks!

**Comment by trwnh** [comment] 2023-05-20 20:02
Duplicate of #8207

**Closed by trwnh** 2023-05-20 20:02 UTC
Labels: suggestion
