### ISSUE TITLE
Ability to share lists 

### ISSUE THREAD

**Issue by innosflew** [mastodon/mastodon#19996] opened 2022-11-07 12:24 UTC
### Pitch

Add the ability to easily share lists and follow other people's lists just like on Twitter.

### Motivation

I think this would come pretty useful for everyone. For example now a lot of academics are coming over from Twitter and having a hard time finding and connecting with other academics. If people were able to share their lists, someone could make a list of academics that people could use for finding and following other academics.

**Comment by ClearlyClaire** [comment] 2022-11-07 14:11
Duplicate of #19882

**Closed by ClearlyClaire** 2022-11-07 14:11 UTC
Labels: suggestion
