### ISSUE TITLE
try to create Account Aliases shows "Something went wrong"

### ISSUE THREAD

**Issue by markusblogde** [mastodon/mastodon#18104] opened 2022-04-26 11:12 UTC
### Steps to reproduce the problem

1. Try to add Account Aliases on Destination
2. Browser opens "Something went wrong" 

### Expected behaviour

Aliases should created

### Actual behaviour

Error shown in Browser

### Specifications

Mastodon v3.5.1

Bundle logs the following:
method=GET path=/settings/aliases format=html controller=Settings::AliasesController action=index status=500 error='ActionView::Template::Error: undefined method `pretty_acct' for #<AccountAlias id: 8, account_id: 1, acct: "xxxx@yyyy.de", uri: "https://yyyy.de/users/xxxx", created_at: "2022-04-26 10:39:47.057880000 +0000", updated_at: "2022-04-26 10:39:47.057880000 +0000">
30:         - @aliases.each do |account_alias|
33:             %td= table_link_to 'trash', t('aliases.remove'), settings_alias_path(account_alias), data: { method: :delete }

**Comment by ClearlyClaire** [comment] 2022-04-26 11:45
This is a duplicate of #18033, this has been fixed in the development branch!

**Closed by ClearlyClaire** 2022-04-26 11:45 UTC
Labels: bug
