### ISSUE TITLE
Propose a new type of post visibility/privacy: mutuals only

### ISSUE THREAD

**Issue by oliviazhaoxu** [mastodon/mastodon#32706] opened 2024-10-30 23:58 UTC
### Pitch

Currently we have 4 types of post visibility: public, quiet public, followers, and specific people. The new type "mutuals only" would behave like a friend circle, and the post will only be visible to people you're mutuals with, i.e., who follow you AND whom you follow back.

### Motivation

While it is nice to control what people can see depending on whether they follow you or not, people sometimes post more personal/private stuff to followers only, and that can influence whether they approve a new follower request or not. Adding this new type can protect user privacy better while also welcoming new friends.

**Comment by trwnh** [comment] 2024-10-31 04:21
Duplicate of #7135

**Closed by trwnh** 2024-10-31 04:21 UTC
