### ISSUE TITLE
Clicking a URL of a toot in the web UI should open the toot in the search area

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#2136] opened 2017-04-19 10:51 UTC
Clicking the URL of a toot like here:

![screen shot 2017-04-19 at 11 49 50](https://cloud.githubusercontent.com/assets/6607512/25176553/60f89896-24f6-11e7-88bc-c98b7eed4a99.png)

... currently opens that URL in a new tab.

It *should* put the URL into the search box and bring up the toot in the search results, like this:

![screen shot 2017-04-19 at 11 50 05](https://cloud.githubusercontent.com/assets/6607512/25176581/7939e7b6-24f6-11e7-89e4-ec5f8439e6ba.png)

At the moment you have to copy and paste toot URLs from toots into the search box in order to repost, reply, interact in any way. I think it could be cool if this process was somewhat automated.

Thanks!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment] 2017-04-19 10:56
How do you get the little checkbox at the bottom of these issues to show as a tick/checkmark? I don't know how so I usually just end up writing "yes"!

**Comment by codl** [comment] 2017-04-19 11:14
`[x]` is how you check those

would mastodon even be able to know which urls point to statuses

**Comment by Cassolotl** [comment] 2017-04-19 11:18
@codl Thank you, re: x!

**Comment by expenses** [comment] 2017-04-20 07:25
Would an appropriate solution be to Oembed the toot?

**Comment by PubliqPhirm** [comment] 2018-08-22 21:38
@expenses That's one of the things that was brought up on the issue Cass listed.  Quote boosts should be straightforward and purely client-side with OEmbed.

**Comment by vibhi19** [comment] 2019-03-25 19:16
> Quote boosts

This will not be added sadly so this is the only solution right now

**Comment by vibhi19** [comment] 2019-03-25 19:16
@Gargron We need this make it possible it in 2.8

**Comment by trwnh** [comment] 2019-03-25 23:17
i'd prefer to have this in the context column rather than in the search results -- in other words, it should fetch the toot if it exists and show it in the far right column with the available replies below it.

**Comment by trwnh** [comment] 2023-01-26 20:47
related to or duplicate of #1399 -- also worth mentioning FEP-e232 Object Links as a way to federate metadata about such links and signal that they can be opened in-app "natively".

**Comment by trwnh** [comment] 2023-05-16 03:26
Duplicate of #1399

**Closed by trwnh** 2023-05-16 03:26 UTC
Labels: ui, suggestion
