### ISSUE TITLE
Allow verification of a site using TXT record in DNS

### ISSUE THREAD

**Issue by aallan** [mastodon/mastodon#20083] opened 2022-11-07 23:28 UTC
### Pitch

Right now the only way to verify your ownership of a website is to add a `rel="me"` link on the page.

<img width="423" alt="Screenshot 2022-11-07 at 23 23 42" src="https://user-images.githubusercontent.com/53625/200436881-0f18cb22-7560-4418-b632-2cb24bb8f314.png">

For many sites which are generated from CMS this is difficult or sometimes impossible.

Another way to verify the site would be to allow us to verify ownership of the domain, perhaps using a TXT record in the DNS of the site. This method is used by other, e.g. [Google](https://support.google.com/a/answer/183895?hl=en).

### Motivation

This would allow more people to verify their websites, and other sites generated from CMS or hosted on third-party services.

**Comment by afontenot** [comment] 2022-11-07 23:42
Dupe of https://github.com/mastodon/mastodon/issues/20030

**Comment by ClearlyClaire** [comment] 2022-11-08 08:42
Closed as a duplicate of #20030

**Closed by ClearlyClaire** 2022-11-08 08:42 UTC
Labels: suggestion
