### ISSUE TITLE
unique posts in timelines

### ISSUE THREAD

**Issue by zh99998** [mastodon/mastodon#8944] opened 2018-10-10 05:17 UTC
now mastodon has three timelines: home, local, global. one post may show in multi columes. when I followed many person, most of posts becomes duplicated. it makes multi columes useless.

![image](https://user-images.githubusercontent.com/359622/46714510-564b5500-cc8e-11e8-80db-1a65ffdf5b97.png)

I suggest to add a feature, before showing a post, check if it's already shown, then don't show it.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment] 2023-05-20 20:03
Duplicate of #8207

**Closed by trwnh** 2023-05-20 20:03 UTC
Labels: suggestion
