### ISSUE TITLE
Don't show copies of my own toots in the timeline

### ISSUE THREAD

**Issue by Oreolek** [mastodon/mastodon#6596] opened 2018-03-02 09:27 UTC
If I'm subbed on someone who decides to reblog my toots, i would see my own text repeated in the timeline back to me.
A notification would be enough, thank you.

**Comment by trwnh** [comment] 2023-05-14 07:01
see also #18955 -- this could be handled by creating a filter targeting yourself in the `home` context

**Comment by trwnh** [comment] 2023-05-14 07:03
Duplicate of #6093

**Closed by trwnh** 2023-05-14 07:03 UTC
Labels: suggestion
