### ISSUE TITLE
Move source to more trustworthy hoster.

### ISSUE THREAD

**Issue by Informeli** [mastodon/mastodon#27468] opened 2023-10-19 07:28 UTC
### Pitch

Move Mastodon to something like codeberg, savanna or even self hosted by the mastodon maintainers.

### Motivation

Github is owned by Microsoft and has already been used to scrape data from the developers on it for github copilot without attribution or permission.
Moving away would mean less people need a github account.

**Comment by vmstan** [comment] 2023-10-20 14:02
Duplicate of #22572

**Closed by vmstan** 2023-10-20 14:02 UTC
Labels: suggestion
