### ISSUE TITLE
Allow for reporting of quote boosts as separate from the underlying post

### ISSUE THREAD

**Issue by quintessence** [mastodon/mastodon#28113] opened 2023-11-28 19:34 UTC
### Pitch

Currently when a user tries to report a quote boost, it reports the underlying post. This assumes that the issue is with the underlying post itself rather than whatever a user is trying to show with quote boost behaviors. 

### Motivation

There are times when a user needs to be able to report the account doing the quote boost and not the original posting account. This can include trying to show bot-like behaviors or other "odd" quote boosts, where it's the interaction that is a problem and not the underlying post by itself. In cases where the underlying post is problematic, it limits the ability to report not only the account that posted the problematic post but also accounts that are boosting / liking it.

**Comment by ThisIsMissEm** [comment] 2023-11-28 19:41
@ClearlyClaire I'm not sure what's causing this observed behavior, since the ReportService and underlying machinery should support reblogs, since they are just statuses (with `reblog_of_id` set, afaik). Could it be a UI issue maybe and not actually an API bug?

**Comment by renchap** [comment] 2023-11-29 14:36
What are you calling a "quote boost"? Do you have an example of such a status?

**Comment by quintessence** [comment] 2023-11-30 21:46
Apologies - I should be calling it just a "boost".  I'll screenshot a boost from Eugen, just because he's a well known account.

<img width="711" alt="Screenshot 2023-11-30 at 13 45 19" src="https://github.com/mastodon/mastodon/assets/3387286/61f278f4-113b-454e-9281-cb49624f1a9a">

I can report the underlying Moose Post, but if what I wanted to report was Eugen boosting the post I cannot report that. The ability to report that is what I'm asking for here. This can help with people boosting harmful content as well as capturing bot behavior.

**Comment by ClearlyClaire** [comment] 2023-12-01 09:53
The backend and API should indeed be able to handle reports of reblogs, but the report UI would require significant rework to achieve this.

**Comment by realpixelcode** [comment] 2024-01-05 13:20
Reporting boosts would be very useful for cases where the boosting user is on a different server than the boosted user and where the two servers have different rulesets (possibly even due to their jurisdictions).

Then, if someone on your home server boosts a remote post that violates the rules of your home server, you can't do much about the original post but you can at least do something about the post being shared “at home”.

Also, some rule violations may be severe enough that even the boosting profiles would need to be punished for them.

**Comment by ThisIsMissEm** [comment] 2024-02-20 00:16
@vmstan This may be a dupe of #13816, but I think this may be the better ticket to keep.

**Comment by trwnh** [comment] 2024-02-20 00:19
Duplicate of #13816

**Closed by trwnh** 2024-02-20 00:19 UTC
Labels: moderation, suggestion, area/web interface

**Comment by ThisIsMissEm** [comment] 2024-02-20 01:21
@trwnh I'd have suggested keeping this one open and closing #13816, since this has more information..?

**Comment by trwnh** [comment] 2024-02-20 01:24
I copied over the relevant information to the other issue; this one has a misleading title and I can't edit titles so I closed this one instead of the other one
