### ISSUE TITLE
extended_description returns 401 error when anonymous user visits the About page

### ISSUE THREAD

**Issue by En3pY** [mastodon/mastodon#22325] opened 2022-12-15 12:09 UTC
### Steps to reproduce the problem

Providing information for unauthenticated users is crucial for the site to work.
When accessing the /about page as an unauthenticated user it returns the page but the "About" section is empty.

Request URL: https://[url]/api/v1/instance/extended_description
Request Method: GET
Status Code: 401 
Referrer Policy: origin

When the user is authenticated, everything works as expected.
![image_2022-12-15_130503131](https://user-images.githubusercontent.com/1427057/207854884-4250635e-8f73-4657-a87b-28c754d54e10.png)

Steps to reproduce:
- Open a private window or clear all cookies
- Go on the /about page

The same goes for /privacy page (which IS A BIG problem).

In addition, if you perform the following:
- Click on Create account
- Click back

All /api calls return 401

![image_2022-12-15_130711087](https://user-images.githubusercontent.com/1427057/207855278-7e3b4079-f826-4477-85af-3f05d9055883.png)

![image_2022-12-15_130744835](https://user-images.githubusercontent.com/1427057/207855389-bff416f0-6d4f-468d-8f13-d66e2c63b83f.png)

In addition to that, 

### Expected behaviour

Contents should be available for users

### Actual behaviour

Privacy information and Instance description is not visible

### Detailed description

As per description

### Specifications

Server:
Mastodon 4.0.2

Client:
Any Browser

**Comment by ClearlyClaire** [comment] 2022-12-15 12:16
Duplicate of #21082 or at least heavily related

**Comment by ClearlyClaire** [comment] 2022-12-15 12:19
Oh, are you using `LIMITED_FEDERATION_MODE`?

**Comment by En3pY** [comment] 2022-12-15 12:26
These are the only settings I set up.
Yes I'd prefer working with limited federation.

AUTHORIZED_FETCH=true
WHITELIST_MODE=true

**Comment by ClearlyClaire** [comment] 2022-12-15 12:28
Yeah, unfortunately, `WHITELIST_MODE` (now `LIMITED_FEDERATION_MODE`) implies that you need to be logged in to see or do anything at all, so that behavior is expected (although it should probably display a specific page rather than try and fail to query all these API endpoints)

**Comment by En3pY** [comment] 2022-12-15 12:29
Ok I will try disabling it waiting for a patch.
Thanks for the hint and the assist on the related case.

**Comment by gaditano66** [comment] 2022-12-17 17:22
I was going to ask the same after installing just now an instance with limited federation mode, but I found this thread. Hoping to receive a patch to resolve these problems.

**Closed** 2023-05-19 06:31 UTC
Labels: bug
