### ISSUE TITLE
Change automatically the theme according to the time of day

### ISSUE THREAD

**Issue by MyNameIsTroll** [mastodon/mastodon#11910] opened 2019-09-21 21:15 UTC
It would be great if there was an option to check to have the theme automatically change according to the time of day.
The light theme during the day and the dark theme at night so as not to tire the eyes.
Ideally, you should be able to choose the daytime hours.

I often change the theme and it's a little painful to have to go through the options every time.

**Comment by mynameismonkey** [comment] 2019-09-22 03:45
As long as it's a user option and not a server option this is a cool idea.

**Comment by norz** [comment] 2019-11-11 09:45
DuckDuckGo does this, and it’s very nice. 😊 
The OS triggers the light/dark theme switch, and DuckDuckGo matches it. 

“**I have my OS set to dark mode. Will DuckDuckGo detect that?**
Absolutely! If you're using the default light theme, DuckDuckGo will match your OS theme automatically!”  

https://spreadprivacy.com/duckduckgo-search-improvements/

**Comment by nrchtct** [comment] 2022-05-03 20:23
Automatic switch between dark and light modes according to time of day (or sunrise/sunset) are by now handled by desktop and mobile operating systems. It would be really nice to have an option to "automatically" switch between dark and light theme according to the OS setting in the web UI. The media query `prefers-color-scheme` is a working draft and is supported by all major browsers. The iOS app has this setting already (Look and Feel > Automatic).

**Comment by haifeng-jin** [comment] 2022-12-21 05:53
Really would like to see this happen. It should not be hard to do. Maybe we can mark this issue as `contribution-welcome`.

The a rough js code should be:
```js
        enableLightTheme();
        if (window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches) {
            enableDarkTheme();
        }
```

**Comment by nshki** [comment] 2022-12-21 16:16
Just wanted to chip in here to say there's a PR for this that's approved and waiting for merge!

https://github.com/mastodon/mastodon/pull/20107

**Comment by haifeng-jin** [comment] 2022-12-22 04:18
@nshki That is amazing! Great work!

**Comment by cassidyjames** [comment] 2023-09-17 19:30
Yeah I think this is ultimately a duplicate of #10976.

**Comment by vmstan** [comment] 2023-11-17 13:24
Closed as duplicate.

**Closed by vmstan** 2023-11-17 13:24 UTC
