### ISSUE TITLE
Please restore display of reply toots in favorite/boost notifications.

### ISSUE THREAD

**Issue by LingGeekRain** [mastodon/mastodon#32324] opened 2024-10-08 20:26 UTC
### Pitch

Up until the most recent update, I could see at a glance in my notifications tab the content of the reply that was favorited or boosted. Now with v4.3.0 all it displays is who it's replying to.

### Motivation

Could you please fix it so that it once again shows the content of the reply so I can see at a glance and not need to click through? The update has made this feature much less convenient.

**Comment by renchap** [comment] 2024-10-08 20:33
Duplicate of #32323

We only display the start of the status, but the cutoff is too harsh when the first line is only the handle of the person you reply to.

**Closed by renchap** 2024-10-08 20:33 UTC
Labels: suggestion
