### ISSUE TITLE
Option for default visibility of replies

### ISSUE THREAD

**Issue by smatthie** [mastodon/mastodon#20563] opened 2022-11-13 12:49 UTC
### Pitch

A separate option to set the default visibility of replies, separate from the visibility of new posts. 

### Motivation

Some people prefer to restrict the visibility to "unlisted" or even "only mentioned" when they reply to a post, in order not to clutter the timelines with replies and have only original posts show up. But it's inconvenient having to remember to do this every time. So there should be an option in the settings, similar to the existing option for default post visibility (which then would only apply to original toots, not replies).

**Comment by trwnh** [comment] 2022-11-13 13:25
Duplicate of #19685

**Comment by smatthie** [comment] 2022-11-13 14:48
Closed as duplicate of #19685 which I didn't find through the search, sorry.

**Comment by dertuxmalwieder** [comment] 2022-11-13 15:21
Still open.

**Closed** 2022-11-14 06:52 UTC
Labels: suggestion
