### ISSUE TITLE
Advanced Web Interface - columns do not fill the width of the screen.

### ISSUE THREAD

**Issue by tlalexander** [mastodon/mastodon#22009] opened 2022-12-03 20:19 UTC
### Steps to reproduce the problem

1. Using firefox or chrome, log in to mastodon and enable the advanced web interface
2. Observe that columns do not fill the screen
3. Dive in to CSS and discover that the correct CSS exists, but is being overridden.

### Expected behaviour

Columns should fill the width of the screen

### Actual behaviour

Columns are a fixed 350px width

### Detailed description

See attached screenshot (content blurred out, developer mode enabled and highlighting the column elements):
![Screenshot from 2022-12-03 11-02-25](https://user-images.githubusercontent.com/1310634/205459873-a76144d6-6afa-43d3-b450-55731c7c9a19.png)
(image description: a screenshot of the mastodon advanced web interface showing columns that do not fill the full width of the screen)

I found that if I uncheck (to disable) the "bad" CSS marked in the image below, then the "good" CSS is enabled, and the columns fill the width of the screen. This leads me to believe this is a bug. I tried to identify the exact line of code that is causing the issue so I could submit a PR, but I am finding that the line numbers listed in the developer window do not seem to me to correspond to the specific lines in question, so I had best not bang my head against the wall.

![Screenshot from 2022-12-03 12-04-10](https://user-images.githubusercontent.com/1310634/205460039-593ccce5-9183-4f3e-9dc1-4001b6ca0417.png)
(image description: a zoomed in screenshot of the relevant CSS properties in the web inspector, with added markings showing the good CSS and the bad CSS that is overriding the good.)

### Specifications

Mastodon v4.0.2+trans_rights-f02cb1c-22326163749
Firefox 107
Ubuntu 22.04

**Comment by wlonkly** [comment] 2022-12-03 21:40
On a narrower window that'll squish the columns rather than allowing horizontal scroll. Maybe there's some responsive-ish behavior by width to prefer fill vs. horizontal scroll? 

for example, with the above css change at roughly portrait tablet size:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/1545955/205463165-f53c914d-d9df-41b8-bc20-87f1381a84cf.png">


(Just happened to notice this bug while looking for something else!)

**Comment by AlanBell** [comment] 2022-12-03 22:32
That looks good to me, with min-width on the columns. They were set to 350 in #9227 but that is a separate thing to the flex setting to use the available space.

**Comment by wlonkly** [comment] 2022-12-03 22:42
I find it a little hard to read, but also the UI escapes its bounding boxes a bit too.

<img width="220" alt="image" src="https://user-images.githubusercontent.com/1545955/205464898-22d8c5b9-8eff-40b1-8811-7135a5489ac5.png">

Oddly my instance doesn't seem to have a min-width of 350? ...ah, #9227 set `width` but not `min-width`. 

With _min_-width of 350, then the suggestion in this issue does make things work in both wide and narrow cases (except the left-side `drawer` element with the toot box could use a tweak as well, it shrinks to nothing before horizontal scrolling starts).

I'm new to the project, and not sure if all three of those issues (flex, min-width, and the drawer width) ought to be handled together?

**Comment by eslerm** [comment] 2022-12-04 05:41
this doesn't work well on ultrawide monitors

I like the current layout

**Comment by AlanBell** [comment] 2022-12-04 10:32
Maybe setting a max-width as well would be a good compromise for a wide viewport with few columns pinned.
I think the drawer (compose column) doesn't need to grow very wide, it can have a min-width of 300 and a max-width of 400.
.column could flex between 300 and 550.

**Comment by tlalexander** [comment] 2022-12-06 21:51
seems reasonable to set a max width to work with ultrawide monitors. what do you think @eslerm ?

**Comment by eslerm** [comment] 2022-12-07 06:30
hi o/ @tlalexander 

A wider width allows more characters-per-line. Currently, column width only changes in mobile mode (under 630px). A changing width causes characters-per-line (and height) to change. That's okay in mobile, but resizing a browser will change the relative position of posts within each column. So, I prefer a set width for non-screen mode.

I like the default characters-per-line. It's a good middle ground for different media. Would a `column width` setting be a good solution for the aims of your proposal? Something admins (or users?) could easily set.

**Comment by AlanBell** [comment] 2022-12-07 10:48
Well I would prefer it to flex, so that if I have two or three columns open they fill the available space, and as I open more columns they still use the available space, but shrink a bit to fit more, until they reach some minimum width at which point horizontal scrolling starts, works out to about 5 columns fitting fine on a 1920 wide viewport before scrolling is required. Things change a bit depending on window size, system font selection and zoom, but that is fine. In general if there is room, columns can relax a bit, and if there isn't room they get tighter before scrolling.

**Comment by eslerm** [comment] 2022-12-07 15:52
The problem with min/max-width is that the position of posts relative to each other changes every time the window is resized. The current fixed width, and other UI choices, prevent that and feel intentional.

If you want posts to take up more screen real estate, changing a set width and zooming feel like a better option.

**Comment by eslerm** [comment] 2022-12-07 16:48
With a `column width` setting you could specify a fixed pixel width or a fixed percentage. Best of both worlds.

**Comment by tlalexander** [comment] 2022-12-08 05:10
When I edit the code in developer mode I can toggle between full width or fixed width. It is true that the number of characters per line changes a bit, but the fixed width does not look any better or more "right" to me than the full width. The difference in number of characters per line does not seem significant on my screen (2650x1440). (I am away from that computer but I will try to share screenshots of the difference when I can.) I like that using the full width fits more posts on my screen. I assume that if I had to zoom the page then I would not actually get more posts on the screen.

I am beginning to think that a good option might be fluid columns by default, with an optional fixed width setting for users with ultrawide monitors or other preferences. I am assuming that 16:9 monitors are most common, in which case I would argue that the slight increase in width looks fine (to me anyway), so that could be a sane default, giving users additional control with an optional fixed width in settings.

I appreciate everyone's contributions here!

**Comment by tlalexander** [comment] 2022-12-16 03:29
So it seems like there are two pieces to this yes?

1. Make a new setting value
2. Make some CSS that has min-width and max-width but will honor the setting value if present.

Seems like folks here know how to do the CSS part. Does anyone know how to make a new setting value?

**Comment by eslerm** [comment] 2022-12-16 15:29
SCSS variables can be set here https://github.com/mastodon/mastodon/blob/main/app/javascript/styles/mastodon/variables.scss

**Comment by nd-** [comment] 2023-11-04 19:28
Any update on this?

**Comment by trwnh** [comment] 2023-12-30 08:45
Duplicate of #11413

**Closed by trwnh** 2023-12-30 08:45 UTC
Labels: bug, area/web interface
