### ISSUE TITLE
GIF upload fails with "Can't create thumbnail"

### ISSUE THREAD

**Issue by madrobby** [mastodon/mastodon#26099] opened 2023-07-20 18:26 UTC
### Steps to reproduce the problem

1. Upload the attached GIF with a new post
![blurX_v1_vs_v2](https://github.com/mastodon/mastodon/assets/3390/219534ec-eec7-40fe-8eda-3ffcbdff2845)

### Expected behaviour

This should work as an image attachment.

### Actual behaviour

It doesn't work, there's an error about that the thumbnail can't be created.

### Detailed description

Some GIFs aren't processed correctly for generating the media thumbnail. I've just created this GIF today in Photoshop.

I have no problem uploading other GIFs, even those that have large filesizes or dimensions.
The GIF also works fine on other social media platforms such as Threads.

### Specifications

This was on hachyderm.io, which currently runs Mastodon v4.1.4.

**Comment by ctalerico** [comment] 2023-08-15 15:39
This one looks like it may be intended behavior.  The error is coming from the app\models\concerns\attachmentable.rb file in the check_image_dimension function, which calculates the matrix size for the above gif as 970 x 990 = 960,300, and which is greater than the GIF_MATRIX_LIMIT set in the same file to 921,600.

![image](https://github.com/mastodon/mastodon/assets/2335724/11d0d2c0-b052-4c1b-b655-340dfbd4cdbf)

**Comment by vmstan** [comment] 2023-11-24 16:19
Closing as fixed, now that the error message has been changed to reflect the GIF file issue, and all attempts to replicate with this file trigger that the file has exceeded the maximum dimension for GIF files.

**Closed by vmstan** 2023-11-24 16:19 UTC
Labels: bug, status/confirmed, area/media processing
