### ISSUE TITLE
Profiles from blocked domains appear in search results 

### ISSUE THREAD

**Issue by matt-y** [mastodon/mastodon#14868] opened 2020-09-27 21:16 UTC
### Expected behaviour

When I choose to block a domain, I am expecting not to see content or profiles from that domain appear when performing a search. 

### Actual behaviour

Blocking a domain removes posts form my federated timeline as desired, but accounts from that blocked domain are still present in my search results. 

### Steps to reproduce the problem

1. Block a particular domain
2. Perform a search that intersects in some way w/ this domain 
    - For instance, a profile from that domain might contain the word you search for
3. observe profiles from that domain in your results 

### Specifications

v3.1.4

**Comment by ThibG** [comment] 2020-09-29 12:17
This is a duplicate of #8586, and should be addressed by #14710.

While I do agree this may be surprising and maybe unwanted, I am unsure about changing this. Indeed, as a user, I may want to check the profile of someone residing on an instance I blocked.

Maybe only allowing exact matches/URL searches for those domains would be a good compromise?

**Comment by SuperSandro2000** [comment] 2020-09-29 13:23
> Maybe only allowing exact matches/URL searches for those domains would be a good compromise?

I like this idea.

**Closed** 2023-05-19 14:22 UTC
