### ISSUE TITLE
Ability to change username

### ISSUE THREAD

**Issue by debbiegoldsmith** [mastodon/mastodon#25256] opened 2023-06-02 19:39 UTC
### Pitch

For people whose username is based on their name, currently if they change their name they either need to live with the old username or go through account migration, with all the issues that entails. It would be very beneficial to these users to be able to just change their username. It's OK if it requires vetting by the instance admin — this kind of thing doesn't need to be self-service.

### Motivation

Many people change their names, most notably trans people. For a trans person, having a username based on their deadname is painful. This is a capability Twitter supports and many trans people have changed their username there as part of the coming-out process (most recently Elliot Page).

**Comment by trwnh** [comment] 2023-06-02 21:26
Duplicate of #15320

**Closed by trwnh** 2023-06-02 21:26 UTC
Labels: suggestion
