### ISSUE TITLE
Soundless notifications

### ISSUE THREAD

**Issue by kayvee2262** [mastodon/mastodon#20151] opened 2022-11-08 18:07 UTC
### Pitch

Looks like if I want any notifications, they have to come with a 'ding' vs just on-screen visual. Can you change that to allow visual without sound? 

### Motivation

Because (believe it or not) when my pups hear the 'ding' they think it means they need to jump around and bark a lot. 
But also because some of us use the site in quiet spaces where a 'ding' is frowned upon and it's hard to remember to mute this one tab when everything else does have soundless notifications (but will cultivate the habit in the meantime!).

**Comment by leo60228** [comment] 2022-11-08 19:31
This is already possible if you click the settings icon in the top-right of the notifications list, I believe.

**Comment by leo60228** [comment] 2022-11-08 19:49
Additionally, I think this is a duplicate of #19691.

**Comment by SamStephens** [comment] 2022-11-10 21:21
> Additionally, I think this is a duplicate of #19691.

I don't think so. #19691 is specifically about notification noises within the web application and their relationship to desktop notifications. This issue more relates to the discoverability of notification settings.

**Comment by SamStephens** [comment] 2022-11-10 21:35
I created #20359 to address how hard it is to find notification settings - please upvote it.

I think this can now be closed as a duplicate of #20359.

**Closed** 2023-05-20 02:53 UTC
Labels: suggestion
