### ISSUE TITLE
Lists of tags

### ISSUE THREAD

**Issue by janEntikan** [mastodon/mastodon#26363] opened 2023-08-06 22:01 UTC
### Pitch

At the moment lists are composed by adding authors/users. I'd like to propose to also curate lists from groups of tags filtered and/or.

### Motivation

At the moment a big problem I found is that niche tags are swamped out by large tags in home feeds. I'd personally also like to be able to see tags that maybe get one or two posts a day. Following both those and tags that receive hundreds of posts a day and you can see how they're very easy to miss. This also makes it harder for those niche tags to gain traction, amplifying the problem exponentially.

**Comment by brendanjones** [comment] 2023-08-09 14:30
Duplicate of https://github.com/mastodon/mastodon/issues/7692

**Closed** 2023-08-12 14:46 UTC
Labels: suggestion

**Comment by janEntikan** [comment] 2023-08-12 14:47
Closing then, as it's a duplicate
