### ISSUE TITLE
Viewing local user profile with full handle (including server name) fails to render

### ISSUE THREAD

**Issue by hexadecimalDinosaur** [mastodon/mastodon#28485] opened 2023-12-23 19:13 UTC
### Steps to reproduce the problem

1. Switch from viewing the page of a local user with shortened URL (*ex. https://mastodon.social/@Gargron*) to URL with lengthened URL (*ex. https://mastodon.social/@Gargron@mastodon.social*)

### Expected behaviour

Web interface should either render the user profile page or redirect to URL with the shortened user handle

### Actual behaviour

Fails to render the page and displays the loading spinner forever

### Detailed description

![image](https://github.com/mastodon/mastodon/assets/36890802/460939cd-d3cb-4381-b3f0-7a9d9d0ff37d)

### Mastodon instance

Tested on [mastodon.social](https://mastodon.social/@Gargron@mastodon.social), [masto.ai](https://masto.ai/@stux@masto.ai), [mstdn.social](https://mstdn.social/@stux@mstdn.social)

### Mastodon version

v4.2.3+pr-28367-d3dbf08 (mastodon.social), v4.2.1 (masto.ai and mstdn.social)

### Browser name and version

Firefox Developer 121.0b4, Vivaldi 6.4.3160.44

### Operating system

Arch Linux

**Comment by vmstan** [comment] 2024-01-01 22:12
Duplicate of #21469

**Closed by vmstan** 2024-01-01 22:12 UTC
Labels: bug, status/confirmed, area/web interface
