### ISSUE TITLE
Allow adding non followed users to lists

### ISSUE THREAD

**Issue by amelandri** [mastodon/mastodon#18485] opened 2022-05-23 08:08 UTC
### Pitch

Currently lists can contain only users that you follow: they are like filters of your main timeline.

Users should be allowed to add non followed accounts to list

### Motivation

Being able to add non followed account to lists would allow users to keep the main timeline clean and organize contents in a better way.

For example, a user could have his main timeline used only for important contacts while having news, gaming and technology accounts relegated to their specific list.

**Comment by trwnh** [comment] 2022-05-23 08:59
Duplicate of #6982

**Closed** 2022-11-02 08:28 UTC
Labels: suggestion
