### ISSUE TITLE
Easily manage multiple accounts

### ISSUE THREAD

**Issue by mrAceT** [mastodon/mastodon#21291] opened 2022-11-21 09:53 UTC
### Pitch

Just imagine, you've been using that other platform in the hope of connecting and social interacting..
Imagine you've got multiple accounts.. a private one, one for your work and an other one for that great hobby..

Wouldn't it be great if you could log into "all" of those accounts.. and that you could switch between them?

PS: why multiple accoumnts? I like to keep some space between work and private, between work and hobby, you understand ;)

### Motivation

Who would benefit from it? Well every one who whats to keep some things separate ;)

**Comment by ineffyble** [comment] 2022-11-21 10:04
Check out https://pinafore.social/ and https://nicolasconstant.github.io/sengi/ for some options here.

**Comment by rbairwell** [comment] 2022-11-21 12:13
Yep, I feel this is already supported by third party apps such as Tusky (Android), https://thedesk.top and many others (some of which are listed on https://joinmastodon.org/apps ).
I can't really imagine how this could function in a "web browser only" scenario by default in a defederated network.

**Comment by mrAceT** [comment] 2022-11-22 09:46
pinafore :  can not add multiple accounts on one instance
nicolasconstant :  started out OK.. but seems more for managing the feeds.. how to start following someone? Hmmmm
thedesk.top : smells like 'nicolasconstant' ?

Is there a third party app that hase the good/intuitive workings of the Mastodon web-version but the ability to swap accounts?

What my suggestion was, be like how you can switch accounts in Twitter:
![image](https://user-images.githubusercontent.com/29061116/203278273-5b71af8a-f708-44c4-b3ca-71fb01201139.png)
I understand that adding an account that's on an other instance is much harder to do, but on the same instance.. that would, in my opinion, be a very useful addition :)

**Comment by alexleonard** [comment] 2022-11-24 09:45
This would be a huge bonus in my mind. Whilst yes, Tusky offers it on Android, there really isn't a clean way to do this in a web browser. And I think the Mastodon app on Android is superior in design to Tusky - so I'd love to be able to manage all my accounts through there if possible. To have a similar approach on the web would be fantastic.

**Comment by mrAceT** [comment] 2022-11-24 09:55
> If we're talking "I can see and swap between multiple accounts on the same instance" then there's overlap with #1405.

In a perfect world I'dd love to be able to switch between accounts on multiple instances too, but it would **score 9 out of 10** when switching between accounts on one instance would be possible.

So, yea, this is for 90% a duplicate of that ticket, well found!

AD: I've read ticket #1405 And when you're an admin and have your won account, and also take a look at the support account if you can help out, easily switching would almost be a necessity, not a feature!

**Comment by mrAceT** [comment] 2022-12-24 09:29
A small update,

I've been using mastodon for a while now, and when one wants to use multiple instances there isn't really much need for switching, as one can simply log in on that instance and add bookmarks.

I now have and admin account, a personal account, a company account, an account to tell about my village and an account for my hobby project.. (on the same instance) switching is a pain.. (also logging out and in sometimes gives a error!?)

So I'dd become a happy camper if one could log in on multiple accounts on the same instance and that somewhere one could choose the different accounts..

**Comment by trwnh** [comment] 2023-05-20 20:24
Duplicate of #380

**Closed by trwnh** 2023-05-20 20:24 UTC
Labels: suggestion
