### ISSUE TITLE
Make it possible to add followed hashtags to lists as well

### ISSUE THREAD

**Issue by joenepraat** [mastodon/mastodon#29961] opened 2024-04-16 12:47 UTC
### Pitch

Please make it possible to add followed hashtags to lists as well. This will make both hashtags and lists more usable.

### Motivation

Right now hashtags are loaded on your home timeline. If you follow more than a few hashtags this home timeline can become very crowded. For accounts we have lists, that can be configured to make posts exclusive to that list, to solve this issue. The same thing would be great with followed hashtags. This would make your home timeline usable again. How exactly this is used (e.g. a list with only hashtags or multiple lists by topic with hashtags and accounts) is of course up to the user.

**Comment by timtfj** [comment] 2024-04-16 14:35
This would be high priority for me. Any time I experiment with following a hashtag I end up unfollowing it very soon afterwards because it floods the home timeline. I'd like to be able to dip in to a set of hashtags at will.

**Comment by renchap** [comment] 2024-04-17 07:17
Duplicate of https://github.com/mastodon/mastodon/issues/7692

**Closed by renchap** 2024-04-17 07:17 UTC
Labels: suggestion
