### ISSUE TITLE
Indication of the copyright for the profile picture and the header

### ISSUE THREAD

**Issue by Lukas2112** [mastodon/mastodon#16746] opened 2021-09-16 11:43 UTC
### Pitch

It is comparable to the indication of the copyright for contributions at the bottom right on Pixelfed.

### Motivation

No longer include copyright information in the header or avatar image itself, if necessary.

**Comment by ClearlyClaire** [comment] 2022-11-08 09:22
Duplicate of #9528

**Closed by ClearlyClaire** 2022-11-08 09:22 UTC
