### ISSUE TITLE
Web client should go back to topic after a comment ist added

### ISSUE THREAD

**Issue by pwFoo** [mastodon/mastodon#8025] opened 2018-07-15 08:14 UTC
At the moment mastodon.social show a empty post form after a comment is added, but it should go back to the current topic / comment I think.

It works fine with Pinafore client (https://pinafore.social). Should be default behavior after comment added.

**Comment by ThibG** [comment] 2018-12-11 18:03
This is a duplicate of #7112, right?

**Closed** 2023-05-14 16:02 UTC
Labels: suggestion
