### ISSUE TITLE
Link previews from Mastodon should show more info with Apple link view

### ISSUE THREAD

**Issue by jaanus** [mastodon/mastodon#20569] opened 2022-11-13 14:15 UTC
### Steps to reproduce the problem

1. Share a link to a post on Mastodon in some system which uses Apple’s [`LPLinkView`](https://developer.apple.com/documentation/linkpresentation/lplinkview) to render link previews
2. Observe the preview that gets rendered

### Expected behaviour

The link preview should have the post content

### Actual behaviour

Link preview only shows avatar of author

### Detailed description

(This issue may well affect also other systems that render previews of web links. I limit my discussion only to Apple LPLinkView because that’s what I’m familiar with.)

Link previews of Mastodon posts aren’t useful. They only show a large avatar of the author, and nothing about the post itself. Here is an example.

Link preview for `https://mastodon.social/@Gargron/109300299959535882` rendered with `LPLinkView` looks like this:

<img width="345" alt="mastodon post preview" src="https://user-images.githubusercontent.com/184253/201526100-72a22d7d-55e5-4c9a-b600-93c27a3c043c.png">

As comparison, link preview for a tweet like `https://twitter.com/joinmastodon/status/1591089671794462720` looks like this, which is much more useful:

<img width="343" alt="twitter preview" src="https://user-images.githubusercontent.com/184253/201526120-fcf4b863-9a45-45eb-b872-b47488fce879.png">

Apple does not disclose how exactly they generate the previews. They definitely crawl the URL, and the preview is probably some combination of OpenGraph content, HTML metadata, and content parsing.

Link previews are powered by the [`LPLinkMetadata`](https://developer.apple.com/documentation/linkpresentation/lplinkmetadata). I give a URL to [`LPMetadataProvider`](https://developer.apple.com/documentation/linkpresentation/lpmetadataprovider) which fetches the link for me and generates the metadata object.

I can inspect the metadata objects in debugger. Here is what the data looks like for the Mastodon post:

<img width="706" alt="mastodon in debugger" src="https://user-images.githubusercontent.com/184253/201526264-b4ee8bd1-6eeb-476b-b29e-6d58f5eac8e0.png">

And here is the same for the Twitter post:

<img width="725" alt="twitter in debugger" src="https://user-images.githubusercontent.com/184253/201526278-be98fa51-4b79-4390-936d-6f72ddfe68f6.png">

You see that the link metadata for the Mastodon post actually contains the Mastodon post content, but for whatever reason, the Apple LPLinkView decides not to render it, and only shows me the author’s avatar.

I am not sure how other link preview renderers behave with Mastodon posts. Maybe it’s only an Apple quirk. Nevertheless, there are quite a few Apple users out there, and many apps use the system-provided link previews. It would be nice to provide more informative previews for Mastodon posts.

### Specifications

Mastodon server version on mastodon.social that was used to fetch the post: v4.0.0rc3

**Comment by connorshea** [comment] 2022-11-13 18:12
It's unfortunate that they don't just use normal opengraph things, since Discord is able to embed toots just fine:

<img width="554" alt="Screen Shot 2022-11-13 at 11 11 57 AM" src="https://user-images.githubusercontent.com/2977353/201537453-b870b1e6-33dc-4112-9407-4602a2a479a5.png">

**Comment by connorshea** [comment] 2022-11-13 18:13
Also, for devs: the best way to reproduce this is via Apple's Messages app, if you have an iPhone/macOS device.

**Comment by connorshea** [comment] 2022-11-13 18:38
Here's Twitter's HTML `<head>` vs Mastodon's, with the stuff that seemed irrelevant stripped out (link tags, script and style tags, android-specific things, fb/google things, etc)

Mastodon:
```html
<meta content="#191b22" name="theme-color">
<meta content="yes" name="apple-mobile-web-app-capable">
<title>Eugen 💀: "I've changed quite a few parts…" - Mastodon</title>
<meta content="Mastodon" property="og:site_name">
<meta content="article" property="og:type">
<meta content="Eugen 💀 (@Gargron@mastodon.social)" property="og:title">
<meta content="https://mastodon.social/@Gargron/109300299959535882" property="og:url">
<meta content="2022-11-07T03:03:41Z" property="og:published_time">
<meta content="I've changed quite a few parts on joinmastodon.org/servers today in response to the feedback from the past week. In detail:

You can now filter by region, type of legal entity, and sign-up speed. Added note about why the topics filter exists. Changed tagline.

&quot;Get on waitlist&quot; has become &quot;Apply for an account&quot; for servers that manually review new sign-ups. Removed total user count from cards." name="description">
<meta content="I've changed quite a few parts on joinmastodon.org/servers today in response to the feedback from the past week. In detail:

You can now filter by region, type of legal entity, and sign-up speed. Added note about why the topics filter exists. Changed tagline.

&quot;Get on waitlist&quot; has become &quot;Apply for an account&quot; for servers that manually review new sign-ups. Removed total user count from cards." property="og:description">

<meta content="https://files.mastodon.social/accounts/avatars/000/000/001/original/dc4286ceb8fab734.jpg" property="og:image">
<meta content="400" property="og:image:width">
<meta content="400" property="og:image:height">
<meta content="summary" property="twitter:card">
```

Twitter:
```html
<meta property="og:site_name" content="Twitter">
<link rel="mask-icon" sizes="any" href="https://abs.twimg.com/responsive-web/client-web/icon-svg.168b89d9.svg" color="#1D9BF0">
<meta name="theme-color" content="#FFFFFF">
<title>Marphy Black on Twitter: "I always felt the most curious alteration made to Gordon's model in Half-Life's Dreamcast port is blahblahblah</title>
<meta content="article" property="og:type" data-rh="true">
<meta description="" name="description" data-rh="true">
<meta content="https://twitter.com/SlappyCromwell/status/1591457037761671168" property="og:url" data-rh="true">
<meta content="Marphy Black on Twitter" property="og:title" data-rh="true">
<meta content="“I always felt the most curious alteration made to Gordon's model in Half-Life's Dreamcast port is blahblahblah”" property="og:description" data-rh="true">
<meta content="https://pbs.twimg.com/media/FhXKLxtXwAM2Do5.jpg:large" property="og:image" data-rh="true">
<meta content="twitter://status?id=1591457037761671168" property="al:ios:url" data-rh="true">
<meta content="333903271" property="al:ios:app_store_id" data-rh="true">
<meta content="Twitter" property="al:ios:app_name" data-rh="true">
```

Interestingly, the primary difference appears to be that Twitter *does not* use og:image unless it's an image embedded into the tweet. So for text-only tweets, it doesn't include an image property. Mastodon uses og:image for toots to represent the user's profile picture.

**Comment by connorshea** [comment] 2022-11-13 19:34
Okay, so after playing around with this for the last while, I'm pretty sure this can't be fixed by Mastodon (unless you do some very cursed things). It's hardcoded so it only works for twitter.

This HTML:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0,viewport-fit=cover">
    <meta property="og:site_name" content="Mastodon">
    <link rel="mask-icon" sizes="any" href="https://abs.twimg.com/responsive-web/client-web/icon-svg.168b89d9.svg" color="#1D9BF0">
    <link rel="shortcut icon" href="//abs.twimg.com/favicons/twitter.2.ico">
    <link rel="apple-touch-icon" sizes="192x192" href="https://abs.twimg.com/responsive-web/client-web/icon-ios.b1fc7279.png">
    <meta name="theme-color" content="#191b22">
    <title>Eugen 💀: "I've changed quite a few parts…" - Mastodon</title>
    <meta content="article" property="og:type">
    <meta description="" name="description">
    <meta content="https://mastodon.social/@Gargron/109300299959535882" property="og:url">
    <meta content="Eugen 💀 (@Gargron@mastodon.social)" property="og:title">
    <meta
      content="“I've changed quite a few parts on joinmastodon.org/servers today in response to the feedback from the past week. In detail:”"
      property="og:description">
  </head>

  <body>
    Foo
  </body>

</html>
```

Gets us this in LinkPreview:

<img width="304" alt="Screen Shot 2022-11-13 at 12 31 09 PM" src="https://user-images.githubusercontent.com/2977353/201540536-9e8c8bca-79a3-4032-894a-a9ac21df5a09.png">


This HTML:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0,viewport-fit=cover">
    <meta property="og:site_name" content="Mastodon">
    <link rel="mask-icon" sizes="any" href="https://abs.twimg.com/responsive-web/client-web/icon-svg.168b89d9.svg" color="#1D9BF0">
    <link rel="shortcut icon" href="//abs.twimg.com/favicons/twitter.2.ico">
    <link rel="apple-touch-icon" sizes="192x192" href="https://abs.twimg.com/responsive-web/client-web/icon-ios.b1fc7279.png">
    <meta name="theme-color" content="#191b22">
    <title>Eugen 💀: "I've changed quite a few parts…" - Mastodon</title>
    <meta content="article" property="og:type">
    <meta description="" name="description">
    <meta content="https://twitter.com/Redistrict/status/1591657489933938689" property="og:url">
    <meta content="Eugen 💀 (@Gargron@mastodon.social)" property="og:title">
    <meta
      content="“I've changed quite a few parts on joinmastodon.org/servers today in response to the feedback from the past week. In detail:”"
      property="og:description">
  </head>

  <body>
    Foo
  </body>

</html>
```

Gets us this in LinkPreview:

<img width="358" alt="Screen Shot 2022-11-13 at 12 33 09 PM" src="https://user-images.githubusercontent.com/2977353/201540608-7cbe4316-69c3-4297-9d5d-bc251277a83a.png">

The ONLY difference is that the `og:url` meta tag was changed to point to a random tweet by Dave Wasserman. I'm fairly certain the special display for tweets onto works for URLs hardcoded to `twitter.com` :|

Maybe we should open a Radar ticket to fix this, or something?

All tested on macOS Monterey 12.6 by just throwing stuff at the wall with basic HTML on a github pages site.

**Comment by ineffyble** [comment] 2022-11-14 01:01
> I'm fairly certain the special display for tweets only works for URLs hardcoded to twitter.com 

Wouldn't surprise me, a lot of platforms handle Twitter in a special way unfortunately.

**Comment by jaanus** [comment] 2022-11-14 07:57
Yes, there seems to be special treatment for Twitter in Apple LinkPreview (as in other platforms too). I’ve seen lots of LinkPreviews from different sites and now that I think of it, Twitter is the only one where the content is expanded. Influencing internal working and special rules inside Apple LinkPreview is beyond the scope of this bug and we can’t expect it to happen.

Nevertheless, even within these constraints, the previews for Mastodon posts could be much more useful, compared to the current one seen above. I made a few more examples.

`https://github.com/mastodon/mastodon/issues/20583`

<img width="342" alt="Screenshot 2022-11-14 at 09 42 55" src="https://user-images.githubusercontent.com/184253/201604168-1890a998-2432-46bf-909f-c1cb10ea27a4.png">

`https://www.bbc.com/future/article/20221103-how-language-warps-the-way-you-perceive-time-and-space`

<img width="344" alt="Screenshot 2022-11-14 at 09 44 06" src="https://user-images.githubusercontent.com/184253/201604256-c6096219-1f36-422b-93c6-d5ce4512433e.png">

Github is especially interesting because they encode a lot of info into the image 🙃 here is the extracted image from that. (Original image URL: `https://opengraph.githubassets.com/ba3a59c4a81dbae2bea65e42a904b82b02fa9320b2d12a3e04ca03d27d59a89d/mastodon/mastodon/issues/20583`)

![20583](https://user-images.githubusercontent.com/184253/201605011-7c262193-2c1c-40aa-946e-fa2bf808d144.png)

Generating the image is cool, but unlikely to be worth the work for Mastodon currently.

What I think would make the most sense for Mastodon is to set up the metadata so that the author’s image does not end up being so big, and the title text is the beginning of the post content, instead of just referring to the author. You often won’t see the full content of the post, but just the beginning would be useful to get a flavor/taste of what the post is about, and deciding whether to tap on the preview to see the full thing.

**Comment by zwaldowski** [comment] 2022-11-19 22:02
From disassembly, I can support the special tweet formatting comes from it detecting specifically Twitter or Sina Weibo URLs. (`+[LPPresentationSpecializations isMicroblogPost:]`)

With that being acknowledged, what should it be doing instead? From the OpenGraph side, how is `og:type = article` alone going to tell you something is a microblog post or a long read? I can imagine that not a lot of implementations are going to do anything with `og:description` because it's so rarely useful. (Outside of microblogs, it's often a marketing description of the entire site, even for a post _on_ the site.)

Maybe it would be additional to throw up [some non-standard attributes](https://en.wikipedia.org/wiki/CURIE) and build support around that, rather than encouraging one-off exceptions.

As others have pointed out, there are likely improvements to be made to the tags as we provide them now.

**Comment by connorshea** [comment] 2022-11-29 01:09
I've submitted a Radar for Apple to hopefully improve the way LPLinkView works, ID FB11832545 in case any Apple employees happen to see this :)

**Comment by czyz** [comment] 2023-01-03 18:13
Based on examination of the html of a twitter post and a mastodon post, I guessed in my closed-as-a-dupe issue #22382 that I suspected Messages is using the og:title and og:image tag information (as well as possibly some other meta tags) and discarding og:description. I wonder if it's possible for Mastodon server to detect the user-agent used by Messages and serve it a special version of the post in which the contents that would go into og:description is stuffed into og:title and og:image is omitted if there's no image in the post? I don't like the idea of serving things wrong as a special case, but I think this is an important case and I don't know how quickly or whether Apple will fix their implementation. A [comment on the closed issue](https://github.com/mastodon/mastodon/issues/22382#issuecomment-1356027787) suggests that Messages isn't the only app that this might fix.

I don't have a dev build of Mastodon up and running to try a test, I suppose maybe I could just put some static HTML versions of twitter and Mastodon posts on my web server and see what tweaks to the opengraph tags (and possibly the `<meta name="Author" content="Publication Name" />` tag) do to links pasted into Apple Messages.

**Comment by ineffyble** [comment] 2023-01-04 00:25
> the contents that would go into og:description is stuffed into og:title

I can't imagine that would look very nice.

**Comment by czyz** [comment] 2023-01-04 01:23
It's what twitter does. If you open up [this link](https://twitter.com/BusinessInsider/status/1603909520056541184) in a browser and then examine the resulting source (getting the contentss of the tweet to display requires javascript), you'll find there's a tag that looks like this:  

`<meta content="“In scathing exit memo, Meta VR expert John Carmack derides the company's bureaucracy: 'I have never been able to kill stupid things before they cause damage.' https://t.co/YAuRQEDRYN”" property="og:description" data-rh="true">`

And when I send that twitter URL to myself via Apple Messages, its preview renders like so, which seems to be using the full contents of that og:title:

![image](https://user-images.githubusercontent.com/345036/210466767-e9e8f750-f938-4766-ab0f-3c5bdfbe9e4a.png)

The og:title tag of "Insider Business on Twitter" appears to be ignored by Messages. It does attribute the tweet in the preview to "Insider Business", so maybe it isn't ignoring og:title but is doing a special-case-for-twitter grep of og:title for `(.+)(?: on Twitter)`.

**Comment by czyz** [comment] 2023-01-04 01:41
Whoa, so I'm totally wrong. There's the og:description right there, not og:title. I'm face-palming right now. 

It remains a mystery to me why URLs to Mastodon posts don't end up with better previews in Messages.

**Comment by thillsman** [comment] 2023-01-26 14:54
> The ONLY difference is that the `og:url` meta tag was changed to point to a random tweet by Dave Wasserman. I'm fairly certain the special display for tweets only works for URLs hardcoded to `twitter.com` :|

I found the same thing. It seems to require a format of `https://twitter.com/x/status/x`. (I shared that here: https://mastodon.social/@thillsman/109739680807358262)

I did the very cursed thing (😂) as a hacky workaround for https://mstdn.link but I'd agree it's improper to update the actual project and the ball's fully in Apple's court for this, unfortunately.

**Comment by jaanus** [comment] 2023-01-27 05:09
> I wonder if it's possible for Mastodon server to detect the user-agent used by Messages and serve it a special version of the post in which the contents that would go into og:description is stuffed into og:title and og:image is omitted if there's no image in the post?

This is not only about Messages. Many other apps use LPLinkView for web previews. Including Mastodon apps. I'm not sure if the user agent for LPLinkMetadata fetcher is always the same, or does it depend on the app.

**Comment by jaanus** [comment] 2023-02-07 07:53
One other tidbit. Link previews for Mastodon posts that contain images are actually really nice, and exactly as expected. The problem is only about the posts with text. Here is a nice LPLinkView of a Mastodon post with images.

You could argue that if the post has both images and text (like this one), it could show some text as well, but that doesn’t matter so much. The images already provide a lot of valuable preview smell.

<img width="667" alt="Screenshot 2023-02-07 at 09 48 53" src="https://user-images.githubusercontent.com/184253/217184394-7d7ee0cb-a699-4133-8048-ed9c7175d94f.png">

**Comment by kamcma** [comment] 2023-02-07 20:52
I'd actually suggest Mastodon should remove the account profile photo header from the markup for links to individual posts, on the logic that the profile photo is per se associated with the _account_, and not individual _posts_ from that account. Until such time as Apple's Link Preview framework properly supports text preview content, when sent/sending a Mastodon post link with no attachments, I'd personally rather see a media-less Link Preview in my Messages, with just the user name and domain text. A giant profile photo (perhaps repeated over and over, if you send multiple links) isn't directly relevant and takes up huge vertical space in the message thread.

**Comment by davidmnelson** [comment] 2023-02-07 21:04
> I'd actually suggest Mastodon should remove the account profile photo header from the markup for links to individual posts, on the logic that the profile photo is per se associated with the _account_, and not individual _posts_ from that account. Until such time as Apple's Link Preview framework supports text preview content generally and not as a special-casing of Twitter, when sent/sending a Mastodon post link with no attachments, I'd personally rather see a media-less Link Preview in my Messages, with just the user name and domain text. A giant profile photo (perhaps repeated over and over, if you send multiple links) isn't directly relevant and unnecessarily takes up huge vertical space in the message thread.

FWIW I like this suggestion because the giant profile photo can create a false impression that the profile photo is the content being shared. The recipient may not realize they are supposed to click on it to read a text-based message.

**Comment by Gargron** [comment] 2023-02-07 21:04
Already removed in main branch.

**Comment by kamcma** [comment] 2023-02-16 20:05
[iOS 16.4 beta 1 may have added Mastodon support to message previews.](https://mastodon.macstories.net/@viticci/109876195940756699)

**Comment by jaanus** [comment] 2023-04-02 05:29
I am closing this as the original reporter, because in iOS 16.4 Apple indeed greatly improved how LPLinkView renders Mastodon previews.

For reference, this is how the link from my original report is now presented.

![image](https://user-images.githubusercontent.com/184253/229333315-5ed1cf7c-5ac0-43fe-910b-7590ee2fc0a6.jpeg)

**Closed** 2023-04-02 05:29 UTC
Labels: bug
