### ISSUE TITLE
ActiveRecord::Encryption::Errors::Decryption app/models/user.rb:280:in `disable_two_factor!'

### ISSUE THREAD

**Issue by lgrn** [mastodon/mastodon#32443] opened 2024-10-13 08:59 UTC
### Steps to reproduce the problem

N/A

### Expected behaviour

User should be able to login

### Actual behaviour

User gets http 500

### Detailed description

For some reason, a user is unable to login. Entering the 2fa just gives a http 500 error. 

When attempting to remove 2fa in the web gui, the following output can be seen logged under the `mastodon-web` service:

```
I, [2024-10-13T08:33:58.670889 #301]  INFO -- : [edc9890a-b076-4b24-af4e-96c81eb0b145] method=DELETE path=/admin/users/8/two_factor_authentication format=html controller=Admin::Users::TwoFactorAuthenticationsController action=destroy status=500 allocations=4714 duration=39.96 view=0.00 db=3.85
E, [2024-10-13T08:33:58.696597 #301] ERROR -- : [edc9890a-b076-4b24-af4e-96c81eb0b145]
ActiveRecord::Encryption::Errors::Decryption (ActiveRecord::Encryption::Errors::Decryption):
app/models/user.rb:280:in `disable_two_factor!'
app/controllers/admin/users/two_factor_authentications_controller.rb:9:in `destroy'
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call'
```

This is worrying, as I expect this indicates that there is an issue with decrypting the relevant user fields via the new 4.3 ActiveRecord functionality.

Since the instance seems to work in general, how can I force-reset these values to something else with valid encryption? I expect that emptying the 2fa and/or password value would work. Another user without 2fa can log in just fine.

How can I enable the user to log in again? I'm fine with wiping the current password/2fa values.

### Mastodon version

v4.3.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: `ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [aarch64-linux]`
- Node.js version: `v22.9.0`

**Comment by lgrn** [comment] 2024-10-13 11:23
I didn't expect it to, but this seems to have worked:
```
tootctl accounts modify [user] --disable-2fa
```
I also tried adding 2fa on my own account where it was previously disabled, and I could enable and login with it successfully, so I assume the workaround is to disable 2fa from the CLI (not the web ui), then re-enable it so it can be encrypted with the correct key.

I'd appreciate any insight on what other fields I should look out for that might be incorrectly encrypted, but for me this is an acceptable workaround since it's a small instance.

**Comment by lgrn** [comment] 2024-10-13 14:13
Ok, so initially I thought this was resolved by running `tootctl accounts modify [user] --disable-2fa but it's not, so this might be the same issue as #32375. Here's my findings so far:

- Two users that DID NOT have 2fa enabled before the 4.3 upgrade have both successfully been able to enable 2fa and use it.
- One user that DID have 2fa enabled before the 4.3 upgrade was unable to log in, but could login after `--disable-2fa` was run -- however, even after this, the user cannot re-enable 2fa without generating an error.

Here's what I can find in the journal for `mastodon-web` for the request that is failing:

```
I, [2024-10-13T12:19:39.424493 #301]  INFO -- : [55d53aee-a049-4122-8712-f37bec9ce5c8] method=POST path=/settings/two_factor_authentication/confirmation format=html controller=Settings::TwoFactorAuthentication::ConfirmationsController action=create status=500 allocations=2558 duration=10.40 view=0.00 db=1.21
E, [2024-10-13T12:19:39.432299 #301] ERROR -- : [55d53aee-a049-4122-8712-f37bec9ce5c8]
[55d53aee-a049-4122-8712-f37bec9ce5c8] ActiveRecord::Encryption::Errors::Decryption (ActiveRecord::Encryption::Errors::Decryption):
[55d53aee-a049-4122-8712-f37bec9ce5c8]
[55d53aee-a049-4122-8712-f37bec9ce5c8] app/controllers/settings/two_factor_authentication/confirmations_controller.rb:18:in `create'
[55d53aee-a049-4122-8712-f37bec9ce5c8] app/controllers/concerns/localized.rb:11:in `set_locale'
[55d53aee-a049-4122-8712-f37bec9ce5c8] lib/mastodon/rack_middleware.rb:9:in `call'
```

So, for some reason 2fa is broken but only for users that previously had 2fa enabled. Regardless of whether this is a migration issue I'm confused as to why disabling and re-enabling 2fa still doesn't work, something seems to make this error sticky per user.

**Comment by ClearlyClaire** [comment] 2024-10-14 07:28
Closing as a duplicate of #32375

**Closed by ClearlyClaire** 2024-10-14 07:28 UTC
Labels: bug, status/to triage
