### ISSUE TITLE
Debian package is necessary.

### ISSUE THREAD

**Issue by matyapiro31** [mastodon/mastodon#3576] opened 2017-06-05 02:20 UTC
<h1>mastodon has no Debian package.</h1>

* * * *

when debian package for mastodon is created, we're able to shrink Dockerfile simply and absorb the difference among version and distribution.

**Comment by aral** [comment] 2017-06-11 10:00
I was just about to open an issue for this also. Having a Debian package would make it exponentially easier to set up your own instance and would result in a considerable rise in the instance count. 

Imagine:

## How to set up Mastodon on Ubuntu (CloudScale.ch, Digital Ocean, etc.)  

1. `sudo apt-get update`
2. `sudo apt-get install mastodon`

**Comment by matyapiro31** [comment] 2017-06-11 10:13
I am expert (but just a few ) of debian package, and maybe it is easy to create for mastodon once, but a package you must maintain takes much time.Can be changed as the way to build be changing.

**Comment by ProgVal** [comment] 2017-06-11 10:21
> maybe it is easy to create for mastodon once

I am not sure about this. Mastodon has 927 nodejs dependencies and 168 ruby dependencies.

**Comment by Gargron** [comment] 2017-06-11 10:23
>Mastodon has 927 nodejs dependencies and 168 ruby dependencies

This is not unusual for a project of this scale. This doesn't stop Gitlab from being a debian/ubuntu package.

Generally for this thread: https://github.com/chef/omnibus

**Comment by matyapiro31** [comment] 2017-06-11 10:42
I think it may **not** contain so many packages in node.js and ruby to assign on the package setting directly.
Those package manager also need editing to specify dependencies.

**Comment by guillaume-uH57J9** [comment] 2017-06-11 11:03
> I am not sure about this. Mastodon has 927 nodejs dependencies and 201 ruby dependencies.

That's good point. I would think twice about installing a package if apt-get asks me "Installing 1128 packages for dependencies. Do you want to continue ? "

Rationalizing nodjs/ruby dependencies in Mastodon (ie reducing their #), or making some of them optional, would go a long way toward packaging.

**Comment by aral** [comment] 2017-06-11 11:10
@guillaume-uH57J9 Use case: I want to install Mastodon on my server.

For the use case of this issue, I don’t really care what the details of the installation are: Could be 1 dependency, could be 1 million dependencies – the beauty of the package is that I don’t have to care. My concern is: can I write a single command, hit OK, and *boom* – a little while later – I have Mastodon installed. Yay! (Much rejoicing, etc.) :)

That said, of course, by all means, please reduce dependencies, etc., if it streamlines the overall process but it’s not a prerequisite for this or the bottleneck that this issue aims to solve. (The bottleneck to new instance adoption is installation complexity and time.) The number of dependencies isn’t really a factor given the tremendous value a package will provide in terms of reducing installation time from hours to minutes – orders of magnitude – and upgrades to a single command.

**Comment by matyapiro31** [comment] 2017-06-11 11:26
Most important role of packaging is to separate the environment for running from the env for building.
Can reduce npm package when running isnt what i know; maybe ruby package is unnecessary then.

**Comment by aral** [comment] 2017-06-11 11:30
@matyapiro31 Again, as far as my use case for this goes (and I’m happy to open a separate issue if you feel I’m hijacking your use case) :) the most important reason for this is to reduce installation time on the most popular hosting platforms (Ubuntu-based) from hours to minutes (an order of magnitude change that will impact instance adoption rates substantially) and maintenance to a single command. If there are any advantages for developers, that’s an additional bonus but my concern here is in encouraging instance adoption.

**Comment by matyapiro31** [comment] 2017-06-11 11:37
For example, http-server is convenient package for testing, but not necessary when run:
```
$ npm install -g http-server
```

Mastodon doesn't use http-server , but there are package installed for similar reason.

**Comment by matyapiro31** [comment] 2017-06-11 14:02
@Gargron could you list up what packages are used now?

**Comment by Gargron** [comment] 2017-06-11 15:06
I do not want to list or justify Mastodon's runtime dependencies. We do not try to make the project bigger on purpose, and everyone who is contributing to the codebase sees that we need the dependencies that we are using. What you are describing ("convenient package for testing, but not necessary when run") is already covered by environments: development, test, production. Dependencies are already sorted accordingly, and production dependencies do not include anything which is not used in production.

You also shouldn't worry about them, I think. What all of these "packaging" tools do, they manage system packages (think postgres, redis, node, protobuf). Ruby and Node dependencies still get installed the usual way, with no difference to manual installation. For a list of system dependencies, look at the production guide: <https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md#general-dependencies>

**Comment by ProgVal** [comment] 2017-06-11 16:00
> everyone who is contributing to the codebase sees that we need the dependencies that we are using

I think some of them could be avoided.
I am not very good at Javascript, but I think the dependency on `classnames` could be removed, for example.

It was added in 860ffc05602b148769b87d0cda39985feb9a8486, apparently just to replace `button ${this.props.secondary ? 'button-secondary' : ''} ${this.props.block ? 'button--block' : ''}` by:

```
classNames('button', this.props.className, {
      'button-secondary': this.props.secondary,
      'button--block': this.props.block,
    })
```

I know it is a small dependency, but I think it is possible to remove at very little cost.

**Comment by matyapiro31** [comment] 2017-06-11 18:27
maybe [this](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mastodon-git) helps us to create a package.

plus:
[/Aptfile](https://github.com/tootsuite/mastodon/blob/master/Aptfile) and [/Vagrantfile](https://github.com/tootsuite/mastodon/blob/master/Vagrantfile) can be reduced by writing dependencies.

**Comment by matyapiro31** [comment] 2017-06-15 15:07
@Gargron Finally, you think package is necessary?

**Comment by akuckartz** [comment] 2017-06-20 19:24
:+1:

**Comment by guillaume-uH57J9** [comment] 2017-06-25 17:23
> I don’t really care what the details of the installation are: Could be 1 dependency, could be 1 million dependencies

Some users might not care, and it won't change much at installation time. 

But for package maintainers this is day and night. Packaging an application + 1 dependency, and maintaining them, is a relatively simple/quick task. 
Packaging 1 application + 1 billion dependencies (and maintaining them) cannot be accomplished by one person. It'd require a whole team.

**Comment by Jehops** [comment] 2017-07-29 16:54
For the [FreeBSD package](http://www.freshports.org/net-im/mastodon/) we punted on the node dependencies.  All the OS and ruby/rails dependencies are covered with `pkg install mastodon`, but then the user still has to do, e.g., `sudo su - mastodon; yarn install; RAILS_ENV=production rails assets:precompile`.  Doing the job of npm/yarn is too ambitious (for me) at this point; we would have to bake a similar infrastructure we have for dealing with ruby packages into the FreeBSD ports/package system.

While it's not a perfect package, most of the feedback I have received from Mastodon administrators running FreeBSD has been positive.

**Comment by Gargron** [comment] 2017-07-29 19:23
@Jehops I actually don't really understand why bundler and yarn dependencies cannot be bundled in the package. There is literally no chance that running `bundle install` or `yarn install` will yield a different result *unless* the Mastodon lockfiles change (e.g. in a new release). That's the exact purpose of lockfiles - reproducible, deterministic bundling.

**Comment by Jehops** [comment] 2017-07-29 20:34
@Gargron, for each rails dependency, there is one-to-one correspondence with a FreeBSD port/package and each of those FreeBSD ports/packages handles dependencies.  Basically, the FreeBSD port/package system is used in place of bundler.  That that sort of solution for the yarn dependencies would be nice, but a lot of work.  It may be feasible in the short term to make one omnibus mastodon-yarn-dependencies package.

**Comment by matyapiro31** [comment] 2017-07-30 03:47
@Gargron mastodon's package usage design is not better to manage package.
We are forced to use newer version of node, ruby, yarn etc than which in distribution packages.
It makes us very complicated to control mastodon package.
There are at least 5 package varieties:
    native packages for mastodon,npm packages,
    gem packages, native package for gem,
    native packages in sub repositories,
and we must check if those packages has bad affect on other packages, this is the reason why very difficult to maintain package.

**Comment by matyapiro31** [comment] 2017-10-11 05:07
I now somehow understand how mastodon works, however it's still very difficult to create debian package.

Mastodon depends on many software that is not packaged correctly for debian. Supplying these packages with appropriate update is very difficult.

**Comment by themusicgod1** [comment] 2017-11-20 19:00
1) FYI there is a RFP for this on debian's side  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=859741

2) "Mastodon depends on many software that is not packaged correctly for debian" If anyone has identified any of these packages, either this thread or the thread I linked to above would be appropriate places to mention them so we can start filing RFPs and getting those packages in debian, too.

3) "these prerequisites change all the time" That's the whole point of debian - to have a stable basis of development, something that we can actually audit and a known 'good state' that we can build from in case someone puts showstopper bugs in.

**Comment by ProgVal** [comment] 2017-11-20 19:21
> If anyone has identified any of these packages, either this thread or the thread I linked to above would be appropriate places to mention them so we can start filing RFPs and getting those packages in debian, too.

Ruby:
* [ ] source ->  ruby-method-source, ruby-source-map ??
* [x] ruby -> ruby
* [x] pkg-config -> ruby-pkg-config
* [x] puma -> puma
* [x] rails -> ruby-rails
* [x] uglifier -> ruby-uglifier
* [ ] hamlit-rails
* [x] pg -> ruby-pg
* [ ] pghero
* [ ] dotenv-rails
* [x] fog-aws -> ruby-fog-aws
* [x] fog-core -> ruby-fog-core
* [x] fog-local -> ruby-fog-local
* [x] fog-openstack -> ruby-fog-openstack
* [ ] paperclip
* [ ] paperclip-av-transcoder
* [ ] active_model_serializers
* [x] addressable -> ruby-addressable
* [ ] bootsnap
* [x] browser -> ruby-browser
* [ ] charlock_holmes
* [ ] iso-639
* [ ] cld3
* [x] devise -> ruby-devise
* [x] devise-two-factor -> ruby-devise-two-factor
* [x] doorkeeper -> ruby-doorkeeper
* [ ] fast_blank
* [ ] goldfinger
* [x] hiredis -> ruby-em-hiredis, ruby-em-hiredis-doc, ruby-hiredis, ruby-hiredis-dbgsym
* [x] redis-namespace -> ruby-redis-namespace
* [x] htmlentities -> ruby-htmlentities
* [x] http -> ruby-http
* [ ] http_accept_language
* [ ] httplog
* [ ] idn-ruby
* [x] kaminari -> ruby-kaminari
* [ ] link_header
* [x] mime-types -> ruby-mime-types, ruby-mime-types-data
* [x] nokogiri -> ruby-nokogiri
* [ ] nsa
* [x] oj -> ruby-oj
* [ ] ostatus2
* [x] ox -> ruby-ox,
* [x] pundit -> ruby-pundit
* [x] rabl -> ruby-rabl, ruby-rabl-rails
* [x] rack-attack -> ruby-rack-attack
* [x] rack-cors -> ruby-rack-cors
* [ ] rack-timeout
* [x] rails-i18n -> ruby-rails-i18n
* [ ] rails-settings-cached
* [x] redis -> ruby-redis
* [ ] mario-redis-lock
* [x] rqrcode -> ruby-rqrcode
* [x] ruby-oembed -> ruby-oembed
* [x] sanitize -> ruby-sanitize
* [x] sidekiq -> ruby-sidekiq
* [ ] sidekiq-scheduler
* [ ] sidekiq-unique-jobs
* [ ] sidekiq-bulk
* [x] simple-navigation -> ruby-simple-navigation
* [ ] simple_form
* [x] sprockets-rails -> ruby-sprockets-rails
* [ ] strong_migrations
* [x] twitter-text -> ruby-twitter-text
* [ ] tzinfo-data
* [ ] webpacker
* [ ] webpush
* [ ] json-ld-preloaded
* [ ] rdf-normalize

nodejs:
* [ ] babel-plugin-preval
* [ ] postcss-smart-import
* [ ] webpack-merge
* [ ] axios
* [ ] autoprefixer
* [ ] babel-plugin-transform-react-remove-prop-types
* [ ] substring-trie
* [ ] babel-plugin-syntax-dynamic-import
* [ ] dotenv
* [ ] react-textarea-autosize
* [ ] cross-env
* [x] rimraf -> node-rimraf
* [ ] emoji-mart
* [ ] array-includes
* [ ] react-redux-loading-bar
* [x] mkdirp -> node-mkdirp
* [ ] react-router-scroll-4
* [ ] postcss-loader
* [ ] font-awesome
* [ ] react-immutable-proptypes
* [ ] react-overlays
* [ ] react-redux
* [ ] babel-plugin-transform-runtime
* [ ] prop-types
* [ ] react-motion
* [ ] http-link-header
* [ ] node-sass
* [ ] intl
* [ ] webpack-bundle-analyzer
* [ ] object-fit-images
* [ ] sass-loader
* [ ] offline-plugin
* [ ] babel-plugin-transform-decorators-legacy
* [ ] intl-messageformat
* [ ] postcss-object-fit-images
* [ ] react-hotkeys
* [x] escape-html -> node-escape-html
* [ ] resolve-url-loader
* [ ] babel-preset-env
* [x] npmlog -> node-npmlog
* [ ] webpack
* [ ] babel-plugin-transform-react-inline-elements
* [ ] babel-plugin-lodash
* [ ] babel-plugin-transform-react-jsx-self
* [ ] immutable
* [ ] tiny-queue
* [ ] redux-immutable
* [ ] classnames
* [ ] babel-loader
* [x] is-nan -> node-number-is-nan
* [x] uuid -> libjs-node-uuid, node-node-uuid
* [x] express -> node-express, node-express-generator, node-spdx-expression-parse
* [ ] react-dom
* [ ] webpack-manifest-plugin
* [ ] path-complete-extname
* [x] lodash -> node-lodash, node-lodash-compat, node-lodash-packages, node-lodash-reescape, node-lodash-reevaluate
* [ ] babel-plugin-react-intl
* [ ] style-loader
* [ ] react-intl
* [ ] react-toggle
* [ ] pg
* [ ] detect-passive-events
* [ ] requestidlecallback
* [x] redis -> node-node-redis
* [ ] babel-plugin-transform-class-properties
* [ ] stringz
* [ ] reselect
* [ ] extract-text-webpack-plugin
* [ ] compression-webpack-plugin
* [ ] redux
* [ ] babel-plugin-transform-object-rest-spread
* [ ] react-notification
* [x] js-yaml -> node-js-yaml
* [ ] css-loader
* [x] glob -> node-extglob, node-glob, node-glob-base, node-glob-parent, node-glob-stream, node-global-modules, node-global-prefix, node-globals, node-globule, node-is-extglob, node-is-glob, node-is-negated-glob, node-is-valid-glob, node-parse-glob, node-to-absolute-glob
* [ ] mark-loader
* [ ] websocket.js
* [x] punycode -> node-punycode
* [ ] redux-thunk
* [ ] intersection-observer
* [ ] react-swipeable-views
* [ ] babel-plugin-transform-es2015-modules-commonjs
* [ ] throng
* [ ] react
* [ ] es6-symbol
* [ ] babel-plugin-transform-react-jsx-source
* [ ] rails-ujs
* [ ] uws
* [ ] react-router-dom
* [ ] marky
* [x] object-assign -> node-object-assign, node-object-assign-sorted
* [ ] intl-relativeformat
* [ ] react-immutable-pure-component
* [ ] babel-core
* [ ] babel-preset-react
* [ ] precss
* [ ] file-loader

**Comment by themusicgod1** [comment] 2017-11-20 20:53
Things you can check off (at least for sid) babel-core https://packages.debian.org/hu/sid/node-babel-core

**Comment by narcisgarcia** [comment] 2022-01-24 08:29
What about dependencies when upgrading Mastodon without .deb package?

**Comment by limdingwen** [comment] 2022-12-03 09:54
FYI A package exists for [Arch Linux](https://aur.archlinux.org/packages/mastodon) and [NixOS](https://search.nixos.org/packages?channel=22.11&show=mastodon&from=0&size=50&sort=relevance&type=packages&query=mastodon).

**Comment by narcisgarcia** [comment] 2023-01-05 09:01
There are diverse options for this: Request for package at official Debian repositories (examples: wordpress, mediawiki), create a self or hosted APT repository (examples: gpxsee, WineHQ, Skype, Gitlab, Jitsi), and publish simple .deb package (example: Skylobby, Adobe reader, Gigablast).

These three options do not exclude between them, as they can be steps to reach the best final situation (1.package, 2.self-repo, 3.Debian-repo).

**Comment by laszlovl** [comment] 2023-03-01 11:13
I created a Github workflow that compiles Mastodon from source, packages it as a deb then publishes that deb as a release asset: https://github.com/laszlovl/mastodon-build

Note that installing this package just places the compiled version of Mastodon in `/opt/mastodon`, it doesn't provide configuration or start any services (it was meant for use with https://github.com/laszlovl/mastodon-ansible-scalable)

**Comment by matyapiro31** [comment] 2023-03-18 07:39
Debian packages are very complicated, it's not just writing shell script to install. It's not pacman, Debian is not Arch Linux.
Making a Debian package has many rules, many script, many tests.
If mastodon provides package, it should provide complete settings in 1 step installation.

**Comment by narcisgarcia** [comment] 2023-03-19 07:52
First step is to package files without scripts and only taking care of separating local settings files from default packaged files. Many server software is packaged without completing settings in 1 step installation: Dovecot, Mailman, etc.

The right alternative to packaging is to deploy software as a standard CMS being possible to install it through FTP and not CLI, same as Wordpress.

**Comment by MarcusWolschon** [comment] 2023-04-08 10:36
> I was just about to open an issue for this also. Having a Debian package would make it exponentially easier to set up your own instance and would result in a considerable rise in the instance count.
> 
> Imagine:
> ## How to set up Mastodon on Ubuntu (CloudScale.ch, Digital Ocean, etc.)
> 
>     1. `sudo apt-get update`
> 
>     2. `sudo apt-get install mastodon`

Not just to set up.
It would make it feasable to **maintain a host for years** for the administrator. 
Move to a new host, do desaster-recovery or otherwise set up an entire server again.

Mastodon is not the only service offered on the host, but the only one that is not in the package-management.
Thus doesn't automatically get checked for regular updates or security relevant updates.

**Comment by MarcusWolschon** [comment] 2023-04-08 10:42
> What about dependencies when upgrading Mastodon without .deb package?

You don't.
You really, really don't.
Managing dependencies, maintaining all configuration as per the proper FHS 
(so it is backed up and restored by the admin along with all other services of the host)
and informing about updates with special emphasis on security relevant upates is the very job of a package management.

I don't even consider setting up a Mastodon instance unless there is a maintained Debian package.
Without, it doesn't play well with Main-, Web-, Database-, file hosting-, ... services on the same host.

**Comment by sjlongland** [comment] 2023-07-06 01:13
My grievance here is the system requirements needed to _compile_ Mastodon, are orders of magnitude greater than that for it to run.

I run my own instance, on a VM that runs on my own hardware.  The host is near maxxed out with RAM, and buying RAM for these machines is not as easy as "go down the shop".  I have as much allocated to this VM as I can practically manage right now.  At run-time, it works fine.

I find in particular, the usual build steps barf when I try to build the front-end assets.  I have to `rsync` the work tree back to another machine, re-run the same steps there, then `rsync` the results back.

To say this is messy and error prone is an understatement.

What are my options?

- Suck it up and buy more RAM… shut everything down to perform the hardware update, then resize the VM -- lots of stuff-around for one service that doesn't use the RAM 99% of the time, an expensive waste!
- Move Mastodon into a container (Docker perhaps) that I can build elsewhere then deploy -- additional overhead involved here
- Move to something other than Mastodon

As an instance admin, I really don't care if the "Debian package" is little more than a pre-compiled tarball that I can unpack somewhere, `rsync` over-the-top (with `--exclude` calls to preserve critical files), then re-start some services.  That would be 100% better than what we have now.

**Comment by CyberTailor** [comment] 2023-11-25 15:00
Prebuilt web assets (published in Releases) would be a nice addition

**Comment by renchap** [comment] 2024-04-18 21:29
Closing this as we do not plan to support a Debian package ourselves.

If the community (or a Debian maintainer) wants to provide one they can, but our recommended way of deployments are either from git, or through our official container image.

**Closed by renchap** 2024-04-18 21:29 UTC
Labels: deployment, suggestion

**Comment by MarcusWolschon** [comment] 2024-05-08 17:30
> Unlike @renchap closing tag, developers and implementers should go to https://github.com/laszlovl/mastodon-build to continue this subject.

That one downloads and builds the source code.
That's not a Debian binary package and doesn't name or manage it's dependencies.
So it needs to be re-build every single time any package on the server is updated because it could be a dependency.


Looking for some other server that speaks ActivityPub.
Something that runs in a LAMP environment perhaps.
Mastodon just doesn't seem to be for people who don't want to have to maintain, backup, restore and operate services that build their own parallel universes away from the existing dependency management.

**Comment by CyberTailor** [comment] 2024-05-08 17:40
@MarcusWolschon i suggest trying snac2 or honk, they are very minimal ActivityPub servers written in C

**Comment by narcisgarcia** [comment] 2024-05-08 18:15
> That one downloads and builds the source code. That's not a Debian binary package and doesn't name or manage it's dependencies. So it needs to be re-build every single time any package on the server is updated because it could be a dependency.

laszlovl's mastodon-build is a project to do what it says.
Sure you can help developer to complete package's features. As you've seen, mastodon project is not packaging it for Debian; then "mastodon-build" is a project started to rach this goal. **IT'S THE RIGHT DIRECTION ABOUT THIS THREAD SUBJECT**.

...or maybe you are only looking for "free as in beer" software with everything already made to satisfy Github visitor.

**Comment by MarcusWolschon** [comment] 2024-05-30 08:23
> > That one downloads and builds the source code. That's not a Debian binary package and doesn't name or manage it's dependencies. So it needs to be re-build every single time any package on the server is updated because it could be a dependency.
> 
> laszlovl's mastodon-build is a project to do what it says. Sure you can help developer to complete package's features. As you've seen, mastodon project is not packaging it for Debian; then "mastodon-build" is a project started to reach this goal. **IT'S THE RIGHT DIRECTION ABOUT THIS THREAD SUBJECT**.
> 
> ...or maybe you are only looking for "free as in beer" software with everything already made to satisfy Github visitor.

I'm busy maintaining other software and will not host and administer services on my server for my users that doesn't play nice with the dependency management of everything else on that box.
Therefore no Mastodon as ActivityPub implementation for me.
