### ISSUE TITLE
android client crashes when reopening another image for a post

### ISSUE THREAD

**Issue by muzikelretifhbr** [mastodon/mastodon#23300] opened 2023-01-29 18:48 UTC
### Steps to reproduce the problem

1. click white button to open prompt to create new post
2. click attach image button on bottom left of screen
3. select image and attach to post
4. repeat steps 2 and 3
5. client crashes

### Expected behaviour

a second image should be uploaded or the original image should be replaced

### Actual behaviour

client crashes

### Specifications

Mastodon for Android v1.1.4 (45)
server is @mastodon.social
Phone is Galaxy S20 5G
Android version 13

**Comment by olekstomek** [comment] 2023-01-29 23:19
https://github.com/mastodon/mastodon-android/issues/522#issuecomment-1407798909

**Comment by ClearlyClaire** [comment] 2023-01-30 08:52
Closed as duplicate of the https://github.com/mastodon/mastodon-android/issues/522

Please use https://github.com/mastodon/mastodon-android/ to file bugs against the Android app!

**Closed by ClearlyClaire** 2023-01-30 08:52 UTC
Labels: bug
