### ISSUE TITLE
[Feature request] Optional possibility to adjust the limit of the length individually

### ISSUE THREAD

**Issue by scroom** [mastodon/mastodon#6388] opened 2018-01-30 17:53 UTC
I think it would be great for the admins if there was an option in the admin settings to adjust the length limit of the toots for their instance. At the moment this is only possible if the Ruby code is adjusted, which has to be done after every update.
This change would certainly lead to greater diversity. But I welcome diversity.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment] 2018-01-30 21:40
This is a duplicate of #5693, in which it turns out (sadly!) that Gargron is against this feature. https://github.com/tootsuite/mastodon/issues/5693#issuecomment-345485028

**Comment by trwnh** [comment] 2023-05-14 00:21
duplicate of #5693

**Closed by trwnh** 2023-05-14 00:21 UTC
Labels: suggestion
