### ISSUE TITLE
API : Add only_media filter to lists

### ISSUE THREAD

**Issue by Gyoo** [mastodon/mastodon#28635] opened 2024-01-07 14:46 UTC
### Pitch

Disclaimer: The only similar issue I've found is #22045 but it's very old and doesn't include a lot of details. Apologies in advance if this has been talked about elsewhere I couldn't find.

The only_media filter is available for several API calls, such as the public timeline, a hashtag timeline or an account's statuses. However, this is not available for lists.

### Motivation

A lot of people, including myself, use lists to track artists and their work. However, when you start to have a lot of artists in your list, the list timeline is crowded with messages that don't include media, and it becomes more difficult to find actual art.
I couldn't find any client that handles it on their side so far, and even had [a discussion with Phanpy's developer](https://github.com/cheeaun/phanpy/issues/391) who told between the lines that he'd rather have a backend filter for that than filtering after the call is made.

It would be a nice quality of life feature for people who have extensive use of lists for similar cases as mine.

**Comment by Shanesan** [comment] 2024-04-03 19:56
I want to mention that #21219 also suggests this, and it [has been a part of Misskey](https://mastodon.tails.ch/@shanie/111148779901158159) for a while now.

**Comment by trwnh** [comment] 2024-04-04 10:05
Duplicate of #21219

**Closed by trwnh** 2024-04-04 10:05 UTC
Labels: api, suggestion
