### ISSUE TITLE
Not receiving email confirmation

### ISSUE THREAD

**Issue by ivaaane** [mastodon/mastodon#31920] opened 2024-09-15 12:26 UTC
### Steps to reproduce the problem

1. try to make an account in toki.social having a gmail account
2. click 'send confirmation email' many times
3. nothing received (i've looked in spam)
4. can't find anything online

### Expected behaviour

I should've received an email confirmation

### Actual behaviour

I didn't receive an email confirmation

### Detailed description

I tried to make an account in toki.social, but the confirmation email didnt came (I looked at spam). It's been two days, and I can't find any help. All I know, talking with other people in Discord, is that this problem also happened to other people trying to make an account in this instance, and apparently the problem is having Gmail as the email service.

### Mastodon instance

toki.social

**Comment by renchap** [comment] 2024-09-16 13:53
This issue tracker is for the Mastodon software. Your issue seems to be caused by a problem with the toki.social instance (which uses our software), so it needs to be reported to this instance's admins.

I am closing this issue as we (the Mastodon software project) can not do anything about it. They are listing a contact email on their page, so you should probably contact them directly: https://toki.social/about

**Closed by renchap** 2024-09-16 13:53 UTC
Labels: bug, status/to triage
