### ISSUE TITLE
"Out-of-line" hashtags

### ISSUE THREAD

**Issue by k80w** [mastodon/mastodon#10743] opened 2019-05-10 04:41 UTC
It would be nice if one could add hashtags for a toot "out-of-line," i.e. not as a part of the text, similar to sites like Tumblr.

Adding inline hashtags to posts can feel annoying. A lot of times, parts of my posts can already be turned into hashtags without affecting the flow of the sentence ("Drinking some #RCCola with my #TotinosPizza"), however, if I want more specific tagging, I'm left with two options:

- Add extra tags inline ("Drinking some #RCCola #Soda #Cola with my #TotinosPizza #Pizza #MicrowavablePizza")
- Dump extra tags at the end ("Drinking some #RCCola with my #TotinosPizza. #Soda #Cola #Pizza #MicrowavablePizza")

None of these extra tags are directly contributing to the text of what I'm posting, but I'd like to use them anyway. I frequently see people tag posts in both of these methods, and it always seems to feel a little.... clunky. I can tell you post is about #Soda if I've read your post; the tag only serves to boost searchability or add metadata to the post so you can find it on your profile, and thus many people probably won't care too much about seeing these tags if this post is in their timeline.

Thus, I think Mastodon should have some way to differentiate between inline-tags that are a part of the actual text, and "out-of-line" tags that are purely used for metadata. This is a feature that's already in use by Tumblr, and it's something I think Mastodon could greatly benefit from if implemented properly.

With Tumblr, tags are a completely separate field from the toot content. I don't think this would be the right way to implement this in Mastodon, as having two separate fields in which one may add tags to some capacity seems a little confusing.

One solution to this would be to not change toot composition at all, simply make it so that when toots are rendered, Mastodon detects blocks of tags at the end and hides them/makes them smaller. Using this toot as an example:

> Drinking some #RCCola with my #TotinosPizza.
> #Soda #Cola #Pizza #MicrowavablePizza

If the last line of a toot is entirely hashtags and whitespace, Mastodon could visually distinguish it by making it smaller and dimmer than the rest of the content, or perhaps hide it behind a menu so it doesn't use up extra space in the timeline.

**Comment by nightpool** [comment] 2019-05-10 05:11
i really like non-body tags in general, although i'm not exactly sure
whether it's good for mastodon—twitter doesn't have it, for example, and
people seem to get along just fine. mastodon walks a fine knife edge
between providing affordances and encouraging creativity via constraint.
definitely would make the UI more complicated/more confusing. One advantage
non-body tags on tumblr have over just minimizing tags at the end of a post
is that they don't show up when reblogged, which allows for an interesting
division (and reblogging users can add tags without modifying the post
itself). these are both really useful affordances that might not be
captured in a more simple system.

I think we should think about ways that we can use topic-based
discoverability in a twitter-like environment, because hashtags on twitter
suck and hashtags on mastodon also suck because they feel cluttered and
gimicky, but this also feels like a feature request that's actually
expressing the desire for a more tumblr-like federated software, not
something that would be good for Mastodon specifically.

**Comment by trwnh** [comment] 2019-05-10 06:08
related: #2331, #7250

**Comment by StarryAster** [comment] 2019-05-10 18:13
What if, instead of a separate field, or just hiding tag clouds, there was some kind of syntax where the tags were added internally, but didn't appear in the post?

As in, if you posted "Drinking some #RCCola with my #TotinosPizza #~Soda #~Pizza", the post would appear as "Drinking some #RCCola with my #TotinosPizza", but the post could appear on searches for the Soda and Pizza hashtags. (#~ was just a suggestion, it can be anything else.)

One of the issues linked above mentions using #:hashtag for making a tag clickable but not searchable, which would be a good thing to have as well.

As for the problem of "how will people know this is a feature", since there is a warning that pops up whenever you use a hashtag on a non-public post (warning that post will not appear on searches even with a hashtag), there could be a warning saying people can use those syntaxes to make a hashtag searchable but not visible / visible but not searchable.

**Comment by NoraCodes** [comment] 2020-06-28 19:59
I don't know that additional syntax in posts is the right way to go. Personally, I've wanted out-of-band metadata for a long time, and I think the Tumblr interface is a good one - with a Mastodon twist.

If we consider the CW field to be like the Tumblr title field (which I personally do use it as, as do others, for long posts), then a separate metadata field, also hidden/unhidden by a button, would be very symmetrical - and, like, polls and CWs, would not intrude on the experience of users who don't want to use them.

**Comment by btaroli** [comment] 2023-01-10 23:55
OK, so this has been out here for a while. Is there any interest in taking it up? Clearly there are a number of us out there who have the same motivation. But what's lost in the simple flagging of more recent mentions as duplicates is that they add additional context.

For example, screen readers and accessibility have lead to the suggestion that the text of a toot should NOT be hashtagged at all, or hashtags should always be added at the bottom of a toot, further decreasing from the space available for the actual text. So yes it would be very much in line with some of these more recent conventions recommended for accessibility if the hashtags did not randomly consume additional space from the often limited space available for the toot itself.

**Comment by tismark** [comment] 2023-04-06 00:23
For what it's worth I think this would be a useful option. I had a comment today from someone using a screen reader who felt like the hashtags made it difficult to get to the alt text of the image in the post. 

Their suggestion was less hashtags, but I know from my own experience that people aren't always following the same hashtags. There's overlap between them but someone might be following hashtag widget and another might be following hashtag widgets, etc. 

It feels like it would be better to put the hashtags out of the actual post field as described in the issue. That would allow not having to worry about how their hashtag use might affect screen readers and just generally provide a cleaner look to posts.

**Comment by volkriss** [comment] 2023-05-14 13:59
I think @k80w is on track pointing out the difference between content and rendering, so Mastodon could even have a different, selectable rendering mode with additional compatibility for screenreaders, all while preserving what the author actually typed in.

In that same vein, FWIW, I wanted to point out that the underlying ActivityPub does have a separate metadata field for tags, so it looks like Mastodon [already does some out-of-body storage of hashtags](https://docs.joinmastodon.org/spec/activitypub/#Hashtag) even though it also preserves them in the body.

If anyone is pondering out-of-body storage, good news, the infrastructure for that is already done!

**Comment by ThisIsMissEm** [comment] 2023-11-21 17:06
@Gargron with the change to the ["trailing hashtags"](https://github.com/mastodon/mastodon/pull/26606) should this be considered resolved? Or would there still be more work to do here?

**Comment by trwnh** [comment] 2023-11-21 19:47
this issue is for authoring such tags, not just displaying them

**Comment by ThisIsMissEm** [comment] 2023-11-21 20:49
> this issue is for authoring such tags, not just displaying them

Perhaps we can update the issue title to clarify this then?

**Comment by volkriss** [comment] 2023-11-23 16:00
Well, quoting from the original post (I don't remember if this changed in the comments) there's this:

> One solution to this would be to not change toot composition at all, simply make it so that when toots are rendered, Mastodon detects blocks of tags at the end and hides them/makes them smaller. 

Judging from the linked PR, it sounds like this solution might have been adopted.

So maybe the inputting has been resolved?

**Comment by aquariusdev** [comment] 2023-12-31 03:07
Since an issue I just filed was marked as a dupe of this, I might as well support this idea with my idea of an "add tags" button in both web and mobile, in which you pull up your followed tags or pinned tag groups/filters to multi-select and populate the end of the post with tags. 

This would be in the style of Tumblr: 
![image](https://github.com/mastodon/mastodon/assets/28520002/bcb83c0a-81fe-4acd-8cf1-80f5f6bcd25e)
![image](https://github.com/mastodon/mastodon/assets/28520002/030a2bf9-36c5-455e-9785-ca6f53d98912)

My idea of how it would look in Mastodon web:
![image](https://github.com/mastodon/mastodon/assets/28520002/ffcf17af-0d72-4036-a180-f6155c38e95a)

How it would work in any mobile Mastodon client:
![image](https://github.com/mastodon/mastodon/assets/28520002/a49a4a32-36d5-4500-ab7d-1b86e9f90392)

**Comment by NoraCodes** [comment] 2024-11-29 16:03
I'd like to register my disagreement with the idea that the implementation in Mastodon today is "out of band". They're part of the post body, the client just renders them differently.

**Comment by trwnh** [comment] 2024-11-29 16:44
It sounds like the issue has been solved according to the author?

> One solution to this would be to not change toot composition at all, simply make it so that when toots are rendered, Mastodon detects blocks of tags at the end and hides them/makes them smaller. Using this toot as an example:
> 
> > Drinking some #RCCola with my #TotinosPizza.
> > #Soda #Cola #Pizza #MicrowavablePizza
> 
> If the last line of a toot is entirely hashtags and whitespace, Mastodon could visually distinguish it by making it smaller and dimmer than the rest of the content, or perhaps hide it behind a menu so it doesn't use up extra space in the timeline.

But the issue has not been solved according to commenters.

I think in this case I’m inclined to say that if anyone feels sufficiently strongly about being able to author or view hashtags that are not part of the content, then probably a separate issue would be best. There may already be one; if not, a new issue should be filed.

**Closed by trwnh** 2024-11-29 16:44 UTC
