### ISSUE TITLE
Customize landing page title and logo

### ISSUE THREAD

**Issue by henrywithu** [mastodon/mastodon#14457] opened 2020-07-27 19:14 UTC
Since this is open source, it would be a great feature if admins can customize landing page title and logo.
I know there is a way, using FTP to replace the .svg file, but that's quite inconvenient.
The reason why admins want to change the title and logo is, the default logo (MASTODON) does not match the site title(such as shown on the browser's tab). The only thing we can do(within the website) is to replace "server thumbnail" and "hero image", and i think more stuff can be done.
Thank you.

**Comment by Jim-Young** [comment] 2023-05-26 02:56
@henrywithu mate, have you tried to replace the .svg logo? I replaced ./live/app/javascript/images/logo-symbol-wordmark.svg but it doesn't show on my server

**Comment by Jim-Young** [comment] 2023-05-26 02:57
The file permission is the same, but it just won't display.

![Selection_004](https://github.com/mastodon/mastodon/assets/29013899/3fa16c04-7f0a-4608-893f-d00a8184644c)

**Comment by N-harzallah** [comment] 2023-07-07 11:11
here is the correct path /home/mastodon/live/app/javascript/images

file name app-icon.svg

**Comment by vmstan** [comment] 2023-11-17 13:53
Closed as duplicate of #967

**Closed** 2023-11-17 13:53 UTC
