### ISSUE TITLE
Allow moderators to add content warnings (CW)

### ISSUE THREAD

**Issue by Crashdoom** [mastodon/mastodon#28353] opened 2023-12-13 19:13 UTC
### Pitch

Allow moderators / admins to add or edit content warnings on both local and remote posts.

**Local Posts**
Moderators should be able to provide text to be added as a content warning to a post that does not currently have one. This action should be federated. If possible, it would be a good idea to additionally federate an attribution for the CW to the instance's moderation team.

The local user should be notified by email, similar to warnings, deletes, and other moderation actions, that a CW was added to their post. Accordingly, a strike should also be recorded.

**Remote Posts**
Similar to above, but this action must not be federated. It should be stored in the database and visible to local instance users that the CW was added by the local moderation team and NOT by the remote user. This could be done by adding a shield icon next to the CW, and if expanded, show an additional note at the top of the post explaining further.

Example verbiage: `This Content Warning (CW) was added by your local moderation team, and not the author of the post.`

**Federating Mod CW Actions**
This appears like it may be difficult as there's no mechanism within the AP protocol that would facilitate that. From a little digging (and please correct me if I'm wrong), Mastodon currently uses the AP `summary` field to identify when a CW has been provided. There's no other easy way of identifying when this was added by the author or the moderation team, and appending text to the summary would be insufficient as anyone could simply add the additional text required.

A thought on that would be to use a different `Activity` type to indicate it was not part of the original post, such as `Offer` (to offer context / a CW) with the object type of `Note`, and using `inReplyTo` to reference the post requiring the CW.

Example:
```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "summary": "furry.engineer moderators provided a CW for this post",
  "type": "Offer",
  "actor": {
    // Most likely the system context as the actor instead of the moderator themselves
    // e.g. furry.engineer@furry.engineer
  },
  "object": {
    "type": "Note",
    "summary": "ContentWarning",
    "content": "(Mod provided CW goes here)",
    "inReplyTo": "https://furry.engineer/...originalpostURL"
  }
}
```

There are edge cases and handling that haven't been considered here, as well as the requirement for this to be handled by other projects, so obviously take this last section as purely suggestion open to alternatives and thoughts.

Another alternative, would be to just add an automatic `Note` in response to the original post and have Mastodon interpret that as adding a CW (so long as it's coming from the originating instance), while otherwise providing the suggested CW as a reply.

### Motivation

Currently, if a post breaks an instance's content warning rules (e.g. NSFW content or sensitive topics), the only moderation actions that can be taken are:

- **Mark as Sensitive**
The problem with this is only the images / attachments are marked as sensitive, but the text content of the post is still visible.

- **Delete Post**
This feels like overreaching and unnecessarily taking punitive action when softer remedies would rectify the problem without forcing the user to remake their post.

- **Warning / Talking directly to the user**
This only works locally and fails to address remote posts, but leaves the post up without the CW and typically incurs receiving additional reports about the missing CW while the issue is being addressed.

Allowing moderators to add CWs themselves would alleviate the additional delay and resolve reports more quickly to avoid remote instance complaints and avoid using harsh penalties for user mistakes.

**Comment by Cassolotl** [comment] 2023-12-14 20:50
Related to *Add moderation tool to edit content warning on a post #1307*?

**Comment by trwnh** [comment] 2023-12-31 06:26
Duplicate of #1307

**Closed by trwnh** 2023-12-31 06:26 UTC
Labels: suggestion
