### ISSUE TITLE
Only silence instance on federated timeline (default or option)

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#7153] opened 2018-04-16 13:37 UTC
Currently when an instance admin or moderator silences instance X, all communication is silenced, except for people on your instance who follow an account on instance X. But if user A on instance X replies on user B from instance Y (and B doesn't follows A), the reply is not seen in users B's notifications. Also the reply from user A@X in a thread of user B@Y on instance Y, is hidden.

Example: On the instance administered by me (todon.nl) Switter.at is silenced, because a lot of images are still not marked as sensitive. But that's the only thing I want. My users are free to communicate with people from Switter, but they have to follow them first, and if someone from Switter replies on a thread (cause Todon.nl's public toots are on Switter's the federated timeline) they aren't noticed by people that don't follow that Switter user.

Of course there are instances you want to silence like that, but mostly instances I silence are only because I want to keep the federated timeline clean, without people getting dicks and boobs in the face when scrolling. And don't get me wrong, I don't have problems with Switter or similar instances.

A solution is to make silencing instances only silence them on the federated timeline, or to have 2 options when silencing instances (only federated timeline or all communication (except when followed).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThisIsMissEm** [comment] 2018-04-17 05:35
Media leaving our instance should be marked as NSFW, but I’ll have to double check. We’re also slowly getting better at moderating, but it can be an uphill battle.

I agree with being able to silence an instance’s media from federation timeline, but think it should be a user option, i.e., instance admin can mute, but then users can unmute.

**Comment by ThisIsMissEm** [comment] 2018-04-17 05:37
We’ve also opened a PR / discussion for moderation tooling to enable us to mark some users as “unlisted” when going out of our instance, and allowing us to block media from certain users

**Comment by ThisIsMissEm** [comment] 2018-04-17 05:39
This issue also better sums up #7140, if we’d like to close that @nightpool or @gargron

**Comment by ThisIsMissEm** [comment] 2018-04-17 05:40
Oh, and #7142

**Comment by mal0ki** [comment] 2018-05-03 09:54
IIRC you can currently choose to reject_media of another server, without silencing it nor blocking it, I'm not 100% sure here, but I believe it's possible. 

I do agree that it'd be useful if silence/blocks both on instance and user level could have bit more granularity to it.

**Comment by trwnh** [comment] 2023-05-14 08:38
Duplicate of #7066

**Closed by trwnh** 2023-05-14 08:38 UTC
Labels: moderation, suggestion
