### ISSUE TITLE
Animated webp profile picture

### ISSUE THREAD

**Issue by HalanoSiblee** [mastodon/mastodon#30456] opened 2024-05-28 13:08 UTC
### Steps to reproduce the problem

1. upload animated 400x400 webp as profile picture
...

### Expected behaviour

Animated Profile picture

### Actual behaviour

Image has been re-encoded by server and only frame 1 taken as static webp image

### Detailed description

webp and apng are smaller high quality and more optimized than regular gif
however mastodon server seems to re-encoding my webp and make it static
any way of fixing this behavior ?.

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-05-17

### Browser name and version

firefox-developer-edition 126.0b7

### Operating system

Arch Linux (x86_64)

**Comment by vmstan** [comment] 2024-05-28 13:18
Duplicate of #21492

**Closed by vmstan** 2024-05-28 13:18 UTC
Labels: bug, status/to triage, area/web interface
