### ISSUE TITLE
Can't see my post on someone's profile when they boost it.

### ISSUE THREAD

**Issue by emj04** [mastodon/mastodon#27173] opened 2023-09-27 11:20 UTC
### Steps to reproduce the problem

1. Make a post.
2. Someone boosts that post.
3. Go to their profile and look for the post that they boosted.

### Expected behaviour

I should be able to see the post that they boosted on their profile.

### Actual behaviour

I can't see their boosts of my posts.

### Detailed description

I believe this started happening after the update to 4.2

### Mastodon instance

mastodon.world

### Mastodon version

v4.2.0-rc2

### Browser name and version

Firefox 117.0.1

### Operating system

Fedroa 38

**Comment by trwnh** [comment] 2023-09-30 21:41
Possibly the same as #27195 and therefore possibly could be fixed by #27204

**Comment by ClearlyClaire** [comment] 2023-10-04 08:35
Closed as a duplicate of #27195. Please re-open if it reoccurs in the upcoming 4.2.1

**Closed by ClearlyClaire** 2023-10-04 08:35 UTC
Labels: bug, status/to triage, area/web interface
