### ISSUE TITLE
Mastodon WebUI Showing Times beyond 24:00

### ISSUE THREAD

**Issue by thecatcollective** [mastodon/mastodon#27309] opened 2023-10-06 12:15 UTC
### Steps to reproduce the problem

1. Browse your federated timeline
2. Click on a post that was created after 00:00 of the day that you are viewing the post from (within your timezone)
3. Note that the listed time now goes past 24:00 (24:30, 24:50, etc...) until it reaches 24:59, at which point it begins showing 01:00 and onwards properly.

### Expected behaviour

The timestamp should've gone from 23:59 to 00:00 when the calendar day switched over

### Actual behaviour

The timestamp goes from 23:59 to 24:00 and just continues onward until 25:00 at which point it switches to 01:00.

### Detailed description

The issue occurs as described above. We haven't been able to track down the reason why this occurs. This issue also occurred when we used Firefox 118.0.1 on Fedora Linux 39 (Beta).

We have attached some images of the issue within this post box.

![image](https://github.com/mastodon/mastodon/assets/127357898/8b299398-4e95-4ce0-896c-f27fd9f86697)
![image](https://github.com/mastodon/mastodon/assets/127357898/a8cf38cc-c9a3-4968-b8f0-dd576bd3c07b)
![image](https://github.com/mastodon/mastodon/assets/127357898/e910abc1-d4ba-4221-bb37-83ea6021d5f5)
![image](https://github.com/mastodon/mastodon/assets/127357898/b87daff9-7a1e-416a-ad14-4ca25ac5681a)

Here is when the timestamp reset itself 
![image](https://github.com/mastodon/mastodon/assets/127357898/ec49042b-e609-4a6d-9777-41a9772ad85d)
![image](https://github.com/mastodon/mastodon/assets/127357898/77f9ee35-eea4-4dc6-b6c5-1c39fc72e3e6)

### Mastodon instance

furry.engineer

### Mastodon version

v4.2.0+glitch

### Browser name and version

Microsoft Edge 117.0.2045.47 64bit (Windows) and Mozilla Firefox 118.0.1 (Linux)

### Operating system

Microsoft Windows 11 22H2 and Fedora 39 (Beta)

**Comment by Cassolotl** [comment] 2023-10-06 23:41
Duplicate of *Midnight is expressed as 24th hour instead of 0th hour #15855* (2.5 year old bug - ouch)

**Comment by thecatcollective** [comment] 2023-10-07 16:27
Ah I see, thank you for the information. Should I mark this as closed? (sorry, first time using an issue tracker)

**Comment by Cassolotl** [comment] 2023-10-07 19:30
@thecatcollective 

>Should we mark this as closed? (sorry, first time using an issue tracker)

No worries! :) Yeah, I'd say head over to the old issue and leave your comments there, and close this one. 👍

**Closed** 2023-10-08 00:26 UTC
Labels: bug, status/to triage, area/web interface
