### ISSUE TITLE
Explore prompt shows up on fairly busy home timeline

### ISSUE THREAD

**Issue by lambda** [mastodon/mastodon#27197] opened 2023-09-28 19:57 UTC
### Steps to reproduce the problem

1. Follow about ~200 people who post and boost reasonably often (I see new posts on my home timeline about once every 1-5 minutes during the day)
2. Upgrade to Mastodon 4.2.0

### Expected behaviour

I wouldn't be prompted to follow more people

### Actual behaviour

Got a prompt to see trending posts and people to follow

### Detailed description

I feel like I use Mastodon fairly heavily, see plenty of posts in my timeline, use the advanced web interface with the local timeline also open where I see even more. A prompt that seems to be designed for new users who don't follow very many people and may want to discover more people to follow seems unnecessary and intrusive for someone who already uses Mastodon heavily.

### Mastodon instance

hachyderm.io

### Mastodon version

v4.2.0

### Browser name and version

Firefox 118.0.1

### Operating system

Ubuntu 22.04.3 LTS (Jammy Jellyfish)

**Comment by p37307** [comment] 2023-09-29 10:52
I have been getting it when the timeline is slow to load/refresh but it disappears after a few seconds. Sometimes it hangs around a little longer. I'm selfhosted v4.2.0 with 2.4K follows 1.9 followers. 

I have a lot of people in different topical lists and now use the list feature to '_Hide these posts from home_' for a significant portion of them. _Off-topic, that new feature makes browsing my timeline and my lists so much better._  I figured it had something to do with the backend filtering those out.

**Comment by ClearlyClaire** [comment] 2023-09-29 12:01
This banner is supposed to show if any of the following is true:
- the average time between two posts in your home TL (as seen by the Web UI), excluding your own posts, is less than 30 minutes
- the most recent post in your home TL (as seen by the Web UI), excluding your old posts, is older than one hour

Is one of these occurring for you? I've also noticed that out-of-order posts were not handled correctly.

**Comment by lambda** [comment] 2023-09-29 17:34
The first definitely wasn't the case for me. As mentioned, I checked the last few posts when I saw this, and it was between 1-5 minutes between posts, definitely much less than 30 minutes.

I have slow mode enabled, as I don't like posts scrolling away while I'm reading them, and I think there were a few posts that hadn't yet displayed when I saw this. I don't think it was as much as an hour since the last post displayed, but it's possible.

Not sure if I can reproduce this now that I've dismissed the prompt, but I think that if those are what the rules are supposed to be, there's a bug in the implementation because my home timeline is busier than that; either it doesn't take into account slow mode, where I deliberately don't want new posts appearing until I click, or it's not calculating the average post rate correctly, or something.

**Comment by p37307** [comment] 2023-09-29 17:55
> This banner is supposed to show if any of the following is true:

I knew I read something about this in the [v4.2.0 release notes](https://github.com/mastodon/mastodon/releases/tag/v4.2.0)
_If average gap between posts is more than 20 minutes, or the most recent post is from more than an hour ago, show a dismissable banner that points to trends and follow recommendations_ https://github.com/mastodon/mastodon/pull/25267

**Comment by lambda** [comment] 2023-09-29 20:53
Oh! Taking a look at that PR, the code doesn't actually follow the logic described above. There's an additional condition; it will show up if there are fewer than 5 different accounts visible:

```js
const homeTooSlow = createSelector(getHomeFeedSpeed, speed =>
  speed.unique < 5 // If there are fewer than 5 different accounts visible
  || speed.gap > (30 * 60) // If the average gap between posts is more than 20 minutes
  || (Date.now() - speed.newest) > (1000 * 3600) // If the most recent post is from over an hour ago
);
```

And it looks like it's looking at the 20 most recent posts:

```js
  const statuses = statusIds.take(20).map(id => statusMap.get(id));
  const uniqueAccountIds = (new Set(statuses.map(status => status.get('account')).toArray())).size;
  const oldest = new Date(statuses.getIn([statuses.size - 1, 'created_at'], 0));
  const newest = new Date(statuses.getIn([0, 'created_at'], 0));
  const averageGap = (newest - oldest) / (1000 * (statuses.size + 1)); // Average gap between posts on first page in seconds
```

So if you have 4 people who have each posted 5 times recently (such as posting a thread), or one person who has posted a lot, you will easily have only 4 accounts in the past 20 posts, even if you follow a lot of people.

There are also a number of other errors in this calculation:

* The denominator in the gap calculation should include `statuses.size - 1`, not `+ 1`; if there are two posts, then there's one interval. This would mean there would need to be a check that statuses.size is at least 2 or else this whole calculation is invalid.
* Is `.size` even right here? I must admit I'm not a frontend guy and I don't really know what the types of any of these objects are, but an array in JavaScript has a `.length` not a `.size` (a set has a `.size`). Is `statuses` something other than an array?
* The comment and release notes say 20 minutes, but the code says 30 minutes

**Comment by p37307** [comment] 2023-10-01 03:26
Also, your issue might have to do with this recent merge. _Fix explore prompt appearing because of posts being received out of order_ https://github.com/mastodon/mastodon/pull/27211

**Comment by lambda** [comment] 2023-10-01 04:21
Yeah, I also wonder, but haven't dug in enough to find out,  what timestamp is being used here. For boosts, is it using the timestamp of the original post or when the boost was made?

I did notice the behavior where the prompt appeared, then disappeared without dismissing it, then appeared again, presumably after the posts on my timeline met the criteria, then failed to, then meet the criteria again.

**Comment by ClearlyClaire** [comment] 2023-10-02 09:31
> Oh! [Taking a look at that PR](https://github.com/mastodon/mastodon/pull/25267/files#diff-9f2c86d49f2c07196f46693d3839095b2560871cbeed00cb35cac93713834d77R37-R54), the code doesn't actually follow the logic described above. There's an additional condition; it will show up if there are fewer than 5 different accounts visible:

That code has been changed in multiple ways since then, in particular the 5 different accounts condition has been dropped.

> Also, your issue might have to do with this recent merge. _Fix explore prompt appearing because of posts being received out of order_ #27211

This was merged after the report, so it would not be a cause, but it would possibly fix the issue if it's caused by posts arriving in the wrong order.

> Yeah, I also wonder, but haven't dug in enough to find out, what timestamp is being used here. For boosts, is it using the timestamp of the original post or when the boost was made?

It should be using the time the boost was made.

**Comment by ClearlyClaire** [comment] 2023-10-02 09:45
> * The denominator in the gap calculation should include `statuses.size - 1`, not `+ 1`; if there are two posts, then there's one interval. This would mean there would need to be a check that statuses.size is at least 2 or else this whole calculation is invalid.

You are correct, although this off-by-two is actually works in favor of not displaying the prompt.

> * Is `.size` even right here? I must admit I'm not a frontend guy and I don't really know what the types of any of these objects are, but an array in JavaScript has a `.length` not a `.size` (a set has a `.size`). Is `statuses` something other than an array?

Yes, `.size` is right. `statuses` is an [`Immutable.List`](https://immutable-js.com/docs/v3.8.2/List/#size)

**Comment by lambda** [comment] 2023-10-04 19:47
> You are correct, although this off-by-two is actually works in favor of not displaying the prompt.

Yeah, was just pointing out things that I noticed on a quick review.

Anyhow, is there any way for me to re-enable this prompt, so I could try to reproduce the issue now that I know more about what the logic is, and check to see why it was triggering on my timeline? I dismissed it because I didn't want the prompt, but only after that thought to file the issue, so now I can't reproduce it.

**Comment by ClearlyClaire** [comment] 2023-10-05 07:49
Currently, it's stored only on localStorage, in the `mastodon_banner_settings.idhome.explore_prompt` key.

**Comment by lambda** [comment] 2023-10-18 01:32
Ah, I think I may have figured it out, after removing that key so I would see the behavior again; it happens when I post a reply to someone, and the newest post in my feed is my reply.

Breakpoint on the calculation shows that the date on the newest post is showing up as the epoch.

![image](https://github.com/mastodon/mastodon/assets/37398/713d45cc-9f6e-413f-9f1f-15cff0ace909)

**Comment by lambda** [comment] 2023-10-18 01:43
Doesn't need to be a reply, just any post from myself. And the prompt goes away when I actually load that post (I have slow mode on).

![image](https://github.com/mastodon/mastodon/assets/37398/eb0c0444-b761-4f1f-82d0-ec24707c46f4)

So it looks like the steps to reproduce are:

1. Ensure that you have cleared the `mastodon_banner_settings.idhome.explore_prompt` local storage key
2. Enable Slow Mode in preferences
3. Write a post that you'll see (I did a "Mentioned people only" post to myself to test)
4. Scroll up on your home timeline to see the "1 new item"
5. When you scroll up all the way you'll see the explore prompt as well.

**Comment by lambda** [comment] 2023-10-18 03:28
Ah, a bit more investigation leads me to realize that this happens due to this earlier code, which uses only pending statuses if there are pending statuses, and then filters out self-posts. That then leads to there being no statuses, since the only pending status in this case was my own post; and so it returns a a value with a date at the epoch, triggering the prompt.

```jsx
const getHomeFeedSpeed = createSelector([
  state => state.getIn(['timelines', 'home', 'items'], ImmutableList()),
  state => state.getIn(['timelines', 'home', 'pendingItems'], ImmutableList()),
  state => state.get('statuses'),
], (statusIds, pendingStatusIds, statusMap) => {
  const recentStatusIds = pendingStatusIds.size > 0 ? pendingStatusIds : statusIds;
  const statuses = recentStatusIds.filter(id => id !== null).map(id => statusMap.get(id)).filter(status => status?.get('account') !== me).take(20);

  if (statuses.isEmpty()) {
    return {
      gap: 0,
      newest: new Date(0),
    };
  }
```

As to how to fix this, it seems like the pending status ids and status ids should be appended, not just taking one or the other. Alternatively, the explore prompt shouldn't show if there are pending statuses; it seems a bit odd to show a prompt about not having much going on on your timeline if you have posts which have just come in that you haven't read yet.

So potential patches, completely untested.

Concatenate the two lists:

```diff
diff --git a/app/javascript/mastodon/features/home_timeline/index.jsx b/app/javascript/mastodon/features/home_timeline/index.jsx
index 93f937628..f19eaf935 100644
--- a/app/javascript/mastodon/features/home_timeline/index.jsx
+++ b/app/javascript/mastodon/features/home_timeline/index.jsx
@@ -37,7 +37,7 @@ const getHomeFeedSpeed = createSelector([
   state => state.getIn(['timelines', 'home', 'pendingItems'], ImmutableList()),
   state => state.get('statuses'),
 ], (statusIds, pendingStatusIds, statusMap) => {
-  const recentStatusIds = pendingStatusIds.size > 0 ? pendingStatusIds : statusIds;
+  const recentStatusIds = pendingStatusIds.concat(statusIds);
   const statuses = recentStatusIds.filter(id => id !== null).map(id => statusMap.get(id)).filter(status => status?.get('account') !== me).take(20);
 
   if (statuses.isEmpty()) {
```

Or just don't bother to show the prompt if there are pending statuses:

```diff
diff --git a/app/javascript/mastodon/features/home_timeline/index.jsx b/app/javascript/mastodon/features/home_timeline/index.jsx
index 93f937628..1349d96ee 100644
--- a/app/javascript/mastodon/features/home_timeline/index.jsx
+++ b/app/javascript/mastodon/features/home_timeline/index.jsx
@@ -37,8 +37,14 @@ const getHomeFeedSpeed = createSelector([
   state => state.getIn(['timelines', 'home', 'pendingItems'], ImmutableList()),
   state => state.get('statuses'),
 ], (statusIds, pendingStatusIds, statusMap) => {
-  const recentStatusIds = pendingStatusIds.size > 0 ? pendingStatusIds : statusIds;
-  const statuses = recentStatusIds.filter(id => id !== null).map(id => statusMap.get(id)).filter(status => status?.get('account') !== me).take(20);
+  if (pendingStatusIds.size > 0) {
+    return {
+      gap: 0,
+      newest: new Date(),
+    };
+  }
+
+  const statuses = statusIds.filter(id => id !== null).map(id => statusMap.get(id)).filter(status => status?.get('account') !== me).take(20);
 
   if (statuses.isEmpty()) {
     return {
```

**Comment by ClearlyClaire** [comment] 2023-10-18 08:28
Thanks for digging into this!

> As to how to fix this, it seems like the pending status ids and status ids should be appended, not just taking one or the other.

I meant to look into that as part of investigating #27362 but I got sidetracked. I agree with your conclusion, and I think these two lists should be appended. Can you open a PR?

**Closed** 2023-10-19 12:25 UTC
Labels: bug, status/to triage, area/web interface
