### ISSUE TITLE
after upgrade to 4.0.1 I get error 500

### ISSUE THREAD

**Issue by r3k2** [mastodon/mastodon#20727] opened 2022-11-15 02:15 UTC
### Steps to reproduce the problem

Steps:
follow the upgrade from 3.5.5 to 4.0.0 instructions as they are on the changelog 

### Expected behaviour

to work like before

### Actual behaviour

erro 500

### Detailed description

After upgrade of our instance now we are down with the elephant page, error 500 I cant see anything out of the normal running 
journal -fu mastodon-sidekiq  or the other 2,  I see some 202 on nginx log
also see some entries not sure if this was there before:
```
1xxxxx4 - - [14/Nov/2022:21:18:24 -0500] "\x00" 400 150 "-" "-"
1xxxxx4 - - [14/Nov/2022:21:18:24 -0500] "\x00" 400 0 "-" "-"
```
### Specifications

Mastodon 4.0.1
ruby 3.0.4p208
Node.js v18.12.1 LTS

**Comment by lilfade** [comment] 2022-11-15 02:20
did you run the db update?

**Comment by r3k2** [comment] 2022-11-15 02:21
@lilfade you mean the 2 step migration? yes

**Comment by r3k2** [comment] 2022-11-15 02:25
not sure if I should restore from backup and checkout 3.5.3 until I can figure this out  @lilfade

**Comment by lilfade** [comment] 2022-11-15 02:27
did you check out your 'systemctl status ...' make sure their all running? 500 error usually means something on the webserver side of stuff. I'd even check your nginx file, I know a couple of changes were made in the default one from the repo as well.

**Comment by r3k2** [comment] 2022-11-15 02:28
@lilfade yeah and journal -fu on each, I even went ahead and backup the old nginx file and put the new one, and of course changed the ssl path etc. same result

**Comment by lilfade** [comment] 2022-11-15 02:32
@r3k2 yea im not sure, i did a progressive one through the rc's except rc2, but everything seemed to just go fine on my end. I suppose i'd say check your syslogs and nginx logs and see what they show and probably restore and try again.

**Comment by r3k2** [comment] 2022-11-15 02:39
@lilfade yeah going to restore and go back to 3.5.5

**Comment by r3k2** [comment] 2022-11-15 02:50
@lilfade ok I checkout the old version, drop the db and restored and now is working, of course with the 3.5.5 :( not sure what happened, never had an issue upgrading as long I was following the steps one by one, is something missing from the official steps? maybe because 4.0.1 needs somethign diff?

**Comment by lilfade** [comment] 2022-11-15 03:01
@r3k2 not sure i did the upgrade of ruby as mentioned, next I did the 

`git fetch && git checkout v4.0.1`. 

Next I ran a 
`bundle install -j$(getconf _NPROCESSORS_ONLN)` & `yarn install --pure-lockfile` as was mentioned in the docs for upgrades and such.

After all that I ran

`SKIP_POST_DEPLOYMENT_MIGRATIONS=true RAILS_ENV=production bundle exec rails db:migrate`

followed by

`RAILS_ENV=production bundle exec rails assets:precompile`

and then

`RAILS_ENV=production bundle exec rails db:migrate`

and finally restarted everything.

**Comment by r3k2** [comment] 2022-11-15 03:11
@lilfade I already had that ruby version, and did everything like you mention, but notice they have just come out with 3 point releases in 15m :D so I am going to hold off until tomorrow night is 4:10am here, that way I make sure they iron out any last minute issues they find. Thanks for the help <3  I will report back here when I actually do the upgrade and succeeds.

**Comment by gabelula** [comment] 2022-11-15 05:10
I skipped 4.0.1. I went from 4.0.0 to 4.0.2 and everything went just fine.

**Comment by lilfade** [comment] 2022-11-15 05:20
Did the 4.0.2 and everything is still fine on my end, I will note I'm a newer instance though vs being around pre 3.5.3.

**Comment by moodler** [comment] 2022-11-15 06:16
I ran the upgrade to 4.0 and then 4.0.2 ... no major errors I could see.  BUT now the webUI is dead.   https://openedtech.social     The services seem to be running, and I can operate fine via the app.    I'm new to ruby unfortunately ... any tips?

**Comment by lilfade** [comment] 2022-11-15 06:27
@moodler If you did *both* db steps you shouldn't have a issue. As mentioned above check your syslogs for errors or your nginx logs if the services are running. `tail -f /var/log/syslog` and see if you see any errors. Worst case restore your 3.5.3 db backup (you hopefully did) and fetch release 3.5.3. check the docs on docs.joinmastodon.org for more tips on the ruby commands as you need to update ruby, gems and probably the yarn install as well. I'm unsure how the DO droplet differs, @r3k2 are you using the preformed template as well or dedicated?

**Comment by moodler** [comment] 2022-11-15 06:40
Thanks a lot for your help ... 

I'm extremely sad to say I did not back up the database ... that was something I was getting to (yes I usually know better, but the site was still so new ...)  so I need to go forward... 

This looks promising:

Nov 15 06:37:53 openedtech bundle[3975]: 1. You want to set webpacker.yml value of compile to true for your environment
Nov 15 06:37:53 openedtech bundle[3975]:    unless you are using the `webpack -w` or the webpack-dev-server.
Nov 15 06:37:53 openedtech bundle[3975]: 2. webpack has not yet re-run to reflect updates.
Nov 15 06:37:53 openedtech bundle[3975]: 3. You have misconfigured Webpacker's config/webpacker.yml file.
Nov 15 06:37:53 openedtech bundle[3975]: 4. Your webpack configuration is not creating a manifest.

Trying to see how to fix that

**Comment by moodler** [comment] 2022-11-15 07:00
I'm getting actual HTML loading properly now on https://openedtech.social/ but it's still not showing up in the browser.  Somethings's still wrong with webpack I guess. No new errors in logs, nginx thinks it's serving fine.

**Comment by moodler** [comment] 2022-11-15 07:11
A tip on the correct way to run webpack for a production instance would be ace right now, if someone knows!

**Comment by rjl20** [comment] 2022-11-15 07:26
I reproduced this behavior with a fresh installation of 3.5.3 and a new database with only the admin user and one toot in it. Following the upgrade steps from 3.5.3 to 4.0.2 gets me the following error in the logs:

ActionView::Template::Error (undefined local variable or method `role_id' for #<User id: 1, email: "xxxxx@xxxx.xxx", created_at: "2022-11-15 06:48:46.527962000 +0000", updated_at: "2022-11-15 06:56:57.247036000 +0000", admin: true, locale: nil, encrypted_otp_secret: nil, encrypted_otp_secret_iv: nil, encrypted_otp_secret_salt: nil, consumed_timestep: nil, otp_required_for_login: false, last_emailed_at: nil, otp_backup_codes: nil, account_id: 109346483488712767, disabled: false, moderator: false, invite_id: nil, chosen_languages: nil, created_by_application_id: nil, approved: true, sign_in_token: nil, sign_in_token_sent_at: nil, webauthn_id: nil, sign_up_ip: nil, otp_secret: nil>

In the schema.rb, I see that the "users" table is supposed to have a "role_id" column, but "echo '\d users' | psql mastodon_production" does not show me that column in the running database. So this feels like although I ran the db:migration steps as described in the upgrade docs, something about that process just didn't work. There was no output from either step; should there have been? I feel like previously I've seen something in those steps.

**Comment by moodler** [comment] 2022-11-15 07:31
Just to help you, I tried 'echo '\d users' | psql mastodon_production" and I do see role_id in that table ...

**Comment by moodler** [comment] 2022-11-15 07:51
OK, this worked for me (hope it helps someone)

0) Shut down all services
1) Edit config/webpacker.yml and change compile to true under production
2) Remove old cache `mv tmp/cache tmp/cache.old`
3) Run  `RAILS_ENV=production bundle exec rails assets:precompile`
4) Change that value in config/webpacker.yml back to false
4) Start up services again

**Comment by ClearlyClaire** [comment] 2022-11-15 09:14
@moodler changing `config/webpacker.yml` shouldn't be necessary, otherwise, yeah, sometimes webpacker likes to pretend it has nothing to do even though the previous attempt at precompiling assets failed (usually because of running out of memory). In those cases I usually `RAILS_ENV=production bundle exec rails assets:clobber` but seems like removing the cache worked for you.

@rjl20 this is surprising. Are you using multiple machines/containers? If so, are all of them using the latest code? This reminds me of #20433 though at this time I don't understand what could have caused the migrations to be marked as complete if they didn't run.

**Comment by rjl20** [comment] 2022-11-15 09:55
> I reproduced this behavior with a fresh installation of 3.5.3 and a new database with only the admin user and one toot in it. 

And now I can't reproduce it, with another fresh install and upgrade. I'm pretty sure the only thing I did differently was add "--trace" to the db:migrate invocations, but I must have done something wrong the first time, since I can't imagine that would change the behavior. I'll try it again with another fresh install tomorrow, I guess.

**Comment by r3k2** [comment] 2022-11-15 15:03
> I ran the upgrade from 3.5.3 (was new last week, using Digital Ocean droplet) to 4.0 and then 4.0.2 ... no major errors I could see. BUT now the webUI is dead. https://openedtech.social The services seem to be running, and I can operate fine via the app. I'm new to ruby unfortunately ... any tips?

this is exacly what happened to us

**Comment by lilfade** [comment] 2022-11-15 15:26
Well those two so far are on DO droplets, are you running on a droplet as well? @r3k2

**Comment by r3k2** [comment] 2022-11-15 15:33
@lilfade no, is hosted on arch GNU/Linux on a intel computer, I can put the expects after work so I can ssh in.
@moodler so I guess yours is up and running, I will give it a try when pick time goes down, we have around 3000 users, I been running and instance since 2017 and never had an issue before like this so is not like I may have done something wrong for lack of experience, also a linux/Unix systems and cybersecurity engineer for 24 years. Something in the update is just not working right with the current setup(this is why I think @moodler solution removing the cache may work or running assets:clobber) it did ocurred to me last night to wipe the cache but it was 4am so I just restored and went to bed :D :D

**Comment by r3k2** [comment] 2022-11-15 23:36
@lilfade @moodler ok I just finished with out any issue, I did the normal procedure and just in case I added the steps from @moodler in the midle and all good. maybe will be nice to add a note on the steps to run this as well:
```
RAILS_ENV=production bundle exec rails assets:clobber
```

**Closed** 2022-11-15 23:37 UTC
Labels: bug, troubleshooting
