### ISSUE TITLE
when someone replies to my toot without mention me, im not notified

### ISSUE THREAD

**Issue by albjeremias** [mastodon/mastodon#12908] opened 2020-01-20 16:25 UTC
I didn't receive a notification when someone replied to my "toot" without mentioning me.. it was commented from hubzilla.. should i report this here or in hubzilla? I guess here, because if i reply to a toot of someone without mentioning, then im not notified? it's a birdsite behavior?

So my question is: **Is this a choice? Or a bug?**

![image](https://user-images.githubusercontent.com/26681446/72742212-284b0500-3ba1-11ea-8246-9c9e10365fa0.png)

**Comment by albjeremias** [comment] 2020-01-20 16:38
on hubzilla: https://framagit.org/hubzilla/core/issues/1431

**Comment by trwnh** [comment] 2020-01-20 17:15
More of an oversight in compatibility -- Mastodon checks for the presence of a `Mention` within the `tag` array. Other implementations like Hubzilla may rely instead on `to`/`cc`/`inReplyTo`.

Also see #10865 for having reply notifications in Mastodon, which this is technically a duplicate of.

**Comment by Wild1145** [comment] 2023-05-02 20:59
As this has come up today on the Discord I just want to bump this and confirm the behaviour is still as described in the report.

**Comment by trwnh** [comment] 2023-05-20 02:58
Duplicate of #10865

**Closed by trwnh** 2023-05-20 02:58 UTC
