### ISSUE TITLE
How can i change the date of my (photo) posts to reflect the date the photo was taken?

### ISSUE THREAD

**Issue by dan-i-welcome** [mastodon/mastodon#29866] opened 2024-04-06 15:34 UTC
### Pitch

We need a way to set the date for posts containing photos taken a long time ago.

### Motivation

I am trying to migrate my account from facebook and other social networks here.
I am uploading past photos from my phone/laptop and all of them get the timestamp of now, it looks like i took 200 totally unrelated photos now.

The profile timeline needs to make sense chronologically, and for that people need the ability to set a past date for posts with uploaded photos.
If anyone is concerned about people misusing this, it's fairly easy to add an icon overlay on all posts which had the date changed to let others know about it.

The inability of setting the date for a post is the main obstacle for me to migrate to Mastodon/Pixelfed.

Please add the UI for changing the date on the "edit post" element.

Thank you.

**Comment by trwnh** [comment] 2024-04-07 01:10
Duplicate of #15912

**Closed by trwnh** 2024-04-07 01:10 UTC
Labels: suggestion
