### ISSUE TITLE
Frontend and backend seem to calculate post length differently

### ISSUE THREAD

**Issue by connyduck** [mastodon/mastodon#17860] opened 2022-03-23 18:28 UTC
### Steps to reproduce the problem

Post a status containing an url <23 characters and fill up the remaining characters until the frontend reports 0 characters left, e.g. `https://example.com 11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111` (change the number of 1s in case the server has a different max length)

### Expected behaviour

Status posts correctly

### Actual behaviour

Error 422 - Validation failed: Text character limit of 500 exceeded

### Specifications

Happens on mastodon.social v3.5.0rc1 and chaos.social v3.4.6

Both Firefox & Chrome

**Comment by digitalcircuit** [comment] 2022-03-23 18:43
@connyduck Thanks for posting this here!

For others first seeing the issue here, as shown in the mentions, [this was originally found when diagnosing a Tusky issue - additional context over there, too](https://github.com/tuskyapp/Tusky/issues/2399 ).

**Comment by connyduck** [comment] 2022-06-16 17:02
Seems to be fixed? Can't reproduce on mastodon.social v3.5.3

**Comment by digitalcircuit** [comment] 2022-06-16 17:34
@connyduck Agreed, I can't reproduce the issue here, either - both Mastodon's web UI (granted, via glitchsoc fork) and Tusky appear to function correctly.

Hazarding a guess since I don't fully understand the code, this was probably fixed with the rewrite of URL parsing in ["Fix being able to post URLs longer than 4096 characters"](https://github.com/mastodon/mastodon/commit/bbc7afa2a24519ac238cbcd4e8aec310a002c40e) via pull request [#17908](https://github.com/mastodon/mastodon/pull/17908).  This happened a mere week after this bug report.

I think you should be fine closing this issue.  Thank you for filing it here in the first place, and for rechecking it!

**Closed** 2022-06-16 17:51 UTC
Labels: bug
