### ISSUE TITLE
Use only one "Notes" section at Moderation/Admin > Reports, instead of two

### ISSUE THREAD

**Issue by KNTRO** [mastodon/mastodon#26201] opened 2023-07-26 20:00 UTC
### Pitch

There are two _Notes_ sections under Moderation or Admin.

One is at https://[domain]/admin/reports/[report_number]

![image](https://github.com/mastodon/mastodon/assets/2568821/68254f25-861d-410f-b25c-97d878bb5f3b)

And the another one is at: https://[domain]/admin/accounts/[account_number]

![image](https://github.com/mastodon/mastodon/assets/2568821/ad792820-6db7-4112-83a2-8f48e6c6bdb5)

I think this needs to be modified to be just one _Notes_ section, not two.

### Motivation

Why two _Notes_ sections? Some administrators or moderators will leave notes in one _Notes_ and others admins or mods will leave notes on the other _Notes_ section, and they will probably not read the notes left by others. 🙄 It's quite confusing.

**Comment by trwnh** [comment] 2023-07-27 02:39
it looks like one is notes about an account, the other is notes about the report? so probably the heading can be reworded to clarify that: "Account notes" or "Notes about this account", as well as "Report notes" or "Notes about this report"

**Comment by KNTRO** [comment] 2023-07-27 04:26
@trwnh These two __Notes__ sections could be together on the same webpage, one section below the other.

- An always visible __Notes about this account__ section that will help as a quick reference
- And a dynamic __Notes about this report__ that will appear on each specific report below the __Notes about this account__ section

**Comment by ThisIsMissEm** [comment] 2023-10-24 17:33
Hi! I'm the person who added this feature, and it's actually a deliberate split. Notes on reports are for discussion about that report specifically (in the future I wish to make it possible to federate this discussion so two moderation teams can align on action to take.

Notes on accounts on the other hand are more for things like "This account frequently has account take-over attempts made" or "This account frequently is misreported in attempts to get them banned" (this something we experienced on Switter.at)

Whilst we could certainly combine them when viewing the report, that'd require some careful UI design, to make sure it was clear which account the note was about; but in the Reports UI, one could certainly argue that you may desire both the Account Notes for the reported account, and for the reporter (e.g., in case they happen to be frequently flyer with poor reports).

I could do up a PR that renames the "Notes about this report" section to "Report discussion" which would be a quick win and inline with the future idea of federating report discussions (you'd be able to select when adding a comment whether to post internally or to share with the other instances participating in that report).

We're also expanding the activity log for reports to include strikes and prior account warnings (I believe this is merged, and shipping in the next release)

**Comment by ThisIsMissEm** [comment] 2024-08-17 21:09
@vmstan this is working as intended — we deliberately have notes about an account and notes about a report.

**Closed** 2024-08-17 21:18 UTC
Labels: suggestion
