### ISSUE TITLE
XMPP messaging

### ISSUE THREAD

**Issue by GBT7** [mastodon/mastodon#20924] opened 2022-11-17 05:14 UTC
### Pitch

I just think that in order for Mastodon to be a more complete social media platform, it needs better private chat features. Perhaps it could implement XMPP, with a chat option showed for users running on instances with compatible versions of Mastodon. Maybe there could be some features on top of that, such as a chat recipient could have the ability to accept or decline a chat, with the option to choose between sending a response message or not.

One thing I would be most excited for if this ever happens is encrypted chat, as XMPP can be used alongside Signal Protocol encryption.

### Motivation

A lot of people on Mastodon are very privacy-minded, so it would be great to have an encrypted chat option. Many users are already directing people to Signal, but that requires them to exchange phone numbers first. Just about all successful social networks have some form of chat feature built in which is more effective and sometimes more private than Mastodon's DM feature. Mastodon benefits from being conducive to one-on-one conversations. It's one of the best things about chat-first platforms like Discord. Also, the idea for a decline option is present on many platforms, as people may not want their DMs and private chats open for everyone to send stuff into.

**Comment by trwnh** [comment] 2022-11-17 05:16
Duplicate of #9181

**Comment by afontenot** [comment] 2022-11-17 06:37
> A lot of people on Mastodon are very privacy-minded, so it would be great to have an encrypted chat option

Worth pointing out that XMPP is rather dated at this point for a secure messaging protocol. Yes, it can be "fixed" if you know exactly the right protocol extensions to apply and have support for them in all the clients, but a clean implementation of a [double-ratchet algorithm](https://en.wikipedia.org/wiki/Double_Ratchet_Algorithm) is really not all that difficult. There are libraries that can help with it. Eventually you'd want an audit of course, but you might as well do Signal-esque messaging if you're going to take the step towards adding encrypted messages to Mastodon. Note that this is what e.g. Whatsapp does as well, it's a common standard at this point.

**Comment by afontenot** [comment] 2022-11-17 07:14
> Correct me if I'm wrong but I thought that Signal's double ratchet algorithm is compatible with XMPP, hence why I already mentioned Signal Protocol above.

XMPP is just the communication protocol. To get double ratchet you have to layer it on top of XMPP which means your clients need special support. It's a bit messy and loses some of the advantages of using an open protocol by requiring an extension that isn't universally adopted. (Specifically, you need to support the [OMEMO](https://en.wikipedia.org/wiki/OMEMO) extension.)

**Comment by jmaris** [comment] 2022-11-17 13:57
Matrix would probably be a more viable option for messaging, however the Matrix Server (Synapse) is quite demanding with memory / CPU

**Comment by Leatherface75** [comment] 2022-11-17 14:17
Omemo extension exists for Piding for example so i would like XMPP support.

**Comment by nightpool** [comment] 2022-11-17 15:23
Please direct your discussion to the linked issue.

**Closed by nightpool** 2022-11-17 15:23 UTC
Labels: suggestion

**Comment by sjehuda** [comment] 2024-08-30 04:45
> Worth pointing out that XMPP is rather dated at this point for a secure messaging protocol.

I want to add, that I am a criminal and corporate lawyer, and amongst my clients XMPP is the "gold standard", so to speak, of communication.

If someone does not use XMPP, then he is probably not my client, nor someone who my clients would be interested in engaging on business with.

**Comment by sjehuda** [comment] 2024-08-30 05:38
Please hide @jmaris comment (mark off topic) because it is off topic.

@jmaris instead of interrupting this discussion, I suggest you open a new ticket.
I will gladly respond.

**Comment by jmaris** [comment] 2024-08-30 12:14
> @afontenot
> 
> > Worth pointing out that XMPP is rather dated at this point for a secure messaging protocol.
> 
> I want to add, that I am a criminal and corporate lawyer, and amongst my clients XMPP is the "gold standard", so to speak, of communication.
> 
> If someone does not use XMPP, then he is probably not my client, nor someone who my clients would be interested in engaging on business with.
> 
> Please hide @jmaris comment (mark it as off topic) because it is off topic.
> 
> @jmaris instead of interrupting this discussion, I suggest you open a new ticket. I will gladly respond.

I'd like to respectfully reiterate my point: if the goal is to implement a chat feature in Mastodon, then we should not limit the discussion to a single protocol. You behave as if the discussion over which protocol to adopt has already been concluded, but it hasn't.

XMPP is an exceptionally robust protocol, which I have personally used for years, but it comes with lots of baggage: features which we consider key today, such as offline messaging, message archiving and sync, and most importantly, encryption, have been bolted onto the protocol rather than built into it.

If the developers are to consider integrating instant messaging into mastodon, then there should be an open discussion about the protocol used, rather than demands from one side or another to implement their preferred solution.

**Comment by sjehuda** [comment] 2024-08-30 14:37
First of all, thank you for your respond.

> I'd like to respectfully reiterate my point: if the goal is to implement a chat feature in Mastodon, then we should not limit the discussion to a single protocol. You behave as if the discussion over which protocol to adopt has already been concluded, but it hasn't.

I am not for the protocol which you have mentione, yet I think it is fine to suggest it, in a new ticket.

I can enjoy eating chocolate and I can enjoy eating chicken, but I do not mix them together, and so I expect to have a segregate discussion here too.

> XMPP is an exceptionally robust protocol, which I have personally used for years, but it comes with lots of baggage: features which we consider key today, such as offline messaging, message archiving and sync, and most importantly, encryption, have been bolted onto the protocol rather than built into it.

XMPP is extensible and XEPs allowing developers to decide which features they want to implement and which not to implement. This should not be change, and this is a good practice. It is even the best practice.

Here is an annotation system which does not use the messaging system. It only uses a single XMPP extension which is XEP-0060.
- https://git.xmpp-it.net/sch/Blasta
- https://video.xmpp-it.net/w/cfozoUeVLFbBFMCCSCJ1Dn (6:38)

The XEP practice allows to build lightweight software and systems as required by given needs.

> If the developers are to consider integrating instant messaging into mastodon, then there should be an open discussion about the protocol used, rather than demands from one side or another to implement their preferred solution.

Of course. I only alerting that the protocol that you have proposed is linked to criminal agencies, and the corporation behind it behaves very bad towards privacy.

**Comment by sjehuda** [comment] 2024-08-30 15:09
> criminals also use email what's your point

Pardon. This is off topic. Please see my claims and video at https://github.com/mastodon/mastodon/issues/14576#issuecomment-2320143648

**Comment by sjehuda** [comment] 2024-08-30 15:11
> criminals also use email what's your point

My point, is that I know people who are classified as "criminal" and most of them use XMPP, which is evident for the quality of XMPP, other than the centralized systems which have to report to governments.

**Comment by MadokVaur** [comment] 2024-08-30 17:00
> Please direct your discussion to the linked issue.

"Nightpool closed this as not planned on November 17, 2022"

Which is almost 2 years ago

Time to learn how Github Blocks work

I've blocked all recent participant (I think, I'll repeat if I seem to have missed anyone)

Seriously, people, if all you want to do is to argue with each other, maybe take it over to Mastodon

**Comment by Leatherface75** [comment] 2024-08-31 15:35
Best would be to implement both XMPP and Matrix support and let the server owners or users choose themself.

**Comment by Neustradamus** [comment] 2024-09-05 13:25
To follow this important ticket.

**Comment by Leatherface75** [comment] 2024-09-06 21:23
> but they're incompatible, @Leatherface75 if that were done then users would only be able to DM people on compatible instances based arbitrarily on the amount of resources at the disposal of the admins as well as their opinions on the matter
> 
> that's like suggesting that instances should have a choice between activitypub and, idk, Zot? Giving a choice to pick only one of the two means we'd no longer even be talking about the same network. If the option were given for a different protocol than the rest of the network, it should be on a fork with a different name, because it would no longer be compatible with Mastodon instances.

Well nowadays if i have to choose i would choose Matrix support.
Matrix servers can support multiple protocols if the servers choose to support it.
