### ISSUE TITLE
Expose action taken in Admin::Report API

### ISSUE THREAD

**Issue by crowdagger** [mastodon/mastodon#26521] opened 2023-08-17 04:56 UTC
### Pitch

Currently (at least from what can be seen on https://docs.joinmastodon.org/entities/Admin_Report/) the API for accessing admin reports exposes whether an action was taken (`action_taken`), when it was taken (`action_taken_at`) and by who (`action_taken_by_account`). It would be nice to have a field describing what the action taken was (limit, suspend, none, ...).

### Motivation

This would be a first step to enable third party tools related to moderation.

**Comment by ThisIsMissEm** [comment] 2023-10-24 17:42
The problem with implementing this will be that the report itself does not contain the information as to which action was taken. Instead you'd need to look at the `Admin::ActionLog` which is the table that produces the "report history" section. We currently do not have an API that exposes the `Admin::ActionLog`, but perhaps we should?

**Comment by ThisIsMissEm** [comment] 2024-02-19 23:56
The `Admin::ActionLog` ticket is here: https://github.com/mastodon/mastodon/issues/23403

**Comment by ThisIsMissEm** [comment] 2024-08-17 21:02
@vmstan I didn't think this can be fixed.

**Comment by trwnh** [comment] 2024-09-02 18:22
Duplicate of #19158

**Closed by trwnh** 2024-09-02 18:22 UTC
Labels: api, moderation, suggestion
