### ISSUE TITLE
Polls need photo selection

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon#29484] opened 2024-03-01 21:49 UTC
### Pitch

Right now polls are only setup for text options.
Photos can't be added as options.
 This should be addressed.

### Motivation

Beneficial for a couple reasons.
1. People like to see their options visually 
2. It gets people engaged in a post and gets their interest which keeps them wanting to come back and look

**Comment by trwnh** [comment] 2024-03-02 08:35
Duplicate of #10707

**Closed by trwnh** 2024-03-02 08:35 UTC
Labels: suggestion
