### ISSUE TITLE
Follow/unfollow button may cover the account name

### ISSUE THREAD

**Issue by nemobis** [mastodon/mastodon#28926] opened 2024-01-26 08:16 UTC
### Steps to reproduce the problem

1. Change your UI to a language with sufficiently long words
2. Search any account
3. Look at the account names
...

### Expected behaviour

I should be able to see the account names

### Actual behaviour

The unfollow button (in Italian "Smetti di seguire") covers the account names

### Detailed description

The space for account details is fixed, and the height of the follow/unfollow button is fixed too, so instead the button extends horizontally until it takes all the space. What's worse, it changes size when you click to follow/unfollow an account. Very often, as I click to follow someone and then I click left to the follow button to see more details (e.g. to add a note), the unfollow button changes extends while my cursor is mid-air, and my click ends up causing an unfollow. The text and clickable area to see the profile become extremely small:

![Screenshot_20240126_094924](https://github.com/mastodon/mastodon/assets/901528/4e58a86c-f840-4cfc-bf90-5a40a46c837f)

### Mastodon instance

mamot.fr

### Mastodon version

v4.2.1

### Browser name and version

Firefox 121

### Operating system

Fedora Linux 39

**Comment by renchap** [comment] 2024-01-26 09:01
Duplicate of #27130

**Closed by renchap** 2024-01-26 09:01 UTC
Labels: bug, status/to triage, area/web interface
