### ISSUE TITLE
Make possible to add a user to a list without following the user

### ISSUE THREAD

**Issue by BiLachner** [mastodon/mastodon#19660] opened 2022-11-02 06:47 UTC
### Pitch

I would like to be able to add a user to a list without having to follow them.

### Motivation

There are some users who post a lot and can make the "quieter" accounts pretty invisible.

I would like to have the toots of the "loud" and also important accounts for retrieval in a list/column without overlooking the "quiet" accounts. The "loud" accounts I would then no longer follow but be able to read their toots.

Thanks

**Comment by ClearlyClaire** [comment] 2022-11-02 08:31
Duplicate of #6982. It will likely never be possible to add someone you don't follow to a list. However, it will likely be possible at some point to exclude accounts you follow from your Home timeline, either on a per-account basis, or on a per-list basis.

**Closed by ClearlyClaire** 2022-11-02 08:31 UTC
Labels: suggestion
