### ISSUE TITLE
Quote-Posts/Toots

### ISSUE THREAD

**Issue by LeftIndy** [mastodon/mastodon#22978] opened 2023-01-07 19:35 UTC
### Pitch

As many of us have migrated from a certain avian themed site recently purchased by a fascist multi-billionaire, the search for viable alternative platforms has led many of us to Mastodon.  Although the site so far has been good depending on which servers best fit our needs and suit our purposes, the lack of quote-posting necessitates going to needless lengths to offer up context and commentary about posts we find interesting enough to share, but which we may wish to offer additional information, context, or opinion.

Many are opposed to the implementation of such a feature, supposedly because of concerns over the abuse thereof to engage in intimidation, targeted harassment, and other forms of toxic behavior.  These concerns are unfounded as the culture, not the tools, is what drives behavior and the ability to go private, mute and block individual accounts, and even mute and block entire server instances means that nobody need fear such actions as seen on the Muskrat's bird app.

### Motivation

The reason this feature is so widely implemented on social media platforms is that it makes it much easier to provide additional context to posts seen on the Fediverse, and add our own opinions without having to go out of our way to copy links and text and take screen captures.  As well, we may wish to share news articles with which we disagree without appearing to concur with or validate the articles themselves.  It simply makes no sense to force users to either do extra work simply to share our opinions or leave for other platforms.  The lack of quote-posting makes it prohibitive to social justice advocates to engage in activism, as acknowledged by Mastodon co-founders.

**Comment by trwnh** [comment] 2023-01-07 19:58
Duplicate of #22872 #22793 #20673 #19889 #18473 #15524 #13876

**Comment by LeftIndy** [comment] 2023-01-07 22:51
> Duplicate of #22872 #22793 #20673 #19889 #18473 #15524 #13876

Not really, because all those requests involve limiting the ability in some way of users to prevent posts from being quoted, whether as a default setting or as a general means of thwarting the feature so as to render it useless for practical purposes.  My request is for quote-posting—period, and if others don't want their posts quoted, they can take their accounts private as on other platforms or, if they really think there's a server rules violation, submit an abuse report, or simply mute or ban people.

**Comment by Cassolotl** [comment] 2023-01-08 01:04
The original issue is *quote + boost #309*, which was opened in 2016 and closed in 2019.

Gargron has [recently stated here](https://mastodon.social/@Gargron/109623891328707089) that he isn't as strongly against QTs as he was. Perhaps if people go to #309 and leave a comment and tag him, he might reopen that issue?

**Comment by LeftIndy** [comment] 2023-01-09 15:22
> The original issue is _quote + boost #309_, which was opened in 2016 and closed in 2019.
> 
> Gargron has [recently stated here](https://mastodon.social/@Gargron/109623891328707089) that he isn't as strongly against QTs as he was. Perhaps if people go to #309 and leave a comment and tag him, he might reopen that issue?

Given the sheer level of hostility to anything and everything that reminds some of the bird app, I doubt that particular issue will be re-opened.  Even still, the suggestions given for implementing the feature make it a practical non-happening anyway.  Half-measure proposals aren't the same as asking for a basic feature that is already widely used on multiple social media platforms.

**Closed** 2023-05-19 06:22 UTC
Labels: suggestion
