### ISSUE TITLE
Login with OSM and other libre projects

### ISSUE THREAD

**Issue by tykayn** [mastodon/mastodon#12187] opened 2019-10-20 08:53 UTC
Add the ability to login to Mastodon via an other libre project like :
* OpenStreetMap
* OpenID
* Wikipedia

Symfony has a bundle for this, enabling an easy implementation of MANY login ways, so i guess it exists too in the ruby universe.
https://github.com/hwi/HWIOAuthBundle

### Pitch
more ways to authenticate are easing the creation account fricition, hence leading to an ease of adoption of mastodon.
plus it gives a layer of security by using a well maintained way to certificate users and reduce spam accounts.

### Motivation
At first i was considering providing auth by privative platforms like twitter , fb, google. But it is the chance to give everyone the chance to discover Auth for great projects, or reuse their auth from somewhere else, making bridges to the libre projects in general and the fediverse.

**Comment by trwnh** [comment] 2019-10-20 09:26
#7958

**Comment by kaniini** [comment] 2019-10-21 08:05
It would be better to support IndieAuth instead of arbitrary OAuth providers.

**Comment by MirceaKitsune** [comment] 2019-10-24 18:17
Generally I'm not thrilled by such an idea, as logging in this way adds an extra dependency to an external server. I always imagined that if for any reason OpenID (or a similar service) goes down for some time, countless people will be locked out of various websites. It can happen... even Facebook / Twitter / Youtube went down for hours on rare occasions.

I'd also worry that someday, those services may be constrained to block interaction with some instances if pressured to do so, which could cause instances to get locked out. I'd offer the way Cloudflare booted 8chan as one example, with no intent to touch on the politics involved... CF was meant to provide DDOS protection and internet infrastructure, yet ended up being pressured to act as spies or censors. The TLDR is, there are a lot of different Mastodon instances, and centralizing some logins to an external provider could give that provider power to take sides.

**Comment by trwnh** [comment] 2019-10-24 18:39
you would still need a mastodon account, so there's no reason to worry about being locked out. logging in (authenticating) with another service is simply an alternative. again, see #7958 (and #4800 for the reverse direction, which also includes discussion of indieauth)

**Comment by trwnh** [comment] 2023-05-16 04:33
Duplicate of #7958

**Closed by trwnh** 2023-05-16 04:33 UTC
