### ISSUE TITLE
Please implement support for markdown syntax within the text input field.

### ISSUE THREAD

**Issue by Guelakais** [mastodon/mastodon#30874] opened 2024-06-29 09:18 UTC
### Pitch

I often try to write markup-like text in the text input field to add links to it. Unfortunately this doesn't work. To be honest, that's all I wanted to add. Here's an example:
```sh
[best link ever](https://anvilproject.org/guides/content/creating-links)
```
which should appear as:
[best link ever](https://anvilproject.org/guides/content/creating-links)

or something similar to:
```sh

[more best links ever](1)
[1](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://neovim.io/&ved=2ahUKEwjYv733u4CHAxV7hP0HHTzlB5QQFnoECAcQAQ&usg=AOvVaw3vU5SQj7OYpVWFjGjhlpuk)
```
which should appear as:
more best links ever](1)
[1](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://neovim.io/&ved=2ahUKEwjYv733u4CHAxV7hP0HHTzlB5QQFnoECAcQAQ&usg=AOvVaw3vU5SQj7OYpVWFjGjhlpuk)

### Motivation

Mastodon is a software that is largely used by open source fans and technology enthusiasts. Many open source environments are more advanced than commercial versions. For example, Linux desktop environments far for windows offered features such as virtual desktops and variable keybindings. Open source is also a driver of innovation that inspires other software. In addition, such a feature makes for a more elegant text flow, as you don't have huge links in your text posts.

**Comment by maikelthedev** [comment] 2024-06-29 14:10
# Extra motivation

A large proportion of users of Mastodon do know markdown. Even on Reddit it was the default for a long time. Even here in Github **I can use markdown** all the *time*. And adding it to Mastodon won't affect those who do not know any markdown. Glitch-version can do it. What's the stopper on stock version?

**Comment by trwnh** [comment] 2024-06-30 02:32
Duplicate of #23981

**Closed by trwnh** 2024-06-30 02:32 UTC
Labels: suggestion
