### ISSUE TITLE
[duplicate] Feature request: Option to disable notification counter in tab title

### ISSUE THREAD

**Issue by realpixelcode** [mastodon/mastodon#15313] opened 2020-12-10 14:47 UTC
Please add an option to disable the new notifications counter in Mastodon's tab title since this may be annoying if you get particularly many notifications. I tried it but all the "Disable Notifications from this website", "Play sound" etc. options don't disable the counter itself, just the actual system's notifications.

For example:  "(5) Mastodon" -> just "Mastodon"

**Comment by weex** [comment] 2021-07-12 23:46
Duplicate of https://github.com/mastodon/mastodon/issues/15313

**Comment by weex** [comment] 2021-07-12 23:47
Duplicate of https://github.com/mastodon/mastodon/issues/13188

**Comment by realpixelcode** [comment] 2021-07-21 14:47
@weex sorry

**Comment by weex** [comment] 2021-07-21 16:17
@realpixelcode Don't be. I looked into this and it was fascinating how hard it was to trace. I just noted that it's a duplicate so both threads could gauge level of interest from the other. Thanks.

**Closed** 2023-05-17 04:01 UTC
