### ISSUE TITLE
Support filter migration

### ISSUE THREAD

**Issue by eobet** [mastodon/mastodon#22668] opened 2022-12-22 20:35 UTC
### Pitch

Followers are migrated automatically. Follows need to be imported manually. With filters you can't do neither.

This needs to be fixed. Ideally, they should also carry over automatically (as should everything else, but that's a separate issue).

### Motivation

Migration is very perilous and a super advanced feature currently. Everything possible should be done in order to streamline it. This is just a small part.

**Comment by FediVideos** [comment] 2023-02-17 21:39
It's a good idea, I think it's a duplicate of https://github.com/mastodon/mastodon/issues/9177 though?

**Comment by trwnh** [comment] 2023-05-14 16:52
Duplicate of #9177

**Closed by trwnh** 2023-05-14 16:52 UTC
Labels: suggestion
