### ISSUE TITLE
Inter instances emoji usage

### ISSUE THREAD

**Issue by goliv04053** [mastodon/mastodon#21586] opened 2022-11-24 20:51 UTC
### Pitch

Use other instances emojis on your instance. 
Example: Discord let's you use other servers emoji on other server (in the case of Discord you have to pay Nitro but in our case it will be free)

### Motivation

I have friends in other instances and their emojis are also interesting. It would be interesting if we could use each other emojis.

**Comment by ineffyble** [comment] 2022-11-25 04:49
The small server I help run (<1000 users, not a lot of traffic) that's been online since 2017 has over 58,000 remote emoji collected, including many duplicates.

I don't know how you could possibly build an emoji picker UI to help you navigate that list, and it also would likely contain emoji that are undesirable or offensive.

**Comment by goliv04053** [comment] 2022-11-26 21:53
I think that the solution to this is to let the user choose which "server emoji pack" wants to use. Example: I choose Mastodon(dot)social and other server emoji pack, it will be available to me only those packs

**Comment by goliv04053** [comment] 2022-11-26 21:53
And if I want to add more I can choose or change.

**Comment by Andre601** [comment] 2023-02-22 10:53
I would love to use emojis from another instance, since they have a lot of cute ones the instance I'm on doesn't.

And before you say "Why not switch to that instance?": I was on it, but owner asked to move to a more fitting instance with that account.

Also, let's adress how to handle these emojis (i.e. how to access/select them).
I think since we already use an e-mail like syntax for mentions could the same be done here. Use `:emoji@instance.tld:` to select `emoji` from `instance.tld` (hopefully this would work and not conflict with the existing mention format).

Also, since not everyone would like to have their emojis used somewhere else should there be a setting to toggle this (default should be off (deny it) to keep current behaviour).

This would really be a cool feature and connect the fediverse even more!

**Comment by trwnh** [comment] 2023-05-19 06:37
Duplicate of #8649

**Closed by trwnh** 2023-05-19 06:37 UTC
Labels: suggestion
