### ISSUE TITLE
Disable previews of content-warning labeled images

### ISSUE THREAD

**Issue by trini** [mastodon/mastodon#10729] opened 2019-05-08 15:19 UTC
### Pitch

While there's a lot of cases where providing a semi-preview of content-warning can be useful, there's other cases where users don't want that preview.  We should make this behavior configurable.

### Motivation

There's a few different reasons one might not want to see a blurred version of sensitive content:
- It can be distracting.  A colorful blurred image is much more eye-catching than a blank box.
- It can be previewing unwanted content.  For example people posting CW'd images of why one should consider blocking another instance over violent images/content.  Having the "receipts" is good, but that should be wholly opt-in.

**Comment by StarryAster** [comment] 2019-05-09 04:35
I haven't seen any examples of blurred images that weren't blurred to the point it was basically impossible to know what they were about, but I agree this should be a configuration.

It would be ideal for this to be configurable both at an admin level and at an user level (like the instance theme), but at least users should be able to choose.

**Comment by trini** [comment] 2019-05-09 12:32
> I haven't seen any examples of blurred images that weren't blurred to the point it was basically impossible to know what they were about, but I agree this should be a configuration.

Maybe I should be a little clearer then.  What pushed me to make an issue over this was a recommended instance block over reaction to the latest US school shooting.  I don't want a blurry preview of screenshots of text or graphics about that.  I want none of it.  The content warning told me exactly what I wanted to know and a blurry preview is harmful.  This logic extends to racism, bigotry and all sorts of other things that trigger people.  The CW tells me I don't want to see it.

**Comment by AirDur** [comment] 2019-05-18 16:56
Yes, please. It's aggressive and eye-catching. I really dislike this new "feature".

**Comment by nightpool** [comment] 2019-05-18 17:00
I can understand not liking it aesthetically, (distracting/eye catching) but in what way is a blurred preview harmful?

**Comment by trini** [comment] 2019-05-18 17:55
> I can understand not liking it aesthetically, (distracting/eye catching) but in what way is a blurred preview harmful?

By existing.  If something is shocking and awful to you, a blurred image may lead your mind to "is it an example of this, or that or ...".  My trigger on this was over a school shooting and no, I don't want to start imagining which of the possibly things could be behind that blurred image.

**Comment by trini** [comment] 2019-10-26 11:40
I see the bot has marked this as stale.  It's still a problem, IMHO.

**Comment by trwnh** [comment] 2023-05-16 03:55
Duplicate of #6141

**Closed by trwnh** 2023-05-16 03:55 UTC
Labels: suggestion
