### ISSUE TITLE
Following Notifications Using RSS/Atom Feeds

### ISSUE THREAD

**Issue by UsernamesAreFuckedUp** [mastodon/mastodon#19017] opened 2022-08-20 10:48 UTC
### Pitch

If you've ever used Lemmy, you must know that there is a little "feed button" in your Inbox page, which points to a randomly generated XML feed (like eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjU2MywiaXNzIjoic29wdWxpLnh5eiIsImlhdCI6MTY2MDkyODcxNH0.-pHb0ZVOioTP_ZjKzvG3JnNI4_Zaah6QwG2jzdUJYJ0.xml (I've changed one letter due to privacy concerns)), so you can follow your notification through your preferred RSS reader. I've read Issue #673, but I guess generating random feed filenames is simpler to implement than needing the user to log in.

### Motivation

Every time you want to check your notifications, you need to open up the client (and for me, the browser, too.). Furthermore, sometimes you don't want to update and check the timeline, but you just want to catch up with notifications. Also, RSS/Atom feeds are the "standard" way of receiving updates on the Web, aren't they? It would be very nice and convenient to have this feature in Mastodon, too.

**Comment by dwbit** [comment] 2022-12-01 13:41
Would love to see RSS support for notifications! Especially when using more than 1 individual are monitoring an account, it is such a great way to parse through notifications in a structured/reliable way.

**Comment by jcdietrich** [comment] 2023-01-04 21:27
I use the Hermit — Lite Apps Browser on Android to view my two mastodon accounts. It supports RSS notifications, and I would love to be able to make use of that functionality.

**Comment by trwnh** [comment] 2024-11-27 00:09
Duplicate of #673

**Closed by trwnh** 2024-11-27 00:09 UTC
