### ISSUE TITLE
post scope that only shows to mutuals?

### ISSUE THREAD

**Issue by reitraced** [mastodon/mastodon#12332] opened 2019-11-08 21:08 UTC
a post scope that only shows to mutuals (accounts that follow you back)

### Pitch
the followers only scope has been very flawed since the beginning and if you want to post personal stuff but still have a public account it doesnt really work
my proposal is to add a scope in between, this scope will allow you to run an account that anyone can follow (helpful for me as an instance admin who doesnt want to split accounts) and still be able to post privately

### Motivation
this post would be beneficial for users who dont want to have to manage a private and public account at the same time.

sometimes you just gotta post privately and not have to go through the hassle of swapping accounts

**Comment by trwnh** [comment] 2019-11-09 00:57
duplicate of #7135

**Closed** 2023-05-20 02:56 UTC
