### ISSUE TITLE
Support Boolean Search for Hashtags

### ISSUE THREAD

**Issue by Timothyjchambers** [mastodon/mastodon#21778] opened 2022-11-28 05:15 UTC
### Pitch

Right now hashtag search is powerful, but it would be far better if it supported even basic boolean search strings.

So instead of only searching for #Hasthag1 you would be able to do a search of:

#Hashtag1 AND #Hashtag2

Or: 

#Hashtag1 OR #hashtag2 -#hashtag3

Then it would search for all posts with either of the two first hashtags, but NOT the third.

### Motivation

While the ability to search for hashtags now on Mastodon is a great way to ensure that only posts that WANT to be found can surface, the lack of even boolean searching makes it that much harder to find precisely what content users are looking for.

By adding a Boolean Hashtag search feature, it becomes greatly more powerful.

**Comment by grothauu** [comment] 2022-11-28 05:28
That us a good feature to filter the information better.

**Comment by sreedev98** [comment] 2022-11-28 05:30
This is a really good idea.

**Comment by grothauu** [comment] 2022-11-28 05:32
In addition it would be fine to filter results by language. #china delivers chinese language results. That is useless for me.

**Comment by esfoobar** [comment] 2022-11-28 17:53
I fully support this! I've been wishing it to exist since I re-joined Mastodon.

**Comment by TymeForChange** [comment] 2022-11-28 18:48
You pretty much can do that now (without actually typing out a query string), in a Hashtag column's settings. See attached. 
![multi-hashtags](https://user-images.githubusercontent.com/56969001/204356465-4d3f6577-95eb-455f-a01c-c8c77b296dbc.png)

**Comment by robinlej** [comment] 2022-12-06 20:45
> You pretty much can do that now (without actually typing out a query string), in a Hashtag column's settings. See attached. ![multi-hashtags](https://user-images.githubusercontent.com/56969001/204356465-4d3f6577-95eb-455f-a01c-c8c77b296dbc.png)

Yes but this is a lot of unnecessary steps (1) be on a computer, 2) use advanced interface, 3) look for hashtag, 4) pin to column, 5) add new hashtag, 6) delete column because you don't actually want it pinned) to do something that would be nice to have directly from the search bar. And that without saying that the hashtag autocompletion and hashtag search from that menu in a pinned column gives you less possibilities than from the search bar.

Anyways, I highly support this request. :)

**Comment by mudomau** [comment] 2022-12-13 16:16
I fully support this request, I think this - https://github.com/mastodon/mastodon/issues/20731 - should be merged here.

As it stands, search is not very functional. Being able to search for multiple tags and combine them using boolean algebra would be an amazing addition, providing a good compromise between searchability and privacy.

**Comment by mudomau** [comment] 2022-12-13 17:27
> You pretty much can do that now (without actually typing out a query string), in a Hashtag column's settings. See attached. ![multi-hashtags](https://user-images.githubusercontent.com/56969001/204356465-4d3f6577-95eb-455f-a01c-c8c77b296dbc.png)

This is great, it should really be the default for the search option to be able to combine tags with boolean algebra like this.

**Comment by supernovae** [comment] 2022-12-20 14:45
An extremely desirable feature.

I'd also ask that #hashtag search be fixed so that it passes through to elastic search. Right now, only "hashtag" goes to ES while "#hashtag" only shows the hashtags.  It would also be nice to be able to Boolean search through to Elastic Searc effectively

**Comment by nekohayo** [comment] 2023-04-24 17:10
Related (if this is not a duplicate of it): issue #6287

**Comment by brendanjones** [comment] 2023-07-10 13:51
Definitely a duplicate of #6287, this should be closed. Though that issue could definitely be better named.

**Comment by renchap** [comment] 2023-09-01 16:23
Duplicate of #6287

**Closed by renchap** 2023-09-01 16:23 UTC
Labels: suggestion
