### ISSUE TITLE
List hashtags separately from body of post

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon#24445] opened 2023-04-06 13:24 UTC
### Pitch

Mastodon should have a WordPress-style or Friendica-style method for listing tags separately from the content of the post, with a separate character limit for the tags.

### Motivation

At the moment, Mastodon's hashtag search system is pulling people in totally incompatible directions:

 - Hashtag search needs an exact match. To make discovery possible, people should add as many tags and variations as possible. For example, someone looking for #trains will simply not see posts labelled #railways or #locomotives. This situation requires posters to add as many related tags as possible, possibly including spelling variations.

 - Large numbers of tags can cause serious problems for screen reader users, especially if there is no warning that they are about to encounter a tag list. Some screen reader apps are forcing blind people to sit through long lists of hashtags just so they can get to the alt text of the post's attachments.

 - If people add lots of tags to their post, especially in the middle of the text itself, this is seen by some as spamming/SEO.

- The standard 500 character limit often means people want to add relevant tags, but there isn't room for these tags. The longer a post, the harder it is to be discovered because there isn't room for as many tags.

 - On some mobile apps long lists of hashtags take up half the screen as they are displayed in the same size font as the content of the post.

To resolve these contradictions, tags should be kept separately from the body of the message, as they are on WordPress posts or Friendica posts or PeerTube videos. The tag list would be displayed much less prominently, use a smaller font, and would include a warning at the beginning saying something like "tag list". The tag list's character limit would be totally separate from the post's main character limit.

This would resolve the contradictions:

 - A separate list would make it more intuitive to add many related tags to a post, especially if it uses Mastodon's current hashtag suggestion system. Tag suggestions work really well when tagging WordPress posts for example, and Mastodon's current tag suggestion system is very similar.

 - By having a separate tag list, screen reader users and screen reader software developers would be able to skip the tag list much more easily.

 - By keeping the tags separate from the post, it would look much less like SEO spam, and more like the unobtrusive tags we are used to on blog posts. Mastodon would be more readable.

 - By having a separate character limit for tags, people who write longer posts would still be able to add as many tags as those who write shorter posts. Discovery would then be equally good for long and short posts.

 - By removing tags from the body of a post, it will make mobile app views display a lot more actual content.

**Comment by nehemiagurl** [comment] 2023-04-06 15:16
I would like to add that I am pretty sure this already is a possibility in ActivityPub. The tags on a Mobilizon event, for example, don't appear in the post when it appears on Mastodon. That should make it relatively easy to implement, unless I am missing something.

**Comment by FediVideos** [comment] 2023-04-06 15:21
Yes indeed, Friendica does this too, and PeerTube, and their posts do appear in Mastodon searches.

**Comment by Cassolotl** [comment] 2023-04-06 19:41
Duplicate of *Replace hashtags with tags #2331* (April 2017) ?

**Comment by FediVideos** [comment] 2023-04-06 20:02
> Duplicate of _Replace hashtags with tags #2331_ (April 2017) ?

Hmm... possibly? I'm not sure, it sounds very specific in that issue about layout? I was just generally wanting it to be disconnected from the body.

**Comment by nehemiagurl** [comment] 2023-04-06 20:15
> Duplicate of _Replace hashtags with tags #2331_ (April 2017) ?

Seems like that request was asking for several things and got most of them done, which resulted in the closure of the issue. While I agree the separation was requested there and this one is technically a duplicate, I think it's best to keep them separated.

**Comment by bearmine** [comment] 2023-04-06 20:24
These two issues older issues seem to be the same or similar idea. #10743 and #23218

**Comment by tismark** [comment] 2023-04-06 20:55
I already commented on one of the older ideas but just adding in here that I feel like moving tags out of the content would benefit both people with screen readers and would look cleaner for sighted viewers as well.

**Comment by rkingett** [comment] 2023-04-06 22:19
This would make it easier to see content on smaller screens as well.

**Comment by FediVideos** [comment] 2023-04-06 22:43
> These two issues older open issues seem to be the same or similar idea. #10743 and #23218

Yeah, those seem much closer!

**Comment by RianQuenlin** [comment] 2023-04-08 01:06
Just an FYI, people with screenreaders can configure it to not read out hashtags as such. I asked about this a while ago.

**Comment by rdela** [comment] 2023-04-08 14:18
> Just an FYI, people with screenreaders can configure it to not read out hashtags as such. I asked about this a while ago.

I have never heard that personally, although [CamelCase seems to be recommended](https://duckduckgo.com/?q=screenreaders+hashtags). Like so many issues related to access, this change would benefit sighted and non-sighted people. I do not use a screenreader or assistive devices but would welcome this change as an author and a reader.

**Comment by patrickhlauke** [comment] 2023-04-08 17:15
> Large numbers of tags can cause serious problems for screen reader users, especially if there is no warning that they are about to encounter a tag list. Some screen reader apps are forcing blind people to sit through long lists of hashtags just so they can get to the alt text of the post's attachments.

just on that point, i'd mention that screen readers aren't "forcing" anything. screen reader users aren't just passive little puppets at the mercy of their software. they have a full set of controls to easily and efficiently navigate through structured content (more than even just non-screen-reader-using keyboard users do). this point smacks a little bit of "somebody think of the poor blind people" and speaking *for* them, without checking what their actual lived experience in fact is...

**Comment by deborahgu** [comment] 2023-04-08 17:31
Seconding @patrickhlauke, and adding that when it comes to hashtags, bad UX for screen reader users is exactly the same as the bad UX for sighted users. If someone is going to write a #post #like #this or worse, #likethis #theworstindoftagging, sighted users are unhappy as well. As long as the tagspam is all at the end of the post, screen reader users can do exactly what sighted users can do: skip to the next post in their reading and ignore all the tags.

I'm agnostic as to the UI requested here, but this is not an accessibility issue.

**Comment by ChasBelov** [comment] 2023-04-10 06:13
Full disclosure: I do not use a screen reader.

The advantage of hashtags being listed separately from the body post is that they could be read out one at a time, as if there were commas between them, without saying the word "hashtag" every time; they would need to be preceded with an announcement such as "hashtags follow". The disadvantage of hiding hashtags rather than placing them at the end is it makes them unavailable for the toot reader who might need them to formulate a search query.

Possible code (at the very scratch level and probably not yet ready for implementation):

`<div class=" hashtags" aria-label="Hashtags follow: firstHashtag, secondHashtag, thirdHashtag">#firstHashtag #secondHashtag #thirdHashtag</div>`

**Comment by aardrian** [comment] 2023-04-10 16:32
Indeed, `aria-label` is [restricted to](https://html5accessibility.com/stuff/2020/11/07/not-so-short-note-on-aria-label-usage-big-table-edition/) interactive bits, widgets, and named landmarks; though more broadly look at [what _cannot_ get an accessible name](https://w3c.github.io/aria/#namefromprohibited) using this or `aria-labelledby`. Also, `aria-label` probably [will not auto-translate](https://adrianroselli.com/2019/11/aria-label-does-not-translate.html#Update05). And to bolster Pat's point, [blaming screen readers](https://adrianroselli.com/2021/10/blaming-screen-readers-red-flag.html) is an easy strawman here.

Separately:
> There is a lot of unnecessary drama in the community right now because of how many hashtags people are using. If we listed them separately everyone would be happy.

I am unaware of such drama, but perhaps I am not following the right hashtags to see it. But asserting that listing them separately would make _everyone_ happy feels like a stretch without some data backing that up.

**Comment by JunkMuffler** [comment] 2023-04-10 17:42
I feel like a number of folks here are probably not connected to the art community as a whole, so I've created a short video that illustrates the problem. 

https://youtu.be/uR2t_iAFpO8

Using the default screen reader on a Google Pixel 6 running the latest version of Android, there isn't a good way for a blind individual to skip past the hashtags and get to the alt text. (Yes, you can tap directly on the photo, but that's not something all screen reader users can do). 

In the art community people use a boatload of tags to improve discoverability, and that's not something that's going to change. If you're a working artist, using a ton of relevant hashtags is a great way to get new customers. 

The number of hashtags used in my demo post is very, very small comparatively.

**Comment by ChasBelov** [comment] 2023-04-10 18:07
Thank you for the feedback on aria-label. Given that feedback, I've got another few possibilities. Brainstorming here.

Option 1:

```
<div class="hashtags" aria-description="Hashtags follow: firstHashtag, secondHashtag, thirdHashtag">
  <span aria-hidden="true">#firstHashtag #secondHashtag #thirdHashtag</span>
</div>
```

However, this doesn't deal with the possibility that or aria-description may not be translated.

Option 2 (requires website to implement the .sr-only (screen reader only) class):

```
<div class="hashtags">
  <span class="sr-only">Hashtags follow:</span> 
  <span aria-hidden="true">#</span>firstHashtag<span class="sr-only">,</span> 
  <span aria-hidden="true">#</span>secondHashtag<span class="sr-only">,</span> 
  <span aria-hidden="true">#</span>thirdHashtag</span>
</div>
```

or maybe just:

```
<div class="hashtags">
  <span class="sr-only">Hashtags follow:</span> 
  <span aria-hidden="true">#</span>firstHashtag, 
  <span aria-hidden="true">#</span>secondHashtag, 
  <span aria-hidden="true">#</span>thirdHashtag</span>
</div>
```

since visible commas wouldn't harm anything and might even make a series of hashtags easier to read visibly.

**Comment by patrickhlauke** [comment] 2023-04-10 18:27
> Using the default screen reader on a Google Pixel 6 running the latest version of Android, there isn't a good way for a blind individual to skip past the hashtags and get to the alt text. (Yes, you can tap directly on the photo, but that's not something all screen reader users can do).

going by containers like you tried in the video is of course not the only way for somebody to navigate with Talkback. swipe up then down, or down then up, to change mode to navigation by words, lines, paragraphs, etc, which then lets you use swipe up / down to move around with that...

**Comment by JunkMuffler** [comment] 2023-04-10 18:42
> > Using the default screen reader on a Google Pixel 6 running the latest version of Android, there isn't a good way for a blind individual to skip past the hashtags and get to the alt text. (Yes, you can tap directly on the photo, but that's not something all screen reader users can do).
> 
> going by containers like you tried in the video is of course not the only way for somebody to navigate with Talkback. swipe up then down, or down then up, to change mode to navigation by words, lines, paragraphs, etc, which then lets you use swipe up / down to move around with that...

Swiping up or down only makes it start spelling out words one letter at a time. It doesnt bring up settings as you stated. Also, the settings under accessibility are pretty sparse. 

![Screenshot_20230410-143806](https://user-images.githubusercontent.com/71350963/230970508-30f35c7a-cb79-4daa-9785-3dbd680f42b8.png)

**Comment by patrickhlauke** [comment] 2023-04-10 18:45
@JunkMuffler [Browsing with a mobile screen reader](https://youtu.be/ev8ERS5Z3NU?t=145)

**Comment by aardrian** [comment] 2023-04-10 18:56
I want to qualify that roughly a quarter to a third of screen reader users are not blind. Please bear that in mind as solutions get tossed around. Especially when messing with accessible names, since those can strand voice control users if not implemented well.

@ChasBelov 

> Option 1

`aria-description` [support is imperfect](https://a11ysupport.io/tech/aria/aria-description_attribute). That is also the accessible description, not the accessible name, but the "prohibited from naming" thing I linked still applies (as in, no generic roles). Further, that approach makes all those linked hashtags hidden from screen reader users.

> Option 2 (requires website to implement the .sr-only (screen reader only) class):

The `.sr-only` class is not a screen-reader-specific class. While that class name is common (and `.visually-hidden` is [more appropriate of a class name](https://www.scottohara.me/blog/2017/04/14/inclusively-hidden.html)), add "Hashtags to follow:" only adds noise since, IME, screen reader users already know how hashtags work.

Using `aria-hidden` on the # can also confuse what is a hashtag versus what is not, especially if authors continue to stuff hashtags into the body of a post (which I anticipate they will do regardless of whatever community norms come to pass, owing to indoctrination lag and cross-posts).

I suggest making some different patterns and then testing each to find the least bad, and then running it by a group of blind users both within and outside the art community / channel / space.

**Comment by JunkMuffler** [comment] 2023-04-10 18:57
> @JunkMuffler [Browsing with a mobile screen reader](https://youtu.be/ev8ERS5Z3NU?t=145)

Same result regardless of the setting. 
https://youtu.be/M99fR5w-sxw

It's not like I pulled this out my butt man. This exists because screen reader users were complaining to the admins of our instance.

**Comment by aardrian** [comment] 2023-04-10 19:05
@JunkMuffler 
> This exists because screen reader users were complaining to the admins of our instance.

It would be good to get some data on their browsing habits elsewhere, expectations, and some breakdown of ratio of complaints to overall screen reader users. Starting with a survey and going from there might be a good start.

I say this because trying to build a solution for them without them in this discussion can end up creating more problems. I have seen the outcomes of _not_ involving the disability community in 'solutioneering' for the disability community (it even has a [dedicated catchphrase](https://en.wikipedia.org/wiki/Nothing_about_us_without_us) and piles of reinvented sign language gloves as evidence)

All that being said, having worked with and conducted two sets of tests with skilled screen reader users (both blind and not) on mobile devices (already familiar with twitter), the vast majority knew images appeared at the end of a post and either jumped to the next post and moved backward or (mostly) leaned on _explore by touch_ to get to the media. It might be worth asking if the users who are complaining use those techniques and, if so, what drawbacks those have for them. Those kinds of answers can uncover other barriers or opportunities.

**Comment by JunkMuffler** [comment] 2023-04-10 19:19
> @JunkMuffler
> 
> > This exists because screen reader users were complaining to the admins of our instance.
> 
> It would be good to get some data on their browsing habits elsewhere, expectations, and some breakdown of ratio of complaints to overall screen reader users. Starting with a survey and going from there might be a good start.

I 100% agree. The issues are as follows:

- Mastodon is not a great place for a consolidated discussion (which is what's happening here)

- Expecting that conversation to happen here is not reasonable. We're assuming the folks involved have GitHub accounts or even know what GitHub is. 

- Lastly, for the record, I don't support messing with Aria roles. I support the original proposal, which is not strictly an A11y issue. Who here loves looking at a wall of hashtags? Anyone? I sure as heck don't. 

This is an opportunity for us to be better than Twitter. It may have been prompted by the aforementioned complaints, but the solution is a win for everyone. 

There is literally no upside to anyone, regardless of their accessibility needs, to look at a wall of hashtags. Sticking them in their own field with a character limit resolves the issue.

**Comment by deborahgu** [comment] 2023-04-10 19:45
> There is literally no upside to anyone, regardless of their accessibility needs, to look at a wall of hashtags. Sticking them in their own field with a character limit resolves the issue.

Speaking as a disabled person who sometimes uses tumblr (which uses the "their own field"), there are downsides to this approach as well. Again, I'm _agnostic as to this overall proposal_ (although as a voice user, I agree that messing with accessible names is the wrong approach). Instances and apps will make the hashtag block low contrast, they'll make it auto truncate, they'll differ on whether the hashtag block is visible on replies and boosts and threads. On tumblr alone there are multiple different ways these UI issues have all been addressed, and one company writes all those UIs. 

Again, I am not voting on this proposal, only emphasizing that it is not an open-and-shut accessibility win.

@aardrian said

> especially if authors continue to stuff hashtags into the body of a post (which I anticipate they will do regardless of whatever community norms come to pass, owing to indoctrination lag and cross-posts).

They 100% absolutely will, so any solution will have to accomodate that pattern, or the changed affordance is itself an inaccessibility bug.  If I type "Celebrating #caturday with my friends!" will that:

* make caturday not a hashtag so it isn't searchable?
* reformat the post as "Celebrating with my friends!" and move the hashtag to the end block?
* make it a hashtag that appears inline and also in the end block?
* block me from posting?

**Comment by aardrian** [comment] 2023-04-10 20:17
@junkmuffler

>I 100% agree.

Cool. When you build that survey, consider a question about which community they belong to (so the blind SR-using art community responses can be broken out and compared/contrasted). Then I am happy to share/promote it.

In the meantime, I will consider this issue a stub awaiting data.

**Comment by JunkMuffler** [comment] 2023-04-10 20:23
> @JunkMuffler
> 
> > I 100% agree.
> 
> Cool. When you build that survey, consider a question about which community they belong to (so the blind SR-using art community responses can be broken out and compared/contrasted). Then I am happy to share/promote it.
> 
> In the meantime, I will consider this issue a stub awaiting data.

Sure. Is there a particular service which is preferable? Google Forms? Something else?

Also, what other questions would be useful to add? The types of questions asked and the way they're asked frequently bias results. So I'd like some input from the folks here on what would be useful to include. :)

**Comment by ChasBelov** [comment] 2023-04-10 20:46
@deborahgu: For "Celebrating #caturday with my friends!" I would expect the toot to read:

"Celebrating caturday with my friends!" (hash mark stripped, but hashtag text untouched)

and the hashtag list would show:

#caturday

The next question is how to handle camelCaps or PascalCaps hashtags. Maybe:

"Celebrating #caturdayEve with my friends."

would post as:

"Celebrating caturday Eve with my friends."

and the hashtag list would show:

#caterdayEve

Since Mastodon allows editing posts, the cost of a poster's mistake in this area is low.

**Comment by aardrian** [comment] 2023-04-10 20:53
@ChasBelov 

None of these have links still. In the [sample post](https://mastodon.art/@junkmuffler/109915751196373584) in the video above, each of those hashtags is a link. I know they are not underlined or styled in any identifiable way (Mastodon [chose not to use underlines](https://github.com/mastodon/mastodon/pull/9898) despite overwhelming support).

Without links, those patterns are ignoring the very real risk of stranding voice control users when applied to hashtags that have links (which is all hashtags all the time). I appreciate the effort, but it does not apply.

**Comment by bearmine** [comment] 2023-04-10 20:56
> @deborahgu: For "Celebrating #caturday with my friends!" I would expect the toot to read:
> 
> 
> 
> "Celebrating caturday with my friends!" (hash mark stripped, but hashtag text untouched)
> 
> 
> 
> and the hashtag list would show:
> 
> 
> 
> #caturday
> 
> 
> 
> The next question is how to handle camelCaps or PascalCaps hashtags. Maybe:
> 
> 
> 
> "Celebrating #caturdayEve with my friends."
> 
> 
> 
> would post as:
> 
> 
> 
> "Celebrating caturday Eve with my friends."
> 
> 
> 
> and the hashtag list would show:
> 
> 
> 
> #caterdayEve
> 
> 
> 
> If that's too fraught, it could just post as:
> 
> 
> 
> "Celebrating caturdayEve with my friends."
> 
> 
> 
> with the same hashtag list.
> 
> 
> 
> Since Mastodon allows editing posts, the cost of a poster's mistake in this area is low.

I completely disagree with this approach. If someone adds a hashtag to the post body, it should stay in the post body exactly as the user put it. The hashtag metadata field/list should be in addition to the already supported hashtag system, and both in body and field/metadata hashtags should be searchable in the same way.

We're shouldn't be trying to remove hashtags, we should be adding flexibility.

**Comment by ChasBelov** [comment] 2023-04-10 21:03
@bearmine: Respectfully, the whole point of this issue was that inline hashtags are problematic for accessibility and need to go. Whether that is true or not may need to be determined, but proposed solutions need to reflect the original problem statement.

**Comment by ChasBelov** [comment] 2023-04-10 21:29
[aardrian](https://github.com/aardrian), thank you. Once more, with links as currently implemented on Mastodon, which is:

`<a href="/tags/firstHashtag" class="mention hashtag status-link" rel="tag">#<span>firstHashtag</span></a>
`
Option 1: Hear "hashtag" once, with pauses in between hashtags:

```
<div class="hashtags">
  <span class="visually-hidden">Hashtags: 
<a href="/tags/firstHashtag" rel="tag">firstHashtag</a>,
<a href="/tags/secondHashtag" rel="tag">secondHashtag</a>,
<a href="/tags/thirdHashtag" rel="tag">thirdHashtag</a>,
</span>
  <span aria-hidden="true">
<a href="/tags/firstHashtag" class="mention hashtag status-link" rel="tag">#<span>firstHashtag</span></a>
<a href="/tags/secondHashtag" class="mention hashtag status-link" rel="tag">#<span>secondHashtag</span></a>
<a href="/tags/thirdHashtag" class="mention hashtag status-link" rel="tag">#<span>thirdHashtag</span></a>
</span>
</div>
```

Eliminating option 2, as the no-pause solution does not address one of the points of the problem statement.

Option 3: Hear "hashtag" on each hashtag, with pauses in between hashtags:

```
<div class="hashtags">
  <span>
<a href="/tags/firstHashtag" class="mention hashtag status-link" rel="tag"><span aria-hidden="true">#</span><span>firstHashtag</span></a>,
<a href="/tags/secondHashtag" class="mention hashtag status-link" rel="tag"><span aria-hidden="true">#</span><span>secondHashtag</span></a>, 
<a href="/tags/thirdHashtag" class="mention hashtag status-link" rel="tag"><span aria-hidden="true">#</span><span>thirdHashtag</span></a>
</span>
</div>
```

**Comment by aardrian** [comment] 2023-04-10 22:29
@ChasBelov

> Option 1: Hear "hashtag" once, with pauses in between hashtags:

As coded, that is a guaranteed WCAG failure since focus can go to hidden controls (meaning the [focus is hidden](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html)).

> Option 3: Hear "hashtag" on each hashtag, with pauses in between hashtags:

As coded, since the # is within `aria-hidden`, the # will not be announced (as "hashtag" or anything). It also can be tricky for voice control users (but maybe only the first time?) since part of the accessible name is programmatically removed. The pauses may or may not be welcome since it means a user has to wait that much longer to get through the wall of hashtags (this presumes users never add commas between hashtags, which can get interesting). So while I don't think there is a WCAG violation out of the gate, user testing would be warranted.

**Comment by ChasBelov** [comment] 2023-04-10 23:35
@aardrian Aha, I misunderstood how aria-hidden works with regard to focus. Okay, scratch option 1.

And I guess added pauses aren't needed either, since screen readers will announce each link as being a link. So, modified option 3:

```
<div class="hashtags">
  <span class="visually-hidden">Hashtags:</span>
  <a href="/tags/firstHashtag" class="mention hashtag status-link" rel="tag"><span aria-hidden="true">#</span><span>firstHashtag</span></a>
  <a href="/tags/secondHashtag" class="mention hashtag status-link" rel="tag"><span aria-hidden="true">#</span><span>secondHashtag</span></a> 
  <a href="/tags/thirdHashtag" class="mention hashtag status-link" rel="tag"><span aria-hidden="true">#</span><span>thirdHashtag</span></a>
</div>
```

**Comment by trwnh** [comment] 2023-04-12 06:29
> Seems like that request was asking for several things and got most of them done, which resulted in the closure of the issue.

nope, #2331 was closed bc the user who filed the issue was banned from this repo/org so all their issues got auto-closed. other linked issues / duplicates:

- #7250 
- #10743 
- #23218

> There is literally no upside to anyone, regardless of their accessibility needs, to look at a wall of hashtags. Sticking them in their own field with a character limit resolves the issue.

if they were separated like this, they wouldn't have a character limit, they'd be separate tags

> I already see posts full of irrelevant hashtags as it is from people just trying to show up in feeds. I can only imagine what it would be like with no limit. If hashtags are excluded from the normal character count, consider an instance-configurable hashtag count?

maybe, but then you have to consider remote instances that override the limit or simply have a different limit.

> Also, I don't see it discussed above, but hashtags could be broken out into a separate property in the ActivityPub ActivityStreams vocabulary. There is even already a property called "tag". This makes semantic sense, taking tags out of the body altogether, but would be a larger change.

`Hashtag`s are already in `tag`. their inclusion in the text content is already optional.

**Comment by kit-repo-depot** [comment] 2023-04-12 16:46
The correct response to instances or users abusing a feature for SEO/visibility/spam is banning the user or instance the user is using, which is already the norm for vexatious instances. 

> this presumes users never add commas between hashtags, which can get interesting
In some implementations (tumblr springs to mind) the site disallows commas within or between tags, instead using a comma to create a new tag

**Comment by innosflew** [comment] 2023-04-20 06:14
It seems the Verge has also published an article on this recently: https://www.theverge.com/23673125/mastodon-separate-tags-hashtag-navigation-accessibility

**Comment by ChasBelov** [comment] 2023-04-20 16:53
For accessibility reasons, "The tag list would be displayed much less prominently, use a smaller font, and would include a warning at the beginning saying something like "tag list". use of a smaller font or lighter font would best be a user preference. I have difficulty reading shrunk or lighter fonts and it presents a cognitive load for me to process it.

I would argue that the accessible implementation be the default, so that it is available to not-logged-in site visitors, but if not the default at least make it an available option for user profile settings.

**Comment by volkriss** [comment] 2023-04-20 17:17
> For accessibility reasons, use of a smaller font or lighter font would best be a user preference. I have difficulty reading shrunk or lighter fonts and it presents a cognitive load for me to process it.

I think the idea is that tag lists are for computers to process, to engage with filters, and people aren't really expected to be processing them in the first place.

In this way of looking at it, tag lists aren't really part of the content, and this is getting them out of the way so that people can focus on processing the content itself.

**Comment by ChasBelov** [comment] 2023-04-20 17:19
"I think the idea is that tag lists are for computers to process, to engage with filters, and people aren't really expected to be processing them in the first place."

If it's important enough to show, it's important enough to be accessible.

Further, search on Mastodon is exclusively by hashtag, so it's important that hashtags be accessible to all.

**Comment by volkriss** [comment] 2023-04-20 17:43
> If it's important enough to show, it's important enough to be accessible.

I'll joke that I think the point is that the hashtag lists are not really important enough to show :)
At least by default alongside the body of the content.

But, oh, now I see your point here, that however this might be approached, it would be better if whatever solution kept visually accessible text.

So for example, instead of making the font small and light, maybe it could be a collapsed text area that anyone could open if they really wanted to see the tag list, one with full sized fonts.

**Comment by ChasBelov** [comment] 2023-04-20 17:46
As long as collapsing by default/showing by default is a preference and there is a collapse all/show all control at the top of the page, that's a great solution in general.

**Comment by ChasBelov** [comment] 2023-04-20 17:54
Actually, with regard to how to handle hashtags that have been inlined with the content, it could be a preference as to whether to leave them as is or remove the hash mark and copy the hashtag to the hashtag section if it's not already there. Default would be to leave as is, but users could override with their preference.

**Comment by Cragsand** [comment] 2023-04-22 22:01
Relevant to the discussion:
- Full text searching of posts
- Searching of all toots 
- Mastodon full-text searching 

Having an option to opt-in and just allow everything in the post to be searchable via elasticsearch or fuzzy search would remove the need for hastags entirely.

https://github.com/mastodon/mastodon/issues/21627#issuecomment-1332768678

**Comment by volkriss** [comment] 2023-04-23 03:01
> Having an option to opt-in and just allow everything in the post to be searchable via elasticsearch or fuzzy search would remove the need for hastags entirely.

Oh, well that's just not the case at all.
Many of us use hashtags to highlight key concepts in our posts and to search for those concepts that other people have labeled as key in theirs. It's an active, explicit tagging, part of the active composition process, that emphatically goes beyond full text, and so is not replaced by full text searching.

Not to mention, full text searching is a far, far bigger engineering topic than this one, about how best to handle display of existing functionality.

So it's really not relevant.

**Comment by trwnh** [comment] 2023-05-14 08:52
Duplicate of #10743

**Closed by trwnh** 2023-05-14 08:52 UTC
Labels: suggestion
