### ISSUE TITLE
Authorized Applications - Revoke All Tokens feature

### ISSUE THREAD

**Issue by jeffsikes** [mastodon/mastodon#29221] opened 2024-02-15 14:44 UTC
### Pitch

Currently there is no way for an end user to revoke all authorized application tokens en masse - you have to revoke them one by one. Because of how some apps configure their authorization schemes, users may end up with copious amounts of applications that need to be revoked.

A Revoke button could be added to the top of the [Authorized Apps page](https://mastodon.social/oauth/authorized_applications) which could do one of the following:

* Remove all tokens across the board
* Remove all tokens not utilized in the past 60 days 

In addition, I'd suggest either allowing various sorts on the list, or at least sorting by the "Last Used On" date, which is probably plenty for most sane people.

* Sort by Last Used On Date (Descending by default)
* Sort by Authorized Date (Descending by default)
* Sort by App Name, Last Used On Date (Ascending by App Name, Descending by Date)

### Motivation

This would be a good tool to have for end users when a security incident occurs (stolen password, a security patch on the server, etc.) so they can start fresh quickly and easily with new tokens after resolving the breach.

Right now, I have a **majestic** amount of authorized apps - many of them my own doing as a tinkerer with the Mastodon API used in client side scripts. I'm sure I'm not the only one out there. It would take me forever to go through my list and revoke each one by hand right now.

There is also no API endpoint to call to list these apps or revoke the tokens.

As requested, I'm tagging @ThisIsMissEm on this request.

Thanks for your consideration!

**Comment by trwnh** [comment] 2024-03-21 00:39
Duplicate of #8461

**Closed by trwnh** 2024-03-21 00:39 UTC
Labels: suggestion

**Comment by re6developer471** [comment] 2024-05-13 02:56
My passwords and accounts keep getting hijacked I'm trying to learn how to protect myself from my information being compromised and stolen

**Comment by ThisIsMissEm** [comment] 2024-05-13 10:23
> My passwords and accounts keep getting hijacked I'm trying to learn how to protect myself from my information being compromised and stolen

@re6developer471 some advice to prevent this: look at the permissions you grant when logging into an app, you can review apps by going "Preferences -> Account -> Authorized Apps", also, under "Preferences-> Account" you'll find Two Factor Authentication & change password settings.
