### ISSUE TITLE
UI strings: consistently use either “email” or “e-mail”

### ISSUE THREAD

**Issue by valtlai** [mastodon/mastodon#31258] opened 2024-08-01 22:11 UTC
### Steps to reproduce the problem

1. Log in to Crowdin.
2. Open all the strings: https://crowdin.com/editor/mastodon/all/en-engb
4. From the dropdown after the search field, select *Strings*.
4. Search for *email* and then *e-mail*.

### Expected behaviour

All the source strings should consistently have either “email” or “e-mail”, but not both.

### Actual behaviour

Both “email” and “e-mail” are used.

### Detailed description

At the moment of filing this issue, there are 49&nbsp;source strings that contain “email” and 70&nbsp;source strings that contain “e-mail”.

(The fix would require a mass change so I opened a GitHub issue as suggested. If the change is doable via GitHub, I can create a PR.)

**Comment by trwnh** [comment] 2024-08-02 10:56
Duplicate of #28317

**Closed by trwnh** 2024-08-02 10:56 UTC
Labels: bug, status/to triage
