### ISSUE TITLE
[Accessibility] Make alt text more accessible

### ISSUE THREAD

**Issue by orowith2os** [mastodon/mastodon#22049] opened 2022-12-04 21:40 UTC
### Pitch

I believe it would be beneficial to show the alt text next to the image when expanded, and have an "ALT" button that shows the alt text, similar to how Twitter does it (I think, haven't checked in a while).

### Motivation

Currently, for alt text, I have to hover over the image to view it. I didn't know this feature was there, I assumed it was a client-specific thing, as I've only seen the alt text on Tusky until now.

**Comment by orowith2os** [comment] 2022-12-04 23:54
I think this builds on top of that a bit, but yeah, might be able to be considered a duplicate.

**Comment by ineffyble** [comment] 2022-12-07 11:44
Closing as duplicate of #18394, have made sure the wording here was copied.

**Closed by ineffyble** 2022-12-07 11:44 UTC
Labels: suggestion
