### ISSUE TITLE
Direct messages

### ISSUE THREAD

**Issue by mackiexx** [mastodon/mastodon#19313] opened 2022-10-07 23:26 UTC
### Pitch

I noticed that direct messages shows on feed also instead of showing when you click to your inbox. This is very inconvenient and can be confusing. it should be fixed. Thank you for the work you are doing

### Motivation

At first i was thinking my direct message was been seen by everyone, it will be great to keep the DM in the inbox so users won't be confused.

**Comment by trwnh** [comment] 2022-10-08 03:38
Current "direct messages" are just regular posts, like followers-only posts but limited to people mentioned.

Related:
- #15914
- #17445
- #3819

**Comment by kescherCode** [comment] 2022-10-09 11:21
In the glitch-soc Web UI fork, this is solved by highlighting the DM status background on feeds, in replies, etc. in a different color. Not to mention the much more visible status icons, because they're filled icons and also colorized.

![Normal posts using the default mastodon gray background, while a direct message is highlighted in a lighter gray](https://user-images.githubusercontent.com/23276523/194754012-13fbe383-a246-47d4-b4fd-a80358da6d2b.png)

**Comment by mxamber** [comment] 2022-10-09 11:24
Also on glitch, hiding DMs from the timeline is already a thing:

![image](https://user-images.githubusercontent.com/13611718/194754140-2bbeac66-5117-480f-894a-16b8a757ea8d.png)

**Comment by easrng** [comment] 2022-10-09 13:09
Pinafore also has a different background color for DMs.

**Comment by shleeable** [comment] 2022-10-15 02:35
Ask the admin to consider https://github.com/mastodon/mastodon/pull/15594

I've done that on my instance.

**Comment by mackiexx** [comment] 2022-10-16 13:21
> Ask the admin to consider #15594
> 
> I've done that on my instance.

How did you do it?

**Comment by trwnh** [comment] 2023-05-16 04:44
Duplicate of #3819

**Closed by trwnh** 2023-05-16 04:44 UTC
Labels: suggestion
