### ISSUE TITLE
Timeline jumps around due to incoming toots

### ISSUE THREAD

**Issue by nolanlawson** [mastodon/mastodon#5491] opened 2017-10-20 21:25 UTC
2.0.0. Steps to repro:

1. In mobile Chrome 64 for Android, go to the local/federated timeline
2. Scroll down a page or two
3. Do nothing
4. Watch incoming toots change your scroll position

I thought this was fixed awhile ago, but we may have regressed due to https://github.com/tootsuite/mastodon/commit/ca0e8be20cf35cce88b17e852448122219c0914f. My hunch is that we are incorrectly calculating the rect size for hidden statuses, perhaps in the case of statuses with images/CWs/something else.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sorin-davidoi** [comment] 2017-10-21 23:19
Investigated this a bit (only on desktop, unfortunately). Pasting the following into the console on the federated timeline (mobile view) should show if the height of the toots differ when they are recycled. It prints warnings on Firefox Nightly but not on Chrome 62.

```js
const feed = document.querySelector('.item-list[role="feed"]');
const articles = new WeakMap();

const articleObserver = new MutationObserver(function(mutations) {
    mutations.forEach(function(mutation) {
        const article = mutation.target;
        const pastHeights = articles.get(article);
        const lastHeight = pastHeights[pastHeights.length - 1];
        const height = article.getBoundingClientRect().height;

        if (lastHeight !== height) {
            const description = !!article.style.height ? 'show -> hide' : 'hide -> show';
            console.warn(description, height - lastHeight, article);
        }

        articles.set(article, [...pastHeights, height]);
    });
});

const feedObserver = new MutationObserver(function(mutations) {
  mutations.forEach(function(mutation) {
    if (mutation.addedNodes.length === 1) {
        const article = mutation.addedNodes[0];
        const height = article.getBoundingClientRect().height;
        articles.set(article, [height]);
        articleObserver.observe(article, { childList: true });
    } else {
        console.log(mutation);
    }
  });    
});

feedObserver.observe(feed, { childList: true });
```

Maybe it would make sense to include a variant of this snippet into the codebase (wrapped in `if (process.env.NODE_ENV === 'development')` in order not to ship it).

**Comment by nolanlawson** [comment] 2017-10-22 19:52
I've managed to reproduce this locally, using [a small script](https://gist.github.com/nolanlawson/d48e5fab0e4b41a9d01e6b9e3757e7f9) that just posts random toots into the timeline (you can run it in a script).

I've determined that it has nothing to do with `get_rect_from_entry.js` or `intersection_observer_article.js`, because you can reproduce it even if we never hide toots. The offending code seems to be this: https://github.com/tootsuite/mastodon/blob/fdb0848e08f34ee967ae2d0ad24cd994e996169b/app/javascript/mastodon/components/scrollable_list.js#L84-L92

So ironically the code that is trying to avoid jerky scrolling is causing jerky scrolling. :confused:

If we remove it entirely, then we remove the jerkiness from Chrome. The reason you're seeing a difference between Chrome and Firefox AFAIK is because Chrome has an intervention to avoid jerkiness when a scrollable element has items added to the top.

I've tried a few different things, but I think the only way to fix this may be to make it so that when new items arrive at the top, if you're not scrolled to `0` then the new items should just have a height of 0 until you scroll them into view.

**Comment by nolanlawson** [comment] 2017-10-22 20:08
Also I think not inserting new toots would be better for battery life, because right now if you have a tab of Mastodon pinned, it'll just keep rendering DOM nodes for every new toot that comes in, even if you're not looking at it.

**Comment by nolanlawson** [comment] 2017-10-29 05:42
It seems that the reason this is happening is that, if new toots arrive _while the user is scrolling_, the above algorithm can't properly figure out how many pixels to offset the new scroll by. It can't tell the difference between the scroll position changing due to user input and the scroll position changing due to incoming toots.

One way we could solve this: new statuses get rendered as zero height (hidden). In the IntersectionObserver algorithm, zero-area elements are automatically "interesting" once they're scrolled into view, so we could just let them become rendered at that point. I.e. when you scroll to the top, all the new toots get rendered at once.

**Comment by nolanlawson** [comment] 2017-10-29 17:04
On second thought, that sounds too complicated. I think this just needs a redesign.

**Comment by nolanlawson** [comment] 2017-11-01 14:54
Either that, or maybe it's time to switch to a true virtual scrolling list.

**Comment by Cassolotl** [comment] 2018-02-26 22:10
Connecting things up: *Don't scroll the timelines (instance/global) when you're below the top #1306*

**Comment by trwnh** [comment] 2023-05-14 00:06
Duplicate of #1306

**Closed by trwnh** 2023-05-14 00:06 UTC
Labels: bug, ui
