### ISSUE TITLE
[MAS-139] Blocklist subscriptions

### ISSUE THREAD

**Issue by RokeJulianLockhart** [mastodon/mastodon#29022] opened 2024-01-31 01:37 UTC
### Pitch

The ability to subscribe to multi-instance blocklists in a manner which doesn't necessitate any manual intervention.

### Motivation

Blocklist management is difficult for administrators - it's a manual process despite the usage of centralized blocklists. Standardizing the subscription and implementation process would be helpful.

**Comment by trwnh** [comment] 2024-01-31 03:31
Duplicate of #116 and several others

**Closed by trwnh** 2024-01-31 03:31 UTC
Labels: suggestion
