### ISSUE TITLE
[Feature] Toot into other instances

### ISSUE THREAD

**Issue by FlorianKrammel** [mastodon/mastodon#9019] opened 2018-10-19 10:02 UTC
I'd like to see this feature. Write a toot and select some other instances to toot in their timeline, too.

**Comment by blubbll** [comment] 2018-10-28 17:13
you could make a bot for this :D

**Comment by sparr** [comment] 2018-12-31 20:47
Do you expect this to work when you do not have an account on that instance? Only when you do?

**Comment by trwnh** [comment] 2023-05-14 16:51
Duplicate of #6865

**Closed by trwnh** 2023-05-14 16:51 UTC
Labels: suggestion
