### ISSUE TITLE
Accounts switcher 

### ISSUE THREAD

**Issue by Jim707t** [mastodon/mastodon#22512] opened 2022-12-19 18:53 UTC
It would be a good feature to have a switcher account for  if you have multiple accounts on different server.

Personally I think it very tiring to logout and login in each time you wanna access one of them.

**Comment by eishiya** [comment] 2022-12-19 19:23
If this is about the web client: if your accounts are on different servers, you shouldn't need to log out and log in to switch accounts, as each web client is independent, you can have multiple of them logged in at the same time.

Multiple accounts on *one* instance is the only scenario which would benefit from the web client having account-switching, but this is rare, and clients designed for use with multiple instances (which the web client does not do by design) already handle that scenario by virtue of supporting multiple accounts.

If this is about some other client (the official iOS or Android apps, or a third-party app), you should post in their respective issue list instead of here.

**Comment by alxsimon** [comment] 2022-12-19 19:44
> Multiple accounts on one instance is the only scenario which would benefit from the web client having account-switching, but this is rare

This one will be increasingly not rare. I have a lot of personal accounts on my server that also manage organization accounts. Having an account switch on the same server is a must have I think. Requiring the use of third party workarounds (like firefox multi-account containers) is not a panacea.

**Comment by ClearlyClaire** [comment] 2022-12-20 09:03
Duplicate of #21291 indeed!

**Closed by ClearlyClaire** 2022-12-20 09:03 UTC
Labels: suggestion
