### ISSUE TITLE
Support .*webp

### ISSUE THREAD

**Issue by AnonymousWebHacker** [mastodon/mastodon#16624] opened 2021-08-17 05:54 UTC
### Pitch

Mmastodon does not allow that type of file *webp

### Motivation

The telegram or whatsapp stikers are in * .webp and mastodon does not allow that type of file

**Comment by tribela** [comment] 2021-08-28 07:17
Was added on #9879 and removed on #11589
I think it is OK to resupport webp now.

**Comment by AnonymousWebHacker** [comment] 2021-08-28 18:28
I had not really dedicated myself to looking for any issuse related to this.

Thanks for the reference. :+1:

**Comment by sindastra** [comment] 2021-11-05 19:59
This issue seems to be a duplicate of #13315

**Closed** 2022-05-27 18:06 UTC

**Comment by Sushubh** [comment] 2022-12-23 18:41
Not sure if I should file a bug report for this. But webp images do not seem to work with "Detect text from picture" functionality.
