### ISSUE TITLE
some warings on RAILS_ENV=production bin/tootctl command

### ISSUE THREAD

**Issue by Tealk** [mastodon/mastodon#17214] opened 2021-12-30 18:22 UTC
### Steps to reproduce the problem

1. go into console
2. type `RAILS_ENV=production bin/tootctl media remove --days 30` as user

### Expected behaviour

the media should be deleted

### Actual behaviour

the media will be deleted but before that the following warnings will be displayed

### Specifications

 Mastodon 3.4.4
Ruby 2.7.2p137
PostgreSQL 11.14
Redis 
```
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
```

**Comment by ClearlyClaire** [comment] 2022-01-01 09:13
These warnings have no known consequence, and they have been fixed in the development version. Duplicate of #16353

**Closed by ClearlyClaire** 2022-01-01 09:13 UTC
Labels: bug

**Comment by JLoDoesIt** [comment] 2022-03-01 09:54
I see one consequence while generating SECRET_KEY_BASE, output is polluted (see **in bold** below)

SECRET_KEY_BASE=$(docker-compose run --rm web bundle exec rake secret)
6aec...[...]...409cbc**as hereewas here**

I then need to run these entries with the remove warning option
SECRET_KEY_BASE=$(docker-compose run --rm -e RUBYOPT=-W0 web bundle exec rake secret)
