### ISSUE TITLE
Toot in Home timeline has @username@instance link that opens in new tab

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#6839] opened 2018-03-19 21:36 UTC
This toot in my Home timeline on dev.glitch.social (different) and ephemeral.glitch.social (vanilla): https://framapiaf.org/@davidrevoy/99710853683679624

When I click the link that looks like `@krita`, it opens in a new tab instead of in the far-right column. Other `@username@instance` are opening in the far-right column as expected.

This toot doesn't have the same problem: https://framapiaf.org/@davidrevoy/99711319588122914 (It's on framapiaf.org and the `@username@instance` is pointing at a user on mastodon.art, same as the weird toot situation.)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment] 2018-03-19 22:26
I'm pretty sure the krita account is a special case because it sounds like the casing if the username was changed already after the account federated to other places, resulting in unexpected behavior.

**Comment by Cassolotl** [comment] 2018-03-19 22:27
Alright, I'll close this, it sounds like it's not a general bug. Thanks!

**Comment by Cassolotl** [comment] 2018-03-19 22:29
(Related to *Usernames on webapp are case-sensitive, but not on profile URL #6837*)

**Comment by trwnh** [comment] 2018-03-19 22:52
Something similar happens in non-Mastodon apps. For some reason, some of them return mentions not as `instance.tld/@name` but instead as `instance.tld/users/name`. This also makes it possible to, say, link to `mastodon.social/users/gargron` while having the mention show up as `@Gargamel`.

Example from Pleroma: https://pleroma.dereferenced.org/objects/2c34ac9f-2b40-47bd-a975-b2c21fc7f23f

The above post in the webapp will load remote Pleroma users fine in the side column, e.g. `social.i2p.rocks/users/jeff`, but clicking my own name in the webapp will open a new tab linking to my profile `mastodon.social/users/trwnh`. Whereas when communicating with other Mastodon users, mentions will instead resolve to `mastodon.social/@trwnh` and load perfectly fine in the webapp.

Not sure this is the same issue, and it most likely has to do with how e.g. Pleroma handles canonical URLs for users, but it could very well be related? What I just described is more about the title of this issue and not the body of OP.

**Comment by Cassolotl** [comment] 2018-03-20 08:19
Oh okay! If it might not be the same issue I'll reopen it.

**Comment by Gargron** [comment] 2018-03-20 08:35
The mention links work correctly when the URLs used in the text body are the same as the ones the mentioned accounts have. Otherwise they can't be matched to tell them apart from normal links.

https://github.com/tootsuite/mastodon/blob/master/app/javascript/mastodon/components/status_content.js#L42

**Comment by trwnh** [comment] 2018-03-20 08:47
Would it break anything to do some disambiguation? Or, is there a difference between `instance.tld/@name1` and `instance.tld/users/name` besides the URL? Because they seem to resolve to the same thing. Just wondering if any part of the server or webapp depends on / is always expecting one schema or the other.

**Comment by Gargron** [comment] 2018-03-20 08:58
`instance.tld/users/name` is the canonical URI. `instance.tld/@name1` is the URL. The URL is specifically meant for displaying to end-users, unlike the URI. Afaik the URI is not even exposed in our REST API, because there was no need for it.

I guess we might wanna ask @lambadalambda if Pleroma uses URIs as URLs over actually provided URLs somehow.

**Comment by lambadalambda** [comment] 2018-03-20 09:07
yes, that's the reason. we use the AP id to link to mentions.

**Comment by Gargron** [comment] 2018-03-20 10:42
Dunno which way to resolve this. If I start exposing the URI in the REST API and fix the web client to check  the hrefs against both, it will still leave a bunch of apps to fix it on their own, and I can't say that checking against both values sounds very elegant to me, it's very obvious guessing at that point. The HTML markup legacy of OStatus is a pain in the ass for all app developers.

**Comment by lambadalambda** [comment] 2018-03-20 12:25
Hard to say. I think you'll just have to check for both, it was guessing before already, you were just always guessing right :)

**Comment by ThibG** [comment] 2018-03-27 16:18
I'd say that both implementations are reasonable, with Pleorma's being more straightforward, and Mastodon using profile URLs that are guaranteed to make sense in the body of statuses… (obviously the spec says nothing about all of this)
But Mastodon is already doing the more “elaborate” guesswork, so I think it's Mastodon's job to also handle the more straightforward case of having the actor id used instead of the actor web profile URL in mentions.

**Comment by Cassolotl** [comment] 2022-12-27 07:36
I'm just rambling through old issues that are coming up in incidental searches, and this one is 4 years old but I don't understand the issue well enough to know whether it's resolved yet?

(I've not bumped into a handle in a post that opened in a new tab instead of in the web UI for ages, but that might be because my follows are mostly Mastodon now...!)

**Comment by trwnh** [comment] 2023-05-14 07:34
conceptually a duplicate of #1399

**Closed by trwnh** 2023-05-14 07:34 UTC
Labels: bug
