### ISSUE TITLE
Feature request: Add bookmarklet to guide and propose the user to use it

### ISSUE THREAD

**Issue by dpriskorn** [mastodon/mastodon#15643] opened 2021-01-30 14:21 UTC
### Pitch

I just signed up for diaspora and mastodon. Diaspora gave me an easy to use bookmarklet that gets out of my way after sharing want I wanted to share. I found a third party bookmarklet for mastodon and tested it out see https://github.com/egils-consulting/mastodon-toot-bookmarklet but it does not close itself after I posted.

The bookmarklet is easy available in the left menu in case I sign in on another browser which is very nice.

I think you should learn from diaspora and ship a bookmarklet and tell and show users how to use it  (maybe in a video).

### Motivation

Every single user using a browser would benefit from this. It makes it dead-simple to post anything easily.

**Comment by vmstan** [comment] 2023-11-17 15:37
Closed as duplicate of #21384 which has some additional discussion.

**Closed by vmstan** 2023-11-17 15:37 UTC
