### ISSUE TITLE
Hashtag autocomplete suggestions should respect CamelCase entry instead of suggesting all lowercase tags

### ISSUE THREAD

**Issue by harryteasley** [mastodon/mastodon#25419] opened 2023-06-14 07:45 UTC
### Pitch

If I start entering "#DogsOfMas" in a post, it will suggest "#dogsofmastodon" as an autocomplete option. It is ignoring the case I've deliberately entered, and will modify my entry if I allow it to autocomplete. Autocomplete is useless to me because of this, as I believe it important to favor CamelCase (PascalCase, if you're inclined that way) in hashtags.

### Motivation

Screen readers for the vision impaired have real trouble with all lowercase hashtags that are a concatenation of words. Mastodon should favor CamelCase hashtags over all lowercase for accessibility reasons, and should always respect user entered case when offering autocomplete suggestions.

**Comment by trwnh** [comment] 2023-06-15 10:35
Duplicate of #9913 and/or #20267

**Closed by trwnh** 2023-06-15 10:35 UTC
Labels: suggestion
