### ISSUE TITLE
Advanced Web Interface option does not use available space.

### ISSUE THREAD

**Issue by ctag** [mastodon/mastodon#11413] opened 2019-07-26 20:04 UTC
### Expected behaviour

The advance web interface option is listed as "make use of entire screen width" I would expect it to do so.

![image](https://user-images.githubusercontent.com/6200085/61978242-5f57a980-afb6-11e9-98a3-bb81ca5857de.png)

### Actual behaviour

But enabling it only increases horizontal usage slightly, while crushing the existing columns with additional elements.

![image](https://user-images.githubusercontent.com/6200085/61978298-8615e000-afb6-11e9-969f-689831928ce8.png)

Modifying the main posts column's Flex CSS brings the page to use all available space.
![image](https://user-images.githubusercontent.com/6200085/61978269-6bdc0200-afb6-11e9-8579-47e206d3325f.png)

### Steps to reproduce the problem

Enable Advanced Web Interface.

### Specifications

Mastodon 2.9.2

I am using Firefox on Linux.

**Comment by palmerito0** [comment] 2020-03-03 04:47
Agreed here. Would be nice to either fill available space or make the column widths adjustable

**Comment by Yowlen** [comment] 2020-07-16 01:29
My issue is different in that it happens in the opposite direction. i.e. adding extra columns ends up having the last column partially go off the edge of the screen. However, I'm commenting here because my issue is caused by the same thing as yours.

Specifically, I've narrowed it down to a rogue `flex: 0 0 auto` field in the `components.scss` file.
![Screenshot_2020-07-15_21-08-39](https://user-images.githubusercontent.com/17078692/87615072-ca2a5500-c6df-11ea-8d73-a9570ccce653.png)

Disabling this particular line using the Inspector in Firefox's Developer Tools lets it inherit the `flex: 1 1 auto` field from its parent.
![Screenshot_2020-07-15_21-17-01](https://user-images.githubusercontent.com/17078692/87615363-913eb000-c6e0-11ea-872a-6092b73f608d.png)

Nothing else needs to be done. Just disable that one and it works. In fact, disabling this one even corrects the nav-bar column to display at the full default width at the expense of the other columns to ensure that at least the most important column is visible regardless of the size of the others.

Also worth noting that modifying this field for one of the columns will modify it for all of them since the css element in question is used for all of them. It's just that some changes appear to be happening somewhere else to automatically weigh each column based on importance -- changes which this particular field appears to override.

**Comment by testman42** [comment] 2021-08-28 18:55
I'm interested as well in seeing this get solved.

**Comment by Oblomov** [comment] 2022-05-03 20:26
Any chance of this getting fixed in the default stylesheet? Having to hack around the default using CSS injection or in-browser user styles is a bit of a bother.

**Comment by brendanjones** [comment] 2022-11-03 18:19
This is still an issue. Should be a really simple CSS fix, no? 

Happens in Firefox on MacOS, haven't tested on other browsers.

<img width="1792" alt="Screen Shot 2022-11-03 at 19 09 52" src="https://user-images.githubusercontent.com/16049594/199802916-5c0559ea-8977-4c39-af39-91bd7df10b76.png">

**Comment by jducoeur** [comment] 2022-11-03 23:17
Also happens on Chrome, so I think it's basically affecting everyone.

**Comment by Gargron** [comment] 2022-11-03 23:47
It's intended for you to fill the space with more columns.

**Comment by jducoeur** [comment] 2022-11-04 00:36
Right, but many of us don't *want* more columns -- four is plenty for me, and only fills my screen maybe halfway across.  (It's actually a very pleasant experience.)

Moreover, the point of flex is that the column width dynamically resizes based on the number of columns: there is no need to leave space for additional ones. If you add more columns, the existing ones will just narrow a little.

**Comment by brendanjones** [comment] 2022-11-04 13:30
> It's intended for you to fill the space with more columns.

That's moot - if the existing columns do not fill the screen width then they should dynamically resize to fill the screen. With some min/max dimensions of course - you don't want the columns resizing to fill an ultrawide monitor, and you need breakpoints for smaller dimensions.

For me I'd prefer if only the Home and Notification columns resized, but you could also resize all columns equally. Would be cool if you could resize the columns yourself and the proportions were stored.

**Comment by th0rsten** [comment] 2022-11-20 15:56
Yes, of course a 4-column layout should always make use of all available horizontal real estate. This is such an easy fix. 

Incidentally, lots of instances do this already, perhaps through local fixes.

**Comment by th0rsten** [comment] 2022-11-20 16:09
> It's intended for you to fill the space with more columns.

Just for the sake of argument, how would I even do that? 

(And I completely agree with [brendanjones](https://github.com/brendanjones): when there ARE no additional columns, the space should be used.)

**Comment by stepheneb** [comment] 2022-11-21 04:53
> > It's intended for you to fill the space with more columns.
> 
> Just for the sake of argument, how would I even do that?

Basically do a search of some type (example #FreeCad) then pin the column. Now do a second search and pin that column.

Currently I'm overiding with this custom local stylesheet:

```css
div#mastodon .drawer,.column {
  flex: 1 1 auto !important;
  min-width: 300px !important;
  max-width: 475px !important;
}
div#mastodon .drawer {
  max-width: 425px !important;
}
div#mastodon .column[aria-label="Notifications"] {
  max-width: 425px !important;
}
```

I can choose to have more columns than fit on my large monitor and then I horizontally scroll.

Mastodon web app v4.0.2;

**Comment by brendanjones** [comment] 2022-11-26 14:39
Suggestion: while this is being argued over can we do one very simple fix: can we centre everything on the screen instead of it being aligned left? I unfortunately don't have the coding skills or I'd make the PR myself ...

**Comment by testman42** [comment] 2022-11-26 22:43
I did not see #8632 referenced here yet. Tagging it just in case that you dudes are not aware of it yet.

**Comment by krc** [comment] 2022-11-26 23:35
It's rather absurd at 2560 × 1440 , even after some space used by sidebery: 
![Screenshot_2022-11-26_masto_advanced](https://user-images.githubusercontent.com/211671/204112686-427fdc4e-7d4d-4418-b687-c107d56f63c6.png)

**Comment by pcantrell** [comment] 2022-11-27 17:35
People seem to like this set of CSS hacks: https://hachyderm.io/@inthehands/109369271004447690

There could be some things there to steal. (Please do.)

<img width="1716" alt="Screen Shot 2022-11-27 at 11 35 06 AM" src="https://user-images.githubusercontent.com/378162/204150847-0bd60cbe-750e-4701-b9c3-12f2bb998efc.png">

**Comment by rshyffer** [comment] 2022-12-23 20:04
Agreed this is an issue. I don't use Advanced Web Interface mode because of this. I wan't my home column to be wider.

**Comment by mjankowski** [comment] 2024-11-24 14:16
Closing on assumption that this will be done (many issues/conversations, all same conclusion).

**Closed by mjankowski** 2024-11-24 14:16 UTC
Labels: partially a bug, area/web interface

**Comment by brendanjones** [comment] 2024-11-26 13:39
Isn’t the convention to close an issue when it’s actually solved, not when it’s planned (or even assumed to be planned)?

**Comment by mjankowski** [comment] 2024-11-26 13:52
Yes, that is the convention! Sorry for typo in my last message - should have read "will NOT BE done"

There have been dozens of issues and PRs over the years asking for and/or doing this same exact thing. I personally believe it should be done and its awkward to not center it ... but the project core team a) does not accept outside design contributions, b) obviously believes otherwise -- so just closing this more of a wontfix. Apologies for any confusion caused by my typo there.

**Comment by brendanjones** [comment] 2024-11-27 16:02
Personally I think in an open source project like this it's best to keep these issues open to collect feedback. But if it's going to be closed can you please use the 'Closed as not planned'? It's very confusing if when you're wanting to report an issue you first search the existing issues and you find your problem closed as completed.

![Image](https://github.com/user-attachments/assets/9deab759-46b4-425c-ac1f-16203a2d8a66)

**Comment by Moilleadoir** [comment] 2026-04-27 12:20
An unresponsive design from unresponsive developers.
