### ISSUE TITLE
Clicking on a name who boosted something takes you to the wrong profile

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#17018] opened 2021-11-22 03:45 UTC
### Expected behaviour

A's profile loads

### Actual behaviour

B's profile loads

### Steps to reproduce the problem

1. Find a post where A boosted a post by B.
2. Click the display name link in "A boosted this"

### Specifications

mastodon.social

**Comment by ClearlyClaire** [comment] 2021-11-22 08:35
Duplicate of #16799

**Closed by ClearlyClaire** 2021-11-22 08:35 UTC
Labels: bug
