### ISSUE TITLE
New lists should get populated with existing toots

### ISSUE THREAD

**Issue by marians** [mastodon/mastodon#16290] opened 2021-05-22 10:55 UTC
I created a new list https://gruene.social/web/timelines/list/12 and added four accounts to it.

Three of them are actually on the same instance as my account (gruene.social). Not that this matters, really.

### Expected behaviour

I expected to see toots of the four accounts in that list showing up as a timeline (all toots by those accounts, sorted by date).

Not sure whether this is intended behaviour or not. If it is intendeded, this is a feature request. Otherwise it's  bug report.

The information text suggests that only new toots coming from the member accounts will appear in the list's timeline. In terms of a user experience, I would much prefer to see the list's timeline be populated with existing toots immediately.

### Actual behaviour

Where I expected a timeline, an empty space appears and a message

> Diese Liste ist derzeit leer. Wenn Wesen auf dieser Liste neue Beiträge veröffentlichen werden sie hier erscheinen.

([Source](https://github.com/tootsuite/mastodon/blob/main/app/javascript/mastodon/locales/de.json#L168))

In English, that is

> There is nothing in this list yet. When members of this list publish new posts, they will appear here.

<img width="588" alt="grafik" src="https://user-images.githubusercontent.com/273727/119223864-131b1900-bafc-11eb-9180-c5c4cade1318.png">

### Steps to reproduce the problem

1. Create a new list
2. Add at least one account to the new list
3. Open the list's timeline

### Specifications

Mastodon v3.3.0

**Comment by ClearlyClaire** [comment] 2021-05-22 11:30
That's indeed how lists work, they are not populated with existing toots unlike the Home timeline. I don't remember what was the original reasoning behind that, and there's now the extra complication that there are multiple settings regarding which replies to show.

**Comment by marians** [comment] 2021-05-22 12:27
Thanks for clarifying. Then it is in deed a suggestion/feature request.

**Comment by quicoto** [comment] 2022-11-10 07:52
To follow up on this, on 3.5.3 the lists don't get fresh posts as the Home timelime. I need to do a page refresh to see toots from the Home timeline appear in a List.

Is this by design?

**Comment by ClearlyClaire** [comment] 2022-11-10 08:28
This is not by design and not something I'm experiencing.

**Comment by quicoto** [comment] 2022-11-10 08:39
Thanks @ClearlyClaire for the quick reply.

Is there anything I could debug in Sidekiq or somewhere else to check why List queue is not auto refreshed like Home timeline? #20308

**Comment by ClearlyClaire** [comment] 2022-11-10 21:28
I don't think the issue would lie with sidekiq, but with the streaming server, or the client's connection to the streaming server. I am not sure how to best debug that, but you could start by making sure that `mastodon-streaming` is running and that the client manages to connect to the websocket endpoint (check the browser's console).

**Comment by quicoto** [comment] 2022-11-10 21:34
@ClearlyClaire Yep, seems like the issue goes into the streaming direction

```
GET wss://ricard.social/api/v1/streaming/? [HTTP/1.1 401 Unauthorized 123ms]

Firefox can’t establish a connection to the server at wss://ricard.social/api/v1/streaming/?. [index.js:60:85](webpack:///node_modules/@gamestdio/websocket/lib/index.js)
GET wss://ricard.social/api/v1/streaming/? [HTTP/1.1 401 Unauthorized 127ms]

Firefox can’t establish a connection to the server at wss://ricard.social/api/v1/streaming/?.
```

The service is up and running, though

```
● mastodon-streaming.service - mastodon-streaming
   Loaded: loaded (/etc/systemd/system/mastodon-streaming.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-11-10 12:56:11 CET; 9h ago
 Main PID: 9138 (node)
    Tasks: 18 (limit: 2315)
   CGroup: /system.slice/mastodon-streaming.service
           ├─9138 /usr/bin/node ./streaming
           └─9196 /root/.nvm/versions/node/v17.9.1/bin/node /home/mastodon/live/streaming
```

Any more good ideas? 😁

**Comment by quicoto** [comment] 2022-11-11 10:11
I have fixed it.

1) Correct user in the streaming.service file set to `mastodon`
2) Correct path to node (accessible from the user `mastodon`) in the streaming.service file

A good way do debug this is going into the `live` folder and run the `./streaming` node command. Which when  the FE called the `/api/v1/streaming/` endpoint it told me there was an issue with authentication

Thank you for the support

**Comment by marians** [comment] 2022-11-11 12:21
@ClearlyClaire Since this was a suggestion / feature request, what does the closing mean for this suggestion?

**Comment by ClearlyClaire** [comment] 2022-11-11 12:26
> @ClearlyClaire Since this was a suggestion / feature request, what does the closing mean for this suggestion?

Sorry, got it mixed up with @quicoto's issue. The behavior has not changed. Reopening.

**Comment by Terra100f** [comment] 2022-11-19 21:33
I am also experiencing this issue. I have lists but they don't populate with anything other that new toots. Also, if I log out and then log in, then the timeline starts over again and only the newest toots appear. It's really frustrating.

Sorry to compare to Twitter, but I really used lists there. It's an efficient use of my time. I had about 25 lists going with some public and some private. Those lists had the entire timeline of tweets from people on those lists in chronological order. I would LOVE the same feature in Mastodon.

I also saw on another feature request that if I move to another server/instance, would those lists follow me? That would be a secondary feature that would help to make my account airtight in case of a move.

**Comment by trwnh** [comment] 2023-01-28 20:45
Just realized this is a duplicate of #5938

**Closed** 2023-05-16 04:45 UTC
Labels: suggestion

**Comment by marians** [comment] 2023-05-16 07:03
@trwnh ... but you closed both https://github.com/mastodon/mastodon/issues/5938 amnd this one (https://github.com/mastodon/mastodon/issues/16290). I think one should stay open.
