### ISSUE TITLE
Backfill lists

### ISSUE THREAD

**Issue by limdingwen** [mastodon/mastodon#21499] opened 2022-11-23 19:32 UTC
### Pitch

When adding an account to the list, the list should fill up with posts that is already known.

### Motivation

When adding an account to a list, even when the account already has posts the server knows about, the list will not be populated. This is confusing UX and discourages experimentation with lists.

**Comment by trwnh** [comment] 2023-01-26 17:05
Duplicate of #16290

**Closed** 2023-01-28 00:47 UTC
Labels: suggestion
