### ISSUE TITLE
can these features ?

### ISSUE THREAD

**Issue by usnbtv** [mastodon/mastodon#25347] opened 2023-06-08 21:58 UTC
### Pitch

👥  particular person
👤  just me
🔒 port-to-port switching
✏️ the write insertion limit can be increased

### Motivation

- can these features be added?

👥  particular person
👤  just me
🔒 port-to-port switching
✏️ the write insertion limit can be increased

**Comment by jaymehta-g** [comment] 2023-06-12 22:10
Please elaborate

**Comment by Lastorder-DC** [comment] 2023-06-14 05:58
What "features"? You should write in detail. What is "port-to-port switching"? or "the write insertion limit can be increased"?

**Comment by usnbtv** [comment] 2023-06-14 09:57
1 - adding text may increase the word limit
2 - will the end-to-end password feature in messages or direct messages come in the future?
3 - Mastodon, is the post editor feature coming? { example : text thickening , slanted text , underlined text , adding a link to a word }

**Comment by Lastorder-DC** [comment] 2023-06-16 11:07
1. #12265
2. #19565
3. #23981, #24239 

@usnbtv

**Comment by trwnh** [comment] 2023-06-16 14:04
Closing as a duplicate of the above listed issues

**Closed by trwnh** 2023-06-16 14:04 UTC
Labels: suggestion
