### ISSUE TITLE
Allow me to use my own domain in my handle without having to host my own instance

### ISSUE THREAD

**Issue by 343max** [mastodon/mastodon#24928] opened 2023-05-09 08:37 UTC
### Pitch

It would be great for users to be able to use the own domain instead of the instance's domain in their user handle. So instead of beeing @user@instance.tld it would be great if one could choose @user@user-domain.tld instead.

Using [webfinger](https://docs.joinmastodon.org/spec/webfinger/) it's already possible to point from ones domain to the users account. But right now it's just a redirect: inside of Mastodon the domain isn't visible and not discoverable. If a mastodon instance was able to handle an "alias" for a user account and make it that users primary I think accomplishing this feature should be … well, not easy but maybe doable without protocol changes.

### Motivation

Discoverability is a hard problem on Mastodon. When I search on mastodon for a person or organization I often find multiple accounts that belong to them, some of them might be fake. Also a user it's much easier to build trust in @news@newsorganization.tld than in @newsorganization@some-instance.tld. To prevent this issue some organizations have started to setup their own instances which might be a great solution for them but can be very hard or impossible for smaller organizations or individuals.

It would help the mastodon communities to build trust, identity and commitment if people and organization could easily bring their own domains to the platform and would make the system look less confusing to new users.

(tbh: I was blown away by the Bluesky feature where one could easily user their own domain as a handle. It helps me to bring my own identity but also makes it very easy for me to make sure accounts belong to the right person or organization)

**Comment by berlincount** [comment] 2023-05-09 09:54
I also wonder how retiring an instance and forwarding the old handle to be a new alias on another instance would look like when you _don't_ want to keep the instance running 😕

Feels related.

**Comment by trwnh** [comment] 2023-05-09 15:18
Duplicate of #2668

**Closed by trwnh** 2023-05-09 15:18 UTC
Labels: suggestion
