### ISSUE TITLE
Links not working unless prefixing with http(s)://

### ISSUE THREAD

**Issue by Porrumentzio** [mastodon/mastodon#14138] opened 2020-06-25 08:22 UTC
On Mastodon, no matter of the app used, if someone writes an internet link, it will be shown as link **only if** it's prefixed with encryption prefix `http(s)://`. This is a bit tedious, as no everyone knows how to solve this and most of all because it's easier and faster to write the link without any prefix.

### Expected behaviour
When someone writes an internet link **without** any **prefix**, let's say "mastodon.eus", it **should** be **interpreted** as link and work as it (if you type on it, redirect to that address on a browser).

### Actual behaviour
When someone writes an internet link **without** any **prefix**, let's say "mastodon.eus", it is **not interpreted** as link, **but** as simple **text**.

### Steps to reproduce the problem

Write a link without any prefix and, when posted, you'll see it's now simple text.

### Specifications

**mastodon.eus** and **esperanto.masto.host** instances with Mastodon **v3.1.4**, both on **Tusky** Android app and **web-view**.
I use Google's **Android** for **Tusky** and Manjaro **Linux** with **Firefox** for web-view.

### Proposal

I suppose Mastodon's engine avoids non-secure links and that's the reason for not showing not prefixed links as them. My proposal is, if you want to preserve that security, make a function on the code that when someone writes "a link" (really it would be `somelettes+dot+someotherletters`), the engine will add the prefix automatically, no matter if showing it on the interface or not (what is more easy).

**Comment by Sasha-Sorokin** [comment] 2020-06-25 11:23
I'm not sure, I dislike when someone accidentally misses whitespace and it counts as a link. Not only it's bad for the readers, but also the author of the post, because links always count as 23 characters. Your suggestion to automatically insert prefix is making this even worse (“…and he like said nah https://haha.babe why ya…”).

As a general tip, Mastodon does not show prefixes in the posts, so when you type `https;//google.com` it will show up as `google.com`, I'm not sure about other clients, but I believe they should follow this approach.

**Comment by Gargron** [comment] 2020-06-25 11:30
Counter-point: I would like to be able to talk about google.com or mastodon.eus without those things turning into links because I'm not trying to make people *go there* but merely talking *about* them. @Sasha-Sorokin's point is also very valid, avoiding accidental links is important in my opinion. Unfortunately users' expectations do not align with this, I've seen plenty of new users (especially from non-technical backgrounds) post links without including the https:// part and thus failing to make it link. That must be a frustrating new experience.

**Comment by Porrumentzio** [comment] 2020-06-25 11:33
There are collateral damages, yes :)
Although there are some reason for not touching this behaviour, as @Gargron pointed, it can be frustrating. Mine was no more than a proposal, which I think deserves to think about

**Comment by SuperSandro2000** [comment] 2020-06-25 12:05
Many usernames nowdays include ``.`` and all of those would probably turn into links to dead domains which is not great.

**Comment by Sasha-Sorokin** [comment] 2020-06-25 12:55
@Gargron I have an idea… Bring this monster.

![Screenshot of Clippy saying “Did you mean to insert link at line 1, character 36?”](https://user-images.githubusercontent.com/10401817/85723571-90d47a00-b71d-11ea-9f0c-3c59de176095.png)

**Comment by last-partizan** [comment] 2023-07-03 19:28
I think there's a variant which satisfy all parties.

google.com should not be linkified, but google.com/ and google.com/something/something is clearly a link.

Any negative sides to this?

And i don't suggest adding a https prefix to stored message text, i think this should be done somewhere before passing it from db to a client.

I don't familiar with mastodon render pipeline, but i can try adding this linkifier, just point me to the relevant part of the code.

**Comment by Signez** [comment] 2023-07-25 13:26
I have heard from friends that it was disconcerting and frustrating for them, so I've looked up to see if there was an issue, and of course there was one :)

In my opinion, this is the kind of affordance that should be made client-side, as part of the controls of the compose area. Ideally, as it is common to do so in all the other microblogging platforms, I would have enabled it by default, but with a very easy setting to override it, either situationally or as a long-term preference:

![Mstdn - Auto-link](https://github.com/mastodon/mastodon/assets/411336/db33ebca-1884-4d7a-9926-77fc3fd13213)

(the overflow menu, i.e. ···, would contain a "Never create auto-link", and that would fill a setting that would be tunable in the Preferences.)

What do you think? Of course, my suggestion would make it _auto-link_ by default, at least for common tlds, to help most non technical-users that would not understand the need to add a `https://`, but still allow users to quickly disable it if it bother them.

**Comment by lucasbfr** [comment] 2023-07-26 06:58
> In my opinion, this is the kind of affordance that should be made client-side, as part of the controls of the compose area. Ideally, as it is common to do so in all the other microblogging platforms, I would have enabled it by default, but with a very easy setting to override it, either situationally or as a long-term preference

I like it, but would prefer if it was the option to "create this link". 
Could it be bundled with the option to generate the preview (client-side)?

Note: a allow-list of common TLD would cause issues of "surprising" the user (why is user.id linkable and mastodon.lol not?)

**Comment by Signez** [comment] 2023-07-26 07:19
I agree: after [discussing with a bunch of people](https://mastodon.social/@Signez/110774652933086254) (with the caveat that of course, that kind of post only touches people familiar with the platform), I think it's safer to indeed opt for a better middle-ground.

Here is a new suggestion, that do not create links automatically but warns user that they _may_ want to do so:

![Mstdn - Warn Auto-link](https://github.com/mastodon/mastodon/assets/411336/ef230302-be61-42b3-9dbe-9ea58dcae660)

The X would discard the suggestion for that post, and the ··· would offer a setting to never suggest it in the future.

**Comment by trwnh** [comment] 2023-07-27 02:23
@Signez that suggestion looks much better than the prior one, but there is the complication that you don't actually know if anything is being served via `https://`. it might be that it is serving something via `http://`, or `ftp://`, or something else, or nothing at all.

**Comment by last-partizan** [comment] 2023-07-27 05:44
I think it's safe to assume that https is default. If it's anything else, you need to explicitly specify protocol.

**Comment by vmstan** [comment] 2023-12-31 16:15
Duplicate of #701

**Closed by vmstan** 2023-12-31 16:15 UTC
Labels: suggestion
