### ISSUE TITLE
Please consider alt text for profile and header images 

### ISSUE THREAD

**Issue by giromide** [mastodon/mastodon#11584] opened 2019-08-16 14:23 UTC
### Pitch

The embrace of alt text in Mastodon has been great, but for completeness, profile and header images should offer alt text.

### Motivation

Feature completeness is my primary motivation.

**Comment by ionathanch** [comment] 2020-09-04 04:51
Idk if reactions will prevent the stale bot from closing this so here's my comment in support of this. Emojis should probably also have alt text as well, but that seems like a separate issue implementation-wise.

**Comment by rkingett** [comment] 2021-05-17 15:04
I still think this should happen on Mastodon but [I pitched this on hometown as well](https://github.com/hometown-fork/hometown/issues/908#issuecomment-842388867)

**Comment by rkingett** [comment] 2022-05-08 19:45
I still support this. Ideally, it should still be supported. If anything, to continue to be better than places like Twitter.

**Comment by thomasmdickinson** [comment] 2022-11-30 03:52
I also want to voice my support for this. Seems strange that a feature like this does not already exist, given the popular support and encouragement of alt text that is so common on many Mastodon servers.

**Comment by dizm** [comment] 2022-12-29 19:17
Also still hoping for this

**Comment by Cassolotl** [comment] 2023-06-18 09:42
Duplicate of *Add ALT-Tag to banner and profile pictures and make the value editable for acessiblility reasons #10313* (March 2019)?

**Comment by vmstan** [comment] 2023-11-17 13:56
Closed as duplicate.

**Closed by vmstan** 2023-11-17 13:56 UTC
