### ISSUE TITLE
Add option to disable notification in tab title

### ISSUE THREAD

**Issue by leahoswald** [mastodon/mastodon#13188] opened 2020-03-02 11:27 UTC
### Pitch

There is this "number of interactions since last focus" in the tab title that is independent of the filters you've configured for notifications. See:
![Screenshot2020-03-02_12-22-02](https://user-images.githubusercontent.com/1292551/75672173-795e1680-5c80-11ea-96fb-f759effe5ce8.png)
This number indicates all kinds of interaction despite you've disabled notifications for this type of interaction. This is for me, and could be for others, a huge distraction in an ever open mastodon tab while doing other things. So it would be great if there was an option to disable this typ of notification. Bonus for making it configurable.

**Comment by nazco** [comment] 2020-06-26 09:54
Would be great to see it in one of the next releases.

**Comment by trwnh** [comment] 2023-05-19 05:55
Duplicate of #12211

**Closed by trwnh** 2023-05-19 05:55 UTC
