### ISSUE TITLE
Support data miners

### ISSUE THREAD

**Issue by SoniEx2** [mastodon/mastodon#19613] opened 2022-10-31 22:13 UTC
### Pitch

All links on an instance (not in the web client) should go through a dataminer, as described in https://discourse.wicg.io/t/web-protocol-dataminers/5877

### Motivation

Mastodon is so grating because it doesn't have nice redirects between random instances and the user's instance. Dataminers solve that.

**Comment by SoniEx2** [comment] 2022-11-19 13:08
The new in-app links are great but they should really use data miners instead of being tied to a specific instance.

Think about it this way: a data miner lets you link to `https://example.org/dataminer/user/@foo@example.org` and if you copy that link and send it to someone else, the data miner will send the user to their own instance instead of to your instance.

In fact, a data miner works with arbitrary URLs, so it'd be `https://example.org/dataminer/?q=web+activitypub://example.org/user/foo` but anyway. these are technicalities. the point is: data miners enable URLs to work across instances and apps, providing the best of every world.

**Comment by SoniEx2** [comment] 2022-12-01 19:37
or at least, could masto use an URL syntax for the in-app links? instead of `https://example.org/@foo@example.net` it would be `https://example.org/?t=web+activitypub://example.net/@foo`. we think leaning in on web protocol handlers would be good in the long-term even if the short-term is suboptimal. but "leaning in", in this case, involves using workarounds - like never actually registering the protocol handler, never providing an UI for it, and never even actually using it as a protocol handler; instead just hardcoding the links to the local instance.

it's important to think about how these things should work in the future, when doing things today.

**Comment by rbairwell** [comment] 2023-01-09 09:47
Duplicate of https://github.com/mastodon/mastodon/issues/19679

**Comment by SoniEx2** [comment] 2023-01-09 11:46
no, that's not the same.

**Comment by SoniEx2** [comment] 2023-01-09 11:59
this one is about using a third-party service instead of a browser feature.

**Comment by rbairwell** [comment] 2023-01-09 14:14
Can you provide a site/details of what exactly a dataminer (in this context) actually is? The page you linked to is just a paragraph written by yourself - which comes from a thread by yourself which is again vague as to what it is trying to address/fix.

Side: Actual "mining" of data on Mastodon - in the traditional sense of "gathering" - would put quite a lot of people against the suggestion, especially your "collect your data while at it and use it to serve ads, thus making their own revenue" comment: most admins (and I suspect users) are against gathering of personal data and advertisements on Mastodon.

If you are worried about protocol handler support - there's several ways to deal with that (see https://paul.kinlan.me/detecting-if-a-url-scheme-can-be-handled/ ). You did bring up on the referenced page the example of MediaWiki's [GeoHack ](https://www.mediawiki.org/wiki/GeoHack) which requires a ["known list" of services](https://geohack.toolforge.org/geohack.php?language=en&params=40.7;-74_type:city(8000000)&pagename=New_York_City) for the user to pick from - which with around 10,000 Mastodon server instances currently active, isn't a reasonable thing to do.

**Comment by SoniEx2** [comment] 2023-01-09 14:27
yes, actual "mining" of data on Mastodon would only happen if the third-party service was tightly connected to adtech, which https://fedi-to.net/ is not. (in fact fedi-to is explicitly anti-adtech.)

> You did bring up on the referenced page the example of MediaWiki's [GeoHack ](https://www.mediawiki.org/wiki/GeoHack) which requires a ["known list" of services](https://geohack.toolforge.org/geohack.php?language=en&params=40.7;-74_type:city(8000000)&pagename=New_York_City) for the user to pick from - which **with around 10,000 Mastodon server instances currently active, isn't a reasonable thing to do.**

(emphasis added)

challenge accepted.

**Closed** 2023-01-09 16:00 UTC
Labels: suggestion
