### ISSUE TITLE
Posting queue

### ISSUE THREAD

**Issue by lookitmychicken** [mastodon/mastodon#22671] opened 2022-12-22 23:04 UTC
### Pitch

For an individual account, add posts & boosts to a post queue. 

Instead of instantly publishing a post or boost, provide an option to add it to a post queue for future publishing.

Default option would still be to post immediately. 'add to queue' would be an option that the user could select.

This would be in addition to any option to schedule a post for publication at a specific time, not a replacement for that functionality.

Enable the user to set posting intervals, e.g post from queue 6 times every hour, or once a day, or every 78 minutes.

There is a similar feature on Tumblr.

### Motivation

Users may want to post or boost a lot of content in one session, but don't want to overwhelm their followers' timelines with too many posts at once.

Adding a post queue feature would enable users to post and boost more freely without the concern of spamming the timelines.

**Comment by ineffyble** [comment] 2022-12-31 15:36
A useful feature, but also one that's definitely able to be implemented by a third-party app/service (e.g. Twitter still doesn't support this despite services like Buffer being popular for years). So it may not be the highest priority to implement in Mastodon itself.

**Comment by Cassolotl** [comment] 2023-02-11 11:41
Duplicate of *Feature request: Queued toots #15219* from 2020, I think?

**Closed** 2023-05-19 06:25 UTC
Labels: suggestion
