### ISSUE TITLE
Preview card for YouTube short urls links to wrong page

### ISSUE THREAD

**Issue by guerda** [mastodon/mastodon#31376] opened 2024-08-11 08:45 UTC
### Steps to reproduce the problem

1. Post a YouTube short URL like https://youtu.be/C_b6bptI844
2. Open the link in the post, video shows fine
3. Open the link via the preview card, YouTube loads the page of an "undefined" YouTube channel or showing a blank page: https://www.youtube.com/undefined

Happens on Mastodon 4.2.10

![Screenshot_20240811-102045](https://github.com/user-attachments/assets/c4acf1df-6cbb-4d07-8cff-215e9d1fbe72)

### Expected behaviour

the preview card should keep the original name the same.

### Actual behaviour

a wrong video page is shown

### Mastodon instance

ruhr.social

### Mastodon version

4.2.10

### Browser name and version

chrome Android Version 127.0.6533.103 and Firefox Android 129.0b9 (Build #2016034799),

### Operating system

Android 14

### Technical details

I tested it with short urls for YouTube shorts and for regular videos, it happens with both of them

**Comment by ThomasLeister** [comment] 2024-08-12 17:54
Hi! I have the same issue with one of my Mastodon instances. Didn't have the time to further dig into this issue, but when I have, I'll contribute.

**Comment by guerda** [comment] 2024-08-12 18:04
Great. Let me know how can I assist.

**Comment by ThisIsMissEm** [comment] 2024-08-15 16:12
Likely a duplicate of #31308, youtube changed something and it broke link unfurling

**Comment by guerda** [comment] 2024-08-15 16:48
Thanks Emily! It certainly looks that way. Hope you can get in contact with one of them soon

**Comment by tomakun** [comment] 2024-08-28 03:03
Same issue here, YouTube card not working and showing as https://www.youtube.com/undefined
Running Mastodon 4.1.7

**Closed** 2024-09-12 11:23 UTC
Labels: bug, status/to triage, area/web interface
