### ISSUE TITLE
A way for admins to change the favicon in admin settings

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#7396] opened 2018-05-07 10:40 UTC
Because it's nice to have a bit of icon individuality on the bookmark bar, and because a lot of admins are using a hosting service now so they need to be able to customise their instance from the admin settings.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nclm** [comment] 2018-09-22 18:28
Yes! I came to open the same issue, looked it up beforehand, and found this :) Now that there is a custom CSS field, the favicon is one of the big missing customisation option.

**Comment by carbonpenguin** [comment] 2019-03-23 00:44
Was just looking for this in the admin interface. +1 to the request... :)

**Comment by koyuawsmbrtn** [comment] 2019-05-24 05:49
It's pretty easy, could @Gargron please put it on the roadmap for 3.0? It should be just a small and simple patch.

**Comment by albjeremias** [comment] 2020-02-28 20:51
how do people change this?

**Comment by koyuawsmbrtn** [comment] 2020-02-28 22:49
> how do people change this?

they just replace the favicon file inside the public folder

**Comment by m-a-x-s-e-e-l-i-g** [comment] 2020-02-29 16:42
This, as well as the apple-touch-icon.png (and other similar icons).

**Comment by ErnestCodes** [comment] 2021-08-15 14:59
I guess changing the favicon in the file is how to go about this

**Comment by edmael** [comment] 2022-05-10 14:39
+1 to this, it's a simple but welcome change.

**Comment by johnsonm** [comment] 2022-06-02 00:13
Like others, I got here because I was expecting this to be part of the configuration; an expectation developed from setting up Discourse, which has fairly substantial "Branding" support. Worth seeing what they do, including image conversion, to make this simple.

**Comment by Gargron** [comment] 2022-06-02 04:30
There is a significant difference... Discourse is not a decentralized social network, every forum is a different, completely separate website, and that is expected. Different Discourse servers neither compete nor cooperate with each other, they just serve whatever specific purpose a forum usually serves. For Mastodon, it is vital that an onlooker can recognize that it's not simply a random website, but a Mastodon server, and therefore part of the decentralized network where they will be able to interact with content from *other* servers. The server operator benefits from the trust established through brand recognition (visitors know what Mastodon is and what to expect from it, so they are more willing to sign up) and there is no confusion whether "I am signed up on Foo" and "I am signed up on Bar" are completely separate social networks or not. There are brand customization options in Mastodon - the title, the description, the hero image - but the favicon and header and footer logos are intentionally left unchangeable in this line of thinking.

**Comment by johnsonm** [comment] 2022-06-02 11:58
What you say makes complete sense for a Mastodon server with open registration.

As you know, the first part of Mastodon setup is the choice whether to make the server for just a single user, and there's nuanced support in the platform for closed registration. There are a lot of Mastodon servers with closed registration; not just those that are in single user mode, but those that serve a particular community. At least, I've run into what I would call "many" while I was trying to decide whether to start running a Mastodon server!

I'm setting up a Mastodon server as part of a community. Registrations will be available within that community, in order to give them a Mastodon server on which the Local and Federated views are likely to be relatively more interesting to them than some "random" Mastodon server with open signup that they find. I am trying to help bootstrap participation in decentralized social networking within that community. Here, the community brand is important, and is a **way to promote Mastodon within that community.**

Ultimately, it's not hard to set up nginx rules that point to branded favicon etc. I've already done that.

But I think you are perhaps unnecessarily discounting the value *to Mastodon* and the fediverse of incorporating favicon in site branding, where it can enhance opportunities to enable and encourage existing communities to expand out into the fediverse by use of Mastodon. I don't mean to argue, and won't prolong a conversation here; I just wanted to present a view that wasn't clearly encompassed in your reasoning. It doesn't ultimately matter to *me* now whether Mastodon makes this change; the nginx route is trivial. I only want to help. ☺

**Comment by jsailo** [comment] 2022-11-15 06:11
+1 to this. I guess this is never going to be implemented? 

@johnsonm I _read_ that you have managed to do this using nginx rules. Could you please help/provide us non-techie people on the steps of how to do this? 

/non-techie = Can run a bunch of CLI commands and tinker with existing code. That's it.

**Comment by svoeth** [comment] 2022-11-16 00:43
@Gargron would you mind telling me which of these is my own server, which is my private account, which is a totally different server and which ones are just joinmaston.org landing page?

![Screenshot_20221116_014023](https://user-images.githubusercontent.com/37115161/202055135-58758f14-9667-4532-8568-6d9a638dbb65.png)

I don't mind having this setting hidden somewhere, but changing the favicon will happen, but currently it is a pain in the a**

Thank you :)

**Comment by rixx** [comment] 2022-11-22 18:03
> For Mastodon, it is vital that an onlooker can recognize that it's not simply a random website, but a Mastodon server, and therefore part of the decentralized network where they will be able to interact with content from _other_ servers. The server operator benefits from the trust established through brand recognition

I think this approach is fundamentally misguided, and I very much hope that you reconsider. I feel very iffy about having brand recognition being higher up in your priorities than instance ownership.

At this point, instance owners *already* change their favicons, and all the other things you mentiond (footers, for example) that you think have to be immutable and make every instance look like mastodon.social. We hack our nginx configs, we hack our custom.css files, and, in the case of the favicon, we have to patch in files of our own.

All this kind of restriction achieves is that it's more annoying to have a favicon that makes it easier to distinguish instances, and that people on hosted instances can't do it.

**Comment by rickosborne** [comment] 2022-11-22 23:55
For posterity, the Apache2 equivalent of @QGuLL 's nginx config is:

```
RewriteEngine on
RedirectMatch 301 "^/packs/media/icons/.*[.](png|ico)" "https://example.com/favicon.$1"
```

(Confirmed as of 4.0.2.)

**Comment by unayok** [comment] 2022-11-24 04:57
If you are serving the icon files statically (via nginx, for example)... [This gist](https://gist.github.com/unayok/5df2c9045a197964561bf9cf939991ce) is a sample script for determining and generating various sizes of icon files based on the current `<html><head><link>` references and `/manifest` and a good quality primary image.

It works okay for me. It queries the main page and the manifest, and (naively) finds the various icon links and desired sizes. It uses Pillow to resize the base image, and drops them into the destination (presumably your /mastodon/public folder). In my setup, nginx has its root set to a writable `/mastodon/public` directory that contains the `system` directory mounted into the docker.

Hope this is helpful for some.

**Comment by hansenandrew** [comment] 2022-11-26 11:19
I would love my favicon to show up on the browser. Is there a way to get it back? 
<img width="482" alt="Screenshot 2022-11-26 at 6 58 35 pm" src="https://user-images.githubusercontent.com/17509205/204086104-68c10985-16ee-4e4d-bcbf-538911bfe9f9.png">

**Comment by rstockm** [comment] 2022-11-28 23:30
> For Mastodon, it is vital that an onlooker can recognize that it's not simply a random website, but a Mastodon server

I see what you're getting at, but maybe here is some common ground here.
Lets's take a look at the custom favicon of chaos.social:

<img width="56" alt="Xnip2022-11-29_00-16-42" src="https://user-images.githubusercontent.com/3195116/204401517-9b5b7a09-462a-4653-ac73-731a80c69b9b.png">

a) it has the official shape
b) the official color (well not for the 4 but lets ignore this for the sake of argument)
c) a server-logo (rocket) in the right color (white).

It's perfectly clear that this is a mastodon server, bit it gives me orientation at first glance to distinguish this server from the other 3 I have accounts on.

So what about this:
- admins have a way to upload a svg
- this will be rendered in white color in the official logo
- fitting the space the official "m" does.

For my openbiblio.social server - which adresses libraray people - this would be - well - a book:

<img width="104" alt="image" src="https://user-images.githubusercontent.com/3195116/204402231-1067d83c-3340-42af-944f-8e3493f7497f.png">

Actually, this looks ginda creepy, but you get the idea.
This might sound a bit like over-engineering, but it would suit both needs?

**Comment by Freeplayg** [comment] 2022-12-08 21:36
> For Mastodon, it is vital that an onlooker can recognize that it's not simply a random website, but a Mastodon server


Also now in 4.0, don't you already have these to already tell that it's a Mastodon server?
![image](https://user-images.githubusercontent.com/40742947/206572263-56bbb79d-0b37-40c1-82b3-d15515a0d609.png)
![Screenshot from 2022-12-08 16-34-21](https://user-images.githubusercontent.com/40742947/206572277-962df931-91be-4f47-833e-f7dbbecd98cf.png)

**Comment by Openmedianetwork** [comment] 2022-12-08 22:35
A thread on social tec of this https://socialhub.activitypub.rocks/t/branding-on-the-fediverse/2534

**Comment by www-cat** [comment] 2022-12-08 22:54
i suspect that there were many cases of people seeing the default Mastodon icon after visiting a link to an instance, and thinking it's impersonating the mastodon.social (possibly to spread malware!).

perhaps a better headerbar would be "websiteName | powered by Mastodon" or "websiteName | part of Fediverse" with the last work linking to a page explaining the website is a part of a network?

**Comment by www-cat** [comment] 2022-12-08 23:12
> > For Mastodon, it is vital that an onlooker can recognize that it's not simply a random website, but a Mastodon server
> 
> Also now in 4.0, don't you already have these to already tell that it's a Mastodon server? ![image](https://user-images.githubusercontent.com/40742947/206572263-56bbb79d-0b37-40c1-82b3-d15515a0d609.png) ![Screenshot from 2022-12-08 16-34-21](https://user-images.githubusercontent.com/40742947/206572277-962df931-91be-4f47-833e-f7dbbecd98cf.png)

that is currently visible only on some screen sizes

**Comment by cadadr** [comment] 2022-12-08 23:21
> For Mastodon, it is vital that an onlooker can recognize that it's not simply a random website, but a Mastodon server, and therefore part of the decentralized network where they will be able to interact with content from other servers.

It's a *fediverse* server, not a mastodon server.

**Comment by psydwannabe** [comment] 2022-12-09 00:32
> For Mastodon, it is vital that an onlooker can recognize that it's not simply a random website, but a Mastodon server, and therefore part of the decentralized network where they will be able to interact with content from _other_ servers. 

@Gargron - At what point do you intend to implement mandatory Mastodon themes on the other Mastodon forks, as well as the other Fediverse clients, in keeping with your unified dream of sameness?

Or were you planning to force us all to defederate from non-vanilla Mastodon servers so we get the perfect Apple walled-garden experience?

**Comment by egypturnash** [comment] 2022-12-09 01:25
yeah eugen can you please let us hang up some curtains and make the spaces we run feel like home to *us* and to *our users*, we are all nodes on the People's Glorious Social Network and I am perfectly fine with that, delighted to be a part of it even, but we are also *specific* nodes with specific values and identities and feelings; we are *communities* that are talking to ourselves in the Local timeline as well as talking to the whole world in the other timelines.

I have put off upgrading to 4.x because you broke all my customizations the last two times I upgraded and I *still* haven't fixed them since the last one and I intend to be switching over to the Glitch fork and wrapping my head around its weird two-tier style system *solely so I can decorate the heck out of my instance and expect it to keep looking the same when I update the underlying software*.

**Comment by Gargron** [comment] 2022-12-09 02:43
Configurable favicon and app icon are on the roadmap.

**Comment by gessel** [comment] 2022-12-19 23:32
@cambraca - thanks, very helpful.  

If anyone wants a bash script that should (still) generate all the standard favicon variants at least up to the at the time of writing 512x512: https://www.blackrosetech.com/gessel/2020/12/21/favicon-generation-script.  I'm sure there are much fancier ones online, but this did what I needed at the time.

It assumes you're starting with an .svg.

**Comment by Chewie9999** [comment] 2023-08-07 15:49
> @cambraca - thanks, very helpful.
> 
> If anyone wants a bash script that should (still) generate all the standard favicon variants at least up to the at the time of writing 512x512: https://www.blackrosetech.com/gessel/2020/12/21/favicon-generation-script. I'm sure there are much fancier ones online, but this did what I needed at the time.
> 
> It assumes you're starting with an .svg.

Thank you!
Note a recent version of InkScape is required, mine from 2020 did not include the -o option, but  v1.3 does.
Also the "size" line needs some slightly different resolutions for Mastodon. I'm using the following:
```
size=(16 32 48 57 60 72 76 114 120 144  152 167 180 192 310 1024)
```

**Comment by gessel** [comment] 2023-08-07 19:54
Thanks, that's great, I added a note for Mastodon users on my script page and credited you.  If I modded the line to be the union of both requirements it would get a bit pretty big.
`size=(16 32 36 48 57 60 70 72 76 96 114 120 128 144 150 152 167 180 192 256 310 384 512 1024)
`

**Comment by Chewie9999** [comment] 2023-08-09 10:12
> Thanks, that's great, I added a note for Mastodon users on my script page and credited you. If I modded the line to be the union of both requirements it would get a bit pretty big. `size=(16 32 36 48 57 60 70 72 76 96 114 120 128 144 150 152 167 180 192 256 310 384 512 1024) `

Fair enough.
I included sizes that would replace files that start "android-chrome-", but I don't think they're actually used - I never see them in the source when requesting a page, even though I see the apple ones and I'm not on an apple device.

**Comment by gessel** [comment] 2023-08-09 12:16
Oh, good work!  I didn't even think to check my actual logs, duh, just followed specifications without checking if they're actually requested, an always moving target, these days.

**Comment by almereyda** [comment] 2023-08-31 18:52
We have added these lines to an Nginx configuration to adapt `favicon.ico`, and also the `/packs/media/icons` route:

```
    location = /favicon.ico {
             return 301 https://example.com/favicon.ico;
    }
    location ~ "/packs/media/icons/" {
             return 301 https://example.com/images/icon-128.png;
    }
```

**Comment by 3-w-c** [comment] 2023-10-07 20:05
@almereyda thanks for the tip! I think the first block might set up an infinite redirect? And the second one didn't work for us, we needed to do this (with the caret `^` before the tilde `~`):

```
  location ^~ "/packs/media/icons/" {
    return 301 https://example.com/favicon.ico;
  }
```

**Comment by renchap** [comment] 2024-05-07 16:59
Fixed by #30040

**Closed by renchap** 2024-05-07 16:59 UTC
Labels: moderation, suggestion

**Comment by mikoducky** [comment] 2024-09-28 20:32
I just had a hosted instance spun up (4.2.12) and the favicon and logo options are not in the branding section like your linked, merged fix. Did it actually happen?

**Comment by almereyda** [comment] 2024-09-29 02:07
When you open the merge commit linked at the bottom of the PR, it shows you that the merged patch is only part of the `main` branch and of the `v4.3.0-beta.1` and `v4.3.0-beta.2` tags. We can expect this feature to land with the next v4.3 release.
