### ISSUE TITLE
Content auto expire / delete for users

### ISSUE THREAD

**Issue by coilysiren** [mastodon/mastodon#1295] opened 2017-04-08 22:10 UTC
As an end user I would appreciate a setting in mastodon similar to https://www.tweetdelete.net/, which deletes all posts after a certain period of time

Implementation proposal:

- `content_expiration_days` on `user`
    - a profile UI setting for this option
    - `content_expiration_days==None` user option unset
    - `content_expiration_days<=0` user opts out of content deletion
    - `content_expiration_days>0` user has set a content deletion time
- an admin setting `DEFAULT_CONTENT_EXPIRATION`, in `.env.production` used when the user expiration value is unset
- a daily runner that deletes all statuses where `status.created_at + content_expiration_days > datetime.now`

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by lynnco** [comment] 2017-04-08 22:11
posted before I was done! editing...

**Comment by kballard** [comment] 2017-04-08 22:37
Seems kind of odd to build this into Mastodon directly, instead of just making a bot to do it.

**Comment by lynnco** [comment] 2017-04-08 22:54
This is definitely something a bot could handle effectively, but I feel the feature has a wide enough appeal that its justified to build it into mastodon for the sake of reach.

Although there's also possibly a discussion to be had here about whether people view content on mastodon as ephemeral or permanent

**Comment by kuro5hin** [comment] 2017-04-08 23:00
Please add this, it makes so much more sense to do it inside the server by a user pref than try to hack it in with bots.

**Comment by ndarville** [comment] 2017-04-08 23:29
Am I right in thinking the updates still live on in other instances due to federation, somewhat alike the correspondence in a mailing list you delete from your @\gmail?

It still serves a purpose that a user profile doesn’t show or reveal the updates, but a false sense of privacy is also very dangerous. If it were to be an official feature, it should come with an extremely well-worded disclaimer.

**Comment by tduehr** [comment] 2017-04-08 23:31
One way to think of Mastodon is as email with a 500 char limit and default bcc all. Recalling an email—where supported—is just sending a second email saying you want to recall the previous email. Without client cooperation, that doesn't work. You might be able to do it in the official client but anyone that's ever received it can push the message out again in some form or another.

**Comment by Changaco** [comment] 2017-04-09 16:29
I'm not a lawyer but I believe that the author of an auto-expiring toot could use copyright to give a legal basis to the time limit. A custom license which only allows distribution of the message for the desired period of time would have to be written, and the toot's metadata would point to that license.

In jurisdictions where keeping a private copy of a copyrighted work is allowed the followers who have received the time-limited toot would be able to keep it after it expires, but not redistribute it. The license could grant that right to everyone regardless of local laws.

Once time-limited toots become part of the public domain they would become shareable again, if anyone still has a copy by then…

P.S. I'm not saying that using copyright is a good idea, and I don't really care about automatic deletion of all messages, I just had a thought about how it could be enforceable so I'm sharing it.

**Comment by nathanatluminal** [comment] 2017-04-20 05:45
This is an awesome feature request. I agree that a bot would be a poor choice. Bots fail all the time. If it was down for a significant period it's entirely plausible that it would never be able to catch up without prohibitive amounts of CPU time for both the bit and the mastodon network. 

It seems like this would be fairly easy to implement as a mark-and-sweep garbage collection on any user's timeline.

**Comment by beaknit** [comment] 2017-04-20 05:48
This is an awesome feature request. I agree that a bot would be a poor choice. Bots fail all the time. If it was down for a significant period it's entirely plausible that it would never be able to catch up without prohibitive amounts of CPU time for both the bit and the mastodon network.

It seems like this would be fairly easy to implement as a mark-and-sweep garbage collection on any user's timeline.

**Comment by Technowix** [comment] 2017-06-03 19:03
any new on that ? maybe a more simple thing, like peoples / admin can set a limit of time where post are kept...

**Comment by Cassolotl** [comment] 2018-04-10 23:32
I think this might be a duplicate of *Auto-Delete for posts / remove old posts from database #875*?

**Comment by tduehr** [comment] 2018-04-11 15:57
No, this is a feature request to enable users to tag posts with an expiration.

**Comment by Cassolotl** [comment] 2018-04-11 19:16
Ahh I get you. This one is for users to have statuses auto-delete after an amount of time of their choosing, and #875 is the same but for everyone on the instance and for much older posts, right?

**Comment by drequivalent** [comment] 2018-11-10 18:03
Also, add options to not delete toots that have any kind of feedback (like or boost) on them.

**Comment by dupainaulevain** [comment] 2019-03-19 09:26
I would love to have that, thanks :+1:

**Comment by Gargron** [comment] 2022-09-25 04:41
Fixed by #16529

**Closed by Gargron** 2022-09-25 04:41 UTC
Labels: suggestion
