### ISSUE TITLE
Adding an emoji with Edge (Windows Phone 10)

### ISSUE THREAD

**Issue by xakan** [mastodon/mastodon#2334] opened 2017-04-22 19:50 UTC
Hi,

When I try to add an emoji to a toot, at the end for example, this one is placed at the beginning. I have to copy/paste to place it where I want.

![wp_ss_20170422_0004](https://cloud.githubusercontent.com/assets/7924208/25307707/b6001222-27a5-11e7-876a-40feea8bc50c.png)

xakan
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment] 2017-06-30 14:37
@nolanlawson Some kind of thing with selectionStart in Edge? Although I'm tempted to close this because mobile phones have native emoji pickers.

**Comment by nolanlawson** [comment] 2017-07-03 23:43
Yes it appears to be this bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11693535/

Oddly though I can only reproduce in Edge mobile, not in Edge desktop (1703 aka Creators Update on both). And yes this only occurs when using the dropdown emoji picker, not when using the native mobile emoji keyboard.

**Comment by xakan** [comment] 2017-07-04 07:31
Oh sorry, I did not try with native emoji keyboard. But I'm now on Android, and I can not make new tests.

**Comment by trwnh** [comment] 2023-01-26 20:55
can this be closed now that Windows Phone is discontinued?

**Comment by xakan** [comment] 2023-01-28 15:53
On my side, I completely forgot this issue, and don't have any Windows Phone anymore. And as it's discontinued, I assume that there are not so much people still using it.

**Closed** 2023-05-13 23:39 UTC
Labels: bug, ui
