### ISSUE TITLE
Image preview doesn't center the focal point

### ISSUE THREAD

**Issue by jomo** [mastodon/mastodon#11518] opened 2019-08-07 17:37 UTC
### Expected behaviour

When picking a focal point, the image preview should show the focal point at the center of the preview (unless the preview is already at the border, in which case it shouldn't move out of the image):

![image](https://user-images.githubusercontent.com/3585743/62643865-34bc0800-b949-11e9-97b1-d8c05a4b2263.png)

### Actual behaviour

The preview center drifts away from the focal point the more you move the focal point away from the image center.

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/3585743/62641977-09371e80-b945-11e9-928a-949d18b0d30c.png)  
![image](https://user-images.githubusercontent.com/3585743/62641985-0d633c00-b945-11e9-9fe8-5dccd39e2d7e.png)

### Note

This happens because the preview shifts away from the border as soon as the focal point does. It shouldn't move until the focal point is farther away from the border than the center of the preview is.

### Specifications

Mastodon v2.9.2

**Comment by jomo** [comment] 2019-10-26 19:05
This is still an issue.

**Comment by trwnh** [comment] 2023-05-16 04:17
Duplicate of #6879

**Closed by trwnh** 2023-05-16 04:17 UTC
