### ISSUE TITLE
"Video has no video stream" when uploading WebM video

### ISSUE THREAD

**Issue by graue** [mastodon/mastodon#26501] opened 2023-08-15 21:18 UTC
### Steps to reproduce the problem

1. Try to upload a WebM video of a screencast I recorded on Ubuntu 22.04 LTS

### Expected behaviour

The video should upload

### Actual behaviour

Upload fails with a 422 "Video has no video stream" error

### Detailed description

I originally got this error while using a custom client (so it's a server/API issue), but I also get it using the Mastodon web interface.

Here's the video file in question. Seems to be a well-supported format. Plays fine in Firefox browser in a `<video>` tag.

[Screencast from 08-15-2023 02:08:31 PM.webm](https://github.com/mastodon/mastodon/assets/1730853/f1dc51ca-271f-4723-bfa8-0b8a68c012ba)

### Mastodon instance

social.coop

### Mastodon version

v4.1.4

**Comment by renchap** [comment] 2023-08-16 09:38
Duplicate of #14779

Should be soon fixed by #26500

Please re-open if this is not related somehow.

**Closed by renchap** 2023-08-16 09:38 UTC
Labels: bug, status/to triage
