### ISSUE TITLE
RSS Feed Titles Need to be More Expressive.

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [mastodon/mastodon#8125] opened 2018-08-05 03:14 UTC
This was actually raised in #1438 .  But, disappointingly, was closed without really understanding the heart of the issue.  Followers should read that one first.  😒

The biggest change over all this was adding RSS to the mix.  It seemingly did **NOTHING** to fix the issue.  

We should not need to Reverse Engineer/workaround a F(L)OSS project, ala `https://github.com/RSS-Bridge/rss-bridge` to get a good feed that does not drop some non descript generic blurb where fed.  Sad that we yearn for Twitter™ in that respect.  With re-toots, replies, et cetera, when content is fed outside a Mastodon client, we get a bunch of generic feeds.  And it is a waste of time clicking on things of no interest to us.  Try `https://mastodon.social/@TootBot.rss`.  It yields the same as `https://mastodon.social/@TootBot.atom`:
> TootBot (@TootBot@mastodon.social) posted a new article: New status by TootBot ( https://mastodon.social/@TootBot/100495275495149029 )

And that is insufficient when a bit of description/summary is needed.  There have been several issues related to this, including merged/pulls, and still this.  😒

**Comment by mike-burns** [comment] 2018-08-05 09:00
Historical and implementation notes:

#7259 is where RSS feeds were added to the repo.

The title is set in `RSS::AccountSerializer`: https://github.com/tootsuite/mastodon/blob/master/app/serializers/rss/account_serializer.rb#L22 . There's duplication in `RSS::TagSerializer` to watch for too.

It's set from `Status#title`: https://github.com/tootsuite/mastodon/blob/master/app/models/status.rb#L146-L152 . Be mindful when changing that; it's also used for the Atom feed that communicates between instances. It's probably safer to construct a title specific to the RSS feed (`#human_title` or a one-off in the serializers).

**Comment by MilkManzJourDaddy** [comment] 2018-08-07 19:30
> Media RSS allows for a much more detailed description of the content to be delivered to the subscriber than the RSS standard.
https://en.wikipedia.org/wiki/Media_RSS

I think many of us who are happy to have a non-*birdsite* platform feed content elsewhere, would much rather know a basic bit about the status, if it interests us, before clicking.  Just a basic blurb, not necessarily even MRSS.

The state of this repulses people from Mastoson instead of drawing them.  Think about it…  I put a Mastodon feed, and  *birdsite* feed someplace.  The *birdsite* fed item describes itself, and the Mastodon item states that some microblogger posted something in their microblog.  ***If*** the *birdsite* item interests thrm, most people will click that, not some mystery link.

**Comment by jbond23** [comment] 2018-08-08 07:58
I posted the original. My user requirement still stands. atom.title is a useful summary of an atom item that is commonly used in the same way as an email subject line.
 
I don't know the detail of the underlying code that does federation. But if it really depends on atom.title containing text of the form "New status by $USERID" then there's something broken with the code design. atom.title should be purely descriptive text and not functional data. I actually find it really hard to believe that the activitypub spec calls for atom.title to be "New status by $USERID" and for that to be somehow used federation between activitypub instances. Can anyone point at a URL where this is stated?

**Comment by nightpool** [comment] 2018-08-08 14:45
@jbond23 The reason an RSS reed was added was not because atom.title is *required* to be "New status by nightpool" but because the atom feed breaks most user-facing feed readers, full stop. So instead, we added a "user facing" RSS feed that was designed to be more friendly.

> for that to be somehow used federation between activitypub instances

ActivityPub doesn't use atom at all. the atom feeds are required by OStatus.

**Comment by babolivier** [comment] 2018-08-10 08:43
I'd second that. Having human-readable RSS/Atom feeds is a feature Twitter has that Mastodon lacks imho.

**Comment by MilkManzJourDaddy** [comment] 2019-01-10 21:54
For those of us tracking this because of Matrix, one possible workaround might be to instead use [MXToot](https://github.com/ma1uta/mxtoot).

**Comment by crockwave** [comment] 2019-02-05 22:16
The RSS feed is not logging boosted toots, but the Atom feed is.  

The reason that is important is that one special use case for me is to monitor the RSS feed for curated content.  One way to do that is to have a Mastodon account used only for curation, and toots that should be curated to a content aggregator could be boosted.  Boosted toots would be culled from the RSS feed and placed into the content aggregator's RSS feed.  If we could boost toots with a comment, and the comment was logged, the content aggregator could use the comment as a custom Title value in the content aggregator's RSS feed.

**Comment by gerhardbeck** [comment] 2019-12-21 17:35
I'm supporting the request, good idea

**Comment by Krinkle** [comment] 2020-10-13 22:56
Would a patch be welcome for improving the RSS feed items as described?

**Comment by gerhardbeck** [comment] 2020-10-14 15:50
> Would a patch be welcome for improving the RSS feed items as described?

For me: yes!

**Comment by MilkManzJourDaddy** [comment] 2020-10-16 19:58
It's unfortunate that with some F(L)OSS projects, what seems to make the most sense *somehow* becomes the most difficult to {re-}implement.  Sadly with this issue, assuming the content is {also} on Twitter™️, it's just easier to use Nitter { [zedeus/nitter](https://github.com/zedeus/nitter/) }.  At least one server *instance* is in a non 14-Eyes nation state {see: [Instances](https://github.com/zedeus/nitter/wiki/Instances) }.  And the about page, i.e. [as seen on Nitter.net](https://nitter.net/about), declares that, **among other goals that seem to align with F(L)OSS philosophy**, RSS is strong with the Nitter.  It's just sad to see *other* F(L)OSS projects **I HAVE SUPPORTED**, seem to not care about letting big conglomerates win by Centralization, i.e. letting them kill RSS/Atom and implement their Centralized form of Push.  IMO, F(L)OSS projects should continue to support robust RSS/Atom Feeds, at least until F(L)OSS **DECENTRALIZED** Push becomes commonplace.  Sad.

**Comment by expenses** [comment] 2022-11-20 20:49
I'm gonna bump this because it's still an issue. I use [newsboat](https://newsboat.org/) for following a bunch of people across twitter (via [RSS-Bridge](https://github.com/RSS-Bridge/rss-bridge)) and now mastodon. Because the RSS feeds don't include item titles I'm getting something like this for now:

![20221120_21h47m40s_grim](https://user-images.githubusercontent.com/13566135/202925358-d5f89ef9-8b55-4c7f-8058-e2755eda30a4.png)

Because of this I'm going to have to make a script that requests the feed, sets the title of each item to be the content body and serves it for newsboat.

**Comment by Krinkle** [comment] 2022-11-21 01:06
@expenses fwiw, RSS2 spec author Dave Winer seems to disagree on the need for titles. They are optional in the spec and he regularly calls upon feed readers that treat this as an error to fix that, as doing so makes for a poor experience when dealing with microblog content (such as social media posts).

A few recent mentions: http://scripting.com/2022/11/03.html#a150642, http://scripting.com/2022/11/16.html#a171002, and an example of "good" feed reader showing a Mastodon feed. http://feedland.org/?mailbox=https://mastodon.social/@davew.rss.

I believe the idea is that microblogs fundamentally don't have a title and this allows for feed readers to optimally design the user experience. E.g. in context where both are shown, one can show content only (avoid annoying truncate + repeat), and in contexts where only headlines are shown it can choose to show part or all of the content. These kinds of decisions become impossible or non-standard once a title is enforced. I have no opinion on this myself, but the original [spec does agree](https://cyber.harvard.edu/rss/rss.html#hrelementsOfLtitemgt) in principle that titles are in fact optional.

**Comment by jbond23** [comment] 2022-11-21 07:43
No title is better than a bad title. I agree that if feed readers need a title within their UI and the feed doesn't have one, then it's the feed readers responsibility to create one. Probably by using N chars of the html stripped body. The current .rss feeds with no title are fine.

The original complaint was because a useless title was being delivered in the feed. Most feed readers will use a title if it's being delivered and a useless title doesn't help.

**Comment by trwnh** [comment] 2022-11-21 09:25
I think this issue can be closed, then?

**Comment by jbond23** [comment] 2022-11-21 10:57
I vote for "yes, close it"

**Comment by expenses** [comment] 2022-11-21 14:00
Okay, that's acceptable.

**Comment by pzingg** [comment] 2022-12-12 17:49
Dave Winer ("Mr. RSS 2.0") is arguing that feed items created from Mastodon toots should **not** have titles, and that feed readers should not be showing things that the original author did not write:

https://github.com/scripting/titlelessFeedsHowto

**Comment by norz** [comment] 2022-12-28 11:26
For those who use FreshRSS, see related issue there : 
https://github.com/FreshRSS/FreshRSS/issues/4838

**Closed** 2023-05-14 16:08 UTC
Labels: suggestion
