### ISSUE TITLE
Polls do not work on single toot page nor the profile page

### ISSUE THREAD

**Issue by IsabelaY** [mastodon/mastodon#10579] opened 2019-04-15 00:26 UTC
### Expected behaviour

Polls on the single toot page or the profile page should ask you for your username and domain for a remote vote, like how it works for remote follow, or at least inform you that a vote is not possible outside of the web application.

### Actual behaviour

Clicking on any option from the poll on the single toot page of the toot or from a profile page does nothing, it does not even show an error message. It does not work even if it is from your own instance. 

### Steps to reproduce the problem

- Open the single toot page of a toot with a poll or a profile page.
- Clicking on any poll option does nothing

### Specifications

Tested on a 2.8.0 Mastodon server, vanilla, using Chrome and Firefox on Windows 10.

**Comment by StarryAster** [comment] 2019-05-07 04:41
I have a suggestion: if the polls on "external pages" aren't meant to be voted on, they should show the current results instead of just the options.

**Comment by Cassolotl** [comment] 2019-05-07 05:02
If you're logged into an instance you shouldn't be shown the results until you've voted, I agree. But fediverse weirdness is a factor! Twitter shows you the results if you're not logged in, but how does that work when every Mastodon member isn't logged in to 99.999% of Mastodon instances, or is logged into seven instances? Or if you're logged into the host instance and have voted already, should the option to vote from other instances be unavailable while just showing the results? Or should it show the results *and* allow voting at the same time somehow?

I definitely agree that remote voting should be a thing. But if you can vote from all seven instances that you're signed in with, do you only get to see the results on a public toot page when you have voted from all instances you're signed in on?

I think as well as remote interactions, public toot pages could have an "open in Mastodon web UI" button. You could click it and type your instance (and log in if necessary), and it opens the toot in the web UI of your choice, and then you can like it and boost it and vote on it in seconds in a familiar environment, instead of having to do the remote interaction rigmarole for each individual interaction.

**Comment by Cassolotl** [comment] 2019-05-07 05:05
The complaint label is weird. If this is a complaint, isn't every feature request/bug report on this issue list a complaint? I would like to understand this label's purpose.

**Comment by jeroenpraat** [comment] 2019-05-22 17:54
This is related (or maybe the same) as issue #10157.

I just had an user who was very confused about this. They tried to click on an voting option, but logged out or logged in, nothing happened in the UI. The user thought that this was a bug and yes, I can think it is indeed a bug.

My proposal is that when people are logged out the poll is (dark) greyed out and when people are logged in that they can click somewhere in the poll to open the poll in the web-app (like with the other interactions on public pages).

**Comment by ell1e** [comment] 2022-05-02 19:30
I found it to be extremely confusing i had to manually find out how to compose the `https://mymastodoneinstance/web/@user@otherinstance` URL **manually** because to me there was literally no other way *at all* to access a poll and vote on it I saw on another instance via its direct web view - where I was, obviously, not logged in since I don't have an account there. I still don't know how to do a vote any other way than manually compose this URL, which I think is not something any user should ever need to know how to do.

Everything I have done before like favoriting, following, etc. just automatically offered me this sort of remote confirmation redirect in a pop-up window, but the poll's "Vote" button was just grayed out. Why? In my opinion this is super inconsistent  and confusing, the vote button should instead also show me the pop-up window and make me confirm the vote instead of silently failing with zero indication what even the problem is. Up to guessing the URL structure as mentioned in the first paragraph I didn't even find any definite info if there even was meant to be a way for me to vote on that remote poll without a local account. If people can't even figure out if they are technically meant to use a function let alone figure out how, in my personal opinion your UI is in need of a fix.

**Comment by joenepraat** [comment] 2022-05-02 22:23
I see this is an old standing issue, but I think/hope/expect/wish that it will be resolved as part of this work in progress pull request from @Gargron: https://github.com/mastodon/mastodon/pull/16800. This seems like a huge undertaking and I really hope it will be part of version 3.6 or maybe it justifies a 4.0.

**Closed** 2023-05-16 03:50 UTC
Labels: partially a bug
