### ISSUE TITLE
Stories

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#13426] opened 2020-04-06 22:18 UTC
### Pitch

Similar to Instagram, Snapchat or WhatsApp Mastodon could have a story feature.

### Motivation

We were completely done one night and thought what an awful idea it is to introduce stories. I think it's not bad to ask.

**Comment by SuperSandro2000** [comment] 2020-04-07 04:42
Well, would hate it.

**Comment by raphgilles** [comment] 2020-04-07 13:57
It's important to know that Pixelfed do that, and it's federated.

Stories are not a bad feature. It's just a bad feature ON Instagram, Snapchat, ect. But it's a very good tool to... tell a story.

**Comment by trwnh** [comment] 2020-04-07 22:07
pixelfed stories are not federated yet; federation model is in-progress and still being thought out

**Comment by mkljczk** [comment] 2020-04-08 06:41
Also [this](https://git.pleroma.social/pleroma/pleroma/-/merge_requests/1875/diffs)

**Comment by resynth1943** [comment] 2020-04-12 23:10
Oh god I would hate stories, it's honestly a cliche at this point

**Comment by STemR** [comment] 2021-09-19 02:31
> 
> 
> pixelfed stories are not federated yet; federation model is in-progress and still being thought out

Hey, any links or updates on the progress for a federated stories/temporary post feature?

**Comment by StefOfficiel** [comment] 2022-10-12 17:56
Stories are a great tool to tell a story or say something ephemeral, it's not intrusive and useful to highlight a key moment of our feed! Just because you would hate Stories doesn't mean you shouldn't include them. If you hate them, well, you won't use Stories. And why not include the possibility in your account settings to hide the Stories for those who hate them!

**Comment by vmstan** [comment] 2023-11-17 21:25
Closed as duplicate of #512

**Closed by vmstan** 2023-11-17 21:25 UTC
