### ISSUE TITLE
Support for mailto: scheme URIs

### ISSUE THREAD

**Issue by kidehen** [mastodon/mastodon#22922] opened 2023-01-03 18:34 UTC
### Pitch

Mastodon needs to handle of mailto: scheme identifiers i.e., trigger initialization of a  user's default email app compose interface. 

Note, this is standard internet savvy application behavior.

Link to post that demonstrates the problem:
https://mastodon.social/@kidehen/109626691035471931

### Motivation

This is standard behavior across internet savvy apps.

**Comment by SoniEx2** [comment] 2023-01-03 23:48
duplicate of #14375

**Comment by ineffyble** [comment] 2023-01-06 14:40
Closing as duplicate

**Closed by ineffyble** 2023-01-06 14:40 UTC
Labels: suggestion
