### ISSUE TITLE
Moderation API

### ISSUE THREAD

**Issue by Gargron** [mastodon/mastodon#10741] opened 2019-05-10 00:04 UTC
In broad terms, the same things possible from the admin interface must become possible through an API with an additional OAuth scope.

**Comment by bclindner** [comment] 2019-07-23 15:19
This should probably be closed. Looks like the GitHub project didn't do it for some reason. :man_shrugging:

**Comment by trwnh** [comment] 2019-10-26 19:58
isn't this `/api/v1/admin`

**Comment by tofuwabohu** [comment] 2022-05-03 19:10
I was about to open a Feature Request to make mod actions (activatinv users, resolve reports, etc) available via API so it can be done in apps. Is this about the same or is it a different thing?

**Comment by trwnh** [comment] 2023-05-13 23:41
Duplicate of #2517

**Closed by trwnh** 2023-05-13 23:41 UTC
Labels: TODO
