### ISSUE TITLE
Feat: respond to toots with emoji

### ISSUE THREAD

**Issue by djayatillake** [mastodon/mastodon#19839] opened 2022-11-06 09:22 UTC
### Pitch

I couldn't see this in the issues.

It would be good to be able to react to toots with emojis where this stays on the toot. Like with Slack and LinkedIn.

### Motivation

Everyone as it allows for differentiated non verbal reaction from favourite which I believe is supposed to be used like a bookmark.

**Comment by Cassolotl** [comment] 2022-11-06 10:24
Duplicate of *arbitrary emojis as reactions #4106*, maybe? :) If so, close this issue and add a comment and a 👍 over there.

**Closed** 2022-11-06 10:37 UTC
Labels: suggestion
