### ISSUE TITLE
Clicking on a hashtag in a user's profile opens in new tab

### ISSUE THREAD

**Issue by yaymukund** [mastodon/mastodon#3982] opened 2017-06-28 11:29 UTC
Similar to #3185, clicking on a tag in someone's profile opens in a new tab. It should go in the third column.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by clarcharr** [comment] 2017-07-24 17:47
Any plans to get this in by 1.5?

**Comment by Cassolotl** [comment] 2018-05-14 13:28
Same if you click a hashtag in thread-view, it is *infuriating*. D: Just, there are a whole bunch of linky things (but not all of them) that open in the last column *unless you are clicking in the last column*, and it's inconsistent and unpredictable and really annoying!

**Comment by JMendyk** [comment] 2018-09-10 14:16
@Cassolotl I believe that hashtags and are now properly handled in statuses and thread-views.

On the subject of mentions/tags/links in users' bio:
One solution would be to copy how hashtags and mentions are handled inside statuses (see https://github.com/tootsuite/mastodon/blob/master/app/javascript/mastodon/components/status_content.js#L26-L81). However, statuses have information about mentions and hashtags provided by API:
```json5
{
  // (...)
  "content": "<p>This toot has a <a href=\"http://localhost:3000/tags/super\" class=\"mention hashtag\" rel=\"tag\">#<span>super</span></a> hashtag and a <span class=\"h-card\"><a href=\"http://localhost:3000/@first\" class=\"u-url mention\">@<span>first</span></a></span> mention</p>",
  "mentions": [
    { "id": "2", "username": "first", "url": "http://localhost:3000/@first", "acct": "first" }
  ],
  "tags": [
    { "name": "super", "url": "http://localhost:3000/tags/super" }
  ]
}
```

But profile bio only has content and lacks tag/mention metadata.
```json5
{
  // (...)
  "note":"<p>My <a href=\"http://localhost:3000/tags/hashtag\" class=\"mention hashtag\" rel=\"tag\">#<span>hashtag</span></a> bio, friend of <span class=\"h-card\"><a href=\"http://localhost:3000/@admin\" class=\"u-url mention\">@<span>admin</span></a></span></p>"
}
```

As the result, API would have to be modified to also result this data.
@Gargron Since it would add new fields, backwards compatibility shouldn't be an issue here. Moreover, Mastodon client developers could find it useful.

Of course, tags/mentions extraction for bio could be performed fully by client but this leads to having to maintain two seperate extraction procedures (which probably should be kept in sync).

**Comment by trwnh** [comment] 2023-05-16 03:25
Duplicate of #1399

**Closed by trwnh** 2023-05-16 03:25 UTC
Labels: bug
