### ISSUE TITLE
Add "Local only" as a "Change post privacy" option.

### ISSUE THREAD

**Issue by johnclint** [mastodon/mastodon#21794] opened 2022-11-28 14:15 UTC
### Pitch

Please consider adding "Local only" as an option in "Change post privacy". 

### Motivation

This feature change would benefit both regular users and admins. There are times when a post is really meant for the members of the local instance--such as a poll about server rules or a request for volunteers to moderate.  
![Change Post Privacy](https://user-images.githubusercontent.com/17678596/204299102-4cd8d6e3-9a49-429e-a2a3-11738ef3ff96.png)

**Comment by rbairwell** [comment] 2022-11-29 01:43
This is actually a featuee on Mastodon-glitch/glitch-soc ( https://glitch-soc.github.io/docs/features/local-only-toots/ ) which is a sort of "features/ideas testing" "fork" of Mastodon. Your instance admin could switch to it using the instructions on https://glitch-soc.github.io/docs/ if they felt this is something they wanted their users to be able to do.

**Comment by johnclint** [comment] 2022-11-29 02:56
Thanks, Richard! I’m glad this feature is already developed and in testing.  I’m the admin of episcodon.net, but we are hosted by toot.io. I’ll wait for this option to roll out in a future upgrade. John Clinton ***@***.*** From: Richard BairwellSent: Monday, November 28, 2022 8:43 PMTo: mastodon/mastodonCc: John Clinton Bradley; AuthorSubject: Re: [mastodon/mastodon] Add "Local only" as a "Change post privacy" option. (Issue #21794) This is actually a featuee on Mastodon-glitch/glitch-soc ( https://glitch-soc.github.io/docs/features/local-only-toots/ ) which is a sort of "features/ideas testing" "fork" of Mastodon. Your instance admin could switch to it using the instructions on https://glitch-soc.github.io/docs/ if they felt this is something they wanted their users to be able to do.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by trwnh** [comment] 2022-11-29 03:26
Duplicate of #861

**Closed** 2023-05-19 06:34 UTC
Labels: suggestion
