### ISSUE TITLE
NoMethodError: undefined method errors in sidekiq

### ISSUE THREAD

**Issue by slueppken** [mastodon/mastodon#18261] opened 2022-05-02 17:41 UTC
### Steps to reproduce the problem

1. I migrated my Mastodon installation from another server, using docker
2. I'm running version 3.5.1
3. I'm opening sidekiq and I see many errors like:
ActivityPub::SynchronizeFeaturedCollectionWorker
NoMethodError: undefined method `filter_map' for nil:NilClass

ActivityPub::SynchronizeFeaturedCollectionWorker
NoMethodError: undefined method `account_id' for nil:NilClass

### Expected behaviour

There shouldn't be NoMethodErrors with failed jobs in my sidekiq queue

### Actual behaviour

I'm not sure what's the result of the error, but I'm pretty sure it's not expected behavior

### Specifications

Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-109-generic x86_64)

> git status
HEAD detached at v3.5.1

> docker --version
Docker version 20.10.14, build a224086

> docker compose version
Docker Compose version v2.4.1

**Comment by ClearlyClaire** [comment] 2022-05-02 18:53
Duplicate of #18066, fixed in the development version

**Closed by ClearlyClaire** 2022-05-02 18:53 UTC
Labels: bug
