### ISSUE TITLE
Notifications need to show time

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon#29486] opened 2024-03-01 21:55 UTC
### Pitch

Notifications very much need to show a sense of time.
If someone likes, boosts or comments on a post, it doesn't say how long ago that notification happened.
If someone liked a post 5 minutes ago, the notification should tell us/ show us that. 
This definitely needs to be addressed

### Motivation

Beneficial because we would have a sense of time with notifications. 
Very much needed

**Comment by trwnh** [comment] 2024-03-02 08:32
Duplicate of #9988

**Closed by trwnh** 2024-03-02 08:32 UTC
Labels: suggestion
