### ISSUE TITLE
[FEATURE] Allow BBCodes & Markdown Codes

### ISSUE THREAD

**Issue by git-3000** [mastodon/mastodon#21936] opened 2022-12-02 00:53 UTC
### Pitch

In the past forums allowed us to share images by using Image Hosting BB Codes. 
I noticed that BB Codes don't work in Mastodon. 

Below is an example of a BB code

`[url=https://ibb.co/GWSDmQwert][img]https://i.ibb.co/GWSDmQwert/mypic232.jpg[/img][/url]`

### Motivation

Some might say that BB Codes are not needed on Mastodon because you can upload pictures on the instance. 
That's correct but there is still tons of image hosting websites and little servers like the one i run I want to tell my members to use image hosting websites instead of my instance to save space.

**Comment by afontenot** [comment] 2022-12-02 02:44
This is mostly a dupe of https://github.com/mastodon/mastodon/issues/18237, with an additional request for BBcode implementation. I think most of the interest in the past has been in Markdown.

**Comment by git-3000** [comment] 2024-03-05 16:22
gab social media site just closed off their image uploads unless you have a paid subscription. They complained that they are running out of storage. 

I am also facing this problem. This is why BB codes is needed.

**Comment by ThisIsMissEm** [comment] 2024-08-22 11:03
@vmstan I think this can be closed as duplicate? #23981

**Closed** 2024-08-22 13:42 UTC
Labels: suggestion
