### ISSUE TITLE
Reaction with emojis instead of favorite

### ISSUE THREAD

**Issue by RZHSSNZDH** [mastodon/mastodon#26487] opened 2023-08-14 16:14 UTC
### Pitch

Instead of using a single choise (star or favorite) it would be better if there was a feature to react with an emoji to toots. I do not know is it possible in fediverse or not.
And also toots' likes which they have taken until now can become to an amoji like ♥️.
Some services have this feature like Telegram and Matrix:
![نماگرفت از 2023-08-14 19-42-39](https://github.com/mastodon/mastodon/assets/69734726/1fd89360-3a1c-466b-b76c-e8b75496dfe5)

### Motivation

I think this will be a popular feature between users.

**Comment by renchap** [comment] 2023-08-14 16:37
Duplicate of #4106

**Closed by renchap** 2023-08-14 16:37 UTC
Labels: suggestion
