### ISSUE TITLE
Edge Casey Link Verification Issue With www prefixed domains

### ISSUE THREAD

**Issue by wgmyers** [mastodon/mastodon#19949] opened 2022-11-07 03:43 UTC
### Steps to reproduce the problem

I am trying to verify my website at https://www.conniptions.org/ on my mastodon.social account (@conniptions).

I have added the `rel="me"` attribute to the link back to my Mastodon account, `@conniptions@mastodon.social` on all my `*.conniptions.org` pages in order to have them show as verified on my Mastodon profile.

Identical code is working fine on my subdomains at https://wayne.conniptions.org and https://comic.conniptions.org. Verification is ok here.

However, verification fails on both www.conniptions.org and on conniptions.org.

### Expected behaviour

I should be able to verify my www prefixed domain

### Actual behaviour

I cannot verify my www prefixed domain

### Detailed description

Mastodon removes the 'www' prefix from profile links, changing `www.example.com` to `example.com`.

My domain does the opposite transform, redirecting `conniptions.org`  to `www.conniptions.org`.

As a result (?) I cannot verify my website using either `conniptions.org` or `www.conniptions.org` on Mastodon.

### Specifications

Mastodon v4.0.0rc1

Bug occurs in Linux, all browsers - other OS's not tested but suspect issue is to do with Mastodon removing 'www' in profile links, while my site deliberately adds it if missing.

**Comment by afontenot** [comment] 2022-11-07 04:46
I'm having issues with link verification as well, and I've noticed several other users. I think the www thing is a red herring, though. Mastodon hides the "www" from the text of the link, but if you hover over it, you can see that it will still take you to the correct location.

It seems pretty much random whether a given domain will work or not. (My domain doesn't use the www.)

I have noticed that the issue even applies to some users from other instances who show up (correctly) as verified on those instances. For example, if you visit `https://mastodon.xyz/@xor` you will see that this user has a verified link. (I checked their site and it does appear to have been done correctly), but when I pull up this user on the `mastodon.social` instance, their site appears to be unverified.

My best guess is that there's some regression on the 4.0.0 release candidate. The working sites all seem to be on 3.5.

**Comment by Forceflow** [comment] 2022-11-07 07:05
I confirm this is also an issue for me. I even built a special little page (because of the 1 mb page limit, see here: https://github.com/mastodon/mastodon/issues/15316) to be able to verify my account, but it doesn't show op on my profile.

This is the page I created: https://www.jeroen-baert.be/mst/

**Comment by afontenot** [comment] 2022-11-07 07:11
I think it's pretty likely that the queue is just overloaded right now. I have seen some new accounts who got the verified status to work, not sure how, but in my case I've even checked with tcpdump and the mastodon.social instance isn't connecting to my domain at all.

**Comment by ClearlyClaire** [comment] 2022-11-07 08:03
Closing as there is no special-handling on subdomains and it is likely to be a transient issue, probably caused by load. The whole process needs improvement, especially better feedback, though.

**Closed by ClearlyClaire** 2022-11-07 08:03 UTC
Labels: bug
