### ISSUE TITLE
Privacy menu truncated in replies

### ISSUE THREAD

**Issue by mikehamca** [mastodon/mastodon#25264] opened 2023-06-04 18:56 UTC
### Steps to reproduce the problem

1. Start writing a reply to a post in the Advanced Web Interface
2. Finish reply, click globe for privacy level
3. "Direct message" option is not accessible because menu truncated.
<img width="591" alt="Screenshot 2023-06-04 at 7 49 00 AM" src="https://github.com/mastodon/mastodon/assets/117941733/ac28afd1-549b-474e-98c1-3e53c9d14794">

4.
...

### Expected behaviour

Privacy menu should float up to be fully accessible

### Actual behaviour

Privacy menu at bottom of screen, last options off screen

### Detailed description

<img width="591" alt="Screenshot 2023-06-04 at 7 49 00 AM" src="https://github.com/mastodon/mastodon/assets/117941733/45ef8b16-53cb-4277-8df1-96623b8ece88">

Using macOS latest version, Vivaldi browser latest version. Vivaldi is Chromium-based.

### Specifications

Mastodon run by mstdn.ca — they do not list version number on their About page, and I have no idea where to find it.
macOS: Ventura 13.4
Vivaldi | 6.0.2979.23 (Stable channel) (arm64)
-- | --
Revision | 725a7354ca3a54908a1ff8fc5b9f50b521a2f755
OS | macOS Version 13.4 (Build 22F66)
JavaScript | V8 11.2.214.22
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Command Line | /Applications/Vivaldi.app/Contents/MacOS/Vivaldi --flag-switches-begin --flag-switches-end --save-page-as-mhtml
Executable Path | /Applications/Vivaldi.app/Contents/MacOS/Vivaldi
Profile Path | /Users/mham/Library/Application Support/Vivaldi/Default

**Comment by ClearlyClaire** [comment] 2023-06-05 08:49
I'm unable to reproduce this, even with Vivaldi. Of note is that mstdn.ca uses glitch-soc, but I'm unable to reproduce even by using the latest version of glitch-soc.

**Comment by mikehamca** [comment] 2023-06-05 13:12
I just tried closing Vivaldi and re-opening it. The problem seems to have cleared. Apologies — should have tried that to begin with.

**Comment by renchap** [comment] 2023-06-26 17:04
Closing, please re-open if this still happens

**Closed by renchap** 2023-06-26 17:04 UTC
Labels: bug
