### ISSUE TITLE
Better reply view

### ISSUE THREAD

**Issue by Rathmox** [mastodon/mastodon#23158] opened 2023-01-19 14:56 UTC
### Pitch

Mastodon should change the way replies are shown. currently a reply and a reply to a reply are shown in the same column.
![image](https://user-images.githubusercontent.com/55508107/213474217-d7c11f6a-da47-4f9d-b845-23c62336f1ee.png)

The interface should clearly show replies like a thread with for example a line on the left to link replies between them. (example with Tusky)
![Screenshot_20230119-155339_1](https://user-images.githubusercontent.com/55508107/213475166-2c3c6944-4c27-40fb-9a23-47cffb65e7a7.png)

### Motivation

When I looks at replies, it always get lost because I just can't see who is replying who. When I use Tusky, a mobile client, it shows them in a way I can understand.

**Comment by GiantCrocodile** [comment] 2023-01-19 18:26
Same here. Replies and notifications are super confusing to me because it's not clear to what the reply refers to or whether it's a standalone reply. The css/UI should be redesigned on that part.

**Comment by slayernominee** [comment] 2023-01-25 22:38
+1

**Comment by Truhe2342** [comment] 2023-03-03 16:36
Threads are currently nearly unreadable in the web interface. Here's an example how the iOS app Toot! displays threads:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/118095316/222775323-b55c6166-48c9-4055-bf9f-32c55c324d3b.png">

It uses coloured lanes for each subthread and this works perfectly without needing more UI space. You can even see if the current post IN YOUR TIMELINE has started a thread, is a reply to a thread or the end of a thread. It's a really nice UX.

![IMG_0943](https://user-images.githubusercontent.com/118095316/222775834-3d6b9f86-ba22-469d-b2b6-7e03b66197d3.png)
![IMG_0944](https://user-images.githubusercontent.com/118095316/222775887-9d498cbe-745e-41ff-ab31-93f6aa2b4e14.png)
![IMG_0945](https://user-images.githubusercontent.com/118095316/222775927-e27d8433-18a8-4e24-9f30-b4fe9fa6c1f6.png)

**Comment by april83c** [comment] 2023-03-06 07:53
duplicate of #19570 ?

**Comment by Rathmox** [comment] 2023-03-06 17:32
@april83c mine is more generic, the thread line was just an idea (but it's really good)
I only searched for "reply" or something like that so I couldn't find this issue

**Closed** 2023-05-19 06:20 UTC
Labels: suggestion
