### ISSUE TITLE
Ability to preview the post before uploading

### ISSUE THREAD

**Issue by Lukas2112** [mastodon/mastodon#26651] opened 2023-08-25 09:14 UTC
### Pitch

A button or something similar, with which a preview is generated that shows the user the post without it being published, to see if everything fits.

### Motivation

It would minimize errors in posts.

**Comment by Cassolotl** [comment] 2023-08-26 10:01
Duplicate of *Preview toot #1860*, which is from 2017 - over 6 years old.

**Closed** 2024-03-19 22:48 UTC
Labels: suggestion
