### ISSUE TITLE
Replace Visibilty -> only people I mention with actual direct message interface and inbox style UI

### ISSUE THREAD

**Issue by jaredzimmerman** [mastodon/mastodon#19950] opened 2022-11-07 03:52 UTC
### Pitch

The mention only visibility is a poor replacement for direct messaging.

### Motivation

current implementation will confuse many users, and does not give high confident to the "privacy" of messages

**Comment by trwnh** [comment] 2022-11-07 04:13
They are direct statuses, not private messages. In any case, a completely separate "messaging" feature is planned, with end-to-end encryption between client devices rather than between accounts.

**Comment by jaredzimmerman** [comment] 2022-11-07 04:18
DM and private@ having nearly identical functionality is overlay confusing.

**Comment by trwnh** [comment] 2022-11-07 04:22
Sorry, I'm not sure what you mean -- there is currently no concept of a "message" at all. Messaging is not part of Mastodon.

**Comment by jaredzimmerman** [comment] 2022-11-07 04:25
Yes, I'm saying I think that rolling out a DM function AND and a private @ or leveraging private @ as the DM functionality is not a good direction

**Comment by trwnh** [comment] 2022-11-07 04:29
Well, the private @ is part of the protocol, so it's probably not going anywhere -- posts can be delivered to specific people instead of to all followers or to the "public". These posts can exist in threads. It's kind of like pulling someone aside and telling them something in private, in reply to something else that they said publicly.

There's been some work to distance the concept of a direct mention from the concept of messaging -- they are not called DMs anymore, the privacy dropdown has been renamed to "Only people I mention", and so on. Aside from that I'm not sure what else can be done.

**Comment by jaredzimmerman** [comment] 2022-11-07 04:35
yes, I understand the premise. I'm saying its not a good decision.

**Comment by stephen304** [comment] 2022-11-07 05:33
I believe this is related to some discussion I've been seeing about people accidentally expanding the scope of an ongoing 1:1 conversation by mentioning additional users that were not meant to be part of the conversation (could be really bad when talking about someone...), or at least the implementation of a proper messaging feature would solve all of these concerns.

Is there a specific ticket being used as the canonical one to track the progress of a separate messaging feature?

**Comment by jaredzimmerman** [comment] 2022-11-07 07:51
> Sorry, I'm not sure what you mean -- there is currently no concept of a "message" at all. Messaging is not part of Mastodon yet.

Also, re:"no concept of a "message" at all" it's literally called Direct Messages in the webapp. 

![Screenshot 2022-11-06 11 46 27 PM](https://user-images.githubusercontent.com/430427/200254977-2c96e657-0043-4581-8c3d-fc6348bc5dbf.png)

**Comment by ClearlyClaire** [comment] 2022-11-07 08:00
> I believe this is related to some discussion I've been seeing about people accidentally expanding the scope of an ongoing 1:1 conversation by mentioning additional users that were not meant to be part of the conversation (could be really bad when talking about someone and trying to share their handle), or at least the implementation of a proper messaging feature would solve all of these concerns.

#18350 and #18363 are meant to address that specific concern but have not received feedback.

**Comment by trwnh** [comment] 2022-11-07 08:42
It seems like the icon was changed but the so-called "Direct Messages" column wasn't renamed. It should be called "Conversations" ideally, as that would be more accurate.

**Comment by TymeForChange** [comment] 2022-11-14 18:24
"Conversations" is not a good label. Posts and replies are conversations, too. Agree with OP that there is little to no distinction between @-mentioning someone and "DM"ing them. Having both as options on the composition window adds extra confusion, making users (especially Twitter uses) assume that the message/post will be 'private' (as it is with Twitter). Further complicated by the fact that Mastodon does not have truly locked/private accounts.

"Direct Message" (or "Direct Post") is a sensible name. But, sadly, this term is being used on other social media to mean private message. 

Perhaps at least making the composition window visibility menu (/alert) more clear to that point would help.  Just saying it isn't end-to-end encryption doesn't solve a problem for confusion. Stating something like "This is not a private message." would be better language.

**Comment by trwnh** [comment] 2022-11-14 21:19
"Conversations" is literally what it is. Yes, non-direct posts are currently not shown in that column -- but they could be. If you want to be specific, that column is currently "Direct Conversations". Arguably the column could be removed temporarily...

**Comment by jaredzimmerman** [comment] 2022-11-14 21:19
When you say "not private" do you mean not encrypted, or visible to other?

If you mean visible to others, then "Mentions" might be a better term if you mean not encrypted, but still generally not visible, I think Direct Messages or just Messages does make the most sense.

**Comment by trwnh** [comment] 2022-11-15 00:01
they're about as "private" as any other forum or social network -- visible only to the participants, but not encrypted, so someone with database access could read them (but generally this does not happen).

the confusion is less about the "private" or "direct" bit -- it's that people seem to expect "messages" to be a completely separate context from timelines.

**Comment by trwnh** [comment] 2022-11-21 09:18
Good point, this could be a duplicate of #3819

**Closed** 2023-05-19 06:16 UTC
Labels: suggestion
