### ISSUE TITLE
Support muting that filters based on posting client

### ISSUE THREAD

**Issue by aurynn** [mastodon/mastodon#23160] opened 2023-01-19 20:46 UTC
### Pitch

The ability to mute posts based on the posting client has been a powerful feature in some of the Twitter apps, and I think it would be an excellent feature in mainline Mastodon to support this capability. It would allow for end-users to filter posts made by marketing tools or cross-posters directly, or other services gain Mastodon/ActivityPub support.

### Motivation

I would like this feature after the announcement of the new iOS app, IceCubes, claims that it supports ChatGPT integration. Based on that, I'd personally like to be able to mute posts from IceCubes as a result.

From my experiences with Twitter, some other applications such as Untapped would post to Twitter timelines, which (when people I followed were at a pub or beer event) could get quite spammy. Having that level of "I don't want to see anything posted by this software" would allow an end-user to mute those sources directly.

As Mastodon picks up traction and more marketing efforts are directed into the fediverse, being able to directly mute marketing tools would be a great quality of life feature for basically everyone.

**Comment by VyrCossont** [comment] 2023-01-19 20:55
One hurdle to overcome: posting app information doesn't currently federate. It's only available through the Mastodon API on the instance where the status originated.

**Comment by trwnh** [comment] 2023-01-20 07:22
Duplicate of #8271

**Closed** 2023-05-19 06:19 UTC
Labels: suggestion
