### ISSUE TITLE
Attachment upload form-data with `\r` characters triggers a 500

### ISSUE THREAD

**Issue by maxf** [mastodon/mastodon#6352] opened 2018-01-24 20:10 UTC
The curl command below (with a valid token inserted) responds with a 500 and "Something went wrong on our end message". It's a multipart/form-data upload of a single png attachment. The command is possibly incorrect, but then the API should then return a 400 (and explain why) but not respond with a 500.
Update: The same call with all instances of `\r` removed from the form-data returns a 200.

```
curl 'https://mastodon.social/api/v1/media' 
  -H 'authorization: Bearer [VALID TOKEN]' 
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary80pOLu6XBJMywYPo' 
  --data-binary $'------WebKitFormBoundary80pOLu6XBJMywYPo\r\nContent-Disposition: form-data; name="file"\r\n\r\ndata:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEoAAABGCAIAAADkcJVdAAAAA3NCSVQICAjb4U/gAAAAGXRFWHRTb2Z0d2FyZQBnbm9tZS1zY3JlZW5zaG907wO/PgAABC9JREFUaIHt219IU1EcwPHfrrpNvdvcav7pfwZlIYH0UIEE0aPQX5DqqaA/Phg99RL0UhRUUARBShI9VUQSIr4kIUQP9RBCf9SMUh9yorVam3+m13t6+NG2tru7c+45Z27D7+Pd3e/swx16/6gtGAxC4aYs9QeQ2zIvn1vm5XMFzitO98KcHumcvPhjYUTsetvVpr3eFgD4Fp67PzgRXdRFTb61uzZ1o/HR07RFp6Ieqby2smSjqOWx95Gevl9tAFDrcp7eWu0okvv1MZ5+78GzBU1DYY29TuyS2RQaj/78ZaztQScKD/ov568w7dyY0K6U5q/QbGgBCDNMzHdh5nF5LaSalb9C2kEojEbnpQoJIWKFDFM+fxm7e/+pVOGL4G2xQrYRI2PjUoVDM31ihczvzy+hzfBeS+uFG+Zv27h+VevpZofDzrM2TfRn3gyn1BmLHUNrb6eP8ximvSDKGArjx3Cqxxb5aHlaYkStB38TAET1abtSikJrV0/WeZAk9DbC6HV+IVHrYW0LAMzp4edTl/wltft8rShsHwgs6IRpGu+Ppvi3tNhDGrqJWs8zjaj1pKEbij1om5z/+mm692XwLgDUupwnt1SXKDamgQJ+t4gSptpw+6fp3le/OwCgrqKUVSjm5IBfmM6G9Ye7rAmFnd3xCM1tmDWhyNNza0IaG2ZBKPj6ilVIb8NYheIvkOmFrDaMSSjlDgeN0JoN6w93vf79ECiEsm5RmQt5bNi7cOebP48gk1DiPUYUzszMJQn5bdjb0OO4cHOV4T5ybxKPjI3faX+SKBRlw+JCb5nhDtIfoXwfn/xPKM6GxYSGZeMJUaJQrA0zEWbpAZjNZiNA/i1ZlJ1FITu8Naurzp1pLi8r1QhoBOxK2SH/lUr7JlHzd3qO7XIfN3xJOi9u00nHYKBjMKDpxKm4RAlNbCCb959taGI4NDscmu0YmhAljNsiHwx3kMhLteF2UcJEm9K/33AfWbx0NoxfmGzTQoa7SeGZ2zAeIaUNZPBobFiS0FeyhmY+vQ2E86r8Pkoblig87L+aUchkA7G8Kr/vfMtRehsWE5YX+cyFrDYQyEOb260y2TAURhd1E+EO1xFWG4ji8diw4dBs+0AgnbDBdaCx4gQAmw2E8Pht2GgkaihscB3YU3EKgNkG/DxRNixVyGMDTp5YG5YobK68yWMDHp4MGxYTOhQVwLoNLPPk2bCYEADAuY4411qbY4UXs0UXdRk2LC7keDLDzEu0tQ8EJNkwfiEbL8k2Gomyrscap5CBl30bxiOk5S2VDbMspOItrQ2zJszM83ndS27DLAgz8Hxe9/mWY7lgw1iFZjy0rfB5csSGMQnT8nLThtELjXm5bMMohcZ/MvczGMplW6wNquPsthpHkQJaCIo9qTsY8wAg921YXGhUWl5hVOD/AVbgvL8tpM28AlznQgAAAABJRU5ErkJggg==\r\n------WebKitFormBoundary80pOLu6XBJMywYPo\r\nContent-Disposition: form-data; name="description"\r\n\r\nuploaded image\r\n------WebKitFormBoundary80pOLu6XBJMywYPo--\r\n' 
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by SamStephens** [comment] 2022-11-20 02:41
This is because it's assumed that [if ImageMagick can successfully identify the file format, any Paperclip errors are a 500 error](https://github.com/mastodon/mastodon/blob/ff43e54a495461eb1a539a1887125190b74754f5/app/controllers/api/v1/media_controller.rb#L9-L16).

```
  def create
    @media_attachment = current_account.media_attachments.create!(media_attachment_params)
    render json: @media_attachment, serializer: REST::MediaAttachmentSerializer
  rescue Paperclip::Errors::NotIdentifiedByImageMagickError
    render json: file_type_error, status: 422
  rescue Paperclip::Error
    render json: processing_error, status: 500
  end
```

The [V2 API has the same behavior](https://github.com/mastodon/mastodon/blob/ff43e54a495461eb1a539a1887125190b74754f5/app/controllers/api/v2/media_controller.rb#L4-L11).

However in this case the file looks like a PNG to both `file` and `identify` (I've confirmed this locally), but is actually not a valid PNG.

Log output with the `rescue Paperclip::Error` block commented out is:

```
15:22:19 web.1     | [paperclip] Trying to link /tmp/8d777f385d3dfec8815d20f7496026dc20221120-2170-nob4w1 to /tmp/4c96b7441b3a99a95f44576839b70f1220221120-2170-dsfjk7.png
15:22:19 web.1     | Command :: file -b --mime '/tmp/4c96b7441b3a99a95f44576839b70f1220221120-2170-dsfjk7.png'
15:22:19 web.1     | Command :: identify -format %m '/tmp/8d777f385d3dfec8815d20f7496026dc20221120-2170-nob4w1[0]'
15:22:19 web.1     | Command :: convert '/tmp/8d777f385d3dfec8815d20f7496026dc20221120-2170-nob4w1[0]' -auto-orient -resize "1481x1401>" -quality 90 +profile "!icc,*" +set modify-date +set create-date '/tmp/c388e12f64fae24519ebf985c7c3c75420221120-2170-q3yism'
15:22:19 web.1     | Completed 500 Internal Server Error in 84ms (ActiveRecord: 6.0ms | Allocations: 99840)
15:22:19 web.1     |
15:22:19 web.1     |
15:22:19 web.1     |
15:22:19 web.1     | Paperclip::Error - There was an error processing the thumbnail for 8d777f385d3dfec8815d20f7496026dc20221120-2170-nob4w1:
15:22:19 web.1     | Command 'convert '/tmp/8d777f385d3dfec8815d20f7496026dc20221120-2170-nob4w1[0]' -auto-orient -resize "1481x1401>" -quality 90 +profile "!icc,*" +set modify-date +set create-date '/tmp/c388e12f64fae24519ebf985c7c3c75420221120-2170-q3yism'' returned 1. Expected 0
15:22:19 web.1     | Here is the command output: STDOUT:
15:22:19 web.1     | STDERR:
15:22:19 web.1     | convert-im6.q16: no images defined `/tmp/c388e12f64fae24519ebf985c7c3c75420221120-2170-q3yism' @ error/convert.c/ConvertImageCommand/3258.:
15:22:19 web.1     |   lib/paperclip/lazy_thumbnail.rb:17:in `make'
15:22:19 web.1     |   lib/paperclip/attachment_extensions.rb:21:in `block in post_process_style'
15:22:19 web.1     |   lib/paperclip/attachment_extensions.rb:20:in `post_process_style'
15:22:19 web.1     |   app/controllers/api/v1/media_controller.rb:10:in `create'
15:22:19 web.1     |   app/controllers/concerns/localized.rb:11:in `set_locale'
15:22:19 web.1     |   lib/mastodon/rack_middleware.rb:9:in `call'
15:22:19 web.1     |
```

Unfortunately the error thrown in this scenario is just a generic `Paperclip::Error`, so we don't have a clean way to tell when an error from Paperclip is a problem with the file, or a problem on our side.

So at the moment, any image file that looks valid to `file` and `identify` but is not actually valid will cause a 500.

Possibly the best plan is to try and get Paperclip to provide a more specific exception type when convert fails in a way that indicates an invalid file format.

Failing that, we could handle [the specific errors that actually indicate misconfiguration](https://github.com/kreeti/kt-paperclip/blob/6b7909007de86b4b907d5b0ab1aaac717acc0bb5/lib/paperclip/errors.rb) as a 500, and then handle `Paperclip::Error` as a 422.

**Comment by SamStephens** [comment] 2022-11-20 02:42
![actually-invalid](https://user-images.githubusercontent.com/1034921/202880180-02e8623a-0c84-41eb-8270-b938c09781c8.png)

This is the invalid PNG encoded in the original `curl` command.

**Comment by mjankowski** [comment] 2024-11-27 17:55
Is this still valid on 4.3?

I know there has been SOME more granularity added, not sure if it covers this specific case or not.

Separately - as we continue on VIPS migration, we should contemplate how to get more narrow errors out as well.

**Comment by mjankowski** [comment] 2024-12-03 16:58
I think this was resolved by a change either in Rails or mastodon since original issue. I'm able to execute the original command and get a successful response, w/out 500 error.

If you still see this, can you reopen and include command which (when run against a 4.3 server) will replicate?

**Closed by mjankowski** 2024-12-03 16:58 UTC
Labels: api, area/media processing
