### ISSUE TITLE
Feature request: draft

### ISSUE THREAD

**Issue by cjeanneret** [mastodon/mastodon#1133] opened 2017-04-07 05:33 UTC
Hello,

I was thinking a bit, testing and poking on mastodon, and found a "small" missing feature: draft.

When you get some internal server error, it might be interesting to be able to keep the toot as a draft in the local storage (or, if the error is at some non-blocking level, in the account instance).

Also, it would allow another feature: program a toot - i.e. "I write it at 9, and want it published at 11:45"

That would be a good step forward.

Of course, its implementation won't be that easy, but at least it should come in some roadmap (and probably not too far in the future, although there are other issues that are more important, even blockers ;))

Thanks a lot for your time with mastodon dev/maintenance :+1: 

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by umonaca** [comment] 2019-11-13 04:39
Suggestion: perhaps a client-side draft would also be helpful in an unstable network.

**Comment by vmstan** [comment] 2024-05-28 13:26
Duplicate of https://github.com/mastodon/mastodon/issues/13617 which came after this post but has a more developed discussion.

**Closed by vmstan** 2024-05-28 13:26 UTC
Labels: ui, suggestion
