### ISSUE TITLE
Feature: Login by username too, not only full email

### ISSUE THREAD

**Issue by oneofthehorses** [mastodon/mastodon#28346] opened 2023-12-13 07:46 UTC
### Pitch

Please make allow users login by choose email **OR** username, because typing my **~20** email charachters address **PLUS @...** eat a lot of efford each time (think i'm not alone in such)

And yes, i close my session\delete cookies\don't save passwords

Thanks for your work!

### Motivation

To make things easier

**Comment by trwnh** [comment] 2023-12-14 00:08
Duplicate of #6976

**Closed by trwnh** 2023-12-14 00:08 UTC
Labels: suggestion
