### ISSUE TITLE
Display/show the "Administrator/Admin" and "Moderator/Mod" badges in mobile web view/version profiles as well

### ISSUE THREAD

**Issue by KNTRO** [mastodon/mastodon#14376] opened 2020-07-22 23:18 UTC
### Pitch
I would like to suggest [this very same idea](https://github.com/tootsuite/mastodon/issues/6702) but for mobile view/version of profiles as well.

### Motivation
I think this was forgotten to implement. By adding this feature, Mastodon will have a more consistent profile format. I think mobile users (and not just Mastodon Web users) also have the right to know who is the admin and who are the mods of any instance.

![image](https://user-images.githubusercontent.com/2568821/88238299-ad4dce80-cc57-11ea-8d6e-4110380beb4d.png)

Thanks for reading!

**Comment by mstdn** [comment] 2020-07-25 20:38
Maybe it's a good idea for faster support

**Comment by vmstan** [comment] 2023-11-17 19:41
Closed as duplicate of #19721 which has more traction.

**Closed by vmstan** 2023-11-17 19:41 UTC
