### ISSUE TITLE
Advanced Layout: Make main column collapsible

### ISSUE THREAD

**Issue by frank42hh** [mastodon/mastodon#18152] opened 2022-04-28 11:23 UTC
### Pitch

Hi,

I'm using tweetdeck and really like the design. So I was quite happy when finding the "advanced" layout, which looks quite like it. but, even though I got full HD, I only get 3 custom columns on screen. So, I would like to suggest this to improve the advanced layout:

Please make the most left column collapsible like it is with tweetdeck. It only contains some menu buttons (first steps, timelines, settings and logout), the search bar and the post window. The mastodon with the Planet Express Ship is very nice, but it doesn't make sense to have that column permanently present in full width.

### Motivation

Well, my motivation is that I think it would be more usable if the advanced layout could adapt more of tweetdeck's features, since they have quite an awesome frontend.

**Comment by Cassolotl** [comment] 2022-04-28 11:47
I totally agree, and I think yours is a duplicate of my feature request from 2019, *Compose drawer could squish down and become sticky with a ⬅️ button #9868* - only you said it way more articulately than me!

**Closed** 2023-05-19 14:10 UTC
Labels: suggestion

**Comment by trwnh** [comment] 2023-05-19 14:26
Duplicate of #9868 if that wasn't clear
