### ISSUE TITLE
Two user prefs: automatic CW; length > X, or user in Auto-CW list [feature]

### ISSUE THREAD

**Issue by NathanHawks** [mastodon/mastodon#6087] opened 2017-12-22 14:19 UTC
_Gonna just put there here and walk away as fast as I can. But I am the user who makes it so other people need this, and I would rather they had this, because right now they only have a mute-or-deal-with-it option, and I'm pretty sure that means everybody's muting me the day I arrive on a server._

Problem: some users post frequent walls of text; the posts are of decent value but it makes the instance look like there's someone on stage, which may cause other users to stifle their own participation. Or, another way of putting it; Problem: the only current option for dealing with verbose users is a mute, which is decidedly antisocial.
Solution:
- The Auto-CW List: A fourth list of users in your profile; their toots, when shown to you, will be shown to you in a CW, whether they used one or not.

Problem: some instances have larger size limits for toots than others; some users want to see these larger toots expanded by default, others (most?) find that doing so basically breaks the tootsuite UI. 
Solution:
- Auto-CW at Length: An option; add a CW whenever displaying any toot to you longer than X characters. (Perhaps also a tickbox to make convo view the exception to this behavior?)

_I am now unsubscribing from this submission because I don't like the way people talk to each other and I tend to try to drive people to suicide over what they think is a simple question._

* * * *

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
There were similar, but not identical, ideas

**Comment by Cassolotl** [comment] 2017-12-22 14:32
Duplicate of #255 "Hide bulk of longer posts from different sites", I think? Open for over a year now.

**Comment by trwnh** [comment] 2023-05-14 00:03
- the first half of the issue (collapse long statuses) has been addressed by the "read more" logic once a status exceeds a certain height.
- the second half (hide user posts behind a warning) should be part of the filter revamp. see #18955 and #6078

**Closed by trwnh** 2023-05-14 00:03 UTC
Labels: suggestion
