### ISSUE TITLE
Honour web finger redirects in profile fields

### ISSUE THREAD

**Issue by mro** [mastodon/mastodon#19582] opened 2022-10-31 10:14 UTC
### Steps to reproduce the problem

1. add a handle as @fediverse@mro.name into a profile page field as e.g. 'Fediverse' on https://digitalcourage.social/@mro

### Expected behaviour

it's clickable and leads to its profile page

### Actual behaviour

it's not clickable

### Detailed description

Webfinger being based on http should follow redirects IMO.

### Specifications

Mastodon v3.5.3

**Comment by MFTabriz** [comment] 2022-12-06 13:18
This issue seems to be resolved in v4.0.2. @fediverse@mro.name does properly resolve to @mro@digitalcourage.social

As a side note: according to the RFC 7033, "A client MUST query the WebFinger resource using HTTPS only."

**Comment by MFTabriz** [comment] 2022-12-07 08:49
@mro Can you please confirm that the issue is solved?

**Comment by mro** [comment] 2022-12-07 08:49
Confirmed to still be not clickable in v4.0.2 at https://digitalcourage.social/@mro field 'FEDIVERSE'.

**Comment by mro** [comment] 2022-12-07 09:07
> RFC 7033, "A client MUST query the WebFinger resource using HTTPS only."

doesn't mastodon?

**Comment by MFTabriz** [comment] 2022-12-07 09:15
> Confirmed to still be not clickable in v4.0.2 at https://digitalcourage.social/@mro field 'FEDIVERSE'.

Sorry I totally missed the issue only happening on the profile fields!

**Comment by MFTabriz** [comment] 2022-12-07 09:17
> > RFC 7033, "A client MUST query the WebFinger resource using HTTPS only."
> 
> doesn't mastodon v4.0.2?

it does! but your description says "Webfinger being based on http should follow redirects IMO" but technically webfinger queries shouldn't query over http or follow http redirects.

**Comment by MFTabriz** [comment] 2022-12-07 09:19
why this issue is opened/marked as a "bug"? Is there somewhere in the Mastodon documentations which say this should be the expected behavior?

**Comment by mro** [comment] 2022-12-07 09:57
is is different for the handles @fediverse@mro.name and @mro@digitalcourage.social which are both syntactical and logical equivalent.

Either be both clickable or none, right?

**Comment by MFTabriz** [comment] 2022-12-07 10:05
> Finally I just reported, you decide. If reports make a difference and are welcome, I will do so in the future.

Thanks a lot for reporting this. I'm just trying to figure out the expected (documented & tested) behavior in this case. I'll look into the issue.

**Comment by mro** [comment] 2022-12-07 16:34
profile page attachment PropertyValue urls being clickable may be an undocumented feature altogether.

**Comment by MFTabriz** [comment] 2022-12-13 20:31
I looked a bit into this. If I have understood the logic correctly, `@usr@domain.tld` is being treated as a mention here.

Normal mentions in the posts go through the [ProcessMentionsService](../tree/main/app/services/process_mentions_service.rb) (which through [ResolveAccountService]( ../tree/main/app/services/resolve_account_service.rb) makes the WebFinger request, the mentioned user gets notified, etc.)
But the text in the account fields just pass through the [TextFormatter](../tree/main/app/lib/text_formatter.rb) which tries to add a link to the mention by resolving the account through a call to ` mention(username, domain)` on [EntityCache](../tree/main/app/lib/entity_cache.rb) which fails to find that account in storage cache.

Moreover, I could confirm that no WebFigner query was received on my server after adding the mention to account field. Also, I couldn’t find any documentation/test explicitly for the links in the account fields.

**Comment by mro** [comment] 2023-02-28 08:25
@MFTabriz but it should, right?

**Closed** 2024-01-03 16:46 UTC
Labels: bug
