### ISSUE TITLE
Share Link to Toot, Displays Preview of Toot

### ISSUE THREAD

**Issue by joshroby** [mastodon/mastodon#21570] opened 2022-11-24 17:40 UTC
### Pitch

When I share a (public) toot to somebody via text message, it should display as a preview of the toot.  Right now it displays a preview of the mastodon user's profile pic.

### Motivation

You want recruitment and ambassadorship?  The easier it is to show people that there's fun / interesting / important stuff on Mastodon, the easier it is to get them to sign up.

If I share a tweet from the birdsite on iOS, my wife sees the text or image of the funny tweet.  If I share a toot, it just shows the user image of the person who tooted.  Not ideal.

**Comment by ineffyble** [comment] 2022-11-25 04:55
Duplicate of #20569. Unfortunately as discussed there, it looks like there's not an easy way to fix this unless someone can convince Apple to make a change at their end.

**Closed by ineffyble** 2022-11-25 04:56 UTC
Labels: suggestion
