### ISSUE TITLE
Boosts of people I’m already following should not be boosted

### ISSUE THREAD

**Issue by barts** [mastodon/mastodon#20411] opened 2022-11-11 13:38 UTC
### Pitch

Maybe this should be a setting, but I wish that if someone boots the post of someone that I’m already following that the post would stay at its original date. Currently what is happening is that I will read posts earlier in the day, they get boosted, and then they show up higher in my feed when I check back later in the day.

### Motivation

If I have a lot of posts in my feed that are getting boosted, my feed ends up out of chronological order and I end up rereading posts I’ve already read. Boosting should be a way for posts to enter my feed that I am not already exposed to, not a way to re-expose me to the same content multiple times.

**Comment by TymeForChange** [comment] 2022-11-12 21:09
**Counter argument:** Personally, I like the current method, with boosted datestamp change.  It gives people a second chance to see something that they missed.  I often will boost a post to a later time/day than the OP for that reason. (Missing the scheduled post feature from Twit, for this reason.) There is an account preference to group boosts, so you aren't inundated with multiple instances of the same boosted post.

**Comment by barts** [comment] 2022-11-12 23:56
I’m not suggesting the default be changed. But since Mastodon is all about preserving the timeline, this strikes me as something that should be a preference.

You can already hide boosts altogether. But I just want to see unique boosts so that my timeline has no redundancy (just what I’m folllowing in chronological order plus what I’m not following that’s been boosted into my timeline at the time it was boosted).

Sometimes I see the same post many times for several days, not just twice.

**Comment by biteater** [comment] 2022-11-16 11:35
A setting to hide boosted posts from accounts you already follow would be great.

I do feel the same as @barts. I see some posts multiple times over a few days, after I saw the original post. Currently the only alternative is to disable boosted posts for all the accounts you follow, but I personally want to see boosts for accounts I didn't know before.

An alternative solution to this issue might be to hide any boosts for posts the user has already seen. But this would require a history of seen posts for every user.

**Comment by barts** [comment] 2022-11-16 14:07
Just saw someone tooted about this same ***@***.***/109353782606533419

**Comment by danfigmatokens** [comment] 2022-12-21 17:41
Absolutely agreed. And with the idea that this should be more general to better not-repeat already seen boosts whether you follow the person or not. Lots of requests and complaints about this, here's my own and the most recent other one I saw.

https://mastodon.social/@schwa/109552835995069716
https://mastodon.social/@danvpeterson/109524465784386470

**Comment by danvpeterson** [comment] 2022-12-21 17:42
Absolutely agreed. And with the idea that this should be more general to better not-repeat already seen boosts whether you follow the person or not. Lots of requests and complaints about this, here's my own and the most recent other one I saw.

https://mastodon.social/@schwa/109552835995069716
https://mastodon.social/@danvpeterson/109524465784386470

**Comment by RockstarRaccoon** [comment] 2022-12-31 20:51
I will say, I'm finding it odd whenever I'm scrolling through the day's timeline and I see stuff posted by people I'm following, even mutuals, but it's a boost from some other account, especially if it's one I'm not even following... IDK what's up with that.

**Comment by ccazabon** [comment] 2023-01-30 00:49
Yes, this - I still want to see boosts from people I'm following, but only of things that I don't already see in my timeline.  I see the same things sometimes five or six times over the course of a day or two, and it's both confusing (because I think I've ended up going back too early in my timeline) and unfortunate (because I want to spend my time seeing things once, not over and over).

I still want to see things my follows boost from people that I'm not already following, because they're probably sharing interesting things.

**Comment by trwnh** [comment] 2023-05-19 06:24
Duplicate of #19665

**Closed by trwnh** 2023-05-19 06:24 UTC
Labels: suggestion
