### ISSUE TITLE
/api/v2/media 503 "error": "There was a temporary problem serving your request, please try again" 

### ISSUE THREAD

**Issue by twoheartliu** [mastodon/mastodon#17867] opened 2022-03-25 03:22 UTC
### Steps to reproduce the problem

1. when upload images it happen
2. try to docker logs mastodon_web_1 have not useful logs, just 503
3. s3 server interface is work,  images display is work
4. sometime /api/v1/media get is repeat 
...

### Expected behaviour

upload image is work

### Actual behaviour

is not work, 503

### Specifications

mastodon v3.4.6

mac Chrome

**Comment by twoheartliu** [comment] 2022-03-25 03:35
![image](https://user-images.githubusercontent.com/19301712/160049247-fa34a174-6dca-4b7a-905e-1429861dc9d7.png)
appear alternately, and upload 200 occasionally…

**Comment by Gargron** [comment] 2022-03-25 04:08
Duplicate of #17744, we cannot provide any meaningful support for failures at the S3 level.

**Closed by Gargron** 2022-03-25 04:08 UTC
Labels: bug
