### ISSUE TITLE
The 'profile:username' meta tag not always updated

### ISSUE THREAD

**Issue by bramus** [mastodon/mastodon#21592] opened 2022-11-24 22:05 UTC
### Steps to reproduce the problem

1. Visit https://mastodon.social/@bramus
2. Click on “Go to profile” to go to the new profile
3. Using DevTools, run `document.querySelector('meta[property="profile:username"]')`

### Expected behaviour

The value of the `content` attribute of that element should be `@bramus@front-end.social`

### Actual behaviour

The value of the `content` attribute of that element is `@bramus@mastodon.social` – it was not properly updated

### Detailed description

Possibly related bug: https://github.com/mastodon/mastodon/issues/21591

### Specifications

Mastodon 4.0.2

**Comment by afontenot** [comment] 2022-11-25 01:04
I think this is just a consequence of client side navigation (as in your other report), right? If you navigate directly to https://mastodon.social/@bramus@front-end.social while logged in, the meta property won't be set at all. If you expect it to be set, this bug should be about that instead.

**Comment by nightpool** [comment] 2022-11-25 02:34
Duplicate of https://github.com/mastodon/mastodon/issues/21591

**Closed by nightpool** 2022-11-25 02:34 UTC
Labels: bug
