### ISSUE TITLE
[Feature Request][API] Exclude lists from the home feed

### ISSUE THREAD

**Issue by lanodan** [mastodon/mastodon#9964] opened 2019-02-02 18:22 UTC
## Use case
- Following a group of users but not wanting them in the home feed if the list is displayed

## Proposal
- `exclude_lists` parameter to the `home` timeline endpoint and you give an array of the ids of the lists being displayed.

This is just so we can have some cooperation on the MastodonAPI but I think I’ll implement this one into pleroma anyway, at least on the backend.

**Comment by Gargron** [comment] 2019-02-03 00:40
We can't filter the home timeline on-read, only on-write. I mean we could, but we won't, because that's a performance bottleneck. Don't know how you're going to do it in Pleroma, Elixir's speed or concurrency or storing JSON blobs in the database won't make lots of joins and subqueries faster, I think.

If we could agree that adding someone to a list should exclude them from the home timeline, as a general rule, then I could be on board with that.

**Comment by christophehenry** [comment] 2021-04-19 10:37
I think this feature would be nice. And an elegant way to solve it, I think, is to add an option  to lists on the API to exclude the users on this list from home. From a DB standpoint, it would translate to a field on each subscription representating this exclusion. Then, the DB can decide whether the posts from this user should be fetched or not based on that field.

**Comment by belaset** [comment] 2022-11-19 22:15
I also would like this feature - I followed one of the gup.pe groups (super cool!) but there are so many posts that it's overwhelming my Home TL and drowning out voices of people I want to be following. Ideally I could put that group in its own list, so I can read it when I have time. (I would do the same for individuals who share lots of photos, where I do want to see and boost them but not all. the. time.) 

So far the only suggestion I've been given was to put the group in List A, and every one of the people I follow in List B, and then use List B as my new "Home"... but adding everyone to List B one by one, just so I can have a TL without one group in it, seems backwards.

**Comment by tyrosinase** [comment] 2022-12-07 15:56
I've done the same thing as @belaset describes (my "Home" is a list called "Everyone Else") but just discovered an *important* shortcoming in that method: unpinning Home means I no longer see announcements.

**Comment by trwnh** [comment] 2023-01-26 17:10
Related #22048 and i guess functionally a duplicate of #16556 (where more discussion ended up happening)

**Comment by trwnh** [comment] 2023-06-05 23:10
Fixed in #22048

**Closed by trwnh** 2023-06-05 23:10 UTC
Labels: suggestion
