### ISSUE TITLE
Verified URL's don't seem to work if you have a trailing "/" character

### ISSUE THREAD

**Issue by wkfry** [mastodon/mastodon#20459] opened 2022-11-11 23:29 UTC
### Steps to reproduce the problem

1. I added the <a rel="me" href="https://mastodon.social/@username">Mastodon</a> link to my personal site and published.
2. I added "http://mysite.net/" as a link in my profile.
3. The link in my profile didn't turn green.
4. Days later, I noticed someone else didn't have the trailing slash, so I removed it from my url.
5. Removing the trailing "/" caused the url to turn green.
...

### Expected behaviour

I would have expected a URL with a trailing "/" to be valid for verification.

### Actual behaviour

The URL on my profile didn't turn green (verified) until I removed the "/".

### Detailed description

Even a little error message would be fine. I was having a hard time trying to figure out why I wasn't showing up as verified.

### Specifications

Mastodon: v4.0.0rc1.

**Comment by erbridge** [comment] 2022-11-11 23:52
My git says this is probably because your website is set up to redirect the trailing `/` and the verifier doesn't follow redirects (which is maybe a bug if I'm reading it correctly). Could you link the real URLs you were using?

**Comment by nourkagha** [comment] 2022-11-12 00:15
Can you try re-adding the trailing slash and confirm if the green goes away?

The issue might not be a bug with the trailing slash, but simply the fact that you updated the link in your profile, because when verifying, you need to remove and re-add the link in order for it to turn green (it doesn't dynamically update).

**Comment by afontenot** [comment] 2022-11-12 06:49
> when verifying, you need to remove and re-add (or just modify/update) the link in order for it to turn green (it doesn't dynamically update).

That in itself might be a bug. If you resave your profile without changing your links, other federated instances will rescan your links automatically. (I've seen this happen with server logs.) It's strange that your home instance doesn't do the same.

**Comment by Anthchirp** [comment] 2022-11-12 13:59
cf. #9195

**Comment by wkfry** [comment] 2022-11-12 23:49
Well, this weird! The real URL is "http://wfry.net". I tried adding the "/" and the green verification on the link disappeared, but now when I remove the "/" again, it won't turn back to green! I've tried altering other properties on my profile, but now I can't get back to verified.

**Comment by nourkagha** [comment] 2022-11-12 23:54
> Well, this weird! The real URL is "http://wfry.net". I tried adding the "/" and the green verification on the link disappeared, but now when I remove the "/" again, it won't turn back to green! I've tried altering other properties on my profile, but now I can't get back to verified.

Might be related to #20304? Try with `https`.

**Comment by wkfry** [comment] 2022-11-13 00:12
My site is 100% static, so I don't have https on it.

**Comment by afontenot** [comment] 2022-11-13 00:30
@wkfry As you seem to be on the mastodon.social instance, you would indeed be affected by this, as it's updated to the latest release candidate. There's no issue in most cases getting a certificate for any site, static or not. If you run your server yourself then certbot can get you a free certificate from Let's Encrypt (it has a plugin for Apache, which you seem to be using). Or if someone else is hosting it then most hosts these days are able to give you a free SSL certificate on request.

**Comment by Darthagnon** [comment] 2022-12-14 23:39
This fixed it for me, as well. I have a [GitHub Pages website](https://robot-one.github.io), and added `rel="me"` to all my socials links, and Mastodon didn't recognise it until I removed the trailing slash

**Comment by vmstan** [comment] 2024-01-01 20:12
Closed as duplicate of #9195

**Closed** 2024-01-01 20:12 UTC
Labels: bug
