### ISSUE TITLE
Media Folder / Drive

### ISSUE THREAD

**Issue by maikelthedev** [mastodon/mastodon#26569] opened 2023-08-21 08:35 UTC
### Pitch

Sometimes you want to use a GIF that you've used previously but Mastodon right now doesn't have a way to recycle media uploads, which means wasted storage space on instances and/or CDNs. 

This feature exists in Firefish, you can go into the DRIVE module and there are all your media uploads, videos, images, even other types of data. And where in Mastodon you have the clip, in Firefish you have the same opening a menu "upload file / from drive" if you click "from drive" the same module that you se in DRIVE is open in a tiny window, you can access all your previous uploads and reuse the same content without having to upload it (and waste storage space) again. 

Like this one:

![Evil Phoebe](https://blahaj.zone/files/974eee36-ae7d-4ded-bd7f-f0c6c48d44b7)

ADVANTAGES:
* Saves A LOT of storage space. 
* Allows for organisation of commonly used media (e.g.: GIFs responses). 

### Motivation

1. Saving storage space
2. Reusing media content for quick responses.

**Comment by BakaDalek** [comment] 2023-12-08 21:08
also taking inspiration from Firefish/misskey

would love accounts to have media drive limits set by admin. To help prevent over use/abuse by any one account

And of course, role based limit assignments would be top tier. Give supporters more drive space since they are supporting the project!

**Comment by trwnh** [comment] 2024-03-19 22:53
Duplicate of #2317

**Closed by trwnh** 2024-03-19 22:53 UTC
Labels: suggestion
