### ISSUE TITLE
Wider panels by default, ability to resize panels horizontally

### ISSUE THREAD

**Issue by MirceaKitsune** [mastodon/mastodon#9463] opened 2018-12-07 18:49 UTC
Mastodon has a modern clean and appealing interface. However there's one nagging problem I keep constantly being annoyed about: The extremely narrow panels! I wanted to ask the team to please consider a way to resize them, as well as a better scaling and alignment mechanism by default. Here's a screenshot of how I have mine configured:

![screenshot_20181207_203227](https://user-images.githubusercontent.com/825418/49666054-7cf3f500-fa5f-11e8-9277-80196c1510c2.png)

It's impossible not to ask why on a 1080p screen, half of the page sits empty and unused, which is not just impractical but also looks ugly. Sure: I could pin more panels, but many of us are used to browsing using one window and the multi-panel layout is often more confusing than helpful. That and I'd really like to see each toot in a wider space, with larger embedded images and the text not feeling so crushed.

My own suggestion: To the left and right we have the two predefined (non-customizable) panels, whereas in between is the space where various panels can be added and removed. The predefined panels could be positioned at the edges of the screen (all the way to the left and right) whereas the customizable ones would be centered and using all the available space in between them. This means that if you've only pinned one panel, it will use 100% of that width... if you've pinned two they will each use 50%... so on and so forth.

Whether my idea or a better one can be considered, please offer us a way to make those panels wider. Even permanently resizing them by clicking and dragging would be very helpful.

**Comment by spaceottercode** [comment] 2018-12-09 22:12
I agree. This is also useful when viewing the Media section. I'm cheating and hacking the CSS atm but I also would find this handy?

**Comment by MirceaKitsune** [comment] 2018-12-31 13:43
I just found an instance called https://mastodon.host which offers a great example of what I'm suggesting. Its only issue is that the hardcoded panel to the right (Getting started) is also stretched, but other than that it's resizing the centered panels closely to how I wish Mastodon did it by default on all instances.

**Comment by MirceaKitsune** [comment] 2019-01-08 15:57
Something I just realized today, even if I've been doing it all along: Whenever I see an image in my timeline I find myself required to click and open it to be able to see it better. On Twitter I don't have this problem, as embedded images are shown at twice the size so I can fully understand them. This is quite an annoyance: I really hope the layout can be reworked to be a bit wider and solve this.

**Comment by spaceottercode** [comment] 2019-01-09 02:30
Also worth checking is Kevin Guertin's workaround (Mastodon : @leonivek@mastodon.social )

**Comment by ChameleonScales** [comment] 2019-01-21 22:38
I personally use userstyles with the [stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) Firefox addon. There are plenty for Mastodon but to me the very best is definitely [Variable width (variation)](https://userstyles.org/styles/154943/mastodon-variable-width-variation). I also have the original [Variable width](https://userstyles.org/styles/139721/mastodon-variable-width) and the [One column (Twitter design)](https://userstyles.org/styles/141802/mastodon-one-column-twitter-design) but they don't get as wide as the first one I linked.

All that said, it would be great to have a native option in the interface's preferences.

**Comment by ChameleonScales** [comment] 2019-01-22 00:18
I personally use userstyles with the [stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) Firefox addon. There are plenty for Mastodon but the one with the most expandable columns (and the one I always use) is definitely [Variable width (variation)](https://userstyles.org/styles/154943/mastodon-variable-width-variation). You can even have a single column that takes almost the whole screen (the left panel is still there but is always kept narrow). I also have the original [Variable width](https://userstyles.org/styles/139721/mastodon-variable-width) for when I want a wide space for tooting but the columns don't get as wide as with the variant.

All that said, it would be great to have some native options in the interface's preferences. Here's how I see it:

![](https://i.imgur.com/gJI84Fs.jpg)

**Comment by ChameleonScales** [comment] 2019-01-28 14:12
Bonus note: I just noticed that both [Variable width (variation)](https://userstyles.org/styles/154943/mastodon-variable-width-variation) and Kevin Guertin's [Full Image Preview and Wider Columns](https://userstyles.org/styles/167207/mastodon-full-image-preview-and-wider-columns) combine nicely when you check them both with the Stylus addon. So you can have limitlessly expandable columns and full image previews at the same time.

**Comment by MirceaKitsune** [comment] 2019-01-28 15:09
Is there any reason not to put the code from that addon into vanilla Mastodon? With of course a few corrections, such as not removing or resizing the right panel. It looks pretty good to me for a default.

**Comment by cnf** [comment] 2019-04-12 15:16
I came here because I was wondering the same thing...

**Comment by MirceaKitsune** [comment] 2019-04-12 22:29
For convenience: Here is a screenshot from mastodon.host who already has this type of layout, which offers a good hint as to what I'm suggesting.

Apart from the right panel also being stretched which I think looks ugly, the pinable tabs behave closely to how I wish they did on all Mastodon instances. I believe there should be a minimum and maximum width, so that columns don't become ridiculously wide either if you have a big monitor. Otherwise make them a bit wider than now, center them on the screen instead of the current left-to-right alignment, and make it so they resize based on the number of columns you pin.

![Screenshot_20190413_011611](https://user-images.githubusercontent.com/825418/56069057-e4adaa00-5d89-11e9-968c-78dc14063d0b.png)

**Comment by dnaf** [comment] 2019-05-11 05:01
related: #5736, #8632

**Comment by esureL** [comment] 2022-11-07 15:31
### Prelude

From my point of view, this should – one way or another – be included in the standard master. Not including it has been an oversight for years and should be added quickly. However, seeing that this isn't the case yet and that I couldn't find a consistently working result from searching the internet, I'll try to make a fairly exhausting post as a reference for Firefox users. :)

### Instance-wide custom theme

As a bonus: The (wonderful) admins of chaos.social provide a "wide" theme for their people. It doesn't look overly complicated, so if you manage an instance or have contact to your admin, you can look (or guide them) this way: https://github.com/chaossocial/custom/blob/master/themes/custom_wide.scss

I have no idea about the actual steps to implement this, sorry. :) However, it might be obvious from the repository.

### CSS modification as Firefox user

If you're using Firefox, you can just as well use the CSS modifications from the template for yourself. I'll start from the very beginning, some of the steps might be skippable for you.

- open a new tab
- type "about:config", enter
- search for parameter "toolkit.legacyUserProfileCustomizations.stylesheets"
- if necessary, change it to "TRUE"
- open "about:profiles"
- Find "Root Directory" and click "Open Folder", keep this tab open for later convenience
- In the newly opened profile folder, find the folder "chrome" (lowercase!). If it's not there, create it.
- In the "chrome" folder, find the file "userContent.css". If it's not there, create it.
- Open the .css file with a text editor and put the following code in:
```
/* Mastodon: use full browser width for columns */
@-moz-document domain(mastodon.social) {
    .drawer, .column {
       /* flex: 1 0 25% !important; */
	   	flex: 1 1 auto !important; 
		min-width: 300px !important;
		max-width: none !important;
    }
};
```
- **IMPORTANT: replace mastodon.social with the domain of your instance.**
- You remember that we left the about:profiles tab open earlier? Now is the time to hit the "restart normally" button on the upper right to make our changes work.

Remark: For me, in fullscreen mode, it looks best with at least five columns (drawer, home, notifications, direct messages, getting started). "Direct messages" is not pinned by default, but you can pin it to make it a permanent column.

If you want to do any adjustments yourself, you can probably search the internet for some CSS fundamentals and experiment with the settings. Just remember to restart firefox (easiest with the button in about:profiles) to apply the changes. Also remember to use the "!important" modifier. A lot of CSS modifications I found online didn't work for me (at least for a specific instance), because the settings got overridden somewhere in the CSS hiearchy.

I hope that helps.

**Comment by barathrm** [comment] 2023-07-19 11:24
Does anyone know if there's a reason why the option of not being able to make the columns wider hasn't been implemented in almost 5 years now? 

This might be slightly off-topic for this specific issue, but I'm interested in the decision making processes around mastodon. If you search this repo for related issues you'll find many. Users have been creating their own work-arounds for many years.

Some related examples

- 2023 https://github.com/mastodon/mastodon/issues/25349
- 2022 https://github.com/mastodon/mastodon/issues/22009
- 2019 https://github.com/mastodon/mastodon/issues/10750
- 2018 https://github.com/mastodon/mastodon/issues/8632
- 2017 (:exclamation:) related PR https://github.com/mastodon/mastodon/pull/711
- 2017 https://github.com/mastodon/mastodon/issues/5736

**Comment by paniash** [comment] 2023-09-09 11:46
Any updates on this?

**Comment by trwnh** [comment] 2023-12-30 08:46
Duplicate of #8632

**Closed by trwnh** 2023-12-30 08:46 UTC
Labels: suggestion
