### ISSUE TITLE
Make the Getting Started column/menu movable

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#5710] opened 2017-11-15 14:23 UTC
From [the toot with the idea in it](https://mastodon.social/@abbenm/99008859536256147):

> I wish #mastodon allowed you to move the "Getting Started" pane left or right. If pin a new column with a hashtag you are interested in, the "Getting Started" pane moves further and further to the right.
> 
> I'd rather have it continuously visible, and the followed tags trailing off to the right.

This is the second person in two days who I've seen request this, so I think it should be here on the issue list!

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nailyk-fr** [comment] 2017-11-18 13:25
Only to be more clear about what column we are talking about: https://github.com/tootsuite/mastodon/pull/3207 bring ability to pin lot of columns and that is really great. 
However the 'multi purpose' column (the far-right variable column that appears for getting-started menu & searches) cannot be moved. 
While creating more than 2 custom columns, even on full HD screens, this make Mastodon difficult to use because of constant horizontal scrolling. On smaller screens like laptop it almost prevent custom columns using. 

P.S.: My instance is currently running the latest (2.0.0) release. 

Many thanks.

**Comment by trwnh** [comment] 2023-01-28 20:10
Duplicate of #4305

**Closed** 2023-01-28 20:25 UTC
Labels: ui, suggestion, new user experience
