### ISSUE TITLE
Hashtag search should show exact match first

### ISSUE THREAD

**Issue by mfitzp** [mastodon/mastodon#19857] opened 2022-11-06 13:38 UTC
### Steps to reproduce the problem

1. Open the web interface
2. Search for a hashtag with a lot of derivative tags, e.g. #python
3. The exact match #python will not be shown in the list
4. Click "Load more..." until you find it

### Expected behaviour

Exact match tags should appear first in the list, other matching tags after

### Actual behaviour

Matching tags seem to be sorted almost randomly

### Detailed description

When searching for a tag with a lot of derivative tags the exact match can be hard to find in the list. You have to page through "Load more..." until you find it, even though you know exactly what you're looking for. Many of the other tags have nothing under them.

Since you *must* click on the tag to view the feed, paging through isn't an option. There isn't a mechanism to open the specific tag as typed (regardless of whether it exists).

https://user-images.githubusercontent.com/126239/200173762-8e7937a1-0eae-4b76-a73e-2e54a9ab7dbf.mp4

Ideally, exact match tags should be shown first (and perhaps highlighted somehow). The remainder of the tags could be sorted by activity. 

### Specifications

Issue seen on web interface and Tusky, iOS app. Unknown server version (instructions to find it would be good here!) but can replicate on current fosstodon.org / mastodon.social

**Comment by tyrosinase** [comment] 2022-11-06 16:51
Oh gosh this, yeah. Short hashtags (#/resin, etc.) are just *gone* for all searchability purposes right now. 

Weirdo workaround: post (dm-to-self) with the hashtag, click in it, and then optionally pin it. Doesn't help with adding hashtags to existing pinned columns, of course.

**Comment by ClearlyClaire** [comment] 2022-11-06 17:01
Kind of a duplicate of #19575, different only in that it suggests hashtags to be sorted by activity.

**Comment by tyrosinase** [comment] 2022-11-06 17:07
I think you're right, though neither one actually says that sometimes the actual short version just doesn't appear at *all,* which is what I'm seeing.

(It's possible that the batch with the match is getting dropped in a silent timeout given all the lag that's happening now, though.)

**Comment by ogrisel** [comment] 2022-11-06 17:09
Related: it would be nice to be able to select the exact match even if there are 0 results currently indexed on the instance. This would make it possible to follow the hashtag and track future posts.

**Comment by mfitzp** [comment] 2022-11-06 19:59
> Kind of a duplicate of #19575, different only in that it suggests hashtags to be sorted by activity.

@ClearlyClaire agreed, I've edited the title to remove that 2nd part (it's more of a feature request) so this can be closed as a duplicate.

**Comment by ClearlyClaire** [comment] 2022-11-06 21:53
Closed as duplicate of #19575

**Closed by ClearlyClaire** 2022-11-06 21:53 UTC
Labels: bug
