### ISSUE TITLE
Fav / bookmarks from other instances disappeared

### ISSUE THREAD

**Issue by dadall** [mastodon/mastodon#23206] opened 2023-01-23 08:18 UTC
### Steps to reproduce the problem

Install Mastodon v4.1.0rc1
Check fav/bookmarks

### Expected behaviour

See all your bookmarks and fav from the fediverse

### Actual behaviour

Only local ones are visible

### Specifications

Mastodon 4.1.0rc1
Ruby 3.0.4
Nodejs  14.22

**Comment by dadall** [comment] 2023-01-23 09:34
Adding new fav/bookmals seems to work as expected. Only old ones are gone.

**Comment by dadall** [comment] 2023-01-23 12:40
The server is configured with media remove (after 3 days) and preview_cards remove (after 3 days) and account cull without parameters. Can't these configuration be the issue ? 
I've been warned few hours after I upgraded to mastodon 4.1.0rc1. That's why I imagine it can be an issue and not a configuration problem.

**Comment by pedroCX486** [comment] 2023-01-23 23:11
I can confirm the same happening to me, I don't have (as far as I know) any settings aggressively removing remote posts on my instance. Lost a lot of favorites/bookmarks after the upgrade.

**Comment by ClearlyClaire** [comment] 2023-01-24 08:26
What do your content retention settings (`/admin/settings/content_retention`) look like? In particular, did you set the “Content cache retention period”?

Can you list the exact `tootctl` calls you made, if any?

**Comment by pedroCX486** [comment] 2023-01-24 14:18
> What do your content retention settings (`/admin/settings/content_retention`) look like? In particular, did you set the “Content cache retention period”?
> 
> Can you list the exact `tootctl` calls you made, if any?

Media cache content period: 14

Content cache retention period: unset

User archive retention period: unset

‘tootctl’ calls after the upgrade: None

My maintenance script didn’t had the time to run after the upgrade (I only run every two months and I was only a month into the period).

**Comment by ClearlyClaire** [comment] 2023-01-24 14:25
> Content cache retention period: unset

Was it ever set to any other value?

Overall, your report is very surprising and I'm really unsure what could have happened. Do you know for sure you lost favs or bookmarks? If so, do you remember which posts they were on? Do you know if those posts are still in the database? If they do still exist on the originating server?

**Comment by pedroCX486** [comment] 2023-01-24 19:46
> > Content cache retention period: unset
> 
> Was it ever set to any other value?
> 
> Overall, your report is very surprising and I'm really unsure what could have happened. Do you know for sure you lost favs or bookmarks? If so, do you remember which posts they were on? Do you know if those posts are still in the database? If they do still exist on the originating server?

In the early days of the instance I had it set to 15 days, but since early December last year I've unset it.

And yep! I've found those posts again on the remote instance (tilde.zone) and managed to re-favorite and reboost some of them. No errors were thrown or anything. So they exists on the originating server but maybe not on my db, I don't know how to check the last part as I'm a lowly front-end dev, barely know my way around DBs inside docker.

**Comment by ClearlyClaire** [comment] 2023-01-25 08:27
> In the early days of the instance I had it set to 15 days, but since early December last year I've unset it.

Were the lost bookmarks from before early December or after it? The “Content cache retention period” setting is extremely aggressive and will delete every remote post older than the threshold regardless of whether the post is bookmarked, boosted, added to favorites, mentions someone…

> And yep! I've found those posts again on the remote instance (tilde.zone) and managed to re-favorite and reboost some of them. No errors were thrown or anything. So they exist on the originating server but maybe not on my db, I don't know how to check the last part as I'm a lowly front-end dev, barely know my way around DBs inside docker.

Hm, there is no easy way to tell, but a strong indication may be: did you have to re-import those posts or did you find them on your own instance without e.g. having to paste their URL in the search bar?

> Edit: Also I'm probably not eligible to report errors here anymore, migrated to glitch-soc after the error happened hoping it was a fluke with Mastodon-mainline (I migrated after the rc1 was merged into glitch so it was ahead). So I guess this is where my report ends.

That's fine, I happen to be the maintainer of glitch-soc and as far as I can tell, there shouldn't be any meaningful difference wrt. this issue.

**Comment by dadall** [comment] 2023-01-25 16:11
I just updated my instance to the rc2 and fav and bookmarks from the other instances are gone, again :shrug:

**Comment by ClearlyClaire** [comment] 2023-01-25 16:12
> I just updated my instance to the rc2 and fav and bookmarks from the other instances are gone, again shrug

What do your content retention settings (`/admin/settings/content_retention`) look like?

**Comment by dadall** [comment] 2023-01-25 16:16
There we go.... 1 day :facepalm:

**Comment by ClearlyClaire** [comment] 2023-01-25 16:17
Yeah, as pointed out, this setting is destructive and will remove posts even if they had bookmarks or favorites, in which cases those would be lost too.

**Comment by dadall** [comment] 2023-01-25 16:19
Things are fixed now. Sorry for the noise. I let @pedroCX486 reply to this issue if needed before I close it.

Thanks for your patience and your help @ClearlyClaire :hugs:

**Comment by pedroCX486** [comment] 2023-01-25 21:41
> Were the lost bookmarks from before early December or after it? The “Content cache retention period” setting is extremely aggressive and will delete every remote post older than the threshold regardless of whether the post is bookmarked, boosted, added to favorites, mentions someone…
Basically since the instance was created in October, but makes since I had it set to 15 days before

> Hm, there is no easy way to tell, but a strong indication may be: did you have to re-import those posts or did you find them on your own instance without e.g. having to paste their URL in the search bar?
Had to re-import!

But here's a plot twist: Some of those instances where the posts lived had turned the aggressive removal on. Which in turn explains why some (majority) disappeared. The ones on tilde.zone are still a mystery to me but I managed to recover them.

> That's fine, I happen to be the maintainer of glitch-soc and as far as I can tell, there shouldn't be any meaningful difference wrt. this issue.

Ah nice!

I'll consider this issue resolved for now until I have more data on what the hell happened and will open another if it happens again, thank you for your patience with us. :D

@dadall Feel free to close this issue :D

**Comment by ClearlyClaire** [comment] 2023-01-26 08:47
> But here's a plot twist: Some of those instances where the posts lived had turned the aggressive removal on.

That shouldn't cause *your* information to disappear, as it would only affect their local cache, though.

> I'll consider this issue resolved for now until I have more data on what the hell happened and will open another if it happens again, thank you for your patience with us. :D

Works for me! At this point I think it was an instance of shooting yourself in the foot with the content retention setting, but don't hesitate to get back to us if you notice anything odd. In the meantime, we will probably reword the setting's description to make things clearer.

**Closed** 2023-01-26 08:49 UTC
Labels: bug
