### ISSUE TITLE
Option to hide followers and follows on public profiles from non-users

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#5337] opened 2017-10-11 19:36 UTC
When a public profile is viewed (outside the web-app) the list with followers and who this user follows is always displayed. It doesn't matter it's viewed as a local (logged in) Mastodon user, a remote Mastodon user or as a non-user (or not logged in user). Even if a Mastodon user has a private account (followers must be approved) the followers/followers are publicly visible.

_This is a privacy issue._

It would great if there is an option to hide the follower/follows lists on the public profile from non-users AKA not logged in users (like birdsite has). For private accounts this option should be enabled by default (hidden), for non-private accounts the option should be disabled by default (not hidden - current situation).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by fsnk** [comment] 2017-10-12 12:07
I'd like to add the suggestion that followed/follower _counts_ also be hideable, both from logged out and logged in users.

One thing I really don't like in social media is how people create status hierarchy around follower counts. It's very common to see exchanges where someone's opinions are belittled or dismissed on the basis of their follower count, and I think this feeds a culture that privileges popularity in discussions.

**Comment by jeroenpraat** [comment] 2017-10-12 18:17
@fsnk I think you should create a separate issue for that feature request.

**Comment by anmol26s** [comment] 2017-11-19 18:58
:+1: Please make it as high priority. Its really very important feature for privacy.

**Comment by deutrino** [comment] 2017-11-28 19:24
See also #1660.

**Comment by jeroenpraat** [comment] 2017-11-28 22:43
@deutrino Not really related. This is only about hiding the follow/follows lists from people who are not logged in.

**Comment by ignasGaubas** [comment] 2017-12-12 08:08
Hello what is doing?

**Comment by deutrino** [comment] 2018-03-30 18:20
I note that #6901 appears to be a bit broader in scope than this issue - it's not spelled out, but #6901 appears to be asking to hide this info in *all* views, not just the public web view as this issue requests.

**Comment by trwnh** [comment] 2018-06-28 21:11
Can this be closed, or is there still a request to only hide it for public views? Or is hiding it in all views sufficient to fulfill this request?

**Comment by vearalyn** [comment] 2020-06-12 06:44
To protect following and followers privacy there really should be an option to hide them even from people following you on a public account. Doesn’t make sense you can hide your liked videos but not who you follow

**Comment by trwnh** [comment] 2020-06-12 17:47
#7532 hides it for everyone, not just non-users

**Comment by leecolleton** [comment] 2022-11-21 20:43
This appears to be fixed, but confusingly it shows "This user doesn't follow anyone yet." and "No one follows this user yet." even though the following / followers counts are visible. Perhaps that text could be changed to "This user keeps their social graph private." or somesuch

**Comment by trwnh** [comment] 2023-05-13 23:58
Duplicate of #6901 and fixed by #7532 -- remaining issues (if any) can be filed as separate tickets

**Closed by trwnh** 2023-05-13 23:58 UTC
Labels: suggestion
