### ISSUE TITLE
Feature Suggestion: Implementing a "Starter Pack" Feature in Mastodon

### ISSUE THREAD

**Issue by T3kn3vr4** [mastodon/mastodon#33091] opened 2024-11-28 16:00 UTC
### Overview

As Mastodon continues to grow and attract new users, the platform's user onboarding experience becomes increasingly important. A potential enhancement to consider is the introduction of a "Starter Pack" feature, similar to that offered by Bluesky. This feature could significantly improve user engagement by helping new users quickly build and customize their social media experience.

### What is a Starter Pack?

Bluesky's Starter Packs are curated collections of accounts and feeds tailored to specific interests, topics, or geographic areas. They allow users to follow multiple accounts with a single tap, instantly populating their feeds with relevant content. Key features of Bluesky's Starter Packs include:

- **Customization:** Users can include up to 150 people and 3 custom feeds.
- **Ease of Use:** Packs can be shared via links or QR codes, making it easy for users to distribute them.
- **Accessibility:** Any user can create and share a Starter Pack.

### Potential Implementation Steps

1. **User Interface Design:** Integrate a "Starter Packs" section into user profiles, enabling users to create and manage packs.

2. **Creation Process:** 
   - Allow users to name their pack and add a brief description.
   - Enable selection of up to 150 accounts and 3 feeds.
   - Include options to share the pack via a unique link or QR code.

3. **Discovery and Sharing:** 
   - Develop a mechanism for users to explore and adopt popular Starter Packs.
   - Encourage community members to share their packs through social media or Mastodon channels.

### Conclusion

Adopting a Starter Pack feature could provide Mastodon users with a richer and more personalized social media experience. By facilitating easier connections and content discovery, this feature could enhance user satisfaction and retention. It could also strengthen Mastodon's position as a user-friendly alternative in the decentralized social media landscape.

_______________________________________________

INTRODUCING BLUESKY STARTER PACKS:
https://bsky.social/about/blog/06-26-2024-starter-packs

STARTER PACKS:
https://bluesky.ms/starterpacks/

BLUESKY STARTER PACKS EXPLAINED: HOW TO START POSTING:
https://www.kapwing.com/resources/bluesky-starter-packs-explained-your-guide-to-getting-started/

### Benefits for Mastodon

1. **Enhanced User Onboarding:** New users can quickly and easily discover interesting accounts, reducing the initial friction of starting from scratch.
   
2. **Community Building:** Curated packs can foster community connections around shared interests or regional affiliations.

3. **Increased Engagement:** Users are more likely to remain active if they find relevant content quickly.

**Comment by mjankowski** [comment] 2024-11-28 16:09
Similar to https://github.com/mastodon/mastodon/issues/32946

**Comment by trwnh** [comment] 2024-11-29 05:51
Duplicate of #32946 imo

**Closed by trwnh** 2024-11-29 05:51 UTC
