### ISSUE TITLE
Include posts in list feeds that were created prior to a user being added to the list

### ISSUE THREAD

**Issue by seanthegeek** [mastodon/mastodon#22505] opened 2022-12-19 16:57 UTC
### Pitch

Content of a list should include all recent (one month?) posts from the members of that list, not just posts that were created after the user was added the list.

### Motivation

For users accustomed to Twitter lists it is confusing and disappointing that only posts that are created after the creation of the list will show up on the list.

The web UI explains why a list has no content despite adding members

> There is nothing in this list yet. When members of this list publish new posts, they will appear here.

But some mobile apps do not, including Fedilab and Tusky. Initially I thought the lists feature was broken in Mastodon. I can't be the only one.

**Comment by jhedlund** [comment] 2023-01-23 18:45
I think this is a dupe of #16290 , and it gets worse as pointed out in https://github.com/mastodon/mastodon/issues/16290#issuecomment-1320974133 that if you log out and back in, the list is empty again and doesn't populate until new toots come in from those in the list.

**Comment by trwnh** [comment] 2023-01-26 17:05
Duplicate of #16290 yeah

**Closed** 2023-05-16 04:46 UTC
Labels: suggestion
