### ISSUE TITLE
Highlight toots from followed hashtags

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#23216] opened 2023-01-23 13:43 UTC
### Pitch

![image](https://user-images.githubusercontent.com/17537000/214054409-137b76ae-e895-408d-b06d-76ce5b2bbd46.png)

### Motivation

I sometimes accidentally follow hashtags, and don't know where toots are coming from.

**Comment by ClearlyClaire** [comment] 2023-01-23 14:20
Duplicate of https://github.com/mastodon/mastodon/issues/22444

**Closed by ClearlyClaire** 2023-01-23 14:20 UTC
Labels: suggestion
