### ISSUE TITLE
Allow the user to arbitrarily filter posts that exceed a defined threshold of hashtags

### ISSUE THREAD

**Issue by RianQuenlin** [mastodon/mastodon#24351] opened 2023-04-01 17:55 UTC
### Pitch

I sometimes see posts on federated feeds that use every single hashtag they can think of, often taking up the entire screen. Instead of having to block obvious trolls there should instead be a feature in filters that says "Hide posts that have [#] or more hashtags" to cull their visibility.

### Motivation

Why? Because of people like this. This idiot used a triple-digit amount.
![image](https://user-images.githubusercontent.com/88654233/229306643-83a6b5f0-8c5d-4b96-8125-9a1da74d3aef.png)

Before you say that certain things have multiple hashtags, that's a personal problem you have to solve yourself.

**Comment by Cassolotl** [comment] 2023-04-06 19:41
Duplicate of *Ability for users to hide posts with more than n hashtags #19185* (Sept 2022) ?

**Closed** 2023-05-19 06:02 UTC
Labels: suggestion
