### ISSUE TITLE
Exact matches for hashtags should be placed at the top of the results list

### ISSUE THREAD

**Issue by velw** [mastodon/mastodon#22253] opened 2022-12-12 17:01 UTC
### Steps to reproduce the problem

1. Enter the hashtag you want into the "Explore" search box or type it into the post edit field
2. The server will return a list of hashtag matches often including longer tags that match only the first section
3. In many cases, it is now impossible to find the hashtag you wanted (the exact match for what you typed in) because there are too many more popular but only partially matching hashtag results. If you scroll or view the next page enough times, maybe you will find it... maybe....
4. If you accidentally hit the space bar while using the post edit field, the hashtag you wanted will now be changed to one of the longer partial matches (possibly without you realising).
5. (Note - one example I've seen this problem with is the hashtag "#news")
...

### Expected behaviour

The hashtag search result that exactly matches what has been typed in or entered should be returned as the first result among matching hashtags

### Actual behaviour

So many other, more active hashtags that only match partially (the initial section, for example) are returned it becomes impossible to find the exact match hashtag in the list of results.

### Detailed description

When entering a hashtag into the "Explore" search box or typing it into the post edit field, a list of popular, matching hashtags is returned (either as a drop-down, on the post edit field, or as a page of results in "Explore").

In both these cases, the server will often return a list of hashtag matches that include longer tags matching only the first section. It will then be now impossible to find the hashtag you wanted (the exact match for what you typed in) because there are too many more popular but only partially matching hashtag results. 

Also, if you accidentally hit the space bar while using the post edit field without realising it automatically substitutes the top hashtag result for whatever you have typed, what you entered will now be changed to one of the longer and incorrect partial matches.

If there is a hashtag search result that exactly matches what has been typed in or entered, that should be returned as the first result among matching hashtags (and the default choice for any automatic substitution - not that anything will need to be substituted, as it will be the same).

This problem currently affects anyone searching for a hashtag term that has been incorporated as a prefix into other, longer and popular hashtags, making it impossible to find the hashtag they wish to use - the one they actually typed in.

### Specifications

Web interface via Firefox 98 and Samsung Internet (I don't think this bug is browser specific)

**Comment by ineffyble** [comment] 2022-12-13 01:01
Duplicate of #17494

**Closed by ineffyble** 2022-12-13 01:01 UTC
Labels: bug

**Comment by velw** [comment] 2022-12-13 06:50
> Duplicate of #17494

Ack, sorry - I thought I'd searched for an existing issue. Troubling that this has been around since February and still hasn't been fixed, especially when hashtags have been made the only way to find content on Mastodon. 😔

**Comment by ineffyble** [comment] 2022-12-13 07:33
There's a draft fix here: https://github.com/mastodon/mastodon/pull/21315

Part of the reason it hasn't generated more attention might be because it only impacts instances that have full-text search (ElasticSearch) enabled, which many don't.

**Comment by ineffyble** [comment] 2022-12-13 07:34
As a workaround you can go straight to the URL for the hashtag in question by the way. E.g. you can go to https://<your-instance>/tags/<desired-tag>

**Comment by velw** [comment] 2022-12-29 13:09
> As a workaround you can go straight to the URL for the hashtag in question by the way. E.g. you can go to `https://<your-instance>/tags/<desired-tag>`

Thank you! Yes, I've been doing this. It's clunky but it works. 👍
