### ISSUE TITLE
Group notifications

### ISSUE THREAD

**Issue by koyuawsmbrtn** [mastodon/mastodon#21476] opened 2022-11-23 12:56 UTC
### Pitch

Grouping notifications would be a great thing since it solves the clutter living in your notification panel.

### Motivation

Once a post goes viral it clutters up your notification panel. Having the option to group notifications would make it easier searching through your notifications and finding what matters.

**Comment by azonenberg** [comment] 2022-11-26 18:44
Assuming you're asking for behavior similar to birdsite, where you see "X people boosted / favorited this post" (maybe separate combined notifications for boost/favorite) then you can expand to get a list of usernames? If so, I'm all in favor.

Related: it would help with decluttering if the notification didn't include the *full* text of your own toots, but truncated to the first few lines (configurable under preferences). I can only fit maybe 2 notifications on a 1080p screen for longer multiline toots and that means a lot of scrolling.

**Comment by wlonkly** [comment] 2022-11-27 00:41
Duplicate of #1483, I think

**Comment by koyuawsmbrtn** [comment] 2022-11-27 00:51
> Duplicate of #1483, I think

Right

**Closed** 2022-11-27 00:51 UTC
Labels: suggestion
