### ISSUE TITLE
Automatic Dark Mode

### ISSUE THREAD

**Issue by Exalm** [mastodon/mastodon#18141] opened 2022-04-27 20:07 UTC
### Pitch

Currently mastodon has light/dark/high contrast styles, but it doesn't allow following the OS preferences like e.g. GitHub or Twitter do. It would be nice to have in addition to always dark/always light.

As a bonus, the high contrast option could be independent, same as true black dark mode is in the iOS app.

### Motivation

Same as other websites - switching it every time manually is pretty annoying.

**Comment by ykzts** [comment] 2022-04-28 06:56
Duplicate of #10976

**Closed by ykzts** 2022-04-28 06:56 UTC
Labels: suggestion
