### ISSUE TITLE
Admin dashboard dates are not inclusive

### ISSUE THREAD

**Issue by twilde** [mastodon/mastodon#21707] opened 2022-11-27 01:40 UTC
### Steps to reproduce the problem

1. Open the admin dashboard at instance-url/admin/dashboard
2. Observe dates listed in the top left corner.
3. Observe that the current day is included in those dates.

### Expected behaviour

Stats should include the current day

### Actual behaviour

Stats do not include the current day

### Detailed description

Thew new users measure code (https://github.com/mastodon/mastodon/blob/main/app/lib/admin/metrics/measure/new_users_measure.rb) includes the current date, but in the SQL query it is truncated using DATE_TRUNC('day'), which truncates to 00:00:00 on the day in question. This means that the stats effectively only update once per day, when the server date advances to the next date. This is unexpected and possibly unintentional.

### Specifications

Mastodon 4.0.2

**Comment by VanillaDeath** [comment] 2022-11-28 19:25
Duplicate of #20268

**Closed** 2022-11-28 20:45 UTC
Labels: bug
