### ISSUE TITLE
Option to choose who can answer to my post

### ISSUE THREAD

**Issue by Twilightssuperb** [mastodon/mastodon#29387] opened 2024-02-24 16:30 UTC
### Pitch

Like at Twitter: "All", "Only people who I follow", "Only mutual friends", "Only my subscribers" (not sure last version would be acceptable).

### Motivation

Defense from trolls and other aggressive speakers.

**Comment by trwnh** [comment] 2024-02-25 05:26
Duplicate of #14762

**Closed by trwnh** 2024-02-25 05:26 UTC
Labels: suggestion
