### ISSUE TITLE
In light of "Add new public status index" #26344, set default post visibility to "unlisted"

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#26408] opened 2023-08-09 09:50 UTC
### Pitch

Gargron said [here](https://github.com/mastodon/mastodon/pull/26344#issuecomment-1666201624):

> It is my decision to unite all discovery features in one setting, because all of this stuff is an expected part of a social network and splitting it up into different settings that everyone has to opt-into one by one just to get the same behaviour they get by default on other social media seems like a bad user experience. Also, `discoverable` is already a federated attribute.

The feature:

> The idea here is to allow public posts by discoverable users to show up in search results.

I think being in plaintext searches for public posts should be opt-in rather than opt-out. So I think the default for new accounts should be for post visibility to be set to "unlisted" by default, so that new users start at a "medium" amount of "loudness": they have to make a profile change to be quieter (followers only), and they also have to make a profile change to be louder (public posts, searchable posts, in federated timeline, etc).

I understand that this will happen by default as profiles are not discoverable by default when you make a new account. However, of the two options "make profile findable to people looking for profiles" and "make posts findable to people looking for public posts", I think the latter is much more likely to open new people up to harassment. People looking for public posts on a particular topic in order to reply and harass will have a much easier time harassing someone if their posts are findable, compared to if their profile is findable.

### Motivation

At the moment, discoverability is set to "off" by default, which is good. It means users have to opt in to have their account listed in the "find new profiles of accounts to follow" page.

Similarly, I think being in plaintext searches for public posts should be opt-in rather than opt-out.

For example, I am happy for people to find my profile by looking at the "find new profiles of accounts to follow" page, but I already get more than enough reply-guys from boosts and having my posts appear in the public timelines. I know that I can change my post searchability by making my post privacy "unlisted" by default, but new users don't know that. Defaulting to privacy is what Mastodon shows of about being, so this is a logical choice.

I think when this new search comes in a lot of people will be changing their default post visibility to "unlisted", because like me they are happy to have their profile discoverable but they want to avoid getting reply-harassed by randos. I think it is wise and compassionate to provide that "unlisted" post privacy for new users by default.

**Comment by shleeable** [comment] 2023-08-09 10:44
There shouldn't be a default... you're allowed to prompt people for their choice.
Too many people making too many assumptions.... making choices for other people is the root cause of these arguments

**Comment by brendanjones** [comment] 2023-08-09 14:23
Same comment as on https://github.com/mastodon/mastodon/issues/26412#issuecomment-1671430872, this isn’t the right solution imo. Better to split out the discoverability settings and everyone needs to opt in to search, new user or not. No need to fiddle with post visibility settings.

**Comment by Cassolotl** [comment] 2023-08-09 17:07
@brendanjones 

> this isn’t the right solution imo. Better to split out the discoverability settings and everyone needs to opt in to search, new user or not.

Is there an issue for that that I can support?

**Comment by renchap** [comment] 2023-08-09 21:07
Hi,

Thanks for sharing your concerns about search with us. The mentioned PR is not done yet and discussions are in progress on how the exact implementation will be, leaning towards having a specific flag for indexing posts into Mastodon's built-in search.

I am closing this issue, not to dismiss your point, but because discussions about this are happening in many places and the mentioned PR will have changes that should fix the issue you (and many other) are concerned about.

**Closed by renchap** 2023-08-09 21:07 UTC
Labels: suggestion

**Comment by brendanjones** [comment] 2023-08-09 22:34
> @brendanjones
> 
> > this isn’t the right solution imo. Better to split out the discoverability settings and everyone needs to opt in to search, new user or not.
> 
> Is there an issue for that that I can support?

@Cassolotl  not that I know of. For now I’d say wait and see what changes are made to that PR.
