### ISSUE TITLE
Post to local timeline only

### ISSUE THREAD

**Issue by micahwalter** [mastodon/mastodon#22932] opened 2023-01-04 14:01 UTC
### Pitch

I'm not sure how this would work exactly, and I know there has been a lot of discussion around post privacy settings already, so I am guessing this has already been discussed somewhere else. But, I keep thinking it would be very nice to be able to choose "Local Timeline Only" when creating a new post. This would mean only users of the local server would be able to view the post, which is a little different than the currently supported "Follows Only." 

### Motivation

I think it would help improve the community aspect of servers and give good motivation for groups to create community around mutual interests, and create reasons for wanting to choose one server over another. Being able to post privately to an entire community means only members of that community would be able to read the post, and would potentially create safer environments where participants felt more free to openly discuss topics related to that community.

Of course, servers with open registration would need to be able to explain that anyone could just sign up for an account in order to read their post, but I think that could be well explained with the right terminology and UI design.

**Comment by Cassolotl** [comment] 2023-01-04 18:59
I feel like this is probably a duplicate of *Add a "Local timeline" privacy option #861* (April 2017). If so, please close this issue and add your supportive comments and reaction emojis to the older post. Thank you! :)

**Closed** 2023-01-06 16:34 UTC
Labels: suggestion
