### ISSUE TITLE
audit log breaks with deleted statuses

### ISSUE THREAD

**Issue by nightpool** [mastodon/mastodon#6426] opened 2018-02-04 05:43 UTC
going to https://cybre.space/admin/action_logs currently returns a 500 error

logs: 
```
 ActionView::Template::Error (No route matches {:account_username=>nil, :action=>"show", :controller=>"statuses", :id=>#<Status id: nil, uri: nil, text: "", created_at: nil, updated_at: nil, in_reply_to_id: nil, reblog_of_id: nil, url: nil, sensitive: true, visibility: "public", spoiler_text: "", reply: false, favourites_count: 0, reblogs_count: 0, language: nil, conversation_id: nil, local: false, account_id: nil, application_id: nil, in_reply_to_account_id: nil>}, possible unmatched constraints: [:account_username, :id]):
     4:       = image_tag action_log.account.avatar.url(:original), alt: '', width: 40, height: 40, class: 'avatar'
     5:     .log-entry__content
     6:       .log-entry__title
     7:         = t("admin.action_logs.actions.#{action_log.action}_#{action_log.target_type.underscore}", name: content_tag(:span, action_log.account.username, class: 'username'), target: content_tag(:span, log_target(action_log), class: 'target')).html_safe
     8:       .log-entry__timestamp
     9:         %time= l action_log.created_at
    10:     .spacer
app/lib/tag_manager.rb:44:in `url_for'
app/helpers/admin/action_logs_helper.rb:37:in `log_target_from_history'
app/helpers/admin/action_logs_helper.rb:8:in `log_target'
app/views/admin/action_logs/_action_log.html.haml:7:in `_app_views_admin_action_logs__action_log_html_haml__247563165727585356_70074423886980'
app/views/admin/action_logs/index.html.haml:5:in `_app_views_admin_action_logs_index_html_haml__4526750395608647622_70074485034700'
```

this happens after taking action on statuses that are later deleted, I assume

**Comment by masv** [comment] 2018-02-19 20:28
Steps to reproduce:

1. As a user, post a status with media attached.
2. As an admin:
    1. Report the user's status.
    2. Open the report.
    3. Click "Hide media attachments".
3. As the original poster, delete the status.
4. As an admin, try to open the action log.

This seems to break because `Admin::ActionLogsHelper.log_target_from_history` (and `TagManager`) tries to create a link to a status that has no account associated with it.

`log_target_from_history` builds a new `Status` from the `recorded_changes` of the log and uses that for the link, but it seems unlikely to me that those attributes will ever include an account ID. Is that correct?

I'm not sure if it makes sense to attach an Account ID to a log to make it linkable even when the target status has been removed, or if perhaps it's better to simply output a string saying that "Status 1234 was deleted."

I'd be happy to contribute a fix either way, but since I'm new here I want to get some feedback before I get cracking 🙂

**Comment by unarist** [comment] 2018-03-26 11:32
@Gargron is implementing soft-deletion of statuses at #5760, but yes, this issue still can be happened and should be fixed anyway.

Also, logs for deleted User or Account entity have similar issue (without errors):

![image](https://user-images.githubusercontent.com/705555/37903437-e5e425a4-3132-11e8-8eaa-4e75f500e77e.png)

Displaying only ids seems easy (though it needs new strings to localize), although I'm not sure how those id only logs are useful...

**Comment by ThisIsMissEm** [comment] 2018-05-09 07:59
Wouldn't it be better to store the serialized toot as part of the log? (same with reports)

**Comment by nightpool** [comment] 2018-06-04 15:27
This is still happening in 2.4

**Comment by nightpool** [comment] 2018-06-04 15:29
```ruby
method=GET path=/admin/action_logs format=html controller=Admin::ActionLogsController action=index status=500 error='ActionView::Template::Error: No route matche
s {:account_username=>nil, :action=>"show", :controller=>"statuses", :id=>#<Status id: nil, uri: nil, text: "", created_at: nil, updated_at: nil, in_reply_to_id: nil, reblog_of_id: nil, url: nil, sensitive: true, visibility: "public", 
spoiler_text: "", reply: false, favourites_count: 0, reblogs_count: 0, language: nil, conversation_id: nil, local: false, account_id: nil, application_id: nil, in_reply_to_account_id: nil>}, possible unmatched constraints: [:account_username, :id]' duration=222.02 view=0.00 db=63.29

ActionView::Template::Error (No route matches {:account_username=>nil, :action=>"show", :controller=>"statuses", :id=>#<Status id: nil, uri: nil, text: "", created_at: nil, updated_at: nil, in_reply_to_id: nil, reblog_of_id: nil, url: nil, sensitive: true, visibility: "public", spoiler_text: "", reply: false, favourites_count: 0, reblogs_count: 0, language: nil, conversation_id: nil, local: false, account_id: nil, application_id: nil, in_reply_to_account_id: nil>}, possible unmatched constraints: [:account_username, :id]):
    4:       = image_tag action_log.account.avatar.url(:original), alt: '', width: 40, height: 40, class: 'avatar'
    5:     .log-entry__content
    6:       .log-entry__title
    7:         = t("admin.action_logs.actions.#{action_log.action}_#{action_log.target_type.underscore}", name: content_tag(:span, action_log.account.username, c
lass: 'username'), target: content_tag(:span, log_target(action_log), class: 'target')).html_safe
    8:       .log-entry__timestamp
    9:         %time= l action_log.created_at
   10:     .spacer

app/lib/tag_manager.rb:44:in `url_for'
app/helpers/admin/action_logs_helper.rb:37:in `log_target_from_history'
app/helpers/admin/action_logs_helper.rb:8:in `log_target'
app/views/admin/action_logs/_action_log.html.haml:7:in `_app_views_admin_action_logs__action_log_html_haml__2842370514651194222_70176050281280'
app/views/admin/action_logs/index.html.haml:4:in `_app_views_admin_action_logs_index_html_haml__2345906915116898820_70176051173180'
```

**Comment by trwnh** [comment] 2023-05-14 00:17
is it still happening in 4.x?

**Comment by ThisIsMissEm** [comment] 2023-09-27 01:01
I think this is now fixed for Statuses, and for Accounts that are deleted, it now just says "Deleted Account" instead of the username / handle.

**Closed** 2024-01-01 22:26 UTC
Labels: bug
