### ISSUE TITLE
Add 'en-us.yml' locale

### ISSUE THREAD

**Issue by wbnns** [mastodon/mastodon#22186] opened 2022-12-09 16:37 UTC
### Pitch

Currently 'en.yml' includes both words from British English as well as American English. There is already an `en-GB.yml` so just wanted to do a temperature check on if it would be a welcome PR to add `en-US.yml` for American English speakers?

This would ensure that Mastodon users in the United States, for example, see the spellings they are familiar with.

Examples:

+ s/favourite/favorite/
+ s/cancelled/canceled/

If so I will make the PR.

Thanks!

### Motivation

Further localize Mastodon UI for its users based on the form of language they are used to seeing

**Comment by ineffyble** [comment] 2022-12-10 01:06
This would need to be done via [CrowdIn](https://crowdin.com/project/mastodon) I believe.

**Comment by ineffyble** [comment] 2022-12-10 15:23
Duplicate of #8163

**Closed by ineffyble** 2022-12-10 15:23 UTC
Labels: suggestion
