### ISSUE TITLE
[Feature Request] Per-Timeline Sensitive Media Display Control

### ISSUE THREAD

**Issue by CDR-Aurora** [mastodon/mastodon#9598] opened 2018-12-21 06:46 UTC
### Pitch

It would be super cool if there was per timeline control for Hiding Media. Like it would be awesome to set only the Local and Federated timelines to hide all sensitive media, but have the Home timeline show all media.

### Motivation

This would be very useful for either SFW or NSFW users of mastodon, as it would allow safe filtering of unknown or unwanted content on Local or Federated timelines, and allow users to see the content of whom they follow.

This was also [suggested previously](https://github.com/tootsuite/mastodon/issues/6970), but due to the influx of users, I think it's the right time to implement.

**Comment by Humblr** [comment] 2018-12-22 20:49
+1 for this. 

We are desperate for this as many of our users have to click on each post as they are fine with all content posted to our instance.

**Comment by trwnh** [comment] 2023-05-14 08:04
duplicate of #6970

**Closed by trwnh** 2023-05-14 08:04 UTC
Labels: suggestion
