### ISSUE TITLE
"opt-out of search engine indexing" does not prevent reply toots from being indexed

### ISSUE THREAD

**Issue by brad2014** [mastodon/mastodon#22874] opened 2022-12-31 09:19 UTC
### Steps to reproduce the problem

1.  opt-out of search engine indexing
2.  on mastodon, reply to someone who has not opted out 
3.  notice that the content of the reply appears in the google search index (e.g. site:infosec.exchange "myname")
...

### Expected behaviour

The content of my toot should not appear on google.

### Actual behaviour

The content of my toot appears on google.

### Detailed description

If a user has *not* opted out of search engine indexing, robots are permitted to index their content.

One of those pieces of content is the context, which contains toot content of users who *have* opted out.

For example, this URL belongs to a user who has not opted out:

https://infosec.exchange/@tychotithonus/109521031783780939

But in rendering this page, an API call is made that returns content of users who have opted out:

https://infosec.exchange/api/v1/statuses/109521031783780939/context

Idea/Suggestion:  Apply the `x-robots-tag: nofollow, noarchive` header to the context response.  This will indicate to search engines that the content embedded in the JSON will not be indexed.  The replies can still be indexed under their main link if the replier does not opt out.  But for repliers who do opt out, their replies won't be swept into the google index inadvertently because they reply to a user who has enabled indexing.

### Specifications

Mastodon 4.0.2+glitch

**Comment by ineffyble** [comment] 2022-12-31 15:08
Duplicate of #22047

I don't believed your suggested fix would work, as Google is not directly archiving the JSON, rather it is indexing the HTML after the frontend JS has run and rendered the page. 

I do want to make a PR that adds X-Robots-Tag headers everywhere but I don't think it solves this problem.

**Closed by ineffyble** 2022-12-31 15:08 UTC
Labels: bug

**Comment by skopf** [comment] 2023-01-18 20:06
I would strongly suggest to completely remove this option as it gives a false sense of privacy.

Toots and profile information are not just displayed on the users profile page. If a post contains a tag, the post will also appear on the tag page. If a user has at least one follower on a remote instance, the toots will be federated there and be displayed on the federated timeline of the remote instance, from which Google will pick it up. Toots can also be boosted, or replied to, or...
Toots are simply displayed on too many pages to be able to hold up with the promise that they do not end up in Google.

I described this specific problem together with other privacy concerns here:
https://medium.com/@s.kopf/mastodon-is-a-zero-privacy-network-here-is-what-you-need-to-know-86aeed685e41
