### ISSUE TITLE
I see all this user's posts in my timeline yet I do not follow this user. No way to tell why a post is in timeline.

### ISSUE THREAD

**Issue by nf3xn** [mastodon/mastodon#23595] opened 2023-02-14 13:21 UTC
### Steps to reproduce the problem

1. Open mastodon web client for me
2. LO FOR IT IS HE
3.
...

![image](https://user-images.githubusercontent.com/88434068/218748666-214288f0-7893-414c-861d-aaaa27774099.png)

![image](https://user-images.githubusercontent.com/88434068/218751136-4ca4a90d-2c90-4727-a04e-952f839c7a1e.png)

### Expected behaviour

I don't see posts from users and hashtags I do not follow 

### Actual behaviour

I see posts from one particular user I do not follow 

### Detailed description

I see all this user's posts in my timeline yet I do not follow this user. 

There is no way I can tell why this is in my timeline. 

It cannot be a hashtag because some of the posts do not have a hashtag at all. There is no way I can check hashtags I am following. I think I only follow the #Ukraine hashtag which would make sense if this user ever had this hashtag in their posts which they do not. 

I have tried following and unfollowing the user to no avail.
How do I determine the provenance of a post so that I can eliminate the source? 

### Specifications

It has been in the last few versions of Mastodon client AFAICT. There is a content script installed on the page also.

**Comment by nf3xn** [comment] 2023-02-15 22:12
Hidden hashtags. Yikes. And as there is no way to tell which hashtags you follow in the client, from your data archive extract or even curl it from the api, so you cannot even disable them one by one to see which one is causing the posts to appear.

**Comment by jmorahan** [comment] 2023-02-16 16:59
Not an ideal solution but you can indeed curl it from the API:
https://docs.joinmastodon.org/methods/followed_tags/

**Comment by trwnh** [comment] 2023-05-19 06:14
Duplicate of #23149 . also tagging #19895 as related

**Closed by trwnh** 2023-05-19 06:14 UTC
Labels: bug

**Comment by andoks** [comment] 2023-07-28 20:01
Thanks @jmorahan!

For anyone that just wants to get a quick list, you can run the following in the browser developer console by adding the bearer-token from a previous request (which you can find in the developer console - F12 - under the network tab): `fetch("/api/v1/followed_tags", {headers: {Authorization: "Bearer <fill out bearer token from a request in the developer console>"}}).then((response) => {return response.json()}).then((json) => {console.table(json)}) `
