### ISSUE TITLE
domain blocks admin api

### ISSUE THREAD

**Issue by compufox** [mastodon/mastodon#15547] opened 2021-01-12 16:45 UTC
### Pitch

manage the status of blocks/create new blocks for domains, instance wide, via the admin api.

### Motivation

this feature is important because it reflects a lack of exposed API endpoints for admins/moderators. it would also be very useful because then admins/mods wouldnt need to open the web interface to manage blocks.

**Comment by just1602** [comment] 2021-02-02 02:25
Yeah, this would be super usefull. With an api we could at least write script to block instance using a list or something like that instead of manually entering it by hand one by one. This api would be really appreciate !

**Comment by Semisol** [comment] 2021-11-06 08:25
I'm replying to this post as it has been months since the last activity. It would be very useful for this kind of API to exist, as it would allow for scripts for administrators to subscribe to fediblock lists and automated actions against instances.

**Comment by dorianim** [comment] 2022-06-02 11:12
I would also like to have an api for this. As the admin of a small instance, it's hard to keep track of bad domains and block them. So I'd like to automate that process. Right now, that is kind of difficult...

**Comment by dorianim** [comment] 2022-06-03 04:58
Yea, thanks, that's what I needed :)
There is no documentation though.

**Comment by trwnh** [comment] 2022-06-03 06:21
It just got added 2 days ago and isn't part of a versioned release yet, so it will be added to the documentation around Mastodon 3.6 probably

**Comment by dorianim** [comment] 2022-06-03 07:22
Ahh, ok. Very nice :+1:

**Comment by dorianim** [comment] 2022-06-03 07:23
So this can be closed as a duplicate of #18140 I think.

**Closed** 2023-05-20 04:16 UTC
