### ISSUE TITLE
Subscribe to notifications in discussion 

### ISSUE THREAD

**Issue by kefir-** [mastodon/mastodon#25503] opened 2023-06-18 20:46 UTC
### Pitch

I'm not sure mastodon or activitypub would allow for this concept, but here goes:

Sometimes I see a really interesting discussion starting on mastodon. I would like to enable notifications to followups, so that I receive notifications of followups, even though I'm not part of the thread. 

It should be possible to unsubscribe to further followups.

### Motivation

It's great to spot the beginning of an interesting discussion in my timeline, but since there's no algorithms that post probsbly won't be shown to me again, even if it gets a lot of responses from others.

Also, a discussion often takes multiple threads. Being notified of related discussions might help to make the discussion more fruitful. 

Comparing this idea to email, it should be similar to subscribing to a Message-ID, and being notified every time a new message appears with this ID in it's References: list.

Facebook also has a feature like this, where it is commonly used to receive notifications when seeing a question you also want the answer to.

**Comment by kefir-** [comment] 2023-06-18 21:37
If I'm reading this right,  it looks like activitypub's InReplyTo would allow for the server side logic to resolve the chain of posts back to the thread start, and send notifications to anyone followup-subscribed as mentioned to one or more posts in that chain. 

https://www.w3.org/TR/activitystreams-vocabulary/#dfn-inreplyto

**Comment by scotthmurray** [comment] 2023-07-09 20:45
+1 to this suggestion. 😁

Duplicates, overlaps with, or otherwise related to: #23702 #10865 #8153

**Comment by trwnh** [comment] 2023-07-09 22:37
Duplicate of #7969 and/or #23702 yeah

**Closed by trwnh** 2023-07-09 22:37 UTC
Labels: suggestion
