### ISSUE TITLE
Media from Misskey not always correctly displayed

### ISSUE THREAD

**Issue by fenarinarsa** [mastodon/mastodon#24649] opened 2023-04-25 11:23 UTC
### Steps to reproduce the problem

1. Follow a Misskey account
2. Some media posted on Misskey don't show properly in Mastodon's TL

### Expected behaviour

The media should be displayed in Mastodon

### Actual behaviour

The media doesn't display

### Detailed description

I noticed what seems to be a compatibility issue between Misskey and Mastodon over the Fediverse. Medias posted on Misskey often don't show properly on Mastodon but I can't really understand exactly under what conditions it happens.

I *think* it happens when GIFs are posted on Misskey (animated GIFs are posted as is), but I found out it also happens with webp files.

Here's examples of problematic posts:
https://misskey.design/notes/9dyizqldzl
https://misskey.design/notes/9dyivaq2f9

My Mastodon instance is shelter.moe and I think it has a low cache retention because of storage issue but otherwise a pretty standard Mastodon setup.

![image](https://user-images.githubusercontent.com/17545417/234261238-efd970fb-75b7-44f2-9476-d6879f739410.png)

### Specifications

Mastodon 4.1.2
Firefox 112.0 64 bits
Windows 11

**Comment by vmstan** [comment] 2024-05-21 15:36
Duplicate of #18687

**Closed by vmstan** 2024-05-21 15:36 UTC
Labels: bug, area/media processing
