### ISSUE TITLE
"Add tags" button for web and mobile

### ISSUE THREAD

**Issue by aquariusdev** [mastodon/mastodon#28535] opened 2023-12-31 02:00 UTC
### Pitch

An "add tags" ("#") button in the bottom of the compose window, which would allow for multiple followed tags to be selected from a dropdown and added to the end of a post. Could also allow for pinned tag groups to be added, which would automatically populate the end of the post with associated tags. 

### Motivation

Given that hashtags are the main means of finding posts from users, this would reduce the friction of adding tags to posts before hitting publish.

Tumblr does this very well: 
![image](https://github.com/mastodon/mastodon/assets/28520002/2db4d148-487f-452e-a337-62ca912676d3)

**Comment by trwnh** [comment] 2023-12-31 02:46
Duplicate of #10743

**Closed by trwnh** 2023-12-31 02:46 UTC
Labels: suggestion

**Comment by trwnh** [comment] 2024-11-29 16:46
Reopening as no longer duplicate
