### ISSUE TITLE
Discovery attack on login form

### ISSUE THREAD

**Issue by Berbe** [mastodon/mastodon#9374] opened 2018-11-27 14:55 UTC
### Expected behaviour

When attempting to login, the use of bad credentials should provide a single and consistent error message saying credentials are invalid, without finer granularity.

### Actual behaviour

When using an incorrect email address, the login form actually states the email is wrong, instead of the credentials pair.
That means email enumeration of registered users is possible ans consists itself in a form of discovery attack.

### Steps to reproduce the problem

1. Reach the login form of any mastodon instance
2. Try to login with non-registered email address

### Specifications

The instance that behavior has been noticed on was v2.6.1

**Comment by Gargron** [comment] 2018-11-27 15:10
Which language? English or another? The messages should be identical

**Comment by m4sk1n** [comment] 2018-11-27 15:24
<details>
<summary>probably French</summary>
 ![screenshot_20181127-162117](https://user-images.githubusercontent.com/21127288/49091649-95def800-f260-11e8-8ff8-c8338418630e.png)
![screenshot_20181127-162124](https://user-images.githubusercontent.com/21127288/49091656-9a0b1580-f260-11e8-955a-a8f6ca1b4cbe.png)
</details>

**Comment by Berbe** [comment] 2018-11-27 17:07
Wow that is unexpected: how are translations able to tell one case (non-existent email) from the other (invalid credentials)?
Sounds like a design flaw.

Thanks for helping spot the problem anyway!

**Comment by nightpool** [comment] 2018-11-27 17:31
ehhhhh either we should say that this is an issue and fix it in the code, not the translations, or we should just ignore it. I find discovery attacks to be pretty overblown.

**Comment by Berbe** [comment] 2018-11-27 18:08
I'll skip the personal opinion which, while dangerous, iss ill-placed in a bug report.

It is definitely a code bug to differentiate thoses error cases in any way, thus allowing to handle them differently in the translation engine. Would you be able to help spot where the problem comes from in the source code?
However, as a quick fix, I'd suggest to set the translated error message strictly identical in both cases for now.

**Comment by nightpool** [comment] 2018-11-27 23:53
@Berbe ...... having an opinion is dangerous? having an opinion on the priority/validity of a bug report is ill-placed? that's the entire point of triage.

**Comment by Berbe** [comment] 2018-11-29 13:40
@nightpool Stop claiming your words for my own; Quibbling stops here & now.

@Gargron If I understand well, does that mean no Mastodon instance would be able to differentiate the error cases, ever?

**Comment by Gargron** [comment] 2018-11-29 15:01
I am still confused because @m4sk1n you were able to reproduce the issue, despite `Devise.paranoid` being set to `true`?

**Comment by Berbe** [comment] 2018-11-29 18:41
I noticed that behavior on https://mastodon.xyz/

**Comment by m4sk1n** [comment] 2018-11-29 18:47
I noticed it on glitch.social (not dev. one)

**Comment by Gargron** [comment] 2018-11-29 21:30
I have identified the issue. The devise-two-factor gem ignores the paranoid setting in its two_factor_authentication strategy and always throws "not_found_in_database". However, if the user record does exist, execution moves to the standard devise_authenticatable strategy, which correctly always throws "invalid" when paranoid mode is activated.

This would have been a larger issue if the keys weren't identical in almost all translations.

**Comment by Gargron** [comment] 2018-11-29 21:47
Submitted fix: tinfoil/devise-two-factor#138

**Comment by Berbe** [comment] 2018-11-30 00:31
Great catch!

Thanks a lot, crossing my fingers for upstream correction and integration of their new version into mastodon ASAP.

**Comment by trwnh** [comment] 2023-05-14 23:03
fixed in upstream pr, i assume. if this is still happening then please comment here so it can be reopened

**Closed by trwnh** 2023-05-14 23:03 UTC
Labels: partially a bug
