### ISSUE TITLE
IPv6 node.js

### ISSUE THREAD

**Issue by RJGhugo** [mastodon/mastodon#31199] opened 2024-07-29 20:02 UTC
### Steps to reproduce the problem

- Use **BIND: "[::]"** on a **IPv6 only** system
- Start tootsuite/mastodon on k3s
- **"node ./streaming"** throw REDIS error (seems to try to connect via IPv4)
- "bundle exec sidekiq c 25" and "bundle exec puma -C config/puma.rb" work well

### Expected behaviour

Bind IPv6

### Actual behaviour

REDIS Error

### Mastodon version

4.2.10

**Comment by RJGhugo** [comment] 2024-07-30 15:54
`args:`
`  - node`
`  - ./streaming`

Logs:

`ERR! Redis Client Error! Error: getaddrinfo ENOTFOUND mastodon-redis`
`ERR! Redis Client Error!     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)`
`ERR! Redis Client Error!  Error: getaddrinfo ENOTFOUND mastodon-redis`
`ERR! Redis Client Error!     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {`
`ERR! Redis Client Error!   errno: -3007,`
`ERR! Redis Client Error!   code: 'ENOTFOUND',`
`ERR! Redis Client Error!   syscall: 'getaddrinfo',`
`ERR! Redis Client Error!   hostname: 'mastodon-redis'`
`ERR! Redis Client Error! }`
`ERR! Error: getaddrinfo ENOTFOUND [::] `

**Comment by RJGhugo** [comment] 2024-07-30 15:58
`args:`
`  - bundle`
`  - exec`
`  - puma`
`  - -C`
`  - config/puma.rb`

Logs:

`[7] Puma starting in cluster mode...`
`[7] * Puma version: 6.4.2 (ruby 3.2.3-p157) ("The Eagle of Durango")`
`[7] *  Min threads: 5`
`[7] *  Max threads: 5`
`[7] *  Environment: production`
`[7] *   Master PID: 7`
`[7] *      Workers: 2`
`[7] *     Restarts: (✔) hot (✖) phased`
`[7] * Preloading application`
`[7] * Listening on http://[::]:3000`
`[7] Use Ctrl-C to stop`
`[7] - Worker 0 (PID: 10) booted in 0.0s, phase: 0`
`[7] - Worker 1 (PID: 18) booted in 0.0s, phase: 0`

**Comment by ThisIsMissEm** [comment] 2024-07-31 16:58
This is kind of a bug in ioredis, which doesn't automatically support ipv6. This is a duplicate of https://github.com/mastodon/mastodon/issues/27043

**Closed** 2024-07-31 16:59 UTC
Labels: bug, status/to triage

**Comment by RJGhugo** [comment] 2024-08-06 19:33
Played around with ghcr.io/mastodon/mastodon-streaming:edge on a **IPv6 only** system.

Got this error:

`{"level":"error","time":1722971417168,"pid":1,"hostname":"mastodon-stream-0","name":"streaming","err":{"type":"Error","message":"getaddrinfo ENOTFOUND [::]","stack":"Error: getaddrinfo ENOTFOUND [::]\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)","errno":-3008,"code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"[::]"},"msg":"getaddrinfo ENOTFOUND [::]"}`

Does it has to do with this bug?

**Comment by vmstan** [comment] 2024-08-06 19:40
Can you confirm your Docker container has a IPv6 address?
