### ISSUE TITLE
Display unread post counters over the icons of closed tabs

### ISSUE THREAD

**Issue by MirceaKitsune** [mastodon/mastodon#9786] opened 2019-01-11 15:48 UTC
A major missing feature is the lack of counters for tabs containing unread posts, indicating the number of new posts since you've last looked at that tab. This should exist for at least Notifications and Direct Messages, though it would not make much sense for Local Timeline or Federated Timeline where the number would jump to +99 in a matter of seconds.

This is important as some of us don't keep the Notifications tab pinned, which is a rather strange default that Mastodon still uses; It's distracting and often useless as many of us get notifications very rarely. I like having it closed and only opening it when there's something new. But since no counter appears over its icon to indicate new activity, we have to randomly open it and guess.

Here is a mockup of how this could look like for the upper-left bar:

![screenshot_20190111_173224](https://user-images.githubusercontent.com/825418/51043629-d227a700-15c7-11e9-8e37-01c94de1bbcb.png)

**Comment by trwnh** [comment] 2019-01-12 16:43
Duplicate of #8285

**Comment by MirceaKitsune** [comment] 2021-01-08 14:48
It appears the latest Mastodon finally added a proper unread counter to the notifications timeline, at least in the simple interface: You no longer see a blue circle and a number only if the notification popped up while you had a window open, but also if the new notification came while Mastodon was closed and you return to it. Can others confirm this can and should be closed?

**Closed** 2023-05-20 03:06 UTC
Labels: suggestion
