### ISSUE TITLE
mastodon.social not delivering push notifications

### ISSUE THREAD

**Issue by nikclayton** [mastodon/mastodon#31483] opened 2024-08-18 12:43 UTC
### Steps to reproduce the problem

See detailed description

### Expected behaviour

See detailed description

### Actual behaviour

See detailed description

### Detailed description

I'm debugging notification delivery. In what follows, $TOKEN is a valid bearer token, $ENDPOINT is the registered push endpoint.

## Push notification subscription

I have an account A1 at mastodon.social, with a push notification subscription. I have verified this with:

```
curl https://mastodon.social/api/v1/push/subscription -H "Authorization: Bearer $TOKEN"
```

which returns the following JSON (reformatted for legibility, server_key redacted, and the URL replaced with $ENDPOINT):

```json
{
  "id":21555581,
  "endpoint":"$ENDPOINT",
  "alerts":{ 
    "mention":true,
    "status":true,
    "reblog":true,
    "follow":true,
    "follow_request":true,
    "favourite":true,
    "poll":true,
    "update":true,
    "severed_relationships":true,
    "admin.sign_up":true,
    "admin.report":true},
    "server_key":"<REDACTED>",
    "policy":"all"
}
```

As you can see, I should be getting push notifications for everything. **In particular, mentions**, to $ENDPOINT.

## Verifying endpoint works

The endpoint is from ntfy.sh, in a second shell (S2) I run:

```
curl -s ${ENDPOINT}/json
```

This subscribes to the stream of notifications, and prints them as they come in.

Back in shell 1 (S1) I send a test notification:

```
curl -d "Test notification" $ENDPOINT
```

This appears in the notification stream in S2 almost immediately. So I am confident that ntfy.sh is receiving messages and delivering them to subscribers with no problems.

## Sending a message from the web UI.

I open two browser windows in Firefox containers so they're separate.

Window 1 (W1) is logged in to mastodon.social from account A1.
Window 2 (W2) is logged in to mastodon.social from account A2.

From W2 / A2 I send the following message, with visibility set to "Private":

```
@A1 Notification test
```

Over in W1 / A1 the notification appears almost immediately. 

However, over in shell S2 the notification does not appear in the stream.

As far as I can tell, mastodon.social did not send the notification for account A1 to the push notification endpoint ($ENDPOINT) registered with that account.

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-08-12

**Comment by nikclayton** [comment] 2024-08-18 12:50
Pretty certain this is a mastodon.social problem.

If I repeat the above, but change account A1 to an account at me.dm, running v4.2.10, and send a private message from account A2 (still on mastodon.social) then me.dm sends the notification to the ntfy.sh $ENDPOINT almost immediately.

**Comment by ThisIsMissEm** [comment] 2024-08-18 13:05
I think this is likely a duplicate of https://github.com/mastodon/mastodon/issues/31467

**Comment by nikclayton** [comment] 2024-08-18 13:15
I'm not sure it is. The discussion in #31467 is about mention notifications. While the example I give above is a mention, the problem I'm seeing also affects other types of notifications.

For example, from the me.dm account (lets call that A3) I followed account A1.

The follow notification appeared immediately in the A1 web interface, but it is not in A1's stream of push notifications, despite being in the push subscription.

Ditto if A3 favourites a post written by A1.

**Comment by ClearlyClaire** [comment] 2024-08-18 13:45
https://github.com/mastodon/mastodon/issues/31467 is a backport error in 4.2.11 only, which only affects mentions from local accounts with elevated privileges. This is unrelated.

**Comment by nikclayton** [comment] 2024-08-19 15:59
Are you able to confirm this on mastodon.social?

Obviously, the only debugging I can do is point out the lack of traffic from ntfy.sh. Checking outbound network traffic from mastodon.social would be necessary to confirm.

**Comment by ClearlyClaire** [comment] 2024-08-19 16:07
Push notifications from mastodon.social work well at least with Firefox's built-in service. I have not tried ntfy.sh.

Looking at mastodon.social's logs, it seems ntfy.sh may be dropping requests from mastodon.social
```
HTTP::TimeoutError: Connect timed out after 5 seconds on https://ntfy.sh/<redacted>
```

**Comment by nikclayton** [comment] 2024-08-19 17:36
Thanks. I'm following up with the ntfy.sh folks to see what they see on their end.

**Comment by ThisIsMissEm** [comment] 2024-08-19 17:58
Could this be that "mastodon doesn't respect nfty.sh's rate limit" bug? Where they respond with a 429 and we don't handle that?

(Or am I misremembering that situation?)

**Comment by nikclayton** [comment] 2024-08-20 12:28
https://github.com/mastodon/mastodon/issues/26078 -- damn.

**Comment by vmstan** [comment] 2024-08-20 17:13
Closing as duplicate.

**Closed by vmstan** 2024-08-20 17:13 UTC
Labels: bug, status/to triage
