### ISSUE TITLE
Resizeable columns in the advanced layout

### ISSUE THREAD

**Issue by stibinator** [mastodon/mastodon#25349] opened 2023-06-09 03:07 UTC
### Pitch

I wrote a userscript that adds resizeability to the columns in the advanced interface. 
The userscript is here https://greasyfork.org/en/scripts/454111-resize-o-don
It basically adds this to the CSS:
```
 .columns-area .column {
        resize: horizontal;
        max-width: 100% !important;
        flexShrink: 0;
}
.column:last-child {
        resize: horizontal !important;
        flex: 1 1 auto !important;
}
.drawer{
        resize: horizontal !important;
}
```

https://github.com/mastodon/mastodon/assets/422938/cd8acaec-42f9-422c-996d-d5fccf7b8629

### Motivation

- It gives the user flexibility to arrange the columns to their preference, and the content. 
- It prevents the wasted space where the columns don't fill the width of the page, which happens with the default web layout.
- It's a simple change that could easily be an optional feature. 
- It works really well in use, I've got the userscript installed on all my desktop browsers, and wouldn't use Mastodon without it.
- Note that the screen recording is also demonstrating another userscript that puts the contents of the drawer at the top of the first content column, to save horizontal space. I'll add another FR for that too.

**Comment by JorgeStolfi** [comment] 2023-08-07 22:18
Also automatic recalculation of column widths, preserving their ratios, when one column is made visible or invisible.

**Comment by trwnh** [comment] 2023-12-30 08:44
Duplicate of #8632

**Closed by trwnh** 2023-12-30 08:44 UTC
Labels: suggestion, area/web interface

**Comment by Seattlerider** [comment] 2026-05-08 15:50
9 years 4 months after the first request to let users meaningfully customize column widths (because not everyone has the same size screen), and requests are still being closed (even when they present possibilities for other instances to try).

Though on the bright side, at least they're no longer being closed as "completed". That's a plus.

**Comment by navara** [comment] 2026-05-08 15:54
They don't even add a reason, like "we want to push there ads someday", they just close it… it makes no sense.

**Comment by trwnh** [comment] 2026-05-08 18:27
#8632 is still open, though?

**Comment by Seattlerider** [comment] 2026-05-09 03:10
> [#8632](https://github.com/mastodon/mastodon/issues/8632) is still open, though?

You closed someone offering a solution, on the basis that someone had asked the question before. (0_o)

That's not particularly logical, unless the goal is "make as many mentions of this issue as possible go away".

**Comment by trwnh** [comment] 2026-05-09 03:19
The goal is to consolidate discussion so it can be tracked more easily. If an issue is already filed, then filing duplicates only creates noise, not signal. If there is a substantive contribution to the discussion, then people can comment on the already-open issue that this is a duplicate of; otherwise, they can add a thumbs-up reaction if they support the issue, and maybe subscribe to the issue if they want to receive updates about it. Is that illogical?

**Comment by Seattlerider** [comment] 2026-05-09 03:25
Did you add the comment to the discussion? No.
Did you add your own comment, pointing to "Hey guys, here's a solution someone posted"? No.
The goal doesn't appear to be to "consolidate discussion".
It appears to be "Make discussion go away".

**Comment by trwnh** [comment] 2026-05-09 03:37
I'm not responsible for commenting on behalf of other people, so they can comment on the main issue if they want. Either way, GitHub inserts a timeline item linking the issues together, as should be visible from 2.5 years ago.

I don't think filing duplicate issues helps with discussion. By definition, duplicate issues divide attention and discussion, so leaving this issue open and ignoring it entirely would have "made discussion go away". If there's too much noise, then the Mastodon team is incentivized to completely ignore the issue tracker because they can't find anything. With 4.2k issues open, many of them likely being duplicates or stale, it's that much harder to find the deduplicated/active issues if people keep filing issues that are already tracked. Of course, people can search for existing issues and still overlook some, which is where "mark as duplicate" helps reduce noise. 

(It seems to confuse some people because GitHub used to treat all such issues as "closed", then later made old duplicate issues "closed as completed" while newer duplicate issues are presented as "closed as not planned", but that's a limitation on GitHub's end -- they don't let issues be closed with a more specific disposition. "Stale" and "duplicate" get lumped under "not planned", and used to be lumped under "completed".)

**Comment by Seattlerider** [comment] 2026-05-12 04:39
Okay, tooter.
