### ISSUE TITLE
Rich retooting ability [feature request]

### ISSUE THREAD

**Issue by tykayn** [mastodon/mastodon#14460] opened 2020-07-28 10:39 UTC
### Pitch
Adding ability to retoot something with adding a CW to it. Quoting a toot and mentionning its link to origin would also do the trick. But a nice presentation would be the best.

### Motivation
When i want to share something that is not properly tagged or marked as sensitive, or i know that my followers would prefer a CW for this, i wish i could add this. My only option by now is not sharing, or downloading media, and reuploading it with the proper markers.

**Comment by Nebby** [comment] 2020-08-12 10:58
The absence of this has pretty much ended Mastodon for me. I can't consistently CW for my followers unless I just don't boost most of the stuff I want to boost.

Different feeds/communities have differing needs and expectations for CWs, so it makes sense that CWs can be added/adapted as boosts propagate. CWs are a huge part of the appeal of Mastodon, but in practice they are broken without this feature imho.

**Comment by realpixelcode** [comment] 2021-01-09 00:49
I'd like to have this feature too, just like the "boost with comment option" #14597 because all this stuff may promote discussions etc. which might get lost else.

**Comment by ShredderWalnut** [comment] 2022-03-11 16:05
I find this feature essential, too. There are many distressing topics that I pay close attention to, but I frequently see non-CW'd toots that I decide not to boost solely because I regard it as CW-worthy.

I believe this feature is beneficial to the Mastodon communities.

**Comment by yuki-93** [comment] 2022-11-05 20:01
Is there an update on this? I really would recommend to have this feature.

**Comment by smidgedy** [comment] 2022-11-21 09:06
I would also love to see this feature - it's not as easily abused as a retoot feature would be as the content would be hidden by default for most users, and it seems like a net positive. 

Additionally, another user on my instance who doesn't have github [is asking for it too](https://aus.social/@didgeridoo/109380896931675107)

**Comment by vmstan** [comment] 2023-11-17 19:24
Duplicate of #13291

**Closed by vmstan** 2023-11-17 19:24 UTC
