### ISSUE TITLE
Add the ability to switch between multiple accounts in the same instance

### ISSUE THREAD

**Issue by trufae** [mastodon/mastodon#31809] opened 2024-09-08 09:04 UTC
### Pitch

I searched in the list of issues/feature requests but I couldn't find any ticket related to this. Other social networks and most native clients support this feature, so I think it will be useful for many users here too.

### Motivation

When using more than one account it's handy to be able to switch between them from the web interface, most 3rd party clients support that feature but it's something I miss when using Mastodon from the web.

**Comment by madeindex** [comment] 2024-09-08 10:00
This is a nice suggestion. However, I think it might take some time as there are currently **[1309 open bugs](
https://github.com/mastodon/mastodon/labels/bug)** which might have priority over usability (for a minority of users with multiple accounts) like this :)

**Comment by llrs** [comment] 2024-10-14 21:05
What would need to happen to make this a reality? Is something that if there is a PR would be considered or not because there are more bugs than users of this feature?

I've seen plenty of people literally having a profesional and a hobby account or a bot/company/organization and user account. Is there some numbers on the number of accounts that users manage/use?

**Comment by mjankowski** [comment] 2024-11-26 23:27
Similar to https://github.com/mastodon/mastodon/issues/380

**Comment by trwnh** [comment] 2024-11-26 23:50
Duplicate of #380 actually

**Closed by trwnh** 2024-11-26 23:50 UTC
