### ISSUE TITLE
Redirect users directly to (web)application

### ISSUE THREAD

**Issue by Doomsdayrs** [mastodon/mastodon#20296] opened 2022-11-10 05:36 UTC
### Pitch

Email services provide this, in which there is a protocol for the following [link](mailto:doomsdayrs@shosetsu.app) to open in an email client.

Thus, the proposal of something similar for Mastodon links. Such as `mastodon://`` and a data payload. 

Furthermore, whenever any content is opened on a browser (and the user is not logged in) the page will attempt to redirect to said mastodon link protocol so the user can return to their original instance with it.

On mobile, this can be used to automatically open any Mastodon client as well.

### Motivation

Users getting lost over numerous instances requiring logins on each.

For example, #19652

**Comment by ineffyble** [comment] 2022-11-10 07:08
Interesting... I was going to say that this would only work on desktops with some type of app (or possibly browser extension) installed, but apparently there are web APIs for this now: https://web.dev/url-protocol-handler/

They even handle multiple sites registering for the same URL scheme, prompting the user to select which one.

So it would be possible to have the Mastodon web app register itself as a handler for `mastodon:` for a logged in user, and if you have accounts on multiple instances, each one would register and be selectable.

**Comment by veale** [comment] 2022-11-12 13:56
I think this is an absolutely key feature, it has confused a huge amount of people, and average users do not and should not need to understand the same-origin policy when asking "why can't I boost this!". What would graceful degradation look like in this situation? If a user clicks "boost" or "follow" on an instance they are not logged into, is it possible for the link to act differently depending on whether or not the user has a Mastodon handler installed or not? (I would think that if it could, that could be a web fingerprinting problem).

**Comment by raikasdev** [comment] 2022-11-17 14:49
Hello! I also developed [an extension](https://github.com/raikasdev/mastodon4-redirect) for this purpose, and would like to give my opinions about this.
Using mastodon: protocol would be possible, as Mastodon4 uses PWAs (not sure about Mastodon3)
At least Discord somehow detects if a protocol is available (so if you open a link, it then opens the Discord app if it is installed, if not it just opens in browser without any "choose" window), so using a similar approach would be very nice in my opinion, so it would kinda be "invisible" to user.

**Comment by nightpool** [comment] 2022-11-17 15:39
This was implemented and then removed in #8127 due to bad browser UX and user confusion, unfortunately. Future work in this area may be possible by combining it with PWAs, which now can [automatically register protocol handlers](https://developer.chrome.com/articles/url-protocol-handler/) with less user confusion. 

Regardless, this issue is a duplicate of #19679

**Closed by nightpool** 2022-11-17 15:39 UTC
Labels: suggestion
