### ISSUE TITLE
Bugs in hashtag column configuration

### ISSUE THREAD

**Issue by steelman** [mastodon/mastodon#21362] opened 2022-11-21 22:28 UTC
### Steps to reproduce the problem

1. Create a column for viewing a hashtag (works fine)
2. Open column settings
3. Type a hashtag in any of the three fields availabl

### Expected behaviour

Exact match should appear first on the list.

### Actual behaviour

Exact match does not apper on the list.

### Detailed description

When I type `#introduction` a number of suggestions appear including: `#introductionsok`, `#introductionsim`, `#introductionwhite` and several others but no `#intruduction`. Apparently it is required to use a tag from the list and it is impossible to use the one typed in the input box.

BTW. The dropdown list for the lower two doesn't fit into space between the intput boxes and the column content

### Specifications

Mastodon 4.0

**Comment by ClearlyClaire** [comment] 2022-11-22 12:53
Duplicate of #21188, related to #17494

**Closed by ClearlyClaire** 2022-11-22 12:53 UTC
Labels: bug
