### ISSUE TITLE
Search Box for Bookmarks

### ISSUE THREAD

**Issue by louis-vgn** [mastodon/mastodon#30418] opened 2024-05-24 19:26 UTC
### Pitch

A search feature to look through bookmarks. It could take two forms:
1. In the global search box with a `in:bookmark` to only query elements saved in bookmarks
2. A search box in the `bookmark` tab.

### Motivation

I am extensively using the bookmark feature to read things later, but there is no way to classify them (*i.e.*, sometimes I only want to read elements on tech, other times news items, etc.). Even more so, sometimes I vaguely remember a post or thread that I wanted to read, and I know I saved it in my bookmarks, but I struggle to find it because it is buried under all the other ones (and finding it chronologically is really not efficient).

Hence, a search feature on the bookmarks would be really helpful, and would love to see it implemented.

Thanks for the great work!

**Comment by renchap** [comment] 2024-05-25 07:48
Duplicate of #27155

**Closed by renchap** 2024-05-25 07:48 UTC
Labels: suggestion
