### ISSUE TITLE
Grouping of trending hashtags into topics

### ISSUE THREAD

**Issue by GBT7** [mastodon/mastodon#23465] opened 2023-02-08 19:47 UTC
### Pitch

Allow instance staff the ability to group hashtags together in trending and (optionally) in search, so that the usage stats of multiple hashtags gets combined, and they take less space in trending when there's multiple hashtags referring to the same thing.
For example: #SOTU, #SOTU2023, and #StateOfTheUnion can all be under a single grouped topic, as can #FF and FollowFriday, #JoeBiden and #Biden, and so on, at the discretion of the instance staff. If such an interface could suggest hashtag groupings too, such as when it sees certain hashtags used together frequently, that would make it much easier to manage.

### Motivation

When one topic has multiple hashtags, that leaves less room for other hashtags in trending, and in the case of big news stories, such as major events in US politics, it can be annoying to see all of the top hashtags being about the exact same topic, especially when said topic doesn't impact or resonate with the reader (for example: I don't live in the US, so American politics doesn't interest me as much). Twitter already has topic grouping in the trending section, and it does a great job of making sure that one single topic doesn't dominate the entire trending section by use of multiple hashtags.

**Comment by rokejulianlockhart** [comment] 2023-02-15 11:32
https://github.com/mastodon/mastodon/issues/23454

**Comment by shaedrich** [comment] 2024-01-13 00:51
Is your proposal limited to strict aliases (#Biden and #JoeBiden refer to exactly the same in 99% of the cases, I would assume)? If not, there are "closely related" hashtags (for example, #USElections applies to both #USElections2020 and #USElections2024, but the two are not aliases of each other, however, they still have some kind of a relation) (#28675, #28676)

**Comment by trwnh** [comment] 2024-01-13 13:23
Duplicate of #23454

**Closed by trwnh** 2024-01-13 13:23 UTC
Labels: suggestion
