### ISSUE TITLE
Improve toot link behavior in web interface

### ISSUE THREAD

**Issue by renatolond** [mastodon/mastodon#8136] opened 2018-08-07 11:06 UTC
As a user, sometimes I want to link to toots for people to see. These toots are often already loaded in my instance, but even so, clicking the link makes the toot open in a new tab.
I would like that if a toot is already loaded in my instance, clicking the link would open the toot in the details tab.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by jeroenpraat** [comment] 2018-08-07 14:05
What a coincidence. I just wanted to make an issue about this.

I want to add that this is also true for links to other profiles (like @otherprofile) in web-app profiles. The expected behavior is that it opens that other profile in the same web-app column, but it opens a new tab, just like described by Renato. This is true for @-links in the bio text and in the meta data fields.

I can remember that somewhere before the introduction of the meta fields, it loaded the @-links in the same column (not in a new tab). Can't exactly remember if this was also true for toots like Renato describes. Maybe this is intentional or else it is a regression.

**Comment by trwnh** [comment] 2023-05-14 16:09
Duplicate of #1399

**Closed by trwnh** 2023-05-14 16:09 UTC
Labels: suggestion
