### ISSUE TITLE
Proposal: Make "Comment" required on Reports

### ISSUE THREAD

**Issue by ThisIsMissEm** [mastodon/mastodon#7122] opened 2018-04-13 12:54 UTC
Presently it's possible to report without a comment, which results in a high volume of reports that cannot be easily judged. The proposal here is to require the comment to be filled in. We should encourage apps to adopt a "quick reason" type form for reporting (perhaps these can be configured by the instance)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by rodti** [comment] 2020-11-04 20:19
100% this.

**Comment by trwnh** [comment] 2024-03-19 22:57
Duplicate of #2222

**Closed by trwnh** 2024-03-19 22:57 UTC
Labels: breaking, moderation, suggestion
