### ISSUE TITLE
Feature request: Add followed hashtags to lists

### ISSUE THREAD

**Issue by loremipsum2022** [mastodon/mastodon#23877] opened 2023-02-25 13:13 UTC
### Pitch

IT would be great if you could add a hashtag you follow to an existing list. Maybe you could then additionally hide the respective hashtag from the home timeline.

### Motivation

The ability to follow hashtags is an essential feature to quickly find topics and accounts that interest you right after you join. Since there is no algorithm, such a feature is all the more valuable. 

However, the more hashtags you follow, the more confusing your home timeline becomes. 

Lists are already a great tool to keep track of the accounts you follow in a structured way. This helps you not to miss posts from people who are important to you. The ability to add hashtags to lists would add even more value to lists while helping to keep the Home Timeline organized (as long as you could hide a hashtag you add to a list from the Home Timeline at the same time).

**Comment by Cassolotl** [comment] 2023-02-25 15:35
Duplicate of *Ability to add hashtags to lists #7692* (May 2018)?

**Comment by FediVideos** [comment] 2023-04-18 18:23
> Duplicate of _Ability to add hashtags to lists #7692_ (May 2018)?

I don't think they're quite the same? The older issue seems to mainly be asking for a way to follow hashtags, which we now have already.

**Closed** 2023-05-19 06:04 UTC
Labels: suggestion
