### ISSUE TITLE
UX suggestion: Bot designation in the feed itself

### ISSUE THREAD

**Issue by lirontocker** [mastodon/mastodon#20801] opened 2022-11-15 17:24 UTC
### Pitch

Hi there, 

I'd like to propose a small UX improvement to the display of bot toots in the feed, namely, by added the label "Bot" to the post (this already exists on the profile itself).

Thanks!
![issue_4](https://user-images.githubusercontent.com/7912787/201985571-35e3b044-7921-4ed9-b3a1-d8dbfb390247.png)

### Motivation

All users of the web interface may benefit from this feature.

**Comment by ocdtrekkie** [comment] 2022-11-15 17:43
This is a duplicate of #20764

**Comment by lirontocker** [comment] 2022-11-15 17:46
> This is a duplicate of #20764

I will close, thank you!

**Closed** 2022-11-15 17:47 UTC
Labels: suggestion
