### ISSUE TITLE
Feature Request : Create pictures poll's

### ISSUE THREAD

**Issue by MyNameIsTroll** [mastodon/mastodon#19740] opened 2022-11-04 14:56 UTC
### Pitch

It would be great to be able to create surveys with pictures. This is a feature I would love to see in mastodon.

I made a small mockup to illustrate this:

![image](https://user-images.githubusercontent.com/31790025/200003887-683b5f2a-9def-45fe-9571-3fa1f5f2ee36.png)

### Motivation

I imagine there are many possible uses for this feature. Personally I would like to be able to ask my subscribers for example what kind of poster or logo they prefer etc. . 
I think this is a feature that could be appreciated by artists. And that's something you can't do with normal surveys unfortunately.

**Comment by Saimyx** [comment] 2022-11-04 16:36
Oh yes, great idea!

**Comment by Airouille** [comment] 2022-11-04 22:42
Great idea !

**Comment by starcrashr** [comment] 2022-11-12 19:34
Duplicate of https://github.com/mastodon/mastodon/issues/10707

**Comment by JorgeStolfi** [comment] 2023-01-29 14:25
See suggestion https://github.com/mastodon/mastodon/issues/22840 "Media and link previews should be displayed inside the toot rather than at the end of it". If that change was implemented, this one would automatically follow. See also #17363.

**Comment by JPLeBreton** [comment] 2023-01-29 20:35
> Duplicate of https://github.com/mastodon/mastodon/issues/10707

The linked issue is very clearly not the same feature as what's being proposed here. This is a specific UX for presenting and selecting images instead of text for a poll. Pros and cons of the proposal aside it should not be closed as a duplicate.

**Comment by JorgeStolfi** [comment] 2023-02-10 04:22
If one implements #22840 ("Media and link previews should be displayed inside the toot rather than at the end of it"), then the text of an alternative to a poll can be just an image, which will be displayed next to the tickbox.  That would give the same result as the above proposal, except that the alternatives would be shown stacked vertically instead of as an array. 

But then, suggestion #23295 ("More flexible polls") could include multi-column layout for alternatives that are narrow enough. Like thumbnail images...

**Comment by trwnh** [comment] 2023-05-20 20:18
> This is a specific UX for presenting and selecting images instead of text for a poll. Pros and cons of the proposal aside it should not be closed as a duplicate.

i think they deal with the same issue, though -- having a UX or mockup doesn't make it fundamentally any different as a feature request for "polls with media", however that ends up getting implemented

Duplicate of #10707

**Closed by trwnh** 2023-05-20 20:18 UTC
Labels: suggestion
