### ISSUE TITLE
Customizable "read before sending follow request" message modal

### ISSUE THREAD

**Issue by mtfront** [mastodon/mastodon#20097] opened 2022-11-08 06:37 UTC
### Pitch

Let user set a customizable message prompt before other people can request to follow them. 
When clicking request to follow button for user who has set such message, open a modal with the customizable and two CTAs: Proceed and Cancel. Proceed will send follow request as normal, cancel will not send the request.

### Motivation

Me and a lot of users I know put down a note in profile saying we won't accept follow request if the requester doesn't have visible original toots. Sadly a lot of people still request to follow without reading this message. Having a more visible prompt (e.g. a confirm modal before sending the request if the requested user has set the message) can hopefully reduce the blind follow and rejected request, and provide a better overall experience for both side.

**Comment by ClearlyClaire** [comment] 2022-11-10 08:06
Duplicate of #10384 indeed! Also related: #17151

**Closed by ClearlyClaire** 2022-11-10 08:06 UTC
Labels: suggestion
