### ISSUE TITLE
Not able to show all the replies below the specific page of the first toot, and "show newer replies" button missing

### ISSUE THREAD

**Issue by pullopen** [mastodon/mastodon#17808] opened 2022-03-16 14:22 UTC
### Steps to reproduce the problem

1. The tooter replied themselves on the first toot to make a long toot thread. 
2. For Example, [this toot](https://bgme.me/@MyCyberMemory/107699005659175815). You can see in the link the replies of the original tooter stopped from Feb. 13th.
3. But actually, [this reply](https://bgme.me/@MyCyberMemory/107960117796631709) should also be attached below the original toot, which was written on March 15th, but there's no way to find it in the link above, nor there're any buttons to show "newer replies".

### Expected behaviour

All replies show below the specific page of the first toot.

### Actual behaviour

Only first few toots shows. 

### Specifications

version: v3.5.0rc1
browser: Firefox

**Comment by ClearlyClaire** [comment] 2022-03-16 16:04
This sounds like a duplicate of #8120. Unfortunately, our paging code is pretty broken for reply trees.

**Comment by pullopen** [comment] 2022-03-17 04:22
> This sounds like a duplicate of #8120. Unfortunately, our paging code is pretty broken for reply trees.

Since it's a bug from 2018, I suppose there's no way to solve it for now?

**Comment by ClearlyClaire** [comment] 2022-03-17 10:34
This is a complicated issue and I unfortunately do not have a solution at the moment.

**Comment by trwnh** [comment] 2023-05-20 20:12
Duplicate of #8120

**Closed by trwnh** 2023-05-20 20:12 UTC
Labels: bug
