### ISSUE TITLE
News tab should feature posters whom mentioned it

### ISSUE THREAD

**Issue by RustoMCSpit** [mastodon/mastodon#25897] opened 2023-07-10 23:42 UTC
### Pitch

A list of posters should be able to be seen (like the same way you see likes)

### Motivation

Interesting

**Comment by mrfoogles** [comment] 2023-07-12 04:50
What if multiple posters mention an item?

**Comment by mrfoogles** [comment] 2023-07-12 04:50
E.g. 100 people do.

**Comment by trwnh** [comment] 2023-07-12 18:24
Duplicate of #19620

**Closed by trwnh** 2023-07-12 18:24 UTC
Labels: suggestion
