### ISSUE TITLE
Suspending accounts cause huge delays in federation

### ISSUE THREAD

**Issue by ChatonneLibertaire** [mastodon/mastodon#9377] opened 2018-11-27 16:43 UTC
### Expected behaviour

Suspending accounts should be smooth and shouldn't create any delays in the federation

### Actual behaviour

anarchism.space is currently (as with many other instances) a spambot surge. However suspending them makes my instances to have huge delays in terms of posting things to the federation (not receiving). The CPU is fine (8 cores working at 5% each), the nginx log is filled with attempted accesses to the suspended account from all the other instances I'm federated with (I'm not sure if it's the cause of this but maybe)

### Steps to reproduce the problem

1) Have a decently federated instance
2) Suspend >20 accounts
3) Send a DM to someone on another instance
4) Wait 30 minutes for the DM to be received

### Specifications

Mastodon: 2.6.1

**Comment by Gargron** [comment] 2018-11-27 18:31
Would I be correct to guess that you participate in a relay, and do not have proxy caching configuring in nginx?

**Comment by ChatonneLibertaire** [comment] 2018-11-27 19:48
@Gargron what do you mean by relay? Also, I have exactly the same nginx configuration as noted in the old Production guide (https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md#nginx-configuration) and the default configuration otherwise, which I guess doesn't have proxy caching?

**Comment by Gargron** [comment] 2018-11-27 20:01
Compare your configuration with: https://github.com/tootsuite/mastodon/blob/master/dist/nginx.conf

I don't see a way for new accounts to cause requests from other servers unless they get followers from those servers or you are using a relay service which broadcasts their posts. So new accounts are likely unrelated to your issues.

**Comment by ChatonneLibertaire** [comment] 2018-11-27 22:46
so, indeed there was no proxy caching. I patched the nginx config, restarted nginx, retried to suspend just one ad-bot (no followers, no toots, nothing) and I get flooded with requests from all the federation or something. This is an example of the line I get in the nginx log:
```
[27/Nov/2018:22:43:37 +0000] "GET /users/<bot name> HTTP/1.1" 410 36 "-" "http.rb/3.3.0 (Mastodon/2.6.2; +<mastodon instance>)"
```
And the same behavior stays when I send a message to another instance (i.e. very very long delay)

**Comment by Gargron** [comment] 2018-11-27 23:31
Ah, I know what's happening. You're right after all. When an account is deleted, we want to make sure that everyone deletes it. So, we forward the delete to every known server. Ironically, for new accounts, most servers don't know them, and have to look them up to get the public key to even read the delete message.

That is a consequence of #8305

**Comment by nightpool** [comment] 2018-11-27 23:48
why would slow web workers cause a sidekiq backup though??

**Comment by nightpool** [comment] 2018-11-27 23:50
something something stoplight something something?

**Comment by ThibG** [comment] 2018-11-27 23:58
I guess the issue isn't so much the fact that the remote servers do a useless query, but that mass-suspending users queues a hell lot of `Delete` delivery jobs.

**Comment by nightpool** [comment] 2018-11-28 02:17
i guess? I wouldn't expect Delete jobs to be particularly more expensive/numerous then other types of jobs. Maybe anarchism.space has a lot of known remote inboxes but comparatively few remote followers?

**Comment by ThibG** [comment] 2018-11-28 09:15
On my single-user instance, `Account.inboxes` returns 1802 entries. I assume it's slightly higher for anarchism.space, so that makes tens of thousands of network-bound jobs when suspending 20 accounts, which can definitely cause some delay in job processing.

I'm not too sure how we can make this more efficient, as we have no way to track who has seen (and copied) accounts. We have the same issue with toot deletion to be honest.

**Comment by ChatonneLibertaire** [comment] 2019-02-11 15:05
Can someone take care of this or something, I can't do this anymore... I got more than a hundred spam bots to remove this morning and now my instance is probably going to be cut from federation for probably the whole day because of this issue.

Please do something. Who do I have to implore to do something to either this issue of the spam bots issue in general?

**Comment by ThibG** [comment] 2019-02-11 21:33
At the very least, I think we should move `Delete` sent to instances without followers to the lowest-level priority queue (i.e., `pull` at the time of writing).

**Comment by penartur** [comment] 2019-03-20 14:15
So what should we do when we're flooded with these `GET` requests for suspended users? Just wait it out?

An odd thing is that I see some instances doing several requests for a single suspension, e.g. toot.cafe, masto.themimitoof.fr and mastodon.huloop.com on this screenshot:

![image](https://user-images.githubusercontent.com/1332951/54691125-c6121580-4b33-11e9-87ca-e2033a08dd46.png)

**Comment by ThibG** [comment] 2019-03-20 14:23
I guess we could add a shortcut to not try fetching the key for an account deletion when we don't know the account… it would be a bit awkward to add such special casing at this point in the flow, but it would definitely make sense

**Comment by penartur** [comment] 2019-03-20 18:07
So the wave has finally abated, after ~5 hours of flooding my instance with requests at 100x (!) the average rate, and making my CPU work at 100% load. Usually I'm getting that number of requests (170k) on a good month...

And I've only suspended ~100 bots with zero followers and zero posts.

![image](https://user-images.githubusercontent.com/1332951/54708079-9a068c80-4b53-11e9-8acb-4e98b0a3a0f4.png)

Thankfully my instance runs on a decent hardware, and was able to survive this without significant disruption of service. However, I believe that for some other instances it could be more similar to a DDoS attack.

**Comment by ThibG** [comment] 2019-03-21 21:50
The awkward fix is in master: https://github.com/tootsuite/mastodon/pull/10326
It won't stop other software from performing such requests though.

**Comment by angristan** [comment] 2019-03-21 21:53
Getting hit with the issue:

```
root@mstdn ~# grep -c "/users/Eagleeyeadventures" /var/log/nginx/mstdn-access.log
22290
```

My instance became unavailable because of one account.

![Screenshot 2019-03-21 at 22 47 32](https://user-images.githubusercontent.com/11699655/54787423-f9d06680-4c2b-11e9-90ed-f9833c132015.png)
<img width="1118" alt="Screenshot 2019-03-21 at 22 47 53" src="https://user-images.githubusercontent.com/11699655/54787424-f9d06680-4c2b-11e9-97a9-4a88ae7544a2.png">

**Comment by mjankowski** [comment] 2024-11-26 20:20
Last update here was ~6 years ago ... I'm going to close this on the assumption that the previously reference commit, while not a full/exhaustive solution, is an "as good as we can up with" solution ... please reopen/comment if there's something specific that still exists on current versions and could use renewed, robust, respectful contemplation.

**Closed by mjankowski** 2024-11-26 20:20 UTC
Labels: partially a bug
