### ISSUE TITLE
Introduce a URI psuedo-protocol to allow better interaction across instances

### ISSUE THREAD

**Issue by JessFairbairn** [mastodon/mastodon#25397] opened 2023-06-13 10:00 UTC
### Pitch

Plenty of web applications nowadays use pseudo-protocols to specify a link, regardless of the actual data format, should be opened in a specific application or website. Spotify has _spotify:_ and Zoom has _zoommtg:_ to prompt the client machine to open external programs.

Websites (and PWAs) can also register as a protocol handler, but with the caveat that it must use the _web+whatever:_ format (explained on MDN [here](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler#browser_compatibility). I would suggest _web+mastodon:_ or _web+fedishort:_ or _web+toot:_ or something.

Mastodon or mastodon-compatible instances could offer to register themselves as a handler for this protocol when the user logs in. After this, if other instances have their follow button offer a link with that psuedo-protocol in the URI and make that account automatically open in your nominated instance.

### Motivation

We know that the difficultly following users across instances has been a huge limitation to new users, to the point where people have built browser extensions to help. I believe this will help reduce the friction there and not require any manual copy and pasting, making is more obvious to newcomers from Twitter and saving powerusers time.

**Comment by renchap** [comment] 2023-06-13 17:17
Closed as duplicate of #19679

**Closed by renchap** 2023-06-13 17:17 UTC
Labels: suggestion
