### ISSUE TITLE
Remote follow dialog is unusable on non-giant screens

### ISSUE THREAD

**Issue by ell1e** [mastodon/mastodon#21891] opened 2022-11-30 15:41 UTC
### Steps to reproduce the problem

1. Go to any remote profile also using mastodon but not your instance
2. Click "Follow"

### Expected behaviour

Follow dialog is usable

### Actual behaviour

The remote follow dialog is unusable on non-giant screens, because it neither does any responsive adjustment nor the most basic addition of a scrollbar

### Detailed description

The remote follow dialog should be responsive or at least have a scroll bar. I'm not even on a phone, just a laptop, so that it can't deal with this screen size is unfortunate. Since this is such basic functionality, would be nice if this could be addressed somewhat soon.

![Screenshot from 2022-11-30 16-36-11](https://user-images.githubusercontent.com/64124388/204844572-e2480699-36fb-46c8-92e1-9b0ddb51335b.png)
(Everything cut off at the bottom in that screenshot is simply not accessible, this includes the section to follow remotely)

### Specifications

Broken on mastodon.lol and a couple of other instances, not sure what exactly they use but it seems to be a recent Mastodon version

**Comment by rbairwell** [comment] 2022-11-30 16:02
Duplicate of https://github.com/mastodon/mastodon/issues/21622 .
Fixed in https://github.com/mastodon/mastodon/pull/21763 .

**Closed** 2022-12-07 11:05 UTC
Labels: bug
