### ISSUE TITLE
Feature Request: When sharing a toot/post, have the user comment in the shared link preview

### ISSUE THREAD

**Issue by ziggyb1013** [mastodon/mastodon#21540] opened 2022-11-24 04:24 UTC
### Pitch
Created from discussion thread: https://github.com/mastodon/mastodon/discussions/21535

When sharing links from the birdsite via Messages for iOS, it's one link gives you one post that does a picture preview, text of the post and the user name.

When mastodon does a shared post in iOS, you get the preview images and the user information, but separates the comment made by the user as a separate "message".

It makes sharing items a bit less convenient and doesn't look like you shared "one thing." Also it's not as concise compared to how a "tweet" is shared. See attached screen shots.

### Motivation

It makes sharing mastodon links and posts much more concise on iOS and looks more definitive as it's just one link, gives you all of the information from the toot/post. Instead of two separate things. It also gives Mastodon feature parity with the bird site.

**Comment by pdenya** [comment] 2022-12-02 21:11
Twitter iMessage preview example
![image](https://user-images.githubusercontent.com/622056/205386508-c04fb33f-1b0d-49f6-a6bb-71df02ccbbd3.png)

Mastodon iMessage Preview example
![image](https://user-images.githubusercontent.com/622056/205386691-1843ac9f-3149-48ab-a5ea-12de3e4bb991.png)

**Comment by pdenya** [comment] 2022-12-02 21:15
duplicate of #20569

**Closed** 2023-05-20 20:24 UTC
Labels: suggestion
