### ISSUE TITLE
Blocking a user doesn't hide their reply to my post

### ISSUE THREAD

**Issue by graue** [mastodon/mastodon#31535] opened 2024-08-22 02:14 UTC
### Steps to reproduce the problem

1. Post a status
2. Receive an abusive or obnoxious reply
3. Block the user

### Expected behaviour

My server should no longer show the blocked user's reply

### Actual behaviour

Other people still see the blocked user's reply under my post, even on my own server

### Detailed description

While I'm aware that limiting replies to followers/mentioned is technically complicated (as discussed in #14762), it seems simple enough at least that _my_ server should not show everyone else a reply under _my_ post from a user I've blocked.

The impact is that I have no way to avoid providing a platform for someone to post something offensive or even illegal -- apart from deleting my own post that they responded to.

This bug is easiest to see by accessing the web interface while logged out, but I'm reporting it as a server/API bug because I assume that the blocked user's reply is also being shown via API endpoints. (And so, for example, if I [used Mastodon replies for my blog comments](https://carlschwan.eu/2020/12/29/adding-comments-to-your-static-blog-with-mastodon/) I would have no way to remove an offensive comment from my blog.)

I'm on Mastodon v4.2.10 (technically Hometown, which hasn't changed this functionality, based on v4.2.10); if this is already fixed in the latest Mastodon, please let me know and accept my apology for the report.

### Mastodon instance

carfree.city

### Mastodon version

v4.2.10+hometown-1.1.1

**Comment by renchap** [comment] 2024-08-22 07:02
I think this may be fixed by https://github.com/mastodon/mastodon/pull/18468 ?

**Comment by graue** [comment] 2024-08-22 07:06
Sounds like it, based on the description. Would love for that to be merged!

**Comment by trwnh** [comment] 2024-08-22 13:46
Duplicate of #15631 / Subset of #10916

**Closed by trwnh** 2024-08-22 13:46 UTC
Labels: bug, status/to triage
