### ISSUE TITLE
TypeError: Cannot read properties of undefined 

### ISSUE THREAD

**Issue by LarsFosdal** [mastodon/mastodon#25589] opened 2023-06-26 16:41 UTC
### Steps to reproduce the problem

1. swiped away from Mastodon app, swiped back an hour later

### Expected behaviour

App should refresh

### Actual behaviour

App raised error

### Detailed description

TypeError: Cannot read properties of undefined (reading 'get')

TypeError: Cannot read properties of undefined (reading 'get')
    at https://mastodon.social/packs/js/features/home_timeline-c60d30a44b864fb9bc77.chunk.js:1:12165
    at https://mastodon.social/packs/js/common-6cfa7ab14058ddfbd1de.js:2:54267
    at t.__iterate (https://mastodon.social/packs/js/common-6cfa7ab14058ddfbd1de.js:2:73568)
    at Ue.a.__iterateUncached (https://mastodon.social/packs/js/common-6cfa7ab14058ddfbd1de.js:2:54235)
    at t.__iterate (https://mastodon.social/packs/js/common-6cfa7ab14058ddfbd1de.js:2:43375)
    at t.forEach (https://mastodon.social/packs/js/common-6cfa7ab14058ddfbd1de.js:2:90132)
    at https://mastodon.social/packs/js/common-6cfa7ab14058ddfbd1de.js:2:71044
    at t.Ft [as withMutations] (https://mastodon.social/packs/js/common-6cfa7ab14058ddfbd1de.js:2:62755)
    at t [as constructor] (https://mastodon.social/packs/js/common-6cfa7ab14058ddfbd1de.js:2:71002)
    at Ve (https://mastodon.social/packs/js/common-6cfa7ab14058ddfbd1de.js:2:57724)

get (webpack:///app/javascript/mastodon/features/home_timeline/index.jsx:38:82)
predicate.call (webpack:///node_modules/immutable/dist/immutable.es.js:1102:20)
fn (webpack:///node_modules/immutable/dist/immutable.es.js:2702:10)
collection.__iterate(function (webpack:///node_modules/immutable/dist/immutable.es.js:1101:15)
fn (webpack:///node_modules/immutable/dist/immutable.es.js:269:16)
forEach (webpack:///node_modules/immutable/dist/immutable.es.js:3959:16)
iter.forEach(function (webpack:///node_modules/immutable/dist/immutable.es.js:2561:11)
withMutations (webpack:///node_modules/immutable/dist/immutable.es.js:1913:2)
empty.withMutations(function (webpack:///node_modules/immutable/dist/immutable.es.js:2559:17)
reify (webpack:///node_modules/immutable/dist/immutable.es.js:1565:56)

### Specifications

Mastodon latest 
Google Pixel 7 Pro

**Comment by renchap** [comment] 2023-06-26 16:57
Duplicate of https://github.com/mastodon/mastodon/issues/25569

Fixed by https://github.com/mastodon/mastodon/pull/25579

Will be deployed on mastodon.social in the coming hours.

**Closed by renchap** 2023-06-26 16:57 UTC
Labels: bug
