### ISSUE TITLE
Verification is dependent on the pattern <a rel="me" href...>

### ISSUE THREAD

**Issue by matt-ellery** [mastodon/mastodon#27001] opened 2023-09-20 22:09 UTC
### Steps to reproduce the problem

I am using hugo/hugo-coder https://github.com/luizdepra/hugo-coder to generate a website.

1. Generate a website with mastodon configured (e.g. url = "https://mastodon.social/@[user]" rel = "me")
2. The hugo-coder theme uses the following format: `<a href="{{ .url | safeURL }}" aria-label="{{ .name }}" {{ if .rel }}rel="{{ .rel }}"{{ end }} {{ if .target }}target="{{ .target }}"{{ end }} {{ if .type }}type="{{ .type }}"{{ end }}><i class="{{ .icon }}" aria-hidden="true"></i>`
3. The html link is generated as: `<a href="https://mastodon.social/@[user]" aria-label="Mastodon" rel="me"   >`
4. Mastodon doesn't recognise the website as verified (no green tick)
5. Change hugo-coder to use: `<a {{ if .rel }}rel="{{ .rel }}" href="{{ .url | safeURL }}" aria-label="{{ .name }}" {{ end }} {{ if .target }}target="{{ .target }}"{{ end }} {{ if .type }}type="{{ .type }}"{{ end }}>
          <i class="{{ .icon }}" aria-hidden="true"></i>`
6. re-generate the website.
7. The html link is generated as `<a rel="me" href="https://mastodon.social/@[user]" aria-label="Mastodon"   >`
8. Mastodon recognises the website as verified (green tick appears)
...

### Expected behaviour

The position of rel="me" within the html link should not affect the verification process. Ideally as long as the two elements (href to the mastodon profile and rel="me") both exist then the link should be verified.

### Actual behaviour

The link is only verified when the link starts with <a rel="me" href...>

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.0-rc2

### Browser name and version

Firefox 117.0.1

### Operating system

Linux Mint 21.2

**Comment by nightpool** [comment] 2023-09-20 23:49
Can you link to a HTML page that reproduces this issue? If you look at the code, you can see that Mastodon uses the Nokogiri HTML parser and a very standard xpath query, so it's very unlikely that it would be related to the order of the attribute or "the position of the rel=me". Maybe because you were using a string template your original template had a malformed attribute or unclosed tag https://github.com/mastodon/mastodon/blob/main/app/services/verify_link_service.rb

**Comment by matt-ellery** [comment] 2023-09-24 21:52
Hi Nightpool. I've tried to replicate the problem again but I'm pleased to say that there are no issues now, so your point about malformed attributes may be correct. I'll close this issue.

**Comment by BobJonkman** [comment] 2023-10-17 18:09
Experienced the same issue: When a 'style=' attribute is present at the start of the '<a>' element then Mastodon did not recognize the verification.  See https://mastodon.sdf.org/@bobjonkman (using Mastodon v4.1.10)

HTML on https://bobjonkman.ca/ : <a style="vertical-align:middle;" rel="me" href="https://mastodon.sdf.org/@bobjonkman" title="Bob Jonkman (@bobjonkman@mastodon.sdf.org) - Mastodon @ SDF" >

I temporarily changed the HTML to put the style attribute at the end of the element: <a rel="me" href="https://mastodon.sdf.org/@bobjonkman" title="Bob Jonkman (@bobjonkman@mastodon.sdf.org) - Mastodon @ SDF" style="vertical-align:middle;" > and the verification was confirmed.

I changed it back to have the style attribute at the start of the element, but now Mastodon continues to recognize the verification...

--Bob.

**Comment by eloquence** [comment] 2023-10-28 05:36
Possibly a similar bug with fragile link parsing: If I add https://cohost.org/eloquence to my bio fields, it does not verify. If I `curl` the HTML, it contains:

```
<a href="https://social.coop/@eloquence" class="text-mango" rel="me nofollow noopener" target="_blank">social.coop/@eloquence</a>
```

**Comment by Geobert** [comment] 2024-04-09 12:53
On instance piaille.fr running 4.2.8, I fail to verify on my website https://geobert.fr
at the bottom I have `<a rel="me" href="https://piaille.fr/@geobomatic">`

**Comment by Geobert** [comment] 2024-05-31 13:54
> On instance piaille.fr running 4.2.8, I fail to verify on my website https://geobert.fr at the bottom I have `<a rel="me" href="https://piaille.fr/@geobomatic"><i class="fab fa-mastodon"></i></a>`

Found out today what was the error: w3c validator was failing on certificate verification, and it turned out that the chain was incomplete. Changed the config of my web server to use `fullchain.pem` instead of `cert.pem` did the trick!

**Comment by mjankowski** [comment] 2024-12-04 20:26
Closing this because the original issue (and some/all of the others) were either resolved or discovered to be issues outside our control.

Separately, the parser here improved a bit in 4.3 release and more so since then.

If there are links or markup snippets anyone has which SHOULD validate but dont, please open new issues with as much detail as possible.

**Closed by mjankowski** 2024-12-04 20:26 UTC
Labels: status/to triage, area/web interface
