### ISSUE TITLE
Support posting polls and images in the same post

### ISSUE THREAD

**Issue by trufae** [mastodon/mastodon#33085] opened 2024-11-27 15:22 UTC
### Pitch

Sometimes it is necessary to publish a poll with a picture, 3rd party apps will need to implement the support for it, because right now it seems to be an exclusive OR

### Motivation

I felt the need to do that several times when using mastodon, from artists asking for feedback about a picture, or showing an image related to the question. There are many reasons why this could be a desirable feature.

**Comment by Cassolotl** [comment] 2024-11-27 18:40
Duplicate of *Polls with Media Attachments #10707*, I think? (If so, please close this issue and head over to support the existing open issue with comments and thumbs-ups!)

**Comment by trwnh** [comment] 2024-11-27 21:48
Duplicate of #10707

**Closed by trwnh** 2024-11-27 21:48 UTC
