### ISSUE TITLE
Ability to Disallow Receiving DMs

### ISSUE THREAD

**Issue by KRRW** [mastodon/mastodon#20866] opened 2022-11-16 11:11 UTC
### Pitch

Hi. In light of recent articles online criticizing how Mastodon does not encrypt direct messages (a.k.a. DMs) (considered a weakness of Mastodon when compared to "birdsite", I think it would be good if there is an option for mastodon users to be able to turn-off receiving DMs altogether (and hide the Send private message button). Like on "birdsite", there are users who use mastodon not for private messaging, and since receiving unwanted DMs can be spammy on the receiver, plus the unsecure nature of Mastodon's implementation of private messaging, being able to turn off and hide the DM option is a great feature. As an alternative, for old-fashioned folks like me who still prefer to communicate via emails, there should also be an option to substitute the DM button with an "email me" button. Exposing my email address to my audience is relatively safer compared to receiving and responding to a DM conversation that  can anytime be exposed to others just by @mentioning their handle.

### Motivation

Cybersec

**Comment by AlanBell** [comment] 2022-11-16 12:02
That link starts composing a message with visibility set to mentioned people only, and the person in question mentioned in it. Removing the link wouldn't stop someone composing a message, setting visibility on their message and mentioning the person.
To really stop DMs you would have to have a bar on mentioning the person in a "mentioned people only" message, which doesn't seem like a feature without complications of it's own.
Removing the shortcut might be possible.

**Comment by ineffyble** [comment] 2022-11-16 12:09
> Twitter DMs aren't e2e encrypted either. I'm not sure this comparison makes sense.

No, but there seem to be a lot of people out there who are much less comfortable with their local Mastodon administrator being able to see their DMs, compared to Twitter employees.

**Comment by AshtonKem** [comment] 2022-11-20 10:06
Part of this feels like a design issue. Under the hood DMs are just visibility restricted posts with named participants, but from the interface they look and feel like DMs. And as Mastodon grows, this means they'll come with the traditional privacy and abuse concerns that plague DMs on other platforms. 

I don't think it's enough to discuss the underlying tech, I think the UX has to be examined here. And not providing a way for people to suppress what feels like a twitter DM, no matter how it works under the hood, is going to become a safety issue sooner or later.

**Comment by unusualevent** [comment] 2022-11-21 00:51
right - whether they're encrypted or not is beside the point of giving people good tools. There's already a checkmark in preferences for "block direct messages from people you don't follow" - I guess the other options would be "block all direct messages". There's already a checkmark for blocking notifications from people you don't follow, or from people who don't follow you.

Telegraphing, via their UI, that they aren't listening / removing the reply feature is something malicious clients /could/ bypass, but polite clients would obey it (and the recipient's settings are still, well, muted, so it doesn't matter, it's just a helpful error page). You could say that all polite clients would respect the settings of an original poster to hide all replies not mentioned by the original authors, or say that a polite client reads a person's profile and notices that DMs are off, and that they won't be notified because they don't follow you, so cool it.

**Comment by ineffyble** [comment] 2022-11-21 09:27
> Duplicate of #11882

Sounds like this is slightly broader in scope - turning off DMs entirely.

**Comment by huitema** [comment] 2022-11-25 20:30
Yes, turning off DM entirely is not hugely different from just blocking DM from accounts that the user does not follow. It sounds different, but in practice if Alice follows Bob the Bob can simply mention Alice and she will get the message.

**Comment by trwnh** [comment] 2023-05-19 06:45
Duplicate of #7603

**Closed by trwnh** 2023-05-19 06:45 UTC
Labels: suggestion, privacy
