### ISSUE TITLE
Feature request: multi timeline

### ISSUE THREAD

**Issue by matyapiro31** [mastodon/mastodon#3987] opened 2017-06-28 16:31 UTC
I think it isn't good for both server and client to fetch all the federation timeline once.
There are many users who don't want to see what not being interested in, and servers maintainers who don't fetch too much.
so I suggest the feature of 'multi  timeline'. In Reddit, there are features like below:
https://mastodon.social/web/timelines/public/local+example.com+mstdn.jp
it's a feature to fetch only which instances you like to watch.
This example shows mastodon.social and example.com and mstdn.jp.

**Comment by sameyepatch** [comment] 2017-11-16 04:50
This is a great idea, please consider implementing this.

Newbies are pretty confused by federation, since most come from Twitter. Say someone creates an account on mastodon.social but then they realize that there is another instance with certain interests relating to theirs, so they *have* to create another account, this time in that instance so they can read a more specific, on-topic local timeline. This is time consuming. They probably have the same username but different password, or same username, same password but two accounts, they'll stop using one of them.

What if they don't have to do that to start with? What if they started by creating an account on mastodon.social but there's an option to add the local timeline from another instance so they can read on-topic toots and follow people from that instance in particular? Yes, there's the search but it only works with hashtags, not with general terms. My guess is that the RegEx filter only applies to the toot contents, so can't filter toots from X instance only (correct me if I'm wrong).

**Comment by deutrino** [comment] 2018-03-31 15:58
Duplicate of #979?

**Comment by lyndsysimon** [comment] 2018-04-04 19:06
> My guess is that the RegEx filter only applies to the toot contents, so can't filter toots from X instance only (correct me if I'm wrong).

As far as I can tell, this is correct.

That's somewhat annoying for me, because I'd like to be able to filter `*@switter.at` from my federated timeline on my primary account, since I'm likely to have it up on my workstation, and many users there don't use `cw` on their image posts.

**Comment by trwnh** [comment] 2023-01-26 23:35
Duplicate of #3812

**Comment by trwnh** [comment] 2023-05-14 00:05
Duplicate of #3812

**Closed by trwnh** 2023-05-14 00:05 UTC
Labels: suggestion
