### ISSUE TITLE
Add descriptions (alt-text) to profile picture and header picture

### ISSUE THREAD

**Issue by colinleroy** [mastodon/mastodon#26505] opened 2023-08-16 07:55 UTC
### Pitch

They're missing. It would be nice to be able to have descriptions of these pictures too.

### Motivation

As an accessibility feature, it would benefit the whole community.

**Comment by Cassolotl** [comment] 2023-08-16 18:00
Duplicate of *Add ALT-Tag to banner and profile pictures and make the value editable for acessiblility reasons #10313* (March 2019)

**Comment by vmstan** [comment] 2023-11-17 13:57
Closed as duplicate.

**Closed by vmstan** 2023-11-17 13:57 UTC
Labels: suggestion
