### ISSUE TITLE
Follower-only replies 

### ISSUE THREAD

**Issue by nf3xn** [mastodon/mastodon#28059] opened 2023-11-23 20:35 UTC
### Pitch

# Per post setting for no replies and/or follower-only replies 

## As a user I would like the ability to control who can reply to my posts with the option for 

- anyone 
- followers only 
- no reply 

### Anyone
Anyone can reply. What we have. 

### Followers only. 
Only people I follow can reply to the post. People can reply to someone I follow who has replied to my post unless they also have set Followers only. No take backs. If you unfollow them after they have replied too bad. 

### No reply. 
Screaming into the void mode. It just sits there. Gone fishing. Go Jets.

## What problem does this solve.
Sometimes there are certain topics you _just know_ that if you post about that you are going to be mansplained to death so you just don't bother because its not worth it.

**Comment by renchap** [comment] 2023-11-23 22:56
Duplicate of #14762

We want to have something similar to this (reply controls), but this is currently blocked due to the lack of a clear way of implementing it with the ActivityPub protocol.

See the linked issue for more details.

**Closed by renchap** 2023-11-23 22:56 UTC
Labels: suggestion
