### ISSUE TITLE
Regression in 3.4: Default follows for new users

### ISSUE THREAD

**Issue by joenepraat** [mastodon/mastodon#16229] opened 2021-05-12 14:26 UTC
On the servers I administer, new users automatically follow the moderators. I manually configure this under 'Default follows for new users' in the site settings. 

According the [changelog for v3.4.0 RC1](https://github.com/tootsuite/mastodon/releases/tag/v3.4.0rc1) "New users no longer automatically follow admins". I suppose this is about the 'Default follows for new users'.

Can you please don't make this regression? The servers I administer worked this way successfully for years. Users can easily see who the moderators are and how to contact them.

This issue can be closed if this is a misunderstanding.

**Comment by Gargron** [comment] 2021-05-12 14:54
'Default follows for new users' option has been renamed. Now it ensures that the provided users appear on top of follow suggestions for new users. Newly signed-up users can choose if they want to follow them or not.

**Comment by joenepraat** [comment] 2021-05-12 15:14
> Newly signed-up users can choose if they want to follow them or not.

And that is exactly what we don't want. With this you are forcing servers like us to change their on-boarding strategy, that worked for years. Another reason we do this is that it fills the new users home timeline with helpful admin/mod posts.

Don't get me wrong, I'm completely in favor of the new follow recommendations, but this is a painful regression. Please consider to fix this? I'm okay with if it's CLI only.

**Comment by rebelga** [comment] 2021-05-13 01:53
The new suggestions should be in addition to the default follows.  The new user should have to opt-out of those defaults (as before).  If they are confused during on-boarding (common) and do nothing here, the defaults set by the administrator should remain.  If the administrator chooses, they can always not set any default, but that choice should be theirs.

**Comment by shleeable** [comment] 2021-05-13 04:49
I second that having users follow my rarely used admin user by default is my preferred option.

This is an opt-out method over opt-in.

**Comment by marians** [comment] 2021-05-17 19:31
I agree that it's unfortunate to remove the automatic following of certain admin accounts. We use this function to increase the likelihood of our users getting information about the platform. However with admin announcements, this may have become less important. Still, with the nature of Mastodon being used by smaller communities, I can see the desire of the "hosts" to be visible on the platform they offer.

Are these feature decisions documented and explained in public somewhere? I would be interested in reading more about the reasons.

**Comment by Gargron** [comment] 2021-05-17 21:16
> Are these feature decisions documented and explained in public somewhere? I would be interested in reading more about the reasons.

I wrote in depth about the changes in #15945, in particular:

> Auto-following admin user(s) is probably the feature that has been carrying new user onboarding for years, but it too is flawed. It requires admins to consistently act as curators and boost interesting content from different users. It leaves people wondering why they are already following someone they don't know, and does not always translate into new users following other people.

I will elaborate.

1. Auto-following admins as a means of onboarding relies too much on individual effort. Some people act as curators to create a default feed that's full of diverse content, but this is a minority of admins. And it has to be done every day. If a new user logs on and finds the most recent posts are from a week ago, it may leave a bad impression. When the user is presented with choices, less active accounts may be more easily forgiven as the user understands they made the choice.
2. Auto-following takes agency away from users, I've received multiple complaints from people who found it confusing/jarring that they were already following someone they did not recognize. Consider the very real example of someone who does not like cats signing up on Mastodon and auto-following me, who boosts a lot of cat content. Because this content is presented to them without them choosing it, it may create the impression that the platform is not for them.
3. With the announcements feature, following admins is no longer necessary for staying up to date with server events, so that is no longer a good excuse for auto-following.
4. Admins may put certain accounts at the top of the suggestions. If an account has a compelling bio (let's say, "follow me for updates about this server"), a new user will likely choose to follow it of their own accord, which is a lot more valuable for everyone. Auto-following happened for every account that went past e-mail confirmation, which included bots or people that bounced and gave up right after that, whereas every manual follow represents a conscious action by a real person.

**Comment by bremensaki** [comment] 2021-05-18 00:40
I don't see why this new onboarding excludes having a list of accounts to auto-follow as an optional extra at least, even if it's not just the admins. Having just that list field back as an option would be hugely beneficial. Nobody would have to use it.

**Comment by shleeable** [comment] 2021-05-18 01:14
I've become aware of how important this auto-follow my admin account was to my workflow and experience as an admin on a smaller instance.

As I've said above, Auto-Follow should be opt-in.

**Comment by shleeable** [comment] 2021-05-18 03:29
So far, I've spoken to four admins, and they all hate this change.
* https://ausglam.space/@hugh/106254039874505849
* https://social.chinwag.org/@mike/106247558562389429
etc

**Comment by hughrun** [comment] 2021-05-18 04:10
Hi

Thanks @Gargron for your work on Mastodon. I enjoy using it and being an instance admin. However this regression is a big problem for many admins and I suspect reflects a misunderstanding of how non-gigantic servers work. The new onboarding tool looks like it will be a great addition however the removal of opt-out auto-follows is unnecessary and problematic.

> Auto-following admins as a means of onboarding relies too much on individual effort. 

The feature as it already existed allows admins to opt-in to this workflow if it works for them and not use it if it doesn't. You're removing a feature that was already optional, the onus is on you to justify why you are removing it, not for admin users to justify why they still need it.

> Auto-following takes agency away from users, 

The whole point of the new on-boarding approach is to provide a more targeted onboarding experience. If you're suggesting a list of recommended follows instead of leaving it up to them to freely find people, you're already taking some agency away from users. They can still unfollow with the same number of clicks it takes to follow.

_Removing_ the ability to set auto-follows on the other hand does take away agency from instance admins.

> I've received multiple complaints from people who found it confusing/jarring that they were already following someone they did not recognize.

And now you are receiving multiple complaints from real admins of real Mastodon instances that you have totally broken their processes for managing non-gigantic servers. Significant decisions to remove key features should be based on wide consultation instead of a few personal anecdotes and an obscure comment in a GitHub pull request.

> With the announcements feature, following admins is no longer necessary for staying up to date with server events

Announcements frankly are a PITA to use - it's much easier to send a toot. On smaller instances this is effectively the same as an announcement. Except it's actually better, because announcements don't appear on most (all?) mobile apps. So if a user doesn't log in via the web interface for months, they'll never see the announcements.

> Admins may put certain accounts at the top of the suggestions. 

**If you make these pinned suggestions _auto-selected_ (i.e. users have to opt out but can do so from the onboarding interface) that would be a good compromise I expect most admins would find acceptable.**

**Comment by marians** [comment] 2021-05-18 07:26
Thanks @Gargron for taking the time to explain the change. Makes sense to me, mostly. I like the fact that admins can add accounts to the top of the suggestions. I also agree with @hughrun that it would be more in line if those would be pre-selected for following, allowing users to opt-out. Each way however has its upsides and downsides. The upside of the new approach is the fact that the user themselves takes responsibilities and gets active, making the timeline their own from the beginning.

I'm curious to test the new experience from a user perspective.

**Comment by marians** [comment] 2021-05-18 07:28
Side node: I understand that the `tootctl accounts follow` still exists, so admins who really want new users to follow specific accounts can create some automation based on that.

**Comment by shleeable** [comment] 2021-06-07 03:02
> Side node: I understand that the `tootctl accounts follow` command still exists, so admins who really want new users to follow specific accounts can create some automation based on that.

Why should this require additional work by instance admins? I don't really want to script something to fix a regression.

**Comment by bremensaki** [comment] 2021-06-07 03:09
The docs say that command makes ALL accounts follow someone. Running it periodically to catch just accounts registered since it was last run feels like suggesting we crack an egg with a sledgehammer.

All this needs is the old text field to come back to stack a few default follows into if the instance admin desires, and wouldn't conflict with or negate the utility of this new method at all. I'd prefer that over "follow admins" honestly, as my general news account doesn't need to be an admin or mod.

**Comment by marians** [comment] 2021-06-07 07:05
> The docs say that command makes ALL accounts follow someone.

My mistake. That's indeed not a workaround then.

**Comment by shleeable** [comment] 2021-06-07 13:19
There is also a work around for this... just make admin accounts auto follow all new signups instead of them following us.

OR just give me a notification of "new signup" to all staff

**Comment by ClearlyClaire** [comment] 2021-06-21 15:04
Assuming the auto-follow itself feature doesn't get back into Mastodon, would an email notification on signup be enough for your admin workflow?

**Comment by joenepraat** [comment] 2021-06-21 19:29
> Assuming the auto-follow itself feature doesn't get back into Mastodon, would an email notification on signup be enough for your admin workflow?

We already have that. I still assume by the way that this regression will be fixed in the next version, especially because I'm by far not the only one.

**Comment by ClearlyClaire** [comment] 2021-06-21 20:12
> > Assuming the auto-follow itself feature doesn't get back into Mastodon, would an email notification on signup be enough for your admin workflow?
> 
> We already have that.

… is that so? as far as I can see, there's notifications for pending accounts, so that's assuming approval-based registration. I thought the issue was with open registration.

> I still assume by the way that this regression will be fixed in the next version, especially because I'm by far not the only one having problems with this.

Knowing Gargron, I wouldn't make such an assumption.

**Comment by renatolond** [comment] 2021-06-21 20:16
> Assuming the auto-follow itself feature doesn't get back into Mastodon, would an email notification on signup be enough for your admin workflow?
@ClearlyClaire I'd prefer in-software notification, with the optional email toggle, but an email would still be fine and better than no notification at all :)

**Comment by joenepraat** [comment] 2021-06-21 20:19
> … is that so? as far as I can see, there's notifications for pending accounts, so that's assuming approval-based registration. I thought the issue was with open registration.

My servers are approval only, but notifying about new users is not the main problem for me as you can read in the original issue.

> > I still assume by the way that this regression will be fixed in the next version, especially because I'm by far not the only one having problems with this.
> 
> Knowing Gargron, I wouldn't make such an assumption.

No comment.

**Comment by bremensaki** [comment] 2021-06-21 22:09
Agreeing wholeheartedly with @renatolond here. Email is better than nothing, but just having back what used to work fine is better. 

My ideal is just putting back the text field for a list of accounts to auto-follow. I don't see why this can't co-exist with the new thing.

**Comment by shleeable** [comment] 2021-06-29 05:01
This being ignored has left a bad taste in my mouth.

**Comment by bremensaki** [comment] 2021-06-30 03:35
If nobody's intending to resolve this issue in some way how about at least being upfront enough to slap a WONTFIX on the case or something instead of just ignoring it.

**Comment by rebelga** [comment] 2021-06-30 12:22
A couple of decades ago, I was an enthusiastic Gnome 1.x user.  It was very configurable for my tastes and use case.  When 2.x came along, the devs decided how it should be used and removed much flexibility.  I've been a KDE user ever since.

It is unfortunate this is an issue at all when it could be so easily resolved by giving site admins an option (even a hidden one).  Such an option (to continue long-established prior functionality) would hurt no one.  Lacking it reflects poorly on Mastodon and may encourage splintering.

**Comment by shleeable** [comment] 2021-09-01 12:31
<img width="840" alt="image" src="https://user-images.githubusercontent.com/17537000/131671440-845daeaa-46bc-4fd2-8c06-e36e37519fc1.png">
lol. Since the autofollow was removed, my spam reports have like increased massively as well.. because I'm not killing the accounts seconds after they're created.

my users are complaining because my quality of service has dropped.

I'm going to patch that code back in to fix the regression and hope it doesn't break anything

**Comment by shleeable** [comment] 2021-09-02 01:13
That annoying guy in Discord wants this ticket actions...

Big G:
![image](https://user-images.githubusercontent.com/17537000/131765668-1e8b5990-245a-4050-81f7-9a5989c092a4.png)

**Comment by cgubi** [comment] 2021-09-11 07:40
Good morning, this is @gubi@sociale.network here, one of the admins of the instance sociale.network . These are my two cents of insights on this regression.

Why we don't have "boost with comment" feature? Because there was only one use case considered for this feature: inviting people to cyberbully the user that will be put on the spotlight with a comment on one of his/her toot.

Why we will lose the feature "autofollow this admin with opt-out freedom of choice" because there was only one use case considered: people getting lost in big instances where autofollowed admins are tooting about cats, with newcomers feeling disturbed by the auto-follow. 

Our use case was the following:

Small community with a defined cultural identity centered around nonviolence and environmentalism.

When you cross the door, you "shake hands" (autofollow) with the people responsible of the community, as it's normal every time you enter into someone else's home to meet a new family.

The autofollowed account is used for announcements with public toots and acts as a bot for just ONE welcome message sent with a private toot to every newcomer.

We also asked for a professional author of comics to develop a mascot for this service account, which is a koala: @koala@sociale.network, an animal associated to environmentalism and wildlife protection, which is acting as "local mascot" for our instance, being a companion to the elephant, the "global mascot" of the software. 

Besides his role for the announcements, the welcome message sent by koala provides the following information:

- Welcome in our environmentalist and pacifist community 
- This is just one instance in a bigger fediverse with thousands of nodes and millions of users (you're not in a useless echo chamber, but in one of many starships to explore a galaxy)
- Here is a link where you can find some documentation for mastodon in the language of the instance (Italian)
- Here is the hashtag we use for "microtutorials" that explain specific functions in one toot
- Here is the tag of one admin that you can contact for support

I used the autofollow also to be followed and follow every newcomer, for an early detection of massive spam bots registration or disruptive behavior. Maybe an option "follow all users" that is available only to admin accounts could be helpful.

It's true what @Gargron said: this requires a lot of effort, but in a small community like ours we are more than happy to make such effort to keep hate speech out of the door. On a daily basis I see who is coming because I got notified of the autofollow, I follow these people to know them and be informed about them, they can unfollow me and we've agency on both sides: they're free to unfollow me and koala, I'm free to know of their arrival and follow them. 

That said, I think that asking @Gargron to revoke this regression, because of the positive use cases, is a pointless attempt, because from his perspective and with his approach such real cases will always stay in the shadow of potential misuses.

Besides this specific discussion, I can see a more general approach here. The creator of a software, showing a great sense of responsibility for all the possible uses of his software, tries to be a global meta-moderator for all installation of such software, preventing misuses with the block or the cut of functions which despite their potential misuse could be really useful for some use cases.

While this approach is understandable and respectable in its intentions from a moral perspective, I think that from a practical perspective, it could be useful to limit human behaviours by education and by the positive social pressure of a community instead of limiting the potential of a software with the cut of some function by design. Promoting positive use cases documented by the community of mastodon admins could be more productive than preventing misuses with the cut of functions that some admins are using in the best interest of their communities.

On top of that, from a cultural perspective this approach is contradicting the culture of decentralization which is the foundation of the fediverse, centralising the prevention of misuses in the hand of one person, and forgetting that the responsibility for misuses made with any free software doesn't rely on the shoulders of software developers, but on the users of the software, and in the case of Mastodon is a responsibility shared with the admins and the moderators of every instance.

That's why my comment is not a wishful but useless request to keep alive this function (even if I'd like to) but it's just a "thank you for your effort and your great sense of social responsibility", followed by the suggestion to @Gargron to consider the option of complying with this sense of responsibility embracing a more open-minded and trustful attitude, where actual positive use cases are not diminished (because only potential misuses are considered and evaluated to decide if a function must be implemented or cut) and the admins/moderators of this complex ecosystem are trusted to do their part to keep it healthy and respectful for their communities.

In any case, the gratitude that I feel for the improved quality of my digital and personal life thanks to the escape in the "mastodon side of the fediverse" , away from commercial platforms of social networking and their evil manipulations, will always be bigger than the small annoyances coming from missing or lost functions.

Best regards

**Comment by shleeable** [comment] 2021-11-06 06:13
https://social.chinwag.org/@mike/107228619980101093

**Comment by rscmbbng** [comment] 2021-11-13 21:25
I'm just going to chime in with the others that miss this functionality. This was a really handy feature for our invite only server. When new people join, the admin & mod team immediately gets notified and can welcome people and give them some tips to get newcomers going. Some form of notification (in the notifications timeline) of someone joining the instance would thus be very welcome.

**Comment by Gargron** [comment] 2021-11-13 22:18
WIP #16953

**Comment by joenepraat** [comment] 2021-11-13 22:24
Interesting and yes also needed, but it's not a fix for this regression. Please read my original comment.

**Comment by rebelga** [comment] 2021-11-13 22:37
Agree.  Tracking new users is easily done by monitoring the administration page, but this is nice.  It does not address the main problem.  There is no work around for new users getting default follows (which they always could later opt-out once they knew what they were doing).  Using default follows or not should be up to the administrator.

**Comment by Gargron** [comment] 2021-11-13 22:39
For @shleeable and @rscmbbng the main desire is to be notified of new sign-ups. This does not require new users to auto-follow admins, only for a different notification type.

For following server updates or knowing who the mods are, you can still use the old setting to pin staff accounts at the top of the suggestions on the onboarding screen.

If the user is a real person and and the bio of the staff accounts explains why you might want to follow them, I believe they will follow the same accounts.

**Closed** 2022-02-23 15:45 UTC
Labels: bug

**Comment by shleeable** [comment] 2022-02-24 02:28
Thank you.
