### ISSUE TITLE
Merge LaTeX support from mathstodon

### ISSUE THREAD

**Issue by attilakinali** [mastodon/mastodon#23464] opened 2023-02-08 18:30 UTC
### Pitch

Christian over at mathstodon (@christianp@mathstodon.xyz) added LaTeX support for mastodon, which allows proper rendering of formulas through mathjax, which can be found in his [mastodon fork](https://github.com/christianp/mastodon/tree/mathstodon-4.0.2).

Would it be possible to integrate these changes into mastodon, so that all instances would correctly render LaTeX formulas without the need of running an unofficial fork? 

### Motivation

This would make discussing technical topics in physics and engineering, where formulas are common more accessible to a broader audience. Especially when discussing with lay-people, having a short formula makes things easier to convey. Unfortunately, if their instance doesn't use Christian's fork, they will get raw LaTeX code, which is just gibberish for mere mortals.

**Comment by nightpool** [comment] 2023-02-09 03:56
dupe of https://github.com/mastodon/mastodon/issues/19806

**Closed by nightpool** 2023-02-09 03:56 UTC
Labels: suggestion
