### ISSUE TITLE
Add support for GPG (end-to-end encryption etc.)

### ISSUE THREAD

**Issue by mattholy** [mastodon/mastodon#29468] opened 2024-03-01 09:20 UTC
### Pitch

- End-to-end encrypted DMs using GPG. Optional of course。
- Sign up and login using GPG.
- Sign toots.

### Motivation

Since gpg proven the identity, and provide a solution for encryption and sign. Maybe we should take an advantage of this.

**Comment by trwnh** [comment] 2024-03-01 13:09
Duplicate of #928

**Closed by trwnh** 2024-03-01 13:09 UTC
Labels: suggestion
