### ISSUE TITLE
Allow login/signup with Google oauth

### ISSUE THREAD

**Issue by tiagorangel2011** [mastodon/mastodon#22792] opened 2022-12-27 15:42 UTC
### Pitch

One of the main benefits of this is the ability to easily sign up and log in to Mastodon using an existing Google or Microsoft account. This can make the process of joining Mastodon faster and more convenient for users, as they don't have to create a new account or remember another username and password.

In addition to improving the user experience, adding Google or Microsoft OAuth can also help Mastodon grow its user base. Many people already have a Google or Microsoft account and may be more likely to join Mastodon if they can use their existing account to log in. This can help Mastodon attract more users and increase its overall reach.

Another benefit of adding Google or Microsoft OAuth is the added security it provides. By using OAuth, Mastodon can rely on the security measures implemented by Google and Microsoft, rather than having to develop its own authentication system. This can help protect user data and ensure that only authorized users have access to the platform.

### Motivation

* _Why do you think this feature is needed?_
  It would be awesome to have Google/Microsoft OAuth, it would simplify login a lot
* _Who would benefit from it?_ Basically anyone who prefers passwordless auth.

**Comment by rbairwell** [comment] 2022-12-27 19:27
This does already exist in the code base ( https://github.com/mastodon/mastodon/pull/16221 linked from https://docs.joinmastodon.org/admin/optional/sso/ ) and whilst I have no knowledge of internal Mastodon decisions, I can speculate as to why this hasn't been made "default" (my experience: 20yrs+ of building login systems and supporting Oauth/SSO) 

1. Which services should be supported? Whilst oAuth is "a standard", each implementor has slightly different configurations and will need individual endpoint urls setup. If you just do Google, Microsoft users will complain, if you do those then Facebook users will want it, and then LinkedIn users...And offering too many possibilites leads to confusion.
2. Migration issues. How do you handle, say, Yahoo shutting down their oAuth endpoint and migrating users to another system (especially if they fail to login during the shutdown period)
3. Centralization. A key "ethos" point of Mastodon is that it is independent and each server can run entirely on its own. Having a dependency on a "big corp" breaks this in many ways.
4. Support. "I've forgotten my password" is one major support request, but then finding out which third party service a user used and then telling them to use that password reset system is a world of pain.

So, whilst in principle, it sounds like a good idea - in practical terms it only really works for "closed environments" (such as if Google wanted to run their own instance for their own staff: no need for any oher login systems).

If Mastodon wanted to go down the "reduce password usage" route (which, to be honest, isn't much of a pain point if you use a password manager witt autofill), then supporting something "open" with no external dependencies such as Web-Authn/"Apple Passkeys" would be the way - but the familiarity of these haven't filtered to the general populace yet (I've been using it for over 5 years...)

**Comment by arheh** [comment] 2022-12-28 15:37
I had this working on my instance and was great for existing accounts. The issue and why I had to disable it is new accounts can’t choose usernames so any newly created accounts end up with a random string of numbers for their username. When tagging someone in a post you’d need to use @1004848584 which useful.

**Comment by rbairwell** [comment] 2022-12-28 15:49
I know it must be possible as https://toot.thoughtworks.com/about and https://glauca.space/about both support SSO/SAML/OAuth with normal looking usernames (ok admittedly not Google oAuth: looking at the code and Google'd documentation it seems the users username isn't sent across by default: ah, the joys of SSO incompatibilities)

**Comment by ThisIsMissEm** [comment] 2024-07-30 18:50
> I had this working on my instance and was great for existing accounts. The issue and why I had to disable it is new accounts can’t choose usernames so any newly created accounts end up with a random string of numbers for their username. When tagging someone in a post you’d need to use @1004848584 which isn’t useful :(

I'm looking into a fix for this via #21296, as such, I'd consider this a duplicate of that issue and recommend closing this issue.

**Closed** 2024-08-01 19:13 UTC
Labels: suggestion
