### ISSUE TITLE
Floating profile data

### ISSUE THREAD

**Issue by robsonsobral** [mastodon/mastodon#21678] opened 2022-11-26 16:41 UTC
### Pitch

Hi! Could we have a floating panel with users info and a "Follow" button on it which would appear on hovering links to profiles?

Some examples follows.

From Twitter:
![image](https://user-images.githubusercontent.com/931642/204099084-044b2f2a-8ca9-4aa2-bb95-be0a25ef8352.png)

From Instagram:
![image](https://user-images.githubusercontent.com/931642/204099112-0c3d77b6-c24a-4c07-b7ef-7bf336af7d93.png)

From Github:
![image](https://user-images.githubusercontent.com/931642/204099126-59822669-c2db-4cd6-8277-6950f6d0bb73.png)

### Motivation

A lot of times I found some people worthing to follow, but I have to move away from the timeline for it.

I'm a VueJS dev, but I could try to find my way over React to help.

**Comment by trwnh** [comment] 2022-11-26 16:50
Duplicate of #14918

**Closed** 2022-11-26 16:55 UTC
Labels: suggestion
