### ISSUE TITLE
Open activitypub links inside current instance rather than in a new tab

### ISSUE THREAD

**Issue by rekcuFniarB** [mastodon/mastodon#24035] opened 2023-03-08 17:02 UTC
### Pitch

When user posts a link, mastodon could check if it refers to an activitypub object (sush as a note) on external activitypub instance (mastodon, pleroma, e.t.c.) and when visitors click such links, fetch and display them inside current instance rather than in a new tab on external instance.

### Motivation

Example:

I'm viewing a post on mastodon.social  which contains a link  to  external post like https://mastodon.online/@username/1234567
If I click that link, it will be opened in a new tab on mastodon.online.
Instead it would be more convenient if current instance (mastodon.social) fetches that link if it's an activitypub object and displays inside current instance just like it does for federated posts explored via search function or global timeline.

**Comment by FediVideos** [comment] 2023-03-08 20:59
Yes, this would be fantastic! Would save a lot of bother and prevent a lot of confusion.

**Comment by shleeable** [comment] 2023-03-09 07:33
This is apparently a harder problem than it seems.. the devs have discussed it, hopefully they fix it.

**Comment by trwnh** [comment] 2023-03-09 08:07
Duplicate of #1399

**Closed** 2023-05-19 06:03 UTC
Labels: suggestion
