### ISSUE TITLE
tootctl account create fails on Mastodon 4.0.2

### ISSUE THREAD

**Issue by suky57** [mastodon/mastodon#21626] opened 2022-11-25 17:14 UTC
### Steps to reproduce the problem

```
mastodon@8f5d3a564e2a:~/bin$ ./tootctl account create martin --email martin@sukany.cz --confirmed --role Owner
Failure/Error: email
    does not seem to exist
```

### Expected behaviour

account to be created

### Actual behaviour

``` mastodon@8f5d3a564e2a:~/bin$ ./tootctl account create martin --email martin@sukany.cz --confirmed --role Owner Failure/Error: email     does not seem to exist ```

### Specifications

Mastodon 4.0.2 running in docker:

**docker-compose.yml:**
```
version: '3'

services:
  postgresql:
    image: postgres:14
    env_file: database.env
    restart: always
    shm_size: 256mb
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - internal_network

#  pgbouncer:
#    image: edoburu/pgbouncer:1.12.0
#    env_file: database.env
#    depends_on:
#      - postgresql
#    healthcheck:
#      test: ['CMD', 'pg_isready', '-h', 'localhost']
#    networks:
#      - internal_network

  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - redis:/data
    networks:
      - internal_network

  redis-volatile:
    image: redis:7
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    networks:
      - internal_network

  elasticsearch:
    image: elasticsearch:7.17.3
    restart: always
    env_file: database.env
    environment:
      - cluster.name=elasticsearch-mastodon
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ingest.geoip.downloader.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "nc -z elasticsearch 9200"]
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - internal_network

  website:
    image: tootsuite/mastodon:v4.0.2
    env_file: 
      - application.env
      - database.env
    command: bash -c "bundle exec rails s -p 3000"
    restart: always    
    depends_on:
      - postgresql
#      - pgbouncer
      - redis
      - redis-volatile
      - elasticsearch
    ports:
      - '127.0.0.1:3000:3000'
    networks:
      - internal_network
      - external_network
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    volumes:
      - uploads:/mastodon/public/system

  shell:
    image: tootsuite/mastodon:v4.0.2
    env_file: 
      - application.env
      - database.env
    command: /bin/bash 
    restart: "no"
    networks:
      - internal_network
      - external_network
    volumes:
      - uploads:/mastodon/public/system

  streaming:
    image: tootsuite/mastodon:v4.0.2
    env_file: 
      - application.env
      - database.env
    command: node ./streaming
    restart: always
    depends_on:
      - postgresql
#      - pgbouncer
      - redis
      - redis-volatile
      - elasticsearch
    ports:
      - '127.0.0.1:4000:4000'
    networks:
      - internal_network
      - external_network
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']

  sidekiq:
    image: tootsuite/mastodon:v4.0.2
    env_file: 
      - application.env
      - database.env
    command: bundle exec sidekiq
    restart: always
    depends_on:
      - postgresql
#      - pgbouncer
      - redis
      - redis-volatile
      - website
    networks:
      - internal_network
      - external_network
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]
    volumes:
      - uploads:/mastodon/public/system

networks:
  external_network:
  internal_network:
    internal: true

volumes:
  postgresql:
    driver_opts:
      type: none
      device: /opt/mastodon/database/postgresql
      o: bind    
  redis:
    driver_opts:
      type: none
      device: /opt/mastodon/database/redis
      o: bind    
  elasticsearch:
    driver_opts:
      type: none
      device: /opt/mastodon/database/elasticsearch
      o: bind    
  uploads:
    driver_opts:
      type: none
      device: /opt/mastodon/web/system
      o: bind 
```

**application.conf**:

```
# environment
RAILS_ENV=production
NODE_ENV=production

# domain
LOCAL_DOMAIN=mastodon.sukany.cz

# redirect to the first profile
SINGLE_USER_MODE=true

# do not serve static files
RAILS_SERVE_STATIC_FILES=false

# concurrency
WEB_CONCURRENCY=2
MAX_THREADS=5

# pgbouncer
#PREPARED_STATEMENTS=false

# locale
DEFAULT_LOCALE=en

# email, not used
SMTP_SERVER=localhost
SMTP_PORT=587
SMTP_FROM_ADDRESS=notifications@example.org

# secrets
SECRET_KEY_BASE=key-here
OTP_SECRET=secret-here

VAPID_PRIVATE_KEY=key-here
VAPID_PUBLIC_KEY=key-here
```

**Comment by ineffyble** [comment] 2022-11-26 13:10
Similar issue to one mentioned on #15850. The issue is that Mastodon is trying to verify that `martin@sukany.cz` is a genuine email address, and for some reason it is unable to in this case.

**Comment by demaniak** [comment] 2022-12-02 09:12
I have the exact same issue.

The truly strange thing is - running that exact same compose locally, it works fine.

Is there any information on HOW mastodon performs the email verification?  
Does it, for example, try to connect to the email service?

**Comment by demaniak** [comment] 2022-12-02 09:16
The mentioned ticket (#15850 ) seems to explain exactly what is going wrong (It's always DNS).
It also explains why it works perfectly fine when running locally, but then fails when I deploy to server (where the mail domain is also actually hosted).

**Comment by vmstan** [comment] 2023-11-16 15:59
Closed as duplicate.

**Closed by vmstan** 2023-11-16 15:59 UTC
Labels: bug
