### ISSUE TITLE
Not possible to send direct messages 

### ISSUE THREAD

**Issue by olemara** [mastodon/mastodon#27232] opened 2023-10-01 16:02 UTC
### Steps to reproduce the problem

1. Installed Mastodon from
2. Create users
3. Try sending direct message to another user
4. Check to see if the message appears under "direct messages", check whether the user that should have received the message gets notified.
...

### Expected behaviour

A direct message should have appeared

### Actual behaviour

No direct message appears. But just as a post.

### Mastodon instance

local

### Mastodon version

v4.0

### Browser name and version

Multiple Firefox, and Chrome

### Operating system

Both linux and windows.

### Technical details

I have tried this both using the UI, and the API:

Sending the following request to another instance that was installed long ago (same version) works as expected:

https://{{mastodon_url}}/api/v1/statuses

{
    "spoiler_text":"postman spoiler_text",
    "status":"postman status @abc_3_serpentine",
    "visibility":"direct"
}

But not to the instance I just installed.

The logs show me that a request is being made, and answered with 200 OK. No error messages are to be found. Also checking the actual request being sent from the front-end is answered with 200 OK.

Please advice if more information is needed, and some guide to debug this properly.

**Comment by olemara** [comment] 2023-10-02 07:08
Same thing happening with v4.0.7, v4.0.11, and v4.0.1.

Clearing all client side data when testing of course.

**Comment by ClearlyClaire** [comment] 2023-10-02 09:49
Closing as a duplicate of #27243

**Closed by ClearlyClaire** 2023-10-02 09:49 UTC
Labels: bug, status/to triage, area/web interface
