### ISSUE TITLE
Change appearance (dark/light mode) with OS

### ISSUE THREAD

**Issue by Ein-Tim** [mastodon/mastodon#20867] opened 2022-11-16 11:14 UTC
## Pitch

Mastodon should offer the user to change the appearance of the UI with the appearance (dark/light mode) of the operating system of the device. Twitter, GitHub, YouTube and many other platforms already support this.

### Why do you think this feature is needed?

I think this feature is needed to give users more customization options and satisfy their needs.

### Who would benefit from it?

Users, who want to use light theme on Mastodon when their OS is in light theme and vice versa, would benefit from this feature.

I searched with the keywords "system" & "appearance", but did not find another open issue for this.

**Comment by ineffyble** [comment] 2022-11-16 12:05
I could have sworn this was already implemented but I'm mistaken, we only have an option for default system _font_.

**Comment by ClearlyClaire** [comment] 2022-11-21 09:16
This is a duplicate of #10976

**Closed by ClearlyClaire** 2022-11-21 09:16 UTC
Labels: ui, suggestion
