### ISSUE TITLE
Buttons on right side of video player don't work in embeds

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#25045] opened 2023-05-20 15:29 UTC
### Steps to reproduce the problem

Somebody [links me a post on toot.cat containing a video](https://mastodon.social/@ehashman@toot.cat/110399239902881231). It looks like this in the notifications column:

![image](https://github.com/mastodon/mastodon/assets/277318/1083b62d-f8df-48d7-b0e7-a614803ba930)

I click the play button and I get a little video player like the normal one:

![image](https://github.com/mastodon/mastodon/assets/277318/826b86c2-6e85-43ac-9b7b-74bab53535aa)

I can play the video fine. However "Full Screen" and "Expand Video" on the right there do not work. Clicking "full screen" has no effect and this appears in the Javascript console.

```
fullscreen.js:20 Uncaught (in promise) TypeError: Disallowed by permissions policy
    at r (fullscreen.js:20:8)
    at toggleFullscreen (index.jsx:372:7)
    at Object.l (react-dom.production.min.js:26:7)
    at p (react-dom.production.min.js:44:6)
    at react-dom.production.min.js:47:6
    at b (react-dom.production.min.js:63:3)
    at lt (react-dom.production.min.js:763:91)
    at ot (react-dom.production.min.js:756:47)
    at ft (react-dom.production.min.js:774:5)
    at mt (react-dom.production.min.js:845:5)
```

Clicking "expand video" actually blanks out the video fully, it just becomes an non-interactive black box, and this prints in the console:

```
react-dom.production.min.js:2336 Uncaught TypeError: Cannot read properties of null (reading 'store')
    at m (connectAdvanced.js:221:70)
    at Yo (react-dom.production.min.js:2996:7)
    at Ii (react-dom.production.min.js:3540:7)
    at Mi (react-dom.production.min.js:3530:141)
    at Ri (react-dom.production.min.js:3515:155)
    at kl (react-dom.production.min.js:5566:72)
    at yf (react-dom.production.min.js:5035:11)
    at gf (react-dom.production.min.js:5029:27)
    at ff (react-dom.production.min.js:4815:7)
    at react-dom.production.min.js:2331:18
```

I don't see these problems in a "toot" that appears [inline in the Home column](https://mastodon.social/@halcy@icosahedron.website/110400472592114525).

I am seeing this on mastodon.social, which is running v4.1.2+nightly-20230517. Toot.cat is running v4.1.2+glitch so I assume it is fairly close to m.s's code, although it's possible this is a glitch specific problem and I should be filing on mastodon+glitch. I have been trying to replicate whatever it was this particular post did to force an opengraph embed with a mastodon.social post and not succeeding, I think in order for that opengraph video to appear the "toot" has to be served from a domain other than the one you're viewing at. It would be interesting to @ a [mastodon.social post to a toot.cat user](https://mastodon.social/@mcc_test_tusky/109882854440026258) and see if it's symmetric.

I am running Chrome 113.0.5672.93 64-bit on Windows 10, I use advanced mode, and I usually run some browser extensions but I turned them off for this test.

### Expected behaviour

If buttons don't work, they shouldn't be displayed. However because in advanced mode embeds appear kinda small it *would* be nice if opengraph videos could fullscreen or lightbox.

**Comment by ClearlyClaire** [comment] 2023-05-22 09:49
There seem to be two issues:
- the iframe not being allowed to go full-screen: this should be addressed by https://github.com/mastodon/mastodon/pull/25058
- the lightbox control being presented even though lightboxing is not possible (and crash itself seems to be a recent regression)

**Closed** 2023-05-23 12:28 UTC
Labels: bug
