### ISSUE TITLE
"In Case You Missed It" feature

### ISSUE THREAD

**Issue by saschanaz** [mastodon/mastodon#18352] opened 2022-05-07 20:46 UTC
### Pitch

Provide suggestions from *the existing followings* (not from random popular accounts) so that users can discover what they missed.

### Motivation

The current real-time timeline is good for interacting with friends who are active exactly when I'm active, but it's bad for interacting with people who aren't as active as others or people who just are in a different timezone.

Such "algorithmlessness" guides me to interact with same friends I've always been interacting with, while less-active friends get less interactions, feel boring, and eventually leave the fediverse, because Mastodon gives very short time for their posts to be discovered and I can't be in Mastodon 24hrs a day.

This is not what I want, when I follow N people it means I want the contents from those N people equally. Certain accounts being super active should not fill my timeline all over with their posts and give others less chances.

PS: This is different from #3782 or #15981 that this is about unpopular posts, not already popular ones.

**Comment by DarckCrystale** [comment] 2022-05-12 18:29
As a short term fix, may I suggest to use lists to group together account with a smaller posting rate?

**Comment by trwnh** [comment] 2023-05-20 20:22
Duplicate of #8518

**Closed by trwnh** 2023-05-20 20:22 UTC
Labels: suggestion
