### ISSUE TITLE
Add a "Hashtag" form in toots

### ISSUE THREAD

**Issue by matteoscopel** [mastodon/mastodon#20398] opened 2022-11-11 09:19 UTC
# Premise

Currently, like on other platforms, hashtags are extrapolated from the content of a post. For example, if I post the following toot:

`Hello #World`

My toot would be discoverable under the #World hashtag.

# Proposal

My proposal is that a dedicated "hashtag" form is added when posting toots. Inside such form, separated by commas, each hashtag would be inserted.

# Benefits of this proposal

I believe this proposal could bring three important benefits which could improve Mastodon as a whole:

- users relying on screen readers would have a less jarring experience. A screen reader reads "#" as "hashtag", which is evidently a break in the text flow.
- it would not count against the 500 characters count limit. In this way, those 500 characters could be spent on actually meaningful content, and not hashtags, improving the quality of the conversation.
- it would allow good discovery of posts. By having posts that use all 500 characters for content, but at the same time can be indexed and discovered easily using hashtags, it could be easier for users to find relevant content and for authors to have their content reach their audience.

# Design details

- the button to open this form, which would be optional, could be next to the CW one and feature a simple # logo.
- **_its use wouldn't be mandatory_**. Hashtags inside posts could still be indexed, in order not to disrupt things.

# Conclusion

I strongly believe this proposal could benefit the whole community, increasing at the same time accessibility, conversation quality, and discovery functionality.

**Comment by ineffyble** [comment] 2022-11-11 09:53
Sounds similar to how Tumblr tags work, and how Cohost implemented tags (see below)

<img width="825" alt="image" src="https://user-images.githubusercontent.com/834880/201314537-c86f164e-e021-4981-b409-3e6519e85c49.png">

There are some advantages to having tags as separate field (although I wouldn't suggest they should replace hashtags, just supplement). One of them being the ability to have spaces and other special characters in the tag.

**Comment by matteoscopel** [comment] 2022-11-11 10:04
> although I wouldn't suggest they should replace hashtags, just supplement

Definitely agree! I think that by supplementing the current system, compatibility with the current system would be preserved and the transition from other microblogging platforms wouldn't be counterintuitive. Moreover, I'm sure that the discoverability and extra characters available would ensure that most people would switch to the hashtag form pretty soon.

**Comment by MBeggiato** [comment] 2022-11-11 10:16
The current system feels more natural. In my opinion, it boosts the usage of hashtags in a real context.

**Comment by MarkBTomlinson** [comment] 2022-11-11 10:41
I saw this mentioned on the art instance along with a sound reason for doing it. If there are too many #tags in the content, it can become messy for the people using screen-readers, as HASHTAG is sound every time it is found.
Seperating them would allow the text to be read more fluidly and be less jarring.

**Comment by matteoscopel** [comment] 2022-11-11 10:43
@MBeggiato 

> The current system feels more natural. In my opinion, it boosts the usage of hashtags in a real context.

I see your point, but:

1. the proposal is to not remove the current system, but to supplement it.
2. in general, we perceive as natural what we are used to. Also see the point about screen readers: while it could be perceived as "more natural" by some, the current system is arguably a disruption for users who rely on screen readers, and in general Mastodon is a really accessible software.

But in any case, it is not my intention to start a debate over what is natural or not. I really want to stress, though, that **my proposal is to keep hashtags working in posts, and to supplement it with a hashtag field** (the screenshot from cohost posted above is an example of a possible design). And, of course, I'm not a developer, so the IF and HOW of how this would be designed and implemented is absolutely beyond this mere proposal :D

**Comment by StudioPetrikas** [comment] 2022-11-11 11:20
Sounds lovely. 

Hashtags, essentially, are metadata. Having them separated from human-readable text would be ideal. 
This would open up an ability to have hash-tags auto-hide, or show-on-click.

Using them "in-context" on Mastodon is pointless, as there's no algorithms that differentiate between in-context hashtags and separate hashtags. It just makes reading harder, finding topics more difficult, and writing unnatural.

**Comment by erbridge** [comment] 2022-11-11 14:07
Is there a different solution to the problem here. The issue expressed is that screen readers vocalise `#thing` as "hashtag thing". We could tell them to say something different or not announce the "hashtag" part at all, if the problem is the amount of disruption created by the announcement. I'm not saying that's the right solution, but it worth considering the problem itself without jumping to conclusions about how to solve it, I think.

**Comment by trwnh** [comment] 2022-11-11 16:04
Duplicate of #10743

**Comment by trwnh** [comment] 2023-05-14 08:57
Duplicate of #10743

**Closed by trwnh** 2023-05-14 08:57 UTC
Labels: suggestion
