### ISSUE TITLE
add activitystreams rel=alternate to tag pages

### ISSUE THREAD

**Issue by kidehen** [mastodon/mastodon#23174] opened 2023-01-20 19:41 UTC
### Pitch

Given the URL `https://mastodon.social/tags/csv` that denote an HTML document about the CSV hashtag and `https://mastodon.social/tags/csv.json` that denotes an ActivityStreams JSON document about the same hashtag, it would be beneficial to include the following in Mastodon's HTML pages.

```
<head>
<link rel="alternate" href="https://mastodon.social/tags/csv.json" type="application/activity+json" />
</head>  
```

### Motivation

User-agent discovery of an associated JSON document, using existing discovery patterns i.e., what's broadly used for RSS and Atom feeds.

**Comment by melroyvandenberg** [comment] 2023-01-24 14:53
Hm. Do you have an example of this might be used by a RSS feed reader? I don't see the full picture yet.

**Comment by nightpool** [comment] 2023-01-24 15:08
duplicate of #22340 by the same user.

@kidehen please refrain from opening new tickets for issues you have already reported.

**Closed by nightpool** 2023-01-24 15:08 UTC
Labels: suggestion

**Comment by kidehen** [comment] 2023-01-24 15:23
> duplicate of #22340 by the same user.
> 
> @kidehen please refrain from opening new tickets for issues you have already reported.

Why on earth are you assuming that this is done deliberately?
