### ISSUE TITLE
option to follow hashtags

### ISSUE THREAD

**Issue by donnerkarlson** [mastodon/mastodon#1096] opened 2017-04-06 19:45 UTC
I did not find an option to follow hashtags, that would be a nice feature.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by thomaskuntzz** [comment] 2017-04-15 14:39
Yeah, that would be great! :+1:

**Comment by rikmendes** [comment] 2017-04-22 12:56
that would be awesome !

**Comment by diegogangl** [comment] 2017-04-22 22:25
This would be totally awesome. It would be great if we could have these "hashtag timelines" in separate columns too, so we can stay on top of them.
Either that or have them on the third column list with a badge showing the number of unread toots.

**Comment by thiagomgd** [comment] 2017-09-17 17:50
I agree with it!
Tumblr has (or used to have) this feature, and it was nice being able to have some tags ready to click and check.

**Comment by zcdunn** [comment] 2017-09-18 14:29
I think a better solution would be supporting GNU Social !groups

**Comment by thiagomgd** [comment] 2017-09-18 14:48
@zcdunn !groups are a nice solution to... groups. But following hashtags (at least on tumblr) are used to another goal

**Comment by zcdunn** [comment] 2017-09-18 15:16
If I understand correctly, the point of groups was to allow users to follow topics, which is your goal with following hashtags. Your instance won't see every post with a hashtag, so following a hashtag wouldn't give you a complete view. I thought groups were designed specifically to address the request to follow hashtags

**Comment by thiagomgd** [comment] 2017-09-18 15:42
@zcdunn you're the first to mention groups on this issue. The point of following hashtags is to... follow hashtags. 

> Your instance won't see every post with a hashtag, so following a hashtag wouldn't give you a complete view.

So, according to your view, we can just remove the search from Mastodon, as we can only search hashtags, and the search wouldn't give us a complete view? What we (I, and the OP) want, is to follow a hashtag, maybe even having a counter (new posts since last view) on the side of it, and maybe notifications.

Tumblr example:
After searching
![image](https://user-images.githubusercontent.com/12170252/30550510-065399f0-9c6e-11e7-95e5-8a9904768f44.png)

After following, when I click the search bar, it auto-suggests the tag. It used to show the number of new posts, but I don't know if they removed that, or if it doesn't work with tags with a massive amount of posts, because it's been years since I've used tumblr.
![image](https://user-images.githubusercontent.com/12170252/30550704-a2e6b48c-9c6e-11e7-9fa2-728ef3169688.png)

After clicking on it again:
![image](https://user-images.githubusercontent.com/12170252/30550727-b54ace56-9c6e-11e7-81d4-eb7436222015.png)

Also, check @diegogangl's suggestion earlier on this post

**Comment by Cassolotl** [comment] 2017-09-18 15:58
>we can just remove the search from Mastodon, as we can only search hashtags

(The search looks for people by username or instance and toots by URL as well.)

**Comment by zcdunn** [comment] 2017-09-18 16:52
> you're the first to mention groups on this issue. The point of following hashtags is to... follow hashtags.

This issue isn't the first time this feature has been brought up. Groups were implemented in GNU Social to address this request.

> What we (I, and the OP) want, is to follow a hashtag, maybe even having a counter (new posts since last view) on the side of it, and maybe notifications

That's exactly what groups provide, but instead of following #topic you would follow !topic.

**Comment by thiagomgd** [comment] 2017-09-18 20:06
@zcdunn never used GNU Social, but looking [here](https://gnusocial.net/doc/groups), seems that it's not what we want. Also, if it as what we wanted, it would be a big naming problem, just confusing everyone. Let's see my considerations.

> You can send a message to a group using the syntax "!groupname" 

So you'll block people from using `#mastodon` and force everyone to use `!mastodon` instead? Also, it says here you can 'send a message to a group', but we are talking about regular posts, like `I love #mastodon, it's nice being here`

> You can join a group by clicking on the "Join" button either in the group list 

Ok, but you can set the privacy so no one can see if you are following the tag/are in the group?

> When choosing the nickname for your group, try to keep it short.

So, if I'm faster than the others, and create !book, which is a private group now, no one will be able to follow the tag #book? (still not understanding how this works to FOLLOW A TAG)
Also, it'll be boring having to create a !something manually for every tag ever used in an instance

> New group messages will appear in your inbox,

That's not what we want. I don't want everything with #book in my inbox (or, if we completely forbid the use of # and replaces it with !, !book)

So, I think that now you'll be able to understand that we are NOT talking about groups, but about FOLLOWING A TAG.

-----------------------

@Cassolotl it was sarcasm :D

**Comment by Phyks** [comment] 2017-09-18 20:20
Just to add up a bit on this, and commenting on my use case. I am watching a couple of tags right now, be they group-like (see `#weeklyphotochallenge` for instance) or about softwares I am contributing to (as people tend to ask question using `#NameOfTheSoftware`, rather than `@OfficialAccountOfTheSoftware`). First use case seems to be matching the group use case, but not the second one.

For now, my solution is to "pin" panels with all these different tags, but my homescreen is just getting wider and wider and less and less usable. I would love to be able to follow these tags, so that all these messages would end in the timeline, mixed with peoples I follow.

**Comment by zcdunn** [comment] 2017-09-18 21:18
> Also, it says here you can 'send a message to a group', but we are talking about regular posts, like I love #mastodon, it's nice being here

_I love !mastodon, it's nice being here_ is a regular post and anybody subscribed to !mastodon would see it in their home timeline.

> Ok, but you can set the privacy so no one can see if you are following the tag/are in the group?

I don't know if other GNU Social servers do that, but I'm sure the Mastodon implementation could add that.

> That's not what we want. I don't want everything with #book in my inbox

Following a user puts all of their posts in your home timeline. Why would following a hastag/group be any different? 

You seem to be getting a little upset with this conversation so I'll end with this. I don't have any stake in groups or hashtags. But if we want the ability to follow a topic, I think it makes sense to use the feature that is already available and in use elsewhere, instead of creating something that wouldn't interact well with the rest of the fediverse. The UX would be slightly different from what you imagine, but I don't see that as being a huge drawback.

**Comment by Cassolotl** [comment] 2017-09-18 23:36
@thiagomgd 

>@Cassolotl it was sarcasm :D

Oh thanks! :P Oops.

I tried GNU Social for a little while. Posts in `!groups` appeared in the timeline, and it was pretty cool. As far as I can tell, the `!` showed that it was in your timeline because you were in a group; you could send something to `!mastodon` *and* tag it `#mastodon` if you wanted to.

The main difference was that someone on an instance would make the group and then they could have the power to admit people to the group or keep them out. If the person left the instance, the group would become neglected because the admin wasn't there to hand over ownership.

Plus, someone could make another group with the same name on another instance, which just made things extremely confusing. At least one hashtag is the same hashtag across all instances, you know?

So personally I do not like the GNU Social group concept, and would much rather follow hashtags, which are less exclusive and tend to shift and change with the people using it.

Maybe a symbol in the toot to say "this is here in your home timeline because you follow this hashtag" might be nice?

**Comment by thiagomgd** [comment] 2017-09-19 01:04
@zcdunn didn't mean to be rude or offend in any way, so, sorry about that :)

-----------------------------------

@Cassolotl 
> Maybe a symbol in the toot to say "this is here in your home timeline because you follow this hashtag" 
Yes, that would be nice. Like Twitter shows a post a say 'Cassolot liked this' on top of it. Although I really hate that I can't turn that off.

I have I few ideas how that could work (with or without putting posts on the timeline). I guess I'll try to edit something on paint (or using chrome's devtools) to illustrate when I have some time :)

**Comment by rory** [comment] 2017-09-19 12:45
Groups might be a good idea, technically, but people now-a-days are using hashtags the way they would use hashtags. Maybe it would be better if everyone used groups, but since people are using hashtags in this way, why not implement "follow hashtag" as a way to implement "groups" as they are currently used? Pave the goatpaths and all that.

**Comment by Cassolotl** [comment] 2017-12-29 16:02
I just wanted to pop in and say that being able to pin hashtags is really cool, but there are a LOT of hashtags I'd like to keep up with, and I don't have the biggest screen ever, so I'd much rather they be booped into my home feed instead!

**Comment by kpcyrd** [comment] 2018-01-02 22:33
Adding hashtags to lists might be a good idea. That way I could create a list with a couple of hashtags and create a pinned column for a specific topic (that doesn't have a common hashtag).

**Comment by Cassolotl** [comment] 2018-02-26 21:50
*Ability to subscribe or follow tags #945* exists and is one day older. Since we can now pin hashtag search columns, maybe this one can be closed as a duplicate of #945?

**Comment by rikmendes** [comment] 2018-02-28 11:59
Agree, great job with hashtags! From mobile On Feb 26, 2018 10:51 PM, Cassolotl <notifications@github.com> wrote:Ability to subscribe or follow tags #945 exists and is one day older. Since we can now pin hashtag search columns, maybe this one can be closed as a duplicate of #945?

**Comment by Cassolotl** [comment] 2018-04-16 10:51
Just spotted this on Instagram today:

![insta](https://user-images.githubusercontent.com/6607512/38805071-75f47754-416c-11e8-8bc5-1bdd5444dc2c.jpg)

**Comment by woj-tek** [comment] 2018-08-02 07:50
Subscribing to hashtags would be awesome. There is a question of the subset:
* only user hashtags (#7988): `#hashtag-to-follow@user@server` (comming from most narrow to less narrow)
* only hashtags from local timeline: `#hashtag-to-follow@server`
* all hashtags from fediverse: `#hashtag-to-follow`

**Comment by wottpal** [comment] 2018-08-19 10:16
> Adding hashtags to lists might be a good idea. That way I could create a list with a couple of hashtags and create a pinned column for a specific topic (that doesn't have a common hashtag).

There is already an issue for that https://github.com/tootsuite/mastodon/issues/6359.

Personally seeing https://github.com/tootsuite/mastodon/issues/6359 to be implemented would make following hashtags unnecessary for me.

**Comment by woj-tek** [comment] 2018-08-19 12:04
I'm aware of #6359 but it's slightly different than following hashtags in itself.

**Comment by duven87** [comment] 2018-09-30 20:29
It would be very nice! I miss !groups

**Comment by cyisfor** [comment] 2019-01-15 04:06
> causing any post (in the reachable fediverse) containing that tag to appear in their Home timeline the same way

Thinking of under the hood, there must already be a way to request posts by `@user`, which is effectively a search for that user's posts on an instance, and that's how people follow a user on a different instance. Their instance regularly "searches" for that user's posts on the other instance, and aggregates the search results.

So just having an instance do the same thing, but generalizing that regular search to allow polling regularly for #tags on each instance, that's how I'd do it. Or, actually I'd have a way for instances to add themselves to subscription lists, for `#tags` or `@users`, and when a post is posted, that instance finds its `#tags` and `@users`, and pushes it to any subscribed instances. Probably could even do that recursively, with a TTL...

Biggest problem is spam. Try searching for the [#Portland](https://mstdn.io/tags/portland) tag sometime, you should see what I mean. Any tag search wouldn't work well if it had no way to filter according to who's posting to that tag, to remove opportunistic spammers or other off topic posters. That's not usually a problem if you're following one single user, since most people don't say "Oh well this Friday I'm gonna spam porn ads to all my friends, then Saturday it'll be normal posting again."

**Comment by remram44** [comment] 2019-01-15 15:43
> Thinking of under the hood, there must already be a way to request posts by `@user`, which is effectively a search for that user's posts on an instance, and that's how people follow a user on a different instance. Their instance regularly "searches" for that user's posts on the other instance, and aggregates the search results.

This is not how it works...

**Comment by Bugsbane** [comment] 2019-01-27 12:09
I'm also desperate to be able to follow hashtags. Following groups, well, meh. I wouldn't object to it being there, but the problem is that people have to join the group and specifically choose to post to the group or you won't see the message. This is opposed to just sticking a hashtag in front of a word any time from the very first toot they write, which is a very well known paradigm. Just compare the number of messages using #mastodon, vs !mastodon.

As an aside, Diaspora has hastag following and I used it extensively and loved it. The system in Mastodon of needing whole separate columns for each tag is super ungainly.

**Comment by steinbitglis** [comment] 2019-02-25 17:08
I'm trying to create an instance for a big group (with subgroups) that used to be on FB.

By the looks of it, hashtags could be a sufficient replacement for our subgroups,
except for the fact that there is no way to address them, not even if they opt in.

I think the following is the most compatible feature upgrade that would suffice for us:

- The ability to get notifications based on a tag filter.

Then we could address a "group" by posting to #basics #bunjeejumping.

Finding a good way to make sure every member subscribes in this way would be a different, but related problem.

**Comment by tolstoevsky** [comment] 2019-08-07 18:15
> The ability to get notifications based on a tag filter.
I double that.

**Comment by gueorgui** [comment] 2019-08-07 18:32
Is anyone working on a pull request for this? I would be happy to lend a hand.

**Comment by devurandom** [comment] 2019-10-26 06:42
I am still interested in this feature.

**Comment by tolstoevsky** [comment] 2019-10-26 15:47
+1

**Comment by notanewbie** [comment] 2019-10-30 20:36
+1

**Comment by eherz1** [comment] 2020-06-15 14:41
+1

**Comment by Bugsbane** [comment] 2020-06-27 17:34
Please, enough with the "+1"'s already. Just use the thumbs up emoji reaction so they get collected on 1 thing and don't flood the devs with identical comments. (Just waiting for some joker to reply to this with "+1"...)

**Comment by umonaca** [comment] 2020-07-14 14:40
`fedibird.com` (maintained by @noellabo ) has implemented this feature.

**Comment by noellabo** [comment] 2020-07-14 17:06
Describes the hash tag subscription feature of Fedibird.

This is for public posts delivered to the server, just like the Federation timeline.

Inserts a user-specified hashtag into the home or list timeline.
![follow_hashtag1](https://user-images.githubusercontent.com/28195220/87454888-913aa380-c63f-11ea-9217-cc4c8a9498d1.png)
![follow_hashtag2](https://user-images.githubusercontent.com/28195220/87454895-94ce2a80-c63f-11ea-999b-9ff91ddbc203.png)


Fedibird has integrated features for subscribing to posts other than hashtags, so you'll need to separate this to make a pull request to Mastodon.

If you want to try it as soon as possible, please register at fedibird.com because the source code is not sufficiently prepared to operate as a fork.

Other information:

For sharing hashtag posts between servers, we have a service based on Mastodon's pub-relay that relays only hashtag posts.

We are also working on implementing groups. There are active method based on mention and passive method based on followback. Passive method is effective for distribution of hash tags.

I'm also thinking about how to actively request posts with hashtags between servers, but I'm still not sure if it works.

**Comment by FediVideos** [comment] 2022-01-10 17:39
As has been pointed out elsewhere, this feature does actually already exist in the multicolumn Mastodon interface! Is there no way of bringing this into the default single column interface too?

The multicolumn interface separates followed hashtags into their own column. Perhaps in single column mode followed tags could be merged into the home column?

This is how Friendica implements it, and it works really well. It's very useful for new users who don't know who to follow, and very intuitive.

**Comment by LoveIsGrief** [comment] 2022-01-16 12:09
@FediVideos I can't find it. How do you get it to work? Screenshots would be great.

This is all I see in a column

![afbeelding](https://user-images.githubusercontent.com/2829538/149659329-af701ecc-5426-4eb4-a526-6643fb5886a9.png)

![afbeelding](https://user-images.githubusercontent.com/2829538/149659352-dc97b113-4394-4464-bc7f-22540e72f24f.png)

**Comment by LoveIsGrief** [comment] 2022-01-16 14:02
For others who haven't discovered the multi-column thing that's a **workaround** to this requested feature:

https://user-images.githubusercontent.com/2829538/149663064-dbe41cdd-8872-409b-9ca5-2ba16d0f488d.mp4

In text form:

 - Go to settings > Preferences > Appearance
 - Activate "Advanced Web Interface"
 - Search for a hashtag
 - Open the settings of the new column
 - "Pin" the column with the search results
 - Open the settings of the column again
 - Tick "include additional tags for this column"
 - Fill out the field(s)
 - Close the column settings

Repeat them for as many hashtag groups as you want.

**Comment by thiagomgd** [comment] 2022-02-22 22:46
Yeah, I had created one column for a few hashtags I wanted, since you can add multiple. But since I use the single column, that doesn't help :/

**Comment by mitras2** [comment] 2022-04-30 11:16
I (once again) came from twitter to mastodon an once again i really like it.
But i miss the feature to follow hashtags a lot!

Why does it make such a huge difference?
Because on Twitter most profiles post content about on specific subject (familiy, food, cars, programming, you name it...). On Mastodon profiles and user are far more diverse and personal in their toots (which is a strength in the first place). 
But if i try to get some toots about cargobikes into my timeline, I need to follow quite a lot aof people and it generates quite some overhead of toots that are totaly irrellevant to me. 
So with profiles being less topic-specific on mastodon (and the fediverse in general) I feel like this feature is a must have!

It would be enought to see all the toots with a certain hashtag that reach my instance by any mean (follow, retoot, reply, etc). I think there is no need to collect toots from all over the fediverse by any form of crawler.

I hope this feature has some chance for active development, as right now i spend a lot of time searching for my favourite hashtags every day to see what happend...

**Comment by MirceaKitsune** [comment] 2022-04-30 14:21
I find it interesting there hasn't been any progress on this yet for many years, given how many of us seem to want the feature and it should be rather easy to implement. You already have a home timeline for which the system pulls posts from every account you watch to compile it... couldn't a few lines of code also make it pull all posts from the local / federated timeline if they contain a tag or keyword, ideally ignoring duplicates so you don't see the same post twice if you're also watching that account?

This could be a big win for Mastodon and the fediverse since IIRC Twitter and other platforms don't have such a feature: It's a clean convenience without negative side effects which people could make use of in different ways. It should help folks find content and accounts of interest more easily and improve everyone's experience.

**Comment by ccoenen** [comment] 2022-04-30 15:58
While there has not been any progress on this particular issue, I believe mastodon as a whole has done very worthwhile things over the past five years. That most recent version, for example improved onboarding. A few versions before that, we got to pack up our stuff and move to a new instance (without losing followers).

While I would also find "follow hashtag" interesting, I do believe those in particular were good choices to implement first. Hashtags will also be hard to get right, because in the current state, this could be seen as "I subscribe to #cooking all over the fediverse", but this *would not be true*. One would just see that hashtag in that part of the fediverse that's in some way connected to one's home instance. (probably local timeline and additionally all posts that somehow make it to one's server anyway). So either this will be a tricky thing to get right in the UI, or it will be a tricky thing to get right in the API.

**Comment by Bugsbane** [comment] 2022-06-08 18:37
I agree that onboarding and the ability to moved hosts were higher priorities.

That said, just adding a warning when the user is adding hashtags to a column should adequately manage user expectations about what toots they're going to see. It would also be very simple to implement.

**Closed** 2022-07-17 11:49 UTC
Labels: suggestion
