### ISSUE TITLE
Set new registrations on new servers to manual approval by default

### ISSUE THREAD

**Issue by joenepraat** [mastodon/mastodon#29269] opened 2024-02-18 16:58 UTC
### Pitch

Currently new Mastodon servers have open registrations by default. To make sure new servers are not so fast misused for spam, it is a good idea to set the registrations to manual approval by default. See [this issue](https://github.com/mastodon/mastodon/issues/29270) with a idea how to make open registrations more secure, after admins decide to use open registrations nevertheless. 

### Motivation

The motivation is the current spam attack.

**Comment by trwnh** [comment] 2024-02-19 03:26
Duplicate of #10590

**Closed by trwnh** 2024-02-19 03:26 UTC
Labels: suggestion

**Comment by joenepraat** [comment] 2024-02-19 05:06
> Duplicate of #10590 

That issue is 5 years old, so let's surely hope that this will be implemented much quicker.
