### ISSUE TITLE
Cryptographically signed content

### ISSUE THREAD

**Issue by avidseeker** [mastodon/mastodon#25440] opened 2023-06-14 17:23 UTC
### Pitch

Are there any plans for including signed posts and comments? In a manner similar to Nostr protocol. So far Mastodon only include identity authentication via Keyoxide.

### Motivation

Signing actual posted content will put less trust in the instance server.

**Comment by trwnh** [comment] 2023-06-15 03:09
Duplicate of #928

**Closed by trwnh** 2023-06-15 03:09 UTC
Labels: suggestion
