### ISSUE TITLE
mastodon links should route to a mobile screen, not a web view

### ISSUE THREAD

**Issue by mauzybwy** [mastodon/mastodon#20778] opened 2022-11-15 13:34 UTC
### Pitch

On android, when clicking a link to a mastodon post from within the mastodon app you are currently directed to a web page. Ideally this would jump to a screen in the app itself.

### Motivation

Everybody would benefit, and it would help create a seamless browsing experience.

**Comment by trwnh** [comment] 2022-11-15 14:44
Not strictly related to deeplinking, actually -- I'd say this issue should be reopened as it is a completely different thing. Deeplinking is about opening a link in-app when you are outside the app. This issue is about opening a link in-app when you are already inside the app.

On a technical side, Mastodon could try to fetch each link with ActivityPub, and if so, add a tag similar to mentions/hashtags/emojis. Perhaps this information could be federated as an Object Link as defined in FEP-e232: https://codeberg.org/fediverse/fep/src/branch/main/feps/fep-e232.md // basically add `mediaType` to a `Link` inside `tag`

**Comment by ineffyble** [comment] 2022-11-15 14:47
> This issue is about opening a link in-app when you are already inside the app.

Is it? I interpreted this as opening a link from web browser.

**Comment by mauzybwy** [comment] 2022-11-15 14:49
Apologies for not being clear, I meant clicking a link from within the application itself.

**Comment by trwnh** [comment] 2023-05-19 06:48
Duplicate of #1399 (at least in part; the other part is having the android app implement whatever solution comes out of the linked issue)

**Closed by trwnh** 2023-05-19 06:48 UTC
Labels: suggestion
