### ISSUE TITLE
Display a label on a toot when it comes from a followed hashtag

### ISSUE THREAD

**Issue by MyNameIsTroll** [mastodon/mastodon#24964] opened 2023-05-12 15:41 UTC
### Pitch

Inform users via a label at the top of the toots when it comes from a followed hashtag.

### Motivation

The followed hashtag feature is interesting, but sometimes we don't know why a toot appears in our timeline. Especially if the toot contains many hashtags, which is often the case.

When someone we follow boosts a toot, at the top of the toot appears the mention "boosted by user". On the other hand, when a toot appears in our timeline because we follow a hashtag, nothing indicates to the user why this message appears in our timeline. We could use this same location to display a label when a message appears in our timeline because we follow a hashtag.

It would also be interesting to have the possibility to manage more easily the followed hashtags. For example to delete directly from the list of hashtags with a small trash icon. We could also imagine an icon to pause the followed hashtag. For example, if you want to follow an annual event, elections or other. You could pause it when you are saturated and easily resume the follow later without deleting it. This would centralize and make it easier to manage lists of followed hashtags.

I've created a small example so you can more quickly visualize what I mean.

![Issue_Hashtags_lists](https://github.com/mastodon/mastodon/assets/31790025/5b1b7916-36f8-47d3-babc-d4745f950d72)

**Comment by frandavid100** [comment] 2023-05-13 10:22
Agreed.

**Comment by Cassolotl** [comment] 2023-07-30 15:23
Duplicate of *Show mention of the followed hashtag #19528* (October 2022)

**Closed** 2023-07-31 06:37 UTC
Labels: suggestion
