### ISSUE TITLE
Link preview entity escape

### ISSUE THREAD

**Issue by ellieayla** [mastodon/mastodon#21360] opened 2022-11-21 22:01 UTC
### Steps to reproduce the problem

1. Make a post linking to https://civic.io/2022/11/21/more-writing-less-words/
2. Eg https://mastodon.social/@mheadd/109382146215500268
3. Observe target page title rendered in link preview

### Expected behaviour

Either maintain the non-breaking space or replace with a space character

### Actual behaviour

Link preview contains `&nbsp;` text

### Detailed description

Some entities in post titles are rendered as expanded text instead of either the entity or a similar character.

### Specifications

mastodon 4.0.2

**Comment by ineffyble** [comment] 2022-11-22 05:42
Interesting...

For description there's an entity instead of raw character in the meta tag.

```
<meta property="og:description" content="More posts. Shorter words. It&#8217;s time to leave the bird site and all the bad habits I picked up there behind." />
```

My first instinct was that this is incorrect (since they're not needed in this context), but it seems perfectly valid, and it looks like other open graph parsers (Facebook, Discord) correctly decode the entity.

But this issue was about the title, and that's quite interesting because there's twothreedifferent titles:

```
<title>More Writing, Less Words &#8211; Civic Innovations</title>
<meta property="og:title" content="More Writing, Less Words" />
<meta name="twitter:text:title" content="More Writing, Less&nbsp;Words" />
````

Facebook, of course, uses the Open Graph title and ignores the vanilla HTML one completely. Discord appears to do the same.

Mastodon is using twitter title text instead (possibly because that occurs lower down in the page, possibly because the parsing logic gives it precedence, haven't checked).

When Twitter renders this text it's correctly printing the raw entity, so the result is the non-breaking space is present in the card and it looks good. When Mastodon renders this text it is escaping the `&` so you get the non-ideal title.

...All this is to say that yes, this looks like a bug in Mastodon that should be fixed 😅

**Comment by AxelBoldt** [comment] 2022-11-25 05:07
The excerpt can also contain escaped HTML entities, as in https://mathstodon.xyz/@tao/109400708957917909

![image](https://user-images.githubusercontent.com/8941698/203905226-96f92ec2-dd12-4187-8e2f-fd290e75dab4.png)

**Comment by MalloryA** [comment] 2022-11-28 13:18
Duplicate of #14602.

**Closed** 2023-05-19 06:38 UTC
Labels: bug, ui
