### ISSUE TITLE
Populate new list with past 12 hours of list member posts

### ISSUE THREAD

**Issue by MadokVaur** [mastodon/mastodon#27704] opened 2023-11-05 13:57 UTC
### Pitch

Now that List members can be excluded from the Home feed, lists have become immensely useful

But. If the on-boarding experience is as important as it's made out to be, creating a new List that sits blank at creation time (and which will remain blank until List member(s) post) is likely baffling for those who haven't figured out what's going on, and even then...

I create a new List of someone I *already* follow, so my instance knows who they are and where they are. Often I can see in my Home feed or my Local feed that they've just posted something minutes before

Why not populate a new List with at least the last 12 hours of the List member's posts, just so users get some feedback and aren't (once again) given the impression that "Mastodon isn't working"?

### Motivation

Repeat:

If the on-boarding experience is as important as it's made out to be, creating a new List that sits blank at creation time is likely baffling for those who haven't figured out what's going on, and even then...

**Comment by trwnh** [comment] 2023-11-06 12:10
Duplicate of #16290

**Closed by trwnh** 2023-11-06 12:10 UTC
Labels: suggestion
