### ISSUE TITLE
Open the post if an URL refers to an ActivityPub posting existing on the local server

### ISSUE THREAD

**Issue by steinarb** [mastodon/mastodon#31335] opened 2024-08-07 20:13 UTC
### Pitch

If someone shares an activitypub post (e.g. a posting made on a different mastodon instance or a pixelfed post) and that same posting has made its way to the local server, it would be nice if clicking on the link opened the local post instead of opening the web page the URL refers to.

### Motivation

When I see something I like or that interests me, I would like to be able to mark it as a favourite, boost it or reply to it.

And I can only do that if the article resides on my local server.

So when someone stares e.g. a pixelfed post I try to open that post on the server (search up the author and look at that authors posts or see if there are hashtags and search for those hash tags).

But finding local version of the post can be hard work.

It would be nice if mastodon could do the hard work for me.

**Comment by renchap** [comment] 2024-08-08 16:58
Duplicate of #21869

We are considering various ways of solving this, but this is not obvious.

**Closed by renchap** 2024-08-08 16:58 UTC
Labels: suggestion
