### ISSUE TITLE
Scheduled Status on Web Interface

### ISSUE THREAD

**Issue by KRRW** [mastodon/mastodon#20842] opened 2022-11-16 05:50 UTC
### Pitch

Hi. Scheduled Status has been available on Mastodon via API for quite some time and there are 3rd party services offering this but shouldn't scheduling toots be made available as an option on toot composer? Needing to create a custom developers app and submit it to an app provider  just to schedule a toot is quite the hassle and potentially risky. Those 3rd party services also only allow scheduling text toots and do not allow adding media attachments, content warnings, setting privacy, etc.

### Motivation

Laziness

**Comment by ineffyble** [comment] 2022-11-16 12:18
Duplicate of #15912.

**Closed by ineffyble** 2022-11-16 12:18 UTC
Labels: suggestion
