### ISSUE TITLE
Hashtag search of Mastodon.social doesn't return specific keyword among its results

### ISSUE THREAD

**Issue by Paarsec** [mastodon/mastodon#22099] opened 2022-12-06 17:06 UTC
### Steps to reproduce the problem

Steps:
1. Let's say I need to follow a specific hashtag, so I look it up,
2. The search results I get don't include the # for that word, only hashtags that start with that word - i.e. if I look up #Twitter I only get #TwitterExodus #TwitterMigration, and so on. As far as I know your keyword simply doesn't appear as a result.

I tried to replicate this on other instances and it doesn't happen. I know other people who can't find hashtags they want to browse/follow on mastodon.social, i.e. the #b3d one also doesn't appear. 

I work around this problem by looking up another # and changing the url with the desired keyword, but that's not possible on the app, so now that the hashtag following feature is available on iOS I thought it could be worth bringing up, as it could put off new users who may think no one is using that specific hashtag.

These are my search results if I try to look up #b3d and #twitter on mastodon.social:
...
![results](https://user-images.githubusercontent.com/37757293/205971968-647fa8e0-b7d6-46c3-ae1b-af28299381fa.png)
![twitter](https://user-images.githubusercontent.com/37757293/205972768-62cc5cf9-3b23-4d7c-b784-bce40143a9ea.png)

Thank you for reading, and I hope this is helpful

### Expected behaviour

Hashtag search should return the specific keyword among the first results.

### Actual behaviour

Search results don't return the specific keyword at all.

### Specifications

It's been happening for at least a few months for me, so it spans multiple versions.
Happens on both desktop and the iOS app, but only for mastodon.social.

**Comment by Cassolotl** [comment] 2022-12-06 17:58
I'm pretty sure this is a duplicate of #17494 (Feb 2022).

**Comment by Paarsec** [comment] 2022-12-06 18:27
> I'm pretty sure this is a duplicate of #17494 (Feb 2022).

Thank you - it looks like on the other thread people have been digging much deeper in the specific code for it, so hopefully it can be fixed at some point.

**Comment by ineffyble** [comment] 2022-12-07 00:01
Duplicate of #17494 and will be solved when #21315 is merged.

**Closed by ineffyble** 2022-12-07 00:01 UTC
Labels: bug
