### ISSUE TITLE
Error 500 when searching for a user profile by URL

### ISSUE THREAD

**Issue by BradRubenstein** [mastodon/mastodon#20450] opened 2022-11-11 22:04 UTC
### Steps to reproduce the problem

1.  I log in as `@bradrubenstein@infosec.exchange`
2.  I search for `https://mastodont.cat/@jordicarsan` so i can follow that account.

### Expected behaviour

`@jordicarsan@mastodont.cat` profile should appear in search results

### Actual behaviour

Error 500 is flashed.  No search results are displayed.

### Detailed description

infosec.exchange issues the search API call:

 `https://infosec.exchange/api/v2/search?q=https:%2F%2Fmastodont.cat%2F%40jordicarsan&resolve=true&limit=10`

which can be seen to return status 500.

Note that if the search is by handle, the search API call is:

 `https://infosec.exchange/api/v2/search?q=%40jordicarsan%40mastodont.cat&resolve=true&limit=10`

which returns the desired profile without error.

### Specifications

infosec.exchange: Mastodon v4.0.0rc2+glitch
mastodont.cat: v4.0.0rc3

**Comment by trwnh** [comment] 2022-11-12 00:15
hmm, cannot replicate from mastodon.social -> mastodont.cat

**Comment by ineffyble** [comment] 2022-11-12 03:25
We probably need the server error message from infosec.exchange to give more details on the 500 before we can troubleshoot further.

**Comment by nyura123** [comment] 2022-11-12 05:14
I was able to reproduce the issue locally on my server, seems to be related to a recent change with verification. Opened a PR with a potential fix, the stack trace is in the PR #20470

**Comment by shleeable** [comment] 2022-11-12 05:17
I'm getting this thousands of times.

![image](https://user-images.githubusercontent.com/17537000/201458512-6af1b7db-bf79-4c43-b1d8-b788c8102d35.png)

![image](https://user-images.githubusercontent.com/17537000/201458514-35852ed2-80b7-469c-a3b7-fb05c2e69d6c.png)

**Comment by ClearlyClaire** [comment] 2022-11-12 08:12
Fixed by https://github.com/mastodon/mastodon/pull/20428

**Closed by ClearlyClaire** 2022-11-12 08:12 UTC
Labels: bug
