### ISSUE TITLE
Without ImageMagick, uploading emoji files is not possible

### ISSUE THREAD

**Issue by cadusilva** [mastodon/mastodon#30578] opened 2024-06-06 16:17 UTC
### Steps to reproduce the problem

1. Set an emoji name and select the emoji file
2. Clicking Upload immediately throws an error

### Expected behaviour

Successful upload and emoji added

### Actual behaviour

Imediate error, failed upload

### Detailed description

After #30090, when uploading an emoji file, an error is immediately thrown.

```
INFO -- : [747998e2-f015-4df6-9828-21284dd45a61] [paperclip] Trying to link /tmp/RackMultipart20240606-4122054-jvtb5n.gif to /tmp/727f3ea9cd9c5f222fec438bb341a8a020240606-4122054-79d0xi.gif
INFO -- : [747998e2-f015-4df6-9828-21284dd45a61] Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/727f3ea9cd9c5f222fec438bb341a8a020240606-4122054-79d0xi.gif[0]' 2>/dev/null
INFO -- : [747998e2-f015-4df6-9828-21284dd45a61] method=POST path=/admin/custom_emojis format=html controller=Admin::CustomEmojisController action=create status=500 allocations=3481 duration=45.68 view=0.00 db=11.68
FATAL -- : [747998e2-f015-4df6-9828-21284dd45a61]
[747998e2-f015-4df6-9828-21284dd45a61] Paperclip::Errors::CommandNotFoundError (Could not run the `identify` command. Please install ImageMagick.):
[747998e2-f015-4df6-9828-21284dd45a61] lib/paperclip/attachment_extensions.rb:21:in `block in post_process_style'
[747998e2-f015-4df6-9828-21284dd45a61] lib/paperclip/attachment_extensions.rb:20:in `each'
[747998e2-f015-4df6-9828-21284dd45a61] lib/paperclip/attachment_extensions.rb:20:in `inject'
[747998e2-f015-4df6-9828-21284dd45a61] lib/paperclip/attachment_extensions.rb:20:in `post_process_style'
[747998e2-f015-4df6-9828-21284dd45a61] app/controllers/admin/custom_emojis_controller.rb:21:in `create'
[747998e2-f015-4df6-9828-21284dd45a61] app/controllers/concerns/localized.rb:11:in `set_locale'
[747998e2-f015-4df6-9828-21284dd45a61] lib/mastodon/rack_middleware.rb:9:in `call'
```

I enabled `libvips` and uninstalled `ImageMagick`. If emojis are meant to be processed by IM instead, I'll reinstall it again.

### Mastodon instance

bolha.one

### Mastodon version

v4.3.0-alpha.4-4655be0

**Comment by ClearlyClaire** [comment] 2024-06-07 08:19
Thank you for your report! This is caused by `paperclip` calling `identify` to get the size of the image:
```
[43e2491e-3dda-4e63-8585-e0529f80f171] Paperclip::Errors::CommandNotFoundError (Could not run the `identify` command. Please install ImageMagick.):
[43e2491e-3dda-4e63-8585-e0529f80f171]
[43e2491e-3dda-4e63-8585-e0529f80f171] kt-paperclip (7.2.2) lib/paperclip/geometry_detector_factory.rb:42:in `raise_because_imagemagick_missing'
[43e2491e-3dda-4e63-8585-e0529f80f171] kt-paperclip (7.2.2) lib/paperclip/geometry_detector_factory.rb:28:in `rescue in geometry_string'
[43e2491e-3dda-4e63-8585-e0529f80f171] kt-paperclip (7.2.2) lib/paperclip/geometry_detector_factory.rb:15:in `geometry_string'
[43e2491e-3dda-4e63-8585-e0529f80f171] kt-paperclip (7.2.2) lib/paperclip/geometry_detector_factory.rb:9:in `make'
[43e2491e-3dda-4e63-8585-e0529f80f171] kt-paperclip (7.2.2) lib/paperclip/geometry.rb:25:in `from_file'
[43e2491e-3dda-4e63-8585-e0529f80f171] kt-paperclip (7.2.2) lib/paperclip/thumbnail.rb:35:in `initialize'
[43e2491e-3dda-4e63-8585-e0529f80f171] kt-paperclip (7.2.2) lib/paperclip/processor.rb:33:in `new'
[43e2491e-3dda-4e63-8585-e0529f80f171] kt-paperclip (7.2.2) lib/paperclip/processor.rb:33:in `make'
[43e2491e-3dda-4e63-8585-e0529f80f171] lib/paperclip/attachment_extensions.rb:21:in `block in post_process_style'
[43e2491e-3dda-4e63-8585-e0529f80f171] lib/paperclip/attachment_extensions.rb:20:in `each'
[43e2491e-3dda-4e63-8585-e0529f80f171] lib/paperclip/attachment_extensions.rb:20:in `inject'
[43e2491e-3dda-4e63-8585-e0529f80f171] lib/paperclip/attachment_extensions.rb:20:in `post_process_style'
[43e2491e-3dda-4e63-8585-e0529f80f171] kt-paperclip (7.2.2) lib/paperclip/attachment.rb:513:in `block in post_process_styles'
```

I think this may be fixed by using our `FastGeometryParser`, but I will need to investigate some more.

**Closed** 2024-06-07 09:33 UTC
Labels: bug, status/confirmed, area/media processing
