### ISSUE TITLE
Post more than four images in a post

### ISSUE THREAD

**Issue by EmilJacobs** [mastodon/mastodon#28460] opened 2023-12-21 14:15 UTC
### Pitch

Make it possible to post more than four media items (pictures, videos) per post.

### Motivation

To post a visual story with more than four photos, you currently need to make a thread of posts. It would be helpful to have just one post that holds all these media items. The platform Threads currently has an implementation of this, allowing up to ten items. This could be replicated.

**Comment by vmstan** [comment] 2023-12-21 20:07
Duplicate of #24461

**Closed by vmstan** 2023-12-21 20:07 UTC
Labels: suggestion
