### ISSUE TITLE
Feature proposal: OAuth PIN Authorization

### ISSUE THREAD

**Issue by nullkal** [mastodon/mastodon#4569] opened 2017-08-09 08:14 UTC
There are circumstances in which the application can't have a callback URL (e.g. Desktop/CLI applications). Authorization code is shown when `urn:ietf:wg:oauth:2.0:oob` is specified to `redirect_uri` currently, but maybe it is too long (hexadecimal 64 digits) to have users manually type it. It is helpful if mastodon has PIN-based authorization like [Twitter](https://dev.twitter.com/oauth/pin-based), or [Imgur](https://api.imgur.com/oauth2#auth_url) has. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThisIsMissEm** [comment] 2023-10-19 20:37
This would be a duplicate of #23408 for non-interactive inputs.

**Comment by ThisIsMissEm** [comment] 2024-11-26 23:37
@vmstan @mjankowski this can be closed as a duplicate

**Closed** 2024-11-26 23:37 UTC
