### ISSUE TITLE
Lists opened to accounts we do not follow

### ISSUE THREAD

**Issue by mj0123456789** [mastodon/mastodon#20520] opened 2022-11-12 19:56 UTC
### Pitch

Hello,
I used to use private lists to monitor and classify accounts and prioritize them in my readings.
On the other hand, a lot of accounts are not in my subscriptions because I prefer to see in my subscriptions things that interest me as a priority, or the relationships I know, etc.
I would like to know if it would be possible for you to plan to allow the addition of an account to lists without necessarily that we follow it?
(I understood that this can oblige to review certain deep functioning of the instances and exchanges of information between the instances).
Thank you for everything.

### Motivation

Could be useful for example since we only load contents in the lists when they are opened.

PS : With the new Tweetdeck (bird again, sorry but useful), multideck is awesome since we can swap from one (with some lists) to another (other lists, other topics).

**Comment by TymeForChange** [comment] 2022-11-12 20:59
co-sign

**Comment by veale** [comment] 2022-11-13 08:55
privacy question this raises: if this were implemented, should mods be able to see who lists an account federated by virtue of list membership, when such lists are private? it's quite useful to see the information as context for why someone has made it onto the federated feed when making moderation decisions (e.g. assessing how many people on the instance would a suspend v a silence affect).

**Comment by trwnh** [comment] 2022-11-13 11:17
Duplicate of #6982

**Comment by ClearlyClaire** [comment] 2022-11-15 10:13
Duplicate of #6982 indeed

**Closed by ClearlyClaire** 2022-11-15 10:13 UTC
Labels: suggestion
