### ISSUE TITLE
The ability to split an account into channels!

### ISSUE THREAD

**Issue by SoniEx2** [mastodon/mastodon#23075] opened 2023-01-13 00:09 UTC
### Pitch

An user can setup channels. An user can post to channels (or every channel). Following an user automatically subscribes to all channels (especially since the followed user might make more channels at any time and you wouldn't find out about it), and channels can be individually blocked/unsubscribed.

### Motivation

We don't know why ppl follow us but we'd like to not flood their feed with our struggles with ADLs or programming stuff or whatnot. This would give ppl the choice to opt-out of some of these, for better or worse.

There's stuff we wouldn't give our followers the choice to opt-out of, like uh, being queer. Yeah that one is non-negotiable. But like, we don't think most ppl wanna know about us cleaning our room in detail. So they should be able to skip those. And "channels" would be a lot more convenient for this than CWs, since channels are about the writer's direct interpersonal relationships rather than about the post's contents.

(Also this is explicitly NOT circles; circles are curated by the user, whereas this is self-curated by the followers.)

**Comment by tullo-x86** [comment] 2023-01-13 00:23
It sounds almost like "reverse Circles". While the posting user would still have to define channels, either ahead of time or at the time of posting, it would be the _followers_ who choose the channels they are interested (or disinterested) in.

Mechanism-wise, this bears a striking similarity to the way email services handle "unsubscribe" requests; some messages (critical updates, transactional notifications) are sent to everyone, others (marketing, events, etc) are sent only to recipients who have selected to receive those. Ignoring, of course, the typical dark patterns employed by users of said platforms.

This is actually an interesting idea, because I'm almost certain that a bunch of my IRL friends have me muted because I endlessly post about things that are mostly interesting to people on instances related to mine.

**Comment by trwnh** [comment] 2023-01-13 04:16
Duplicate of #1208

**Comment by SoniEx2** [comment] 2023-01-13 04:22
not quite - this is more of a modified form of hashtag/keyword filtering, by applying it per-user instead of globally.

the current hashtag filtering approach sucks and it could be made so much better by simply *leaning* on it. maybe also giving it its own activitypub field. but anyway.

#1208 takes this stuff to a completely different direction.

**Comment by marksda1** [comment] 2023-03-22 06:06
I came to see if this suggestion had been made already. 

This, exactly this. I keep separate accounts for this reason. I have a "business" account (I'm an artist) and a personal account. I think of this like a newsletter where the subscriber can pick the topics that are of interest to them .If they follow me and they want art but not Star Trek for example they might not want to hide Star Trek entirely with a global filter but they only want to see my art posts. 

And yes, I too think of it as reverse circles. It gives the poster control over what messages are "broadcast" to what channel.

**Comment by trwnh** [comment] 2023-05-20 20:29
closing in favor of either #1208 (categorizing posts on a profile into "channels", "streams", etc) or #380 (to allow multiple profiles per account, if you'd like even more separation)

**Closed by trwnh** 2023-05-20 20:29 UTC
Labels: suggestion
