### ISSUE TITLE
Change “A look inside” on the homepage to show the instance’s local timeline

### ISSUE THREAD

**Issue by mikekreuzer** [mastodon/mastodon#8558] opened 2018-09-01 20:56 UTC
“A look inside” on an instance’s homepage could show the instance’s local timeline, not the federated timeline. Or both could be available, but a look inside the instance would be cool.

**Comment by ykzts** [comment] 2018-09-01 21:06
![screenshot on admin UI](https://user-images.githubusercontent.com/12539/44949918-49109e80-ae76-11e8-905b-9af4cd039361.png)

from `https://instance.example.com/admin/settings/edit`

🤔

**Comment by trwnh** [comment] 2018-09-02 00:14
It's currently an admin setting, and many people set it to show the federated TL, but I think the issue is asking for a more user-facing way to toggle this. Heavily related: #1053 #8176

**Comment by mikekreuzer** [comment] 2018-09-02 00:30
Yes, what @trwnh said - would be great for people external to an instance to be easily able to really "look inside", whether or not they're already on Mastodon.

/api/v1/timelines/public?local exists, but you need to BYO interface :-)

**Comment by zcdunn** [comment] 2018-09-02 21:29
Also, this timeline doesn't show up on mobile anymore so that should be fixed

**Comment by enterprisey** [comment] 2018-09-16 21:49
> /api/v1/timelines/public?local exists, but you need to BYO interface :-)

it exists: http://www.unmung.com/mastoview

**Comment by kevquirk** [comment] 2018-09-22 11:05
+1 for this. Showing the federated timeline is completely pointless as it doesn’t give visitors a feel for the actual instance.

The whole point of this feature is to “look inside” the instance. If it’s showinf the fed timeline then users aren’t looking inside the instance, they’re looking inside the fediverse. I offers nothing to independent instances.

**Comment by trwnh** [comment] 2018-09-22 17:08
@kevquirk The federated TL is different for each instance! There's still value in showing off the wider network for an instance.

**Comment by kevquirk** [comment] 2018-09-22 17:13
I disagree entirely. When the feature says "look inside", I feel that
the majority of people will think that would mean "look inside THIS
instance".

----- Original message -----

**Comment by trwnh** [comment] 2018-09-22 17:18
@kevquirk You are still looking inside the instance, just not at the messages that *originate* from it, but rather all the messages that are inside it.

**Comment by enterprisey** [comment] 2018-09-22 19:11
@trwnh If the instance federates with a very high-traffic instance (mastodon.social comes to mind), then toots from the latter instance will drown out the toots that the user is presumably interested in.

**Comment by trwnh** [comment] 2018-09-22 19:42
@enterprisey Federating with an instance doesn't mean you get all the messages in your federated TL. Only the people followed by the server's members will appear. I agree that seeing local previews is useful, but disagree that federated previews are not useful. Whether "A Look Inside" uses local or federated is an admin decision.

**Comment by enterprisey** [comment] 2018-09-22 19:44
I still don't see why it's an admin decision.

>

**Comment by kevquirk** [comment] 2018-09-22 19:45
Exactly. I run a Linux/Open Source instance. If I were to enable this
feature pote tial new members are likely to see very little Linux/Open
Source stuff, but rather a load of anime etc.
This will instantly put many potential members off. Ipso facto, the
feature is useless as it displays the fed timeline.
----- Original message -----

**Comment by kevquirk** [comment] 2018-09-22 19:49
Obviously there are differing positions here. Would the best solution therefore be an option to choose which timeline to display in the admin panel?

**Comment by nightpool** [comment] 2018-09-22 19:52
pretty sure that option already exists

**Comment by kevquirk** [comment] 2018-09-22 19:56
So it is, thanks. 👍

**Comment by retonom** [comment] 2018-11-21 08:15
could the default be changed to showing the local timeline? I'd say most admins are not aware of this option and hence people get to see the federated timeline which gives no clue what is actually going on on the specific instance. I give you an example:

https://ruby.social/about

this tells you nothing about the ruby aspect of the instance. what I would like to know looking at such a preview is:

- how active is the instance?
- how "on-topic" is it?
- what ruby stuff do people post?

based on this information I'd then decide whether I want to join the instance or not...

**Comment by retonom** [comment] 2018-11-26 20:22
But the admin of ruby.social obviously doesn't know about this option and we're left in the dark what is actually happening on the instance. I've seen many instances like this and when I suggest to the admin to change the option to show only local toots they gladly do just that. That's why I think it should be the default.

**Comment by retonom** [comment] 2018-11-27 20:54
@stragu I like the idea with the user being able to toggle and you explain the benefits (from a federation POV) of a local-timeline default very well.

**Comment by Cassolotl** [comment] 2023-02-12 11:52
Logged out users can now see the instance's local or federated timelines (e.g. [here](https://mastodon.social/public)), so this can probably be closed?

**Comment by mikekreuzer** [comment] 2023-02-12 22:21
I'm happy if this is closed now.

Thank you all. Masto's come a long way in four & a half years. :smile:

**Closed** 2023-02-13 03:54 UTC
Labels: suggestion
