### ISSUE TITLE
Custom lists for favourited/bookmarked posts

### ISSUE THREAD

**Issue by benelaci** [mastodon/mastodon#25151] opened 2023-05-28 21:29 UTC
### Pitch

I'm longing for an option to organize favourited or bookmarked posts into categories, groups or lists, or save a post directly into a list item.

### Motivation

After a while there are hunderds/thousands of favourites, and it gets very hard or impossible to browse them. Items favourited long ago essentially get lost in the digestion pit.

(*For my own needs:* From time to time, I review my favourites to see if there's anything worth boosting. This would be aided by a system of lists/categories.)

**Comment by trwnh** [comment] 2023-05-28 23:56
Duplicate of #16595

**Closed by trwnh** 2023-05-28 23:56 UTC
Labels: suggestion
