### ISSUE TITLE
Replace the "navigation column" paradigm by a true column system in the advanced mode

### ISSUE THREAD

**Issue by Signez** [mastodon/mastodon#25877] opened 2023-07-10 14:55 UTC
### Pitch

Remove the right-most "navigation" column by acknowledging that the advanced interface mode does not follow a browser-like navigation.

All navigation would be made using transient columns shown directly next to the column where a navigation occurs, i.e. when clicking on an account link in the home column, an "attached" column appears on its right, that can be closed and navigated into, until it's either closed or that column is itself pinned as a new column.

The "Getting started" column content could became a dimmed last column, blending with the background, allowing to quickly add new columns and showing the same content as now.

(This would be helped by having #25875 be solved first, as it would ensure browser navigation would still work, in an albeit different matter, as it would open those links in their own single column UI.)

### Motivation

There seems to be some mismatch between some users expectations (including mine) of how the navigation should be handled in such a multi-column interface, how columns should be added, and how it's handled right now.

The current navigation model in the advanced interface is based around a viewport area that, most of the times, matches less than 25% of horizontal space. Moreover, it is not really named explicitly as such: it is basically the outer right column (I call it the _"navigation column"_).

The browser address bar is always showing the URL of that singular column, and you may "pin" the content of this column to its own column that will live somewhere else, but _never_ to the right of the "navigation column".

It's quite frustrating for a few reasons:

* If you happen to have a lot of columns or a narrow-but-not-mobile screen, you will not be able to see that column. The application will scroll horizontally to that column, but it's frustrating to always get back to that column when you want to navigate in the app, a very very common action.
* If you happen to click on a post, the content of the post and the replies will not be seen near the action, but in that "navigator column".
* The "Back" button on top of the _navigation column_ is a not a hierarchical Back, but a temporal Back: clicking on it will not get you back to where the action originated, but what was in that _navigation column_ before.

This would resolve (or provide some relieve for) those issues:

* #15798
* #18296
* #20292
* #21671

**Comment by trwnh** [comment] 2023-07-10 16:27
Duplicate of #8048?

**Comment by ronilaukkarinen** [comment] 2023-09-24 13:31
I agree. Right now I have to jump between compose column and the last column. It's frustrating and one of the things that makes the advanced mode pretty unusable.

**Comment by trwnh** [comment] 2023-12-30 08:58
Closing as duplicate of #8048. Please let me know if you disagree

**Closed by trwnh** 2023-12-30 08:58 UTC
Labels: suggestion
