### ISSUE TITLE
UX Suggestion: Show posts about a specific news item when clicking through to news

### ISSUE THREAD

**Issue by lirontocker** [mastodon/mastodon#21129] opened 2022-11-19 19:56 UTC
### Pitch

Hi there, 

I'd like to suggest showing posts about news items underneath a snippet / larger thumbnail of a news item when clicking through from the news page. The interaction could look something like this (Disclaimed: These are just wireframes):

![Screenshot 2022-11-19 204957](https://user-images.githubusercontent.com/7912787/202869036-01ebea20-b0aa-4e0e-bd77-64931e5320b5.png)
![Screenshot 2022-11-19 205037](https://user-images.githubusercontent.com/7912787/202869039-9f465545-d33c-4873-b222-2969fd367bed.png)

It adds an extra click but gives more context to the conversations happening about a specific news item, as teased on the thumbnail ("XYZ people in the last X days")

### Motivation

All users could benefit from this feature

**Comment by trwnh** [comment] 2022-11-20 03:01
Duplicate of #19620

**Comment by lirontocker** [comment] 2022-11-20 08:48
> Duplicate of #19620

Thank you, I'll close this one!

**Closed** 2022-11-20 08:49 UTC
Labels: suggestion
