### ISSUE TITLE
Improve EDITED POST view - implement red & green side-by-side DIFF visualisation

### ISSUE THREAD

**Issue by PurryPlatypus** [mastodon/mastodon#26743] opened 2023-08-31 13:26 UTC
### Pitch

The "mechanic" of being able to edit posts is amazing!

However, the presentation of the posts "changelog" could use a "proper side by side" DIFF rendering, with red(deletions) and green(additions/substitutions)!

Here's an example / deep link, featuring a screenshot of the SHOULD BE state of things; https://layer8.space/@platymew/110984212565619798 …imho

…how do i upload this example screenshot, on GitHub? (it should be persistent, even if my instance of choice [edit: the deep link] goes the way of the Dodo)

### Motivation

motivation …huh, yeah; it's rather cumbersome, currently, to make out the changes/edits of a toot/post. One can view each version, all right, but it still requires enormous amounts of cognitive overhead to decipher "what's actually changed". And lots of clicking around in the UI, in order to view each change.

We should adapt the software, to serve OUR NEEDS, rather than us adapting to the state/current implementation of the software. ;) 

A side-by-side DIFF, with coloured/highlighted visual pointers would be the PERFECT vehicle for such an effort, imho.

(if someone tells me, how to upload a screenshot, i'll post it here - for now, y'all have to click the link above)

**Comment by PurryPlatypus** [comment] 2023-08-31 14:06
…imho, this should be implemented client-side (i'm talking browser-based) …no idea what Android or *-apps do …please focus efforts on browser-diff, 1st. I'm mildly familiar with "design patterns", and if this code adheres to "common" server/client API architecture, this request shouldn't increase server/instance load, much.

**Comment by trwnh** [comment] 2024-03-19 20:29
Duplicate of #20783

**Closed by trwnh** 2024-03-19 20:29 UTC
Labels: suggestion
