### ISSUE TITLE
Mute toots posted using third-party app

### ISSUE THREAD

**Issue by KRRW** [mastodon/mastodon#21280] opened 2022-11-21 07:01 UTC
### Pitch

We need a mute/block option against third-party apps like Crossposter from Twitter. Most accounts that use this feature are merely dumping their tweets into mastodon instances remotely. Interacting with these toots is often futile as the poster is still on twitter. And the crossposter is just bringing the toxic content from twitter to mastodon. That is why mastodon users should be given the ability to block/mute toots posted using an app that has a given word in its name, like "twitter", "crossposter", and the likes.

### Motivation

For the sake of mastodon users who don't want the toxicity of twitter

**Comment by trwnh** [comment] 2022-11-21 09:27
Duplicate of #8271

**Closed** 2022-11-21 10:00 UTC
Labels: suggestion
