### ISSUE TITLE
Sort out user in DM

### ISSUE THREAD

**Issue by vibhi19** [mastodon/mastodon#9992] opened 2019-02-09 06:00 UTC
Pitch

The ability to sort out user in DM. The issue is when you start multiple DM with same person it became a mess and there is no way other than scroll down and find the exact chat with that user and it become time consuming. So an search for user, only show that user dm would be awesome or Show all those different chat in one like Showing user on dm column and when click on it, it will show all different dm with that user.

Motivation

It will make thing easy and simple and user dont have to waste time finding those chat and best of all it wont be an mess anymore

**Comment by sapphaos** [comment] 2019-10-26 06:39
I would also love to have this implemented :+1:

**Comment by LucileDT** [comment] 2019-10-26 07:10
I agree, it's useful for a professional use!

**Comment by trwnh** [comment] 2023-05-16 03:30
Duplicate of #3819

**Closed by trwnh** 2023-05-16 03:30 UTC
