### ISSUE TITLE
Block Followers of a User

### ISSUE THREAD

**Issue by MrHamel** [mastodon/mastodon#28636] opened 2024-01-07 21:16 UTC
### Pitch

My friend on the federation has posted [this idea](https://hachyderm.io/@winterschon/111716036172642988) on the federation. Not sure if this is feasible or worthwhile, but thought I would raise it on her behalf to see where it goes.

To ensure this feature/idea does not go too crazy, it would not block the followers the user also follows themselves.

> I wish there was a non-api method on #Mastodon to mute/block not just one person, but everyone who is associated with their profile (followers specifically, but also additional strata).

> “Recursive Block”?

> basically, yep, with a depth variable as limit

### Motivation

The idea behind this if someone has really bad takes on topics that a user does not agree with, they also get blocked, as another tool alongside blocking/muting hashtags.

**Comment by trwnh** [comment] 2024-01-08 06:04
Duplicate of #8238

**Closed by trwnh** 2024-01-08 06:04 UTC
Labels: suggestion
