### ISSUE TITLE
Specify Context/Content Hashtags for which to follow users

### ISSUE THREAD

**Issue by alex-train** [mastodon/mastodon#16826] opened 2021-10-08 16:31 UTC
### Pitch

Hi,
Would it be possible to follow someone **only** for specific topics or contents?
For example, it would be great **to follow someone only for** Politics, or Entertainments, or Songs, or Games, and so on.
This could be implemented **by defining simple hidden Context/Content Hashtags** added automatically by the server to the toots, or in a hidden metadata field, associated with the toot.
They could be something like: #$Politics, or #$TVShows, etc.
In this way, when I write a toot, I could choose the context to associate with the message, so my followers could read only the toots about their favorite contents.
Thank you.
Alex

### Motivation

This feature would focus interest on specific and preferred followed contents, and it would help users to talk without hesitation about anything, posting their thoughts under specific labels.
Sometimes people don't follow other users, because they don't care about all the posted topics.

**Comment by trwnh** [comment] 2021-10-09 02:15
duplicate of #1208

**Closed** 2023-05-19 14:12 UTC
