### ISSUE TITLE
Allow to set a default visibilities for replies

### ISSUE THREAD

**Issue by allo-** [mastodon/mastodon#21102] opened 2022-11-19 15:15 UTC
### Pitch

When I reply to a toot, I often set the visibility to unlisted. When I post something new, I usually use public posts. It would be nice to have different defaults for the visibility of new posts and replies.

As many clients try to copy the visibility of the previous post, the selected visibility should probably be the minimum between the visibility of the parent post and the setting in the setting for the default reply visibility.
Example: When posting a reply to a "public" post, the visibility should be "unlisted", but when posting a reply to a "follower-only" post, the visibility should be "follower-only"

### Motivation

Many posts are public, but there often is no need for replies to be listed in local and federated timelines. So it can be useful to have a default for a lower visibility level.

**Comment by trwnh** [comment] 2022-11-19 15:36
Duplicate of #19685

**Closed** 2022-11-19 15:37 UTC
Labels: suggestion
