### ISSUE TITLE
Feature Request: Post to Categories/Bins

### ISSUE THREAD

**Issue by jimbo2150** [mastodon/mastodon#20776] opened 2022-11-15 13:22 UTC
### Pitch

Add the ability to post to _bins_ or _categories_, so if a user can post to a **life** category and other posts in the **political** category and other posts in a **gaming** category. Others who follow can choose to follow all the users' posts, filter out posts in specific categories, or only see posts added to specific categories.

### Motivation

Others have requested it on other social networks. It would reduce the amount of noise coming from accounts when people don't want to see certain categories of posts. For example, if a gaming website posts about games but also politics, some people may not want to see the political posts and show as noise in their feed.

**Comment by trwnh** [comment] 2022-11-15 13:24
Duplicate of #1208

**Closed** 2023-05-19 06:49 UTC
Labels: suggestion
