### ISSUE TITLE
Import following list never finished

### ISSUE THREAD

**Issue by lapcat** [mastodon/mastodon#27231] opened 2023-10-01 15:49 UTC
### Steps to reproduce the problem

1. Open https://mastodon.social/settings/imports
2. Select following list
3. Choose file of followers exported from previous instance
4. Select Merge
5. Upload

### Expected behaviour

Finished with downloadable list of failures

### Actual behaviour

In progress with no list of failures

### Detailed description

I migrated Mastodon instances yesterday and then imported my following list from the previous instance. After more than 24 hours, the import is still "In progress", with 202 / 204 imported, with 1 failure. So it appears to be stuck on 1 imported follower.

Also, the Failures list is not clickable, because it's still in progress, unlike with finished imports.
![Screenshot 2023-10-01 at 10 39 35 AM](https://github.com/mastodon/mastodon/assets/56086/23f57008-7974-4ff9-b5f0-f3db18660db9)

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.0+pr-27116-50e1f46

### Browser name and version

Safari 17

### Operating system

macOS 13.6

**Comment by ClearlyClaire** [comment] 2023-10-02 12:20
I have seen multiple reports of this, but haven't been able to reproduce it myself yet. I will continue digging, but I am not sure what is happening yet.

**Comment by lapcat** [comment] 2023-10-02 12:34
I just did a diff of my old and new following lists. My old following list has 3 accounts absent from my new following:

1. jsnell@mastodon.social (which has moved to jsnell@zeppelin.flights)
2. lapcatsoftware@mastodon.social (which is my own new account)
3. peisert@mastodon.radio

**Comment by ClearlyClaire** [comment] 2023-10-02 12:49
Follow requests waiting for approval should still count towards successful imports, it should not prevent the import for moving forward!

**Comment by lapcat** [comment] 2023-10-02 13:04
I cancelled the follow, but the import is still "In progress".

**Comment by ClearlyClaire** [comment] 2023-10-02 13:23
> I cancelled the follow, but the import is still "In progress".

Yes, it is not related to whether the follow request is pending.

Do you perhaps have duplicate accounts in the list you're importing?

**Comment by lapcat** [comment] 2023-10-02 13:27
> Do you perhaps have duplicate accounts in the list you're importing?

No.

**Comment by ClearlyClaire** [comment] 2023-10-02 14:04
I think I identified two issues, one would be caused by duplicates in the CSV (which is not your case), and one where the generic failure path would fail to update the import's progress. That second one should be fixed by #27247

**Closed** 2023-10-02 14:20 UTC
Labels: bug, status/identified, area/web interface
