### ISSUE TITLE
500 text character limit

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon#29487] opened 2024-03-01 21:58 UTC
### Pitch

Right now text is limited to 500 characters in post descriptions and comments. 
This should be opened up to unlimited

### Motivation

Beneficial because if we're typing something lengthy, it can happen in one comment etc

**Comment by trwnh** [comment] 2024-03-02 08:30
Duplicate of #27433

**Closed by trwnh** 2024-03-02 08:30 UTC
Labels: suggestion
