### ISSUE TITLE
Posts from limited accounts on server level are still visible when boosted

### ISSUE THREAD

**Issue by joenepraat** [mastodon/mastodon#27179] opened 2023-09-27 21:19 UTC
### Steps to reproduce the problem

1. Limit an account on the server
2. Wait until someone you follow boost a post from this account
3. See that boosted post appear on your home timeline or in a list. I only tested this with a list with 'Hide these posts from home' enabled, but I guess it would have appeared on my home timeline as well when I had disabled this option.

### Expected behaviour

When an account is limited you should not see anything from that account, except when you follow that account

### Actual behaviour

It still showed a boosted post from that limited account, despite being limited.

### Mastodon instance

todon.nl

### Mastodon version

v4.2.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: 3.2.2
- Node.js version: v16.20.2

**Comment by joenepraat** [comment] 2023-09-27 21:29
I see it's a duplicate of #26301. That one is from August 2. I don't understand why that one wasn't picked-up, because I think it's of a high priority. I let the devs decide which issue should be closed, but can you please fix this ASAP?

**Comment by trwnh** [comment] 2023-09-30 21:43
Duplicate of #26301

**Closed by trwnh** 2023-09-30 21:43 UTC
Labels: bug, status/to triage
