### ISSUE TITLE
Avatar border bug

### ISSUE THREAD

**Issue by ZoeBijl** [mastodon/mastodon#22179] opened 2022-12-09 14:48 UTC
### Steps to reproduce the problem

1. Visit a profile on v4.0.2 (either advanced or simple), for example this one: https://front-end.social/@moiety

![messed up border around avatar](https://user-images.githubusercontent.com/5457769/206727696-23a9532e-7d46-47f4-b29b-a894a3b85147.png)

![messed up border in advanced](https://user-images.githubusercontent.com/5457769/206727781-770227b9-7293-47e3-b388-28897030af60.png)

### Expected behaviour

border looks normal, loops around

### Actual behaviour

border is broken up

### Detailed description

Seems to be caused by a `margin-left: -2px` on `.account__header__bar .avatar` in [components.scss.js](https://github.com/mastodon/mastodon/blame/e8481e67a760d901742f2af2b306557dcd9183a3/app/javascript/styles/mastodon/components.scss#L7024)

[relevant thread](https://front-end.social/@moiety/109484037335689148)

### Specifications

Mastodon 4.0.2
Checked in Chrome and Firefox

**Comment by ineffyble** [comment] 2022-12-10 00:20
Duplicate of #20822

**Closed by ineffyble** 2022-12-10 00:20 UTC
Labels: bug
