### ISSUE TITLE
Accounts are being suspended without any admin action

### ISSUE THREAD

**Issue by athosmoreno** [mastodon/mastodon#22425] opened 2022-12-18 00:48 UTC
### Steps to reproduce the problem

I have administrator rights in a small Mastodon instance (https://bolha.one) and we have noticed that some accounts are being suspended without me or the instance owner taking any action. One notable example is https://mastodon.social/@elonjet. The audit log doesn't show anything, but this account appeared as suspended in our instance.
Other administrators also reported this behavior (https://mindly.social/@KuJoe/109524608919961202).

We have no idea on why this is happening and how to fix it at this time.

### Expected behaviour

No accounts should be suspended without any administrator action

### Actual behaviour

Accounts from other instances are being suspended for no reason

### Specifications

Mastodon 4.0.2

**Comment by KuJoe** [comment] 2022-12-18 00:57
I've confirmed this issue and have to regularly unsuspend a specific account a few times a day.
![image](https://user-images.githubusercontent.com/1040086/208271936-cd5d4215-5cac-44b3-84c6-615d037be608.png)
![image](https://user-images.githubusercontent.com/1040086/208271940-35ed2126-92f0-4340-9c66-2baac0c7a647.png)

I originally thought it was related to relays, but this is not the case since I disabled all relays last night and the account has still been suspended twice today.

**Comment by KuJoe** [comment] 2022-12-18 00:59
Additionally, I've had another user contact me from a different server asking why they were suspended and users from my server could not follow them and vise-versa. I checked their account and it showed they were suspended but there was nothing in the audit log about it nor any reports.

**Comment by vitorgrs** [comment] 2022-12-18 01:45
Same issue happened here, with the same account (on bolha.us)

**Comment by nightpool** [comment] 2022-12-18 02:24
This account was briefly (accidentally) suspended and then unsuspended by the mastodon.social instance. This triggered a bug in some remote instances where the "suspend" job for that account got queued up multiple times in sidekiq and continues to retry, causing the "resuspend" behavior you're seeing. This bug is fixed by #22363

**Closed by nightpool** 2022-12-18 02:24 UTC
Labels: bug
