### ISSUE TITLE
Hashtag is not parsed after a slash

### ISSUE THREAD

**Issue by GiantCrocodile** [mastodon/mastodon#21117] opened 2022-11-19 18:06 UTC
### Steps to reproduce the problem

1. Update your Mastodon profile biography to a string like "#test/#test2".
2. Press save

### Expected behaviour

both hashtags can be clicked without adding a space after the "/"

### Actual behaviour

the 2nd hashtag is not clickable

### Detailed description

At least in the language German it's not uncommon to start a word directly after and before a "/" so it should work fine in both cases. I'm not sure if this is by design or intended. It's a minor usability issue.

### Specifications

Mastodon v4.0.2
latest Firefox
Windows 11

**Comment by Cassolotl** [comment] 2022-11-19 19:45
Duplicate of *Hashtags directly after / don't become links #1910* - yes, this has been a thing for five years without being fixed. :(

**Closed** 2023-05-19 06:41 UTC
Labels: bug

**Comment by GiantCrocodile** [comment] 2023-05-20 20:33
@trwnh Any insight on why this isn't planned to be implemented? Why is the other issue still open then?

**Comment by trwnh** [comment] 2023-05-20 20:37
Duplicate of #1910. (GitHub categorizes duplicate issues under the "not planned" label, as opposed to "complete")

**Comment by GiantCrocodile** [comment] 2023-05-20 20:39
Thanks for the info @trwnh, I wasn't aware of that. Have a nice weekend!
