### ISSUE TITLE
Give Posts From a Followed Hashtag A "#followed" tag in the post header

### ISSUE THREAD

**Issue by zerojay** [mastodon/mastodon#20939] opened 2022-11-17 12:38 UTC
### Pitch

Currently, posts that are from followed hashtags just show up in the timeline. It can sometimes be a bit confusing as to why that particular post has hit your timeline, especially due to issue #20937.

I was trying to understand why I had a Spanish post from a user I did not follow and was not boosted by those I follow in my timeline. It took a little time to realize it was because it had been tagged with a hashtag I follow.

Currently, boosted posts receive a little header that shows a boost icon and "username boosted" to let us know why we are seeing that post. It would be VERY helpful to have something similar for followed hashtags. Perhaps even just something as simple as "#hashtag" would be great. Perhaps the "#hashtag" portion could be a clickable link popping up a list of posts with that hashtag in the interface, just like searching currently does.

### Motivation

Much like boosted posts before they had a header, users might not understand why a particular post is showing up in their feed and it may not be obvious that it is because they follow a particular hashtag. In fact, if you are only following hashtags with little traffic, you may even be under the impression that following hashtags is a feature that doesn't work unless you notice a post come through that has the hashtag buried somewhere within it.

Adding a "#hashtag" header to a post will show users why they are seeing the post, and would make followed hashtags have more consistent behavior with how boosts are presented in the timeline as well.

**Comment by trwnh** [comment] 2022-11-18 01:11
Duplicate of #19895

**Closed** 2022-11-21 12:14 UTC
Labels: suggestion
