### ISSUE TITLE
Import/export list 

### ISSUE THREAD

**Issue by JeedPi** [mastodon/mastodon#22852] opened 2022-12-30 10:17 UTC
### Pitch

It would be great, when importing a list of accounts to follow, to have the possibility to add these account to an existing or a new list. 

Similarly, when exporting accounts followed, the ability to filter them and export only accounts from a list would be useful too.

### Motivation

The import and export features are really useful to discover new accounts quickly (see https://astrodon.social/@AlexSanterne/109602017394641198 for example). 

When using the list feature to create "theme based timelines", having to manually add each account to the list after the import is really painful. Adding to a list during import would solve this.

**Comment by ineffyble** [comment] 2022-12-31 15:14
Duplicate of #15015

**Closed by ineffyble** 2022-12-31 15:14 UTC
Labels: suggestion

**Comment by JeedPi** [comment] 2022-12-31 15:23
Oh. Sorry for the duplicate. I did search for similar entry. I guess I did not search hard enough :(
