### ISSUE TITLE
option to sort replies by most-favourited/hot

### ISSUE THREAD

**Issue by naught101** [mastodon/mastodon#23141] opened 2023-01-18 03:22 UTC
### Pitch

Allow replies to be sorted by most favourited.

I think this should just be a global setting per user.

It should also apply to all sub-replies, so:

- reply 1
    - sub reply 1
    - sub reply 2 **
- reply 2 *

Becomes

 - reply 2 *
 - reply 1
    - sub reply 2 **
    - sub reply 1

It might also be useful in a future iteration to have other sort methods, e.g. oldest first, or something akin to Reddit's "best" (although this requires down votes) or "hot" (mass favourited in the last X hours).

### Motivation

Often toots with lots of replies have excellent content hidden in the late replies, which is swamped by meaningless early short replies (like "haha, awesome"). 

This in some cases reduces the likelihood of good in-depth conversations about interesting issues.

This feature would also allow the OP to give some small boost to the replies that they find most interesting.

Obviously self-favourites should be excluded. Also replies by OP should always come at the top regardless of sort method.

**Comment by guyyst** [comment] 2023-01-25 02:05
Couldn't agree more. Back when I was still using TweetBot for Twitter, I occasionally opened a tweet in the official Twitter app, since third party Twitter apps could *only* sort replies chronologically.

On Mastodon, especially with posts that have been heavily boosted and received potentially hundreds of replies, I frequently find myself leaving the post because there's no way I'm going to read everything, and chances are, the *great* replies aren't among the first ~20.

I understand the hesitation some people might have towards this, and the potential for toxicity it creates, but I think that the 2 simple sorting options suggested by OP would increase the usefulness of replies by multiple orders of magnitude. It doesn't have to be some magic algorithm à la Twitter that pushes the most controversial replies to the top.

**Comment by trwnh** [comment] 2023-10-31 09:46
Duplicate of #15062

**Closed by trwnh** 2023-10-31 09:46 UTC
Labels: suggestion
