### ISSUE TITLE
Re-enable video play at timestamp support (e.g. youtube.com)

### ISSUE THREAD

**Issue by ldexterldesign** [mastodon/mastodon#30966] opened 2024-07-08 23:45 UTC
### Steps to reproduce the problem

1. Visit https://www.youtube.com/watch?v=kPE9v5aCAb0
2. Click share button and specify a "Start at" time, which generates a custom URL
3. Copy URL
4. Paste URL into Mastodon post
5. Click to play video, using video placeholder / preview card, inside Mastodon (i.e. rather than clicking the URL to play at youtube.com)

### Expected behaviour

Video should play from specified/shared timestamp

### Actual behaviour

Video plays from start

### Detailed description

I believe I was involved with getting this feature request into Mastodon a while back (apologies, I searched for the issue but couldn't find it - perhaps using incorrect keywords), hence this being a bug rather than a feature request again. I suspect this is a regression.

### Mastodon instance

https://mastodon.social

### Mastodon version

v4.3.0-nightly.2024-07-05-security

### Browser name and version

Tested multiple browsers so don't think this is relevant

### Operating system

macOS 14.1.2 (23B92)

**Comment by ldexterldesign** [comment] 2024-07-08 23:46
A test [URL]

[URL]: https://mastodon.social/@ldexterldesign/112753450841022049

**Comment by renchap** [comment] 2024-07-09 07:21
Duplicate of #22238 

There is a PR trying to fix this, but it has never been merged: https://github.com/mastodon/mastodon/pull/26584

**Closed by renchap** 2024-07-09 07:21 UTC
Labels: bug, status/to triage, area/web interface
