### ISSUE TITLE
Display Bot label in timelines

### ISSUE THREAD

**Issue by Andre601** [mastodon/mastodon#21788] opened 2022-11-28 12:46 UTC
### Pitch

The "Bot" label should be displayed in the timeline (i.e. federated timeline), or alternatively have an icon to indicate a bot account.
This is about the web-app.

### Motivation

Right now, when you're looking at the federated timeline (or any timeline really) is there no way to see if a user is actually a bot or not, unless you check their user page directly.

A quick example using the "Level checker" account from botsin.space:
![grafik](https://user-images.githubusercontent.com/11576465/204281119-d1bd380d-68a7-4177-b4ef-da79c811660e.png)

Here, you have 0 indicators that this account is marked as a bot. Only when you check their profile is it displayed using the "Bot" label.

Because of this would it be useful, if the bot label can be displayed on the timeline too (Or as mentioned an icon as an alternative as apps such as Tusky do already).

**Comment by jdebp** [comment] 2023-01-12 19:21
This appears to be a duplicate of #20764, as #20801 was.

**Closed** 2023-05-19 06:34 UTC
Labels: suggestion
