### ISSUE TITLE
More button menu on timeline scrolls away from post on web

### ISSUE THREAD

**Issue by imrehg** [mastodon/mastodon#21966] opened 2022-12-02 23:11 UTC
### Steps to reproduce the problem

1. Go to a timeline on the web (local or federated), a steadily but not too fast moving one is likely easiest to replicated
2. Scroll a bit down on the page, so that posts don't move from your perspective on the screen, but new posts are added to the timeline
3. Click on a post's "more" button (triple dots) to bring up the menu
4. Wait until some new posts come in to the timeline

### Expected behaviour

The popped up menu stays with the post and on your screen

### Actual behaviour

With new posts menu will be scrolled up & away, while the post stays where it was on the screen

### Detailed description

This behaviour makes the "more" button pretty unworkable on fast moving timelines (like the Federated view for most people, probably).

Here,s an example, clicking on the "more" button of the bottom post:

<img width="699" alt="Screenshot 2022-12-03 at 07 00 48" src="https://user-images.githubusercontent.com/38863/205404179-ee8d1766-1ad1-45f7-9e36-75db63bde8fa.png">

After new posts came in, the menu moved, see how the "more" button of the bottom post is still highlighted/selected, but the menu itself scrolled away:

<img width="717" alt="Screenshot 2022-12-03 at 07 01 00" src="https://user-images.githubusercontent.com/38863/205404186-7397f0d5-60c2-4d18-916f-5a8539acf24f.png">

### Specifications

Firefox 107.0.1
MacOS Ventura 13.0.1 (22A400)

**Comment by ClearlyClaire** [comment] 2022-12-07 10:55
Duplicate of #14266

**Closed by ClearlyClaire** 2022-12-07 10:55 UTC
Labels: bug
