### ISSUE TITLE
Provide diff in notification when a boosted post is edited

### ISSUE THREAD

**Issue by vecna13** [mastodon/mastodon#28763] opened 2024-01-16 19:22 UTC
### Pitch

Notifications that someone edited a post should indicate how the post has been changed since the user boosted it.

### Motivation

It's confusing to just get a notification that just says someone edited a post and the new text. It's missing a lot of context: What did the post originally say (and by extension, why did I originally boost it)? What's different? (Did the author just fix a typo or completely replace it with a new post?)

If the post is edited to be objectionable, the user may want to unboost it. This feature would make it easier to figure this out by building on the user's previous decision, rather than requiring them to reconsider it like a new post.

**Comment by kiluazen** [comment] 2024-06-02 10:46
Is anyone working on this @trwnh, @vecna13  . I would like to work on it!!

**Comment by shaedrich** [comment] 2024-09-01 16:26
Related to #20783

**Comment by trwnh** [comment] 2024-09-01 16:33
Duplicate of #20783 actually

**Closed by trwnh** 2024-09-01 16:33 UTC
Labels: api, suggestion, area/web interface

**Comment by shaedrich** [comment] 2024-09-01 16:37
@trwnh Are you sure? The way, I understand it, #20783 ask for more of a context menu option to show a modal with a diff when you encounter an edited toot in your feed, while #28763 might display the diff right away _instead_ of the toot as a notification

**Comment by trwnh** [comment] 2024-09-02 02:19
those are just implementation details, the feature request is the same (diffs for edited posts)

**Comment by shaedrich** [comment] 2024-09-02 04:21
If it's not forgotten about in the other issue, because this wasn't specifically addressed there, that's fine 👍🏻
