### ISSUE TITLE
Web preview link drops URL fragment hash 

### ISSUE THREAD

**Issue by callionica** [mastodon/mastodon#26467] opened 2023-08-13 12:40 UTC
### Steps to reproduce the problem

1. Create a post with a link that includes a hash fragment (e.g link to a particular comment in a GitHub issue)
2. View the post in the official iOS client
3. Notice that a preview has been created for the linked page.
4. Click the preview box and notice that the link takes you to the top of the page because the hash fragment has been dropped from the URL used by the preview box. 

### Expected behaviour

The preview link should go to the specific comment on the GitHub issue

### Actual behaviour

The preview link goes to the top of the page 

### Detailed description

I don’t know which component in Mastodon is responsible for the web preview boxes, but I’m on mastodon.social and using the official Mastodon iOS client.

The link on those web preview boxes needs to contain the hash fragment. Dropping it can completely change the meaning of the post. Imagine that you post “I agree strongly with this” and link to a GitHub issue comment that says “The suggestion from the OP will blow a hole in our security and must not be allowed to happen”, and instead the web preview box links to the top of the issue where the OP says “We should disable HTTPS so that more clients can access the server”. It’s a bad bug! Please fix. 

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.0+nightly-2023-08-09

### Browser name and version

Safari iOS 

### Operating system

IOS 16.6

**Comment by callionica** [comment] 2023-08-13 12:52
I guess this is https://github.com/mastodon/mastodon/issues/19538 which I failed to find on my first searches for related issues.

**Comment by ClearlyClaire** [comment] 2023-08-14 07:20
Closed as a duplicate of #19538 (which I changed the title of to make it more searchable)

**Closed by ClearlyClaire** 2023-08-14 07:20 UTC
Labels: bug, status/to triage, area/web interface
