### ISSUE TITLE
"Back"-link in Start-menu links to previously visited site

### ISSUE THREAD

**Issue by sjustesen** [mastodon/mastodon#21922] opened 2022-12-01 12:12 UTC
### Steps to reproduce the problem

1. Navigate between different sections in Mastodon for a while
2. Keep clicking the "Back"-button in the top right corner of the start-menu
3. Suddenly, you'll end up on the site you visited before going to Mastodon

### Expected behaviour

Disable/hide the "back"-button when you're on the startpage of Mastodon

### Actual behaviour

An unexpected visit to a site in my browser history

### Specifications

Mastodon v4.0.2 (web edition)
Ubuntu 22.04 LTS (64 bit)
Firefox 107.0 (64 bit)

**Comment by trwnh** [comment] 2022-12-01 16:19
Duplicate of #20292

**Comment by rbairwell** [comment] 2022-12-02 17:10
If you follow a link to your instance, the "start page" would actually be the profile you followed.

It'll be better if the React frontend kept track of the history.pushState and history.go calls to stop the the "Back icon" in the column accidentally kicking people out od Mastodon.

**Comment by ineffyble** [comment] 2022-12-03 12:33
Closing as duplicate of #20292.

**Closed by ineffyble** 2022-12-03 12:33 UTC
Labels: bug
