### ISSUE TITLE
Permit single toot thread view within own instance

### ISSUE THREAD

**Issue by bbbradsmith** [mastodon/mastodon#22983] opened 2023-01-07 23:06 UTC
### Pitch

A link to a toot on another instance will open in my web browser as a useful public view of just that toot and its thread, as served by its own instance.

A link to a toot on my own instance (mastodon.social) will instead open my own multi-panel integrated view, as if I'd found it on my timeline and clicked it there.

It is good that there is a way to click on a toot, and get it dropped into the main multi-panel local view, but I would find it helpful to be able to access both versions.

I would suggest either a user option about how toot link URLs will open in a new tab by default, or access to a modified URL from the ... menu on a toot that will open in the single-thread view.

The existing behaviour of the multi-panel view opening left-clicked links in its own tab is good, and useful. Not suggesting any change to that. Am only suggesting a need to access the single-thread view.

### Motivation

I find the isolated single-thread view much easier to read. It allows me to review the thread without the distraction and encumberance of everything else going on in the main mastodon view. The main view is constantly changing, and has a lot of extra information and features that I find very detrimental to my ability to read a thread. It reduces my ability to focus on the content I'm trying to read and understand.

I would categorize this as an accessibility feature request.

I also use it whenever I wish to share a link to a took publicly. I want to preview how I expect the thread to look for others before sending it to them.

My current workaround is to open a private browser window to view it this way.

However, I'm continually surprised about which toots open in which way, because the behaviour is only different for ones that are local to my instance. It's not terribly obvious which instance toots in my timeline are from, but I also wouldn't want it to be. This request is mostly about being able to minimize distractions, and the number of steps between trying to open a toot/thread in this view and getting to read it. Having to keep track of instances at the same time would add to the mental load involved.

**Comment by trwnh** [comment] 2023-01-07 23:20
lemme make sure i understand what you're asking for -- you're saying that the issue occurs under the following?

- you are logged in
- you click a link to a local status
- you are using the advanced web UI
- you want to view the default UI because it has only one column focused

if so, this issue is largely a consequence of the removal of the separate "permalink" views and the merging of their routing into the web-app. you would have to do something like the following:

- embed the single-column detailed status view within the multi-column layout, perhaps as a modal or side panel
- have the multi-column layout be a separate app view, not handling URLs at all, and route permalinks to a single-column view always

this would have the side effect of making URLs harder to copy in-app, as you now have to go through the menu action instead of through your browser's navigation bar.

**Comment by bbbradsmith** [comment] 2023-01-08 01:15
I do appear to be using the advanced web UI. I don't believe I've ever noticed this option before. Was advanced originally the default, and subsequently changed, but leaving older users in the advanced version they were used to? Okay, let me investigate the default UI for a moment...


So, yes I am logged in with advanced UI. I find its multi-panel setup excellent for scanning new toots, and quick interactions. When I find a toot that's attached to a longer thread, I instead find it detrimental and prefer to open that thread in a new tab.


I guess previously, the link attached to the timestamp in the corner of a toot was a direct link to the toot on its instance, which would take me to the default/public single column view with a single middle-click, or right-click and new tab. I was making use of this a lot in the past.

It seems now this link has changed to a local (mastodon.social) root with the instance information at the end of the URL instead, which is intended to open in the user's chosen UI (i.e. "advanced" in this case). When that changed, I would do what I did before, but the new tab instead opens a new instance of the advanced view again with all that other stuff not relevant to the toot. If I was intending to read it later, this often resulted in me coming to that tab later, finding it full of other information, and just closing it.

If I noticed right away it wasn't what I wanted, I'd close the new tab, go back to the toot in the previous tab, click the "..." menu and "open original page" to get there. A bunch of extra steps (admittedly due to my own confusion about the changes), but I could still get what I was looking for.

However, this got me to the situation that I'm in, where there's literally nothing I can click on a local toot to be able to get there. It only works for toots from other instances. For a local toot this view simply doesn't exist if I'm logged in and set to advanced UI. It seems I either have to change my user settings or be logged out (e.g. private window) to get there.


There is the second case of sharing links. If I want to link to a toot I found in my feed, I was used to right clicking the timestamp to get the link. My usual desire was to open it in a new tab so I could see how it would look for the person I'm sending it to, then pass it on. With the changes, it seems I get the correct link for a local toot (but I can't preview because it goes to advanced UI for me), and for a federated toot I get instead a link at the domain of my local instance, which I again can't preview, and also isn't the link I want to share because it seems inappropriate to bounce the person I'm sending the link to through mastodon.social to get to somewhere else.


So, maybe that illustrates what motivated me to make the suggestion. I was using the timestamp link as a tool for focused reading (singled thread view), and for sharing links. The timestamp link no longer works for either of those purposes anymore, and the case of local focused reading no longer has any direct access (which is why I move it to a private tab to log myself out).

So, I don't know if the way I was using the timestamp link was unusual? I can't speak for other users. Looking over it, I'm realizing it works that way with tweetdeck + twitter and I had been using it for both these purposes there for a long time, and it continues to work that way, at least from my end-user perspective. I brought that same habit to Mastodon when I came to it years ago, but it's one I now have to try to unlearn/replace.


Now that I know about the existence of the default non-advanced view... unfortunately I think taking away the advanced view is a big loss in a different direction. I very much prefer advanced view for scanning the feed and quick interactions, but I value a separate focused view for threads that require more significant attention. Until recently, I had both these things, but the focused view is becoming less accessible to me as the UI changes.


So, assuming my request isn't just a fringe issue, and is worth addressing, I guess the most direct suggestion I could make would be:
* 1. A user option that makes local instance links open the focused view when they're a new tab. Only reuse the advanced view when following a link from its own page.
* 2. A user option that changes the timestamp link into the "original page" link instead of being rerouted through the local instance.

Another alternative might be:
* Provide a "simple view" link for all toots (local and external) that has a URL that designates it should be viewed in the default single panel view when opened. Possibly in the "..." menu, but again the timestamp seems a really convenient place for this, and if so maybe that would want to be an option.

I'm sure many users like having everything open into to the advanced view, or are happy with default view, so I wouldn't propose to take that away from anyone.


The last comment about using the browser bar as a way to copy a link to a toot actually really confuses me. I hadn't even considered it. With the advanced view, there are so many things onscreen, and it's a bit hard for me to think that one of the 10 toots I can see is reflected by the browser's navigation URL. Maybe others consider that more intuitive than I do?

My intuition was always that a link to a toot should be in the physical vicinity of that toot. That's where I would look for it. The timestamp was always my go-to, and and once that stopped working the way I expected, the "..." became a slightly less convenient place to look, but the inconsistency of that menu for local/federated toots has made it a little weird.

**Comment by trwnh** [comment] 2023-01-08 02:14
> Was advanced originally the default, and subsequently changed, but leaving older users in the advanced version they were used to?

yes, it used to be the only UI available.

> Provide a "simple view" link for all toots (local and external) that has a URL that designates it should be viewed in the default single panel view when opened

this is effectively what i proposed, yes -- it would just require some big changes to how the preference for "advanced web UI" is handled and rendered. rather than being a switch for the whole UI, it would be a "mode" that the user can enter while logged in, perhaps served via `/deck` or some other URL dedicated to the multi-column view.

this way,

- opening a new tab should always take you to the single column view
- you should be able to get back to the multi column view at any point

**Comment by bbbradsmith** [comment] 2023-01-08 07:23
Yes, that would serve the desired purpose.

**Comment by trwnh** [comment] 2023-01-15 05:23
Oh, I just realized this is a duplicate of #21472

**Comment by bbbradsmith** [comment] 2023-01-15 06:07
Sure. I'll follow that issue then.

**Closed** 2023-05-19 06:22 UTC
Labels: suggestion
