### ISSUE TITLE
Boost and favourite count are out of sync

### ISSUE THREAD

**Issue by sorin-davidoi** [mastodon/mastodon#3166] opened 2017-05-20 10:23 UTC
When removing the favourite and boost status of a toot, the numbers in the `status_action_bar` get out of sync. The `unfavourite` and `unreblog` endpoints return the old values, probably since the work is async.
![](http://g.recordit.co/G408nT58Dw.gif)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by alexgleason** [comment] 2020-03-13 18:58
This issue seems to be fixed on the frontend in v3.1.2, although POST /api/v1/statuses/:id/unfollow still returns the old favourites_count

**Comment by xmflsct** [comment] 2020-11-01 00:29
Agree, using API endpoint to perform action is still unsync. Have tried `statuses/:id/favourite` and `statuses/:id/unfavourite`. Any update on this?

**Comment by vmstan** [comment] 2024-11-24 14:30
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.

**Closed by vmstan** 2024-11-24 14:30 UTC
Labels: api
