### ISSUE TITLE
Option to hide self boosts

### ISSUE THREAD

**Issue by Traivor** [mastodon/mastodon#23170] opened 2023-01-20 16:49 UTC
### Pitch

Some accounts have a habit of frequently boosting their own posts. @TexasObserver@texasobserver.social is one such. I get that they want to make sure their content is seen, but I really don't want to scroll past the same post over and over again.

I **DO**, however, want to see their boosts of other's posts, so hiding boosts altogether is not a good alternative.

Bonus points for making this available as both a global filter and a per account setting, the latter being the most useful.

### Motivation

Excessive self boosting pollutes follower's timelines.

This is similar to, but not the same as, https://github.com/mastodon/mastodon/issues/20093.

**Comment by AshKyd** [comment] 2023-02-08 05:45
This looks like a duplicate of https://github.com/mastodon/mastodon/issues/21632

**Comment by Traivor** [comment] 2023-02-08 14:55
> This looks like a duplicate of #21632

It does indeed. I guess the hyphen in that one defeated my attempts to find something already open.

**Closed** 2023-05-19 06:19 UTC
Labels: suggestion
