### ISSUE TITLE
Links to toots should open the toot in the Mastodon API instead of another webpage

### ISSUE THREAD

**Issue by Mbodin** [mastodon/mastodon#22561] opened 2022-12-20 15:24 UTC
### Pitch

On the web interface, when clicking on a link within a toot, the interface currently always opens a new tab, following this link.
However, sometimes this link points to a toot. I think that in such case, the toot should be opened directly within the Mastodon interface, as if copy/pasted in the search bar.

This could be implemented when displaying a link, by checking whether it comes from a federated instance. If it the case, clicking on this link fetches the toot. Otherwise, the link is left as-is.

This is the current behaviour within Tusky, but in my experience, is not Mastodon’s.

### Motivation

When being asked a question about something I did, I sometimes just refer to a toot of me describing what I did at the time. Frequently, this past toot was posted in follower-only mode, but it should not be an issue as the person asking me about it (let’s call him/her O) is following me.

And yet, I get a lot of responses like “this link is broken/dead”. The reason is that O clicked on the link instead of copy/pasting it into the search bar of Mastodon. Clicking on the link opens a new tab, in my instance. O is not from the same instance than me, so is not connected to Mastodon within this tab, so can’t see the follower-only toot.

In this situation, O is completely reasonable: clicking on a link is how a link is meant to be used. My way of doing is also reasonable: linking a toot using its link is what a link is there for. The issue there is that Mastodon assumes from the user a very unusual way of interacting a link: copy/pasting it in the search bar.

**Comment by rbairwell** [comment] 2022-12-21 02:35
Our of interest, which instance are you on? It sounds like that instance has https://docs.joinmastodon.org/admin/config/#authorized_fetch enabled which automatically stops non-ActivityPub clients (ie web browsers) directly fetching content.

**Comment by Mbodin** [comment] 2022-12-22 15:37
It’s aleph.land. From my understanding, this option only concerns public posts, so it doesn’t feel relevant here (the linked toot was follower-only).

For instance, I can access in incognito mode the following public toot: https://aleph.land/@MartinShadok/109524497031569311 I can’t (as expected) access in a web browser in incognito mode the following toot, in follower-only mode: https://aleph.land/@MartinShadok/109535840336761017 To me, this is the expected behaviour.

What is not expected to me is for Mastodon to open a new webpage when clicking a link to a toot, especially when the linked toot is follower-only.

**Comment by rbairwell** [comment] 2022-12-22 16:03
Okay, aleph.land is actually running [glitch-soc](https://glitch-soc.github.io/docs/) v4.0.2+glitch which whilst very similar to "core" Mastodon does have a number of features/enhancements such as [local-only toots](https://glitch-soc.github.io/docs/features/local-only-toots/)  and similar. I know @ClearlyClaire works a bit on glitch so she should be able to help a bit.

**Comment by nemobis** [comment] 2022-12-23 07:21
Is this issue similar to https://github.com/mastodon/mastodon/issues/22673?

**Comment by ClearlyClaire** [comment] 2022-12-23 07:51
Yes this looks like a duplicate of #22673

> Okay, aleph.land is actually running [glitch-soc](https://glitch-soc.github.io/docs/) v4.0.2+glitch which whilst very similar to "core" Mastodon does have a number of features/enhancements such as [local-only toots](https://glitch-soc.github.io/docs/features/local-only-toots/) and similar. I know @ClearlyClaire works a bit on glitch so she should be able to help a bit.

glitch-soc has indeed different behavior in that timestamps remain links to the original resource, rather than providing in-app linking, but that's not how I understand this issue: from my understanding, this issue is about having links in the post's contents recognized as links to fediverse resources, and have them open in the app.

**Comment by twilde** [comment] 2022-12-23 20:24
> from my understanding, this issue is about having links in the post's contents recognized as links to fediverse resources, and have them open in the app.

That's why I'm here, at least! 👍

**Comment by wolfteeth** [comment] 2022-12-27 20:33
It'd be good to have this in the web UI. I've been helping a new user who was very confused and frustrated by the current behavior taking her to a different server where she couldn't interact with the post. There is a story I have been hearing over and over about people being taken to other servers and not realizing it, and trying to re-login on the remote server's page. Of course it doesn't work, because it's not their home server. My partner did this. I think it is not obvious to many users that they went to a different site, especially if the remote server is also running Mastodon, so the UI looks very similar.

Worth noting that some third party apps already detect that the link is a post and pull it into the UI. Toot! for iOS has done this for a while.

**Comment by FlorianMarquardt** [comment] 2022-12-29 13:29
I agree with the good suggestion made here! It would make the whole experience of referring people to an earlier toot very seamless!

**Closed** 2023-05-19 06:26 UTC
Labels: suggestion

**Comment by wolfteeth** [comment] 2023-06-29 18:22
Curious as to why this ticket was closed without reason or response from the maintainers. This has been cited by multiple critiques of the Mastodon web software as a pain point for new users, and especially mobile web users, who may not realize they were just sent to a different site when they clicked a link to a fediverse post.

**Comment by trwnh** [comment] 2023-06-29 18:24
it's a duplicate of https://github.com/mastodon/mastodon/issues/22673

**Comment by wolfteeth** [comment] 2023-06-29 18:27
@trwnh ah okay, I missed that. Thanks.
