### ISSUE TITLE
Duplicate email notifications after 4.1.0 update

### ISSUE THREAD

**Issue by rixx** [mastodon/mastodon#23727] opened 2023-02-19 13:04 UTC
### Steps to reproduce the problem

1. Any action that triggers a notification, e.g. a new report
2. Receive multiple emails (up to 7 so far) for the new report
![2023-02-19T14:02:58+01:00](https://user-images.githubusercontent.com/2657547/219949824-7ad343c5-594a-4183-8035-3069e07a6c02.png)

### Expected behaviour

Only one email per notification issue

### Actual behaviour

Multiple emails, varying amounts

### Detailed description

The behaviour started with the 4.1.0 update.

### Specifications

Mastodon 4.1.0

**Comment by leahoswald** [comment] 2023-02-19 20:12
There is a still open report for the rc1 of 4.1.0 too: https://github.com/mastodon/mastodon/issues/23198

**Comment by ClearlyClaire** [comment] 2023-02-20 14:31
This looks like #23198 indeed, though I have no idea what's happening in that issue. What's your mail setup? Do you have errors showing up in sidekiq?

**Comment by leahoswald** [comment] 2023-02-20 15:22
We use an external mailserver and on this site nothing was changed. So we know it is a result of the update. This is the only mail related error I see:

Feb 20 16:02:03 worker01 bundle[1527793]: [ActiveJob] [ActionMailer::MailDeliveryJob] [be001321-1857-40ca-aec7-f232f1eb0c70] Error performing ActionMailer::MailDeliveryJob (Job ID: be001321-1857-40ca-aec7-f232f1eb0c70) from Sidekiq(mailers) in 6184.43ms: Net::ReadTimeout (Net::ReadTimeout with #<Socket:(closed)>):

But I see a connection on the mailserver and everything looks ok on this site. Maybe the timing of the disconnect from the mastodon worker is a bit off. Is there a timeout for the mail job? If so it could be a problem with the postscreen which delays the initial EHLO 2 to 6 seconds to block early speakers. Maybe the message is transferred already but mastodon thinks its a timeout and so it is retried multiple times.

**Comment by ClearlyClaire** [comment] 2023-02-20 15:40
A little over 6 seconds is indeed long and I could see that triggering a timeout. I don't remember any change in that area, though, but I'll investigate. The last release that worked as expected was 4.0.2, right?

**Comment by ClearlyClaire** [comment] 2023-02-20 15:56
I believe I found it!
We are not setting timeouts ourselves, but between Mastodon 4.0.2 and Mastodon 4.1.0, we updated dependencies, which pulled a new version of the `mail` gem had an undocumented change that went from having no timeout to having a default read timeout of 5 seconds (https://github.com/mikel/mail/commit/4f56234f04eb041810641ee0dfd717034a59b9dc)

**Comment by leahoswald** [comment] 2023-02-20 16:01
> The last release that worked as expected was 4.0.2, right?

Jup.



> We are not setting timeouts ourselves, but between Mastodon 4.0.2 and Mastodon 4.1.0, we updated dependencies, which pulled a new version of the `mail` gem had an undocumented change that went from having no timeout to having a default read timeout of 5 seconds ([mikel/mail@4f56234](https://github.com/mikel/mail/commit/4f56234f04eb041810641ee0dfd717034a59b9dc))

That sounds indeed like the source of the problem. Could be change it to something like 10 seconds to prevent this problem?

**Comment by ClearlyClaire** [comment] 2023-02-20 16:08
Can you try https://github.com/mastodon/mastodon/pull/23750 and see if it fixes your issue?

**Comment by leahoswald** [comment] 2023-02-20 17:16
Deployed. I will give you feedback later today (CET) or tomorrow.

**Comment by leahoswald** [comment] 2023-02-20 18:47
Sorry, the patch doesn't help.

**Comment by leahoswald** [comment] 2023-02-21 08:56
Sorry doesn't solve the problem :(

**Comment by ClearlyClaire** [comment] 2023-02-21 08:58
Thanks for reporting. Have you restarted all sidekiq processes after applying the patch? What is the timeout in the logs now?

**Comment by leahoswald** [comment] 2023-02-21 09:07
Now it's 10 seconds.

> 
Feb 21 10:02:45 worker01 bundle[2908560]: [ActiveJob] [ActionMailer::MailDeliveryJob] [4e20ddbf-0194-475a-8377-2e458b545c42] Error performing ActionMailer::MailDeliveryJob (Job ID: 4e20ddbf-0194-475a-8377-2e458b545c42) from Sidekiq(mailers) in 10204.98ms: Net::ReadTimeout (Net::ReadTimeout with #<Socket:(closed)>):

I don't get why it thinks there is a timeout. On the Mailserver side everything looks good and there are multiple accounts on this mailserver and everything works fine.

**Comment by evgeni** [comment] 2023-02-21 09:14
Could it be a behaviour change from the [Ruby 3.1 support in `mail`](https://github.com/mikel/mail/commit/d9d8dcc6bae1774a033ad488cea6217db3a3ebf3), that now pulls in `net-smtp` directly which might have a problem talking to your SMTP server?

**Comment by ClearlyClaire** [comment] 2023-02-21 09:16
> Which versions of the mail gem does mastodon use? I can't find it in the gem file or anywhere else.

Mastodon 4.1.0 uses `mail` 2.8.0.1. It's not a direct dependency but gets pulled by `actionmailer`. You can find the version in `Gemfile.lock`.

> Now it's 10 seconds.
> 
> `Feb 21 10:02:45 worker01 bundle[2908560]: [ActiveJob] [ActionMailer::MailDeliveryJob] [4e20ddbf-0194-475a-8377-2e458b545c42] Error performing ActionMailer::MailDeliveryJob (Job ID: 4e20ddbf-0194-475a-8377-2e458b545c42) from Sidekiq(mailers) in 10204.98ms: Net::ReadTimeout (Net::ReadTimeout with #Socket:(closed)):`

Interesting. Try changing to a even higher timeout? Or set it to `nil`?

**Comment by leahoswald** [comment] 2023-02-21 09:19
For the record we are still using: ruby 3.0.4

**Comment by leahoswald** [comment] 2023-02-21 09:21
> Mastodon 4.1.0 uses `mail` 2.8.0.1. It's not a direct dependency but gets pulled by `actionmailer`. You can find the version in `Gemfile.lock`.

The question is could I do a manual downgrade to the version in 4.0.2 to see if the problem is gone? Would help to pinpoint the source of the problem.

**Comment by evgeni** [comment] 2023-02-21 09:25
Ruby 3.0.4 has `net/smtp` 0.2.1 bundled in. 0.2.2 has an interesting changelog entry saying "Replace `Timeout.timeout` with socket timeout." So I guess downgrading mail and/or net/smtp is a good try.

**Comment by leahoswald** [comment] 2023-02-21 09:29
FYI: Just restarted the workers with a 60s timeout and until now there is no error in the log. 

> Ruby 3.0.4 has `net/smtp` 0.2.1 bundled in. 0.2.2 has an interesting changelog entry saying "Replace `Timeout.timeout` with socket timeout." So I guess downgrading mail and/or net/smtp is a good try.

Again I need to know the versions used by 4.0.2. I'm not that experienced in ruby to know where to find this information.

**Comment by ClearlyClaire** [comment] 2023-02-21 09:33
In Mastodon 4.0.2, there was no explicit dependency to `net/smtp` so it used the built-in one. But it also did not set *any* timeout, direct or indirect.

Mastodon 4.1.0 updated the `mail` gem, which introduced a default timeout of 5 seconds, and also added an explicit dependency on `net-smtp` 0.3.3.

> The question is could I do a manual downgrade to the version in 4.0.2 to see if the problem is gone? Would help to pinpoint the source of the problem.

Yes, you could try: `bundle add mail --version=2.7.1`

In general we do not recommend messing with your dependencies though, so please remember you made this change and undo it when we have sorted out the issue.

2.7.1 already had support for timeouts but no default one, so you could try a shorter timeout and see if the issue still occurs.

**Comment by leahoswald** [comment] 2023-02-21 11:45
I reduced the timeout from 60s down to 20s and it still looks like the problem is solved. So maybe 20s is a better default value than 10s. But I can check later if going down to 15s is an option too if yo want.

**Comment by ClearlyClaire** [comment] 2023-02-21 13:26
Thanks for the report! It would be interesting to try with 15s. It's also surprising it takes more than 10s in the first place. It's also surprising that this would not prevent the mail from being sent, but only the connection to cleanly close.

As far as your own configuration is involved, I would try to avoid the delay on the SMTP server's end if you can, since that delay will affect the job duration anyway.

**Comment by leahoswald** [comment] 2023-02-21 20:12
Ok, it looks like a 15s timeout works too. But if I go down to 10 seconds for a second test, I see the problem again within less than a minute. I could deactivate the postscreen check for the host that adds 2 to 6 seconds of delay or at all, but this is a setup not only I use, so it would be better to add a sensible timeout that is bigger than the default 5s to prevent others from running into the same problem. I would suggest 15s or for more of a safety margin 20s.

Still I don't know why the 4 seconds left, if we take the 10s timeout, are not enough there is no real reason on the mailserver site, which is indicated by the fact that the mail is send properly. As it is with 5s timeout most of the time. So there has to be a reason why the connection isn't closed in time leading the code to assume the mail wasn't send properly.

So I would say we've found a solution for the problem but not the cause yet. I will dig a little deeper with more debug logging in the next few days.

**Comment by leahoswald** [comment] 2023-02-21 20:30
Sorry, I forgot that mastodon uses the submission port (587) not 25 and postscreen isn't active at all on this port because all users are authenticated. So there is no delay from that. I'm currently digging trough the logs but need more time but I thought is is a interesting finding for the moment.

**Comment by ClearlyClaire** [comment] 2023-02-22 10:06
Thank you for your investigations! So this seems to be a mail server issue, although I have no idea what would be causing it.

Considering the annoying failure mode and the fact that it affected at least one other person, I'd still consider #23750 worthy of inclusion (though the annoying failure mode is for the `read_timeout` so maybe the `open_timeout` can be lowered back to 10 or 5 seconds).

**Comment by leahoswald** [comment] 2023-02-22 10:18
I just checked again and there was no new error in the logs over the last 12h so I think we can say it is solved.

And I agree with your suggestion that a read_timeout of 15 or 20 seconds is still a good idea and also that open_timeout could be lowered back to 5 seconds.

**Closed** 2023-03-03 19:37 UTC
Labels: bug
