### ISSUE TITLE
Improve Multiple Choice Poll discoverability

### ISSUE THREAD

**Issue by frumble** [mastodon/mastodon#18467] opened 2022-05-20 14:00 UTC
### Pitch

Currently, you have to click on one of the single choice radio buttons to change to a multiple choice poll in the Web UI. This has astonishing bad discoverability. Nothing wrong with the click-to-change but there should also be a proper checkbox in the poll creating UI for changing the type.

### Motivation

Currently, the discoverability is pretty bad and even worse for blind users.

**Comment by trwnh** [comment] 2022-05-20 22:21
Duplicate of #10873

**Closed** 2023-05-20 20:12 UTC
Labels: suggestion
