### ISSUE TITLE
Allow migration of account notes and lists

### ISSUE THREAD

**Issue by adeverteuil** [mastodon/mastodon#22188] opened 2022-12-09 19:16 UTC
### Pitch

Include account notes in the `following_accounts.csv` export.

Support importing account notes from CSV.

### Motivation

I noticed that when moving account to a new Mastodon instance, the `following_accounts.csv` exported file doesn't contain account notes. I like to keep notes on people I follow, to remember why I follow them. This information would be lost if I move to a different instance.

Workaround: I have a script that generates a CSV report of my following accounts, and fetches my account notes using the Mastodon API. I could add functions that writes account notes back to Mastodon from CSV.

**Comment by jayrope** [comment] 2022-12-09 22:42
+1 and adding, that while your workaround is great for nerds & geeks normal users need this included into a migration just so & without any further action required.

**Comment by connorshea** [comment] 2022-12-10 00:47
This issue should probably be focused on migrating notes. Lists are covered by a few other issues.

**Comment by ineffyble** [comment] 2022-12-10 01:03
Duplicate of #19959

**Closed** 2022-12-10 01:04 UTC
Labels: suggestion
