### ISSUE TITLE
Public profile privacy

### ISSUE THREAD

**Issue by Aldarone** [mastodon/mastodon#4098] opened 2017-07-07 13:32 UTC
Some people with a protected account on WitchesTown asked if it would be possible to hide every toots from their public profile when visitor are not following them (not logged in users as well) in order to reduce their exposition outside of the fediverse.

I think this feature would be beneficial to a lot of people.

Toots permalinks would still be active; public, unlisted and boosted toots would still be visible inside mastodon but the profile page would be seen as if every single toot were made with the « private » visibility (There is nothing here!) and the atom feed would be empty as well.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by clworld** [comment] 2017-07-10 02:39
Some thoughts:
* I think toots which you don't want to be displayed on public page must posted as private visibility.
* I think Mastodon should make dafault_privacy private when account is protected.
* Mastodon can not change visibility of old toots and toots posted as public is still displayed on public page after account is protected.
I think It's problem but solve this ploblem is difficult because toots are already federated.
(Some ad-hoc hacks can hide toots from public page but doing some special for public page is good thing?)
* Toots as public/unlisted from protected account is sometime useful I think. 
* It seems showing private toots on public page works for users on same instance but not for users on other instance (because instance does not know about other instances user).

**Comment by Aldarone** [comment] 2017-07-18 15:46
> I think toots which you don't want to be displayed on public page must posted as private visibility.

That's the point of this issue. Someone with a protected account might want to post something on the federated timeline or publicly reply to someone without these toots to be « easily » accessible from the publicly reachable archive like the public profile is.

IMO it's the same reasoning behind the absence of search for toots or profiles on mastodon.

**Comment by trwnh** [comment] 2023-01-26 23:41
Duplicate of #609 I think

**Comment by trwnh** [comment] 2023-05-14 00:06
Duplicate of #609

**Closed by trwnh** 2023-05-14 00:06 UTC
Labels: api, ui, suggestion
