### ISSUE TITLE
make post visible to a list(of users)/tag a list

### ISSUE THREAD

**Issue by no-1ne** [mastodon/mastodon#28070] opened 2023-11-25 06:23 UTC
### Pitch

currently there is a way to make post visible to specific users, can it be extended to make it visible to a list (and members in the list) by tagging the list 

### Motivation

while sharing, if it gets to more than few users, it gets cumbersome and repetitive and simply tagging a  list can be handy

![image](https://github.com/mastodon/mastodon/assets/11027129/03195fae-707c-4d4c-9cf8-17e79b88d703)

**Comment by trwnh** [comment] 2023-11-25 16:30
Duplicate of #14459

**Closed by trwnh** 2023-11-25 16:30 UTC
Labels: suggestion
