### ISSUE TITLE
Backup links are based on `S3_ENDPOINT` + bucket instead of `S3_CLOUDFRONT_HOST`

### ISSUE THREAD

**Issue by progval** [mastodon/mastodon#26546] opened 2023-08-18 16:22 UTC
### Steps to reproduce the problem

1. Set this in your config:

```
S3_ENABLED=true
S3_BUCKET=octodonfr2
S3_ENDPOINT=http://radosgw.sodium-fdfc:7480
S3_CLOUDFRONT_HOST=assets.oc.todon.fr
```

2. request a backup
3. click the link

### Expected behaviour

/backups/xx/download should redirect to https://assets.oc.todon.fr/backups/dumps/xxx/xxx/xxx/original/archive-20230818160701-xxxxx.tar.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxx&X-Amz-Date=20230818T160731Z&X-Amz-Expires=10&X-Amz-SignedHeaders=host&X-Amz-Signature=xxx

### Actual behaviour

/backups/xx/download redirects to http://radosgw.sodium-fdfc:7480/octodonfr2/backups/dumps/xxx/xxx/xxx/original/archive-20230818160701-xxxxx.tar.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxx&X-Amz-Date=20230818T160731Z&X-Amz-Expires=10&X-Amz-SignedHeaders=host&X-Amz-Signature=xxx

### Detailed description

If `S3_ENDPOINT` is not publicly reachable, then backups/exports are not downloadable.

If it is, it may cause extra billing due to bypassing the CDN.

### Mastodon instance

oc.todon.fr

### Mastodon version

v3.5.11

### Technical details

- Ruby version: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
- Node.js version: v12.22.12

**Comment by renchap** [comment] 2023-08-18 16:57
It seems you are running mastodon v3.5.11, please note that we will most probably not fix it in this version if we release a fix, and that we will soon stop providing patches for v3.5.

We encourage you to upgrade to a more recent version when possible.


> If it is, it may cause extra billing due to bypassing the CDN.

Those objects should never be cached (and should already have `Cache-Control: private` header in the response), as they may contain sensible data, so they will never be cached by your CDN

> If `S3_ENDPOINT` is not publicly reachable, then backups/exports are not downloadable.

This is a valid issue, I am not sure we even thought about this (very uncommon) use-case

**Comment by progval** [comment] 2023-08-18 17:47
> We encourage you to upgrade to a more recent version when possible.

I have issues with some of the changes in 4.0 so I'd rather stick with 3.5 for as long as it's supported.

Do you know if this issue is fixed in 4.1.x?

> we will most probably not fix it in this version if we release a fix

I'd be fine with applying a patch myself, but I wasn't able to find where in the codebase this URL is constructed.

**Comment by renchap** [comment] 2023-08-18 18:13
> Do you know if this bug is fixed in 4.1.x?

This behaviour is the same as what you described in 4.1 (and the upcoming 4.2)

> I have issues with some of the changes in 4.0 so I'd rather stick with 3.5 for as long as it's supported.

Have those issues been fixed by all the UX work that have been done in 4.2 by any chance? We plan to announce the EOL date for 3.5 when we release 4.2

> I'd be fine with applying a patch myself, but I wasn't able to find where in the codebase this URL is constructed.

This is done here: https://github.com/mastodon/mastodon/blob/bb23116e8d17b0fa7564a0f713c48753cfba7023/app/controllers/backups_controller.rb#L11

I am not sure why the host is not used here, maybe because we are using expiring URLs for security, and those need to be directed to the S3 endpoint directly?

**Comment by progval** [comment] 2023-08-18 18:26
> Have those issues been fixed by all the UX work that have been done in 4.2 by any chance? 

Partially. It adds support for Debian 12 after dropping support for Debian 11 in 4.0. There is still the issue of the public frontend being merged with the React app (requires JS and is considerably slower to load).

> We plan to announce the EOL date for 3.5 when we release 4.2

Thanks for the heads-up, I had been wondering about this.

> This is done here: 

Yeah I found that part but couldn't follow the thread from there

**Comment by ClearlyClaire** [comment] 2023-08-21 07:03
This issue seems like a duplicate of #24380

> I am not sure why the host is not used here, maybe because we are using expiring URLs for security, and those need to be directed to the S3 endpoint directly?

This is an underlying issue in Paperclip (see #2196) and possibly in the S3 libs we use. I do not fully grasp that part of the library and what we're expected to do exactly.

**Comment by progval** [comment] 2023-08-21 07:09
https://github.com/thoughtbot/paperclip/issues/2196, not #2196

**Comment by vmstan** [comment] 2024-01-01 16:12
Closed as duplicate and unsupported version.

**Closed by vmstan** 2024-01-01 16:12 UTC
Labels: bug, status/to triage
