### ISSUE TITLE
Respect user light/dark mode preferences?

### ISSUE THREAD

**Issue by j9t** [mastodon/mastodon#27183] opened 2023-09-28 07:55 UTC
### Steps to reproduce the problem

1. Switch to Mastodon dark or light site theme
2. Switch to light or dark mode on the operating system

### Expected behaviour

Mastodon switches to the other theme, respecting the system setting

### Actual behaviour

Mastodon keeps the theme, respecting the site/app setting

### Detailed description

It seems the implementation of Mastodon offers a dark _theme_, which is different from dark _mode_, but the implementation is not user-friendly and scalable as user’s general preferences are being ignored.

There are several approaches to improve this—for example, add a toggle that would ensure to respect `prefers-color-scheme`, or make the current themes style sheets that respect that media query—, but improvements would be great because it does seem counter-intuitive that a general dark or light mode preference would not be respected.

### Mastodon instance

mas.to

### Mastodon version

v4.2.0

### Browser name and version

Chrome; Brave

### Operating system

macOS 13.6; Android 13

**Comment by ClearlyClaire** [comment] 2023-09-28 09:03
Duplicate of #10976

**Closed by ClearlyClaire** 2023-09-28 09:03 UTC
Labels: suggestion, area/web interface
