### ISSUE TITLE
Feature: upload remote pictures via link

### ISSUE THREAD

**Issue by saggel** [mastodon/mastodon#2677] opened 2017-05-01 09:44 UTC
Coming from the forums world to mastodon I can't but miss a feature that also doesn't exist in the competing platforms: that of uploading a picture to your post that you found online.

I can imagine it'll be possible to have an option when you upload a picture to select whether you want to upload it from your computer, or to use an existing on the web, and in this case as to whether you want this to be a link or to transfer the picture to the server.

Here's a screenshot of this from a forum platform I used before mastodon

<img width="440" alt="screenshot 2017-05-01 11 39 22" src="https://cloud.githubusercontent.com/assets/7208257/25576941/e56ccb4a-2e62-11e7-95ff-9f73cf1a1086.png">
<img width="432" alt="screenshot 2017-05-01 11 39 33" src="https://cloud.githubusercontent.com/assets/7208257/25576942/e56df11e-2e62-11e7-9271-3dcf7dc258b9.png">

This is just do discuss whether it could be useful as a feature and maybe how could be done!
Keep up the good work!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment] 2017-05-01 14:12
There's two ways to implement this in the software:

- When you post a toot with a URL ending in .{png,jpg,jpeg,gif,...}, it interprets it as you posting a pic, retrieves it and attaches it to your toot.
- When it sees a URL ending in .{png,jpg,jpeg,gif,...} in a stream, it interprets it as an image, and either hotlinks it or retrieves it to display it.

I believe the second solution is what's implemented in BetterTweetDeck (cc @eramdam) but it could have privacy implications (since the user's machine would be retrieving arbitrary images from servers on the internet). 

Just my two cents.

**Comment by saggel** [comment] 2017-05-01 14:21
@wxcafe thanks for the idea for implementation :-) 
I take it that you like the feature suggestion :-)

I'm about to open a whole new topic with this sentence, but wouldn't your idea for implementation work also for let's say youtube videos?

**Comment by wxcafe** [comment] 2017-05-01 14:23
nah. Youtube videos aren't a file, you can't just `<img src=https://youtube.com/whatever>` them. Images, on the other hand, can be linked that way.

**Comment by saggel** [comment] 2017-05-01 14:24
Thanks :-) just had the thought :-)

**Comment by Komic** [comment] 2017-05-01 18:55
I'm pretty sure parsing and serving them just like the current user-uploaded images would be the right call.

**Comment by br4nnigan** [comment] 2017-05-04 15:52
> the user's machine would be retrieving arbitrary images from servers on the internet

Isn't that what we're doing on the internet all the time? You never know what you're getting.

**Comment by fwenzel** [comment] 2017-05-14 21:36
This appears to be a duplicate of #1162.

**Comment by trwnh** [comment] 2023-05-14 00:05
Duplicate of #1162

**Closed by trwnh** 2023-05-14 00:05 UTC
Labels: ui, suggestion
