### ISSUE TITLE
Suggest allowing use of WebP and Brotli to lighten loads on servers/client that support it.

### ISSUE THREAD

**Issue by DamonHD** [mastodon/mastodon#30019] opened 2024-04-21 17:58 UTC
### Pitch

Integrating support for the now-well-tested WebP image format (Accept: image/webp) and Brotli compression (Accept-Encoding: br) would reduce bandwidth demands significantly, eg during a preview stampede.

### Motivation

Save bandwidth all round (and reduce climate change)!

**Comment by renchap** [comment] 2024-04-21 21:28
Duplicate of #20896 for webp support (which would probably require a huge refactor of our media pipeline)

For Brotli compression, we already compress the assets using Brotli. It is up to the server admin to configure their webserver to serve those properly. For dynamic Brotli compression of the dynamic pages, same, this is up to the server admin to configure their webserver/proxy to compress on the fly, but this might not be a good idea as Brotli might have significant overhead.

**Closed by renchap** 2024-04-21 21:28 UTC
Labels: suggestion

**Comment by DamonHD** [comment] 2024-04-22 06:39
I don't believe that you are accepting Brotli compressed HTML pages from servers that offer them: not from my server for example.  My relevant HTML pages are precompressed with zopfli and Brotli but you appear not to accept-encoding br, only gzip.

**Comment by DamonHD** [comment] 2025-02-07 18:24
FWIW Mastodon 4.3.3 still does not seem to allow Brotli-compressed HTML pages to be fetched: the gzip version is fetched when both are available.
