### ISSUE TITLE
Federation with Lemmy

### ISSUE THREAD

**Issue by skariko** [mastodon/mastodon#18596] opened 2022-06-03 08:31 UTC
### Pitch

Hello, good morning everyone,
I am writing at the [suggestion](https://github.com/LemmyNet/lemmy/issues/2290#issuecomment-1145096692) of one of Lemmy's developers after asking for a feature for Lemmy.

I was told that it concerns the way Mastodon 'sees' Lemmy, so I was wondering if it could be improved.

In summary: A user from Mastodon who follows a Lemmy community sees posts via Title + URL. The problem is that if you post on Lemmy an image or an external URL the post on Lemmy becomes unreachable from Mastodon.

Some example:

Anyone who follows a Lemmy community from Mastodon sees, in case of image posted ([original post](https://feddit.it/post/6292)) this:
![immagine](https://user-images.githubusercontent.com/25532821/171814943-6f45c827-3b55-4e9c-b26b-59b2ad0373fa.png)

In case of external URL ([original post](https://feddit.it/post/6267)) this:
![immagine](https://user-images.githubusercontent.com/25532821/171815029-0dd5d8d9-4259-41a4-811e-4eb4c82dac62.png)

This is instead a normal post ([original post](https://feddit.it/post/6755)) withouth image or externarl URL (and how I think it should always be seen).
![immagine](https://user-images.githubusercontent.com/25532821/171815102-d75bbe29-7adb-4a67-a76f-6a7d4e5dae40.png)

As you can see on the first two it shows only the link to the pics or to the external URL and there is no way of seeing which is **the link of the post on Lemmy**.

## How could it be improved?
I think there two way to improve it:

- Allow Lemmy to post the entire message and not just the one referring to the title + URL. This would solve the problem regardless since the entire message would be seen and nothing would be lost.

- If this is not possible (or does not want to be done) I think it would be the case to always allow the link to Lemmy's original post (which as you can see from the images does not happen if an external image or URL is posted). That way those on Mastodon can, by clicking on Lemmy's URL, also see the entire post.

### Motivation

I think everyone would gain since the federation is one of the milestones of the fediverse is precisely the federation. Currently the federation with Lemmy is great but somewhat limited because if you post an image or a URL currently there is no way to know if there was anything else written within the post or not.

**Comment by ClearlyClaire** [comment] 2022-06-03 09:11
This sounds like a duplicate of #17003

**Comment by skariko** [comment] 2022-06-03 09:31
> 

Yes thanks, i can't find it. It is the same issue.

**Closed** 2022-12-08 11:25 UTC
Labels: suggestion
