### ISSUE TITLE
Apple Messages doesn't use og:description for link previews, resulting in previews that show user names, IDs, and avatars, rather than post content 

### ISSUE THREAD

**Issue by czyz** [mastodon/mastodon#22382] opened 2022-12-17 02:55 UTC
### Pitch

Hi, when sharing posts to friends via Apple Messages, the links nearly always expand into thumbnails that are just giant photos of the poster's avatar image and their name and username -- but it would be better if they showed up as an image from the post (only included if applicable) and the post contents.

I've attached a screenshot which shows the preview thumbnails in Apple Messages for these two links:
https://ohai.social/@pfadintegral/109523926407762788
https://apple.news/A0DljT-xsQn-cjzIGFVj7Bg

![Screenshot 2022-12-16 at 6 41 41 PM](https://user-images.githubusercontent.com/345036/208219888-c09d3464-89f5-4eb3-8619-ef02e01c3e26.png)

Mastodon pages put the user name and id in the og:title tag, the user's avatar in og:image (or the image from the post's contents if one exists), and it includes the post's text contents in og:description. 

I did a search on Apple's site and found some [documentation on the use of opengraph in Messages](https://developer.apple.com/library/archive/technotes/tn2444/_index.html). it appears that Messages does not use the opengraph og:description tag for these previews at all. So it is only displaying the og:title and og:image information when it expands a link in Messages into a larger thumbnail preview. This is why the thumbnail for the Mastodon post (top image in screenshot) doesn't contain post content.

Below it, the link from Apple News is showing a relevant photo, title, and publication name. So it is displaying og:title, og:image, and it also may be using the `<meta name="Author" content="Publication Name" />` tag, though this isn't listed in Apple's documentation. There are opengraph tags for this but I don't see them when I grab the article with wget.

It would be great if Mastodon links expanded to informative thumbnails when pasted into Apple Messages chats. I don't know if the solution is to fix this in Mastodon by changing the information included in og:title and og:image (maybe only conditionally for when the site is requested from Apple Messages) or if it's Apple's issue to fix. But the issue is adding friction to the process of sharing links in one of the largest messaging platforms. One often has to resort to sending friends screen captures of posts, rather than fill the chat with a bunch of large user photos and no post content.

### Motivation

Anyone using Mastodon on macOS or iOS would benefit from improving these thumbnails. It would make Mastodon content as easy to share as twitter content, which is a good thing.

**Comment by avi-c** [comment] 2022-12-17 04:24
This would be a small and very helpful change. It will also benefit other apps like WhatsApp, Apple Mail, Gmail, etc. that parse the OpenGraph tags similar to Apple Messages.

**Comment by connorshea** [comment] 2022-12-17 06:06
I believe this is a duplicate of #20569. I investigated this behavior in that issue, and unfortunately I'm fairly certain that the Twitter domain is special-cased. I think Mastodon's embeds behavior here could definitely improved somewhat without any changes on Apple's side of things.

**Comment by ineffyble** [comment] 2022-12-17 15:16
Duplicate of #20569

**Closed by ineffyble** 2022-12-17 15:16 UTC
Labels: suggestion
