### ISSUE TITLE
Rename "Publish" to "Send" for Direct messages

### ISSUE THREAD

**Issue by dewey** [mastodon/mastodon#20156] opened 2022-11-08 18:58 UTC
### Pitch

Currently if you write a new Direct message the button is labeled "Publish" with a lock icon. I believe it would be less confusing to label it "Send" or something similar to make it clear it's a Direct message and not a post.

<img width="342" alt="Screenshot 2022-11-08 at 19 53 47" src="https://user-images.githubusercontent.com/790262/200651248-527d3280-1a9c-4d2b-87e5-2c6f0553ba42.png">

### Motivation

The lock icon isn't explicit enough in communicating it's a direct message and more of a "chat" than a new public post. The lock icon could be interpreated as "unlisted post" or "private post because my account is private".

**Comment by MattWilcox** [comment] 2022-11-09 09:09
Disagree - you are in fact publishing, and I like the reminder that this wording gives. You know it's a DM because you yourself made it a DM by @user@instance.ext right at the start. There's no confusion about your intent for this to be a DM.

"Send" might give the impression that DM's are private, and they are not.

**Comment by dewey** [comment] 2022-11-09 09:30
> There's no confusion about your intent for this to be a DM.

Me opening this issue, seeing other people being confused about it and [articles being published](https://gizmodo.com/mastodon-how-to-dm-send-messages-twitter-1849759852) about it online make it very clear that there can be confusion.

> And here’s where most people seem to get confused. When you DM someone on Twitter, it opens up this special folder that makes it abundantly clear the message you’re typing is a DM. Mastodon doesn’t do this. When you click the DM button on Mastodon, it sends you to the same text box that you’d normally to type posts for everyone to see.

I think it's similar to how Twitter started implementing DMs where you had to prepend your Tweet with the letter `d` to make it a DM in the same interface that's also used to send a public post. There's a good reason this was changed as people accidentally sent DMs as public posts. I think there's a way to make this less confusing while still retaining the disclaimer that this is not a "private" message, just like messages on old internet forums that were always "private", but in reality stored in plain text. Nobody was confused about that there either.

**Comment by MattWilcox** [comment] 2022-11-09 11:44
There might be a better UI to make things clearer, you're right. I'm not sure that just changing the button text does that though :/

A lot of things are relying on already understanding the context of how Mastodon works, and I'm seeing some confusion from people that do not and expect things to be "just like Twitter", when things aren't - and by design.

Back to the main question: why do you feel that "publish" is confusing as a commit action message when writing a DM?

**Comment by dewey** [comment] 2022-11-09 11:50
> Back to the main question: why do you feel that "publish" is confusing as a commit action message when writing a DM?

I agree that maybe just changing the button text isn't solving the problem, but it's a first step. For me "publish" means making something publicly known, or share with many people (Publishing a book, publishing an newsletter,...). This is also what [online dictionaries](https://www.merriam-webster.com/dictionary/publish) say.

I know that technically it's not private (in the sense of encryption) but it's private as it's between two people and not visible to the public by default (Unless I'm misunderstanding something).

**Comment by MattWilcox** [comment] 2022-11-09 22:56
I think we're both of the same understanding, just differing on the utility and implication of the wording.

By using "Send" the _implication_ is that the message is private. It's only "sort of" private though, so this is a bit of a false implication. Is it a big risk? Not likely.

Conversely, "Publish" is also slightly wrong, you're publishing it - just only to the intended recipient _and any admin_. Which is the gotcha. At least if it remains "publish" there's not an implicit idea that the communication is private.

So the question is which is worse for a user: a partially inacurate "publish" label or a partially inacurate "send" label?

In either case, I don't think there's any confusion that *the intended recipient will be directly notified*. The confusion is *will I realise who else can see it?*

**Comment by trwnh** [comment] 2022-11-09 23:33
I think ultimately the wording is actually not that significant -- you could make public posts say "Send" as well, and it wouldn't even be wrong. Like "Send tweet" or "send post" in common usage.

**Comment by mu-arch** [comment] 2022-11-11 02:04
At risk of going off topic here, but, I believe the entire private messaging system (inb4 "it's not a private message system" in that case we need to address adding one) has bigger problems. Private messages should not be showing up in a user's feed at all, nor should mentioning another user's @handle inside the DM pull the other party into the private message. It's extremely confusing for new users, because they believe it works like other sites they are used to.

Conversely, if private messages are not going to be a goal for Mastodon then that needs to be communicated clearly to users.

**Comment by trwnh** [comment] 2022-11-11 02:32
@mu-arch there are several other issues related to the availability (or not) of "messaging", which would probably be better suited than this one for the kind of discussion you are trying to have. nonetheless, to reiterate, there are no messages-in-a-separate-context, there are only statuses-in-your-inbox. a separate context for messaging is planned, just not ready yet.

**Comment by JetForMe** [comment] 2022-11-11 06:28
I agree with the OP that it should be "Send" and not "Publish."

**Comment by MBeggiato** [comment] 2022-11-11 10:22
Another possible solution would be, to add an information above the input like "This post will only be visible to @xyz". This wouldn't break the current "post" wording and would make it clearer, that this is fact is an DM.

**Comment by TymeForChange** [comment] 2022-11-12 21:16
**Alternatively, or in addition to:** When clicking the DM icon, the message composition window would change to a unique color -- as a clear visual signal that you are in DM mode. Likewise, have the viewed DMs display that same unique color.

**Comment by daprice** [comment] 2023-02-08 00:22
IMO the lock icon is the worst thing here, even moreso than the wording. At first I thought it meant there was something preventing me from clicking it. Every lock icon I’ve ever seen on a UI element meant either “this functionality is locked, you can’t do it” or “click this to lock something”, neither of which has anything to do with this particular case.

It doesn’t help that, according to the nearby privacy menu, the same lock icon means “followers only” whereas the “@“ symbol means DM. Showing the “followers only” icon when the privacy is set to DM looks more like a bug, and simply replacing the lock icon with the “@“ symbol would make it pretty clear even if the wording remains “Publish”.

**Comment by Unifex** [comment] 2023-02-14 20:38
> There might be a better UI to make things clearer, you're right. I'm not sure that just changing the button text does that though :/

I was thinking that having a solid border around the post form that had a different colour for each post style may do the job.  Have that border colour mirrored on the Privacy selector button to give a very obvious indicator of what set that colour would, in my mind, tick all the boxen for fixing this.

**Comment by TymeForChange** [comment] 2023-07-14 15:31
> > There might be a better UI to make things clearer, you're right. I'm not sure that just changing the button text does that though :/
> 
> I was thinking that having a solid border around the post form that had a different colour for each post style may do the job. Have that border colour mirrored on the Privacy selector button to give a very obvious indicator of what set that colour would, in my mind, tick all the boxen for fixing this.

Or, as I suggested in November, re: https://github.com/mastodon/mastodon/issues/20156#issuecomment-1312573480

_Alternatively, or in addition to: When clicking the DM icon, the message composition window would change to a unique color -- as a clear visual signal that you are in DM mode. Likewise, have the viewed DMs [in feed/columb] display that same unique color._

...as a border alone might not stand out enough. Requires the same code to achieve either.

**Comment by TymeForChange** [comment] 2023-07-14 15:47
I agree that the button should be renamed for DM/PMs.  "The word publish is too similar to the word public (by design), and an inference is easily made.  Even naming the button "DM" or "PM" (rather than 'publish'), depending on the final name of the feature/feed-column, would be an improvement. 

And, the sender's DM/PMs definitely shoud NOT be appearing in the main feed, as they do now. They should ONLY appear in the DM (/PM) feed/column. 

Anything and everything that can make this DM/PM feature more comfortable for users is a win. 

Because Mastodon accounts themselves cannot be 'private' (unavailable to non-followers, as they are on Twit), one must take greater care when posting to set the visibility correctly. Sadly, you can't simply Edit a post to change that visibility.

**Comment by TymeForChange** [comment] 2023-07-14 16:17
> You know it's a DM because you yourself made it a DM by @[user@instance.ext](mailto:user@instance.ext) right at the start. There's no confusion about your intent for this to be a DM.
> 

Dude, that's not even true. If you simply reply to someone's public OP, it begins with their handle; but it is viewable for others, as well -- the extent of which dependent on whether it was replied to using global, unlisted, or followers only.

**Comment by trwnh** [comment] 2023-07-14 17:07
if i mention 10 people and make that post mentions-only, then i am technically still "publishing" to a limited audience of 10. if i make a followers-only post and i have only 1 follower, i am still "publishing" to a limited audience of 1. it's not a different action. publication with a limited audience is still publication. don't confuse "publish" or "publication" with "public" -- they share the same root but have different meanings.

regardless, as stated above,the button could say "send" for posts addressed to "public" as well. the important thing is that the button should say the same thing for all audiences, since it denotes an invariant action. for what it matters, you could also rename "public" to "everyone" or "anyone", to further disambiguate it from the act of publication or publishing.

**Comment by TymeForChange** [comment] 2023-07-14 17:14
> if i mention 10 people and make that post mentions-only, then i am technically still "publishing" to a limited audience of 10. if i make a followers-only post and i have only 1 follower, i am still "publishing" to a limited audience of 1. it's not a different action. publication with a limited audience is still publication. don't confuse "publish" or "publication" with "public" -- they share the same root but have different meanings. 

You continue (in this post and others) to harp on the "technically" when we all are describing the user experience and expectation. Those can be incongruent. What matters is the UI/UX.

**Comment by anuyts** [comment] 2023-07-14 17:27
> if i make a followers-only post and i have only 1 follower, i am still "publishing" to a limited audience of 1.

Restricting your Mastodon followership to a single account is not the intended typical usage of Mastodon and therefore should not guide the design of the UI.

> if i mention 10 people and make that post mentions-only, then i am technically still "publishing" to a limited audience of 10.

In postal or e-mail correspondence, this is typically called sending.

What is different is that the audience is chosen ad hoc, for every message, by the author. In publishing to your followers, the set of followers is a given. Moreover, it is the followers who take the initiative to (request to) become a follower.

There are Wiktionary pages about [sending](https://en.wiktionary.org/wiki/send) and [publishing](https://en.wiktionary.org/wiki/publish). In the relevant meanings of publishing, the audience is in some sense "the public". In the case of sending, on the contrary, the recepient is generally specified ad hoc, e.g. "I send you a letter" vs. "I publish an article".

**Comment by trwnh** [comment] 2023-07-14 17:41
If the expectation is wrong, then we shouldn't lie about what's actually happening. See #3819 for *actual* "messages". This issue as filed currently starts from a faulty premise:

> make it clear it's a Direct message and not a post.

**There is no such thing as a "message" in current Mastodon.** There are **only** posts. Saying anything to the contrary doesn't magically make it true. Rather than making the UI/UX seem *more* like a message, it should actually seem *less* like a message. The fact that they're posts should not be a point of confusion. Audience is a separate dimension from context.

Given the above, this issue is currently invalid. However, I am not closing it because there is still a discussion to be had about the point of confusion expressed by OP. If #3819 would address the concern, I can close it in favor of #3819. Otherwise, we could make the button *always* say "Send", or we could rename "Private mentions" once again if indeed people are getting confused by it. Or we could do some other thing to clarify the situation. But what we're *not* going to do is start treating certain posts as if they're not posts.

> What is different is that the audience is chosen ad hoc, for every message, by the author.

This is *always* true. The audience is chosen ad-hoc by the author, for every post, based on the union of the scope and the mentions. `Public` is just another recipient in the total audience. If you want to call *every* post a "message", that's fine. But that would potentially be misleading, since "message" has come to mean something different than "post". There is the concept of a messaging context, where "messages" are grouped by recipient or chat room -- this is what #3819 covers. Posts do not exist in that context. They are generally grouped by the tree of replies, or by author on a profile, or in the timelines of recipients.

**Comment by anuyts** [comment] 2023-07-14 19:06
Well despite the "faulty premise", there are a lot of valid concerns and constructive proposals to address these in the above discussion. The following two suggestions do not seem incompatible with your take on the matters:

* Replace "Publish 🔒" with "Publish @" in case of a "Mentioned people only" post.
* Give such posts a colored background or highlighted border, both when typing and when reading.

The only reason I can think of to object to these proposals, is when you're in favour of creating confusion between both "publication" options, in which case I would propose to abolish "Mentioned people only" posts.

**Comment by trwnh** [comment] 2023-07-14 19:58
I don't think there's anything wrong with changing the icon, but I'm not sure what the second proposal is intended to accomplish. Mentions-only posts have been the subject of confusion, but I don't think there's a reason to remove them outright. It would be better to clarify that "they're just posts", and that they exist in the same thread as public posts. I personally frequently use "mentions-only" in reply to posts which are not "mentions-only", because they are continuations of the thread for which I would like to limit the audience, akin to pulling someone aside at a party and telling them something directed at them, but with the chance that others may overhear, or others might get pulled in later or wander off. Example:

```
A1: this is a Public post
B2, in reply to A1: @A this is a Public reply
A3, in reply to B2: @B this is a followers-only reply, visible to A, A's followers, and also to B (who may or may not follow A
B4, in reply to A3: @A this is a followers-only reply, visible to B, B's followers, and also to A (who may or may not follow B)
A5, in reply to B4: @B this is a mentions-only reply, and I am mentioning @C. it is visible to A, B, and C only.
B6, in reply to A5: @A this is a mentions-only reply which drops the mention of C. it is visible to B and A only.
C7, in reply to A5: @A @B this is a mentions-only reply. it is visible to C, A, and B.
```

To C, they only see posts A5 and C7. If C follows only A, they will see posts A1, B2, and A3, as well as A5. If C follows A and B, they will see the first 5 posts and C7. If C follows only B, they will see post B2, as well as B4 and A5 and C7.

Now, we could have an 8th post replying to either A5 or B6; this 8th post could have a scope of Public, despite being in reply to a mentions-only post. This wouldn't make any sense in a "messaging" context, but it's perfectly valid in a "post" context. You're not in a private room. You're still at the party with everyone else, in public. This is what I meant when I said that publishing to a limited audience is still publishing. There's no difference in whether it's 1 or 10 or 100 or 1000 or a million recipients. It gets federated as an activity, which is sent/delivered to relevant inboxes, and then interpreted by Mastodon as a post which gets inserted into timelines, attached to a reply-tree, etc. Everyone mentioned is a recipient. Your followers collection is a recipient. The "Public" pseudo-collection is a recipient. You could also theoretically address to people who are not mentioned, but Mastodon doesn't currently let you do this -- it collapses mentions and addressing together. This is a UX decision intended to make the experience more like old pre-2014 Twitter. If you undid this decision, you'd end up with what is basically email, where you choose your recipients separately from who you mention in the body of the content. Consequently, it would be possible to mention someone without delivering to them.

**Comment by anuyts** [comment] 2023-07-14 20:10
At a party, it's impossible to mistake whether you're standing on the table and addressing everyone interested, or taking someone aside. Nor whether the person addressing you is standing on the table or taking you aside.
My second proposal - the colored box/background, both when typing and when reading - intends to make this equally clear on Mastodon. Because confusing one for the other can cause real embarrassment.

**Comment by TymeForChange** [comment] 2023-07-14 20:26
And, both a public reply and a mentions-only post begin with a handle. Better to err on the side of caution.  

The OP raised a UI/UX issue that several others have agreed wants for a clarification. We have offered viable solutions. It's like 1 line of DHTML code!  If true Private Messaging ever happens, that will need another level of clarification. 

trwnh, if you are so troubled by UI/UX clarifications, make this suggested modification the default and allow users to disable it in their Settings.

**Comment by trwnh** [comment] 2023-07-14 21:12
I'm not troubled by UI/UX clarifications. I'm troubled by the proposed change *obscuring* the reality of the situation. The more "special treatment" you give to mentions-only posts, the more likely it is that people will confuse them for "direct messages", **which they are not**. Currently they are highlighted on display (with a header, a lightly accented background, and an @ icon), but not in the compose box (unless you consider the warning box to be a form of highlight). Previously, they were not highlighted (just an @ icon), and before that, they were highlighted less prominently (without the header, just a lighter background as well as the envelope icon).

If it's a question of "Send" vs "Publish", then making it only *sometimes* say "Send" is *more* confusing, not less confusing. It is even more confusing if it causes people to mistakenly assume that they are sending messages instead of posts. We should clarify that regardless of whether you are "sending" posts or "publishing" posts, they are still posts. Both are correct in all cases; you "send" the activity to recipients, at which point it gets "published" in timelines, and this does not depend on the scope of the post.

Put another way: the problem that should be solved is not what the button's text *says*. It's what the button's text *implies*.

In summary:

- If you are arguing that it should say "Send" `to make it clear it's a Direct message and not a post` then this is wrong.
- If you are arguing that `it's a direct message and more of a "chat" than a new public post` then you are mistaken.
- If you are comparing them to being `just like messages on old internet forums` then this is inaccurate -- it is as if you posted a message in a forum thread that only certain people can see; it won't end up in your "PM" inbox, it'll end up *in the thread*.
- If the size of the audience matters to you, then you should know that the audience size is not at all correlated to the scope; there is no limit on how many people you can mention/address, and you can in fact mention/address more people than follow you. The only limit is indirectly, via the character limit.
- If you believe that `Private messages should not be showing up in a user's feed at all, nor should mentioning another user's @ handle inside the DM pull the other party into the private message`, then you are asking for #3819.

**Comment by anuyts** [comment] 2023-07-14 21:49
> Currently they are highlighted on display (with a header, a lightly accented background, and an @ icon),

Good, I was unaware of this, my instance must be running an older version.
That leaves the @ on the publish-button and the highlight for the compose box TBD.)

I wasn't suggesting chat-like functionality, but comparing to how Zoom deals with a similar confusing situation. In the chat of a (very populous) Zoom call, all messages appear in the same feed. Those that are not posted to everyone but to restricted people, are (IIRC) marked as such in a red font. This is clear and not confusing.

You are very concerned about not setting false expectations. Is this for privacy reasons or merely for clarity as to how Mastodon works?

**Comment by TymeForChange** [comment] 2023-07-14 23:55
> I'm not troubled by UI/UX clarifications. I'm troubled by the proposed change _obscuring_ the reality of the situation. The more "special treatment" you give to mentions-only posts, the more likely it is that people will confuse them for "direct messages", **which they are not**. 

But, they are direct posts if, _and only if_, the composer selects that option from the Composition Window options. And, it is that fail-point that the OP (and others) has addressed.  Perhaps they should be called Direct Posts, eliminating the word "message" if that implies more inherent privacy than is actually occurring.  If they don't function as users expect from using other social media, give that feature a unique Mastodon name -- therein lies the greatest confusion.  Then, the user has to pay more attention to what the help text states is the action. There will be many users who go back and forth between similar social apps, even daily. If there is no universal functionality and name for such a feature, make it unique. 

For that reason, there needs to be very good clarification, to help users understand how this visibility option works on Mastodon.  Just putting up a warning saying a PM isn't end-to-end encrypted really isn't helpful.  People pretty much know that about Twit, too (that anyone with access to the "mechanics" could read it).

Making the argument that people are trying to make Mastodon = Twitter is misguided.  No matter the app, there is good and bad UI/UX.  We, in this discussion, have made cases for improvements. 

====

Can of worms opened: I have never liked the term "Publish" on the button. It just has a different connotation in general and certainly in platforms like Wordpress. I'd probably recommend "Post" over it, if asked. Even if this was used for all options, but the "@" symbol appeared next to the word on the button for the Direct Posts, it'd be a slight clarification, maybe.  

From UI/UX, I see and explain the behavior thusly by visibility greater to lesser:

Post to Public
Post to Fediverse
Post to List **
Post to Followers
Post to Individual(s)

** wish list

NOTE: The post-to-public (globe icon) is an important point to make. Because you are literally posting for anyone, even outside of Mastodon, to see.  I'm not sure new users quite get that.

**Comment by trwnh** [comment] 2023-07-15 01:54
> Perhaps they should be called Direct Posts, eliminating the word "message" if that implies more inherent privacy than is actually occurring.

Perhaps indeed. Currently they are not called "messages" anywhere, but they used to be called direct messages many years ago, before getting renamed to mentions-only statuses, before getting renamed to private mentions quite recently, and even that is still confusing: #24837

Personally I prefer "mentions-only post" as a parallel to "followers-only post". If it were up to me to revamp the whole compose box, I'd make the following changes:

- `Change post privacy` -> `Set post visibility`
  - `Public` -> `Discoverable`
    - `Visible for all` -> `Visible to anyone, and included in discovery features`
    - (This one has a caveat in that old "public" posts need to be migrated to a scope that shows them in public timelines but doesn't include them in full-text search, in order to not grant retroactive consent.)
  - `Unlisted` -> `Anyone`
    - `Visible for all, but opted out of discovery features` -> `Visible to anyone`
    - (This one is another oft-confusing feature for newcomers. I can't tell you the number of times I've had to inform people that making their replies unlisted will generally not have any effect within Mastodon. It might matter for other implementations, though.)
  - `Followers only` -> `Your followers`
    - `Visible for followers only` -> `Visible to anyone that follows you, plus anyone you mention`
    - (Another point of confusion, but rarer: some people assume that mentioning someone won't let them see it unless they are following you.)
  - `Mentioned people only` -> `Mentioned users`
    - `Visible for mentioned users only` -> `Visible to anyone that you mention in this post`
    - (The warning box above would also be reworded to highlight that all mentions count, not just the ones at the beginning.)
      - `Posts on Mastodon are not end-to-end encrypted. Do not share any sensitive information over Mastodon. [Learn more]` -> `This post will be sent to anyone mentioned, including mentions not at the beginning of the post. This is not a private message. Do not share any sensitive information over Mastodon.`
    - (There is also #18363 which proposes a "safeguard mentions" feature, turning this warning into an active confirmation that must be disabled in settings.)

> If they don't function as users expect from using other social media, give that feature a unique Mastodon name

An alternative to "Mentioned users", "Mentions-only post", etc. is to maybe call them "whispers". This would be analogous to, say, Minecraft, where the chat message isn't visible to everyone, but ops can still see the message in their chat log in-game, as well as in their server logs. That's still not entirely clear on the semantic difference between a post and a chat message, but it's probably better than "private mentions"?

> Post to List ** wish list

See #983. There is a point of contention in that the Lists feature is for organizing your *following*, not your *followers*. The inverse feature would be most commonly known as Audiences, Circles, or Aspects. There's also some minor protocol changes that need to be made in order to allow addressing arbitrary actors without leaking the full list of recipients.

> I wasn't suggesting chat-like functionality, but comparing to how Zoom deals with a similar confusing situation. In the chat of a (very populous) Zoom call, all messages appear in the same feed. Those that are not posted to everyone but to restricted people, are (IIRC) marked as such in a red font. This is clear and not confusing.

From a UI perspective I'd personally reserve highlights for when you're mentioned anywhere in the body of the content. Tangentially, I also use a userstyle that de-emphasizes mentions-only posts and makes them blend in with the background.

> You are very concerned about not setting false expectations. Is this for privacy reasons or merely for clarity as to how Mastodon works?

Both. The incorrect expectations lead to people making harmful mistakes. For example, `@friend please watch out for @badperson` will send the "message" to both `friend` and also to `badperson`.

**Comment by anuyts** [comment] 2023-07-15 05:54
> Both. The incorrect expectations lead to people making harmful mistakes. For example, `@friend please watch out for @badperson` will send the "message" to both `friend` and also to `badperson`.

But at least `@badperson` is visible in the post, whereas `@followers`, `@world`, `@discoveryfeatures` are not. This is why I think posts with neither of those three **typically** large-scale audiences should look different, both when reading and when writing.

> From a UI perspective I'd personally reserve highlights for when you're mentioned anywhere in the body of the content.

But it's important to know whether someone is shoutig or whispering to you, and whether you are shouting or whispering to someone, and to not mistake one for the other, and the distinction is just not all that clear if you don't have e.g. a different background/box.

On top of that, mentions of yourself could be highighted or something.

> Tangentially, I also use a userstyle that de-emphasizes mentions-only posts and makes them blend in with the background.

Anything that makes them look really different is good!

> * Post to Public
> * Post to Fediverse

This does not clearly reflect the functionality.

Perhaps between text and post button there should be a notice:
```
[📢 Included in discovery features.] Visible to [🌎 public,] [👥 your followers,] [explicitly relist all people mentioned,] and ⚖️ moderators. 🔓 Unencrypted.
```
Then the button should always just say "Post".

**Comment by anuyts** [comment] 2023-08-10 19:01
Quoting @trwnh 
> Currently they are highlighted on display (with a header, a lightly accented background, and an @ icon), but not in the compose box (unless you consider the warning box to be a form of highlight).

As far as I can see, there is no such special header or highlighting for "Mentioned people only"-posts in v4.1.6.

**Comment by trwnh** [comment] 2023-08-12 02:03
it should be in 4.2

**Comment by xgpt** [comment] 2023-08-20 13:16
> A lot of things are relying on already understanding the context of how Mastodon works[...]


This is a bug, not a feature.

The end user should not have to care about how the postal service works in order for their letter to arrive to the addressed destination.

Nor should a user misunderstand if they are writing a sealed letter or writing a postcard to their friend (mentioned either way, but private vs public post)

**Comment by trwnh** [comment] 2024-01-26 04:56
> the button should always just say "Post".

This is now the case. Also, in the latest commits, the "direct" scope now looks like this:

![image](https://github.com/mastodon/mastodon/assets/10606431/347fa241-1253-4af6-a460-3c90b5734bca)

Hopefully this helps reduce the confusion, and clarifies that it is a "post" like any other.

**Closed by trwnh** 2024-01-26 04:56 UTC
Labels: suggestion

**Comment by anuyts** [comment] 2024-01-26 11:44
Does this mean the lock emoji on the post button is also gone?

Also, is there a good reason why coloring "Specific people"-posts has been accepted as a good feature, but coloring the message composition box for such posts has not?

**Comment by trwnh** [comment] 2024-01-27 17:27
> Does this mean the lock emoji on the post button is also gone?

Yes, there are now no icons next to the "Post" text.

> Also, is there a good reason why coloring "Specific people"-posts has been accepted as a good feature, but coloring the message composition box for such posts has not?

I'm not sure. The coloring has been added and removed at various points before, as some people complained either way.
