### ISSUE TITLE
Allow for multilanguage toots and/or manual translations

### ISSUE THREAD

**Issue by juju2143** [mastodon/mastodon#21530] opened 2022-11-24 01:13 UTC
### Pitch

As far as I know, the language picker in the compose box only allows to pick a single language in which the toot will be written in. What happen if you write a toot in more than one language? Wouldn't it be nice to pick more than one language? Or even better, a way to translate toots manually as you compose them, with a way to switch the toot's language when read?

### Motivation

This is something you often see in countries and communities with more than one official language, such as Canada or Belgium, or even Native American communities where a effort is done to revive their ancestral language (although you'd need to add it in the picker in the first place, which isn't quite the point here). Given enough space, posts aimed for the entire country, especially where you can't assume every of your readers knows English, often will be translated manually and written in every official language in the same message.

For instance, Facebook has one such feature to compose posts with manual translations, which is something I'd like to see on Mastodon, but ithe translation you see is tied with the language you set the interface on with about no way to see the other translations, which is kind of a bummer and why it's barely see it used as far as I know.

**Comment by ineffyble** [comment] 2022-11-24 01:23
Duplicate of #18241.

**Closed by ineffyble** 2022-11-24 01:23 UTC
Labels: suggestion
