### ISSUE TITLE
"Incase You Missed It" in the timeline

### ISSUE THREAD

**Issue by Freeplayg** [mastodon/mastodon#20728] opened 2022-11-15 02:19 UTC
### Pitch

Something to show less frequent posts higher up in the timeline

### Motivation

Some post more often than others, and those who don't post as much get buried in the timeline. I think it can be especially bad for artists who only post their art when they're finished.

I think this is fine as long as it's not based on popularity or what it thinks you may like. And if wanted, add a button to go back to chronological only.

(I don't know if this has been posted before or not, I may have searched for the wrong terms)

**Comment by MenschenToaster** [comment] 2022-11-19 22:39
> This is probably a dumb question, but: have you considered subscribing to their posts? (The bell icon on their profile.)
> 
> I'm suggesting this because I know I and others appreciate Mastodon showing things only in the order that they're posted, no "algorithms" involved. In a war between "some reordering" and "no reordering", I'm not sure who would win!

I feel like a togglable algorithm would be really nice. I know many really appreciate mastodons ordered feed but I would prefer seeing what the people I follow like or what I've missed and stuff like that

**Comment by MenschenToaster** [comment] 2022-11-19 22:42
And this is probably a duplicate of #18352

**Closed** 2023-05-20 20:22 UTC
Labels: suggestion
