### ISSUE TITLE
Feature request: allow followed hashtags to be added to Lists

### ISSUE THREAD

**Issue by inametaphor** [mastodon/mastodon#21335] opened 2022-11-21 18:38 UTC
### Pitch

Because users can now follow hashtags, allow those hashtags to be added to Lists in the same manner user accounts can be added

### Motivation

A user may want to see views of their Home feed with or without hashtags. While a solution exists to add all followed user accounts to a list (and thus have a view without the followed hashtags), there's no similar method to see ONLY posts that contain a followed hashtag.

**Comment by sparr** [comment] 2022-11-26 16:54
dupe #20715

**Comment by brendanjones** [comment] 2023-07-14 16:20
> dupe https://github.com/mastodon/mastodon/issues/20715

Which is itself a duplicate of https://github.com/mastodon/mastodon/issues/7692

**Closed** 2023-07-14 17:54 UTC
Labels: suggestion
