### ISSUE TITLE
notification-bar-message text on light theme is not visible

### ISSUE THREAD

**Issue by teeerevor** [mastodon/mastodon#25913] opened 2023-07-11 14:31 UTC
### Steps to reproduce the problem

1. Set theme to light
2. type message
3. press publish
4. notification bar shows but text is not visible.
...

### Expected behaviour

notification bar should be visible

### Actual behaviour

notification bar is hard to see

### Detailed description

<img width="219" alt="light-notification-bar" src="https://github.com/mastodon/mastodon/assets/17292/081f21c3-128c-4980-82e8-e875115fda1e">

### Specifications

Mastodon 4.1.4

**Comment by renchap** [comment] 2023-07-11 15:18
Duplicate of #25910

**Closed by renchap** 2023-07-11 15:18 UTC
Labels: bug
