### ISSUE TITLE
Show actual number of notifications 

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon#31255] opened 2024-08-01 20:40 UTC
### Pitch

You seem to have the notification bell to max out at 40+.
Why not just show the actual number?
If it's 50, show 50 on the bell

### Motivation

We should know the actual number of new notifications

**Comment by renchap** [comment] 2024-08-01 21:44
Duplicate of https://github.com/mastodon/mastodon/issues/27293

**Closed by renchap** 2024-08-01 21:44 UTC
Labels: suggestion
