### ISSUE TITLE
Profile url backlink verification is not case insensitive

### ISSUE THREAD

**Issue by BoD** [mastodon/mastodon#21112] opened 2022-11-19 17:33 UTC
### Steps to reproduce the problem

1. Have a website e.g. `example.com` containing a backlink (with rel="me") to your profile 
2. In your profile, add a metadata item pointing to `EXAMPLE.com` (in uppercase)

### Expected behaviour

The metadata item should be shown as verified

### Actual behaviour

The metadata item doesn't show as verified

### Detailed description

When adding the item as `example.com` (in lowercase), then it works as expected ✅.

You can see an example of this on my own profile https://mastodon.social/@BoD

It's not a big deal of course, but I usually write my domain name as JRAF.org, this wasn't working, and I had no idea why. After randomly trying things, I discovered this was the reason.

### Specifications

This is on v4.0.2.

**Comment by anisse** [comment] 2022-11-19 21:41
This specific issue seems to be a duplicate of https://github.com/mastodon/mastodon/issues/20944

**Comment by BoD** [comment] 2022-11-19 22:10
You are right @anisse. Closing this one then.

**Closed** 2022-11-19 22:10 UTC
Labels: bug
