### ISSUE TITLE
Mastodon blocklist

### ISSUE THREAD

**Issue by hansw-nlo** [mastodon/mastodon#22316] opened 2022-12-14 21:39 UTC
### Steps to reproduce the problem

nothing to reproduce. Just a notification since real complaints are not answered. 

I have generated a blocklist of mastodon servers (150 of them pounding my server while not even having AP enabled) and yes,I will publish it on Januari the 2nd 2023. I am sick of the advises but most of all about the lack of knowledge about the common way to deal with errors, the flood of attempts to reach my server, etc... 

Make mastodon http status aware and I might take the ban away. 

Have a happy life, thanks for killing the fediverse

### Expected behaviour

blabla

### Actual behaviour

blabla

### Specifications

blabla

**Comment by afontenot** [comment] 2022-12-15 00:49
Probably a dupe of https://github.com/mastodon/mastodon/issues/4486 and https://github.com/mastodon/mastodon/issues/21861

At any rate, if anyone would like a list of 10150 Mastodon servers rather than wait 19 days for a list of 150 of them, [here's one I made](https://0x0.st/on4t.txt).

I made this list with the following code:

```python
import requests
from bs4 import BeautifulSoup as Soup

req = requests.get("https://mastodon.fediverse.observer/app/views/tabledata.php?software=mastodon")
soup = Soup(req.text, "lxml")
instances = soup.find_all("a", class_="url")
print(len(instances))
with open("instances.txt", "w") as f:
    for instance in instances:
        f.write(instance.text + "\n")
```

Please don't run this code in an automated fashion to avoid overwhelming the Fediverse Observer site.

**Comment by ineffyble** [comment] 2022-12-15 05:46
`instances.social` has a nice API too, might have a larger number of servers.

**Comment by ineffyble** [comment] 2022-12-15 05:47
> Probably a dupe of #4486 and #21861

In terms of HTTP status handling, I'd say #22097 and #22070 are more relevant.

**Comment by afontenot** [comment] 2022-12-15 07:05
> instances.social

Ooh, cool. Assuming that [this](https://instances.social/list.json) is the full list, it's got 7321 instances - but 1832 are unique and not on the F.O. list!

**Comment by hansw-nlo** [comment] 2022-12-15 07:54
The fediverse.observer list is incomplete. Some do not want to get indexed. Also, it parsing content from the ip address where also one of the larger diaspora instances is running / hosted. .

**Closed** 2022-12-16 05:23 UTC
Labels: bug
