### ISSUE TITLE
Create Lists based on topic (hashtags) instead of people

### ISSUE THREAD

**Issue by marcususa** [mastodon/mastodon#22812] opened 2022-12-28 21:31 UTC
### Pitch

Right now, I can follow people, but they don't always post on things I want to read about. We all have different interests. Maybe one person likes politics, computers, science, and music. Well, I would like to read their posts on computers and music, but I am not really interested in politics or science. If we categorized our posts with hashtags, and if we could list posts based on hashtags, then we could get just the desired posts from a person. Right now, it's all or nothing. Either you have to read some of every post, or you have to unfollow. There is no in between, no happy medium.

### Motivation

It is needed because of the diversity in people.  We are not exactly the same all the way through. Even language filtering would be a good idea. You could select languages you want posts in, and then languages you can't read would not be presented in any timeline. This would deliver more posts to you that matter.

**Comment by ArthurJ** [comment] 2022-12-30 11:24
Adding to that pitch, it would be nice to add account that we don't follow to lists.
E.g. I follow some bots that posts useful content, but that pollute my timeline. Having them segregated on a list would make my timeline cleaner.

**Comment by ArthurJ** [comment] 2022-12-30 11:29
Related:
https://github.com/mastodon/mastodon/discussions/21772

**Comment by btaroli** [comment] 2023-01-10 22:05
> Adding to that pitch, it would be nice to be able to add accounts that we don't follow to lists. E.g. I follow some bots that posts useful content, but that pollute my timeline. Having them segregated on a list would make my timeline cleaner.

I have noticed, when listing users, that if you do it from the user profile, an option is shown to mute the user from home timeline as you add them to a list. Sadly this doesn't appear when adding them to a list directly. That may be a different issue... BUT I would, by extensions, say it would be useful to add a hashtag to a list without having to follow it *or* similarly allow muting it from other views when it's put into a list. And that doing this from the list directly should still allow this choice.

**Comment by trwnh** [comment] 2023-01-26 18:06
Related #1208

**Comment by JesseWeinstein** [comment] 2023-02-11 16:56
More related (the first from 2018): 
https://github.com/mastodon/mastodon/issues/7692: "Ability to add hashtags to lists".
https://github.com/mastodon/mastodon/issues/20715 "Add hashtag to list"

**Comment by brendanjones** [comment] 2023-07-14 16:42
Completely a duplicate of https://github.com/mastodon/mastodon/issues/7692

**Comment by renchap** [comment] 2024-04-17 07:17
Duplicate of https://github.com/mastodon/mastodon/issues/7692

**Closed by renchap** 2024-04-17 07:17 UTC
Labels: suggestion
