### ISSUE TITLE
Clicking on a thread post leads to the top of the thread

### ISSUE THREAD

**Issue by renchap** [mastodon/mastodon#27313] opened 2023-10-06 20:42 UTC
### Steps to reproduce the problem

1. On your timeline, click on a post deep in a thread (or a reply deep enough)
2. See that it loads the thread, scrolled to the reply
3. Press "back"
4. Click again on the same post

### Expected behaviour

I see the post I clicked in the thread

### Actual behaviour

The thread load, but scrolled to top

### Mastodon instance

oisaur.com

### Mastodon version

v4.2.0

### Browser name and version

Safari

### Operating system

macOS

### Technical details

This probably happens when the thread is already loaded in Redux, and `scrollIntoView` is not called somehow.

**Comment by ClearlyClaire** [comment] 2023-10-09 09:22
I'm actually unable to reproduce the issue in single-column mode, but can reproduce something similar in advanced mode: when first opening the post, it correctly scrolls to it, but when clicking the same post again, it scrolls to the top.

This occurs because the logic responsible for scrolling in `app/javascript/mastodon/features/status/index.jsx`, in `componentDidUpdate` isn't triggered.

I don't know how to fix that, as this actually hasn't to do with the component's props but with navigation.

**Comment by ClearlyClaire** [comment] 2023-10-09 09:37
It probably has to do with `react-router` and scroll restoration. In this specific case, we don't want `react-router` to scroll to top when a history state is pushed but instead let us scroll to the selected post ourselves. I'm not sure whether we should try to address that now (so that it can be addressed in the 4.2.x branch) or take care of that after #25047 is merged.

**Closed** 2023-10-09 10:21 UTC
Labels: bug, status/confirmed, area/web interface
