### ISSUE TITLE
Many posts missing in a conversation

### ISSUE THREAD

**Issue by TimothyRichardGreen** [mastodon/mastodon#21497] opened 2022-11-23 19:25 UTC
### Steps to reproduce the problem

1. View on my own instance (in my case, mastodon.ie) a post which was written on another instance (in this case, social.coop).
2. Observe that there are five replies to that post.
3. Open the post on its own instance (social.coop).
4. Observe that there are at least six other replies which are visible there, but were not visible to me on my own instance.
...

### Expected behaviour

When viewing a conversation, I want to see the whole conversation

### Actual behaviour

I see about two half of a conversation, with half the posts missing with no warning

### Detailed description

This can lead to some very confusing conversations, with people talking at cross-purposes, or butting in to answer questions which were already answered hours previously.

I'm not sure whether this is just a delay in sync, or an actual intended feature of federation. (Those posts were made by other users on other instances, so perhaps it's intentional that they're not visible on mastodon.ie if no one here was following them?) Either way, it's confusing and annoying.

### Specifications

Mastodon.ie is and Social.coop are both on v4.0.2. I haven't checked every server of people involved in the conversation.

**Comment by trwnh** [comment] 2022-11-23 19:44
likely no one follows those 6 other replies' authors, yes. federation works like email, and you send posts to your followers. replies are constructed from what you receive.

there have been proposals at various times to rework this so that replies are delivered only to the author, who is responsible for redistributing them somehow (by updating the `replies` collection with a link to that object, it has been suggested). if authors maintained their `replies` collections it would then be possible to fetch recursively downwards (assuming you wanted to load more replies that way).

in any case, this is likely a duplicate of #9409

**Comment by TimothyRichardGreen** [comment] 2022-11-24 14:58
I still maintain that this is a bug, because as a design decision it's just ridiculous. But I don't know to what extent pushback is actually useful. Is this a decision that has been made, and that's it, and if I don't like it I can lump it? Or are people open to changing their mind? As it is, it makes Mastodon unusable for me. I cannot participate in a conversation with bits silently missing.

It means that if someone asks a question about how to use the platform, I'm reluctant to chip in with a helpful answer, for fear that they may have already received one I can't see, and they'll think I'm being annoying, talking over the original.

It means that any long conversation will be confusing and have people talking at cross-purposes, because they're missing context.

Or, just now, someone posted an interesting post in three parts, to get around the character limit. I saw part one, because it contained a hashtag I'm following, but I had no way to see parts two and three until I opened the thread on the original server.

As far as I'm concerned, Mastodon is fundamentally broken.

**Comment by trwnh** [comment] 2022-11-24 15:03
It's not a "design decision" as much as it is a "technical limitation". It's solvable in theory, but in practice it just hasn't been done yet. Perhaps there is a consideration that fetching the *entire* conversation may be too much, though -- not all of which may be relevant. But nothing really "fundamental" about it not being implemented yet.

**Comment by pullopen** [comment] 2022-11-26 06:48
See #17808 , many replies are missing even when you open it in the original server.

**Comment by nanos** [comment] 2023-04-02 15:15
Just thought I’d highlight here, that there are now two tools to deal with this issue:

[FediFetcher](https://blog.thms.uk/fedifetcher) is a python script you can either run as a cron job, or a GitHub action (full disclosure: I’m the author)

Alternatively, there is [combine.social](https://combine.social/) which does essentially the same, but as a service.

**Closed** 2023-05-19 06:36 UTC
Labels: bug
