### ISSUE TITLE
Public & Private Avatar

### ISSUE THREAD

**Issue by trymeouteh** [mastodon/mastodon#15550] opened 2021-01-12 17:04 UTC
Please allow for the option to have two avatars on your profile. One would be your public avatar which all can see and the other one will be your private avatar which only followers can see. This way you could have your real face as your private avatar and have a logo or something as your public avatar for privacy.

**Comment by trwnh** [comment] 2021-01-12 20:46
tangentially related: https://github.com/tootsuite/mastodon/issues/9468#issuecomment-465398240

**Comment by vmstan** [comment] 2023-11-17 16:05
Duplicate of https://github.com/mastodon/mastodon/issues/15548, https://github.com/mastodon/mastodon/issues/15549, https://github.com/mastodon/mastodon/issues/15550, https://github.com/mastodon/mastodon/issues/15551 and https://github.com/mastodon/mastodon/issues/15552

**Closed** 2023-11-17 16:05 UTC
