### ISSUE TITLE
[Feature request] Polls with media

### ISSUE THREAD

**Issue by ThatOneCalculator** [mastodon/mastodon#17363] opened 2022-01-24 21:16 UTC
### Pitch

Allow toots with both polls and media attachments. 

### Motivation

Most of the polls I (and others) make are about asking for an opinion on something that usually involves and image or two, and instead of asking people to look at the comments, having the media right there in the status would be nice.

**Comment by JorgeStolfi** [comment] 2023-01-29 14:24
See suggestion #22840 "Media and link previews should be displayed inside the toot rather than at the end of it".   If that change was implemented, this one would automatically follow.

**Comment by vmstan** [comment] 2023-10-14 13:09
Duplicate of #10707

**Closed** 2023-10-14 13:09 UTC
