### ISSUE TITLE
Status card link stripping in-page named anchor

### ISSUE THREAD

**Issue by mattedgar** [mastodon/mastodon#20367] opened 2022-11-10 22:46 UTC
### Steps to reproduce the problem

1. Publish a post with a URL that has an in-page named anchor, e.g. https://docs.joinmastodon.org/user/profile/#verification
2. View the post in Mastodon web

### Expected behaviour

Both the status link and status card should link to the named anchor

### Actual behaviour

The status link links to the in-page named anchor, but the status card links to the top of the page

### Detailed description

First observed when posting this status:

Hovering over the status link...
<img width="384" alt="Screenshot 2022-11-10 at 22 42 30" src="https://user-images.githubusercontent.com/1483266/201221568-77b555df-7ade-4b1a-97cc-171dd3eae8af.png">

Hovering over the status card...
<img width="383" alt="Screenshot 2022-11-10 at 22 42 42" src="https://user-images.githubusercontent.com/1483266/201221606-92e48276-b922-4d76-9736-151ad1046cce.png">

### Specifications

Mastodon 3.5.3 and Mastodon 4.0.0rc1
Firefox 106.0.5 (64-bit)

**Comment by ineffyble** [comment] 2022-11-11 03:04
This is likely because the status card is using the canonical URL as declared by the website, which won't include anchors. Unless it's changed, this is the same behaviour on most social networks such as Twitter and Facebook.

**Comment by mattedgar** [comment] 2022-11-11 08:18
Thanks, that explanation makes sense. I'm not sure that other social networks all link to the cononical URL without named anchor. Birdsite and LinkedIn both link their cards to the URL including anchor

**Comment by ClearlyClaire** [comment] 2022-11-11 09:24
This is a duplicate of #19573

**Comment by ineffyble** [comment] 2022-11-11 09:25
Shouldn't be the hardest thing to include anchor, will just require some
custom logic.

**Closed by ClearlyClaire** 2022-11-11 09:24 UTC
Labels: bug
