### ISSUE TITLE
Separate private replies from direct messages

### ISSUE THREAD

**Issue by SoniEx2** [mastodon/mastodon#17445] opened 2022-02-05 00:57 UTC
### Pitch

If an user replies to a public post with direct visibility, the reply should be shown as a private reply notification but not as a DM.

### Motivation

Private replies aren't DMs. Distinguishing the two would benefit old and new users alike. The current UX/UI is confusing and creates social issues.

**Comment by shleeable** [comment] 2022-02-09 09:56
I believe Big G has an long term thing to make "Real DMs" part of the ecosystem.. but he'll need to speak to it.

**Comment by SoniEx2** [comment] 2022-02-09 13:11
We believe so too, altho we don't see why we need to wait for the backend changes before (some of) the frontend changes...

**Comment by trwnh** [comment] 2022-11-21 09:18
Duplicate of #3819

**Comment by SoniEx2** [comment] 2022-11-21 09:42
not quite - this is about some UI changes. but it is related, yes.

**Closed** 2023-05-16 04:44 UTC
