### ISSUE TITLE
Disable invites that never expire for users

### ISSUE THREAD

**Issue by joenepraat** [mastodon/mastodon#8638] opened 2018-09-06 20:47 UTC
Normal users are able to create invites that never expire. As an instance admin I like to retain a bit of control, so a max. of 1 week is enough IMO for regular users. To make this configurable for admins is also a good idea.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by egypturnash** [comment] 2018-10-09 05:14
Today I was thinking about allowing my users to generate invites for a while, but I really don't want to let them invite infinity people. All it takes is one user generating and spreading an unlimited invite - *which is the default* - for me to suddenly have to contend with a *lot* more new users than I'm prepared to deal with.

Ideally I feel like I'd like to be able to set a limit on how many invitations a user can generate over a month, and limit how many people they can invite. Both by setting limits on what options they have in the invitation generation form, and maybe also by saying things like "users can only generate invitations good for up to MAX_ALLOWED_INVITES new accounts in a month/year/their entire existence".

**Comment by keithjgrant** [comment] 2022-11-11 18:43
I strongly second this. It seems especially pertinent with the explosion of growth we have now 😕

I want to trust my users with invites, but... I want a limit on how much rope I'm giving them (and the people that they invite, afterwards!)

**Comment by egypturnash** [comment] 2022-11-11 18:58
yeah, as presently implemented invites are really not something I want to trust anyone to generate besides me and my (nonexistent) mods, and I constantly have to watch myself to make sure I don't accidentally hand out an infinite invitation by accident.

**Comment by trwnh** [comment] 2023-05-20 19:59
Duplicate of #6353

**Closed by trwnh** 2023-05-20 19:59 UTC
Labels: suggestion
