### ISSUE TITLE
PgHero reports duplicate indexes

### ISSUE THREAD

**Issue by eitch** [mastodon/mastodon#32556] opened 2024-10-17 07:31 UTC
### Steps to reproduce the problem

After upgrading to 4.3.0 i checked PgHero and i get the following warnings:

Duplicate Indexes
These indexes exist, but aren’t needed. Remove them for faster writes.

Details
On account_aliases
    index_account_aliases_on_account_id (account_id)
is covered by
    index_account_aliases_on_account_id_and_uri (account_id, uri)

On account_relationship_severance_events
    index_account_relationship_severance_events_on_account_id (account_id)
is covered by
    idx_on_account_id_relationship_severance_event_id_7bd82bf20e (account_id, relationship_severance_event_id)

On custom_filter_statuses
    index_custom_filter_statuses_on_status_id (status_id)
is covered by
    index_custom_filter_statuses_on_status_id_and_custom_filter_id (status_id, custom_filter_id)

On webauthn_credentials
    index_webauthn_credentials_on_user_id (user_id)
is covered by
    index_webauthn_credentials_on_user_id_and_nickname (user_id, nickname)

Can i simply remove the first index, and how would i do this on a docker compose environment?

### Expected behaviour

No duplicate indexes

### Actual behaviour

4 duplicate indexes in PgHero

### Technical details

Mastodon docker environment:

Software
Mastodon	4.3.0
Ruby	3.3.5p100
PostgreSQL	14.13
Redis	7.4.1
Elasticsearch	7.17.4
libvips	8.15.3
FFmpeg	7.0.2

**Comment by renchap** [comment] 2024-10-17 08:49
Duplicate of https://github.com/mastodon/mastodon/issues/32061

**Closed by renchap** 2024-10-17 08:49 UTC
Labels: status/to triage
