### ISSUE TITLE
CPU and RAM hogging when in the middle of a timeline

### ISSUE THREAD

**Issue by Macellatore** [mastodon/mastodon#22508] opened 2022-12-19 17:45 UTC
### Steps to reproduce the problem

1. Open the web interface of a fairly active instance
2. Take a "fast" timeline, such as the federated one, scroll down for a while and leave it as is
3. wait for hours/days

### Expected behaviour

The page should be usable even after days, maybe without loading all the toots but showing one of those "[...]" placeholders that is often shown in other cases

### Actual behaviour

The page keeps loading the new toots requiring more and more system resources until it becomes unusable

### Detailed description

As written above, i usually keep a tab of my browser open on a mastodon instance.
If i forget to scroll back up to the lastest toot of every timeline that is showing and leave the page as is, the page starts to eat more and more ram and cpu until it becomes unusable.
When the scrollbars of the timelines are left at the top, the page seems to load 20 toots at most, and loads the older ones only when the user scrolls down. If the scrollbar is left middle-timeline, the newer toot keep getting loaded but they never unload.

### Specifications

Linux user 6.0.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 02 Dec 2022 17:25:31 +0000 x86_64 GNU/Linux
Mozilla Firefox 107.0.1 (64-bit)
Judging from the footer, Mastodon instance should be at v3.4.7

**Comment by vmstan** [comment] 2023-11-02 21:05
Closed as duplicate of #787

**Closed by vmstan** 2023-11-02 21:05 UTC
Labels: bug
