### ISSUE TITLE
DMs should be encrypted

### ISSUE THREAD

**Issue by jamieschuts** [mastodon/mastodon#22054] opened 2022-12-05 00:04 UTC
### Pitch

As we know, DMs can be viewed by server admins. End users are not made aware of this, especially new users. While we'd like to think server admins will never do this, unfortunately it will happen in isolated cases. There is also no mecahnism to alert users that someone has viewed or accessed their direct messages.
Propose that DMs be envelope encryption with a combination of Server key + user key. Where users generate their own key as they join the server. This key is only known to the user.
DMs should have a message / icon to make the user aware that it is encrypted

### Motivation

Increase trust in the platform
Better user security and privacy
Users and community to benefit

**Comment by hlangeveld** [comment] 2022-12-05 00:22
See also #19565

**Comment by expertmanofficial** [comment] 2022-12-05 00:38
Saw your toot (https://retrochat.online/@narf/109458161674743237)[on Mastodon] and decided to subscribe.

I do support this request!!!!!

**Comment by shleeable** [comment] 2022-12-05 01:29
Dupe of a dupe of a dupe. We get it.

**Comment by rbairwell** [comment] 2022-12-05 02:26
See also https://github.com/mastodon/mastodon/issues/18079 amongst others.

When I select "Mentioned people only" (aka a DM), I do get the message "Posts on Mastodon are not end-to-end encrypted. Do not share any sensitive information over Mastodon. Learn more" appear in the webapp.

Doing e2e encryption is difficult: especially in a web app (it is a bit easier on downloaded apps as you can then store the private keys locally): there's a reason why the other social networks (Twitter, LinkedIn even Facebook) as part of their core web based product (Messenger, WhatsApp etc are all downloadable). 

Some services - such s Proton Mail (which specialises in encryption) - do do a web based solution, but if you lose your recovery details then every message is lost https://proton.me/support/set-account-recovery-methods .Not too nice for forgetful users who have already lost their password. 

Oh - and yes, that does mean - at least in theory - Musk, Zuckerberg, Microsoft can all read your DMs on those systems: along with your email provider being able to read all of your emails if they wanted to(!).

 Mastodon is just a bit more open about the fact that server administrators have full access to the system and hence could read anything they wanted (but, as a sysadmin myself, we don't due to computer misuse laws, data protection and laziness: only time I've done something like that is when I was confirming an abuse report).

**Comment by koteisaev** [comment] 2022-12-05 13:43
Real end-to-end encryption mean for me something that encrypted in a way, when only you and recipient can read these messages. It really can be implemented only for 1x1 communication, when keys stored locally on machines used by users.
Mastodon is not designed for this use-cases, as the underlying protocol, ActivityPub, which seems to be designed for opposite user case, for messages (updates about something) to be publicly broadcasted.
May be "Direct Messages" must be renamed to something like "Mention someone" with users search popup mentioning you will not write a PRIVATE message, but more like "write on user wall/feed" or such?

**Comment by person1234-ux** [comment] 2022-12-06 05:03
I agree end to end should be implemented but only if it can be implemented in a way that we can verify that end to end encryption hasn't been tampered with. The end to end encyption must be implmented by an expert in chryptography so that it meets all the standed and is verifyable secure. It would be better to have no end to end encrypition at all then to have end to end encryption implement in such a way that it can be easily worked around. Haveing end to end encyption that doesn't do what it supposed to do is very dangerous because it makes people beleive that their messages are secure when they are in fact not secure at all. This can and unforetnly will lead to more harm then good.

**Comment by jamieschuts** [comment] 2022-12-06 05:30
I guess the real reason for this Feature request is to get developer attention & get it in the backlog. This is something previous attempts (you might call them dupes) have failed to do. If it gets enough attention then funds / effort can be diverted to implementing from the core team. If that means getting an outsider to look at encryption then great. I feel the platform should be built on a secure foundation by default with privacy & security as core features.
for certain users this could matter a LOT. Imagine a nation state spying on anonymous bloggers, a malicious admin using a DM for extortion e.t.c. Remember anyone can host a server. that is both awesome and scary.

**Comment by ClearlyClaire** [comment] 2022-12-07 10:31
Closed as a duplicate of #19565

Again, this is something we are interested in, and we have some backend code to route one-to-one end-to-end encrypted messages, upload and fetch keys and pre-keys following what is basically Matrix's one-to-one E2EE protocol, and issue message franking values (allowing end users to report DMs to their admin), but the client-side part is currently not implemented anywhere, and we're lacking a format description for the cleartext itself. There is someone effort to bring this feature in the official mobile apps, but it's not a priority, and it requires careful consideration of UX and security aspects.

**Closed by ClearlyClaire** 2022-12-07 10:32 UTC
Labels: suggestion
