### ISSUE TITLE
First @ post to a user should only broadcast to that user and mutuals

### ISSUE THREAD

**Issue by kevbob** [mastodon/mastodon#29086] opened 2024-02-04 20:03 UTC
### Pitch

So, this is a behavior twitter got right that I think should be carried over. 

If you start a post with a handle to be specific to a particular user, the behavior we got used to with a tweet started that way was it was only broadcast to that user and any mutuals. On Mastodon it’s broadcast to all of your follows. You can’t do a smaller convo with just that person without turning it into a DM. 

Replies work as expected though: just to that user and your mutuals.

**So I propose that Mastodon use the same behavior: Start an @ post to someone, it only shows in their timeline and anyone who follows you and also follows that user.**

### Motivation

The feature would be beneficial to new users on the platform* who expect that behavior and those who want to keep a conversation limited to the user you are reaching out to. Mutuals is fine, but not to everyone who follows you. This is bad design. First time someone who was not a mutual reacted to my post, I thought I did something wrong and deleted it. As a consequence, I limit my posting to someone directly; and occasionally make use of an existing post thread and change the subject. That's a dumb solution, but it's my workaround without resorting to a DM.  

*I'm not a new user, just someone who has gotten used to it but continues to think Mastodon does this wrong. 

(I did search for a topic that might address this, I am sure someone will link to one, but you know how GitHub searching is on a popular project.)

**Comment by trwnh** [comment] 2024-02-04 22:26
Twitter actually changed this behavior due to people using `.@` to get around it (and not everyone knowing that this was needed).

Duplicate of #8311 btw

**Closed by trwnh** 2024-02-04 22:26 UTC
Labels: suggestion
