### ISSUE TITLE
Ability to change PWA icon and favicon

### ISSUE THREAD

**Issue by SJang1** [mastodon/mastodon#20726] opened 2022-11-15 02:05 UTC
### Pitch

It would be nice to have a setting that does the ability to
- Change the PWA icon
- change favicon
of the server.

### Motivation

Servers can make their images by changing the server icon easily.

**Comment by lgE-1** [comment] 2022-11-16 17:43
I also need this ability. The uniform icons make the instances too similar to each other, and such a lack of personalization would reduce the motivation of admin to run their own instances. At present, the technical threshold for modifying icons is relatively high, I hope it can be more convenient, or provide notes for modification.

**Comment by ThatOneCalculator** [comment] 2022-12-12 22:58
It's a shame masto is lacking in this department compared to Calckey/Misskey...

![image](https://user-images.githubusercontent.com/44733677/207173578-b24a0e4f-9818-44d5-b61c-7922c55f39b8.png)

**Comment by LovesTha** [comment] 2022-12-12 23:19
Server setting of icon is a minimum. Per user could be nice, but would be additional server load so probably not worth it.

**Comment by almereyda** [comment] 2023-08-31 18:52
Is this possibly a duplicate of #7396?

**Comment by renchap** [comment] 2024-04-13 17:18
Duplicate of #7396

**Closed by renchap** 2024-04-13 17:18 UTC
Labels: deployment, suggestion
