### ISSUE TITLE
Feature request: Allow to change the background for the web UI

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#7450] opened 2018-05-11 16:01 UTC
Would be easy to implement since just an upload form and some css rules are needed, which will be applied when the background is set. Also allow to reset the background to default. The background will be applied somewhat like this: https://css-tricks.com/perfect-full-page-background-image/. That would give the user alot of customizability and they can make it "their own".

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mal0ki** [comment] 2018-05-15 11:32
So you are requesting this for users, not for admins to customize their instance?

**Comment by koyuawsmbrtn** [comment] 2018-05-15 12:17
Yep. Admins are already able to change the wallpaper for the main page anyway (inline style-attributes on the front-page description).

**Comment by mjankowski** [comment] 2024-11-27 19:57
Doing issue triage - going to close this as not planned on the assumption that zero core team response in six years makes this unlikely, and the [general policy to not accept outside design ideas](https://github.com/mastodon/.github/blob/main/CONTRIBUTING.md#project-specific-considerations)

**Closed by mjankowski** 2024-11-27 19:57 UTC

**Comment by trwnh** [comment] 2024-11-27 21:28
I think that policy only applies to PRs, not feature requests?

However, the issue is stale because static profile pages were removed in Mastodon v4.0
