### ISSUE TITLE
Inputting improper username syntax breaks /settings/aliases

### ISSUE THREAD

**Issue by durablenapkin** [mastodon/mastodon#18049] opened 2022-04-17 21:17 UTC
### Steps to reproduce the problem

1. Go to https://instancename.tld/settings/aliases
2. Enter `@username@instancename2.tld` (instead of username@instancename2.tld)
3. Save
4. Page breaks and all subsequent visits to https://instancename.tld/settings/aliases results in `We're sorry, but something went wrong on our end.` page
...

### Expected behaviour

Either user input is checked for proper formatting or an error message is shown

### Actual behaviour

Any attempt to access /settings/aliases results in a "We're sorry, but something went wrong on our end." page

### Specifications

v3.5.1 (on https://mastodon.social/ instance)

**Comment by ClearlyClaire** [comment] 2022-04-20 12:14
This is actually not caused by using an initial `@` (which is properly stripped), but by an issue displaying *any* alias. It's been fixed in #18004

**Closed by ClearlyClaire** 2022-04-20 12:14 UTC
Labels: bug
