### ISSUE TITLE
Hashtags in Profiles are URLs pointing at original instance, not mapped to local instance

### ISSUE THREAD

**Issue by nmstoker** [mastodon/mastodon#22414] opened 2022-12-17 21:09 UTC
### Steps to reproduce the problem

1.  Find a profile for someone on another Mastodon instance where the profile lists hashtags
2. Click one of the profile hashtags
3. Observe how this opens a new page with the URL of the original instance and not your local instance
...

### Expected behaviour

Hashtag link would open for the tag on your instance

### Actual behaviour

Hashtag link opens for the tag on the original instance (less useful)

### Detailed description

It's conceivable some may argue this is the intended behaviour, but having the URL of the hashtag use the original Mastodon instance URL (ie where the person whose profile it is comes from) is much less useful and it's unexpected as it differs from how hashtag handling occurs in regular posts (where they are correctly mapped to the local instance).

The mapping to the local instance means that post hashtags appear in the correct panel in the Advanced UI, whereas this scenario may be related to bugs already raised relating to profile hashtags opening in new windows, here:
#21016
#3982
#3185

As a user, I would find it more useful if the hashtags were mapped locally, because then any action I wish to complete with the hashtag can be easily achieved.  With the current functionality, you're now on another instance so none of the usual functionality works (ie you are not signed in, so you cannot like posts for that hashtag on the original instance, cannot directly follow people etc etc)

### Specifications

Mastodon v4.0.2
Firefox 108.0.1 (64-bit)  - Firefox for ArchLinux
Arch (x86_64)

**Comment by ineffyble** [comment] 2022-12-18 07:57
Ooh, interesting. This is because hashtags are treated the same way as users (a "mention").

**Comment by nemobis** [comment] 2022-12-23 07:31
If hashtag clicks are captured to link the local version of the hashtag, *please* make it so it's still possible to go the original URL in one click (e.g. by opening in new tab). Cf. https://github.com/mastodon/mastodon/issues/20827.

**Comment by nmstoker** [comment] 2022-12-23 16:55
@nemobis Would two clicks be acceptable or is there a particular urgency/advantage that it be one?

Presumably if they did fix this to be local for the profile hashtag links, people could still click through to the original profile and then access the original hashtag link there if they needed to.

**Comment by nemobis** [comment] 2022-12-23 17:09
Il 23/12/22 18:55, Neil Stoker ha scritto:
> @nemobis Would two clicks be acceptable or is there a particular urgency/advantage that it be one?

The advantage is accessibility. For example I can use the keyboard to 
open the link as I wish.

**Comment by nmstoker** [comment] 2022-12-23 17:30
Okay. I'm probably missing something, but what's the big advantage of viewing the hashtag link on the original instance?

**Comment by nemobis** [comment] 2022-12-23 18:00
And what's the advantage of not seeing them on the original instance? I simply think the user should be allowed to make the choice. Currently it's easy enough, on the web interface: I left-click to see the local version of the hashtag, I ctrl-click to open in new tab and see the hashtag on the remote instance.

**Comment by nmstoker** [comment] 2022-12-23 18:18
You haven't really made the case, you're just bouncing it back to me. I get that you want to click the link form you want, but you haven't really explained why this is valuable vs clicking the local form of the hashtag link.

I already explained the advantage of switching it (the interaction with posts found from the hashtag would generally be more convenient because you'll remain on your own instance where you are logged in). 

I realise we have opposing preferences, I'm simply trying to do the right thing and encourage you to clarify why your way is useful, beyond a marginal convenience, so that people can weigh up whether both options need "one click" (which will likely bloat the UI) vs prioritising one link form and the other being treated as an edge case, that might be less convenient (eg two clicks, which frankly isn't that big a deal from what i can see, even with a keyboard)

**Comment by trwnh** [comment] 2023-05-16 03:25
Duplicate of #1399

**Closed by trwnh** 2023-05-16 03:25 UTC
Labels: bug
