### ISSUE TITLE
Audit logs cannot be accessed after upgrade to v4.0.0rc1

### ISSUE THREAD

**Issue by rodti** [mastodon/mastodon#19609] opened 2022-10-31 20:40 UTC
### Steps to reproduce the problem

1. Upgrade from v3.5.3 to v4.0.0rc1 (commit https://github.com/mastodon/mastodon/commit/2d9a85db6efe0c9ccfda1420551ce3d6025bc27e)
2. Logged in as admin, go to Preferences > Moderation > Audit Logs
3. Browser loads https://mastodon.scot/admin/action_logs
4. Error shown 'We're sorry, but something went wrong on our end.', audit logs are not accessible

### Expected behaviour

List of audit log information shown

### Actual behaviour

Error page

### Specifications

Mastodon v4.0.0rc1
Node 3.0.4

**Comment by Gargron** [comment] 2022-10-31 20:52
`rails db:migrate` probably

**Comment by rodti** [comment] 2022-10-31 20:59
> `rails db:migrate` probably

I did run db:migrate as part of the upgrade which didn't give any errors. This happens on two separate instances.

**Comment by Gargron** [comment] 2022-10-31 21:15
What's the error log say?

**Comment by rodti** [comment] 2022-10-31 21:23
> What's the error log say?

`Oct 31 21:21:58 mas bundle[237216]: [2c0663d2-c94a-4eb6-abe1-429fb1bf8931] ActionView::Template::Error (No route matches {:action=>"show", :controller=>"admin/accounts", :id=>nil}, missing required keys: [:id]):
Oct 31 21:21:58 mas bundle[237216]: [2c0663d2-c94a-4eb6-abe1-429fb1bf8931]     4:       = image_tag action_log.account.avatar.url(:original), alt: '', width: 40, height: 40, class: 'avatar'
Oct 31 21:21:58 mas bundle[237216]: [2c0663d2-c94a-4eb6-abe1-429fb1bf8931]     5:     .log-entry__content
Oct 31 21:21:58 mas bundle[237216]: [2c0663d2-c94a-4eb6-abe1-429fb1bf8931]     6:       .log-entry__title
Oct 31 21:21:58 mas bundle[237216]: [2c0663d2-c94a-4eb6-abe1-429fb1bf8931]     7:         = t("admin.action_logs.actions.#{action_log.action}_#{action_log.target_type.underscore}_html", name: content_tag(:span, action_log.account.username, class: 'username'), target: content_tag>
Oct 31 21:21:58 mas bundle[237216]: [2c0663d2-c94a-4eb6-abe1-429fb1bf8931]     8:       .log-entry__timestamp
Oct 31 21:21:58 mas bundle[237216]: [2c0663d2-c94a-4eb6-abe1-429fb1bf8931]     9:         %time.formatted{ datetime: action_log.created_at.iso8601 }
Oct 31 21:21:58 mas bundle[237216]: [2c0663d2-c94a-4eb6-abe1-429fb1bf8931]
Oct 31 21:21:58 mas bundle[237216]: [2c0663d2-c94a-4eb6-abe1-429fb1bf8931] app/helpers/admin/action_logs_helper.rb:9:in `log_target'
Oct 31 21:21:58 mas bundle[237216]: [2c0663d2-c94a-4eb6-abe1-429fb1bf8931] app/views/admin/action_logs/_action_log.html.haml:7
Oct 31 21:21:58 mas bundle[237216]: [2c0663d2-c94a-4eb6-abe1-429fb1bf8931] app/views/admin/action_logs/index.html.haml:26
Oct 31 21:21:58 mas bundle[237216]: [2c0663d2-c94a-4eb6-abe1-429fb1bf8931] app/controllers/concerns/localized.rb:11:in `set_locale'
Oct 31 21:21:58 mas bundle[237216]: [2c0663d2-c94a-4eb6-abe1-429fb1bf8931] lib/mastodon/rack_middleware.rb:9:in `call'`

**Comment by GuidoDr** [comment] 2022-11-01 14:50
I do have the same error message in our 4.0.0rc1 instance too. (latest docker version, just a couple of minutes old)

mastodon-web_mastodon-1  | [56b4fb77-64e6-466f-8293-6545caccf34b] method=GET path=/admin/action_logs format=html controller=Admin::ActionLogsController action=index status=500 error='ActionView::Template::Error: No route matches {:action=>"show", :controller=>"admin/accounts", :id=>nil}, missing required keys: [:id]' duration=65.90 view=0.00 db=13.02
mastodon-web_mastodon-1  | [56b4fb77-64e6-466f-8293-6545caccf34b]
mastodon-web_mastodon-1  | [56b4fb77-64e6-466f-8293-6545caccf34b] ActionView::Template::Error (No route matches {:action=>"show", :controller=>"admin/accounts", :id=>nil}, missing required keys: [:id]):
mastodon-web_mastodon-1  | [56b4fb77-64e6-466f-8293-6545caccf34b]     4:       = image_tag action_log.account.avatar.url(:original), alt: '', width: 40, height: 40, class: 'avatar'
mastodon-web_mastodon-1  | [56b4fb77-64e6-466f-8293-6545caccf34b]     5:     .log-entry__content
mastodon-web_mastodon-1  | [56b4fb77-64e6-466f-8293-6545caccf34b]     6:       .log-entry__title
mastodon-web_mastodon-1  | [56b4fb77-64e6-466f-8293-6545caccf34b]     7:         = t("admin.action_logs.actions.#{action_log.action}_#{action_log.target_type.underscore}_html", name: content_tag(:span, action_log.account.username, class: 'username'), target: content_tag(:span, log_target(action_log), class: 'target'))
mastodon-web_mastodon-1  | [56b4fb77-64e6-466f-8293-6545caccf34b]     8:       .log-entry__timestamp
mastodon-web_mastodon-1  | [56b4fb77-64e6-466f-8293-6545caccf34b]     9:         %time.formatted{ datetime: action_log.created_at.iso8601 }
mastodon-web_mastodon-1  | [56b4fb77-64e6-466f-8293-6545caccf34b]
mastodon-web_mastodon-1  | [56b4fb77-64e6-466f-8293-6545caccf34b] app/helpers/admin/action_logs_helper.rb:9:in `log_target'
mastodon-web_mastodon-1  | [56b4fb77-64e6-466f-8293-6545caccf34b] app/views/admin/action_logs/_action_log.html.haml:7
mastodon-web_mastodon-1  | [56b4fb77-64e6-466f-8293-6545caccf34b] app/views/admin/action_logs/index.html.haml:26
mastodon-web_mastodon-1  | [56b4fb77-64e6-466f-8293-6545caccf34b] app/controllers/concerns/localized.rb:11:in `set_locale'
mastodon-web_mastodon-1  | [56b4fb77-64e6-466f-8293-6545caccf34b] lib/mastodon/rack_middleware.rb:9:in `call'

**Comment by rodti** [comment] 2022-11-01 16:12
Well this is strange. 24 hours later I can now click on the Audit Logs page and it works as expected. Is there some job that runs in the background that could have caused this change? Fixed on both servers!

@GuidoDr maybe worth trying on your server tomorrow?

**Comment by ClearlyClaire** [comment] 2022-11-01 17:25
This is most probably caused by the refactoring in #19040 not providing a migration path for existing log actions.

**Comment by ClearlyClaire** [comment] 2022-11-01 17:26
> Well this is strange. 24 hours later I can now click on the Audit Logs page and it works as expected. Is there some job that runs in the background that could have caused this change? Fixed on both servers!
> 
> @GuidoDr maybe worth trying on your server tomorrow?

You likely have new admin logs that display fine, while older entries will still break.

**Comment by rodti** [comment] 2022-11-01 17:29
> > Well this is strange. 24 hours later I can now click on the Audit Logs page and it works as expected. Is there some job that runs in the background that could have caused this change? Fixed on both servers!
> > @GuidoDr maybe worth trying on your server tomorrow?
> 
> You likely have new admin logs that display fine, while older entries will still break.

It shows 433 pages of audit logs, the first (from broadly the time of the upgrade) works fine, any page from the 2nd onwards have the same error as before.

Crucially it's working going forward.

**Comment by SJang1** [comment] 2022-11-01 18:11
As here from 3.5.3 upgraded to MAIN, having the same issue. the strange thing is only on https://[domain]/admin/action_logs the old mastodon logo from 3.5.3 on the favicon pops out. (blue favicon, not purple)

**Comment by GuidoDr** [comment] 2022-11-03 12:50
> 



> @GuidoDr maybe worth trying on your server tomorrow?

at least until now I do still see this error on my instance (which is a rather small instance)
But I do see that @ClearlyClaire did already some fixes that do now wait for review.
So I assume that it will be fixed when these are moved to main. 😃

**Closed** 2022-11-03 15:06 UTC
Labels: bug
