### ISSUE TITLE
Toots not showing when following users from other instances

### ISSUE THREAD

**Issue by rtnF14** [mastodon/mastodon#14058] opened 2020-06-16 01:44 UTC
### Expected behaviour
Toots showed

### Actual behaviour
![image](https://user-images.githubusercontent.com/13418482/84722324-1719ef00-afad-11ea-95cb-428df1827b5e.png)
Toots not showed. Even though the toots counter is working, it failed to display the toots

### Steps to reproduce the problem
1. Create an account in an instance 
2. Follow an account in another different instance 

### Specifications
v3.1.4

**Comment by julienw** [comment] 2020-06-16 17:28
I see the same thing. As a quick note, I can see the pinned toots, but not the others.

**Comment by julienw** [comment] 2020-06-16 17:31
See #14017 too.

**Comment by trwnh** [comment] 2023-05-16 04:38
Duplicate of #34

**Closed by trwnh** 2023-05-16 04:38 UTC
