### ISSUE TITLE
Announcements are not dated—new accounts may see very old announcements and think they're current

### ISSUE THREAD

**Issue by johnhorner** [mastodon/mastodon#32194] opened 2024-10-01 03:04 UTC
### Pitch

Announcements should have a date showing when they were made.

### Motivation

I recently created a new account on Zirk.us and saw an announcement:

> How do you feel about reducing our maximum character count? Please take a moment to vote!

I do feel strongly about that issue … but the announcement was from December 2022, the poll was long closed and the issue long decided.

A date would have been useful.

**Comment by ClearlyClaire** [comment] 2024-10-04 08:00
Hi! Thank you for your report. This is a duplicate of #18307

**Closed by ClearlyClaire** 2024-10-04 08:00 UTC
Labels: suggestion
