### ISSUE TITLE
Link handler on profile bio/metadata

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#9946] opened 2019-01-30 04:47 UTC
### Expected behaviour

Click hashtag/mention on profile served on web UI

### Actual behaviour

Clicking hashtag/mention will redirect to static page(/tags/tagname or remote instance profile page) + not even in a new tab

### Steps to reproduce the problem

* Use hashtag on you profile bio
![image](https://user-images.githubusercontent.com/5047683/51958819-3df98300-2495-11e9-8799-14d2c2eb49e0.png)

* Mention other user on profile metadata
![image](https://user-images.githubusercontent.com/5047683/51958835-4ea9f900-2495-11e9-960b-0fd5de45fadf.png)

### Specifications

Mastodon v2.7.1

Browser: Firefox 64.0 (64 bit)

**Comment by ThibG** [comment] 2019-02-11 09:08
Yeah, this is because to Mastodon, those are regular links, Mastodon does not attach mention tags to those, neither does it store them locally.

**Comment by Gargron** [comment] 2019-02-12 04:02
The ActivityPub actor JSON does contain mentions and hashtags metadata. But we are not storing/processing it for actors and we are not returning it in the REST API.

**Comment by ThibG** [comment] 2019-02-12 18:23
> The ActivityPub actor JSON does contain mentions and hashtags metadata.

I'm not sure what you're trying to say. I see code for hashtags but not mentions.

**Comment by colinleroy** [comment] 2022-11-26 17:56
Hi,
This is still true post 4.0, whereas #hashtags in posts are now handled to go to <myinstance>/tags/<theHashtag>
Is this still a technical limitation ?

**Comment by trwnh** [comment] 2023-05-16 03:24
Duplicate of #1399

**Closed by trwnh** 2023-05-16 03:24 UTC
Labels: suggestion
