### ISSUE TITLE
Allow separate default post visibility for threads

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [mastodon/mastodon#20340] opened 2022-11-10 16:41 UTC
### Pitch

Extend the user settings which control post visibility (Preferences -> Other -> Posting Defaults) to allow specific settings for (at least) thread follow-on posts. A thread follow-on post is any reply to one's own posts. If the post being replied to has a higher visibility than this setting (as happens when replying to the first post in a thread), the reply's default visibility is adjusted accordingly. If the post being replied to already has this visibility or a lower one (as happens when replying to later posts in a thread with proper visibility), that visibility is inherited; this is the current behaviour for all posts and it should be preserved.

This feature is adjacent to, but not the same as, the features requested in #5723, #8565, and #5108.

### Motivation

It is considered good practice to set follow-on posts of threads to unlisted in order to keep an instance's local timeline clean. However, the current user settings only allow a generic default post visibility that applies to all posts. Many users who do not wish to protect their profile's contents set this to public. The only exception to the setting are replies to posts with limited visibility, which then inherit these posts' visibility by default. Adding finer-grained option(s) would alleviate the manual changing of visibility that is currently necessary. Also, for users that are unaware of visibility, the UI or its defaults, it would allow their posts to not clutter up the local timeline (which they are doing due to ignorance, not out of malice).

**Comment by steelman** [comment] 2022-11-10 16:47
> reply to one's own posts

I believe such settings may be useful for all replies no matter who's the original poster. This may be configurable too.

**Comment by hfte** [comment] 2022-11-12 18:42
Kind of a duplicate of https://github.com/mastodon/mastodon/issues/19685

**Comment by kleinesfilmroellchen** [comment] 2022-11-13 11:58
@hfte didn't find that with the search, we can close this issue then but I'll move my comment over there.

**Closed** 2022-11-13 12:00 UTC
Labels: ui, suggestion
