### ISSUE TITLE
Link preview for a toot should actually preview the linked-to toot

### ISSUE THREAD

**Issue by scruloose** [mastodon/mastodon#22616] opened 2022-12-21 14:17 UTC
### Steps to reproduce the problem

Refer to another toot (post, whatever) in a toot of my own, and link to it so people can click through to the thing in its original context.
Every toot has a URL, so this works …ish.

### Expected behaviour

Preview should contain, resemble, or in some way pertain to the toot I'm linking to.

### Actual behaviour

Preview is dominated by user avatar and name, and provides no glimpse whatsoever of the toot — the thing actually being linked to.

### Detailed description

I've seen open issue reports about some Apple-specific sharing preview thing, but I think this is broader. Even in the web interface, the preview of a link *in* a Mastodon toot *to* another Mastodon toot is so useless that screencapping a toot and "replying" to the screencap with no link to the original at all is a widely-used workaround.

Is the 3-block layout of the preview rigidly hard-coded somewhere? Is there a compelling reason Mastodon can't send *just* the first few lines of the text of the toot instead? If the toot doesn't contain an image, neither should the preview. As it stands, the link preview is actively misleading, looking for all the world like it's a link to a user's profile, not a toot.

### Specifications

Seen on Mastodon 4.02 in Firefox, and Tusky on Android.

**Comment by brandonkelly** [comment] 2022-12-24 12:46
Came here to suggest the same thing. This seems like a good compromise to giving people the ability to “quote-toot”, without specifically adding it as a feature in the UI.

**Comment by theotherlinh** [comment] 2023-01-14 16:05
I'd like to echo a better preview card. And agree it's a good compromise to QT. Frankly, this is all I'd like to see... show the contents of the post (maybe first 250 char + image?), don't notify the author (or anyone mentioned in the OP), gets to the point of contextual information without bugging the OP.

I would expand this to better link preview cards across the board, frankly. I know  some clients do a great job of this. But it'd be nice to see on the web, too.

**Comment by vmstan** [comment] 2023-11-23 00:09
Closing as not a bug, but a feature request for quote toots.

**Closed by vmstan** 2023-11-23 00:09 UTC
Labels: bug
