### ISSUE TITLE
Batch deletion of Dead/Spam Accounts in Webview

### ISSUE THREAD

**Issue by barning** [mastodon/mastodon#13118] opened 2020-02-19 08:07 UTC
### Pitch
On the instance where I am admin, several hundred new spam accounts have registered over a short time. We have switched off the open registration and want to delete the new, inactive accounts. I can identify the accounts quite well, because they all have almost the same IP. But I can’t find any way to perform a batch deletion.

### Motivation
The amount of time admins and moderators would save with a web interface for batch deletion would be very significant. Right now we have to click on every account and ban it.

Looks similar to #11346

**Comment by Gargron** [comment] 2021-11-18 21:55
Duplicate of #11346

**Closed by Gargron** 2021-11-18 21:55 UTC
