### ISSUE TITLE
When you have many similar favorites and reboosts, coalesce them?

### ISSUE THREAD

**Issue by resuna** [mastodon/mastodon#25630] opened 2023-06-28 07:30 UTC
### Pitch

When you have many responses to a message your notifications get flooded with so-and-so favorited/reboosted your message, and it's hard to find new unique and distinct notifications in the spam.

When you have more than a couple of identical notifications, display them as "so-and-so and 37 other people favorited your message" with appropriate linkage to get the actual list of people when desired.

### Motivation

This would benefit anyone whose post goes viral and their notifications suddenly feel like they've opened a packed hall closet in a '50s sitcom.

**Comment by trwnh** [comment] 2023-06-28 10:54
Duplicate of #1483

**Closed by trwnh** 2023-06-28 10:54 UTC
Labels: suggestion
