### ISSUE TITLE
Web interface - UX - When loading a link to a reply post, initial scroll position may not clearly draw user's attention to the correct post

### ISSUE THREAD

**Issue by Laogeodritt** [mastodon/mastodon#26875] opened 2023-09-10 08:17 UTC
### Pitch

I've done a few quick searches and didn't find this mentioned yet—but Mastodon has a _lot_ of issues, so pardon if I've missed it.

As described in the motivation section, when linking directly to a post that is a reply to another post (including threads), it loads with the post's content box's top edge ≈50% down the page, and this makes it unclear to the user in some circumstances whether they were linked to the intended post, or to its parent post.

Would it be possible to change this scroll position on initial load in order to provide clearer UX when loading a link to a reply post? (Or possibly adjust other UI design elements?)

I don't know what constraints Mastodon might have when it comes to calculating height of elements (I know that's not possible to reference in CSS, but might be doable if the scroll position is JS post-render), but I might suggest targeting the display name or start of the post content 1/3 down the page, rather than the top of the content box 1/2 down. (In my limited typesetting/page composition experience, the focal point is often ≈1/3 down a page vertically rather than dead centre.)

Other UI design elements to clarify might include text size and indentation for the target post, which I think the former Twitter used (still uses?).

### Motivation

When loading a link to a post within a thread, or made as a reply to someone else, there are two UX objectives (to me, offhand):

1. Place focus on the post that was linked.
2. Ensure it is clear that the post is a reply to another post.

Currently in Mastodon 4.1.7, when loading a link to a reply post, the page auto-scrolls so that the linked post appears ≈halfway down the main content container of the page. I've noticed a few people I know (myself included) get briefly confused and think the prior post is being linked, depending on the context (e.g. attached images, how tall each post is). The linked post may even be partly scrolled off the page if tall enough, while the previous post may be fully on the page.

Although the background colour of the linked post is slightly lighter, that does not register very well at a glance in this situation.

This behaviour seems to achieve objective 2 very well, but does not always communicate 1 effectively. Both are important, but arguably 1 is more important given that that is the content that corresponds to the URL itself.

An example is here (thread of my own posts): https://kind.social/@laogeodritt/111022905901525109 - on loading, it looks like the previous post's attached image is the focal point, and I had two people ask me if I'd given them the wrong link as it didn't match what I described to them when I linked them.

Screenshot as it appears to me (media and identity information hidden—just not to upload it to GitHub, obviously it's available at the link above):

![image](https://github.com/mastodon/mastodon/assets/1468874/725729a8-12da-451a-b328-93b86210602f)

**Comment by ClearlyClaire** [comment] 2023-09-11 08:32
This sounds like a duplicate of #18312, which should be fixed by #24685, part of the upcoming 4.2.0.

**Comment by brendanjones** [comment] 2023-12-23 23:46
@ClearlyClaire I don't know if it's exactly the same situation/problem, but:
- on desktop when you publish a reply,
- and then click "open" on the "Post published" toast notification, 
- and the thread is long so your reply is off the bottom of the page
- then you're not shown your reply.

In fact, your scroll position doesn't seem to change at all. If I'm scrolled to the top of the thread when I post my reply, then do the above process, my scroll position doesn't move. In other words, it feels like the 'open' action wasn't successful. The only way I know it was is that the url does change, and if I scroll down I see my reply.

My server is on v4.2.3.

**Comment by ClearlyClaire** [comment] 2024-01-03 10:47
@brendanjones I'm not sure exactly what is happening yet, but I can replicate the issue. I think this is not the exact issue originally reported here (scrolling to the wrong post) but something more along the lines of scrolling to the correct post just for it to be immediately shifted around by more posts loading.

**Closed** 2024-01-04 14:17 UTC
Labels: suggestion, area/web interface

**Comment by brendanjones** [comment] 2024-01-04 14:59
@ClearlyClaire does that PR solve the issue I mentioned, and if not do you want me to make a separate issue for it?
