### ISSUE TITLE
Force-sensitive domain blocks

### ISSUE THREAD

**Issue by puyoxyz** [mastodon/mastodon#23101] opened 2023-01-15 11:31 UTC
### Pitch

Right now, there's an option to "force-sensitive" a user[1] (force all their media to be flagged as sensitive), but this option doesn't exist for domains/servers

So, basically, the request is: that same feature, but for domains/servers

### Motivation

Some servers don't moderate users not marking their media as sensitive correctly, but I don't want to just completely block all media from those servers, I just want to make it flagged as sensitive

[1]
![image](https://user-images.githubusercontent.com/15311104/212538188-a5ac8673-79bf-4611-b0a3-e0e6d08af04c.png)

**Comment by ThisIsMissEm** [comment] 2023-07-16 21:22
This appears to be the same issue as #20514   though subtly different.

**Comment by trwnh** [comment] 2023-07-16 23:42
Closing as a duplicate of #20514 because the implementation would be the same

**Closed by trwnh** 2023-07-16 23:42 UTC
Labels: suggestion
