### ISSUE TITLE
Title and excerpts of web page previews sometimes contain HTML entities

### ISSUE THREAD

**Issue by AxelBoldt** [mastodon/mastodon#21598] opened 2022-11-25 01:25 UTC
Posts that include a URL will have a short web page preview at the bottom, and here I often see out-of-place HTML entities or Unicode characters which don't appear on the web pages themselves.

For example, see this post: https://mathstodon.xyz/@tao/109400708957917909

(Using web interface v4.0.2 on Firefox 107.0/Windows 10.)

**Comment by Soviut** [comment] 2022-11-25 02:49
@AxelBoldt In Chrome this looked fine to me. Are you able to take a screenshot and add it to your post?

**Comment by ineffyble** [comment] 2022-11-25 04:44
Duplicate of #21360.

**Closed by ineffyble** 2022-11-25 04:44 UTC
Labels: bug
