### ISSUE TITLE
Toot as another user

### ISSUE THREAD

**Issue by ArnoldSchiller** [mastodon/mastodon#23736] opened 2023-02-20 00:29 UTC
### Pitch

I don't know if it's possible, the feature request is a bit complex. "Toot as" - some people may know the function, whether on Facebook or Twitter. On Facebook, these are pages where other accounts are entered as editors or admins. On Twitter, Tweetdeck fulfilled the possibility. The user logs in under his normal user name and receives authorisation to write under a different name and as a different account from the respective page administrator or account administrator. In order for this to work across different instances in Fediverse, the software would have to be an SSO provider so that a "toot as" across different instances would be possible. 

Example of an event where a username is opened on a server. 10 users somewhere in the Fediverse get permission to post there as an invitation and 10 Fediverse users could then post as this event and reply with their own Fediverse username in the login, but "toot as" this event.

### Motivation

Manage teams for organisations and events

**Comment by hex-m** [comment] 2023-02-22 19:02
Thank you for your Suggestion!

The "toot as.." part of your request is discussed in #380 and #23288.

The "give permissions to others to toot as this account" is requested in #15896 with some related discussions in #20804.

Both topics are similar as both mean we have to give up the 1-to-1 relation between a set of credentials that is used to login, and an account/profile/identity. So one human (E-mail address + Password + Second factor ) should be able to manage multiple ActivityPub actors and one ActivityPub actor should be sharable between multiple humans.

**Comment by ArnoldSchiller** [comment] 2023-02-23 02:29
"So one human (E-mail address + Password + Second factor ) should be able to manage multiple ActivityPub actors and one ActivityPub actor should be sharable between multiple humans." When an account with password and access is shared, that is ultimately something completely different than when I grant someone access. I have seen it happen that someone who was given access then changed the password because they also had access to the email address and took over the account with hostile intent. With an admin-editor relationship like on tweetdeck, for example, that never happened. The admin can revoke the privilege of the abusive content publisher and he cannot take over the account as an act of revenge. This 1:1 relationship with disclosure of account, password and mail only needs a single team member to be ill-intentioned, for whatever reason. But if this is the only way to do it in Mastodon, then it is bound to happen. A single person does not have all the information and is overloaded to operate an account. But I know that also at ProtectTheKids or WatchUnion where a single person can not afford it. Of course you don't have to move to the Fediverse if the feature is missing and some will not do that then. These accounts, where it is the case that only one can take care of it, then quickly fall asleep again, because a single person is simply overwhelmed and some content can only be done in a team. But well, if that was already disktutiert and Mastodon has decided against it, then that's just so.

**Comment by vmstan** [comment] 2024-11-23 23:41
Closed as duplicate of #15896

**Closed by vmstan** 2024-11-23 23:41 UTC
