### ISSUE TITLE
UI: Displaying role on user page

### ISSUE THREAD

**Issue by Izorkin** [mastodon/mastodon#20031] opened 2022-11-07 19:46 UTC
### Steps to reproduce the problem

1. Open user page with administrator/moderator rights.
2. In settings of roles Owner/Administrator/Moderator, set option "Display role as an icon in user profiles".

### Expected behaviour

The user page displays role

### Actual behaviour

Role not showing on user page

### Specifications

Mastodon 4.0.0rc2
Ruby 3.0.4
Nodejs 18.9.1

Vivaldi 5.5.2805.38 (Chrome/106.0.0.0)

**Comment by MBeggiato** [comment] 2022-11-11 10:33
Yup. rc3 still has this issue.

**Comment by ineffyble** [comment] 2022-11-14 18:06
This is likely to not be addressed until v4.1.

**Comment by Ry3yr** [comment] 2023-01-09 20:26
Yep.
The role won't show up anywhere on the profile under the current ver 4.0.2

**Comment by justdaj** [comment] 2023-02-18 18:58
Still not resolved in 4.1  :-(

**Comment by justdaj** [comment] 2023-03-20 21:09
No fix in 4.1.1

**Comment by cdp1337** [comment] 2023-04-30 04:08
![Screenshot from 2023-04-29 23-59-20](https://user-images.githubusercontent.com/737865/235334969-bb915fd6-e3cc-4616-843d-11be04c39fef.png)
![Screenshot from 2023-04-29 23-59-44](https://user-images.githubusercontent.com/737865/235334971-5397fa91-e39d-42ef-b263-f25d1a43ed06.png)
![Screenshot from 2023-04-30 00-00-26](https://user-images.githubusercontent.com/737865/235334972-1067d3ce-a635-4b0f-8965-833d993c660f.png)

I dunno where the official opinion of this feature is at right now, but roles appear to be supported in the backend so I took some code I found in the app and adopted it to actually implement this request.  Code is on a separate branch and can be cleanly merged into main.

https://github.com/cdp1337/mastodon/tree/features/20031-display-role

**Comment by JeremyStarTM** [comment] 2023-04-30 08:03
Thank you for fixing that bug. Hope it gets merged with the official repo.

**Comment by justdaj** [comment] 2023-04-30 09:37
> I dunno where the official opinion of this feature is at right now, but roles appear to be supported in the backend so I took some code I found in the app and adopted it to actually implement this request. Code is on a separate branch and can be cleanly merged into main.

Amazing.  Thank you
I did read somewhere that it's on the roadmap to fix, but seems to have been a bug for a while.

**Comment by ClearlyClaire** [comment] 2023-05-02 15:55
Duplicate of https://github.com/mastodon/mastodon/issues/19922

**Closed by ClearlyClaire** 2023-05-02 15:55 UTC
Labels: bug

**Comment by VityaSchel** [comment] 2023-08-03 11:17
> ![Screenshot from 2023-04-29 23-59-20](https://user-images.githubusercontent.com/737865/235334969-bb915fd6-e3cc-4616-843d-11be04c39fef.png) ![Screenshot from 2023-04-29 23-59-44](https://user-images.githubusercontent.com/737865/235334971-5397fa91-e39d-42ef-b263-f25d1a43ed06.png) ![Screenshot from 2023-04-30 00-00-26](https://user-images.githubusercontent.com/737865/235334972-1067d3ce-a635-4b0f-8965-833d993c660f.png)
> 
> I dunno where the official opinion of this feature is at right now, but roles appear to be supported in the backend so I took some code I found in the app and adopted it to actually implement this request. Code is on a separate branch and can be cleanly merged into main.
> 
> https://github.com/cdp1337/mastodon/tree/features/20031-display-role

Provided solution does not work anymore, since "account" class has changed and account.get('roles') now returns undefined. I explored this class and found that it has _root.nodes hashmap with 31 entries. Now I'm trying to find which one if role

**Comment by VityaSchel** [comment] 2023-08-03 11:32
This doc says that /api/v1/accounts/lookup?acct= should return role: https://docs.joinmastodon.org/entities/Account/
however, when I look to /app/services/resolve_account_service.rb there is no "role" field

**Comment by trwnh** [comment] 2023-08-03 15:51
@VityaSchel ResolveAccountService is for resolving remote accounts. For that API method you should be looking at app/controllers/api/v1/ or something similar. and for the actual entity, look at the serializers in app/serializers/rest/

in any case, the change you are seeing is that the old role property (user, moderator, admin) was replaced with the new role system, but not exposed in a new property until https://github.com/mastodon/mastodon/pull/23255 which will be part of 4.2
