### ISSUE TITLE
Maintenance mode / Activate via CLI

### ISSUE THREAD

**Issue by ralfr** [mastodon/mastodon#20142] opened 2022-11-08 16:47 UTC
### Pitch

It would be awesome if one could programmatically enable/disable a maintenance mode via the Admin CLI and set a custom message.

### Motivation

- Maintenance mode would show a static (?) page to all users that the instance is currently undergoing maintenance and an optional custom message.
- On the API level, maintenance mode could signal to other instances and clients, that the instance is currently undergoing maintenance (as opposed to being down). Clients (apps, etc.) should deal with the status accordingly.
- Other instances could apply e.g. an exponential backoff strategy and "come back later" to continue federation etc.

Optionally, one could set a time date, when the instance is expected to be back fully operational and the information could be used by consumers for advanced functionality.

**Comment by ClearlyClaire** [comment] 2022-11-08 18:05
Duplicate of #19961

**Closed by ClearlyClaire** 2022-11-08 18:05 UTC
Labels: suggestion
