### ISSUE TITLE
Long URL in Profile page breaks grid design (web UI)

### ISSUE THREAD

**Issue by imacdonald** [mastodon/mastodon#8602] opened 2018-09-03 22:34 UTC
Release 2.5.0
Entering a long URL in the Profile page of the web UI forces out the width of column-1 beyond alignment with the header. My long Socialhome URL is the culprit in the attached screenshot.

![2018-09-03-232956_1532x830_scrot](https://user-images.githubusercontent.com/1724575/45002722-eaf8ce00-afd1-11e8-8ca3-8509d10d2a60.jpg)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by JMendyk** [comment] 2018-09-04 07:32
I tried to reproduce your issue on Chrome 68.0.3440.106 and Firefox 61.0.1 and unfortunately haven't been to reproduce your issue.

If I may ask, what is the browser (and version) you are using? New public profile page uses CSS Grid which may not be fully supported by your browser. Also, could you check out the same page using other browser you have available?

**Comment by imacdonald** [comment] 2018-09-04 20:26
Thanks for the quick reply.

The problem happens with PaleMoon 28 (latest version) and Firefox 52.9
(which is an ESR version). The intended layout is rendered correctly
with Chromium 61.

**Comment by JMendyk** [comment] 2018-09-04 21:08
Firefox 52 was the first one to implement CSS Grid but they initially had some issues with overflow, which match your issue ([1356820](https://bugzilla.mozilla.org/show_bug.cgi?id=1356820), [1348857](https://bugzilla.mozilla.org/show_bug.cgi?id=1348857), [1350925](https://bugzilla.mozilla.org/show_bug.cgi?id=1350925)) which were fixed in Firefox 54. PaleMoon 28 is the first one to support CSS Grid (thus profile page looks mostly ok), apparently they also have layout overflow issues.

I'll try to look into finding an easy way to fix this issue when I have some spare time but I don't have previous experience with CSS Grid.

Maybe @Gargron will be able to better help you and investigate this issue, since he redesigned public profiles in #8068 and (obviously) is author of Mastodon.

**Closed** 2023-05-14 16:41 UTC
Labels: bug
