### ISSUE TITLE
Link Preview removes any hashes from the actual link

### ISSUE THREAD

**Issue by Arbee4ever** [mastodon/mastodon#21411] opened 2022-11-22 17:45 UTC
### Steps to reproduce the problem

1. post a link with a hash
2. hover over the link preview
3. see that it's not there

### Expected behaviour

The hash should stay

### Actual behaviour

I gets removed

### Detailed description

Example of this can be seen [here](https://floss.social/@modrinth/109388328504602384)

### Specifications

Firefox 106.0.4
Fedora 37
Mastodon v4.0.2

**Comment by Brawaru** [comment] 2022-11-22 17:50
Link in post has the correct fragment (hash):
![Screenshot of the correct link shown in tooltip when hovering the link in post](https://user-images.githubusercontent.com/10401817/203385125-0705ddbc-f8a5-4f1f-a39d-269a65711fcd.png)

However in post it doesn't have that, resulting in broken link:
![Screenshot of the incorrect link when hovering over the embed](https://user-images.githubusercontent.com/10401817/203385406-591bba06-ff70-4b14-ae6f-c19cdc08c1a9.png)

**Comment by Brawaru** [comment] 2022-12-03 15:13
Duplicate of #19538. Will probably be fixed by #21974.

**Closed** 2023-05-19 06:38 UTC
Labels: bug
