### ISSUE TITLE
CWs for Boosts

### ISSUE THREAD

**Issue by mespotine** [mastodon/mastodon#20818] opened 2022-11-15 20:20 UTC
### Pitch

I would like to be able to add CWs to Boosts to protect my followers from non-cw'ed toots. 

### Motivation

To protect my followers from non-cw'ed toots that could affect followers but at the same time be able to boost these toots.

**Comment by CEbbinghaus** [comment] 2022-11-16 08:01
At that point its only a small step removed from quoted replies. Since it would be infeasible to change the CW of the original post, This information would have to be attached to specifically the boost itself. At that point other information could be attached too such as text content and what you are left with is essentially a quote reply. I don't think there is an elegant way to solve this without paving the way for Quote toots

**Comment by brocoli** [comment] 2022-11-30 19:53
https://github.com/mastodon/mastodon/issues/13291

**Comment by trwnh** [comment] 2023-05-20 20:07
Duplicate of #13291

**Closed by trwnh** 2023-05-20 20:07 UTC
Labels: suggestion
