### ISSUE TITLE
Ability to filter or block posts based on the app that posted them

### ISSUE THREAD

**Issue by hach-que** [mastodon/mastodon#21370] opened 2022-11-22 02:48 UTC
### Pitch

A non-trivial number of people use apps that cross-post from Twitter to Mastodon. These apps are often completely unaware of things like content warnings.

Rather than individually blocking or muting people when I see cross-posted content come up in my timeline (since I follow hashtags), I'd like to be able to filter or block posts based on the app that sent them. I think the most trivial and straight-forward implementation would be to add a new block option here:

![image](https://user-images.githubusercontent.com/504826/203208642-3dce25b4-fdff-44d8-bb66-46195b4478cb.png)

### Motivation

Now that following hashtags is a feature, you're far more likely to see content by random people using the hashtags and this includes content that is coming from automatic cross-posting accounts. Having a quick way to filter out all of the cross-posters by app would be much more efficient than blocking individual accounts.

**Comment by afontenot** [comment] 2022-11-22 04:18
Agree on the feature, but probably a dupe of https://github.com/mastodon/mastodon/issues/8271

**Comment by ClearlyClaire** [comment] 2022-11-22 12:29
Closed as duplicate of #8271

**Closed by ClearlyClaire** 2022-11-22 12:29 UTC
Labels: suggestion
