### ISSUE TITLE
Multichoice poll - cannot change answer even when poll is still open

### ISSUE THREAD

**Issue by wcbutler** [mastodon/mastodon#20611] opened 2022-11-14 01:49 UTC
### Pitch

Noticed this with Fedilab app where I voted and realized my answer was wrong and the poll was still open that I couldn't change it. Not sure if it's a native issue with their app or with Mastodon but wanted to post it to help. 

### Motivation

Anyone using polls.

**Comment by wcbutler** [comment] 2022-11-14 01:50
Made this a feature and not a bug because maybe that was expected behavior

**Comment by ClearlyClaire** [comment] 2022-11-15 09:59
That is indeed expected behavior, we don't allow users to change their votes after they have voted.

**Comment by hinnerk** [comment] 2023-12-17 10:39
The iOS app (2023.16 build 6043) has currently minimized away the last hint of some indented text being a poll – the bullets – (see example picture below) and utilizes a one-click interface, leading to a UI where a single click on an innocently looking text creates a "vote".

This just happened to me in a case where I wasn't even aware that there was a poll (I'm rather new to Mastodon). I never had the intention to vote, the accidental vote it is for something that I condemn – and now it turns out that I can't even get rid of that blasted thing.

Please, give users an option to undo accidental votes through the web interface. If you want to prohibit changing votes, then please add a 'delete' functionality.

Here's a more innocent example of the poll UI. Note that the poll that "lured" me in was from a person, did have no hashtags and was set private for followers only, so in my case there was only indented text and no hint that there even might be a poll.

<img width="227" alt="2023-12-17 poll ui mastodon app 2023 16 (6043)" src="https://github.com/mastodon/mastodon/assets/24145/38826f14-8a94-4853-a78a-746ec3e25f7c">

**Comment by renchap** [comment] 2023-12-18 11:39
iOS issue opened here: https://github.com/mastodon/mastodon-ios/issues/1197

Closing this issue as not allowing someone to change their answers is a feature.

**Closed by renchap** 2023-12-18 11:39 UTC
Labels: suggestion
