### ISSUE TITLE
Add categories for toots

### ISSUE THREAD

**Issue by allo-** [mastodon/mastodon#17667] opened 2022-02-28 10:41 UTC
### Pitch

Currently, toots can be filtered by hashtags, which also make them more visible, and using hashtags is entirely optional.

Mastodon should add categories, which can and possibly must be selected (including an "other" or "general" category). Examples for these categories would be:

- Art
- Photography
- Politics
- Conversation
- Projects
- Activism
- Comics
- (...)
- Other

By encouraging users to actually select a category via a dropdown, many more toots would have a category on which other users can filter. Other than hashtags, the category would not lead to the toot being included in more searches (use an *additional* hashtag for this), but they could be muted by category and filtered by category (e.g., by pinning a "Politics" (Categories: `Politics`, `Activism`, ...) column and a "Beautiful things" (Categories: `Art`, `Photography`, ...) column).

The list should be mostly fixed, and if custom categories are allowed they should be discouraged, e.g., by making it one click to select "Politics", but more clicks to create a new category, e.g., `Other Category -> Add Category -> "Some Category only I am using"`. Custom categories would be more an option to find out which categories are missing from the list. For more dynamic tagging there are still hashtags and for more dynamic warnings there is still the CW function.

### Motivation

People seem to use hashtags rarely and inconsistently, making it difficult to filter on them.

The use of spoiler tags CWs either hides everything with a CW or shows everything depending on the user setting to always show content with a CW, but does not allow to only hide posts with certain content.

Using a dropdown list of categories is both fast to use when writing a toot and easy to filter on, as the list of categories is much smaller than the list of hashtags that one has to filter to achieve the same result. It can also be expected that people are more willing / less forgetful to use categories than always adding a hashtag.
It also makes categories discoverable, so people notice "Oh, there are people who like me to tag that a post is about sports" who would not have thought about tagging sport posts when there was only a text field.

**Comment by loxK** [comment] 2023-12-18 02:03
Want ! I woulds love to follow some people's categories instead of all their posts.

**Comment by trwnh** [comment] 2023-12-18 04:21
Duplicate of #1208

**Closed by trwnh** 2023-12-18 04:21 UTC
Labels: suggestion
