### ISSUE TITLE
Hashtag / Hashtags won't work on toots with CW / content warning

### ISSUE THREAD

**Issue by KNTRO** [mastodon/mastodon#11443] opened 2019-07-29 12:22 UTC
### Expected behaviour

I should be able to click on hashtagged words.

### Actual behaviour

Hashtags are not created/clickable.

### Steps to reproduce the problem

Just redact a toot with content warning and add hashtags to the toot. [Here's an example of the output toot](https://mastodon.social/@KNTRO/102524592320896636).

### Specifications

Mastodon Web v2.9.2.

**Comment by Cassolotl** [comment] 2019-07-30 11:16
Hashtags in the CW field don't work, but if you put the hashtags under the CW, in the body of the toot, they work. CWs are intended to be plaintext. :)

**Comment by KNTRO** [comment] 2019-07-30 11:30
The hashtags I used are in the body of the toot, like this:
[body of toot]
Blah blah blah, #hashtags are here
[CW content, clic to view]
[/body of toot]

**Comment by Cassolotl** [comment] 2019-07-30 16:04
By "body of the toot" I mean the bigger text box. Here's a screenshot of what I mean:

![Screenshot 2019-07-30 at 17 03 51](https://user-images.githubusercontent.com/6607512/62145871-1cfed700-b2ec-11e9-855b-fe690fa7936b.png)

**Comment by Prog1563** [comment] 2020-10-06 13:17
This would be a very nice feature to have

**Comment by dioraman** [comment] 2021-03-04 14:58
Please fix this since it is counter-intuitive for newcomers that hashtags will not work in content warning.

**Comment by Vaguery** [comment] 2022-11-22 14:34
Watching a large number of newcomers being told by the existing Mastodon community to "use CW as if it was a subject line" and also "use hashtags for findability".

If one cancels the other, this is a bug.

**Comment by trwnh** [comment] 2023-05-14 23:35
Duplicate of #699

**Closed by trwnh** 2023-05-14 23:35 UTC
Labels: troubleshooting
