### ISSUE TITLE
Send an Automated Reply to a User After Taking Action on a Report

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#14474] opened 2020-07-31 06:52 UTC
### Pitch

Send an automated reply to a user after taking action on a report.

### Motivation

Currently no communication happens after sending a report. How will a user know whether or not any action was taken? Manually replying to every report would be a time-consuming affair so why not send an automated reply instead? This will also encourage users to help admins/mods keep an instance. . . clean.

**Comment by ThibG** [comment] 2020-07-31 17:22
Being able to (optionally) reply with a follow-up to reports (even across instances, while respecting the privacy of the original instance) is something I tried to push a while ago. If I remember correctly, the main concern about that was about “abusive reporters” getting feedback regarding whether their reports have been acted upon or not, possibly making them angrier if the reports haven't been dealt with etc.

I personally think those concerns are relatively minor, especially if follow-ups are optional, while helping good-faith reporters assess whether their reports have any effect, and, allowing instance admins to report back to the reporter if they're not taking immediate action for instance (e.g., “I'm not banning the reported user now, but I've got in touch with them and they agreed not to do that thing again”).

On a slightly related note, I still think it makes sense for instance admin to know if reports their users made have been forwarded (#13237).

**Comment by Sasha-Sorokin** [comment] 2020-07-31 19:09
> feedback regarding whether their reports have been acted upon or not, possibly making them angrier if the reports haven't been dealt with etc.

Twitter and VK just won't send you a notification if no action was taken, but you can't really tell whether your request was even processed or it's just they decided no action is necessary. I really wish moderation was slightly more transparent and you could feel the impact of your reports (currently it feels like you shout into the void).

It's just simple notifications like this:

- (in a few minutes after reporting) “Your report about @{handle} was received.”
  - on click would open modal with details about report and reported posts
- (if forwarded) “Your report about @{handle} was received and was forwarded to {domain}.”
  - same as above, but now with remark that report was forwarded to {domain}
- (after action has been taken and moderators decided to reply) “An update on your report from {date}.”
  - also would open details about the report, but now with comment that action was taken like:

    >“… based on our investigation, we found violation of our code of conduct and taken necessary action.”
    
    > “Thank you for reporting, reports like yours help keeping {domain} a safe place.”
  - would be sent twice if was forwarded and remote moderators decide to also take an action
  - this includes just resolving with no action (unless done silent?)

BTW! There should be a system in place that would detect duplicate reports and merge them into one, but sending notifications to all the reporters, so it won't be the first person who reported to receive the update.

**Comment by rixx** [comment] 2022-06-23 09:16
Bumping this to say that we would appreciate it a lot!

Ideally this would be a simple text field with the option to select templates, just like the warning procedure. Being able to send the reporter a message of "It's been handled, thank you for reporting" would make things quite a bit better both for us (no need to log in to the admin account and send individual DMs) and for the users (actual feedback that their report has not been swallowed by the void).

**Comment by dilinger** [comment] 2022-12-26 21:30
> Being able to (optionally) reply with a follow-up to reports (even across instances, while respecting the privacy of the original instance) is something I tried to push a while ago. If I remember correctly, the main concern about that was about “abusive reporters” getting feedback regarding whether their reports have been acted upon or not, possibly making them angrier if the reports haven't been dealt with etc.

Honestly, a reporter *should* be angry if their report hasn't been dealt with. Unless the instance is a free-for-all, users should have an idea of how on top of things their instance's moderation team is. If they're not on top of things, that means it's time to migrate (or volunteer to help out). If a user's behavior rises to the level of abusive based on their response to moderation, then maybe the user is the problem and the mods can ban them.

I consider a behavior report like a bug report. There is a problem with (a user's behavior on) the instance, and I should have some idea of the outcome of a report. I should also be able to see a full list of my reports, which comes in especially handy if I'm being targeted for some reason.

The claimed reason for not quoting is due to concerns about pile-ons, but coordinating that pile-on can still happen on other forums or even here with a basic link to a toot. Reporting is our tool to deal with abusive pile-ons. The process of dealing with reports should not be opaque.

**Comment by trwnh** [comment] 2024-01-31 08:00
Duplicate of #1685

**Closed by trwnh** 2024-01-31 08:00 UTC
Labels: moderation, suggestion
