### ISSUE TITLE
POST /api/v1/apps is opened

### ISSUE THREAD

**Issue by 3DRaven** [mastodon/mastodon#21991] opened 2022-12-03 15:51 UTC
### Steps to reproduce the problem

curl --request POST \
  --url https://mastodon/api/v1/apps \
  --header 'content-type: multipart/form-data' \
  --form client_name=X \
  --form redirect_uris=urn:ietf:wg:oauth:2.0:oob \
  --form scopes=X \
  --form website=X

### Expected behaviour

Registration of application is closed and allowed only by approvals by Admin

### Actual behaviour

Registration of apps is opened

### Detailed description

I can create request to this API for server created from prepared Droplet 
https://marketplace.digitalocean.com/apps/mastodon
So, any "bad" guy can register infinite number of application on my server,
or I need to close this URL path by Nginx. I do not have 
methods to approve some applications by Mastodon admin panel.

### Specifications

From Droplet
Mastodon Version 4.0.2 OS Ubuntu 20.04

**Comment by ineffyble** [comment] 2022-12-03 16:02
Is your concern that someone could spam the endpoint and create a lot of rows in the database?

**Comment by 3DRaven** [comment] 2022-12-03 16:13
Yes

**Comment by 3DRaven** [comment] 2022-12-03 20:48
On mastodon.social registered apps: 1563915

**Comment by 3DRaven** [comment] 2022-12-03 21:36
Next step of attack
POST https://mastodon.example/api/v1/accounts because app registration is opened you can create App and spam by it by creating lot of accounts without any email verification, just for fill db It is faster slow down db.

**Comment by ineffyble** [comment] 2022-12-04 03:26
It's worth noting this is the basis of how Mastodon apps work, from the official iPhone clients all the way to Twitter crossposters and stuff. Changing to a model where apps require approval would fundamentally break the app ecosystem. Putting some kind of rate limiting or similar on the endpoint wouldn't be a bad idea, but can also be accomplished outside of Mastodon (e.g. in config on the web server, CDN, or similar).

Also, I think the fact that mastodon.social happily has 1.5 million apps also shows there's not a huge performance impact here. If an attacker wanted to bring down a Mastodon instance and was happy to make over a million HTTP requests, there's probably far better ways they could do it.

**Comment by ineffyble** [comment] 2022-12-04 03:29
As for filling the db with accounts, every remote account an instance sees creates an account record (as we see with the recent activitypub-troll matter). So there's far better and more efficient ways to clog up an instance's accounts table.

**Comment by 3DRaven** [comment] 2022-12-04 09:33
`If an attacker wanted to bring down a Mastodon instance and was happy to make over a million HTTP requests, there's probably far better ways they could do it.`

It is not an attacker, it just regular activity. Fortunately. May be rate limits already set for this endpoints by default or by default any instance can be spammed? Or it is just undocumented?

`As for filling the db with accounts, every remote account an instance sees creates an account record (as we see with the recent activitypub-troll matter). So there's far better and more efficient ways to clog up an instance's accounts table.`

Do I understand correctly that by having better ways to destroy instances, you justify the fact that this one should also be?

This data spam methods do not need to be fast, we just can create 10 strings spam bot and destroy small nodes for a week.

**Comment by ineffyble** [comment] 2022-12-04 09:37
Being able to create accounts (if the server is open for registration) is not a bug, it's the intentional behaviour of Mastodon. It's also not something that needs an OAuth app to do, so restricting creation of apps does not offer any protection or additional security in that respect.

**Comment by 3DRaven** [comment] 2022-12-04 09:52
In POST /accounts endpoint documented rate limit, so, we can spam only with limited rate. But need a captcha here. Because we can spam from any node in Fediverse (a lot spam bots). It is not a normal and `it's the intentional behaviour of Mastodon` it is just architectural bug, not a program bug. And possibility to fill db by any other methods without limiting it is architectural bug too, I just not shure about quality of documentation, I hope there is undocumented limits.

But, my deal it is create bug and description ;)

**Comment by ineffyble** [comment] 2022-12-04 09:57
> But need a captcha here.
See #877 for tracking this.

**Comment by 3DRaven** [comment] 2022-12-04 09:59
Now I see lot of methods to attack to Fediverse. So, not only I.

**Comment by ThisIsMissEm** [comment] 2023-10-19 19:46
Whilst the `/api/v1/apps` endpoint is not specifically rate-limited, it is rate limited using the `throttle_unauthenticated_api` rule, which is currently 300 requests in a 5 minute period per IP Address. It would be possible to add a lower rate limit for that endpoint specifically.

`/api/v1/accounts` is specifically rate limited by `throttle_api_sign_up` at 5 requests per 30 minutes.

Keep in mind that every client that connects to the Mastodon API that is not a confidential client (i.e., one that can securely keep a secret such as a pair of client credentials (client_id, client_secret) secure & safe) is a separate application registration. That is, two installs of Ivory will result in different credentials (client_id and client_secret) since that application is not a confidential client but a public client. This is the way that OAuth 2.0 is designed.


We could additionally track the `last_used_at` timestamp for OAuth Applications, not just OAuth Access Tokens, this would then allow us to revoke applications that haven't been used in a while requiring a new registration and new oauth access tokens.

**Comment by ThisIsMissEm** [comment] 2024-07-28 18:16
I'm currently working on a IETF Internet Draft that I'm hopeful that Mastodon will adopt (Bluesky and IndieAuth already have), which is called [OAuth Client ID Metadata Documents](https://drafts.aaronpk.com/draft-parecki-oauth-client-id-metadata-document/draft-parecki-oauth-client-id-metadata-document.html). This will likely be the successor to our current dynamic client registration-inspired approach.

At the moment `POST /api/v1/apps` has been heavily rate-limited as of https://github.com/mastodon/mastodon/pull/30316, which sets the rate-limit to 5 requests per 10 minutes per IP address. Whilst we acknowledge it's still "attackable", the amount of data used for each OAuth Application is insignificant compared to the amount of data you could create by spamming, say, the scheduled statuses endpoint. This is [vaguely noted](https://datatracker.ietf.org/doc/html/rfc7591) in the RFC for dynamic client registration as a security consideration.

The approach of having an "approval based" flow would only really work for single-user instances, due to the nature of dynamic client registration. This wouldn't work for majority of Mastodon servers which are not single-user instances.

What OAuth Client ID Metadata Documents allows is a `client_id` that is a URI to the JSON you would typically send to the dynamic client registration endpoint (note, this is [slightly different](https://github.com/mastodon/mastodon/issues/30154) to Mastodon's `POST /api/v1/apps` endpoint), the Mastodon server would then determine whether or not it needs to register a new application or use an existing one; If it needs to register a new one, it requests the document at the URI indicated by `client_id` and uses it's contents to perform registration.

OAuth Client ID Metadata Documents will likely be the way to solve the "proliferation of oauth clients" problem that OAuth Dynamic Client Registration faces. You can learn more in #31151

**Comment by mjankowski** [comment] 2024-12-05 18:31
I'm going to close this as wont fix since I think the conversation revealed that there's not really a way to make this better given the application intended design, and because the rate limit was changed in that linked PR.

Perhaps future work on OACMD will further improve things.

If I've missed something important here or there's more to resolve, please reopen!

**Closed by mjankowski** 2024-12-05 18:31 UTC
