### ISSUE TITLE
Add to Lists: Not Followed Accounts

### ISSUE THREAD

**Issue by living8bit** [mastodon/mastodon#22744] opened 2022-12-26 05:47 UTC
### Pitch

I like to view news feeds from various sources, but some post _**way**_ too often and thus the home timeline gets cluttered/overrun.  The only choices are unfollow, mute, or block.  Doing any of those does not provide a regular means of seeing what's "going on" (i.e. like #Explore) within "those" accounts.

By being able to add _unfollowed_ accounts to a list, we can view these other sources of information without the home timeline clutter.

### Motivation

I feel everyone could benefit.  Currently, the only real solution to this I know of, is to put all your followers, _except_ the "clutter" ones, into a list.  Then, change the interface to view your primary list and only go to your "Home" timeline when you want to view the clutter.  However, this seems counter-intuitive, _plus_ every time you follow someone "normal", you also have to add them to a/the list.

Thanks for your consideration.

--Living8Bit

**Comment by Cassolotl** [comment] 2022-12-26 10:42
Duplicate of _Feature request - add accounts to list without following them #6982_ (2018).

**Comment by mtalexan** [comment] 2022-12-26 19:08
As an alternative, an option to follow but hide from my timeline would be nice. They could still be added to lists and viewed there, but aren't part of the default "timeline" list.

**Closed** 2023-05-19 06:24 UTC
Labels: suggestion
