### ISSUE TITLE
When WHITELIST_MODE=true, /about pages are 404

### ISSUE THREAD

**Issue by tweitzel** [mastodon/mastodon#12450] opened 2019-11-23 03:04 UTC
### Expected behaviour
/about and /about/more should appear as normal while logged in.
```
Nov 23 02:52:56 rustycat bundle[8117]: [74c87943-2c29-41a5-a346-c540d3ac729d] method=GET path=/about/more format=html controller=AboutController action=more status=200 duration=35.98 view=26.09 db=4.41
```

### Actual behaviour
/about and /about/more return 404
```
Nov 23 02:44:36 rustycat bundle[31166]: [7213ce12-6788-4805-a1a2-86bb355615a1] method=GET path=/about format=*/* controller=AboutController action=show status=404 duration=0.74 view=0.00 db=0.00
```

### Steps to reproduce the problem
Install a new mastodon on ubuntu 18.04 according to deployment guide.
Put WHITELIST_MODE=true in .env.production and start.
Log in with admin account to get a cookie.
/about and /about/more 404s
Put WHITELIST_MODE=false in .env.production and restart.
/about and /about/more both work fine.
Put WHITELIST_MODE=true in .env.production and restart.
/about and /about/more both 404.

### Specifications

v3.0.1

Tested on ios, mac safari, linux firefox, mac chrome.

**Comment by ThibG** [comment] 2019-11-27 18:09
This is by design, although I disagree with that design…

**Comment by tweitzel** [comment] 2019-11-27 18:52
It's by design that the about page doesn't even work for logged-in users?
This also affects /api/v1/instances which prevents the Toot! app from working.

**Comment by tweitzel** [comment] 2019-11-29 06:34
I think this is the issue: https://github.com/tootsuite/mastodon/blob/07da35c17c4ff8e0fc7b90aba0b619dae119a633/app/controllers/about_controller.rb#L34

Why should logged-in users be punished by getting 404s from clicking the about link on every page of the UI?

**Comment by ThibG** [comment] 2019-12-01 13:14
Yes, not having about pages is by design, but that's not something I agree with. I think the main idea was that they wouldn't look like Mastodon instances from the outside. Having a link to the about page while it's not viewable seems like an oversight, though

**Comment by mjankowski** [comment] 2024-11-26 21:19
Last update here is ~5 years ago, and original issue was about a long-outdated version.

Is this still an issue on current version (the setting name here has changed as well), and separately - the conversation seemed to resolve with roughly "This is a wontfix even though it doesnt make sense", if thats still accurate, should we close?

**Comment by ClearlyClaire** [comment] 2024-11-28 12:27
The issue is a bit different now, as the `/about` HTML page is actually served, but the API requests to `/api/v2/instance` and `/api/v1/instance/extended_description` required for rendering of the actual contents are denied with a 401. The reasoning is the same.

Issues #20777, #23434 and #21082 might be more fitting for the new behavior.

**Closed** 2024-11-29 06:08 UTC
Labels: partially a bug, area/web interface
