### ISSUE TITLE
New columns in advanced web interface should be closer to where you click

### ISSUE THREAD

**Issue by jasonycw** [mastodon/mastodon#26279] opened 2023-08-01 13:53 UTC
### Pitch

When in advanced web interface, every time when you trigger a new "pannel" by clicking some interactive links, it default to the reuse the column "Getting started" column.

Instead of reusing that, a new column on the right of the column you just click should be inserted and be used, with easy to access buttons at the top to pin or remove the columns.

### Motivation

Since I put the "Getting started" column on the very right of the deck, and it was out of screen most of the time due to how many columns I have, it's very annoying to need to scroll left and right just. 

e.g. I search some profile on the left, click the profile, it scroll the "Getting started" column on the right and now I cannot see my search results

**Comment by renchap** [comment] 2023-08-01 21:25
Duplicate of #25877

**Closed by renchap** 2023-08-01 21:25 UTC
Labels: suggestion
