### ISSUE TITLE
Advanced Web Interface: Open replies of a post in the very same column, not in a different one

### ISSUE THREAD

**Issue by sam1919** [mastodon/mastodon#28634] opened 2024-01-07 13:26 UTC
### Pitch

In the timeline (no, in **all**) columns please let users open the posts in the **same** column instead of a totally different column. When the user presses "back" the previous content should be appear again, with the correct previous post displayed.

### Motivation

I have 5 columns in the advanced web interface.

1. Edit column
2. Timeline
3. Notifications
4. A hashtag column
5. This discovery (or what it's called) column

Whenever I see a post in the timeline and want to open its comments it will open in the "discovery" column at the right. This is not convenient at all.

**Comment by trwnh** [comment] 2024-01-08 06:10
Duplicate of #8048

**Closed by trwnh** 2024-01-08 06:10 UTC
Labels: suggestion
