### ISSUE TITLE
Post stats not showing

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon#29483] opened 2024-03-01 21:08 UTC
### Pitch

I would imagine this has been posted previously.
When scrolling my feed, the quantities for comments, boosts and likes do not appear.
They only appear when opening a post.
This needs a fix

### Motivation

Beneficial because when others look at a profile, they want to easily see how much attention the posts are getting. 
If they look under the post and see no activity, they will think the page is not busy.

Pages look more attractive to others when they see activity under the posts

**Comment by trwnh** [comment] 2024-03-02 08:48
Duplicate of #23058

**Closed by trwnh** 2024-03-02 08:48 UTC
Labels: suggestion
