### ISSUE TITLE
Not all images of Pixelfed account are showing when viewed from a mastodon instance

### ISSUE THREAD

**Issue by PCPandaStyle** [mastodon/mastodon#18939] opened 2022-08-06 12:18 UTC
### Steps to reproduce the problem

1. Look at a pixelfed account from inside a mastodon instance (for example @Laszlo@pixelfed.social or @marcelo@pixelfed.social)
2. Compare the images shown inside each instance

### Expected behaviour

In Mastodon all of the images inside a Pixelfed account should be visible

### Actual behaviour

The result was very inconsistent, in some cases most images were missing, sometimes only some images were missing, sometimes I did not see any images missing at all.

### Specifications

The instance that I encouraged this bug in was running mastodon v3.5.3
pixelfed.social runs pixelfed v0.11.3

**Comment by Tslmuun** [comment] 2022-08-06 12:29
This is not a bug.  Mastodon has a size limit for uploading media files.  If you are admin, you can change the limit.
![Screenshot_20220806-202457](https://user-images.githubusercontent.com/50679343/183249009-f3a00ccd-feb2-40f4-a534-3c689b62fe19.png)

**Comment by PCPandaStyle** [comment] 2022-08-06 12:43
But pixelfed already compresses the images heavily, the maximum image size is 1080 x something, I think 1920.
I also just compared it, one of the images that is shown is almost twice the file size as one that isn't shown.

and this one was not shown, uploaded before one that was shown and only half the file size as well.
![2022-08-06-144029](https://user-images.githubusercontent.com/81259139/183249352-99cb7af2-ccaf-4666-a6f8-89f2cce344a4.png)
![2022-08-06-144038](https://user-images.githubusercontent.com/81259139/183249354-50036001-0e4a-4a75-a518-a4f119b0a297.png)

**Comment by ClearlyClaire** [comment] 2022-08-19 07:56
Do you have a link to a specific PixelFed post that does show as expected?

**Comment by PCPandaStyle** [comment] 2022-08-19 08:04
any Pixelfed post that shows on Mastodon, for example https://pixelfed.social/p/Laszlo/466115334682325379

**Comment by ClearlyClaire** [comment] 2022-08-19 08:11
Oops, sorry, I meant “does **not** show as expected”.

**Comment by PCPandaStyle** [comment] 2022-08-19 08:17
https://pixelfed.social/i/web/post/463036907806068274

**Comment by ClearlyClaire** [comment] 2022-08-19 08:19
Hm, I seem to have no issue displaying this in Mastodon.

**Comment by PCPandaStyle** [comment] 2022-08-19 08:29
yes, if you enter that link in mastodon then the post will be loaded, and from that point on it will be known to the mastodon instance.
Another thing to consider is that it seems to depend on the mastodon instance, how severe this issue shows.
If you look at an account, for example that @jj808@pixelfed.social, once on pixelfed and once through mastodon, will it show the same posts for you?

**Comment by ClearlyClaire** [comment] 2022-08-19 08:42
Alright, I misunderstood your issue then! I thought it was Mastodon failing to properly process some PixelFed posts, but it's your instance not having the full view of a remote account. This is not specific to federation with PixelFed and can occur with any fediverse implementation, including between two Mastodon instances.

Unfortunately, this is tricky to do in an efficient way, and also to avoid the issue of federating deletes more complicated than it currently is.

Closed in favor of #34

**Closed by ClearlyClaire** 2022-08-19 08:42 UTC
Labels: bug
