### ISSUE TITLE
Followed toots that federated to my instance didn't appear in my home timeline

### ISSUE THREAD

**Issue by wolfteeth** [mastodon/mastodon#2614] opened 2017-04-29 06:38 UTC
Different from #2613, though they sound superficially similar. Another case of missing toots.

I follow two remote users who were engaged in a public conversation, but some of the toots didn't appear in my home timeline. I got a very confusing partial view of the discussion until I clicked over into the thread view.

In this case the remote toots had successfully federated to my instance. I saw them when I clicked one of the replies and went into the thread view. Both users' local profiles also had the complete list of toots, but some didn't appear in my home timeline.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by neoranger** [comment] 2017-05-04 13:34
I have the same problem in my instance mastodonar.club. I am using the v1.3.2 tag.

**Comment by borisulianov** [comment] 2017-05-04 13:34
Hi! I'm using Mastodon at mastodonar.club and I can confirm this behaviour (I've already checked with other users on my instance, and some of them are experiencing this issue too).

**Comment by trwnh** [comment] 2023-05-13 23:42
closing this issue because it was last reported on v1.3.2 -- if it is still happening, please file a new issue

**Closed by trwnh** 2023-05-13 23:42 UTC
Labels: bug
