### ISSUE TITLE
Moderation support tools: "most blocked" lists

### ISSUE THREAD

**Issue by fpiesche** [mastodon/mastodon#5676] opened 2017-11-13 17:22 UTC
To make proactive moderation easier, might it be worth having an admin-/moderator-visible list of accounts/instances that have been blocked or muted by multiple local users (with a configurable threshold, to accommodate differing instance sizes)?

This would allow mods and admins to spot recurring misbehaviour from specific users or instances so they can proactively investigate if moderator-level action or community discussion might be appropriate **before** an issue becomes serious enough for users to draw their attention to it.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by fpiesche** [comment] 2017-11-13 17:30
The potential for abuse for such a feature seems relatively low to me (though I'm wondering if this might be abusable by malicious admins to guide harassment?). Input from others on whether this is a terrible idea would be much appreciated.

**Comment by nightpool** [comment] 2017-11-13 17:33
Oooh, yeah, this seems like a good idea

**Comment by wxcafe** [comment] 2017-11-19 12:06
👍

**Comment by Cassolotl** [comment] 2017-11-19 13:17
It might be useful if the feature also showed how many people on the local instance *follow* each most-blocked-person/instance too?

**Comment by your-friend-alice** [comment] 2019-12-25 07:15
the block and report buttons have very distinct, separate purposes, and blurring the line between them would be a betrayal of user trust. blocking as a separate operation from reporting is implicitly a private action, as such it's inappropriate for a moderator to view them, especially in aggregated form.

if blocking a user increases the chances of them being subject to scrutiny by a moderator, then blocking becomes a punitive action. this undermines one of blocking's core functions: a forceful, last-ditch tool for de-escalating conflict. i've blocked people i care about who i absolutely don't want to harm. and there's plenty of other non-reportable reasons to block a user. maybe you just don't like someone's posts, maybe somebody vents about issues in their life that happen to be a trigger for you (in which case, the last thing you want to do is risk jeopardizing their access to community!), maybe you're in the midst of a wave of harassment and you're blocking anyone who sends you a follow request, maybe you're just a really private person and you block anyone who interacts with you other than close friends. the reasons abound. making the block button punitive directly hurts its usability.

if a user blocks someone without reporting, that was their choice. if you believe users are not reporting reportable content, that's a UI, policy, or user trust issue, and has to be addressed at the root, rather than substituting report data for some heuristic based on private user data that wasn't meant for that purpose.

**Comment by trwnh** [comment] 2023-01-28 20:00
duplicate of #3139

**Closed** 2023-05-20 19:57 UTC
Labels: moderation, suggestion
