### ISSUE TITLE
Incorrect reply count "0" when toot has replies

### ISSUE THREAD

**Issue by parkingmeter** [mastodon/mastodon#29336] opened 2024-02-21 16:50 UTC
### Steps to reproduce the problem

1. Have upgraded to Mastodon 4.2.7
2. Have followed an account
3. Followed count Toots and has replies
4. See Toot in Home feed with 0 count reply
5. Select Toot and see multiple replies

### Expected behaviour

Reply count should match the current number of replies

### Actual behaviour

Reply count shows 0 

### Detailed description

Only noticed in Mastodon version 4.2.7, home feed of Toots are incorrectly showing a 0 reply count. Not all Toot's are affected, some Toots show the correct reply count, including local Toots. 

Example Toot showing 0 replies:
![Mastodon-no-reply-count](https://github.com/mastodon/mastodon/assets/4755594/909398d9-c8e8-4c70-99d1-6eb1a2b18fa5)

Same Toot showing the replies:
![Mastodon-toot-replies](https://github.com/mastodon/mastodon/assets/4755594/7ff311b6-d8f9-425f-9ad2-2b9b09e8ee9f)

### Mastodon instance

https://mastodon.parkingmeter.info/

### Mastodon version

v4.2.7

### Browser name and version

Brave v1.62.165

### Operating system

Arch Linux kernel version 6.7.4-arch1-1

### Technical details

I was unable to find any errors or related logs on my server relating to this issue.

**Comment by trwnh** [comment] 2024-11-23 09:05
Duplicate of #8324

**Closed by trwnh** 2024-11-23 09:05 UTC
Labels: area/web interface
