### ISSUE TITLE
admin moderation option to forward report to other instances following yours ("forward to downstream instances")

### ISSUE THREAD

**Issue by unusualevent** [mastodon/mastodon#29345] opened 2024-02-22 11:10 UTC
### Pitch

Only for particularly bad cases (and not done by users) - the moderators should have the ability to easily forward a mod report to instances whose inboxes subscribe to that server.

Such reports should go in a different bulk tab in the mod UI, and can be used to preemptively deal with forwarded reports.

### Motivation

Different from the other feature request I made for "forward reports to mentioned instances" as a user option. This is moreso a directly-following report sharing inbox.

It should not be auto-cascading and requires mod input at each stage to decide whether to forward the report, act on it, or mute the instance from forwarding-to-downstream

**Comment by unusualevent** [comment] 2024-02-22 11:12
e.g.,

small instance follows big instance with fast mod team

or under-staffed instance follows an account on an instance with a very active mod team

small instance reaps benefit of community report submissions.

**Comment by trwnh** [comment] 2024-02-23 14:14
Duplicate of #11510

**Closed by trwnh** 2024-02-23 14:14 UTC
Labels: suggestion
