### ISSUE TITLE
Docker: `latest` tag is pointing to last built image, not latest published stable version

### ISSUE THREAD

**Issue by y8** [mastodon/mastodon#25766] opened 2023-07-06 15:03 UTC
As far I understand currently new docker images are being built and pushed to hub.docker.com. 

But it seems like `latest` tag is being updated for each built version, leading to situation when it actually points to wrong version 

On this screenshot you can see that `latest` tag currently points to `v3.5.9`

<img width="1247" alt="image" src="https://github.com/mastodon/mastodon/assets/80930/cb6b0fdb-1972-4156-9599-8878036e3fe7">

Consequentially, if someone tries to pull `latest` tag right now, they will effectively downgrade their instance. 

### Expected behaviour

`latest` tag points to latest published release (v4.1.2, at this moment)

### Actual behaviour

`latest` tag points to older release branch (v3.5.9)

**Comment by renchap** [comment] 2023-07-06 16:17
Closing as duplicate of #25765

**Closed by renchap** 2023-07-06 16:17 UTC
Labels: bug
