### ISSUE TITLE
Instance mode that is just a static website of the whole instance

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#19223] opened 2022-09-23 15:19 UTC
### Pitch

Inspired by [this post](https://lethargic.talkative.fish/@suricrasia/statuses/01GDM4QB2KWYRD14XZZR4EYEXQ):

>"someone should make some software that reads a mastodon database and creates a static HTML archive of all the posts with all the right URLs, so that if someone doesn't want to host an instance anymore, they can convert it to a static version and host it cheaply"

### Motivation

Having a way to archive instances when you're shutting them down would preserve lots of valuable stuff and keep it accessible, but at a lower cost.

**Comment by trwnh** [comment] 2022-09-23 22:26
probably ease of writing such a function. it could be a tootctl command that cold caches everything or just exports it to a "public" folder

**Comment by nemobis** [comment] 2022-11-25 15:36
> I think you can do this [with just wget](https://www.linuxjournal.com/content/downloading-entire-web-site-wget).

Definitely not in Mastodon v4 web UI, which removed all server-side rendering.

**Comment by trwnh** [comment] 2023-05-16 04:55
Duplicate of #17596

**Closed by trwnh** 2023-05-16 04:55 UTC
Labels: suggestion
