### ISSUE TITLE
Ranked choice polls

### ISSUE THREAD

**Issue by starcrashr** [mastodon/mastodon#20519] opened 2022-11-12 19:46 UTC
### Pitch

Ranked choice options for polls.

### Motivation

I would like to use Mastodon for organizing, but the lack of ranked choice voting would require me to facilitate union elections with other tools.

**Comment by kolgza** [comment] 2022-11-13 16:31
If you click on the radio button when create a poll, you can switch to [approval voting](https://en.wikipedia.org/wiki/Approval_voting).
![image](https://user-images.githubusercontent.com/46303203/201532702-6ed9d15d-4038-43e5-b0ea-c2fb5f8fc1ee.png)

**Comment by starcrashr** [comment] 2022-11-13 16:41
> If you click on the radio button when create a poll, you can switch to [approval voting](https://en.wikipedia.org/wiki/Approval_voting). ![image](https://user-images.githubusercontent.com/46303203/201532702-6ed9d15d-4038-43e5-b0ea-c2fb5f8fc1ee.png)

That's not ranked choice.

**Comment by FedericoCeratto** [comment] 2022-11-28 17:01
Mastodon might not be the right platform for complex voting, but if there's interest I would suggest https://www.debian.org/vote/ and https://en.wikipedia.org/wiki/Condorcet_method to get meaningful and fair results.

**Comment by JorgeStolfi** [comment] 2023-01-29 14:57
Please see #23295.

**Comment by mjankowski** [comment] 2024-11-27 21:28
Doing some issue triage ... I'm going to close this as a dupe of the linked issue, which captures a bunch of in my opinion great ideas about improving polls. No idea how likely any of them are, but RCV would be cool.

To anyone every building this -- the people who "voted" (ordered a list) in an RCV poll should be able to in some way publish/promote/link-to their specific ranking of the thing in question.

**Closed by mjankowski** 2024-11-27 21:28 UTC
