### ISSUE TITLE
Feature Request: notification about all new toots

### ISSUE THREAD

**Issue by rpallai** [mastodon/mastodon#6437] opened 2018-02-06 21:46 UTC
This is not what a regular user wants by default, but could be useful in a few cases. For example, one can create a secondary account with this feature enabled to follow the loved (and not too chatty) ones to be well-informed.

You can see this request as a variant of #4890 but it's more generic. On the other hand a bit hackish to maintain a secondary account, but it's not so rare even on Twitter IMO. This feature could be a good temporary solution until a very (or over-)sophisticated notification system will come to reality.

(By the way the official Twitter app also supports this.)

**Comment by trwnh** [comment] 2023-05-14 00:16
assuming this is a duplicate of #4890; if the "subscribe to all posts" feature ("the bell") doesn't address your request, please comment here so that the issue can be reopened (and please clarify why not)

**Closed by trwnh** 2023-05-14 00:16 UTC
Labels: suggestion
