### ISSUE TITLE
Add to list without following

### ISSUE THREAD

**Issue by sparr** [mastodon/mastodon#21680] opened 2022-11-26 17:02 UTC
### Pitch

Allow adding someone to a List without Following them.

### Motivation

I want to have lists of news sources and niche content producers, but I don't want them in my Home feed or to wade through them when I'm managing my Follows. I would like to add an account (or hashtag, or instance, if those features ever land) to a list without following it.

This would indirectly resolve #19865 and similar requests related to lists and unapproved follows.

PS: Twitter apparently allows this.

**Comment by Cassolotl** [comment] 2022-11-26 18:45
This is a duplicate of *Feature request - add accounts to list without following them #6982* (March 2018), I think?

**Closed** 2022-11-26 22:21 UTC
Labels: suggestion
