### ISSUE TITLE
Allow users to directly transfer their posts and DMs from one instance to another [GDPR]

### ISSUE THREAD

**Issue by CONIGUERO** [mastodon/mastodon#23522] opened 2023-02-11 03:00 UTC
### Pitch

Currently Mastodon doesn't support exporting and importing of posts and DMs from one instance to another.

This should change as soon as possible due to legal reasons related to GDPR. Users should be able to both manually export/import those types of data and be able to directly trigger a transfer of such data from one instance to another in which they want to migrate.

### Motivation

Aside from convenience, this is a legal requirement under GDPR.

Art. 20:

1. The data subject shall have the right to receive the personal data concerning him or her, which he or she has provided to a controller, in a structured, commonly used and machine-readable format and have the right to transmit those data to another controller without hindrance from the controller to which the personal data have been provided[...]

2. In exercising his or her right to data portability pursuant to paragraph 1, the data subject shall have the right to **have the personal data transmitted directly from one controller to another**, where technically feasible.

**Comment by Cassolotl** [comment] 2023-02-11 10:38
This is a duplicate of *Support Post Migration #12423* (2019), but your GDPR quotes are really good and relevant and (for me at least) compelling, so I think copying them over to that discussion would be really valuable.

**Closed** 2023-05-19 06:14 UTC
Labels: suggestion
