### ISSUE TITLE
Toots beginning with a mention doesn't only show to followers of both parties.

### ISSUE THREAD

**Issue by WatchMeNow** [mastodon/mastodon#28783] opened 2024-01-17 16:15 UTC
### Steps to reproduce the problem

1. Initiate a conversation with another account. E.g. X writes a new toot, starts with mentioning Y.
2. Using an account Z that only follow X: View the home timeline.

### Expected behaviour

The toot should have been treated as a reply, e.g. Z should not see what X posts to Y in Z's home feed

### Actual behaviour

Z can see the initiation of X and Y's conversation.

### Detailed description

When X is starting a conversation the expectation is that only people in overlapping follower circles should be able to see it in the same manner as a reply to someone instead of it being a very public post.
Not to mention it's a privacy issue to see the start of conversations I'm not intended to be a part of or know about show up in the timeline even though they're publicly posted (similar to sitting in a café and a loudspeaker blaring out your first words to your friends). 
(Also very annoying when there's a new bot service people are signing up for via mentioning it - I know _way_ too much about which rss feeds my mutuals follow via rss-parrot.)

Added it as a bug instead of a suggestion as it's running counter-intuitive to standard UX.

### Mastodon instance

mastodon.social

### Mastodon version

v4.1.2

### Browser name and version

FireFox 121

### Operating system

windows 11

**Comment by trwnh** [comment] 2024-01-17 21:33
Duplicate of #8311

Essentially, there is a difference between a mention and a reply. If you start with a mention as in `@foo is a cool person!` then this is not a reply, and it will be shown to followers even if they don't follow `foo`.

For historical context, Twitter used to hide tweets starting with a mention, necessitating a dot-at `.@` if you wanted to avoid this behavior. But this was only necessary as long as Twitter hid tweets starting with mentions. Twitter eventually stopped doing this.

**Closed by trwnh** 2024-01-17 21:33 UTC
Labels: bug, status/to triage, area/web interface

**Comment by WatchMeNow** [comment] 2024-01-23 21:38
Sorry for the duplicate, searched a bit before I posted, but didn't find it.

Point still stands, though: people _do not_ expect this behavior, and are not aware of the proposed workaround (setting to followers only, which afaik puts it in your silo of followers, not your common followers, which in turn is used as a harassment tactic). 
The .@ is a more clear way to show that "this mention isn't mainly aimed at the person I'm mentioning, but to my whole audience".

For historical context: Twitter's .@'s (e.g. mastodon's first-@'s) were also used as a call for pile-on by the same people who used QT's as a harassment tactic.
