### ISSUE TITLE
Host multiple domains on a single instance

### ISSUE THREAD

**Issue by steelman** [mastodon/mastodon#20486] opened 2022-11-12 10:58 UTC
### Pitch

Disclaimer: I haven't set up an instance myself and I haven't made any performance measurements and I am just guessing based on some general experience.

Enable hosting multiple domains on withe single instance of Mastodon just like it is possible to host multiple e-mail domains with a properly configured single stack of software.

### Motivation

Advantages:

Single instance serving multiple domains is easier to maintain than multiple instances each serving one domain. It also may be more efficient resourcewise. This MAY encourage hosting companies to offer managed Mastodon hosting at lower price to people wishing to have their own domain but incapable of: paying for a VPS, managing an instance themselves.

To use such managed Mastodon service DNS domain owners would have to point to their provider IP addresses. 

(BTW but probably out of scope of this issue is sever discovery beyond A or AAAA DNS records. Matrix has a flexible [server discovery protocol](https://spec.matrix.org/v1.4/server-server-api/#server-discovery))

Risks: bugs may result in leaking data between domains. As much as this is definitely unwanted, public nature of Mastodon makes impact of such problems somewhat less severe IMHO.

**Comment by ineffyble** [comment] 2022-11-12 11:38
Duplicate of #2668

**Closed by ineffyble** 2022-11-12 11:38 UTC
Labels: suggestion
