### ISSUE TITLE
How can i add 2k words in filters?

### ISSUE THREAD

**Issue by geekytricky** [mastodon/mastodon#29374] opened 2024-02-23 12:26 UTC
### Pitch

1: I want to add 2000 swear words in filters. but i cannot able to add these words in single attempt.. i do not want to these words one by one. this process will take long time..
2: Cannot backup these Filter presets and migrate to another instance.
please fix it...

### Motivation

try to add 2k words in filters one by one. it will take 3-4 hours

**Comment by trwnh** [comment] 2024-02-23 14:12
Duplicate of #9177

**Closed by trwnh** 2024-02-23 14:12 UTC
Labels: suggestion
