### ISSUE TITLE
Migration notification `@bob@m.s has moved to @bob@m.o`

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#26771] opened 2023-09-02 11:33 UTC
### Pitch

I'd like to see a migration notifications to make people more aware of movement... the auto follow feature is great, but I'd like to become aware of the move.

`@bob@m.s has moved to @bob@m.o`

### Motivation

Quality of life improvement.

**Comment by trwnh** [comment] 2023-09-03 12:33
Duplicate of #23250

**Closed by trwnh** 2023-09-03 12:33 UTC
Labels: suggestion
