### ISSUE TITLE
Multiuser Setup for Institutional Accounts

### ISSUE THREAD

**Issue by cmeesters** [mastodon/mastodon#33048] opened 2024-11-23 16:09 UTC
### Pitch

Hi,

Whilst setting up an Open Science Community Account on our instance (fediscience.org) we realized that only one email password combination could be stored for that account. This requires to a) get a functional mail account to share and b) a password to share. This is ... suboptimal.

I would suggest allowing access for multiple users to one account. A single person could set up the account and allow others to toot and boost. Said person should also be able to withdraw such rights. To prevent loosing access to such a Mastodon account, it should be allowed to promote several mail accounts to be privileged. 

This still leaves one person to initiate the account and distribute passwords. Hence, all account bearers should be able to set up or be required to use 2FA authentication to avoid abuse of multiuser accounts.

### Motivation

Any institutional account (for press releases (e.g. universities, political institutions), community accounts (e.g. sport clubs)). There are no more shared secrets and maintenance of such accounts would be simpler.

**Comment by vmstan** [comment] 2024-11-23 23:40
Duplicate of #15896

**Closed by vmstan** 2024-11-23 23:40 UTC
