### ISSUE TITLE
[Feature] Backfill feed on startup

### ISSUE THREAD

**Issue by ted-gould** [mastodon/mastodon#6288] opened 2018-01-18 14:53 UTC
New Mastodon user and I started out finding people and following them. What surprised me is that this kept my feed still really empty. I realize now that Mastodon focuses on getting updates and then filling up as people post. I think that it'd be an improvement if, on first seeing an account, would grab something like the last 10 posts and start filling up the home feed. It would make Mastodon feel more active quickly.

**Comment by Gargron** [comment] 2018-01-18 15:07
This absolutely does happen in the background (see MergeWorker)

**Comment by ted-gould** [comment] 2018-01-18 16:14
I haven't looked at the source, speaking completely from an experience perspective. It might be because my server was new as well. But, starting out, it felt pretty lonely.

Perhaps what I'm requesting is to run the MergeWorker on a higher frequency update when starting a new instance or account.

**Comment by trwnh** [comment] 2023-05-14 00:09
Duplicate of #34

**Closed by trwnh** 2023-05-14 00:09 UTC
Labels: suggestion
