### ISSUE TITLE
Please change limited federation instance going to /about

### ISSUE THREAD

**Issue by gaditano66** [mastodon/mastodon#22504] opened 2022-12-19 16:52 UTC
### Steps to reproduce the problem

1. You install a mastodon instance and change it to limited federation
2. The homepage goes to /about and gives many errors in information of the instance and 401 errors
3. It should go only to /auth/sign_in when you visit the homepage and then all normal once logged in
4. Installing an instance now is not good at all, we are missing an instance without errors if we choose a limited federation instance
...

### Expected behaviour

It should work fine without errors

### Actual behaviour

Horrible UI with errors and problems in the instance information

### Detailed description

Please,
in previous versions we could go to some private route in /auth/sign_in and all was working great.
In new versions we can't install an instance and see what's happening now going to /about, it's horrible.
Please fix it.
Thank you

### Specifications

Mastodon 4.0.2
Limited federation

**Comment by gaditano66** [comment] 2022-12-19 17:00
Or please tell me what can I do to: 
- avoid these errors
- go to auth/sign_in when I visit the homepage and then going to /home and all ok
- fix the errors when going to /about as it is now

**Comment by gaditano66** [comment] 2022-12-21 10:52
I see that there is no one interested in correcting this serious problem when someone wants an instance with limited federation. Is it because they don't get the same support when it is not with federation?

**Comment by vmstan** [comment] 2024-01-01 19:02
Closed as duplicate of #20777

**Closed by vmstan** 2024-01-01 19:02 UTC
Labels: bug
