### ISSUE TITLE
Hide List Member from Home Feed

### ISSUE THREAD

**Issue by jaredzimmerman** [mastodon/mastodon#22629] opened 2022-12-21 19:44 UTC
### Pitch

Similar to the functionality of "hide boosts" I'd like for followed accounts and entire lists to be able to be configured to "Hide from Home timeline" 

### Motivation

so  I can follow some more high volume publisher/automated accounts but not see them clutter my Home feed.

**Comment by ClearlyClaire** [comment] 2022-12-22 08:44
Duplicate of #16556

**Closed by ClearlyClaire** 2022-12-22 08:44 UTC
Labels: suggestion
