### ISSUE TITLE
New Setting request for when Posting - Ability to set 'Comments Disabled'

### ISSUE THREAD

**Issue by PeterG77777** [mastodon/mastodon#30095] opened 2024-04-28 05:55 UTC
### Pitch

It would be handy to be able to post with comments disabled sometimes, like in instances where you post a news article but don't want comment wars in the comment section. You Tube has the ability, Facebook groups and pages also have the ability, it's very useful when providing an article or news item link where you don't want any nasty comments from anyone who happens to not like or agree with the news item.

### Motivation

Many social media platforms use this same feature, it works well in curbing nastiness and abuse, and provides people who often share news articles safety against backlash and nasty comments.

**Comment by renchap** [comment] 2024-04-28 11:10
Duplicate of #8565

**Closed by renchap** 2024-04-28 11:10 UTC
Labels: suggestion
