### ISSUE TITLE
[web app] Remove left-side column, and post/reply in situ?

### ISSUE THREAD

**Issue by Shohreh** [mastodon/mastodon#21480] opened 2022-11-23 14:20 UTC
### Pitch

Hello,

Is there a way to remove the left-side column, so that new posts/replies are done through the column where threads are displayed?

Thank you.

![image](https://user-images.githubusercontent.com/1541861/203569681-3f1ee61c-0672-4289-b545-127e07f35117.png)

### Motivation

Easier UI, would work like Twitter

**Comment by trwnh** [comment] 2022-11-23 14:24
Duplicate of #13311

**Comment by nuclearfall** [comment] 2022-11-23 17:03
I think the intent is to allow a person to be able to see what they're responding to, while still only having a single text entry, to avoid having to keep track of state of boxes and what from where is going to whom. But I could be way off.

**Closed** 2023-05-19 06:37 UTC
Labels: suggestion
