### ISSUE TITLE
Consider: Switching to ActiveStorage from Paperclip

### ISSUE THREAD

**Issue by matthewford** [mastodon/mastodon#20270] opened 2022-11-09 20:35 UTC
### Pitch

Paperclip has been deprecated https://thoughtbot.com/blog/closing-the-trombone, and while there are efforts to maintain it via kt-paperclip, it would make sense to switch to ActiveStorage.

Doing so would make the switch to vips https://github.com/mastodon/mastodon/issues/20269 much simpler, as ActiveStorage uses https://github.com/janko/image_processing which supports both ImageMagick and vips.

Some guides on how to switch:
https://gist.github.com/jmevans0211/b9abb28ed51b13a46df451e87c901767
https://www.fastruby.io/blog/upgrades/active-storage/gradually-migrate-from-paperclip.html

As ActiveStorage is part of Rails core it will be better supported by the community.

### Motivation

All servers.

**Comment by TheEssem** [comment] 2022-11-09 23:54
There's already an open issue for this at #7414, not much activity since 2018 however

**Comment by ClearlyClaire** [comment] 2022-11-10 10:41
This is indeed a duplicate of #7414.

**Closed by ClearlyClaire** 2022-11-10 10:41 UTC
Labels: suggestion
