### ISSUE TITLE
Clicking a post in a long thread highlights the post *before* the requested one

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#18312] opened 2022-05-04 17:34 UTC
### Steps to reproduce the problem

When I click a post in a long thread in the feed or user columns, it focuses the post *above* it in the thread in the right-hand column. If the post before it is long, this results in the post I want being scrolled so far down it is nearly or entirely unreadable.

![ee96ea2ece2c3a48](https://user-images.githubusercontent.com/277318/166743929-86968101-31b8-498d-a2c8-3f80873c0221.png)

Repro: Go to [my profile](https://mastodon.social/@mcc) and scroll down a bit looking for a post starting with "What I'm listening to today). Every day for the last week I've been posting these. The thread is now quite long, every individual post is long, and every individual post has an attachment. Click the first "What I'm listening to today" you see and it should highlight it in the right column.

I do not see this problem when the post and the post before it are both short (example: [this post](https://mastodon.social/@aeva/108244797669966341), I saved and can post a screenshot of clicking that post if you like). With short posts, it shows the highlighted post off-center in an appealing way that shows the reply context of the post. I think with the long thread, either it's trying "too hard" to show context (it should not be showing context *at the expense of* the post I asked it to highlight); or it's trying to show the highlighted post centered in the column but either the length of the posts or the many attachments in the thread are tripping up the centering calculation.

### Expected behaviour

The post I wanted to look at should have been centered and as much as the post as can fit on the screen should be visible.

### Actual behaviour

The post I wanted to look at is mostly or entirely non-visible. This makes me feel confused :(

### Specifications

I am using the "original" not simplified interface. I am using Chrome 100.0.4896.127, Windows 10 Version 21H1 (Build 19043.1645), I normally have the uBlock Origin extension version 1.42.4 enabled but turning it off does not change this behavior. I view the site at 125% magnification because my eyesight is bad, which probably exacerbates the problem (by making the window effectively less tall).

I saw this on mastodon.social, but the problem does **not** replicate on all instances. I made a [post on Mastodon](https://mastodon.social/web/@mcc/108240059340531969) about this problem and multiple users using the "Glitch variant" of Mastodon (for example Kat Marchan, using version":"3.2.0+glitch" on toot.cat, replies with a screenshot of my test thread in [this post](https://mastodon.social/web/@zkat@toot.cat/108240148542200843)) reported they did not see the problem. I did not hear from anyone else on mastodon.social either confirming or denying they can reproduce the problem.

**Comment by ClearlyClaire** [comment] 2022-05-04 19:46
I can reproduce it, both in vanilla Mastodon and glitch-soc. It doesn't always occur exactly in the same way. I suspect this may be caused by the preview cards resizing after initial display and scroll, or some of the scroll-to-account-for-new-posts code going wrong.

There is an adjacent bug where clicking a second time on the exact same post will scroll to the top, but I currently have no idea why that would occur.

**Comment by ClearlyClaire** [comment] 2023-04-26 21:11
> There is an adjacent bug where clicking a second time on the exact same post will scroll to the top, but I currently have no idea why that would occur.

That adjacent bug has been addressed in #21797.

> I suspect this may be caused by the preview cards resizing after initial display and scroll

Upon examining closer, I still think this is the issue: the post is scrolled into view before the preview cards are displayed, so both the post's height (because it has a preview card) and its scroll offset (because visible ancestors have preview cards) change after it is scrolled into view. I am unsure how to handle that.

**Closed** 2023-07-21 11:14 UTC
Labels: bug
