### ISSUE TITLE
ability to follow other instances local feed. 

### ISSUE THREAD

**Issue by jakubiszon26** [mastodon/mastodon#18692] opened 2022-06-19 07:57 UTC
### Pitch

An option to search for specific instance and being able to follow it's feed and view it in either your local feed or dedicated page

### Motivation

That would make it easier to follow whole communities and in general would deliver more content to the user.

**Comment by umrath** [comment] 2022-08-01 05:30
This is especially useful for small instances where the local feed is pretty much useless.

**Comment by RiverMoot** [comment] 2022-10-30 00:36
This is like- my ONE problem with the platform so far, having gotten into it today. I don't wanna have to make an account for every instance I like. T_ T

**Comment by Gargron** [comment] 2022-10-30 00:42
Hopefully the upcoming groups feature will address the root cause of this feature request.

**Comment by akien-mga** [comment] 2022-10-30 10:40
This seems to be a duplicate of https://github.com/mastodon/mastodon/issues/6942

Great to see it being worked on!

**Comment by robkam** [comment] 2022-11-07 20:23
The Qoto instance does this ([repository here](https://git.qoto.org/qoto/qoto)):

- Domain Subscriptions - Bring another instance's local timeline as a feed in Qoto, no need to have an account on another server again, just import their timeline here!
- Favorite Domains - Our last release allowed us to add remote timeline as a feature where you could pull up the local timeline of a remote instance as its own column. Now you can also add domains to a favorite domain list which makes it easier to access and bring up the timelines by listing them directly in the navigation panel.

**Closed** 2023-05-19 06:56 UTC
Labels: suggestion
