### ISSUE TITLE
Add confirmation check before posting image with no alt text

### ISSUE THREAD

**Issue by Daenyth** [mastodon/mastodon#24148] opened 2023-03-17 15:57 UTC
### Pitch

Sometimes when I post images, I forget to post alt text, because it's an "extra" part of the workflow of adding an image.

I would like to have a configuration option that warns me when I'm about to post an image without alt text, so that I have to intentionally choose it, rather than do it by accident.

I'd be happy if the *default* was "warn" but even if it's something I need to enable, I'd be happy with it

### Motivation

This would benefit everyone who uses alt text on images, and also people who write alt text for images they post

**Comment by hypermug1** [comment] 2023-03-17 18:00
This has already been suggested numerous times

**Comment by Daenyth** [comment] 2023-03-18 14:47
Ah, I tried searching issues for it but I didn't find it. Feel free to close this as a duplicate if there's a better ticket

**Comment by Deuchnord** [comment] 2023-03-22 10:40
An implementation has been proosed in #21679 but the PR seems to be stale. I hope it will get merged soon

**Comment by trwnh** [comment] 2023-05-19 06:04
Duplicate of #7804

**Closed by trwnh** 2023-05-19 06:04 UTC
Labels: suggestion
