### ISSUE TITLE
Able to add accounts of others, those not followed, to some my account list(-s)

### ISSUE THREAD

**Issue by kj45o** [mastodon/mastodon#20560] opened 2022-11-13 12:14 UTC
### Pitch

Implement support to add users not followed by my account to list defined same account.

Same request regarding hashtags.

### Motivation

Several accounts of other Mastodon users are of my interest.
I am not going to follow them however I like to have them on some of my lists.
That's one major component of how me uses Twitter so far.

**Comment by trwnh** [comment] 2022-11-13 13:26
Duplicate of #6982

**Comment by kj45o** [comment] 2022-11-13 16:50
How soon can #6982 deliver its final results? I know this question changes nothing for this FR.

**Closed** 2022-11-15 10:04 UTC
Labels: suggestion
