### ISSUE TITLE
SVG Avatars

### ISSUE THREAD

**Issue by aveao** [mastodon/mastodon#9804] opened 2019-01-14 07:39 UTC
### Pitch

SVG images should be allowed for avatars.

They could be rendered on server-side at time of upload, at time of fetch or ideally, just be served as svgs. I am not familiar with the backend code on mastodon, so I can't give more detailed ideas, but it could be nice to serve both an avatar url (like always, for backwards compat) and a vector avatar url (if available, to be used by supporting clients).

### Motivation

~~[Stars!](https://elixi.re/i/32daocjf.png)~~

SVG vector images, compared to regular raster images, are small, infinitely-scalable and rather extensive.

Benefits for people setting SVG avatars: I know some artists who only make SVG art (such as @mstrodl). Such artists would benefit immensely from this, as it'd allow them to use their art directly without having to render it to a raster format first (which causes the benefits of SVG that I mentioned above to be lost).

Benefits for people viewing SVG avatars: Less data consumption, better scaling on all sizes of screens.

---

### Related Issues and PRs

#9283 

#9253

### Security Considerations

As with all other SVG related issues/PRs, this obviously has security considerations due to the aforementioned extensive nature of them (for example, they can run javascript by default).

Most of these issues can be defeated on client side by serving images with `'Content-Security-Policy': "sandbox; frame-src 'none'"` header set.

On server side, there's multiple approaches. I think the PR I linked above took a take at securing them on server-side, but I didn't check the details. Either way, it'd be possible to use a whitelist [such as this](https://stackoverflow.com/questions/4881364/sanitizing-an-svg-document-by-whitelisting-elements) for securing them (which is what gitlab does when rendering svgs).

**Comment by Mstrodl** [comment] 2019-01-14 11:53
It's also worth noting that svgs don't execute javascript unless it's inlined in html or embedded with an iframe, img elements won't run javascript

**Comment by Popolon** [comment] 2022-12-09 21:42
SVG also allow animation, that is already supported by main browser since few years. They don't need javaScript, static animate tag allow them. Here is an exemple.
![animated SVG](https://popolon.org/gblog3/wp-content/uploads/2021/10/Pinguin_v2.svg)

**Comment by trwnh** [comment] 2023-05-16 03:13
Duplicate of #6569

**Closed by trwnh** 2023-05-16 03:13 UTC
Labels: suggestion
