### ISSUE TITLE
Youtube Embedding has wrong link for popout

### ISSUE THREAD

**Issue by Anaerin** [mastodon/mastodon#25995] opened 2023-07-15 08:25 UTC
### Steps to reproduce the problem

1. Link a YouTube video
2. Click the right-hand icon of the two in the embed (to open the video in a new tab)

### Expected behaviour

The YouTube video opens in a new tab

### Actual behaviour

A new tab opens to https://www.google.com/sorry/index?continue=[videoURL]

### Detailed description

The embed works just fine for playing in-place, but this link appears to be broken for some reason.

### Specifications

Front-End issue, using current stable Mastodon PWA release, in Desktop Google Chrome (Also reported in FireFox, both Desktop and Mobile).

An example of this is here: https://kind.social/@Texan_Reverend/110717080960355266

**Comment by bmanuel** [comment] 2023-07-18 01:48
@Anaerin it seems like this may have been a YouTube issue. I am able to open that original link. Is that the case for you as well?

**Comment by Anaerin** [comment] 2023-07-18 02:45
In the embed in the example, the circled link (for opening in a new tab/window) goes to google.com/sorry not the video URL as expected. Every other function (the link itself, the play option, etc) work as expected.
![image](https://github.com/mastodon/mastodon/assets/989271/32610356-a68c-4fcd-b1c1-166259fc4950)

**Comment by c960657** [comment] 2023-07-23 17:30
I cannot reproduce this, but I think it is related to this code:
https://github.com/mastodon/mastodon/blob/5e8cbb5f82ab0df0de80539650a6e55d7cf7a3a5/app/services/fetch_link_card_service.rb#L52C1-L52C1

I seems Google sometimes redirects to the “sorry” page when requesting the original URL of the YouTube video. Note that the “sorry” page has HTTP status code _429 Too many requests_.

I think the problem can be fixed by moving the reassignment of `@url` inside the `if res.code == 200` block, so the original URL is not overwritten if it redirects to a page with a non-200 response.

**Closed** 2023-07-28 21:02 UTC
Labels: bug
