### ISSUE TITLE
Issue with options on a post.

### ISSUE THREAD

**Issue by AdenGames** [mastodon/mastodon#20084] opened 2022-11-08 00:04 UTC
### Steps to reproduce the problem

1. Click 3 dots on rc 2
2. Hover over or under pop up.
3. It moves away
...

### Expected behaviour

Stayed static

### Actual behaviour

Moved

### Detailed description

It moves when you hover near it.
I added a video so you can see what I mean.

### Specifications

v4.0.0rc2

https://user-images.githubusercontent.com/39639320/200441604-4677681f-2346-4e27-a44b-c29d96058add.mp4

**Comment by afontenot** [comment] 2022-11-08 00:12
Probably a dupe of https://github.com/mastodon/mastodon/issues/14266. I've been experiencing it too. 

I also started a discussion about it because I was surprised about how old the issue was, with no recent comments. https://github.com/mastodon/mastodon/discussions/20006

**Comment by ClearlyClaire** [comment] 2022-11-08 08:39
Definitely a duplicate of #14266, this occurs because the dropdown menu has a fixed position in the *document*, not relative to the post it was opened from, so when a new post comes in, it adds to the document, the interface scrolls down to compensate, and leaves the dropdown up.

**Closed by ClearlyClaire** 2022-11-08 08:39 UTC
Labels: bug
