### ISSUE TITLE
add ability for admins and users to filter out media without descriptions

### ISSUE THREAD

**Issue by devinprater** [mastodon/mastodon#17866] opened 2022-03-24 21:40 UTC
### Pitch

Currently, there is no way for instance admins or users to filter away media without descriptions. This means that, even if users cannot see media, or do not want to see media without descriptions, or if reading descriptions of media is easier for a user than watching it, they do not have this option.

### Motivation

This feature would help:

* Blind people, for whom seeing images without descriptions is an everyday slap in the face.
* Neurodivergent people, for some of whom images are harder to understand contextually than text descriptions.
* People who stand in solidarity with blind people, for whom this will be a reminder to describe their media and to remember those who don't have the privilege of being able to see.

**Comment by ryliejamesthomas** [comment] 2022-03-25 07:33
Would this filter-out the whole post? I see a problem with it unhelpfully filtering-out media whose descriptions are in the message they're attached to.

**Comment by devinprater** [comment] 2022-03-25 19:38
Yes, it would. And since the user enabled such a feature, they'd know that's what they're getting into.

**Comment by Cassolotl** [comment] 2022-04-27 21:36
I believe this may be a duplicate of *A filter to hide posts with images that do not have descriptions #11682*. If you think so too, please close this issue, and head to the older one to add a comment and/or a 👍. :)

**Closed** 2023-05-19 14:14 UTC
Labels: suggestion
