### ISSUE TITLE
reaction instead of favorite, just display emojis like discord does it

### ISSUE THREAD

**Issue by soloturn** [mastodon/mastodon#32952] opened 2024-11-18 03:53 UTC
### Steps to reproduce the problem

favorite is confusing, as it is used like bookmark in browsers. better would be to do it like in discord. just display the emojis. and call it "reaction" or so. offer like care sad etc.

### Expected behaviour

reaction is better name

### Actual behaviour

favorites, looks like my personal favorites, but poster does not notice it

### Mastodon instance

all

### Mastodon version

v4.3.0

### Browser name and version

all

### Operating system

all

**Comment by trwnh** [comment] 2024-11-18 06:18
Duplicate of #4106

**Closed by trwnh** 2024-11-18 06:18 UTC
Labels: status/to triage, area/web interface
