### ISSUE TITLE
thumbnails not loading

### ISSUE THREAD

**Issue by joeg2023** [mastodon/mastodon#26641] opened 2023-08-24 15:10 UTC
### Steps to reproduce the problem

Hi All,

im having an issue with Mastodon loading image thumbnails

they are black

https://1drv.ms/i/s!AmcG12ikC8S72X8TLFp-7F8MSBwG?e=UGi70U

however clicking on the image gives me the image

https://1drv.ms/i/s!AmcG12ikC8S72gA7j0Ux9eHS1wDy?e=qRBJYJ

it's driving me mad

can anyone help?

thanks for any help

chip

### Expected behaviour

thumbnail load

### Actual behaviour

thumbnails dont load, but clicking them shows the correct image 

### Mastodon instance

shock.zode.me

### Mastodon version

v3.5.3

### Browser name and version

Chrome 116.0.5845.110

### Operating system

Windows 10 22H2

### Technical details

none, i cant see anyhting interesting in the nginx error logs journalctl

**Comment by cadusilva** [comment] 2023-08-24 15:45
> Hi, i have just updated to V4.1.6 ... the issue is still there
> 
> thanks for your help

Maybe your problem is just `nginx` misconfigured. Your image links starts with `http://`, which points to elsewhere in your web server installation. When the same image link starts with `https://`, the image loads fine. Check your `nginx` configuration, set a redirect from HTTP to HTTPS and things should work as intended.

Your port `80` server block should be something like this:

```
server {
	listen 80;
	listen [::]:80;
	server_name shock.zode.me ;
	return 301 https://$host$request_uri;
}
```

Also check your CDN setup, if any, and `.env.production` file to see what's making your Mastodon installation generate links starting with `http://`.

**Comment by joeg2023** [comment] 2023-08-24 16:19
> > Hi, i have just updated to V4.1.6 ... the issue is still there
> > thanks for your help
> 
> Maybe your problem is just `nginx` misconfigured. Your image links starts with `http://`, which points to elsewhere in your web server installation. When the same image link starts with `https://`, the image loads fine. Check your `nginx` configuration, set a redirect from HTTP to HTTPS and things should work as intended.
> 
> Your port `80` server block should be something like this:
> 
> ```
> server {
> 	listen 80;
> 	listen [::]:80;
> 	server_name shock.zode.me ;
> 	return 301 https://$host$request_uri;
> }
> ```
> 
> Everything else must be in your port `443` server block. Check your `dist` folder inside your Mastodon installation for examples.
> 
> Also check your CDN setup, if any, and `.env.production` file to see what's making your Mastodon installation generate links starting with `http://`.

I LOVE YOU!... it's fixed, many thanks for your help! ... it's been driving me mad!

**Comment by joeg2023** [comment] 2023-08-24 16:21
for anybody else looking for a "cure" the issue was this

https://github.com/mastodon/mastodon/issues/23109

my minio instance is HTTP but it's proxied through nginx over HTTPS...  the S3 was set to http appending http://url breaking the thumbnail changing the S3 protocol to HTTPS fixes the issue

thanks

**Comment by renchap** [comment] 2023-08-24 21:47
Closing as this has been solved.

**Closed by renchap** 2023-08-24 21:47 UTC
Labels: bug, status/to triage, area/web interface
