### ISSUE TITLE
Clicking "Open original page" taking me to the link shared by the post instead of the post itself

### ISSUE THREAD

**Issue by ChristopherKing42** [mastodon/mastodon#22139] opened 2022-12-07 21:55 UTC
### Steps to reproduce the problem

1. Go to https://mathstodon.xyz/@yogthos@lemmy.ml/108856710929059105
2. Click "..." and then "Open original page"

### Expected behaviour

Takes me to the [original post](https://lemmy.ml/post/432194)

### Actual behaviour

Took me to the link shared by the post: https://x.st/visual-sum-of-cubes

### Detailed description

I think it is going to the "url" field instead of the "id" field of the message. It should go to the "id" field, right?

### Specifications

Mastodon v4.0.2
Chrome on Android

**Comment by ClearlyClaire** [comment] 2022-12-08 11:28
It sounds like a duplicate of #17003.

`url` is meant to represent the same object as `uri` in potentially different representations (e.g. HTML vs ActivityStreams), but apparently Lemmy is still using `url` to refer to the link the activity is talking about rather than the activity itself.

cc @Nutomic

**Comment by ChristopherKing42** [comment] 2022-12-08 16:20
Here's an example of what they're activity stream looks like: https://github.com/LemmyNet/lemmy/blob/main/crates/apub/assets/lemmy/objects/page.json

Maybe Mastodon and Lemmy are on different versions of ActivityPub?

**Comment by ChristopherKing42** [comment] 2022-12-08 19:34
It seems to affect comments for some reason too. The original page for https://mathstodon.xyz/@poVoq@slrpnk.net/109400425530365829 is https://slrpnk.net/comment/34196, which gives a 404 error.

**Comment by Nutomic** [comment] 2022-12-09 14:27
> url is meant to represent the same object as uri in potentially different representations (e.g. HTML vs ActivityStreams), but apparently Lemmy is still using url to refer to the link the activity is talking about rather than the activity itself.

Lemmy sends the `url` field for backwards compatibility with and older version. I wasnt aware that this caused problems for Mastodon. As that old Lemmy version is barely used anymore, we can remove the `url` field in 0.17.0 which will be released soon.

**Closed** 2023-05-19 06:33 UTC
Labels: bug
