### ISSUE TITLE
Links in preview are altered

### ISSUE THREAD

**Issue by timhutton** [mastodon/mastodon#18552] opened 2022-05-29 18:13 UTC
### Steps to reproduce the problem

I included this URL in [a toot](https://mathstodon.xyz/@timhutton/108386537832754044): https://github.com/gollygang/ruletablerepository/wiki/TheRules

The toot appeared with a preview that claimed to be about that page ("TheRules"):

![image](https://user-images.githubusercontent.com/647092/170885120-83668beb-7c27-4739-ba0d-dbb6a0a79df0.png)

but clicking on the preview takes you to: https://github.com/GollyGang/ruletablerepository

### Expected behaviour

Clicking the link preview should take you to the link.

### Actual behaviour

Clicking the link preview took me to a different link.

### Specifications

Mastodon v3.5.3, web interface accessing [the toot](https://mathstodon.xyz/@timhutton/108386537832754044) using Firefox 100.0.2, on Windows 10.

**Comment by connyduck** [comment] 2022-05-29 18:16
Duplicate of https://github.com/mastodon/mastodon/issues/18475 ?

**Comment by timhutton** [comment] 2022-05-29 18:25
Yes, duplicate of #18475

**Closed** 2022-05-29 18:26 UTC
Labels: bug
