### ISSUE TITLE
Allow following an instance rather than individual accounts

### ISSUE THREAD

**Issue by fasihrana** [mastodon/mastodon#22371] opened 2022-12-16 17:50 UTC
### Pitch

It would be very helpful if we could see posts from an instance without having to follow individual accounts. The same way you can subscribe to hashtags, you should be allowed to subscribe to the whole mastodon server.

### Motivation

This will be very useful where the mastodon server is hosted by a news organization and you could follow their whole server instead of following individual accounts.

There is already a server being hosted by a news organization, [Bylines](https://bylines.social/) in the UK, for their own accounts as a way for these accounts to be a verified source.

The idea came from this post on [mstdn.social](https://mstdn.social/@ACAElliott/109524389974013949).

**Comment by ineffyble** [comment] 2022-12-16 19:04
Duplicate of #6942

**Comment by ineffyble** [comment] 2022-12-16 19:05
Or possibly duplicate of #8082 is a better fit

**Closed by ineffyble** 2022-12-16 19:04 UTC
Labels: suggestion

**Comment by fasihrana** [comment] 2022-12-17 14:23
I don't believe those two issues are the same. This is talking about specifically allowing users to be able to subscribe to instances. The other issues are talking about admins allowed relays for instances. This issue is talking about having posts from other instances show up in your personal timeline rather than local or federated timelines.

This is fundamentally different than #6942 and #8082.

**Comment by fasihrana** [comment] 2022-12-17 14:25
#20995 is a better fit though and a better solution to I cater for variety of I threats.
