### ISSUE TITLE
Add "System default" theme option

### ISSUE THREAD

**Issue by rail01** [mastodon/mastodon#26359] opened 2023-08-06 09:25 UTC
### Pitch

Please add "System default" theme option, which upon choosing would detect browser's theme setting and based on that decide whether to display the app in Light or Dark theme.

### Motivation

That way, managing the theme wouldn't require manually changing settings every time. Most apps are able to automatically determine the system/browser theme and automatically apply a fitting theme based on that, unless a different option is chosen specifically by the user.

For me personally it is important because when I work with my laptop outdoors I prefer the light theme and most things automatically change to light when I change system theme with one toggle, but Mastodon isn't one of these things.

Having "System default" theme option would solve this sort-of accessibility need of mine.

**Comment by mcclure** [comment] 2023-08-06 15:33
I was interested to learn there's actually a w3 standard feature for this.

https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme
https://caniuse.com/?search=prefers-color-scheme

**Comment by ClearlyClaire** [comment] 2023-08-07 08:51
Hi! Thank you for your report, but this is a duplicate of #10976

**Closed by ClearlyClaire** 2023-08-07 08:51 UTC
Labels: suggestion
