### ISSUE TITLE
New status privacy option "Hashtag only" or "View by #"

### ISSUE THREAD

**Issue by bnejal** [mastodon/mastodon#6940] opened 2018-03-28 03:37 UTC
This would allow for nsfw blogs to post directly to only a personal timeline or within the context of a particular hashtag as a privacy option without creating additional search options or modifying the non-public privacy option. This particular privacy policy only blacklists local and fediverse timelines.

* * * *

- [✅ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by bnejal** [comment] 2018-03-29 01:15
Groups does sound good, but now that I think of it, it would just be better for users in the to able to create their own custom privacy options out of a special "custom privacy policy" panel in settings.  This would entirely remove the need of adding a new privacy option for whenever pre-existing privacy policies for each toot are insufficient for user needs and answers tons of potential use cases for users in one swoop. A few potential possibilities I could think of from the top of my head would be:
- The use case I stated above
- Making toots visible everywhere else but not fediverse
- making toots public but not searchable by hashtag 

And much more if we keep on thinking of toots as emails that head over to special public mailing lists, where we can specify where our toots can go

**Comment by trwnh** [comment] 2023-05-14 07:57
#1208 + #983 

i don't think this makes sense as a "privacy option", because hashtags aren't people and they can't see anything. #983 targets letting you choose your recipients, and #1208 lets you choose a category for your post, so it seems like this issue is a conceptual duplicate of one or both of these. if you disagree, please comment why this issue is different and it may be reopened

**Closed by trwnh** 2023-05-14 07:57 UTC
Labels: suggestion
