### ISSUE TITLE
Web frontend and API returning 500 Internal Server Error on media upload for JPG/HEIC files

### ISSUE THREAD

**Issue by Jorijn** [mastodon/mastodon#26370] opened 2023-08-07 09:21 UTC
Hi,

We're having some issues with a user who's uploading pictures from her Samsung (Android) phone using the Tusky app. The camera produces `.JPG` files, but when inspecting its contents, the mime type suggests it's a `image/heic` file. 

When uploading this image to either toot.community, or mastodon.social, the server returns a 500 Internal Server Error.

I'm attaching the picture inside a .ZIP file, to prevent GitHub from altering it in 
any way: [IMG_20230806_104609_649.jpg.zip](https://github.com/mastodon/mastodon/files/12274400/IMG_20230806_104609_649.jpg.zip)

### Steps to reproduce the problem

* Upload the attached picture.
* Observe the described behavior.

### Expected behaviour

The photo would upload and show in the post editor.

### Actual behaviour

The photo is not uploaded, a toast with `500` appears in the bottom left.

### Mastodon instance

mastodon.social, toot.community

### Mastodon version

v4.1.5+nightly-2023-07-31

### Browser name and version

Safari (Version 16.6 (18615.3.12.11.2))

### Operating system

macOS 13.5 (22G74)

### Technical details

Logs from the web container(s):

```
Common labels: {"app":"mastodon","component":"web","container":"web","filename":"/var/log/pods/tootcommunity_tootcommunity-mastodon-web-788496686f-5grvr_04f25db6-80e2-4a29-ab5b-184f7caf68d4/web/0.log","instance":"tootcommunity","job":"tootcommunity/mastodon","namespace":"tootcommunity","node_name":"pool-toot-2-ynieh","pod":"tootcommunity-mastodon-web-788496686f-5grvr","stream":"stdout"}
Line limit: "1000 (17 returned)"
Total bytes processed: "67.8  MB"


2023-08-07T11:18:48+02:00	[5dde5fa18a186587d31f9570c6a20198] lib/public_file_server_middleware.rb:18:in `call'
2023-08-07T11:18:48+02:00	[5dde5fa18a186587d31f9570c6a20198] lib/mastodon/rack_middleware.rb:9:in `call'
2023-08-07T11:18:48+02:00	[5dde5fa18a186587d31f9570c6a20198] app/controllers/concerns/localized.rb:11:in `set_locale'
2023-08-07T11:18:48+02:00	[5dde5fa18a186587d31f9570c6a20198] app/controllers/api/v2/media_controller.rb:5:in `create'
2023-08-07T11:18:48+02:00	[5dde5fa18a186587d31f9570c6a20198] lib/paperclip/attachment_extensions.rb:20:in `post_process_style'
2023-08-07T11:18:48+02:00	[5dde5fa18a186587d31f9570c6a20198] lib/paperclip/attachment_extensions.rb:20:in `inject'
2023-08-07T11:18:48+02:00	[5dde5fa18a186587d31f9570c6a20198] lib/paperclip/attachment_extensions.rb:20:in `each'
2023-08-07T11:18:48+02:00	[5dde5fa18a186587d31f9570c6a20198] lib/paperclip/attachment_extensions.rb:21:in `block in post_process_style'
2023-08-07T11:18:48+02:00	[5dde5fa18a186587d31f9570c6a20198] app/lib/fast_geometry_parser.rb:5:in `from_file'
2023-08-07T11:18:48+02:00	[5dde5fa18a186587d31f9570c6a20198]   
2023-08-07T11:18:48+02:00	[5dde5fa18a186587d31f9570c6a20198] IOError (closed stream):
2023-08-07T11:18:48+02:00	F, [2023-08-07T09:18:48.463813 #39] FATAL -- : [5dde5fa18a186587d31f9570c6a20198]   
2023-08-07T11:18:48+02:00	I, [2023-08-07T09:18:48.462960 #39]  INFO -- : [5dde5fa18a186587d31f9570c6a20198] method=POST path=/api/v2/media format=html controller=Api::V2::MediaController action=create status=500 duration=20.83 view=0.00 db=3.76
2023-08-07T11:18:48+02:00	I, [2023-08-07T09:18:48.461713 #39]  INFO -- : [5dde5fa18a186587d31f9570c6a20198] [paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
2023-08-07T11:18:48+02:00	I, [2023-08-07T09:18:48.453956 #39]  INFO -- : [5dde5fa18a186587d31f9570c6a20198] Command :: file -b --mime '/tmp/47990cc2af22b952682322cbc887334120230807-39-vk3t7m.heic'
2023-08-07T11:18:48+02:00	I, [2023-08-07T09:18:48.453613 #39]  INFO -- : [5dde5fa18a186587d31f9570c6a20198] [paperclip] Trying to link /tmp/ea0e067ae42133ca6ad9faca49caccd920230807-39-jbqlu8.jpg to /tmp/47990cc2af22b952682322cbc887334120230807-39-vk3t7m.heic
2023-08-07T11:18:48+02:00	I, [2023-08-07T09:18:48.452359 #39]  INFO -- : [5dde5fa18a186587d31f9570c6a20198] [paperclip] Trying to link /tmp/RackMultipart20230807-39-hnxoqn.jpg to /tmp/ea0e067ae42133ca6ad9faca49caccd920230807-39-jbqlu8.jpg
```

**Comment by ClearlyClaire** [comment] 2023-08-07 09:51
Seems like a duplicate of #23588.

**Closed** 2023-08-07 10:27 UTC
Labels: bug, status/to triage, area/web interface
