### ISSUE TITLE
Profile Metadata Privacy Settings

### ISSUE THREAD

**Issue by trymeouteh** [mastodon/mastodon#15549] opened 2021-01-12 16:58 UTC
Please add a setting to allow for your profile metadata to be visible to anyone, or to only your followers.

**Comment by vmstan** [comment] 2023-11-17 16:03
Duplicate of https://github.com/mastodon/mastodon/issues/15548, https://github.com/mastodon/mastodon/issues/15549, https://github.com/mastodon/mastodon/issues/15550, https://github.com/mastodon/mastodon/issues/15551 and https://github.com/mastodon/mastodon/issues/15552

**Closed by vmstan** 2023-11-17 16:03 UTC
