### ISSUE TITLE
Group favourited notifications for the same toot.

### ISSUE THREAD

**Issue by Heather-Herbert** [mastodon/mastodon#21288] opened 2022-11-21 09:35 UTC
### Pitch

Currently, all favourited notifications appear as individual entries within the notifications tab.
While this works well for low-volume notifications (5 or so) once a toot "goes viral" and receives hundreds of notifications, increasingly likely given the increase in user base over recent weeks, it makes locating other types of notifications (follows or reposts) difficult.

Current Notification card
![image](https://user-images.githubusercontent.com/410682/203012855-bb544514-afd7-468f-af25-bf4b218f4fb3.png)
(Apologies for the poor editing)

Suggested Notification card
![image](https://user-images.githubusercontent.com/410682/203014134-d228e75c-647d-4a42-baee-87620d49a824.png)

### Motivation

This change would assist users with popular toots (as noted within the Pitch section, this is increasingly likely), helping prevent "notification overload" and improving the usability of the notification tab

**Comment by ClearlyClaire** [comment] 2022-11-21 10:00
Duplicate of #20146

**Closed by ClearlyClaire** 2022-11-21 10:00 UTC
Labels: suggestion
