### ISSUE TITLE
Sort Comments by Most Starred/Boosted/Replied

### ISSUE THREAD

**Issue by lwtong** [mastodon/mastodon#23729] opened 2023-02-19 17:37 UTC
### Pitch

1. Allow tooter to pin comments at the top of the comments section of a toot.
2. Dropdown in toot-comments section to sort by most starred/boosted/replied/newest/oldest.

### Motivation

1. Minimize duplicate-comment replies if a user can view by most starred/boosted/replied comments.
2. Increase engagement; particularly with news organizations, and creatives using Mastodon as part of their social-media outreach.

These features are commonly available in news articles on the web.

**Comment by rbos** [comment] 2023-02-22 20:27
This would be very helpful for me. Once you exceed a certain number of follows, you quickly get overwhelmed and can't keep up with the feed. It would be nice to have posts ranked by number of favourites, or by number of retoots, or some combination of that. As far as I can tell, I only ever see 0/1 favourites on a toot, depending on whether I personally have interacted with it, so I guess some mechanism for sharing the (anonymized) total of favourites/boosts would be good. I suppose malicious servers could misreport favourite/boost numbers, but if servers are caught doing that too much, I expect they'd get blocked and otherwise ostracized.

**Comment by trwnh** [comment] 2023-10-31 09:46
Duplicate of #15062

**Closed by trwnh** 2023-10-31 09:46 UTC
Labels: suggestion
