### ISSUE TITLE
Post is `text/html` yet RSS says it is `text/plain`

### ISSUE THREAD

**Issue by sjehuda** [mastodon/mastodon#29891] opened 2024-04-10 14:09 UTC
### Steps to reproduce the problem

1. Unknown
2. See https://ma.fellr.net/@fell/112217662940193667
3. Extract data from RSS feed https://fosstodon.org/tags/postmarketos.rss

### Expected behaviour

RSS should indicate that post is HTML

### Actual behaviour

RSS indicates that post is Plain Text

**Comment by sjehuda** [comment] 2024-04-10 15:10
Use case.

By using Mastodon feed I was hoping to easily forward contents from Mastodon platforms to Movim platform using Slixfeed news bot.

Here is a good post, which is published as "Atom Over XMPP" (see IETF 66) and is translated to HTML due to the attribute value `text/html`.

![forward_mastodon_to_movim_good](https://github.com/mastodon/mastodon/assets/19249089/546b3ebd-31ca-40ab-9e0d-80783d9add68)

Here is a bad post which is really HTML but the attribute value indicates`text/plain`. so Movim does not render it as HTML.

![forward_mastodon_to_movim_bad](https://github.com/mastodon/mastodon/assets/19249089/776ed908-9a80-45f9-9349-a6d86ec8e331)

[Images and links](https://github.com/mastodon/mastodon/assets/19249089/e0c54ac5-2fc5-490a-a605-cd115e0f0a6a) appear nicely - I mention this just so you know how the message appears in Movim.

**Comment by mjankowski** [comment] 2024-12-03 14:09
Can you add more detail about which parts of the generated feed have the wrong type? It's not obvious to me from the title and description of this issue, along with the rss2 spec, what exactly the disconnect is..

**Comment by sjehuda** [comment] 2024-12-04 10:37
I did not attache the feed itself.

The problem is that the feed indicateda type of (plain) Text instead of HTML.

**Comment by trwnh** [comment] 2024-12-04 10:44
Where does the feed indicate it is text/plain? How ought it indicate that it is text/html?

**Comment by sjehuda** [comment] 2024-12-04 12:22
See attribute "type".
```
type="image/png"
type="plain"
etc.
```

**Comment by mjankowski** [comment] 2024-12-04 13:43
Yes, sorry - those were my questions as well. I don't see the described problem present in the provided URL.

Going to close this as cant reproduce -- but if you are able to find an RSS feed produced by current release which has these qualities, please reopen this and add direct feed snippet in question, link to feed, link to rss validator with feed, etc...

**Closed by mjankowski** 2024-12-04 13:43 UTC
Labels: status/to triage

**Comment by sjehuda** [comment] 2024-12-04 19:58
@Gargron That was a guess. As I had no raw data.

@mjankowski I will. Thank you.

I advise to utilize Atom Syndication Format as it is a standard and is more robust than RSS.
