### ISSUE TITLE
[Request] Exclusive lists (hiding listed toots from the primary timeline on an opt-in basis)

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#16556] opened 2021-08-02 02:42 UTC
### Pitch

https://github.com/hometown-fork/hometown/wiki/Exclusive-lists

This feature rules. Please port it.

### Motivation

Twitter has the ability to add people to lists you don't follow... mastodon does not
so I need to follow people, then list them, which causes my timeline to be filled with people I wouldn't otherwise follow.

Excellent middle ground of supporting both the follow first (less stalkerish) modal, while also allowing lists to be more useful.

this is also an opt-in UX feature that won't cause distruption to existing users. win win

**Comment by dariusk** [comment] 2021-08-04 04:48
FYI, [this commit is my implementation](https://github.com/hometown-fork/hometown/commit/bfc0fbab2c94dc134715f555edf793991da172a2) along with [this bugfix](https://github.com/hometown-fork/hometown/commit/b2270fd37). I could make a pull request if that's something maintainers would like to see.

**Comment by shleeable** [comment] 2021-08-04 15:23
I'm a huge fan of merging forked features into the master. Allows forks to experiment more and gain some consensus and quality control... Please PR and see what they say

**Comment by dariusk** [comment] 2021-08-04 15:24
Planning to later today!

**Comment by shleeable** [comment] 2021-10-14 03:55
@dariusk hey friend.

**Comment by bixfrankonis** [comment] 2022-05-02 19:26
Really need this in core Mastodon.

**Comment by dariusk** [comment] 2022-11-08 00:07
I'd assume not. The 4.0 code is very different and I've only just begun
looking at it.

**Comment by sunarch** [comment] 2022-12-12 01:02
I would also like if something like this was implemented.

**Comment by gutocarvalho** [comment] 2023-01-27 13:57
It's an important feature, I hope we can see this soon.

**Comment by narration-sd** [comment] 2023-02-09 21:49
a quesion: would this still leave listed identities in everyone-visible Home:Following?

I often enough want to hear what persons are saying, but not broadcast that I may in any way agree with them...!

More demos, more privacy to go with, no?

**Comment by dariusk** [comment] 2023-02-09 22:05
> a question: would this proposal still leave listed identities in everyone-visible Home:Following?

Yes, it would not change anything about the visibility of who you follow -- that is a separate feature. This feature is simply about shunting messages from one timeline (the Home timeline) to another (a list timeline).

You have the option to hide your entire list of who you follow by choosing "Hide your social graph" under Preferences

![image](https://user-images.githubusercontent.com/266454/217949789-bcb4533d-4b76-494b-93aa-a729095aa0f6.png)

But you do not have the option to hide some subset of accounts you follow.

**Comment by narration-sd** [comment] 2023-02-10 01:11
Well, thanks, @dariusk . I confess the mixed motives surrounding this area are a bit mystifying. I'd come here out of that other feature still in discussion.

It seems to me that what you're setting us up to do here is:
a) show everything that for intelligent reasons we want to pay some attention to, thus labelling oursevles as nuts if we list any of same, or,
b) shut off entirely that we have any activity  at all, thus having an equally unpleasant presntation as anti-social.

The root of the problem seems to be a certain phobia some have about 'stalking'.  Which presumably is listeniing to someone but not informing them. 

So why not give us all privacy, by always informing the person folowed - so that _they_ can see our Follow, and showing tha tfollow to no-one else if all we've done is list them?

I haven't qute seen the harm of unseen following, but will understand some think this is feraful; in which case really they ought to go private, perhaps? 

But I really don't want to get into that, just see that everyone has good choices. My proposal tries to satisfy what they apparently want, while making for a much more comfortable situaiton for everyone, I hope...

Can't this work?

**Comment by dariusk** [comment] 2023-02-10 01:25
@narration-sd Forgive me but I do not understand how what you are talking about is related to this feature? It is explained in detail in the wiki article linked in the original post in this thread:

https://github.com/hometown-fork/hometown/wiki/Exclusive-lists

The purpose of the feature has nothing to do with privacy at all -- it has to do with situations where, say, I would like to follow a lot of accounts that post cat pictures, but I don't want them in my home feed and would prefer to look at them on my own time. I would add them to an Exclusive List and then they would skip my home feed. Then I could click on the list and view them when I feel like it.

I feel like you may be misunderstanding the feature entirely? Your "show everything" or "shut off everything" has nothing to do with Exclusive Lists, which operate on an account by account basis, shut nothing off, and expose no information to outside parties.

Perhaps it was the screenshot I included in my post above that was a source of confusion: I included it as an off-topic courtesy in case you were unaware of the feature (which has nothing to do with this thread), but maybe you thought it was related?

**Comment by narration-sd** [comment] 2023-02-10 02:02
Darius, it's true I might be misunderstanding here -- that's why I asked you the question. 

I came here from a more open-season discussion on the significant problem, in https://github.com/mastodon/mastodon/issues/6982.  Which today, references this proposal.

The basis  of my comment is that at present, Mastodon does not allow you to List contributors without Following them.

In that context, I suspect my comments make good sense. But -- are you solving that issue here? Or just masking the discomfort of having a home timeline filled with heavy contributors?

I have that problem also, immediately on coming to Mastodon weeks ago. For some reason, otherwise interesting persons spam -- I haven't understood that reason yet. Maybe trying to appeal broadly to get followers. But it nearly destroys the ability to watch ones Home timeline.

**Comment by trwnh** [comment] 2023-05-20 20:05
Duplicate of #9964

**Closed by trwnh** 2023-05-20 20:05 UTC
