### ISSUE TITLE
Show user's profile metadata on timeline hover.

### ISSUE THREAD

**Issue by derspyy** [mastodon/mastodon#27978] opened 2023-11-19 12:58 UTC
### Pitch

the idea is that you should be able to see profile metadata on hover, just like on misskey.

![image](https://github.com/mastodon/mastodon/assets/65043391/986cbb48-796a-48da-89f4-09c7e2924eeb)

### Motivation

this was brought up on #16226.

the reasoning is that there is already a dedicated place for pronouns, however they aren't easily accessible from the timeline.

**Comment by trwnh** [comment] 2023-11-19 23:35
Duplicate of #14918

**Closed by trwnh** 2023-11-19 23:35 UTC
Labels: suggestion
