### ISSUE TITLE
Filters not working as intended (on mastodon.social) on the explore tab. But they work properly on third party apps like Ice Cubes.

### ISSUE THREAD

**Issue by zchilds** [mastodon/mastodon#24016] opened 2023-03-07 15:25 UTC
### Steps to reproduce the problem

1. Create a filter with keywords (example Elon Musk)
2. Open the explore timeline
3. Scroll and read posts, but they aren't being filtered

![image](https://user-images.githubusercontent.com/32874904/223466858-6c389f71-c27c-4c31-947c-975c28605a47.png)

![image](https://user-images.githubusercontent.com/32874904/223466888-99a0e18c-0709-4dcb-bb6b-396d5379f037.png)

![image](https://user-images.githubusercontent.com/32874904/223466754-e9f4dc43-6a83-4855-97c4-56fa47d75d53.png)

### Expected behaviour

Posts should be hidden completely

### Actual behaviour

Posts are completely visible. Not hidden whatsoever.

### Specifications

- Using latest stable release of Google Chrome
- Using the www.mastodon.social website
- On the "explore" tab

It works properly when using third party apps such as https://elk.zone/ or the Ice Cubes app. Does not work on the primary mastodon website.

**Comment by trwnh** [comment] 2023-03-08 01:06
Duplicate of #21083

**Closed** 2023-05-19 06:03 UTC
Labels: bug
