### ISSUE TITLE
Request: collapse retoot/fav notifications

### ISSUE THREAD

**Issue by Viss** [mastodon/mastodon#28243] opened 2023-12-05 21:15 UTC
### Pitch

Currently, if a post gets popular or even goes viral, the notification functionality more or less spams the notification column, flooding it with every occurence of a fav or a boost, resulting in thousands of notifications. It would be really nice to see that 'collapsed' into one notification saying '3592 people boosted your post' versus seeing all 3592 individual notifications

### Motivation

since we cant make the columns wider, and since every notification comes in piecemeal, this results in somewhat of a ddos scenario for anybody who makes a sufficiently popular post - their notifications get slammed and they'll miss things. 

also, on tusky, which has the same problem with not collapsing notifications, each notification comes through as an android alert, so all 3592 individual notifications also become push notifications.

**Comment by renchap** [comment] 2023-12-05 21:45
Closing as duplicate of #1483

We are planning to add notifications grouping in the next version (4.3).

**Closed by renchap** 2023-12-05 21:45 UTC
Labels: suggestion
