### ISSUE TITLE
Cannot add some users to list immediately after following

### ISSUE THREAD

**Issue by confluence** [mastodon/mastodon#20541] opened 2022-11-13 06:49 UTC
### Steps to reproduce the problem

1. Click through to a user profile on home server
2. Click the follow button
3. Immediately attempt to add the user to a list

### Expected behaviour

User is added to the list

### Actual behaviour

There is an error and the attempt fails

### Detailed description

This primarily seems to affect a particular remote server which takes a long time to resolve follow requests. I can immediately see when this has happened, because the `+` button label next to the list name does not rotate to an `x`, and I get a popup error on the left (`404 Record not found`). If I check my followed accounts, I can see that the account is not there yet.

I assume that during the delay before the follow request completes I am not following the account yet and so it's impossible for me to follow them. I am able to follow the account later, once it shows up in my list of followed accounts, but this is annoying because in the current UI immediately after following is the most convenient time to add an account to a list. I wonder if it would be possible to detect that the follow request is pending, and queue the add-to-list request to execute if it succeeds.

### Specifications

Mastodon v4.0.0rc3

**Comment by ClearlyClaire** [comment] 2022-11-15 10:07
Duplicate of #19707

**Closed by ClearlyClaire** 2022-11-15 10:07 UTC
Labels: bug
