### ISSUE TITLE
StatusesIndex: NoMethodError: undefined method `extract_status_plain_text' for StatusesIndex:Class

### ISSUE THREAD

**Issue by markusblogde** [mastodon/mastodon#17965] opened 2022-04-05 13:20 UTC
### Steps to reproduce the problem

1. Upgraded Elasticsearch to 7.17.2
2. Upgraded Mastodon to 3.5.0
3. View sidekiq queue

### Expected behaviour

sidekiq queue should be processed

### Actual behaviour

queue filled up with index errors:

NoMethodError: undefined method `extract_status_plain_text' for StatusesIndex:Class

### Specifications

mastodon v3.5.0

**Comment by mfa777** [comment] 2022-04-05 13:57
I got plenty of same error, it looks like going to be solved in next version: https://github.com/mastodon/mastodon/issues/17913

**Comment by ClearlyClaire** [comment] 2022-04-05 14:13
Duplicate of #17913, fixed by #17912 (not released yet, to be included in 3.5.1)

**Closed by ClearlyClaire** 2022-04-05 14:13 UTC
Labels: bug
