### ISSUE TITLE
News tab in explore should go to the discussions first, not the article.

### ISSUE THREAD

**Issue by jaded0** [mastodon/mastodon#21909] opened 2022-12-01 01:25 UTC
### Pitch

Allow the user to see the discussions happening related to an article by clicking on it in the news tab of the explore page. If they really want to go to the article, allow the discussions screen a link at the top that will take the user there.

### Motivation

Reddit is a good example of this. When I click on a news story on the reddit homepage, I actually want to see people's comments about it. The app has no intuitive way to do so from the news screen.

**Comment by afontenot** [comment] 2022-12-01 06:44
> News tab in explore should go to the discussions first, not the article

Maybe this is your point, but as far as I know there's no way to find "discussions" *at all*. It's not that the news interface is unintuitive, it's that it doesn't provide this capability! (I'd love to be corrected if this is wrong.)

Looking up what people are saying about a given news article would amount in some sense to a "search", and Mastodon (broadly speaking) doesn't allow you to find content by searching. Is your request that Mastodon allow you to find discussions happening around a news article? If so, you might edit the title of the issue to something like "The news tab in explore should show posts talking about the articles" or something like that.

**Comment by ClearlyClaire** [comment] 2022-12-07 12:05
Duplicate of #19620 I think (feel free to reopen if you disagree). I maintain my position that posting a link does not have the same implications as posting hashtags and does not imply that you intend for your post to be searchable based on that link.

**Closed by ClearlyClaire** 2022-12-07 12:05 UTC
Labels: suggestion
