### ISSUE TITLE
Allow to Hide Bots From the Global and Local Timeline or Make A Separate Bots Timeline

### ISSUE THREAD

**Issue by drequivalent** [mastodon/mastodon#16054] opened 2021-04-17 12:55 UTC
### Motivation

The Fediverse has a bot problem. When people open the timelines, they see bot posts mixed in with the user posts. And the bots (being by no means spambots but useful or funny ones) may be much chattier than the people, who have a limited capacity, both mental and physical, to post stuff. This results in terrible signal to noize ratio while browsing the Fediverse, making the impression that only bots live here. THAT NOT GUD USER EXPERIENCE, YEH?

### Pitch

There are two solutions I see. One would be - make a setting for global and local timelines that would allow the user to hide posts from the actors that are marked as bots:

![Screenshot from 2021-04-17 15-58-09](https://user-images.githubusercontent.com/1463277/115114035-d9ec0800-9f95-11eb-8890-2c6f0fec7f06.png)
![Screenshot from 2021-04-17 15-48-51](https://user-images.githubusercontent.com/1463277/115113888-2edb4e80-9f95-11eb-9996-70f86715e594.png)

OR

Make a separate bot timeline: all bots all the time, and hide them from all other timelines.

Discuss!

**Comment by Oreolek** [comment] 2021-04-18 07:14
Duplicate of #8293

**Closed** 2023-05-19 14:14 UTC
