### ISSUE TITLE
GIF uploads fail with "file size too big" even if they are only 1 MB

### ISSUE THREAD

**Issue by tswast** [mastodon/mastodon#2467] opened 2017-04-26 03:17 UTC
I had trouble posting this GIF:

<details>
 <summary>GIF</summary>

![doodle007](https://cloud.githubusercontent.com/assets/247555/25416621/909b6d1a-29f3-11e7-9a68-144d42ec5f19.gif)

</details>

Even though it is only 1 MB, it gave me an error that the file size was too big on upload. To work around this, I ran the GIF through the [gifsicle -O3 lossless optimizer](https://www.lcdf.org/gifsicle/), which resulted in this GIF, which does upload fine.

<details>
 <summary>GIF</summary>

![doodle007-o3](https://cloud.githubusercontent.com/assets/247555/25416674/d8f8cbd4-29f3-11e7-805b-c2b5a3d7752a.gif)

<details>
</details>

You'll notice that the file size is barely different, but it made the upload to Mastodon work. Maybe that could be a first step in any GIF upload? It's a pain to have to do it manually, especially when I'm on a mobile phone.

Note: I'm not the only user to have this issue. See [this thread](https://mastodon.social/@WelshPixie/4173624).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) - 1.2.2 - and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment] 2017-04-26 07:51
Thanks for the issue, strange indeed. (Note: I've edited your issue to hide the GIFs behind a `<details>` tag by default.)

**Comment by rixx** [comment] 2017-04-26 17:51
I see the same thing on my instance: I get told that uploads max be only 8MB even if the gif is much smaller. It seems to work starting at some very small size instead.

**Comment by Artoria2e5** [comment] 2017-05-01 00:29
It looks like the first GIF image is 1077441 bytes, just a bit more than the `1.megabytes` = 1048576 bytes cap.

```
$ wget https://cloud.githubusercontent.com/assets/247555/25416621/909b6d1a-29f3-11e7-9a68-144d42ec5f19.gif
[...]
[scrubbed] ‘909b6d1a-29f3-11e7-9a68-144d42ec5f19.gif’ saved [1077441/1077441]
```

**Comment by Cassolotl** [comment] 2018-05-26 10:34
I just uploaded a 1.8MB gif to a vanilla instance without issues, so I can't reproduce this. Maybe it's been fixed?

**Comment by rixx** [comment] 2018-05-26 11:18
Looks that way, yes, can confirm large gif upload is working.

**Comment by Tagadda** [comment] 2018-05-27 02:27
Hey, I just tried to update my header with a 1.8MB one, still an issue.
I'll update this post with a link to the gif shortly.

**Comment by Cassolotl** [comment] 2018-05-27 08:46
Are you able to upload it to a post? (Maybe it's just headers somehow?)

**Comment by Tagadda** [comment] 2018-05-27 09:01
I can post it as a toot, no problem with that.
AFAIK, GIF headers are NOT converted to mp4, and the max file size is 2MB.

**Comment by Cassolotl** [comment] 2018-05-27 09:50
I see! Thank you for explaining. :)

**Comment by trwnh** [comment] 2023-05-13 23:40
closing this issue -- if it is still happening, please file a new issue

**Closed by trwnh** 2023-05-13 23:40 UTC
Labels: bug
