### ISSUE TITLE
please add support for passkeys and passwordless login

### ISSUE THREAD

**Issue by jakeyounglol** [mastodon/mastodon#27225] opened 2023-09-30 17:53 UTC
### Pitch

please add passkeys. it’s more secure than passwords and even 2FA. it would also be great if you could just sign in with passkeys and not even have to type in my username/email address

### Motivation

this would benefit everyone including server operators and users. it is also a security improvement

**Comment by ClearlyClaire** [comment] 2023-10-02 09:53
Duplicate of #20383

**Closed by ClearlyClaire** 2023-10-02 09:53 UTC
Labels: suggestion
