### ISSUE TITLE
Column with many additional tags displays only the original tag

### ISSUE THREAD

**Issue by CosineP** [mastodon/mastodon#12373] opened 2019-11-13 04:44 UTC
### Expected behaviour

![hashtags](https://user-images.githubusercontent.com/3986627/68733583-1a777300-05a5-11ea-873a-cf24841fccfc.png)
i expect to see in order of time posted some #overwatch, some #stevenuniverse, some #drawing and such

### Actual behaviour

i only see #stevenuniverse (the original hashtag) posts in the column. this issue is not resolved by a page refresh

### Steps to reproduce the problem

i added many hashtags to one column. i also have some "not" tags. this problem may have first appeared (can't quite remember) when i added another "not" tag, but having since removed it my column is still broken.

before this i had a similar issue: when i clicked on #stevenuniverse in my column, the unpinned column would actually be my mixed special one, and the old one would become #stevenuniverse. this was fixed by a refresh so i don't care enough to open a tracker, but i mention in case it helps

### Specifications

v3.0.1 vanilla @ masto.host (anticapitalist.party)

Firefox 70.0.1 on Debian 10

**Comment by panarom** [comment] 2019-11-13 18:00
I think you're seeing this behavior because of https://github.com/tootsuite/mastodon/pull/12091 (as referenced in https://github.com/tootsuite/mastodon/issues/12197, which may make this issue a duplicate of that one).  I'm not sure if there's an open issue for refactoring the UI code to indicate the limits on the number of tags

**Closed** 2023-11-17 02:31 UTC
