### ISSUE TITLE
Feature Request: Public/Private profile/avatar/banner/meta

### ISSUE THREAD

**Issue by MxtressMyxx** [mastodon/mastodon#15644] opened 2021-01-30 19:18 UTC
When an account is set to approve follows, allow the ability for users to set a separate public facing profile/avatar/banner/meta for non-followers.

This would allow folks to keep potentially sensitive information out of the public eye while still allowing users to divulge additional information to approved followers.

**Comment by ThibG** [comment] 2021-01-31 18:04
Duplicate of #15548,  #15549, #15550, #15551 and #15552

**Closed by ThibG** 2021-01-31 18:04 UTC
