### ISSUE TITLE
Rearrange images in post editor after bulk upload

### ISSUE THREAD

**Issue by Sushubh** [mastodon/mastodon#28437] opened 2023-12-20 01:43 UTC
### Pitch

So, this is a problem I have been facing since day one. Suppose I want to share a couple of images in a particular order and I select them in file picker in proper order… Mastodon post editor would never get them in right order forcing me to reupload one image at a time to get them in order. 

This highlights another annoyance. The editor size changes during and after upload moving the upload and post button up and down. If the images can be rearranged after upload, this resolves both the ux/ui issues. 

### Motivation

This would improve user experience. Anyone who post multi-image posts on a regular basis would benefit from such a change.

**Comment by Cassolotl** [comment] 2023-12-21 11:07
Duplicate of *[Feature request] Ability to reorder attached images after uploading but before posting #9635* (Dec 2018)

**Closed** 2023-12-31 06:15 UTC
Labels: suggestion
