### ISSUE TITLE
Post language button wrapped into two lines when zh-CN/HK/TW/YUE was selected

### ISSUE THREAD

**Issue by sorz** [mastodon/mastodon#26967] opened 2023-09-19 05:30 UTC
### Steps to reproduce the problem

1. Select one regional Chinese, e.g. Chinese (China), on the language drop-down menu.

### Expected behaviour

"ZH-CN" displayed as a whole like surrounding buttons.

### Actual behaviour

The button was splitted into "ZH-" and "CN" on two lines.

### Detailed description

![Screenshot 2023-09-19 131033](https://github.com/mastodon/mastodon/assets/535565/4c4c446c-4b93-49ec-ab11-74b65efbf4c0)

Regional Chinese options was added on #26066.

### Mastodon instance

self-host instance

### Mastodon version

v4.2.0-rc

### Browser name and version

Firefox 118.0b9

### Operating system

v4.2.0-rc1

**Comment by gunchleoc** [comment] 2023-09-24 11:19
Duplicate of https://github.com/mastodon/mastodon/issues/19302

**Closed** 2023-09-25 10:59 UTC
Labels: bug, status/confirmed, area/web interface
