### ISSUE TITLE
Add a bulk action for managing lists on the relationships page

### ISSUE THREAD

**Issue by rpkoller** [mastodon/mastodon#19859] opened 2022-11-06 14:00 UTC
### Pitch

It would be convenient and helpful to add a new bulk action to the `relationships` page. Currently there is only the option to unfollow selected users. But instead I would propose the following addition (the feature aka its interface components should only be visible if the number of created lists >= 1)

- Add a new column showing the lists, a person you follow, is on
- Add a new filter option with the options `all`, `not on a list` and a select element where the user is able to filter for a certain list. 
- Add a select element to the bulk action row on top of the follows and followers list where the user is able to select a certain list with a button `add to list` and a button `remove from list` to trigger the action in the end 
- On a dedicated list page the `edit list` button could instead of opening a model forward the user to the relationships page. Or in case the user list table on the appearance page would get too crowded with the new proposed components a similar page to relationships could be created solely dedicated to list management.

That way it would be possible to govern the assignment and removal of accounts to the different lists in a convenient and comfortable way. 

### Motivation

Motivation was the following. I've used Mastodon a few years back for a short while. I've already added a few persons to follow. I went on a hiatus. A few days ago I've started using it again. I've added a few more persons to my following list. So i have ~100 accounts added. I've then thought it would be reasonable to give lists a go and structure the people I follow semantically by context and where their main areas of interest are. 
Problem is if you create a list and then press the `edit the list` button to add a new person to the list, you have to add the name in the search bar on top of the lists members list. Due to the fact that there is no autocomplete functionality in place that process turns out quite cumbersome and in particular challenging (you have actually to know the account names from the top of your head - from a a11y perspective that is challenging task). I had to open a second window with my overall mastodon user list. I then went through that list and every time i've spotted a user name suitable for the list i was currently populating,  i've then typed in that username in the list modals search field in the other window and added the account. 
thats a time consuming process. in contrast with the suggestion i've pitched that process would be streamlined. you would simply have to select a list in the bulk action, click all the accounts you want to add and then submit the request.

**Comment by trwnh** [comment] 2023-05-20 20:19
Duplicate of #19856

**Closed by trwnh** 2023-05-20 20:19 UTC
Labels: suggestion
