### ISSUE TITLE
Hashtags in the CW field are not treated as hashtags

### ISSUE THREAD

**Issue by alper** [mastodon/mastodon#20649] opened 2022-11-14 11:55 UTC
### Steps to reproduce the problem

1. I created a new toot with a CW
2. The CW was the hashtag "#musk"
3. I searched my local server for this hashtag.

### Expected behaviour

I expect my toot with the #musk hashtag in the content warning to show up in the list of toots.

### Actual behaviour

My toot did not show up. Other toots with that hashtag did.

### Detailed description

I think it would be helpful for a bunch of reasons to make the CW field a native part of the toot (unless this would create other unwanted interactions).

In particular it could be a good place to put a hashtag and being able to put hashtags in the CW would allow an onramp to standardise the CWs that people use. This could later be helpful in allowing more useful filtering functionality.

### Specifications

Metatext 1.5.3

**Comment by ClearlyClaire** [comment] 2022-11-15 09:57
This is presumably by design, but maybe this could be revisited. See #699

**Comment by lazy-fox** [comment] 2022-11-21 13:36
Came here as a newbie to Mastodon via VERY similar expectations as OP, read reasoning of #699 and found a few other issues on this topic describing it as "spoiler" or unsearchable CW.

Have not looked at filtering yet (newbie...) but read here that not only suppressing, but (easier) discovery is on the table - which is the angle I am arguing on. 

From my naive POV searching CW (as only or additional option?) makes sense as CW is read more often (&perhaps revisited at later time) and needs less resources, similar to searching a few GB of emails on sender and word occurs in subject line instead of word occurs in text of mail.

**Comment by clarfonthey** [comment] 2022-11-21 19:23
Seems like this is also open in the form of #11443. Would love to see this properly fixed. IMHO, mentions and hashtags should be linked in the subject field just like they are in the body.

**Comment by yllekz** [comment] 2023-02-17 19:08
Feels like a bug that should be fixed. It should be an expected behavior that putting a pound-sign before a word anywhere on Mastodon results in the same behavior no matter what. The title of a CW post should be no exception.

**Comment by trwnh** [comment] 2023-05-14 23:35
Duplicate of #699

**Closed by trwnh** 2023-05-14 23:35 UTC
Labels: bug
