### ISSUE TITLE
Feature Request: follow (sub)threads, not only actors

### ISSUE THREAD

**Issue by Unip0rn** [mastodon/mastodon#8153] opened 2018-08-09 16:40 UTC
The usecase is, that someone (not me) starts some discussion or asks a question that rises my interest so I want to get updates on it.
Currently I only see the option to frequently poll the discussion or ask people to include me in the mentions but that seems a bad UX to me, since it requires people to actively support something the maschine could do much better.
The way I dream about this, there is just another button next to boost/fav.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nilesjohnson** [comment] 2022-11-26 13:52
I'd like to voice my support for this feature.  There are a number of cases where discussion is disjointed, or repetitive (or both!) because some participants miss the replies of others.  Also, depending on how this is implemented, the underlying functionality could potentially address #10865 as a special case.

**Comment by trwnh** [comment] 2023-05-14 16:12
Duplicate of #7969

**Closed by trwnh** 2023-05-14 16:12 UTC
Labels: suggestion
