### ISSUE TITLE
'schema' term definition value in context should end with slash instead of fragment

### ISSUE THREAD

**Issue by csarven** [mastodon/mastodon#32273] opened 2024-10-06 11:57 UTC
### Steps to reproduce the problem

1. `curl -H'Accept: application/ld+json' https://w3c.social/users/csarven`
2. Observe that the JSON-LD context uses `"schema":"http://schema.org#"`
3.
...

### Expected behaviour

`"schema":"http://schema.org/"`

### Actual behaviour

`"schema":"http://schema.org#"`

### Detailed description

The value of the term `schema` should end with slash (`/`) for the schemaorg URL: `http://schema.org/` instead of `http://schema.org#`. The intended URLs of schema terms are of this form: `http://schema.org/{term}`

### Mastodon instance

https://w3c.social/

### Mastodon version

v4.2.11

**Comment by trwnh** [comment] 2024-10-06 15:11
Duplicate of #18361

**Closed by trwnh** 2024-10-06 15:11 UTC
Labels: bug, status/to triage
