### ISSUE TITLE
Order of hashtags in search

### ISSUE THREAD

**Issue by nclm** [mastodon/mastodon#19585] opened 2022-10-31 12:42 UTC
### Steps to reproduce the problem

1. Search for a hashtag
2. Look at the list of results

<img width="899" alt="Screenshot 2022-10-31 at 13 34 02" src="https://user-images.githubusercontent.com/923008/199009655-5e4546c7-7ebd-411e-b614-f3b7b083401b.png">

### Expected behaviour

The hashtag I searched for should be the first on the list 

### Actual behaviour

A lot of other tags are positionned before, and I need to click “Load more” then scroll down to get to what I was looking for

### Detailed description

They could even be some bolding/highlighting of the what I searched in all hashtags, so I can see better how the other ones differ.

### Specifications

Mastodon v4.0.0rc1

**Comment by ClearlyClaire** [comment] 2022-10-31 16:33
Duplicate of #19575

**Closed by ClearlyClaire** 2022-10-31 16:33 UTC
Labels: bug
