### ISSUE TITLE
Save temporary text draft

### ISSUE THREAD

**Issue by giuliohome** [mastodon/mastodon#22797] opened 2022-12-27 19:45 UTC
### Pitch

When publishing or editing a toot, the temporay drafted text should be saved somewhere, at session level or in application local storage or at server level. I don't want to specify the implementation details here, just a couple of technical examples in Ruby on Rails, both unrelated to mastodon: [client side](https://stevepolito.design/blog/rails-auto-save-form-data/) or [server side](https://stevepolito.design/blog/rails-auto-save-form-data/).

### Motivation

Especially for mobile apps, it is a common issue that switching the activity while e.g. editing a toot produces a page reload.

Notice that mobile apps (iOS and Android) resort to the Ruby on Rails webapp to edit a toot: hence please see [such a motivation originating from there](https://github.com/mastodon/mastodon-ios/issues/591#issuecomment-1366094324) too.

**Comment by giuliohome** [comment] 2022-12-27 20:09
Since you're already using the [`localStorage` for the settings](https://github.com/mastodon/mastodon/blob/main/app/javascript/mastodon/settings.js), I would likely suggest it also for the implementation of the toot's text draft autosave.

**Comment by giuliohome** [comment] 2023-03-06 09:43
Afaics this appear resolved - on the mobile side - by the above mentioned implementation, that has been released now.

Not sure whether something else is in "backlog grooming" for the desktop side..

**Comment by vmstan** [comment] 2024-05-28 13:26
Duplicate of https://github.com/mastodon/mastodon/issues/13617

**Closed by vmstan** 2024-05-28 13:26 UTC
Labels: suggestion
