### ISSUE TITLE
Support MX equivalent for domains

### ISSUE THREAD

**Issue by LoveIsGrief** [mastodon/mastodon#25127] opened 2023-05-24 22:58 UTC
### Pitch

It's possible to have email handled for you by a completely different domain than the one you own. What if the same were possible with mastodon? For those who have a personal domain, but that don't want to go through the hassle of hosting their own mastodon instance, they could add a `TXT`  (or maybe some other entry) to their DNS and have messages for mastodon go the "mastodon domain".

# Examples of possible implementations and scenarios

## Setup
 - Lakisha has a domain laki.in and a mastodon account `@laki@masto.io`
 - She would like to have a mastodon handle `@laki@laki.in`
 - She adds a `TXT` to her laki.in domain with the format `masto=laki=@laki@masto.io`
 - She adds a field on her account on masto.io "alias" = "`@laki@laki.in`"

## Sending a message

 - Yusuf wants to toot at Lakisha `@laki@laki.in` from `@yusuf@meemo.my`
 - meemo.my's mastodon instance discovers that there is no mastodon instance on laki.in
 - meemo.my falls back to looking at the `TXT` DNS entries with `masto=*`
 - meemo.my finds `laki=@laki@masto.io`
 - meemo.my toots `@laki@masto.io` with metadata that the original target was `@laki@laki.in`
 - masto.io verifies that `@laki` has the "alias" field with `@laki@laki.in` and put the toot in the inbox

### Motivation

Hosting your own services can be a pain and so can migration, so why not use existing resources and save users the effort? This will also allow those using hosted services with a cPanel that have little control over their servers to have personalized mastodon accounts. Also, mastodon is often compared to email and that has `MX` in DNS, which does something similar.

**Comment by trwnh** [comment] 2023-05-25 17:12
Duplicate of #2668

**Closed by trwnh** 2023-05-25 17:12 UTC
Labels: suggestion
