### ISSUE TITLE
Dedicated hashtag text field to add additional metadata outside of the toot text

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#23218] opened 2023-01-23 13:46 UTC
### Pitch

**style v1**
![image](https://user-images.githubusercontent.com/17537000/214054648-9243cf58-0322-4371-b7a0-b84d07798081.png)

**style v2 (tumblr style)**
![image](https://user-images.githubusercontent.com/17537000/214062254-08a23906-6e70-415e-8dc1-631f0aba301d.png)

**Reference:** 
![image](https://user-images.githubusercontent.com/17537000/214059055-53a8a487-5d04-4ef8-9d75-6a00cb6ffa1b.png)

---
**side note:**  Elk is kind of doing this by hiding hashtags at the end of the toot on the timeline. and only shows them once you click the toot directly.

![image](https://user-images.githubusercontent.com/17537000/214055256-ac4499f2-7850-4f5c-b0e0-840b0f1ba432.png)
![image](https://user-images.githubusercontent.com/17537000/214055290-9bdddb72-8d55-48f1-8899-deeeea884250.png)

### Motivation

![image](https://user-images.githubusercontent.com/17537000/214055080-8f63b7e3-8a23-4fea-b801-0800695d5800.png)

**Comment by Cassolotl** [comment] 2023-01-24 01:07
Related, maybe?

* Replace hashtags with tags #2331 (2017, closed)
* Make tags at the end of posts invisible somehow #7250 (2018, open)
* "Out-of-line" hashtags #10743 (2019, open)
* Add a "Hashtag" form in toots #20398 (2022, open)

**Comment by jimrhiz** [comment] 2023-01-28 23:50
For people who prefer the current approach, would that remain available by simply adding hashtags to the body of the post instead of using the #/Add tags button? Would such old-style hashtags still be searchable and followable?

**Comment by shleeable** [comment] 2023-01-30 00:02
> For people who prefer the current approach, would that remain available by simply adding hashtags to the body of the post instead of using the #/Add tags button? Would such old-style hashtags still be searchable and followable?

Absolutely. the concept covers both.

**Comment by trwnh** [comment] 2023-05-14 08:51
Duplicate of #10743

**Closed by trwnh** 2023-05-14 08:51 UTC
Labels: suggestion
