### ISSUE TITLE
Feature Request: Add support for AVIF images

### ISSUE THREAD

**Issue by cybrkyd** [mastodon/mastodon#30267] opened 2024-05-12 09:25 UTC
### Pitch

In January 2024, Edge finally joined the other major browsers in supporting the AVIF image format.

Please add support for AVIF to Mastodon.

Like WEBP, this next-gen format is gaining traction. It would be great to have built-in support for when a user posts, for example, a URL which has as its main thumbnail an AVIF image.

### Motivation

Like WEBP, this next-gen format is gaining traction. It would be great to have built-in support for when a user posts, for example, a URL which has as its main thumbnail an AVIF image.

**Comment by renchap** [comment] 2024-05-12 13:37
Kind of duplicate of https://github.com/mastodon/mastodon/issues/20896

Supporting multiple formats for user-facing images depending on browser support would require a full rewrite of our media pipeline. When / if we do that, this will probably come through dynamic transcoding of images using a 3rd party software (like `imgproxy`).

Closing as it is part of a larger topic that is in our backlog.

**Closed by renchap** 2024-05-12 13:37 UTC
Labels: suggestion

**Comment by cybrkyd** [comment] 2024-05-12 14:09
Hopefully this clarifies, sorry for lack of detain initially. I'm not asking for the final cached image to be AVIF which is what issue https://github.com/mastodon/mastodon/issues/20896 is all about.

I'm referring to the actual incoming pre-cache mime type "AVIF" not being pulled into Mastodon in the first place. So, when adding a link which has:

<meta property="og:image" content="https://example.com/image.AVIF

Mastodon will take JPEG|PNG|BMP|WEBP etc and then do the conversion to whatever the preferred final storage option is (webp currently, I believe).

My FR is to request that AVIF is added to the pre-cache block of images which Mastodon accepts in prior to conversion. E.G. JPEG|PNG|BMP|WEBP|AVIF >> then convert to final storage state.

**Comment by AndrewKvalheim** [comment] 2026-06-24 20:54
Duplicate of #18762?
