### ISSUE TITLE
A system to allow sensitive avatars / banners on profiles

### ISSUE THREAD

**Issue by MirceaKitsune** [mastodon/mastodon#10710] opened 2019-05-05 17:27 UTC
Ever since Mastodon existed, users and admins alike experience frictions over a less obvious source of discord: NSFW avatars and banners. Some users really want to have them, whereas others take it personally if even a small avatar containing something questionable pops up in their timeline. I've decided to open this issue after I was asked to remove the avatar and banner from one of my bot accounts, in my case over something completely harmless which some people still managed to be bothered by; It got me thinking there has to be a better way to handle the problem.

I'd like to suggest the option of allowing profiles to contain avatar and banner graphics hidden behind warnings. I'll post the various ideas I had below, which I encourage people to vote on and discuss.

### Setting NSFW profile art as an user

First users need a way to mark their avatar or banner as sensitive. There are primarily two options:

1. **Allow both SFW and NSFW profile media**

This would be the quick and easy solution. Essentially the user can configure two sets of avatars and banners: A SFW one and a NSFW one.

When a viewer wishes to avoid sensitive content, they see the SFW versions... whereas if the viewer is okay with sensitive media, the NSFW ones are displayed instead. If a NSFW avatar or banner isn't set, SFW ones are displayed to either type of viewer... whereas if no SFW ones are set, they appear empty to users who have chosen not to see sensitive content.

2. **A sensitive flag for profile media**

This method seems more ideal. Just like you have the option to "mark media as sensitive" when adding images to posts, your avatar and banner would also contain such a checkbox.

A banner or avatar marked as NSFW would have the same effect as sensitive media in posts: They will appear either blurred or empty. The viewer must take the decision to reveal them.

### Enabling NSFW profile art as a viewer

Now others need a way to tell Mastodon if they want to see the sensitive media set in other peoples profiles. There are various ways to achieve this:

1. **Follow the "media display" setting**

The best option if practical: Avatars and banners behave just like media embedded into posts. If you go to your preferences ( eg: https://mastodon.social/settings/preferences ) you have a Media Display field with 3 settings:

- Hide media marked as sensitive
- Always show media marked as sensitive
- Always hide all media

When using the first option, NSFW avatars and banners are hidden. When using the second, they are always shown. When using the third choice... well that suggests all media should be hidden, so you should technically be seeing no avatar or banner at all?

2. **A dedicated option**

It might make more sense to have a preference specifically for this scenario. Ideally it can be a per-timeline option rather than a global profile setting, so you may enable or disable them in particular columns: Whether you want to see sensitive content or not depends on you as a person, but also on the location from where you're using Mastodon at that particular moment... as such it would make sense to have an easy way in general to toggle sensitive media.

3. **Per user flag**

Another solution would be to hide sensitive avatars / banners on each profile until the viewer confirms they're okay with seeing them on that particular page. The first time you encounter any user, NSFW media will be blurred or appear empty, and you have an icon allowing you to toggle them on or off (optionally with a Content Warning description). Your decision is remembered per user, so once you confirm you're okay with seeing the NSFW media of any person it will stick forever... unless you click the icon again to revoke it. As a bonus, this could also be used to override hiding sensitive media in posts per user, in case you trust only particular people's sensitive media to be okay for you.

One problem with this approach however is what happens if the user updates their avatar or banner: Should the safety be reset and the viewer asked to enable it again? This might also complicate the system too much, as a whole new list would have to be stored just to keep track of who's profile you've accepted sensitive media from.

**Comment by trwnh** [comment] 2019-05-06 01:30
Subset of / related to #9468

**Comment by trwnh** [comment] 2023-05-16 03:48
Duplicate of #6958

**Closed by trwnh** 2023-05-16 03:48 UTC
Labels: wontfix, suggestion
