### ISSUE TITLE
Allow users to mute instances on their end, not just block

### ISSUE THREAD

**Issue by Mintww** [mastodon/mastodon#14959] opened 2020-10-08 17:11 UTC
### Pitch

Users can already decide to block an instance for just them. This is sometimes a bit excessive, and so I propose a "mute instance" option in addition that simply hides that instance from the public timeline for that user.

### Motivation

Sometimes an instance is full of people constantly churning out content you'd rather not see, but you don't want to fully cut them off (say, you have one beloved mutual on that instance, or the content isn't offensive, just disinteresting to you).

**Comment by Krinkle** [comment] 2020-10-15 06:43
Would this be a standard preference in the account settings, implicitly applied to all clients and interfaces?

Or as a local feature within the main web app, and/of for individual apps to implement locally? I've seen some apps already support local filters and queries on the timelines. I don't know how those current work, though, or if they're efficient.

**Comment by rfkat** [comment] 2023-05-02 09:27
I'd love to see this implemented, as a means to foster seeing content from small-to-medium instances.

With mastodon.social now being the default instance that people are nudged into joining, I want to be able to remove content from such monsters from my timeline. They're destroying the very idea of decentralization, and I do not want to participate in that.

**Comment by takodag** [comment] 2023-07-06 16:40
I'd like to bump this as well, for the following reason: as Mastodon does not provide auto-translate on posts, and I cannot read foreign languages, I should be able to mute instances with a large focus on languages I don't speak.

I don't want to block the instances using foreign languages, as there may be speakers of my language that I don't want to prevent from seeing my content and I don't want to go to the extreme of blocking someone just because we don't share speech, but if I can't read 90% of posts on an instance I don't want to have to see it, either.

**Comment by manedfolf** [comment] 2023-07-20 01:43
Bumping. I silence mastodon.social for all my users because it clutters up the federated timeline. I would prefer to leave this decision in the hands of users, but all they can do is block the instance. Users should have the same controls as instance-level in filtering their content.

**Comment by egypturnash** [comment] 2023-07-20 02:20
I'd love to enable my users who care about the federated timeline to make their own decisions. I really only block the absolute worst stuff that I just do not ever want to have to interact with and leave the federated firehose alone.

**Comment by trwnh** [comment] 2023-07-20 02:39
Duplicate of #7792

**Closed by trwnh** 2023-07-20 02:39 UTC
