### ISSUE TITLE
List copying/transfer between users.

### ISSUE THREAD

**Issue by luukasahola** [mastodon/mastodon#19694] opened 2022-11-03 15:20 UTC
### Pitch

As some users might have hundreds of followed users, the timeline might get messy which might've given inspiration for the lists feature. Users can create and edit lists, export them as CSV files and pin them to the advanced web interface. The main problem for it though is the transfer of the lists between instances and users. The settings don't allow importing lists and lists aren't federated. I don't see a reason why lists would have to be federated (currently not in the ActivityPub standard), but could the transfer/copying of lists be made easier to allow users to create curated lists to their audiences?

### Motivation

Having the ability to transfer/copy lists created by other users could benefit users by introducing them to a bulk of new users without having to go individually follow them.

**Comment by fadookie** [comment] 2022-11-08 20:43
This might be a partial duplicate of https://github.com/mastodon/mastodon/issues/15015 although that one only deals with list .csv import.

**Comment by trwnh** [comment] 2023-05-20 20:15
Duplicate of #18292

**Closed by trwnh** 2023-05-20 20:15 UTC
Labels: suggestion
