### ISSUE TITLE
Clicking on a handle in someone's bio opens a new tab

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [mastodon/mastodon#3185] opened 2017-05-20 19:20 UTC
Shouldn't it also go into the third column, or...?

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment] 2023-05-16 03:26
Duplicate of #1399

**Closed by trwnh** 2023-05-16 03:26 UTC
Labels: bug
