### ISSUE TITLE
Add hashtag to list

### ISSUE THREAD

**Issue by noamross** [mastodon/mastodon#20715] opened 2022-11-14 23:50 UTC
### Pitch

As of 4.0 one can follow a hashtag so that it appears in one's home timeline. I suggest that one also be able to add a hashtag to a list, which would allow people to curate list composed of desired people and hashtags.

### Motivation

This is a natural extension of the current follow feature and would benefit the same people who use lists. Anyone who divides their interests or feeds would benefit from being able to combine these two main ways of creating topical feeds.

**Comment by goldjg** [comment] 2022-11-15 00:50
+1 👍🏻

**Comment by Cassolotl** [comment] 2022-11-15 08:16
Duplicate of *See list of followed hashtags #20132* (from a week ago).

**Comment by Cassolotl** [comment] 2022-11-15 08:17
Duplicate of *Ability to add hashtags to lists #7692*. (Over 4 years old!)

**Comment by burndive** [comment] 2022-11-15 22:03
Yes, please!  I'm sure a client app could implement this as well, or something functionally equivalent, but this would be a great native feature.

**Comment by burndive** [comment] 2022-11-16 18:15
One way to implement this might be to enable users to mark followed accounts as hidden on the Home timeline.  

Perhaps "follow" means by default add to the Home timeline, but on the lists selection screen for an account, you can simply uncheck the Home timeline and assign them to other list(s).  

This wouldn't necessarily change what your profile's "following" page looks like, and it wouldn't affect how instance servers interact with one another, but it would enhance the users' experience by giving us the ability to categorize our feeds in a manageable way.  It would allow us to follow prolific accounts without drowning out (equally or more important) non-prolific accounts in our timeline.

**Comment by noamross** [comment] 2022-11-16 23:00
@burndive I think your request to hide/remove users from the home timeline so as to watch them only in listscis a separate feature from adding hashtags to lists. I note that you can get the same outcome in advanced view and some clients by omitting the home timeline and _only_ viewing lists (one of which might be your "main" list). But the idea may make sense for many cases. I suggest you open it as a separate issue to track.

**Comment by burndive** [comment] 2022-11-16 23:26
Oh, sorry, I think I confused which thread I was on.

**Comment by lightx** [comment] 2022-11-17 18:40
+1 ☝️

**Comment by biasto-bias** [comment] 2022-11-17 18:50
I would also like this very much!

**Comment by rbruchal** [comment] 2022-11-18 14:27
+1 for me.

**Comment by minorsecond** [comment] 2022-11-18 21:40
This would be a great feature!

**Comment by burndive** [comment] 2022-11-18 22:01
Not exactly the same thing, but worth noting for those wanting this feature:
The Fedulab app (Android) allows you to add a hashtag as a timeline column alongside your lists.

**Comment by z3zUK** [comment] 2022-11-19 10:23
This would be super helpful. I've started following a few hashtags and it would be great to only focus on a particular hashtag when you want to, via a list, rather than having the posts diluted through your home feed.

**Comment by biasto-bias** [comment] 2022-11-19 10:27
Yes! And specifically, I would like to add _multiple_ related hashtags to a list. I follow a ton of hashtags that I'd like to stay updated on, and it's not really feasible to check them individually.

Right now, I'm using Feedbro with the RSS feeds to send links to a Discord server, but it's annoying to copy each link from the Discord server to paste it into the search bar when I want to interact with someone's post. I'd like to be able to just scroll down a feed and interact with whichever posts catch my interest, right there in the feed.

**Comment by aserper** [comment] 2022-11-21 00:49
Absolotely! +1! It'd be perfect to add multiple related hashtags to a list, as @biasto-bias says!

**Comment by kerim** [comment] 2022-11-21 02:08
I came here just for this. Or, the reverse, the ability to add a list (or even individual accounts) to a pinned hashtag search in the advanced interface.

**Comment by projectdp** [comment] 2022-11-24 04:00
Does anyone know who might be a good resource to contact or assign regarding this suggested feature?

**Comment by mvasigh** [comment] 2022-11-28 16:14
I'd really like this feature as well. I'm willing to look into contributing it but would want a sense of what the scope of this would be since I am a first time contributor to Mastodon.

**Comment by scruloose** [comment] 2022-12-19 14:35
This would be a major usability improvement. Currently there seems to be a Catch-22 where there's no way to combine Lists and Filters to cut down the volume of your Home feed while still getting the benefit of following hashtags.

Due to issue #7953 if you want to use Lists to cut down the volume on your Home feed, you can't… because "Home and Lists" is *one* filter context, so even once you've added someone to a List, you can't filter them out of your Home timeline (for deduplication) without nullifying the List. Awkward.

As a workaround to that, I have *another* List that's basically "custom home". So high-volume news accounts and such go in whatever topic-relevant List, and the core people whose toots I don't want to miss go in that "custom home" List. Thus every account I follow is in one list or another, and I mostly don't even bother looking at my actual Home timeline anymore. It's a little crude, but it works. Except…

That workaround fails in the case of followed hashtags, because toots pulled in by a hashtag-follow *only* appear in the dupe-riddled firehose of my Home feed, where I'll never see them.

I'd *really* like to see hashtags treated as a first-class "followable" entity, so they show up in the Follows list in my profile (maybe separated into their own block below followed users, whatever) and can be added to Lists, just like users.

**Comment by burndive** [comment] 2022-12-19 17:09
It doesn't solve the issue in the web, but as a client, the Fedilab app for Android allows you to "pin" a hashtag as a column. I use this instead of following hashtags, and I use the same trick of basically ignoring Home in favor of a "main" list (which I've added myself to).

This app is also in the process of implementing a "mute for home" feature that you can apply to lists or individual accounts, thought it seems to have the effect of muting everything involving those accounts (including your own replies and boosts) from your Home timeline. Hopefully they will figure it out, but even in its current state it's by far the most useful client for people who use lists.

**Comment by scruloose** [comment] 2022-12-19 19:29
@burndive thanks for the suggestion, but… I move back and forth between the web interface and a phone app pretty freely, and use desktop primarily, so a workaround that's limited to one client app doesn't really work for me. And pinning a hashtag to its own column leads to unwanted proliferation of columns, rather than letting me sort, say, the news-related hashtags AND news-related accounts I follow all into a List called "news" (and then filter them out of Home… \*sigh\*).

Basically, the problem as I see it is that hashtag following is only half-implemented. Sure, you can follow hashtags, but the functionality is nowhere near what it is for the one and only other thing you can follow: accounts. There's nowhere you can look to see what hashtags you're following, *and* you can't put them in Lists. That makes no sense, and really *really* shouldn't be left up to client apps to work around.

Any "followable entity" — whether it's an account, a hashtag, another instance's `/public/home` timeline [maybe](https://github.com/mastodon/mastodon/issues/21500#issuecomment-1356353794) some day, or whatever — really needs to have the above-mentioned functionality built into the core implementation before it can be considered "working".

/rant

**Comment by JesseWeinstein** [comment] 2022-12-21 13:42
> As a workaround to that, I have _another_ List that's basically "custom home". So high-volume news accounts and such go in whatever topic-relevant List, and the core people whose toots I don't want to miss go in that "custom home" List. Thus every account I follow is in one list or another, and I mostly don't even bother looking at my actual Home timeline anymore. It's a little crude, but it works. Except…

I wanted a tool to do that (but without the topic-specific lists), just with a "everybody I follow except for these accounts" list, and I didn't see any such tool, so I hacked one into https://github.com/magicalraccoon/tootstream (although I haven't published the branch yet). I'll update this comment when I do.

**Comment by georgecz** [comment] 2022-12-21 14:07
At the risk of further complicating the issue, what are the possibilities of being able to construct a feed on user-determined conditions and filters, of which a list of follows and hashtags would be just a specific case?

**Comment by scruloose** [comment] 2022-12-22 15:47
@georgecz  I agree completely. I'd go even further, to be honest. I can't imagine why message-handling rules that are all variations on `(UNTIL ExpiryTime) IN CONTEXT foo IF FIELD bar MATCHES PATTERN baz DO ACTION blah` are being treated as **four** unrelated features, all half-implemented, scattered through the UI and Preferences.

List, Filter, Mute, and Block are all specific cases of the above, and it seems to me that it would be *less* complicated to consolidate them all into one UI page for "Filtering, Blocking, and Sorting" (replacing/extending the Lists page) that lets the user view, add, and edit their custom rules the way a webmail system does it. Want to see the list of everyone you have Muted? That's just a filtered view of your table of rules. (Currently, if there's anywhere to see a list of your Mutes, Blocks, or both, I haven't been able to find it.) What users, hashtags, (and keywords?) are sorting into `List A`? Just another filtered view of your table of rules. Want to MOVE matching toots to List A instead of COPY so you don't have to create a second rule specifying the **exact same** conditions in the **exact same** context to filter the dupes out of Home? Trivial.

Not only should "Home" and "Lists" be different contexts, but *each* List should be a separate CONTEXT (with "all Lists" as an option). Keyword matching should support *at least* basic wildcards, and rules with more than one condition should *at least* allow "trigger when ANY condition matches" vs "trigger only when ALL conditions match". (Personally, I'd like to be able to write arbitrary Boolean logic like `If (Condition A OR Condition B) AND NOT Condition C` for my `COLLAPSE`, `HIDE`, and `MOVE/COPY to List` rules… but I can see that might be pretty niche.)

Obviously not every CONTEXT → CONDITION → ACTION permutation makes sense, but I'd think starting with consistent, flexible, and general, then disabling the nonsensical, unsupported, and unsafe combinations would be easier on users **and** devs in the long run.

**Comment by raphmim** [comment] 2023-01-05 00:44
+1 on this! 

Following hashtags is a great (and imo pretty unique) feature, but I find that it's rendered largely useless without being able to add them to lists. 

This also feels like a relatively low-effort feature to implement, so hoping it gets added natively to Mastodon!

**Comment by john94501** [comment] 2023-01-11 00:26
+1 on this.

**Comment by sami-huvilanet** [comment] 2023-01-25 01:53
Those public lists as '**Who to follow**' -recommendations could then  also be shown collectively as 'Top Recommendations' based on an open and thoughtful algo, which could –for instance– measure the amount of combined followers of those who recommend.  

Especially many (not-too-geeky) and often impatientish new users need easy guidelines & tips to start their DECENTralized Some-journey, without excessive floundering and frustration.

**Comment by JeedPi** [comment] 2023-02-16 23:28
+1 to that. I have theme-based list, such as "Automation", and it would be great to add a hashtag like #HomeAssistant to this list. I could also create a list following a few hashtags relate to lists I have (Japan, Tech...), and from this list, add the most interesting accounts to the theme-based list. 

Lots of potential. Crossing fingners :)

**Comment by julesbl** [comment] 2023-03-05 11:35
I would like this

**Comment by trwnh** [comment] 2023-05-19 06:50
Duplicate of #7692

**Closed by trwnh** 2023-05-19 06:50 UTC
Labels: suggestion
