### ISSUE TITLE
Youtube videos always start at the beginning despite a time specified as a parameter in URL

### ISSUE THREAD

**Issue by sevan** [mastodon/mastodon#22238] opened 2022-12-11 19:50 UTC
### Steps to reproduce the problem

1. Play a youtube video on the youtube website
2. right click on video and select "copy video url at current time"
3. post the link on Mastodon
...

### Expected behaviour

When you press play on the video embedded in a post, it should start at the time specified

### Actual behaviour

Video always starts at the beginning, despite the ?t=123 parameter

### Detailed description

It looks like the time parameter is ignored on playback. Oddly, the parameter is taken into account on generating the still image for the post, despite, it will always play from the beginning. 

### Specifications

Not a new issue, but observed on Mastodon 3.5.x and newer.

**Comment by BrunoViveiros** [comment] 2023-08-15 14:07
Can I take this one?
It also relates to #9944

**Comment by vmstan** [comment] 2024-01-01 16:07
Closed as duplicate of #9944

**Closed** 2024-01-01 16:07 UTC
Labels: bug
