### ISSUE TITLE
Make all hashtag suggestions in Pascal Case.

### ISSUE THREAD

**Issue by rkingett** [mastodon/mastodon#24554] opened 2023-04-16 23:40 UTC
### Pitch

I'd like the software to suggest hashtags in Pascal case exclusively. [I'm aware this PR was merged to try and fix a similar issue](https://github.com/mastodon/mastodon/pull/16460) but there is still a constant problem of people having to fight with the software to do hashtags in pascal case or CammelCase, especially when they would like to use a hashtag suggestion.

When a user wants to use a hashtag in a suggestion, that hashtag should always appear in Pascal case. This helps people wanting to make their content easier to read and it would help other Blind users of Mastodon and the wider Fediverse.

If a user selects from a hashtag suggestion I'd like to see that hashtag in Pascal Case.

### Motivation

Even with the above PR, people are frustrated because they want to use the hashtag suggestions but also want to make the content accessible to a bigger audience.

Pascal Case is where every word in a hashtag is capitalized. CammelCase is a practice where the first word in the hashtag is not capitalized, but all other words in the hashtag are capitalized.

PascalCase across the whole ecosystem would be easier to read on mobile screens and it would help people read really long hashtags. the Fediverse is extremely popular with the Blind/VI community and this would only make it easier to use the software.

**Comment by ClearlyClaire** [comment] 2023-04-17 12:27
(Kind of a) duplicate of #20267

**Closed by ClearlyClaire** 2023-04-17 12:27 UTC
Labels: suggestion
