### ISSUE TITLE
Timestamps on edited toots are shown beyond 23:59

### ISSUE THREAD

**Issue by stevepdp** [mastodon/mastodon#20828] opened 2022-11-15 22:30 UTC
### Steps to reproduce the problem

See the following two toots:

- [https://mstdn.social/@stevepdp/109324712532921940](https://mstdn.social/@stevepdp/109324712532921940)
- [https://mstdn.social/@stevepdp/109293519494228479](https://mstdn.social/@stevepdp/109293519494228479)

![Capture](https://user-images.githubusercontent.com/1271004/202038669-799c58b1-7dd1-4c76-b5e0-c8ad52560784.PNG)
![Capture2](https://user-images.githubusercontent.com/1271004/202038670-bd6060d8-f1ca-4cd9-94ce-fd1db6af6789.PNG)

### Expected behaviour

I would expect the 24 hour clock to roll from 00:00 to 23:59

### Actual behaviour

I was shown a timestamp that went beyond 23:59

### Detailed description

You'll notice that on both the basic and advanced UI modes, the edited timestamps shown are 24:04 and 24:07 respectively.

I would expect them to read 00:04 and  00:07 respectively, but I can't honestly recall if it was infact at those times past midnight that I made the changes.

### Specifications

Mastodon v4.0.1 (mstdn.social)
Browser: Brave [Version 1.45.123 Chromium: 107.0.5304.110 (Official Build) (64-bit)]

**Comment by ineffyble** [comment] 2022-11-15 22:54
@stevepdp We've been looking into this recently. What locale is your browser set to? (e.g. what language and region settings are you using?)

**Comment by ineffyble** [comment] 2022-11-15 23:29
Hmm, interesting. From the chat in the Discord, the date/time formatting _should_ be handled by a browser-side function according to locale. But if locale was the issue, we'd see a lot more people raising bugs.

**Comment by Onatcer** [comment] 2022-11-16 00:51
I just experienced this bug too, with a non-edited toot/post. Im in GMT+1 and my browser language is set to english. Browser is Arc (Chromium-based).

But it looks like the bug is related to the Mastodon "Interface language" setting. I had it set to "English" when the problem appeared. When I changed it to German (which matches the timezone i'm in), the time showed correctly. 

Tested this on mastodon.social (v4.0.2).

**Comment by abochmann** [comment] 2022-11-19 00:03
I see the same. The timestamp goes from 24:59 to 01:00
![image](https://user-images.githubusercontent.com/9380844/202822460-31f5dd7d-8886-4162-83f6-41f84f84e963.png)
Browser is Vivaldi (Chromium), and configured to use the system time format (Windows, German).

**Comment by abochmann** [comment] 2022-11-19 13:12
This seems to be a Chromium problem - the timestamp looks fine in Firefox on the desktop and mobile.

This toot can be used as a test case (currently shows 24:24 in all Chromium browsers I tried): https://mastodon.infra.de/@galaxis/109367384829198550

**Comment by Cassolotl** [comment] 2022-11-28 09:41
Duplicate of *Timestamp issue with UI lang + browser lang #18414*?

**Closed** 2023-05-19 06:46 UTC
Labels: bug
