### ISSUE TITLE
Media Library : Easy to use interface for media items uploaded by a user

### ISSUE THREAD

**Issue by ranjithrajv** [mastodon/mastodon#16593] opened 2021-08-10 07:46 UTC
### Pitch

Media Library, a media management feature that enables a user to search/sort already uploaded media from their account and to add new media items, with easy to use interface.

### Motivation

- Helpful for reusing already uploaded media in new posts.
- Helps users to find all the media uploaded by them at one place.

#### Other fediverse projects implementing this

- Misskey : https://github.com/misskey-dev/misskey#misskey-drive
- Peertube, Funkwhale, Pixelfed etc. are by-design media-centric projects that have media management built-in.

**Comment by trwnh** [comment] 2024-03-19 22:54
Duplicate of #2317

**Closed by trwnh** 2024-03-19 22:54 UTC
Labels: suggestion, area/web interface
