### ISSUE TITLE
Hashtag search broken due to focus on suggestions at expense of original search term

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon#17494] opened 2022-02-09 22:59 UTC
### Steps to reproduce the problem

1. Search for hashtag "nintendo" on instance mastodon.online
2. Note none of the results are "nintendo", just many suggested variations on it
3. Scroll through several pages, lots more hashtag suggestions but none of them are "nintendo" 
...

![hashtagexample](https://user-images.githubusercontent.com/75383929/153304463-37e3bbe4-1eb4-40c4-a117-73fd968ee5ec.png)

### Expected behaviour

The hashtag I searched for ("Nintendo") should be top of the list of suggestions

### Actual behaviour

The hashtag I searched for is absent from the suggestions list

### Specifications

Mastodon v 3.4.6

Ubuntu Linux, Firefox 96

**Comment by Gargron** [comment] 2022-02-10 00:21
That's weird. It should prioritize exact matches. I'll look into it.

**Comment by FediVideos** [comment] 2022-02-10 20:15
Thank you! :pray:

**Comment by FediVideos** [comment] 2022-05-07 14:40
This bug still seems to be happening, but affects different tags?

Also, it feels like the suggestions are breaking other search functions and refusing to show any results if the user doesn't select a suggestion from the list.

A new user contacted me saying they can't get a search result for tag "disability" (post is here https://mstdn.social/@neurodivergentgeek/108261025588500103).

I can confirm this as I have an account on the same instance mstdn.social, have attached screenshot.
![disability](https://user-images.githubusercontent.com/75383929/167258817-f556d8fd-3fc4-43c2-9b51-0b5869dcb13d.png)

Also, if you click on the "posts" tab of the search results without selecting a tag suggestion, it says there are no posts at all. Surely it should be showing posts with the tag the user originally searched for?
![disability2](https://user-images.githubusercontent.com/75383929/167258903-87cb16fe-0e79-46d2-863d-aafdf677858c.png)


mstdn.social is running 3.5.2glitch

**Comment by FediVideos** [comment] 2022-07-27 15:05
Any progress on this bug? I've had more people contact me because this bug is stopping them finding stuff on Masto due to the suggestions blocking results for the original term.

I can verify this bug is still present, I just tried searching for hashtag "food" on mas.to (Masto 3.5.3) and mstdn.social (3.5.3 Glitch), neither of which listed this tag in the suggestions. And because the suggestions prevent access to the results, I'm unable to see results for this tag on these instances.

I also tried "food" on mastodon.online and it worked fine, by the way. Have you got some fix being tested on that instance?

![foodsearch1](https://user-images.githubusercontent.com/75383929/181281764-6372701c-4c57-453d-a4e9-3de103fe46c3.png)
![foodsearch2](https://user-images.githubusercontent.com/75383929/181281792-0f46c354-ed1f-42dc-9855-d66a7243e251.png)

**Comment by Jab2870** [comment] 2022-07-27 15:12
https://mastodon.technology/@archie2870/108719468767466407

Seems like this issue I'm having might be related. When trying to exclude a tag from a list, I cannot select blockchain

**Comment by Cassolotl** [comment] 2022-10-08 16:15
I'm having this issue today from eldritch.cafe for #poll.

**Comment by ashemedai** [comment] 2022-11-05 07:24
So I ran into this issue myself this week for a number of hashtags. I could understand if the tag might not have been used recently, but that's not the case (searched on #rust - it's halfway down or so through 125 results):
![image](https://user-images.githubusercontent.com/610865/200107878-fd76123d-b613-4a2b-8233-262cebd683bf.png)

And I think this problem also cascades to the advanced web view additional hashtag feature. If I want to add an additional hashtag, I get a dropdown of all wildcard matches, but not my exact match. Probably because the dropdown limits the hashtag search result to X items.

**Comment by ashemedai** [comment] 2022-11-05 08:11
The relevant code snippet seems to be located at https://github.com/mastodon/mastodon/blob/c4b92b1aee27a813e24395d43e265cc02a8fe9a3/app/javascript/mastodon/features/compose/components/search_results.js#L113-L124

Ruby and JavaScript are not my forté, but this seems a very simplistic search that simply returns things as we get them. Unless I am missing something from a lower layer that's powering this.

**Comment by afontenot** [comment] 2022-11-07 21:18
Probably worth mentioning that this issue isn't consistent across servers. One user on ecoevo.social reports that all hashtags they've tried seem to work correctly and show the exact hashtag as the top result. However when I try the exact same hashtags on mastodon.social they don't work (they show five results that do not include the exact match).

**Comment by ClearlyClaire** [comment] 2022-11-08 09:46
This is not a client-side issue but a server-side issue. It's also caused by the ElasticSearch code path, which explains why it doesn't occur on all instances.

The culprit is `TagSearchService#from_elasticsearch` but from my limited understanding of ElasticSearch, I do not understand why it does not behave as intended.

**Comment by afontenot** [comment] 2022-11-08 10:23
Something else which is not quite the same issue is that sometimes the search doesn't work at all rather than returning the results in unexpected order.

For instance currently on mastodon.social, I can see that `#mytopshelf` is a trending hashtag. However, when searching for this hashtag, I see no results of any kind.

**Comment by FediVideos** [comment] 2022-11-09 22:58
The suggestions are still broken.

Someone just complained to me they were unable to search for hashtag "algorithm" on mastodon.social

Just tried this on several other instances:
mstdn.social - Incorrect, "algorithm" off the page at position 20
mastodon.online - Correct, with "algorithm" top
tech.lgbt - Correct
social.growyourown.services (two user instance!) - Incorrect, only two suggestions and neither were "algorithm"

**Comment by FediVideos** [comment] 2022-11-09 23:01
Just wondering, is it really worth keeping the hashtag suggestions at all if they are blocking people from seeing the tags they want?

The combination of incorrect suggestions plus the misleading numbers (0 for every result) has made some new people think hashtag search is totally broken.

**Comment by ClearlyClaire** [comment] 2022-11-10 08:07
@FediVideos this is still the same issue, we already know it depends on servers because it depends on whether ElasticSearch is enabled

**Comment by thypon** [comment] 2022-11-12 14:49
Since this is affecting many instances, I made a quick fix applicable with TamperMonkey.

https://gist.github.com/thypon/5078cd48c2c73b99293e1e22d17ec7c4

With this quick fix, whenever you search for a hashtag, that hashtag will be added to the top of your search.

**Comment by FediVideos** [comment] 2022-11-17 13:31
Any updates on this? Any 

> @FediVideos this is still the same issue, we already know it depends on servers because it depends on whether ElasticSearch is enabled

Okay, thanks for clarification.

Is there any chance of switching off hashtag suggestions until this is fixed?

I'm still getting users asking why they can't see the tag they're searching for, just got one a few minutes ago. (The one just now is on mastodon.social by the way.)

**Comment by FediVideos** [comment] 2022-11-17 13:42
...and again, just had a couple more people asking about tags not being in suggestions, again on mastodon.social.

**Comment by tyrosinase** [comment] 2022-11-17 17:04
This has gotten so much worse with the Twitter influx, because they're so used to putting on twenty variations of a hashtag in desperation. Really common hashtags like "fiber" or "cosplay" are just unsearchable now (barring the url-editing workaround, which doesn't help in all situations).

**Comment by FediVideos** [comment] 2022-11-18 14:49
How about just refomatting the suggestions page so that the original term is in large font with the message "Click here for results from #Gardening" and then below that in smaller letters would be "Did you mean these similar hashtags?" and then the elasticsearch suggestions for that tag?

That way, if the elastic search suggestions are broken people can easily ignore them and go straight to the tag they searched for.

**Comment by tyrosinase** [comment] 2022-11-18 14:52
It's not just the suggestions page though - it's also the box where you add more tags to an existing tag column, and I think a couple other places.

**Comment by ashemedai** [comment] 2022-11-18 15:57
@ClearlyClaire It's been ages since I did any proper Elasticsearch work, so caveat emptor. I annotated the appropriate code. If I have to hazard a guess at the most likely culprit, `most_fields` with the `operator: 'and'`. Especially when I read [this warning in their documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#type-cross-fields).

Haven't had time to set up an Elasticsearch node with some test data.

```ruby
class TagSearchService < BaseService
  def call(query, options = {})
    @query   = query.strip.gsub(/\A#/, '')    # e.g. #mastodon -> mastodon
    @offset  = options.delete(:offset).to_i   # paging
    @limit   = options.delete(:limit).to_i    # paging, fetch max [limit] rows
    @options = options

    results   = from_elasticsearch if Chewy.enabled?
    results ||= from_database

    results
  end

  private

  def from_elasticsearch
  query = {
      function_score: {                       # The function_score allows you to modify the score of documents that are retrieved by a query.
        query: {                              # query passed to function_score
          multi_match: {                      # multi-field match query
            query: @query,                    # hashtag without hash (#), e.g. 'mastodon'
            fields: %w(name.edge_ngram name), # Ruby syntax to create an array of strings, ['name.edge_ngram', 'name']
            type: 'most_fields',              # most_fields is used to query multiple fields that contain the same text analyzed in multiple ways, e.g. edge ngrams - setting the second field to the original query string should push it to the top of the list
            operator: 'and',                  # most_fields is field-centric, it generates a match query per field (2 here: name.edge_ngram, name) - this means that ALL terms must be present in a single field for a document to match
          },
        },

        functions: [                          # functions to apply to the function_score query results
          {
            field_value_factor: {             # The field_value_factor function allows you to use a field from a document to influence the score.
              field: 'usage',                 # field extracted from the document to be used by field_value_factor
              modifier: 'log2p',              # add 2 to the field value and take the common logarithm
              missing: 0,                     # if 'usage' not present in the document, set value to 1 to be used by log2p -> [0.3010..1]
            },
          },

          {                                   # decay functions score a document with a function that decays depending on the distance of a numeric field value of the document from a user given origin
            gauss: {                          # normal decay function, since origin is not given, it is set to default of 'now' for date fields
              last_status_at: {               # field name to apply normal decay function to
                scale: '7d',                  # defines the distance from origin (now) + offset (14d) at which the computed score will equal the 'decay' parameter (21d)
                offset: '14d',                # only compute the decay function for documents with a distance greater than 14 days
                decay: 0.5,                   # documents at the distance 'scale' will be scored 0.5
              },                              # IOW, documents from now - 14d ago score 1, documents that are 21d away score 0.5
            },
          },
        ],

        boost_mode: 'multiply',               # query score and function score is multiplied
      },
    }

```

**Comment by rhersel** [comment] 2022-11-18 17:48
I support this change request. Just try to search for #linux, #floss, #opensource. You will not find the search term without endless scrolling. Approx. 2 month ago, the search behavior was different (on mastodon.social). The exact search term was not on top of the list, but nearby. The current search does not what it is supposed to do: find the search term.

**Comment by FediVideos** [comment] 2022-11-19 17:03
Even more new people have been asking today why they can't search for the hashtags they want, sending me screenshots ofthis problem.

Could the hashtag suggestions please be switched off (or at least made optional) until it is fixed? The current state is acting as a roadblock on using Mastodon because there is no easy or obvious workaround.

**Comment by afontenot** [comment] 2022-11-20 05:10
One potential very quick workaround for instances using elasticsearch would be to disable searching for *non-approved* hashtags. No, this isn't a *great* workaround, but in the "new post" hashtag search on mastodon.social, I can search for both `#mastodon` and `#lgbt` and **both** show up in the four results. That's because the dropdown only shows approved hashtags. 

The case where it's completely broken is searching in the search bar, because this returns non-approved hashtags.

On instances where all the common hashtags are already admin approved, switching to only searching for approved hashtags would at least make the search somewhat usable.

**Comment by FediVideos** [comment] 2022-11-20 21:03
Why not just switch off suggestions?

Why are the suggestions so important that it's okay to ruin the basic search function?

People usually just want to see the result of what they look for, the suggestions are sort of a secondary thing usually?

**Comment by naught101** [comment] 2022-11-27 09:57
I'm not sure if this is the place, I couldn't find an existing, but aside from the exact march thing, it would also be good if the remaining tags were sorted by most used first.

The search on mastodon.social is always full of irrelevant one-off tags that are never likely to be used again, and the first page or two often only contain 3-4 tags with more than 2 uses in he last week. It would be good to bump those to the top, to maximise the likelihood of popular tags being meaningfully reused.

**Comment by afontenot** [comment] 2022-11-27 10:03
> it would also be good if the remaining tags were sorted by most used first.

They're supposed to be (roughly). The search is broken because of the elasticsearch configuration issue described above.

**Comment by vitorgrs** [comment] 2022-11-28 07:08
I believe is the same problem I'm having, though the solution here is different. At our instance on bolha.us, we have set to automatically approve hashtags only recently, and thus, these prior hashtags that was in use prior to that doesn't show on search

<img width="660" alt="image" src="https://user-images.githubusercontent.com/9909446/204214763-229a89c9-83ad-4547-ace9-382acffb66b0.png">

As you can see, it's already enabled to show on search  
<img width="653" alt="image" src="https://user-images.githubusercontent.com/9909446/204214986-e8ffb736-db2b-4029-84a2-d5fc198899fe.png">

The solution that I found out, is to disable the option to show on search, and enable again, then it works.

The thing is, I would need to do that on over 700 hashtags... 

Any tips?

**Comment by sparr** [comment] 2022-12-01 23:47
This is occurring right now for some but not all users on mastodon.social searching for #Ukraine, which produces many #UkraineWithAdditionalWords suggestions, none of which are nearly as active as #Ukraine itself.

**Comment by velw** [comment] 2022-12-13 06:53
> That's weird. It should prioritize exact matches. I'll look into it.

Is there any update on when this will be addressed? Mastodon intentionally steers users to use hashtags exclusively for finding content on topics of interest. That searching for them doesn't work correctly is a problem. Am surprised to see it hasn't been addressed 10 months after it was flagged.

**Comment by ClearlyClaire** [comment] 2022-12-13 07:48
There's a potential fix here: #21315. It needs review/testing, though.

**Comment by mudomau** [comment] 2022-12-13 18:02
I think this might be related?

https://github.com/mastodon/mastodon/issues/19944

I noticed searching for some terms returned no results, but the results appeared when I typed the term into the URL

**Comment by FediVideos** [comment] 2022-12-14 21:54
> > > There's a potential fix here: #21315. It needs review/testing, though.
> > 
> > 
> > This just injects an exact match as the first result, though, right?
> 
> Yes. That's what the current issue is mainly about though.

Yes! If you can make the initial search be hardwired to appear first, that will solve most of the issues :+1: 

Just had more new people today asking why they can't search for the term they typed in, saying that it is putting them off using Masto. If their searches are guaranteed to appear first, they will be happy.

**Comment by afontenot** [comment] 2022-12-14 22:55
> With all due respect, you have to let people search for whatever they want. Even if you're not sure about exact matches, other people will be sure.

I didn't mean this in a judgmental way, in that Mastodon should dictate what users ought / ought not to be searching. I meant it in the "sometimes there really are no good results for the precise search term" sense. If someone searches for a hashtag because they want to view posts with that hashtag, that seems to me like a different thing than searching for a hashtag because they want to see matching hashtag search terms. The Mastodon search interface by default does the latter, and I don't think anyone has proposed changing that?

I think it does make sense to make sure that an option to search for posts using the exact search term is always present. I think an exact match should be scored very highly. But I can't think of any *inherent* reason that it should always be listed first. If other search terms score better using the scoring function Mastodon applies, then they just do. If that yields unexpected results then that indicates a problem with the scoring function, IMO. If *no one* has ever used a hashtag before, then users are just going to be disappointed when they click on it in the search and see zero posts.

It sounds like the issue you want fixed is that people can't easily use the Mastodon web interface to find recent posts using a *specific* hashtag - and the issue I want fixed is that hashtag search is completely broken on instances using Elasticsearch. I don't have any particular need for the latter bug to be addressed in this Github issue, although it has be the focus of much of the conversation.

**Closed** 2022-12-15 17:41 UTC
Labels: bug

**Comment by FediVideos** [comment] 2023-02-16 02:56
Thank you to all the developers who fixed this, great work, well done!  :clap:
